### ISSUE TITLE
Missing .stfolder file

### ISSUE THREAD

**Issue by sebastianbauer** [syncthing/syncthing-android#1000]
There seem to be some tools that cleanup empty files like .stfolder. Any chance Syncthing can create the .stfolder files read-only?

### Version Information

    App Version: 0.10.1
    Syncthing Version: v0.14.41
    Android Version: Android 6.0

**Comment by AudriusButkevicius** [comment]
Sorry, but you should go back and talk to the tool that deletes empty files, it's not really a problem on our side.

**Comment by sebastianbauer** [comment]
I agree, thanks.
