### ISSUE TITLE
Crash on CyanogenMod

### ISSUE THREAD

**Issue by pihug12** [syncthing/syncthing-android#1001]
Last versions are affected by this CyanogenMod bug: https://issuetracker.google.com/issues/64434571

See:
* [Twidere-Android/issues/963](https://github.com/TwidereProject/Twidere-Android/issues/963)
* [tasks/issues/577](https://github.com/tasks/tasks/issues/577)
* [Slide/issues/2555](https://github.com/ccrama/Slide/issues/2555)
* [Signal-Android/issues/7171](https://github.com/WhisperSystems/Signal-Android/issues/7171)

My device (Kindle Fire HD 7" on CM12.1) reboots itself after updating Syncthing Android to 0.10.1.

Updating "build tools" to 26.0.3 or 27.0.1 could fix it.

**Comment by Nutomic** [comment]
I didn't know that this issue was affecting Syncthing. Thanks for letting me know!
