### ISSUE TITLE
Syncthing Configuration Backups Disappear 

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#1002]
I'm having a case of phantom-configuration-deletion-action syndrome. 😝

Syncthing for Android (0.12.2 on ARM64) configuration files I've exported delete automatically from my file system upon resetting the app via my System Settings < Apps < Syncthing  < Storage < Clear Data. Syncthing used to never delete the contents of that folder after a reset.

Android 8.x Oreo
HTC U11 US-Unlocked

**Comment by AudriusButkevicius** [comment]
Clear data is handled by the OS rather than syncthing itself, so most likely something changed how android works.

**Comment by Catfriend1** [comment]
Clear data does not affect paths outside the /Android/data int-sdcard folder. Currently, syncthing app stores backups at /backups/syncthing on the int-sdcard. So this should be no issue anymore.
