### ISSUE TITLE
No permission to read SD card

### ISSUE THREAD

**Issue by maxomaniak** [syncthing/syncthing-android#1004]
I added a folder location I want to sync, the folder is on the external SD card of my phone. 
Syncthing says it has no permission to see the files in that folder. 
I expected a pop-up that asks for permissions to read/write on external SD.

### Version Information

    App Version: 0.10.2
    Syncthing Version: 0.14.42
    Android Version: Android 7.1.1

**Comment by AudriusButkevicius** [comment]
Please search existing issues.
