### ISSUE TITLE
Crash relating to UI

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing-android#1006]
App Version: 0.10.1 F-Droid
    Syncthing Version: v0.14.41
    Android Version: Android 5.0.2

I had Syncthing open but not the web GUI (in the app or browser). I wasn't interacting with the app at all. After a while I received a notification from Syncthing that it crashed, producing the following log data:
[ST crash.txt](https://github.com/syncthing/syncthing-android/files/1646872/ST.crash.txt)

**Comment by AudriusButkevicius** [comment]
Yeah, sadly this is just a partial log.

**Comment by imsodin** [comment]
Is the reason for this partial log problem known? This isn't the first time this happens.

**Comment by Catfriend1** [comment]
Maybe some out of memory problem?
@ProactiveServices Problem still present in recent version 0.10.8? Closed until Logs are provided.
