### ISSUE TITLE
Recurring Usage Reorting dialog (v.0.10.03)

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing-android#1009]
Steps:

1. Open Syncthing
2. Usage Reporting Dialog appear
3. Accept/Reject it
4. Restart as prompted
5. After a few seconds the prompt appears again

Restarting syncthing doesn't change anything - the UR prompt keep popping up
Setting the UR status via webUI, has no effect - the prompt keep appearing.

Curiously enough, the issue has appeared for me only after updating to v.0.10.03 (which mentions https://github.com/syncthing/syncthing-android/commit/08bf74d7aa523a91ac393299ff19463ea9fc85d7 in the changelog)

### Version Information

App Version: 0.10.03
Syncthing Version: v0.14.43
Android Version: Android 8.0; 8.1

**Comment by cornclaw** [comment]
I can confirm that this is happening as well on Android 7.0

**Comment by Craeckie** [comment]
Same issue on Android 6.0.1 with same version, just that the dialog appears many times on top of each other, so the app is almost unusable. Switching off the internet connection doesn't help.

**Comment by aamadorj** [comment]
Same here: PH-1 running AOSiP 8.1.

**Comment by vsespb** [comment]
Same. Unusable. Xiaomi Redmi 4

**Comment by imsodin** [comment]
As you can see right after the original report, the issue has already a fix proposed in PR #1010. Please refrain from more "same here" comments. They don't help, they just create noise.

**Comment by Flouss** [comment]
As a workaround until this gets fixed, just open the Web GUI. The usage report dialog doesn't appear there.

**Comment by Catfriend1** [comment]
Workaround: open data/data/com.nutomic.sync..../files/config.xml with root explorer and set urseen to 3 and uraccepted to 2. Then the dialog doesnt appear anymore.

**Comment by narbehaj** [comment]
Same issue here, after updating it to latest release Jan 26. Reporting dialog shows up repeatedly. LG-V20 Android 7.0

**Comment by licaon-kter** [comment]
Same here, Play version, Android 5.1.1.

The WebGUI helps, albeit it always has a dialogue on the top of the page with "settings need saving..."

**Comment by DrSchnagels** [comment]
Confirmed, 1+ 5 Oreo 8.0, super annoying lol.
Please fix asap, im in the hospital and i need to sync my pictures.
thanks!

**Comment by alldigital** [comment]
@Catfriend1 your hack did the trick. Thanks.

**Comment by AudriusButkevicius** [comment]
So I am going to lock this, as "me too" doesn't add any value.
