### ISSUE TITLE
Endless loading, reboot does not help

### ISSUE THREAD

**Issue by vsespb** [syncthing/syncthing-android#1011]
Endless loading, reboot does not help.
Log file loading stuck too.

What I did before that happen: I started editing advanced folder properties, clicked on enable fs watcher checkbox, went to next field, but web page jump and I started typed in wrong field. Thus I pressed "back" button and did not save the settings (including fs watcher). So I can say I did nothing at all (unless advanced settings saved without save button).

Latest SyncThing (playmarket shows 0.10.4; SyncThing itself does not show anything).
Xiaomi Redme 4, Android 6.0.1, MIUI 8.0

![screenshot_2018-01-28-23-10-12-069_com nutomic syncthingandroid](https://user-images.githubusercontent.com/1210230/35486812-7a7a6c54-0484-11e8-908b-8f954085e801.png)

![screenshot_2018-01-28-23-09-08-678_com nutomic syncthingandroid](https://user-images.githubusercontent.com/1210230/35486811-78d04b30-0484-11e8-987d-93924d870ed7.png)

log file: 
```
[SST4V] INFO: TCP listener ([::]:22000) starting
[SST4V] INFO: KCP listener ([::]:22020) starting
[SST4V] INFO: Completed initial scan of readwrite folder "ScreenShots" (1911b-k7xvb)
[SST4V] INFO: Completed initial scan of readwrite folder "[**cut**]" (6333n-d2l1z)
[SST4V] INFO: Device [**cut**] is "[**cut**] " at [tcp4://192.168.[**cut**],tcp4://[**cut**]]
[SST4V] INFO: Device [**cut**] is "Redmi 4" at [dynamic]
[SST4V] INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
[SST4V] INFO: GUI and API listening on 127.0.0.1:8384
[SST4V] INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
```

during this http://127.0.0.1:8384/ from android device is "connection refused". and it does not connect to peers, according to logs.

**Comment by Nutomic** [comment]
Can you use logcat to retrieve logs and post them?

**Comment by vsespb** [comment]
Hi. Today I rebooted phone again, and it start working as usual.
So in total,
1st device reboot - did not help, endless loading.
2nd device reboot - fixed problem.

**Comment by Shemzone** [comment]
Hi fellows!
Same endless loading here since update to Oreo 8.1 (LineageOS) on OnePlus One.
It worked like a charm before on Nougat 7.1.1 (Lineage OS as well, same device).
I rebooted a bunch of times, still no luck.

I got this in logs:
Log Android
--------- beginning of main
03-23 22:19:54.990 W/Adreno-EGL(17038): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
03-23 22:19:59.478 W/Adreno-EGL(17038): <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE

Log Syncthing (to long to display within this post)
[logsyncthing.txt](https://github.com/syncthing/syncthing-android/files/1844307/logsyncthing.txt)

Hope to get it work as before.

Regards

**Comment by rmueller83** [comment]
Here is a log file. I removed some "Polling web gui" entries for clarity.
[syncthing.txt](https://github.com/syncthing/syncthing-android/files/1853235/syncthing.txt)

**Comment by AudriusButkevicius** [comment]
It crashes because of some sort of security features of the OS, as syncthing can't read the hostname of the device.

**Comment by AudriusButkevicius** [comment]
Scratch that:

```
SyncthingNativeCode: SIGSYS: bad system call
03-27 19:59:19.425 27023-0/? E/Go: SIGSYS: bad system call
03-27 19:59:19.426 26951-27026/com.nutomic.syncthingandroid W/SyncthingNativeCode: PC=0xb16b0988 m=6 sigcode=1
03-27 19:59:19.427 27023-0/? E/Go: PC=0xb16b0988 m=6 sigcode=1
03-27 19:59:19.428 26951-27026/com.nutomic.syncthingandroid W/SyncthingNativeCode: goroutine 1 [syscall]:
03-27 19:59:19.428 27023-0/? E/Go: goroutine 1 [syscall]:
03-27 19:59:19.430 26951-27026/com.nutomic.syncthingandroid W/SyncthingNativeCode: syscall.Syscall(0x13a, 0x1, 0x0, 0x4005, 0x0, 0x0, 0x0)
03-27 19:59:19.430 27023-0/? E/Go: syscall.Syscall(0x13a, 0x1, 0x0, 0x4005, 0x0, 0x0, 0x0)
03-27 19:59:19.431 26951-27026/com.nutomic.syncthingandroid W/SyncthingNativeCode: 	/home/felix/Downloads/go/src/syscall/asm_linux_arm.s:17 +0x8 fp=0x9117ac88 sp=0x9117ac84 pc=0xb16b0968
03-27 19:59:19.432 27023-0/? E/Go: 	/home/felix/Downloads/go/src/syscall/asm_linux_arm.s:17 +0x8 fp=0x9117ac88 sp=0x9117ac84 pc=0xb16b0968
03-27 19:59:19.433 26951-27026/com.nutomic.syncthingandroid W/SyncthingNativeCode: github.com/syncthing/syncthing/lib/osutil.ioprioSet(0x2, 0x5, 0xb, 0x0)
03-27 19:59:19.433 27023-0/? E/Go: github.com/syncthing/syncthing/lib/osutil.ioprioSet(0x2, 0x5, 0xb, 0x0)
03-27 19:59:19.435 26951-27026/com.nutomic.syncthingandroid W/SyncthingNativeCode: 	/home/felix/workspace/syncthing-android/syncthing/src/github.com/syncthing/syncthing/lib/osutil/lowprio_linux.go:33 +0x3c fp=0x9117acac sp=0x9117ac88 pc=0xb19ae3e4
03-27 19:59:19.435 27023-0/? E/Go: 	/home/felix/workspace/syncthing-android/syncthing/src/github.com/syncthing/syncthing/lib/osutil/lowprio_linux.go:33 +0x3c fp=0x9117acac sp=0x9117ac88 pc=0xb19ae3e4
03-27 19:59:19.436 26951-27026/com.nutomic.syncthingandroid W/SyncthingNativeCode: github.com/syncthing/syncthing/lib/osutil.SetLowPriority(0x913a4000, 0x91bd8060)
```

**Comment by AudriusButkevicius** [comment]
It seems it's a bastardized kernel that doesn't have some linux primitives.

@calmh, put this under android build flag?

**Comment by rmueller83** [comment]
It should be this kernel: https://github.com/LineageOS/android_kernel_samsung_msm8974
If you see that there is something wrong with it, I can try to reach its maintainer.

**Comment by AudriusButkevicius** [comment]
Well it's missing the ioprio_set syscall, which has been in the Linux kernel 2.6.13 since 28 August 2005.

**Comment by rmueller83** [comment]
Strange, the implementation is there: https://github.com/LineageOS/android_kernel_samsung_msm8974/blob/lineage-15.1/fs/ioprio.c#L61

**Comment by rmueller83** [comment]
Following https://github.com/LineageOS/android_kernel_samsung_msm8974/blob/lineage-15.1/arch/x86/syscalls/syscall_32.tbl ioprio_set would be syscall number 289, but your log excerpt says ``syscall.Syscall(0x13a, ...)``which is number 314. Further down in my log file there is another line:
``Cause: seccomp prevented call to disallowed arm system call 314`` which is ``sync_file_range``.

**Comment by rmueller83** [comment]
The syscall table also contains it as 314: https://github.com/LineageOS/android_kernel_samsung_msm8974/blob/lineage-15.1/arch/arm/kernel/calls.S

**Comment by rmueller83** [comment]
My logfile contains a line: ``Cause: seccomp prevented call to disallowed arm system call 314``

It looks like this is a general Android 8 problem: https://developer.android.com/about/versions/oreo/android-8.0-changes.html#security-all

> Android 8.0 (API level 26) applies a Secure Computing (SECCOMP) filter to all apps. The list of allowed syscalls is restricted to those exposed through bionic. Although there are several other syscalls provided for backwards compatibility, we recommend against their use.

**Comment by rmueller83** [comment]
The list of allowed syscalls should be here: https://android.googlesource.com/platform/bionic.git/+/android-8.1.0_r18/libc/SYSCALLS.TXT

**Comment by AudriusButkevicius** [comment]
Well that's not the case on my pixel with vanilla Android 8.1

**Comment by MartinX3** [comment]
Nexus 6
Same problem here since upgrading from LineageOS 14.1 to 15.1. Syncthing log only shows:

`--------- beginning of main`

**Comment by stooone** [comment]
Me too.:(

**Comment by AudriusButkevicius** [comment]
Please refrain from making comments that add no value to the discussion. Emoticons are available there if you must express yourself. At least this doesn't send everyone that is following the repository an email.

**Comment by Catfriend1** [comment]
@vsespb : According to your recent issue got solved I guess you can now use syncthing app properly on your phone and this issue is solved too in the meantime? Please let me know if the issue still persists.

**Comment by AudriusButkevicius** [comment]
Closing this as I think it's fixed in the latest version.

**Comment by vsespb** [comment]
> and this issue is solved too in the meantime?

since issue was intermittent, I cant tell if it solved or not. lets close, I ll reopen if it reappears.
