### ISSUE TITLE
F-Droid build fails for 10.4

### ISSUE THREAD

**Issue by acornsirup** [syncthing/syncthing-android#1012]
Hi!

F-Droid fails to build the most recent Syncthing version:
https://f-droid.org/wiki/page/com.nutomic.syncthingandroid/lastbuild_4137

Is this an error on F-Droid's side or is there something that needs to be fixed on the Syncthing side?

Thanks!

**Comment by AudriusButkevicius** [comment]
Seems that version of Go is before time.Until was added, which I suspect is 1.8

**Comment by imsodin** [comment]
`time.Until` is indeed 1.8 and f-droid runs on debian oldstable (jessie) which only has 1.7. Judging by [this f-droid server issue](https://gitlab.com/fdroid/fdroidserver/issues/359) I doubt a switch to debian stable (stretch) will happen any time soon. So it will be necessary to build go from source for f-droid builds. Maybe using the build= metadata parameter, but that's probably a question to ask to the f-droid specialists.

**Comment by Bubu** [comment]
I think we can use the official go 1.8 distribution for now. Downloading and installing it before the build. But it'll be a while before I can setup and test this change.

**Comment by acornsirup** [comment]
Built successfully now. Thanks, everyone!
