### ISSUE TITLE
FS Watcher does not seem to work, logs broken too

### ISSUE THREAD

**Issue by vsespb** [syncthing/syncthing-android#1013]
I have DCIM folder (internal storage) shared and FS watcher enabled. I have only two devices paired - Android and Linux.

I do the folloging:

1) enabled debug log for and "fs" and "watchaggregator"
2) make some photos
3) go and watch advanced logs

I expect: photos immediately uploaded

But what happens is:

Photos uploaded only after 1+ mins.
Logs are empty (even after photo uploaded). Last line in logs is: "Enabled debug data for watchaggregator".

I also played with fs watcher on linux box, and now I definitely see, that under linux file watcher works, under android - does not.

Attaching log screenshot - this is the log that I saw _already_ when I've got photos on another device. Photos files are IMG_20180131_153249 IMG_20180131_153251 IMG_20180131_153252

So
1) photos were made after I turned on logging (see timestamps)
2) photos were uploaded
3) by that time advanced log was still empty

And I feel like file watcher does not work, but no strong evidences, as logs do not work too.

### Version Information

Xiaomi Redmi 4, Android 6.0.1, MIUI 8.0
SyncThing 0.14.43

![screenshot_2018-01-31-15-41-17-373_com nutomic syncthingandroid](https://user-images.githubusercontent.com/1210230/35623989-990ff1cc-069e-11e8-86e7-303b4aa1d2f0.png)

**Comment by imsodin** [comment]
As far as I know the android wrapper has it's own change detection, so it should work even without Syncthings own fs watching enabled. I seem to remember @Nutomic saying that in Android 6 there is some kind of limitation with the Android watching, so maybe that is the issue here.

As for why Syncthing's watcher isn't working: Do you have one of these log lines:  
```INFO: Started filesystem watcher for folder ...```  
```WARNING: Failed to start filesystem watcher for folder ...```

**Comment by AudriusButkevicius** [comment]
I think at some point Nutomic might have disabled the Java notification watcher.

**Comment by vsespb** [comment]
> Do you have one of these log lines:

Yes, I restarted SyncThing and have line that it's started:

![screenshot_2018-01-31-17-05-07-024_com nutomic syncthingandroid](https://user-images.githubusercontent.com/1210230/35627534-36879634-06aa-11e8-969e-e64ec1b694a7.png)

Next I even saw lines where watcher receives some events. I switched window to make phone, switched back, but all lines related to watcher gone (othere left in place). I went to "Debugging Facilities" and checkbox "watchaggregator" gone, I enabled it again, made few test with photos and it's gone again, now I see last line in logs: "Enabled debug data for watchaggregator", again.

**Comment by Nutomic** [comment]
Yes, the Android Java API for watching file changes is broken in Android 6. However, the file watcher built into Syncthing is working, so you should can use that instead.

**Comment by vsespb** [comment]
> However, the file watcher built into Syncthing is working, so you should can use that instead.

what does it mean "watcher built into Syncthing"? how it looks from user point of view? what is the option name?

**Comment by imsodin** [comment]
> I have DCIM folder (internal storage) shared and FS watcher enabled.

> what does it mean "watcher built into Syncthing"? how it looks from user point of view? what is the option name?

The two things are the same, so you said you already enabled it (also visible in your log). If you see the events in the log, then these files should be scanned (after 10s) and thus changes be picked up. If the web UI log viewer resets itself when switching windows (weird, maybe android "browser" resets stuff?), you may try logcat after enabling the watchaggregator debugging facility.

**Comment by Catfriend1** [comment]
@vsespb Please wait for the next release of the app containing syncthing 14.47 or higher. The file watcher was much worked on the last weeks. If that does not help, please report back and the ticket will be reopened.
