### ISSUE TITLE
Language setting sometimes change and other glitches

### ISSUE THREAD

**Issue by vsespb** [syncthing/syncthing-android#1014]
I have phone language Russian, but I turned English for SyncThing.
Now most of time it's English, but sometimes Russian again. For Main app and for Web GUI.
If I often open Web GUI, chance to reproduce is higher.

Also, I saw several times:
1) WebGUI / Advanced settings is sometimes filled with empty values - no folders in list etc (after reopen it's set again)
2) Logs checkboxes sometimes clear, when it was previously set (after reopen it's set again)

I feel like sometimes it fails to read data from phone memory and thinks that there is no data.

Xiaomi Redmi 4, Android 6.0.1, MIUI 8.0
SyncThing 0.14.43

**Comment by vsespb** [comment]
screenshot for random language.
what I did: opened application, saw random language, made screenshot. did not change anything. language is still Russian after app restart.

on screenshot you can see that interface is Russian, but language chooser shows English.

![lang1](https://user-images.githubusercontent.com/1210230/35650025-e4b66014-06eb-11e8-83b5-7b7a20557677.png)

**Comment by Nutomic** [comment]
The language settings only work with a hack, and there is no official way to implement this. We use the same method for this as F-Droid, so you will probably have the same problems in that app. I don't think there is anything we can do against that.

**Comment by Catfriend1** [comment]
@vsespb I guess its still a problem in the recent version 0.10.8? So leaving this open is correct.

**Comment by vsespb** [comment]
Yes it's still broken

**Comment by Catfriend1** [comment]
@vsespb Is this also happening in fdroid?

**Comment by AudriusButkevicius** [comment]
It shouldn't matter, but logs/repro would be interesting.

**Comment by vsespb** [comment]
Don't know. I replaced my phone with Xiaomi Mi 6 with Android 7. I think there is no language setting.

**Comment by Catfriend1** [comment]
Ok, I'll close it.
