### ISSUE TITLE
I really want to sync folders from SD-card on Android 7 without pain, please

### ISSUE THREAD

**Issue by nleo** [syncthing/syncthing-android#1016]
Hi, guys!

Your app tells me that my Android version isn't support SD-card access. But it does.

I use QuickPic and ResilioSync. Both show me something like "on next screen choose SD-card to give us write access", and then some Android screen there I choose SD-card and both apps works well. I can use QuickPic to delete and move photos through folders on SD-card and ResilioSync to sync them with PC.

But syncthing-android can't do this simple thing for me.

I know you are clever guys you can do this. They did and you can.

Thank you.

**Comment by NYPD** [comment]
https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions#what-about-sd-card-support
