### ISSUE TITLE
Update FAQ - External SD Card Support

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing-android#1017]
Link: https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions
What about SD card support?
- Android Nougat (7+) has a developer option to allow every app external sd card write access regardless of permission consent.
![grafik](https://user-images.githubusercontent.com/16361913/35784241-7dbc8a64-0a15-11e8-9175-1c1f7905d50a.png)

**Comment by Nutomic** [comment]
Did you try if this works with Syncthing?

**Comment by bor** [comment]
What kind of Android you have?
Is it some specific vendor-alike distribution?

**Comment by Catfriend1** [comment]
The current version of syncthing works. I also tested non - superuser terminal emulator creating a file on sdcard with touch /storage/.../test.
I am on 2018-12-18 lineage for microg android 7.1.2 with device lg h815 (g4).

**Comment by bor** [comment]
I'm trying to achieve this, at the moment no luck :(
Should be syncthing running as root?

**Comment by Catfriend1** [comment]
@bor: no root required. Did you Grant the storage permission via androids settings/apps/syncthing/permissions "normal" menu?

**Comment by bor** [comment]
@Catfriend1 sure, it was (even before).
I'm still have errors like:
`Creating folder marker: mkdir /storage/IDXX-XXXX/test/.stfolder: permission denied`

**Comment by Catfriend1** [comment]
@bor: ok then I think not every android implements the same here... Or another Feature is helping me out. 
If you dare, you can patch services.jar from android to allow sdcard write access without root. I did this some time before to my phone. https://github.com/Catfriend1/tingle

**Comment by Catfriend1** [comment]
Lets close this as invalid until I tested it on fresh reimaged android rom.

**Comment by TiZ-EX1** [comment]
That's not what that option means. It means to force every app to be able to be moved to the external SD card.

**Comment by Catfriend1** [comment]
You're right. So, in the meantime I got a PR merged solving the problem by running syncthing app with root privileges.

**Comment by trymeouteh** [comment]
I have Andriod Oreo and I have an app called [FolderSync Pro](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.full&hl=en) (Or [FolderSync](https://play.google.com/store/apps/details?id=dk.tacit.android.foldersync.lite&hl=en)) Which allows you to sync folders between your SD card to a cloud storage service and between your internal and external storage. I tried it out and it worked.

I am not an app developer but would it be possible to see how it is done in FolderSync and implement that into Syncthing to add SD Card support?

**Comment by AudriusButkevicius** [comment]
No, because syncthing is written in Go.
