### ISSUE TITLE
No connection over OpenVPN unless "Run only on wifi" unchecked

### ISSUE THREAD

**Issue by hubertbanas** [syncthing/syncthing-android#1019]
### Starting point:
- server configured with local discovery only
- android client configured with the following
  - local discovery only
  - "Run only on wifi"

### What happens:
- android client is on a public wifi; syncthing client is not connected; everything here is exactly as expected
- android client successfully establishes connection using OpenVPN; at this point I would expect successful connection but instead "Syncthing Options" and "Backup" becomes greyed out and syncthing client is not connected to the sync server; this is unexpected since android client is still on wifi

### Workaround:
- on android client: uncheck "Run only on wifi" under "Run Conditions"; "Syncthing Options" and "Backup" become available and syncthing client establishes connection

### Version Information
Syncthing Version: v0.14.43, Linux (64 bit)
App Version: v0.14.43
Android Version: Android 8.1.0
OpenVPN Connect 1.1.27 (build 96)

**Comment by robohobbit** [comment]
Same with Shadowsocks and Global Discovery on.

`--------- beginning of main
03-06 10:26:34.388 I/SyncthingNativeCode( 5382): [ZMR75] INFO: syncthing v0.14.43 "Dysprosium Dragonfly" (go1.9.2 android-arm64) vagrant@jessie64 2017-12-29 21:23:06 UTC [noupgrade]
03-06 10:26:34.390 I/SyncthingNativeCode( 5382): [ZMR75] INFO: My ID: ZMR75LR-L6LEUBD-PJNMHLI-4PCZTGD-4CTD2QS-GAGBTVF-WEFZDC3-7AE5NAK
03-06 10:26:34.399 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Disabling weak hash
03-06 10:26:34.511 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Ready to synchronize "WeChat Downloads" (uattt-328gw) (readwrite)
03-06 10:26:34.513 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Ready to synchronize "WhatsApp" (kl83v-mw0cn) (readwrite)
03-06 10:26:34.513 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Ready to synchronize "Notes" (8yv5k-grwwk) (readwrite)
03-06 10:26:34.514 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Ready to synchronize "Documents" (1haf0-kpl6x) (readwrite)
03-06 10:26:34.515 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Ready to synchronize "WeChat Pictures" (teqpy-jt6f6) (readwrite)
03-06 10:26:34.516 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Ready to synchronize "Music" (knwgc-3n2bj) (readwrite)
03-06 10:26:34.516 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Ready to synchronize "Photos" (3hht9-fn79c) (readwrite)
03-06 10:26:34.516 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Ready to synchronize "Android" (3g8ng-0wvra) (readwrite)
03-06 10:26:34.519 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Send rate is unlimited, receive rate is unlimited
03-06 10:26:34.521 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Rate limits do not apply to LAN connections
03-06 10:26:34.526 I/SyncthingNativeCode( 5382): [ZMR75] INFO: TCP listener ([::]:22000) starting
03-06 10:26:34.543 I/SyncthingNativeCode( 5382): [ZMR75] INFO: KCP listener ([::]:22020) starting
03-06 10:26:34.563 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Completed initial scan of readwrite folder "WeChat Downloads" (uattt-328gw)
03-06 10:26:34.566 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Completed initial scan of readwrite folder "Android" (3g8ng-0wvra)
03-06 10:26:34.586 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Completed initial scan of readwrite folder "WeChat Pictures" (teqpy-jt6f6)
03-06 10:26:34.594 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Completed initial scan of readwrite folder "Notes" (8yv5k-grwwk)
03-06 10:26:34.597 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Completed initial scan of readwrite folder "WhatsApp" (kl83v-mw0cn)
03-06 10:26:34.624 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Completed initial scan of readwrite folder "Documents" (1haf0-kpl6x)
03-06 10:26:34.646 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Device [REDACTED] is "MI5" at [dynamic]
03-06 10:26:34.647 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Device [REDACTED] is "HP250G3" at [dynamic]
03-06 10:26:34.649 I/SyncthingNativeCode( 5382): [ZMR75] INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
03-06 10:26:34.655 I/SyncthingNativeCode( 5382): [ZMR75] INFO: GUI and API listening on 127.0.0.1:8384
03-06 10:26:34.656 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
03-06 10:26:34.847 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Completed initial scan of readwrite folder "Photos" (3hht9-fn79c)
03-06 10:26:35.057 I/SyncthingNativeCode( 5382): [ZMR75] INFO: Completed initial scan of readwrite folder "Music" (knwgc-3n2bj)
03-06 10:26:35.399 W/SyncthingNativeCode( 5382): ionice: exec 9554: Permission denied
03-06 10:26:35.595 I/SyncthingNativeCode( 5382): [ZMR75] INFO: UPnP parse: unrecognized UPnP device of type upnp:rootdevice
03-06 10:26:35.596 I/SyncthingNativeCode( 5382): [ZMR75] INFO: UPnP parse: unrecognized UPnP device of type upnp:rootdevice
03-06 10:26:35.598 I/SyncthingNativeCode( 5382): [ZMR75] INFO: UPnP parse: unrecognized UPnP device of type uuid:00000000-0000-1000-0000-0024b2e1a909
03-06 10:26:35.599 I/SyncthingNativeCode( 5382): [ZMR75] INFO: UPnP parse: unrecognized UPnP device of type uuid:00000000-0000-1000-0000-0024b2e1a909
03-06 10:26:35.600 I/SyncthingNativeCode( 5382): [ZMR75] INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-wifialliance-org:device:WFADevice:1
03-06 10:26:35.601 I/SyncthingNativeCode( 5382): [ZMR75] INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-wifialliance-org:device:WFADevice:1
03-06 10:26:35.602 I/SyncthingNativeCode( 5382): [ZMR75] INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-wifialliance-org:service:WFAWLANConfig:1
03-06 10:26:35.603 I/SyncthingNativeCode( 5382): [ZMR75] INFO: UPnP parse: unrecognized UPnP device of type urn:schemas-wifialliance-org:service:WFAWLANConfig:1`

**Comment by Catfriend1** [comment]
@hubertbanas Can you please Update to 0.10.8 version and report back if the issue still persists? There were changes made regarding android 8.x

**Comment by hubertbanas** [comment]
0.10.8 doesn't fix the issue. Please reopen this bug.

**Comment by Catfriend1** [comment]
@robohobbit Can you please give a hint to @hubertbanas how OpenVPN works properly?

**Comment by robohobbit** [comment]
As I pointed out in my comment, I'm using Shadowsocks.

**Comment by AudriusButkevicius** [comment]
So being connected to VPN somehow hides the fact that android is connected to wifi, is that the issue?

**Comment by hubertbanas** [comment]
Correct, the options are greyed out and syncthing client stays disconnected from a sync server.

**Comment by Catfriend1** [comment]
Hi @hubertbanas ,
do you have the metered wifi setting toggled on in android as mentioned in https://stackoverflow.com/a/23879816 ? Then it would make sense to me why that happens.

**Comment by Catfriend1** [comment]
Opened Syncthing App based on debug build from PR #1119  : 
I tested with the following syncthing run condition prefs set:
- always run in background
- run only on wifi (all SSIDs valid)
With the fixes in place, syncthing correctly runs on wifi while OpenVPN is connected or disconnected:
![image](https://user-images.githubusercontent.com/16361913/40935933-f38d7dfc-6839-11e8-8b70-cc820f2c8df4.png)

**Comment by hubertbanas** [comment]
@Catfriend1 
Metered setting was set to "Automatic". I switched it to "Not metered" but that didn't make a difference.

BTW, on Android 8.1 this settings is berried at
Settings > Network & Internet > Data usage > Network restrictions

Looks like you already have a fix for it?

**Comment by Catfriend1** [comment]
@hubertbanas Does this debug build fix it? https://build.syncthing.net/repository/download/SyncthingAndroid_Build/21900:id/debug/app-debug.apk Be careful, its full of changes so please backup important data first.

**Comment by yaomtc** [comment]
Can verify that the same thing happens for me with the NordVPN app, which IIRC is a frontend for OpenVPN.

**Comment by Catfriend1** [comment]
To clarify the bug report: If you are running on wifi with openvpn connected, what does your syncthing notification on the status bar say? (Running or disabled?)

**Comment by yaomtc** [comment]
I don't have a Syncthing notification, but it does show in the "3 apps are using battery" notification. But if I open Syncthing while connected to the VPN and the wifi-only option is enabled, I get the pop-up saying Syncthing is disabled.

**Comment by Catfriend1** [comment]
@yaomtc @hubertbanas Can you please test if the issue still occurs running the latest debug build at https://build.syncthing.net/repository/download/SyncthingAndroid_Build/22103:id/debug/app-debug.apk (Please backup important data first and backup your configuration before switching over to the debug build)

**Comment by hubertbanas** [comment]
@Catfriend1 
Notification shows "Syncthing is disabled" when on VPN.

**Comment by Catfriend1** [comment]
@hubertbanas : which st build and openvpn version do you use?

**Comment by Catfriend1** [comment]
@hubertbanas : thanks for posting more info. I'm on de.blinkt.openvpn 0.7.5 with the latest debug version linked above. Could you please grab some logs with the matlog app and filter for DeviceStateHolder and SyncthingService ?

**Comment by yaomtc** [comment]
Using the linked build, the problem persists, even with the notification showing up now.

**Comment by hubertbanas** [comment]
FYI,
This bug is still present in v0.14.48 (0.10.11)

**Comment by Catfriend1** [comment]
Did you use this version de.blinkt.openvpn 0.7.5? I cant tell if the other mentioned vpn app works.

**Comment by yaomtc** [comment]
The problem seems to be gone for me. It could be related to a May security update I received a couple days ago, maybe, or having been away from my usual sources of wifi for a few days, I don't know. Using Syncthing version 0.14.47, Syncthing-Android version 0.10.10, and NordVPN 3.1.5+playstore.

**Comment by Catfriend1** [comment]
@yaomtc ok thanks for reporting back. Does that mean version 0.10.11 has a problem that did not exist in 0.10.10?

**Comment by hubertbanas** [comment]
I no longer see this problems as well. This is after receiving June 5, 2018 Android security patches. Please leave this bug open for another week or two to allow more testing.

- Android 8.1.0 (June 5, 2018 security patches)
- Syncthing Android Client v0.14.48 (0.10.11)
- OpenVPN 3.0.5 (1816)

**Comment by hubertbanas** [comment]
It has been working consistent for the past few days. Thank you all for getting this resolved.
