### ISSUE TITLE
Syncthing consumes CPU even when it should be off

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#1020]
Syncthing is configured to run on Wi-Fi only and there is also AFWall rule giving Syncthing access only to Wi-Fi network. Wi-Fi get turned on and off repeatedly.

Hovewer, I've just found Syncthing causing faster battery discharge, consuming about 9-11% CPU, although Wi-Fi is off. The process name is `com.nutomic.syncthingandroid`. Trying to open Syncthing produces "exit syncthing or change settings" message.

After explicit `kill 6563` it stopped consuming the CPU. Trying to open Syncthing still produces the same message.

### Version Information

    App Version: 0.10.4
    Syncthing Version: (empty in Settings->About when Wi-FI is off)
    Android Version: Android 4.4.2

**Comment by vsespb** [comment]
I understand that syncthing always consumes 9-11 % CPU, unrelated to wifi settings (and you note wifi because with wifi off it should do nothing)?

**Comment by vi** [comment]
Yes, it sometimes gets stuck. Probably not always reproducible.

Have you tested rapid changes of network status, so that Syncthing tried to be available, then tries to stop, then tries to become available again and so on?

Is grace period to prevent too much start/stop attempts implemented? (e.g. don't start Syncthing engine unless 5 seconds elapsed from previous shutdown of Syncthing engine).

**Comment by vsespb** [comment]
no. i am not maintainer. i just try to understand if your issue similar to mine https://github.com/syncthing/syncthing-android/issues/1043

**Comment by Catfriend1** [comment]
@vi Is your problem solved with the current release 0.10.8?

**Comment by imsodin** [comment]
That's because naturally any change to our build process brakes the F-Droid build process. Unfortunately I don't see any obvious cause from the log:  
https://f-droid.org/wiki/page/com.nutomic.syncthingandroid/lastbuild_4141
@AudriusButkevicius @Catfriend1 @capi Does it make any sense to you?

**Comment by capi** [comment]
I'm no expert on the build, but in #1049 there were changes regarding the signing configuration so that automatic builds on PR don't get signed. I suppose, that's what's breaking now for F-Droid.

**Comment by Catfriend1** [comment]
@imsodin Looks like the release signing setup is not ready. Can this be causes by the transition to another account?
@vi Here is the release build 0.10.8 - https://drive.google.com/file/d/1lhe8IyLTBbla4km-R_YDHYP0hIiUN1gZ/view?usp=sharing

**Comment by imsodin** [comment]
@Catfriend1 F-Droid signs their apps with their own keys: https://f-droid.org/en/docs/FAQ_-_App_Developers/#what-about-signing AFAIK F-Droid only interacts with the git repo, so there shouldn't be any accounts involved.

The output path shouldn't have changed, right (the error message anyway doesn't seem to point to that)? From F-Droid Metadata:
`output=app/build/outputs/apk/release/app-release-unsigned.apk`

**Comment by vi** [comment]
Switching from/to F-Droid build is a hassle (because of the signing).

Maybe I'll wait for F-Droid problem to be resolved, than test how it works.

**Comment by vi** [comment]
Tried `0.10.8`: still happens.

My session was like that:

* Syncthing upgraded;
* Restarted Syncthing on PC;
* Opened Syncthing app on Android: the device is "disconnected";
* Entered web UI: something like "Connection refused" or another system, non-Syncthing content.
* Exited WebUI, restarted Syncthing from menu.
* Now Syncthing is connected and transfers data.
* The data finished transferring.
* Launched terminal and `top -m 3`: `com.nutomic.syncthingandroid CPU=3%`.
* Turned off Wi-Fi from quick settings panel.
* `top` in the terminal still shows 2-3% for syncthing
* Clicked on "Syncthing is disabled" notification
* "Syncthing is disabled. Do you wasn to change your preferences? [Exit] [Change Settings]"
* [Exit]
* Still 2-3% in `top -m 3`
* Swipe away Syncthing from the list of recent apps.
* Finally `Syncthing` disappears from `top -m 3`.

**Comment by AudriusButkevicius** [comment]
2-3% is expected and far from 50% reported in the initial reports.

**Comment by AudriusButkevicius** [comment]
Not sure what the complain is. 
Yes, running applications consume CPU, on other news, water is wet.

**Comment by vi** [comment]
`com.nutomic.syncthingandroid` is UI part of Syncthing, unlike `libsyncthing.so` which is engine part, I suppose. When syncthing is in background (let alone turned off), I expect it to be idling.

When I see syncthing actually working, it is `libsyncthing.so`. When I see Syncthing just burning CPU for no reason, it's `com.nutomic.syncthingandroid`.

----

**Update**: I tried turning Wi-Fi on and off multiple times again, but can't reproduce the bug anymore so far. `com.nutomic.syncthingandroid` is still running, but is nowhere near the top list of consuming CPUs when in background. CPU consumption is only when I do something in Syncthing UI or when `libsyncthing.so` is also active.

I'll comment here again if I notice the misbehaviour again.
