### ISSUE TITLE
Annoying notification message even when Wi-Fi is off.

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#1021]
Syncthing is configured to be only on Wi-FI. Hovewer there is persistent notification "Syncthing is disabled" (or even occasionally "Syncthing is enabled") stays when Wi-Fi is off, especially when mobile network goes on and off.

Syncthing attracts too much of my attention when it should just sit still and wait.

Settings: Run conditions: Always run in background = on (is the accent on "always" or on "background" here?); Run only on wifi = on, run only when charging = off, respect android battery saving = on; Behaviour: Notification = Low Priority.

### Version Information

    App Version: 0.10.4
    Syncthing Version: (empty in Settings->About when Wi-FI is off)
    Android Version: Android 4.4.2

**Comment by Catfriend1** [comment]
This will be discussed on in https://github.com/syncthing/syncthing-android/issues/1048 as there is already a technical approach for a solution found.
