### ISSUE TITLE
Syncthing on Android suddently exited when I terminated Syncthing instance elsewhere.

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#1022]
I press Ctrl+C on my laptop Syncthing instance. Web GUI on laptop shows message about disconnection of the engine. And Web GUI on Android also instantly shows message that syncthing is terminated, as if Ctrl+C travelled across the network to Android.

Restarting Syncthing on Android makes it work again. But anyways it is suspicious.

### Version Information

    App Version: 0.10.4
    Syncthing Version: (empty in Settings->About when Wi-FI is off)
    Android Version: Android 4.4.2

**Comment by AudriusButkevicius** [comment]
I sugest you read this: http://www.softwaretestinghelp.com/how-to-write-good-bug-report/

You haven't provided logs, nor did you explain how to reproduce this.
One of observations of things are completely useless.

**Comment by vi** [comment]
If I it happens again then maybe I'll collect the logcat. At that time I was just tried to coerce Syncthing into synchronizing a folder stuck at bad state (in the end I've just removed and re-created it) and brushed the failure aside.

Underspecified bug report also has some value (for example, others who also encounter this will know that it's not the first time), so it worth reporting it.

**Comment by AudriusButkevicius** [comment]
And what if they don't, this stays open forever without a resolution? 

I prefer only to have things around that can be reproduced, and therefore fixed.

**Comment by vi** [comment]
> this stays open forever without a resolution

Stays open until original author or somebody adds more information, or until a duplicate, better issue filed. "There is smoke somewhere here around" is a better request for a fire bridage compared to nothing at all.

**Comment by Nutomic** [comment]
If you dont post steps to reproduce and logs, you only spam the issue tracker. So I will make it simple for you: if you dont post logs, I will close this issue.

**Comment by vi** [comment]
I'll just create a new issue if/when I get the logs and/or better reproduce steps (compared to "Start Syncthing on Android; start Syncthing elsewhere, make sure they are connected, terminate Syncthing elsewhere with Cltr+C, Expectes: syncthing on Android keeps running, Actual: syncthing on Android suddenly terminated").
