### ISSUE TITLE
Syncthing ignores run condition on Android 8.1

### ISSUE THREAD

**Issue by rvn2p** [syncthing/syncthing-android#1030]
Hi,
after upgrading to Android 8.1 syncthing started to sync when not on wifi/charge (see screenshots)
![screenshot_settings_20180306-095127](https://user-images.githubusercontent.com/20243819/37023169-5a7bed48-2125-11e8-99bc-969ee663a3c3.png)
![screenshot_trebuchet_20180306-095055](https://user-images.githubusercontent.com/20243819/37023170-5a99617a-2125-11e8-9647-75d29811ce74.png)

 

### Version Information

    App Version: 0.10.4
    Syncthing Version: v0.14.43
    Android Version: 8.1 (lineage-15.1-20180226-nightly-oneplus3)

**Comment by AudriusButkevicius** [comment]
See existing issues.
