### ISSUE TITLE
Run only on Wifi - but also as Hotspot

### ISSUE THREAD

**Issue by jeyca** [syncthing/syncthing-android#1034]
I activated the option "Run only on Wifi", but sometimes I use my phone as a Hotspot where my notebook connects to. This also means "run on wifi" for me, but not for syncthing at the moment, it does not run when using the phone as Hotspot with another device connected. 

Could this also be covered by this option? Or added as an additional one?

**Comment by AudriusButkevicius** [comment]
Search existing issues, my memory serves this was already answered/closed.

**Comment by jeyca** [comment]
Ok, seems to be this one: https://github.com/syncthing/syncthing-android/issues/641

I did not understand all of it, but it seems to be a problem, to stop the app syncing over mobile data when a hotspot is activated. Is that true? But why should syncthing sync over mobile data, when the  connected device is just in the local network?!

**Comment by DrSchnagels** [comment]
Actually it is a bug for me. Syncthing crashes silently, doesnt correctly load, when I enable hotspot.

**Comment by jeyca** [comment]
Do you have "run only on wifi" activated?

**Comment by Catfriend1** [comment]
According to https://github.com/syncthing/syncthing-android/issues/194 Nutomic labeled this a niche use case. If implemented, the user should get a clear warning from the app, that this can cause a lot of data traffic over the mobile network if syncthing is not configured appropriately for "just local connections". Nutomic said "So syncthing would have to be started with global discovery disabled, and only local discovery enabled.". Is a PR for this welcome?

**Comment by jeyca** [comment]
I would really be looking forward in having this option, to sync in hotspot mode. I do not really understand, why this would force opening sync for mobile as well. Its intuitive for me that being in a hotspot network is the same like being in the same wifi network for the users.

**Comment by AudriusButkevicius** [comment]
Just disable the run on wifi condition, as being a hotspot is clearly not being on the wifi, and being on the mobile network.

**Comment by Catfriend1** [comment]
An interesting explanation I found about the isActiveNetworkMetered() function of ConnectivityManager:
https://stackoverflow.com/questions/23877476/android-why-connectivitymanager-isactivenetworkmetered-always-returning-true

**Comment by daviewales** [comment]
Is there going to be any progress on this?
I almost exclusively use my phone hotspot as a local "WiFi network" between my phone and my computer for Syncthing.

**Comment by Catfriend1** [comment]
The new run conditions allow setting metered WiFi as an allowed precondition to run syncthing.

**Comment by daviewales** [comment]
I assumed that meant when the phone was connected to another hotspot, not when the phone was a hotspot itself.

Is my assumption incorrect?

Also, will this option only sync over the WiFi hotspot locally, without using my data?
