### ISSUE TITLE
F-Droid build fails for 0.10.5  / st-0.14.45

### ISSUE THREAD

**Issue by wwwutz** [syncthing/syncthing-android#1035]
Looks like go-1.10 is missing.
```
0.10.5

We can't build this version: The build for this version appears to have failed. Check the build log.

Version code: 4138 

== Installed Android Tools ==

INFO: Creating log directory
INFO: Creating temporary directory
INFO: Creating output directory
INFO: Using git version 2.11.0
INFO: Building version 0.10.5 (4138) of com.nutomic.syncthingandroid
INFO: Running 'sudo' commands in /home/vagrant
ERROR: Could not build app com.nutomic.syncthingandroid: Error running sudo command for com.nutomic.syncthingandroid:0.10.5
==== detail begin ====
+ apt-get install -y golang-go/testing golang-1.9-go/testing golang-src/testing golang-1.9-src/testing
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 golang-go : Depends: golang-1.10-go but it is not installable
 golang-src : Depends: golang-1.10-src but it is not installable
E: Unable to correct problems, you have held broken packages.
==== detail end ====

```

    App Version: 0.10.5
    Syncthing Version: v0.14.45

**Comment by wwwutz** [comment]
The problem is even more confusing, as the F-Droid app presents syncthing as 0.10.5, but the apk downloaded is still for syncthing version 0.14.43.

**Comment by AudriusButkevicius** [comment]
There are issues with the latest version so it's best to hold back I suspect

**Comment by wwwutz** [comment]
To be correct: @ 2018-03-12 20:15 GMT  F-Droid says 0.10.4 ( not .5 ) and syncthing v0.14.45. But v0.14.43 is installed.

**Comment by TheBestTheBestTheBest** [comment]
I can confirm i had to delete the play store version and use the F-Droid version to go around the fact that the last 0.10.5 version is very buggy. I had to stick with 0.10.4, it's extremely stable and works wonders even on LTE/3G/Public Wifi

**Comment by Nutomic** [comment]
FYI the build doesn't seem to work with Go 1.10, so F-Droid should keep using Go 1.9.

**Comment by imsodin** [comment]
I went ahead and created a Merge Request at F-Droid fixing this issue and disabling the 0.10.5 release: https://gitlab.com/fdroid/fdroiddata/merge_requests/3000
I hope that's ok.

**Comment by wwwutz** [comment]
I was able to download st-a-0.10.6, with a cherrypicked st0.14..45+1-gbf165d68 from f-droid.. so everything is fine for me. Thanks!

**Comment by imsodin** [comment]
@wwwutz Where? As far as I can see F-Droid's newest version is 0.10.4 and the build problem is still pending:  
https://f-droid.org/wiki/page/com.nutomic.syncthingandroid#0.10.5  
https://f-droid.org/packages/com.nutomic.syncthingandroid/

**Comment by Catfriend1** [comment]
Also cant find the fdroid release 0.10.6

**Comment by licaon-kter** [comment]
As the merge request shows, it was not yet merged, it will take time to build, publish etc.

**Comment by wwwutz** [comment]
Oooops. Sorry. I was tricked by `yalp`. Normally I install everything via F-droid but I stumbled over `yalp` and `yalp` happily installed 0.10.6 ... from google play store.

**Comment by Catfriend1** [comment]
Build 0.10.7 is available on fdroid.
https://f-droid.org/packages/com.nutomic.syncthingandroid/#0.10.7
