### ISSUE TITLE
Stopped working with last update

### ISSUE THREAD

**Issue by serl** [syncthing/syncthing-android#1037]
After the last app update, Syncthing stopped working. In my configuration, I synchronize a folder of 500-1000 files of various sizes, about 4GB in total, between my android tablet and a couple of Linux machines.

### The symptoms

* Syncthing on the tablet is persuaded that the folder has 300 files more, and that it is about 1GB bigger (but it's not, I checked with a file manager), and it's "trying to push" the extra data (I mean: showing the other devices as syncing).
* On the other side, it is not downloading the updates from the other clients, but only creating phantom `.syncthing.*.tmp` files.
* The connections between the tablet and the other clients is regularly "reset by peer" (I guess that's why it's not syncing).
* (Battery consumption seems increased.)

### What I tried

* Export configuration -> Delete application data from android settings -> Import configuration. It re-synchronize quickly and worked for a while (I guess until Syncthing got restarted). Then it broke again.

### Version Information

    App Version: 0.10.5
    Syncthing Version: v0.14.45
    Android Version: Android 5.0.2

**Comment by AudriusButkevicius** [comment]
#1032
