### ISSUE TITLE
"Battery eater" - Received inotify event 8 at syncthing.log

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing-android#1038]
appv: current and older releases.
syncthing: current 14.46-rc1 and older releases including 14.45+commit.

Reproducer:
- Create a sync folder for "/storage/emulated/0" = Internal SD Card.
- every time, syncthing writes something into its log file at "/storage/emulated/0/Android/data/com.nutomic.syncthingandroid(.debug)/files/syncthing.log", inotify event 8 is received by the "FolderObserver". This repeated more than three times, so I suspect a battery eating cycle consisting of syncthing writing its logfile, triggering inotify file change event, writing to the log, .... The cycle stops after ~ 12 times so it is not a deadlock. I think we can get better here by hard-excluding its own log.

Log excerpt:
![grafik](https://user-images.githubusercontent.com/16361913/37393533-a23e9976-2771-11e8-9b09-c18252ed8185.png)

Workaround:
- exclude "/storage/emulated/0/Android/data/com.nutomic.syncthingandroid(.debug)/files/syncthing.log" by using normal syncthing core ignore list.

**Comment by mariosangiorgio** [comment]
I'm seeing the same battery issues

**Comment by DrSchnagels** [comment]
I get the same message on my OP5 8.0 and Pixel C 8.1.
I also have /0/ as sync share set up. 
BUT i exclude the whole /Android folder.

**Comment by vsespb** [comment]
Same. Started eating battery at 0.14.45 and not fixed in 14.45+1 
Was fine before those versions.

**Comment by vsespb** [comment]
hm, but I don't sync `com.nutomic.syncthingandroid(.debug)/files/syncthing.log`.

**Comment by Catfriend1** [comment]
@DrSchnagels @vsespb When you run Catlog App and filter on "FolderObserver", do you see the same log entries I posted above with event 8 logged?

**Comment by vsespb** [comment]
no. ok i started separate issue https://github.com/syncthing/syncthing-android/issues/1043

**Comment by AudriusButkevicius** [comment]
I am pretty sure this is same as #1043
