### ISSUE TITLE
Latest Release Rejected by Google Play

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing-android#1039]
> Hi Developers at Felix Ableitner,
> 
> Thanks for submitting your app to Google Play. I reviewed Syncthing, com.nutomic.syncthingandroid, and had to reject it for violating our device and network abuse policy. If you submitted an update, the previous version of your app is still live on Google Play.
> 
> Here’s how you can submit your app for another review:
> 
>     Read through the Optimizing for Doze and App Standby article for instructions on how to use the Doze feature.
>         Note: If you're submitting a peripheral companion app, please provide a summary of your use case to our policy support team.
>     Remove android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS from your manifest.
>     Make sure your app is compliant with the Device and Network Abuse policy. Remember that additional enforcement could occur if there are further policy issues with your apps.
>     Sign in to your Play Console and submit the app.
> 
> You can read this Android Developers Help Center article for a list of app types which are eligible to declare this permission.
> 
> Once you’ve removed this permission, you might consider using Firebase Cloud Messaging (FCM) if your app’s message delivery requires a temporary exemption from battery optimization. Please set high priority only if the message is time-critical and requires the user’s immediate interaction, and be aware that setting your messages to high priority contributes to more battery drain compared to normal priority messages.
> 
> Alternatively, if you need to set alarms that fire while in Doze, please use setAndAllowWhileIdle() or setExactAndAllowWhileIdle().
> 
> If you’ve reviewed the policy and feel this rejection may have been in error, please reach out to our policy support team. One of my colleagues will get back to you within 2 business days.
> 
> I appreciate your support of Google Play!
> 
> Best,
> 
> Sierra
> 
> Google Play Review Team
> 
> We'd appreciate your feedback on Play policy notification emails. Help us improve the developer experience by completing this three question survey.

This means Google is not letting me release the fix for #1032. The changes they request would take a complete rewrite, and would take months to complete. As a workaround, I have created a new version 0.10.7, which you can get from the beta channel:

https://play.google.com/apps/testing/com.nutomic.syncthingandroid

Unless Google reverses their decision, every single user will receive a broken version of the app, and they won't even notice it unless they browse this issue tracker. This is a terrible decision by Google, blackmailing open source developers and preventing me from releasing a bug fix for users.

I sent an appeal to Google, but I have no idea if this will help. If you have any contacts at Google, please ask them to look into this. It could also help to contact Google on social media. 

I strongly suggest you to switch to F-Droid instead, where you won't be the subject of such shenanigans. This will require a reinstall of the app.

https://f-droid.org/packages/com.nutomic.syncthingandroid/

**Comment by Catfriend1** [comment]
Hey @Nutomic,
is it possible to compile against an older android sdk version? I've read this on forums on the web that developers compiling "for android 8.x+" are forced to comply.

**Comment by Nutomic** [comment]
No, once an update was released on Google Play with a certain targetSdkVersion, it is not possible to downgrade it any more. Unfortunately I made such an update a while ago.

**Comment by Nutomic** [comment]
Huh, you are right. I am surprised it was that easy.
