### ISSUE TITLE
Travis build for 0.10.6 is failing

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing-android#1041]
Error logged is:
`21.31s$ git submodule update --init --recursive
Submodule 'syncthing' (https://github.com/syncthing/syncthing.git) registered for path 'syncthing/src/github.com/syncthing/syncthing'
Cloning into '/home/travis/build/syncthing/syncthing-android/syncthing/src/github.com/syncthing/syncthing'...
error: Server does not allow request for unadvertised object bf165d680f38dcbf08fffd3a1bf2cd42da8c2217
Fetched in submodule path 'syncthing/src/github.com/syncthing/syncthing', but it did not contain bf165d680f38dcbf08fffd3a1bf2cd42da8c2217. Direct fetching of that commit failed.`

This is because imsodin's commit is outside of the main syncthing repository. I'm looking for a fix.

**Comment by imsodin** [comment]
I took the liberty to push the branch to the syncthing/syncthing repo: https://github.com/syncthing/syncthing/tree/v0.14.45-android  
That might already fix your problem without modifications to syncthing-android.

**Comment by Catfriend1** [comment]
Thanks @imsodin ... just the second I found the solution.
I'm going to submit a travis fix for review, in case we need this in the future for building with an external temporary commit.

**Comment by Catfriend1** [comment]
Hmm.. travis does not seem to support customizing the git clone part of the build process?!
On my build server, the following lines instead of  ...
git submodule update --init --recursive
... helped correctly downloading the repository with an external commit reference:
git submodule init
git submodule sync
git submodule foreach "(git checkout master; git pull)"
git submodule update --init --recursive
