### ISSUE TITLE
Syncthing Headers mysteriously missing

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#1042]
This is a constant issue on my HTC U11... Syncthing directories keep getting an "Error" message, no matter if I reset the app and delete all content - The error is temporarily fixed if I clear the app's data and re-import my old config, but by the end of the day when I check my Syncthing status again, the errors re-appeared.

 The error tells me, in the web GUI (not the standard app GUI for some reason), that the directories can't sync due to "missing headers."

I do not have any 'system cleaner' apps installed nor used besides HTC's built-in Boost+ solution, but Syncthing is added to it's whitelists. (In addition, I've disabled Boost+ and the Syncthing error still occurs regardless.)

ST v0.14.45
ST-Android v0.10.5
Android 8.x Oreo

**Comment by Catfriend1** [comment]
Hi,
app version 0.10.5 is broken. Please update to 0.10.6 on google play store.
That should solve your problems.
Kind regards
