### ISSUE TITLE
Failed to create syncthing config

### ISSUE THREAD

**Issue by MrGlasspoole** [syncthing/syncthing-android#1052]
After the installation and starting Syncthing it crashes.

Syncthing Version: 0.10.7 from F-Droid
Android Version: Android 4.4.4 / Cyanogenmod 11

Log:

> --------- beginning of /dev/log/main
04-14 12:40:53.187 W/SyncthingNativeCode( 1497): SIGILL: illegal instruction
04-14 12:40:53.217 W/SyncthingNativeCode( 1497): PC=0x40638844 m=0 sigcode=1
04-14 12:40:53.217 W/SyncthingNativeCode( 1497): goroutine 0 [idle]:
04-14 12:40:53.217 W/SyncthingNativeCode( 1497): goroutine 1 [running]:
04-14 12:40:53.227 W/SyncthingNativeCode( 1497): runtime.systemstack_switch()
04-14 12:40:53.227 W/SyncthingNativeCode( 1497): 	/usr/lib/go-1.9/src/runtime/asm_arm.s:209 +0x4 fp=0x512267b8 sp=0x512267b4 pc=0x40159500
04-14 12:40:53.227 W/SyncthingNativeCode( 1497): runtime.main()
04-14 12:40:53.227 W/SyncthingNativeCode( 1497): 	/usr/lib/go-1.9/src/runtime/proc.go:128 +0x54 fp=0x512267e4 sp=0x512267b8 pc=0x401256b8
04-14 12:40:53.227 W/SyncthingNativeCode( 1497): runtime.goexit()
04-14 12:40:53.227 W/SyncthingNativeCode( 1497): 	/usr/lib/go-1.9/src/runtime/asm_arm.s:971 +0x4 fp=0x512267e4 sp=0x512267e4 pc=0x4015b600
04-14 12:40:53.227 W/SyncthingNativeCode( 1497): trap    0x6
04-14 12:40:53.227 W/SyncthingNativeCode( 1497): error   0x0
04-14 12:40:53.227 W/SyncthingNativeCode( 1497): oldmask 0x1204
04-14 12:40:53.237 W/SyncthingNativeCode( 1497): r0      0x40fd5020
04-14 12:40:53.237 W/SyncthingNativeCode( 1497): r1      0xc
04-14 12:40:53.237 W/SyncthingNativeCode( 1497): r2      0x0
04-14 12:40:53.237 W/SyncthingNativeCode( 1497): r3      0x40eaaf98
04-14 12:40:53.237 W/SyncthingNativeCode( 1497): r4      0xbefff884
04-14 12:40:53.237 W/SyncthingNativeCode( 1497): r5      0xd4
04-14 12:40:53.237 W/SyncthingNativeCode( 1497): r6      0x7d4
04-14 12:40:53.237 W/SyncthingNativeCode( 1497): r7      0x33
04-14 12:40:53.237 W/SyncthingNativeCode( 1497): r8      0x40eab490
04-14 12:40:53.237 W/SyncthingNativeCode( 1497): r9      0x0
04-14 12:40:53.237 W/SyncthingNativeCode( 1497): r10     0x40eaaf98
04-14 12:40:53.237 W/SyncthingNativeCode( 1497): fp      0xbefff840
04-14 12:40:53.247 W/SyncthingNativeCode( 1497): ip      0x1
04-14 12:40:53.247 W/SyncthingNativeCode( 1497): sp      0xbefff838
04-14 12:40:53.247 W/SyncthingNativeCode( 1497): lr      0x40eeddaf
04-14 12:40:53.247 W/SyncthingNativeCode( 1497): pc      0x40638844
04-14 12:40:53.247 W/SyncthingNativeCode( 1497): cpsr    0x20000010
04-14 12:40:53.247 W/SyncthingNativeCode( 1497): fault   0x0
04-14 12:40:54.267 W/SyncthingNativeCode( 1497): usage: ionice <pid> [none|rt|be|idle] [prio]

**Comment by AudriusButkevicius** [comment]
Seems like your device is not supported, as the CPU is missing some instruction sets syncthing relies on.
