### ISSUE TITLE
Regularly creates conflicts for files that (I am almost certain) aren't being modified

### ISSUE THREAD

**Issue by TiZ-EX1** [syncthing/syncthing-android#1053]
Hi there. Thanks for all the work you do on this project.

So, I use todo.txt. I keep it as a subfolder of my Documents, and my Documents is synced between my two computers, my two servers, and my phone. I used to have simpletask, but I stopped using it in favor of a web UI on my server.

In the middle of every night, and often during the day when I'm actively productive, sync conflicts will appear for todo.txt and done.txt. But they only appear when my phone has syncthing enabled, so I must presume that syncthing-android is the cause of this. Those files don't get touched on my phone at all! Or rather... I'd hope they don't! I don't know why my phone continuously asserts that its untouched files are the newest versions in contradiction to the other hosts which really do have the newest versions, creating those conflicts.

todo.txt is written in bash, which I believe means that instead of actually modifying an existing file, it will just make a new one with the same name and replace the old one. So doing tasks, cleaning my done.txt and moving it to the archive, I think technically results in the creation of new files. I wonder if this is part of what makes syncthing-android wig out so hard?

I'm not sure what I would do to diagnose this and make sure that todo.txt and done.txt aren't actually being continuously touched by my phone somehow. Recommendations on that?

### Version Information

    App Version: 0.10.8
    Syncthing Version: v0.14.46+1-g7f1c0a33
    Android Version: Android 8.0 (happened on 7.1 too)

**Comment by AudriusButkevicius** [comment]
Please use the [forum](https://forum.syncthing.net/) for support related queries.
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
