### ISSUE TITLE
Have a configurable Timout if condition not anymore given

### ISSUE THREAD

**Issue by Mannshoch** [syncthing/syncthing-android#1056]
If I load my Phone with the super charging adapter I have Problems with the Display. So I have to temporary unplug my Phone.  And do something. Also I have sometime some Connection problems with my W-Lan. It should not shutdown immediately if the connection to the given W-Lan is broken.

**Comment by AudriusButkevicius** [comment]
No, you break the run conditions, hence syncthing is terminated. You should fix your wlan and charger, not expect applications to work around your issues

**Comment by Mannshoch** [comment]
Isn't Software supposed to help us around our Issues? It's not a Problem on my Charger it's a Problem on the Phone. My W-Lan is for my use-case good enough I don't feel like buy a W-Lan repeater to get a slightly bit better W-Lan in the garden.

**Comment by AudriusButkevicius** [comment]
Well, we will not be wedging in extra code to handle your sketchy wifi. 

The generic usecase is covered, and it works.
