### ISSUE TITLE
All settings are gone after updating app

### ISSUE THREAD

**Issue by jeyca** [syncthing/syncthing-android#1058]
After updating Syncthing to version 0.10.8 from 0.10.7 via F-Droid, Syncthing lost all its settings. When I started it, it first created security keys and then asked me about if I would like to share informations. So, everything that happens with the first start of this app. All folder and device settings were gone.

### Version Information
    App Version: 0.10.8
    Android Version: Lineage OS 14.1

**Comment by AudriusButkevicius** [comment]
Use the forum for support.
