### ISSUE TITLE
Add possibility to reset delta indexes

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing-android#1060]
For debugging purposes it would be nice if there was an option like the existing "Reset Database" in the debug menu also for resetting the delta indexes. As there is no rest API endpoint for that, I am unable to do it on android (or admittedly just unwilling to find/try out how I could do it manually).

**Comment by Nutomic** [comment]
Isnt there an environment variable for this? You should be able to pass that from the app settings.

**Comment by imsodin** [comment]
Not that I am aware of. There is the command line option `-reset-deltas` similar to `-reset-database`. I assume the mentioned "Reset Database" just restarts the syncthing binary with `-reset-database`, so a new option "Reset Delta Indexes" could likely reuse that by replacing the command line parameter. to `-reset-deltas`.

**Comment by Catfriend1** [comment]
I am currently doing this in a new PR ...
