### ISSUE TITLE
Incorrect native UI status of a remote device during synchronization

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing-android#1062]
Following up on the [forum discussion](https://forum.syncthing.net/t/incorrect-devices-status-on-android/11510):

   1. Add a big file to a folder shared with a remote device
   2. Open Syncthing app (native UI), and review the remote device's status
   * Result: remote device is shown as "Up to Date"
   * Expected result: remote device is shown as "Syncing"

WebUI shows "Syncing" status correctly

### Version Information

    App Version: 0.10.8
    Syncthing Version: v0.14.46
    Android Version: Android 8.0

**Comment by Catfriend1** [comment]
Working on this in https://github.com/syncthing/syncthing-android/compare/master...Catfriend1:deviceSyncStatus

**Comment by Catfriend1** [comment]
Hi @scienmind ,
can you please test if this debug build fixes the problem with the device UI sync status?
https://build.syncthing.net/repository/download/SyncthingAndroid_Build/20341:id/debug/app-debug.apk
Please be sure to backup your data and config first before switching to the debug build. It contains a bunch of more changes that are currently unreleased like syncthing 0.14.47

**Comment by scienmind** [comment]
Thanks, @Catfriend1 !

Just tested the linked apk on one of the devices, looks fixed indeed 👍

**Comment by Catfriend1** [comment]
@scienmind Thanks for testing.

**Comment by Catfriend1** [comment]
@scienmind The last apk linked above had a serious error in its code as I discovered today and fixed it (endless loop problem if a device got deleted). Would you mind trying this one? https://build.syncthing.net/repository/download/SyncthingAndroid_Build/20364:id/debug/app-debug.apk

**Comment by scienmind** [comment]
I tried the newer apk, shows "Syncing" status when appropriate as well.

FYI - don't consider it "well tested" by me in any way. Just a sanity check if it basically does what it should.
