### ISSUE TITLE
Android [Security Patch] Update Stops Syncthing From Working

### ISSUE THREAD

**Issue by ShadowRylander** [syncthing/syncthing-android#1063]
Hello! <br>
&nbsp;&nbsp;&nbsp;&nbsp; My sincerest apologies if this has already been reported; however, I simply do not understand the log report enough to research the issue myself; it is likely a `CyanogenMod` / `LineageOS` issue as it stands.

* `What Happened:` No idea; Syncthing just stopped working on Android 8.1.0 after an upgrade to one of the security patches, likely from one in late March.

* `What I Expected To Happen Instead:` For Syncthing to work as usual.

* `Any Steps To Reproduce The Problem:` Upgrade your Android version?

`Version Information:`
* `App Version:` 0.10.7 / 8 (Tried this on the Termux and Google Play versions respectively.)
* `Syncthing Version:` v0.14.45 "Dysprosium Dragonfly"
* `Android Version:` CandyROM 8.1.0
    * `Candy Version:` Candy-bacon-8.1-OFFICIAL-20180418-2004
    * `Security Patch Level:` April 5th, 2018 (I said late March, because I upgraded, then downgraded once I realized Syncthing wasn't working. Now that I've upgraded again, I want to make sure I don't have the same issue.)

* `Log:` https://pastebin.com/5wKBnEqJ (I thought the log would be too long to paste here directly.)
    * I do believe I have the `Termux: golang` package installed.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by AudriusButkevicius** [comment]
Actually just upgrade to latest version, this was fixed.
