### ISSUE TITLE
"Web View" causes CPU usage even when it is no longer visible.

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#1064]
Yet Another CPU Usage Issue.

1. Open Syncthing (when it is configured to be running)
2. Menu -> Web GUI
3. Quickly, before the web GUI fully rendered (while it is still spinning the "Waiting for GUI" spinner), press back
4. Repeat "2." and "3." multiple times, stacking opened-but-hidden web GUIs
5. Now CPU usage by `com.nutomic.syncthingandroid` stays high (and persists even when Syncthing shuts down), also Web GUI stops loading anymore.

The more repititions of "4.", the more CPU is used during and after Syncthing session.

Abnormal CPU usage starts even if Web GUI is entered only once (regardness of if it is exited by pressing back or not).

### Version Information

    App Version: 0.10.8
    Syncthing Version: v0.14.46+...
    Android Version: Android 4.4

**Comment by Catfriend1** [comment]
@vi Hi, do you use a proxy on your network?

**Comment by vi** [comment]
No.

**Comment by Catfriend1** [comment]
I'll try to reproduce it on my test device.

**Comment by AudriusButkevicius** [comment]
https://stackoverflow.com/questions/3130654/memory-leak-in-webview

This talks about it, it seems that we might need to call mWebView.destroy() and override onDestroy callback, but it seems there might be references still held to it, so perhaps the second answer with the frame is a better option (we should just check that clicking on links still works)

**Comment by Catfriend1** [comment]
Are those may chromium consoles after trying to reproduce it as described above a leak indicator?
![screenshot_20180430-142509](https://user-images.githubusercontent.com/16361913/39427041-91c00fa4-4c82-11e8-8284-a84117e97428.png)

**Comment by AudriusButkevicius** [comment]
Potentially
