### ISSUE TITLE
Failed to start Syncthing on Onyx-Boox Cleopatra 3 under Android 4.0.4

### ISSUE THREAD

**Issue by w201403** [syncthing/syncthing-android#1065]
E-book reader Onyx-Boox MC_Cleopatra3 Android 4.0.4
kernel ver. 3.0.35
jenkins@ubuntu-build-server #1
Fri Jul 21 18:58:40 CST 2017

# what happened
Syncthing don't letting me customize and use itself.

# what you expected to happen instead
I've expected the same exellent synchronization like on smartphone.

# and any steps to reproduce the problem.

## It probably be better to show the photoes..
Sorry if I doing something wrong. I just want to be more understandable. 
Screenshots couldn't be upload for unknown reasons. I can give a links on them
[1.](https://yadi.sk/i/CZBth5Jv3UqdcT)
[2.](https://yadi.sk/i/8nD_1YWg3Uqe7F)
[3.](https://yadi.sk/i/PX6vZ_zR3UqeA6)
[4.](https://yadi.sk/i/28ZZtdW43UqeE4)
[5.](https://yadi.sk/i/dl_LTLUB3UqeFy)
[6.](https://yadi.sk/i/JzlQ8mM73UqeKT)

### SyncthingRunnable
```
04-27 13:53:50.670 I/SyncthingRunnable(3669): Syncthing exited with code 11
04-27 13:53:50.670 W/SyncthingRunnable(3669): Syncthing has crashed (exit code 11)
04-27 13:53:50.890 I/System  (3669): 	at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:152)
04-27 13:53:51.740 I/SyncthingRunnableIoNice(3669): ionice performed on libsyncthing.so
04-27 13:53:51.740 I/System  (3669): 	at com.nutomic.syncthingandroid.service.SyncthingRunnable$1.run(SyncthingRunnable.java:205)
04-27 13:53:51.740 E/SyncthingRunnableIoNice(3669): Failed to set ionice 1
04-27 13:54:48.600 I/SyncthingRunnable(3669): Syncthing exited with code 11
04-27 13:54:48.600 W/SyncthingRunnable(3669): Syncthing has crashed (exit code 11)
04-27 13:54:48.620 I/System  (3669): 	at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:152)
04-27 13:54:49.570 I/SyncthingRunnable(3669): Syncthing exited with code 11
04-27 13:54:49.570 W/SyncthingRunnable(3669): Syncthing has crashed (exit code 11)
04-27 13:54:49.720 I/System  (3669): 	at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:152)
04-27 13:54:49.740 I/SyncthingRunnableIoNice(3669): ionice performed on libsyncthing.so
04-27 13:54:49.740 I/System  (3669): 	at com.nutomic.syncthingandroid.service.SyncthingRunnable$1.run(SyncthingRunnable.java:205)
04-27 13:54:49.740 E/SyncthingRunnableIoNice(3669): Failed to set ionice 1
04-27 13:54:50.530 I/SyncthingRunnableIoNice(3669): ionice performed on libsyncthing.so
04-27 13:54:50.530 I/System  (3669): 	at com.nutomic.syncthingandroid.service.SyncthingRunnable$1.run(SyncthingRunnable.java:205)
04-27 13:54:50.530 E/SyncthingRunnableIoNice(3669): Failed to set ionice 1
```
### SyncthingRunnableloNice

```
04-27 13:53:51.740 I/SyncthingRunnableIoNice(3669): ionice performed on libsyncthing.so
04-27 13:53:51.740 E/SyncthingRunnableIoNice(3669): Failed to set ionice 1
04-27 13:54:49.740 I/SyncthingRunnableIoNice(3669): ionice performed on libsyncthing.so
04-27 13:54:49.740 E/SyncthingRunnableIoNice(3669): Failed to set ionice 1
04-27 13:54:50.530 I/SyncthingRunnableIoNice(3669): ionice performed on libsyncthing.so
04-27 13:54:50.530 E/SyncthingRunnableIoNice(3669): Failed to set ionice 1
```

Other log files was empty

# Version Information

    App Version: hmm.. what App do you mean?
    Syncthing Version: v0.10.8
    Android Version: Android 4.0.4

Thank You very much for help!
Syncthing is very needed and important program for me.

**Comment by AudriusButkevicius** [comment]
As the issue template explains, please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
