### ISSUE TITLE
Web GUI does not load sometimes

### ISSUE THREAD

**Issue by vsespb** [syncthing/syncthing-android#1082]
Android 7.1.1, Xiaomi Mi 6, MIUI 9.2.2.0
v0.10.8, google play, 0.14.46+1-g7f1c0a33

I tried to open web Gui. It does not load (it was worked yesterday, when I bought this new phone)

![screenshot_2018-05-07-14-21-07-590_com nutomic syncthingandroid](https://user-images.githubusercontent.com/1210230/39699561-64d636e6-5202-11e8-962d-10294bdc5617.png)

After maybe 5 minutes it loaded with empty device/folder list (in fact I have folders and devices).
![screenshot_2018-05-07-14-24-08-530_com nutomic syncthingandroid](https://user-images.githubusercontent.com/1210230/39699594-8c09c14c-5202-11e8-8143-38bca0f988e1.png)

SyncThing restart does not help. App kill from android app list helps.
Reproducible: sometimes. Maybe related to https://github.com/syncthing/syncthing-android/issues/1011

**Comment by Catfriend1** [comment]
Hi @vsespb !
Does it load when you use the debug build from https://build.syncthing.net/repository/download/SyncthingAndroid_Build/20345:id/debug/app-debug.apk and PR https://github.com/syncthing/syncthing-android/pull/1080 ? I've made some changes to the webgui dialog stuff to fix things. Would love to have your feedback on it - but, please backup your data first - its an unreleased version based on syncthing 0.14.47.

**Comment by vsespb** [comment]
it happens "sometimes". so If I run it and see no bug, it wont tell that bug is fixed at all.

**Comment by Catfriend1** [comment]
I narrowed down "sometimes" to if you repeatedly open, close the webgui without killing the app in between. This should be fixed by the pr. If not, we'll reopen the issue after 0.10.9 was released.
