### ISSUE TITLE
Syncthing app gets crashed.

### ISSUE THREAD

**Issue by Sammaz2** [syncthing/syncthing-android#1090]
### Actual behavior
I opened the syncthing open android app. And then there appears loading web gui. I clicked the back arrow present on the top left corner and then i clicked on the options present on the top left corner. After that I clicked on the settings and then i opened the syncthing options. After all this i clicked on the incoming rate limit and then i putted numbers, and clicked on ok. Suddenly the app crashed. Second time I clicked on outgoing rate limit and there I putted some numbers, and then clicked on ok. The app suddenly crashes. Third time i removed all numbers in both incoming as well as outgoing and clicked on ok. Same was the case with that. The app crashed.

### How to reproduce
* First you need to download the app from fdroid and then install it, open it.

* Click on the back arrow present on the top left corner.

* Then click on the options present on the top left corner.

* After that open the settings option.

* There click on the incoming rate limit and then put some numbers and click on ok. Suddenly the app will crash.

* U can also try in outgoing rate limit. Same is the case with that, app crashes.

* Or if we remove the numbers in both incoming as well as outgoing then press ok. App suddenly crashes.

https://youtu.be/wwa7YdqnWI8

* Browser: syncthing.

* Version:0.10.8

* Operating system:7.1.2

* Device model: Redmi 4

**Comment by Catfriend1** [comment]
Thanks for reporting it. I think it will be fixed in the next release as the do stuff in the background on settings change was fixed by Nutomic.

**Comment by Catfriend1** [comment]
Thanks for the log excerpt. I'll probably have time to look into it on sunday and test it.

**Comment by Catfriend1** [comment]
Does this also occur with debug build https://build.syncthing.net/repository/download/SyncthingAndroid_Build/21224:id/debug/app-debug.apk ? Note: please backup first before trying, this is not a release.

**Comment by Catfriend1** [comment]
Ah okay my fault. I finally got it reproduced. The number has to be higher "than max int value". So for small numbers it works correctly, higher numbers cause a crash.

**Comment by AudriusButkevicius** [comment]
Regardless of why, there is no reason to crash.

**Comment by Catfriend1** [comment]
Its the parseInt

**Comment by AudriusButkevicius** [comment]
Sure, we should catch the exception and print that it's an invalid number, not crash.
