### ISSUE TITLE
F-Droid build is failing

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing-android#1091]
https://f-droid.org/wiki/page/com.nutomic.syncthingandroid/lastbuild_4143

Not sure what that binary file is for, and if the error should be fixed in Syncthing or in F-Droid.

**Comment by licaon-kter** [comment]
Is that needed during compilation?

Maybe we can just `scandelete=syncthing/src/github.com/syncthing/syncthing/lib/model/testdata/tmpfile` it?

**Comment by licaon-kter** [comment]
Fixed and build already. 

/close this
