### ISSUE TITLE
Syncthing annihilating the battery on my and my girlfriend's phones.

### ISSUE THREAD

**Issue by teraniadan** [syncthing/syncthing-android#1094]
* My phone: HTC U11+ (128GB, 6GB RAM). Android 8
* Girlfriend's: Sony XZ Premium (64GB, 4GB RAM). Android 8
* Syncthing: Latest Android version: 0.10.10
* Setup: Automatic OR Manual sync, default settings.

_________________________________________

Ever since I installed and setup Syncthing on both our phones we've barely been able to get 12 hours of battery life out of them. You can see from the screenshots below that we used to get 3 days of moderate use or a full day of heavy use.

The battery drain is worse than I have ever seen from any other app. As soon as Syncthing is disabled on our phones the battery drain stops and I can confirm this is the ONLY app that I have installed in the last week and only change that has been made on both phones.

Here's my HTC U11+ phone battery usage after installing and configuring Syncthing to share 3 folders between my unRAID server and our 2 phones:

1. https://i.imgur.com/H2ShVOz.jpg (Syncthing is orange)
2. https://i.imgur.com/PVVGo3R.jpg (Syncthing is maroon)
3. https://i.imgur.com/rkUFnRB.jpg (Syncthing is maroon)

Here is the same battery drain on my girlfriends phone after installing and configuring the same folders:

1. https://i.imgur.com/kdVgjvT.png (Syncthing is maroon)
2. https://i.imgur.com/ahSt2BY.png (Syncthing is maroon)

As I said, as soon as the app is disabled the battery drain stops. Rebooting our devices doesn't solve the problem and neither does even turning on Battery Optimisation for the app.

I've also tried turning off automatic sync but it STILL causes the exact same amount of drain. Honestly all I can do is uninstall or disable the app from the system menu to stop the battery drain. As soon as that's done it stops.

We've had to stop using the app entirely because we can't get more than 12 hours of use out of our phones and they used to last 3 days with moderate usage. It seems to start at selected times, like 4:00pm, 8:00pm etc. and then just goes on until I disable or uninstall the app. I hope someone can narrow down this problem.

**Comment by wweich** [comment]
What does the web ui or the logs say? Any errors or other problems?
What folders do you try to sync (you can't sync ext SD)?

I think, something on your phones / configuration prevents syncthing from working correctly, which causes it to try forever and drain the battery.

**Comment by AudriusButkevicius** [comment]
Anyways, this is a forum discussion as there is nothing actionable here.

**Comment by Catfriend1** [comment]
Does turning off global, local discovery and nat in syncthing options help? Please give me feedback on the forum if you use these options for device linkage.
