### ISSUE TITLE
Broadcast intents not working on Android 8.1

### ISSUE THREAD

**Issue by acornsirup** [syncthing/syncthing-android#1096]
Hello,
I upgraded from a phone using LineageOS 14.1 (Android 7.1) to another one using LineageOS 15.1 (Android 8.1).
Previously I was able to start and stop Syncthing by using the [broadcast intents](https://github.com/syncthing/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents).
This does not work anymore. What kind of logs do I need to provide?
Thank you.

**Comment by AudriusButkevicius** [comment]
You should get a logcat output as the intent is fired off.

**Comment by acornsirup** [comment]
`W/BroadcastQueue( 1189): Background execution not allowed: receiving Intent { act=com.nutomic.syncthingandroid.action.STOP flg=0x10 } to com.nutomic.syncthingandroid/.receiver.AppConfigReceiver`
Seems to be the only related log item.

**Comment by Catfriend1** [comment]
Duplicate, see https://github.com/syncthing/syncthing-android/issues/995
