### ISSUE TITLE
Wrong text on "Loading Spinner UI"

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing-android#1100]
The text shows "generating keys" during restart of the syncthing binary when it's not doing that step.

Reason:
On first app launch, an extra is put telling "hey this is first app launch". The Spinner UI dialog code picks it up and tells "generating keys". It also picks up the first launch extra (only used within the spinner UI code) when the first app assistant was completed and the user configures something and then restarts syncthing binary.

I'll make a PR to set the EXTRA_FIRST_START flag to false after the first-run syncthing binary initialization completed properly as this only will affect the spinner. Maybe we should rename it to something like EXTRA_KEY_GENERATION_IN_PROGRESS

### Version Information
    App Version: 0.10.10
    Syncthing Version: v0.14.47
    Android Version: Android 7.1.2 LOS

**Comment by Catfriend1** [comment]
Closed by https://github.com/syncthing/syncthing-android/pull/1101

**Comment by AudriusButkevicius** [comment]
You should put `(fixes #xxxx)` in your PR names.
