### ISSUE TITLE
GUI password and API key is logged to logcat

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing-android#1107]
Reproducer
Install Catlog app or use "adb logcat" and capture a log while syncthing is running. After a config change or reload, the config - including the sensitive password/key data - is dumped to the log output.

Suggestion
Depending on point of view, this can be considered a potential security leak under special circumstances. The API key and password should be replaced by generic tags before dumping parts of the config for easier debugging.

App Version: 0.10.10 (newer commits and previous releases)
Syncthing Version: v0.14.47
Android Version: Android 7.1.2

**Comment by AudriusButkevicius** [comment]
Syncthing doesn't dump them, so it's best you remove the logs that log it in the app.

**Comment by Catfriend1** [comment]
I'll submit a PR but not today :-)
