### ISSUE TITLE
Add Asus file explorer to Sync in Android

### ISSUE THREAD

**Issue by victorjagu** [syncthing/syncthing-android#1110]
Hello,
I'm using sync for a while and it works like a charm!
I just want to ask if there's a possibility of adding Asus file manager to Sync in Android's platform, so we can use it to access directly the sync folders.
Thank you very much
Best regards,
Victor

**Comment by AudriusButkevicius** [comment]
We don't "whitelist" specific applications, applications have to register themselves as being able to handle certain item types, which seems your specified application dows not, hencw the problem is on the other side.
