### ISSUE TITLE
Feature request: panic button support

### ISSUE THREAD

**Issue by ZJaume** [syncthing/syncthing-android#1127]
### Expected behaviour
Appear on the list of Ripple Panic and having the option to configure behaviour. The options could be:

- Hide the app
- Erase configuration (especially keys or ids of the folders and paired devices)
- Erase the content of the shared folders (or maybe select which folders want to delete)
### Resources
[https://guardianproject.info/2016/01/12/panickit-making-your-whole-phone-respond-to-a-panic-button/](url)
[https://dev.guardianproject.info/projects/panic/wiki/](url)

**Comment by AudriusButkevicius** [comment]
No, if you need that, make sure your OS has support for that.

**Comment by Catfriend1** [comment]
Note : Android 7+ also has a panic button support meaning a different thing (pressing back shortly one after another press multiple times to get back to the home screen). The emergency deletion can be handled by the OS. If you setup your synced folders within the Android/data/com.nutomic.syncthingandroid/files folder your synced data, keys and setting would be all gone on uninstall of the app. Maybe you find a tool which can trigger an apps uninstall "on panic kit action". Please take into account that a lost phone probably may not have internet connectionto trigger one of those suggested options...
