### ISSUE TITLE
FR: Publish Gradle build log as an artifact

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing-android#1128]
Hi,

In the build log of teamcity there is a line xx issues found with a link to file:///opt/buildagent/work/19a8ed19ae4d1032/app/build/reports/lint-results.html
Can we please publish this as an artifact so one can look into them if its not causing too much time expense?

**Comment by AudriusButkevicius** [comment]
Enabled for non-release builds

**Comment by Catfriend1** [comment]
Thank you very much 👍
