### ISSUE TITLE
Leak probability in SyncthingService.AsyncTask

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing-android#1135]
![image](https://user-images.githubusercontent.com/16361913/41336699-5632019e-6eed-11e8-9511-e71db0e5d3cb.png)

![image](https://user-images.githubusercontent.com/16361913/41336705-58cfdc0a-6eed-11e8-9334-6398da4a12c6.png)

see build warnings [lint-results.zip](https://github.com/syncthing/syncthing-android/files/2097072/lint-results.zip)

    App Version: 0.10.11 (and earlier)
    Syncthing Version: v0.14.48
    Android Version: Android 7.1.2

**Comment by Catfriend1** [comment]
@AudriusButkevicius I investigated the build warnings and found - according to https://stackoverflow.com/questions/44309241/warning-this-asynctask-class-should-be-static-or-leaks-might-occur/46166223#46166223 - we are using AsyncTask in a way leaks might occur when the service (or activity holding it) terminates while the long running background task is still running and later triggers onPostExecute.
My solution linked is working so far, but code looks very ugly as we've got a basic implementation problem with this since the syncthing wrapper exists.
That's also the reason why I did not pull request with this, I think the other three AsyncTask's (see build log) can easily be made safe and static but the main problem lies in SyncthingService:AsyncTask.

What do you think about my next thought to improve it:
- We drop SyncthingService:AsyncTask here and do the syncthing binary start synchronously. This won't block as in case of normal startup (app+syncthing binary) SyncthingRunnable moves the whole binary execution thing in a new thread. So we get back to onPostExecute very quickly in time.

- Now we've got a problem on app first start where keys should be generated. This code lies since the early days of this app in "doInBackground/new ConfigXml()/generatekeys" and I understand this was the reason for originally implementing the AsyncTask not to block the main thread for a long time (is this right @Nutomic ?)

- So I would move the key generation to FirstStartActivity with a progress bar or whatever indicator and launch the AsyncTask there as only SyncthingRunnable.run(GENERATE_KEYS) has to be moved to a static AsyncTask, we get a shorter and less confusing code - less prone to thread synchronization errors. (Currently, we can't make sure for all vars,classes, listeners onPostExecute() calls that they are still available when the "long enduring call" gets back)

Would be nice if you could give me feedback before a lot of time gets into fixing this.

**Comment by Nutomic** [comment]
I'm not sure if it's a good idea to start Syncthing synchronously. In that case, you only have one frame to start Syncthing (16.6ms), and that might not be enough on slow devices. But I don't remember what it does there exactly, so maybe time is not a problem.

I think it's a good idea to run key generation in the background in general. Otherwise, the key generation has to be restarted if the activity is closed (eg by swiping the app in the task manager). But this might not be a problem if the key generation is fast enough these days.

But actually, it should be relatively easy to fix this problem by turning the AsyncTasks into `private static class`. https://stackoverflow.com/a/44309450

**Comment by Catfriend1** [comment]
@Nutomic thanks for looking into this issue. Your last explanation was also the method to fix this on my linked commit above. Maybe this messy code that we get then can be cleaned up by implementing a listener to trigger the on postexecute. Also, onpreexecute can be put on LaunchStartupTask. I'll think about that again and taking your feeeback into account. Then there would only be the doinbackground reaching out of static to the weak ref'd non static context and we can do null checks there.
