### ISSUE TITLE
syncthing-android builder down?

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing-android#1138]
Hi,
I've just opened a new PR and the TeamCity builder seems to be down:
![image](https://user-images.githubusercontent.com/16361913/41394524-8db1fc60-6faa-11e8-8619-5cca9a4640bd.png)
@calmh @AudriusButkevicius Is there currently any maintenance downtime expected?

**Comment by calmh** [comment]
No, but looks like it's been cleaned out. That's probably my fault, but I don't know the recipe for recreating it, unfortunately.

**Comment by Catfriend1** [comment]
Ok no hurry. Would be cool getting it back the next days. Until then I can use my private build server so I'm not blocked.

**Comment by calmh** [comment]
Once Audrius chimes in with the recipe for the image I'll set it up so it doesn't happen again.

**Comment by calmh** [comment]
Fixed. I've also added it as an automated build on docker hub and will make the build agent pull from there once it's done, so it can resolve this automatically if it happens again in the future.

**Comment by Catfriend1** [comment]
Thank you very much :-).

**Comment by Catfriend1** [comment]
Sorry to interrupt you again, but TeamCity seems to be down. Travis is currently working.

**Comment by calmh** [comment]
Build agent wasn’t connected because docker doesn’t auto start on that box after reboot, I blame systemd of course and haven’t had the energy to troubleshoot it. Coming up now.

**Comment by Catfriend1** [comment]
Hi,
I'am currently experiencing a new problem with the TeamCity builder at https://build.syncthing.net/viewLog.html?buildId=24859&buildTypeId=SyncthingAndroid_Build&tab=buildLog :  

@calmh  Do you have any ideas why it's not successfully building anymore?
Thanks for your help.

> [12:08:03]Publishing artifacts (3m:07s)
[12:08:03][Publishing artifacts] Collecting files to publish: [app/build/**]
[12:08:04][Publishing artifacts] Publishing 4263 files using [S3ArtifactsPublisher]: app/build/**
[12:08:04][Publishing artifacts] Publishing 4263 files using [ArtifactsCachePublisher]: app/build/**
[12:11:10][Publishing artifacts] Failed to publish artifacts: Failed to upload artifacts into bucket kastelo-builds: 
java.io.IOException: Failed to upload artifact intermediates/incremental/mergeDebugResources/merged.dir/values-bn/values-bn.xml to https://ams3.digitaloceanspaces.com/kastelo-builds/SyncthingAndroid/SyncthingAndroid_Build/24859/intermediates/incremental/mergeDebugResources/merged.dir/values-bn/values-bn.xml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20180805T120850Z&X-Amz-SignedHeaders=host&X-Amz-Expires=60&X-Amz-Credential=GP7ZT2VZXW5VMYBCGVQV%2F20180805%2Fams3%2Fs3%2Faws4_request&X-Amz-Signature=06be0e4ce53edfae9b0309a9db6bd5c4a757a68a6465231ea5ee258e307a0c32: received response code HTTP 502.
(...)
java.io.IOException: Failed to upload artifact intermediates/incremental/mergeDebugResources/merged.dir/values-hu/values-hu.xml to https://ams3.digitaloceanspaces.com/kastelo-builds/SyncthingAndroid/SyncthingAndroid_Build/24859/intermediates/incremental/mergeDebugResources/merged.dir/values-hu/values-hu.xml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20180805T120852Z&X-Amz-SignedHeaders=host&X-Amz-Expires=59&X-Amz-Credential=GP7ZT2VZXW5VMYBCGVQV%2F20180805%2Fams3%2Fs3%2Faws4_request&X-Amz-Signature=09d86f3a38926db9b3b1564c8c107b92100ae23e52545bb7c82a204836555b6b: received response code HTTP 503.
[12:11:10]Build finished

**Comment by calmh** [comment]
Freak storage oddity

**Comment by calmh** [comment]
Because

<img width="850" alt="screen shot 2018-08-05 at 18 49 55" src="https://user-images.githubusercontent.com/125426/43687975-6e64a8da-98e0-11e8-9cb8-2daf30b8bf44.png">

but by all means narrow that down to something more useful. It doesn't matter greatly though - the error above is from me experimenting with DO Spaces (S3-like object storage) as a backend, and that's clearly not stable yet. I'm going to move the Syncthing build server to one of my physical boxes at Hetzner (Xeon/32GB/2TB mirrored) that is currently build slave, and then it'll have lots of free  disk space for artifacts without trickery.

**Comment by AudriusButkevicius** [comment]
I've locked that down a bit.

**Comment by Catfriend1** [comment]
@AudriusButkevicius Thanks for improving the Artifacts filter. It's now exactly what I need :)
![image](https://user-images.githubusercontent.com/16361913/43717787-e59a2d82-9988-11e8-84d9-c4791e27daba.png)
