### ISSUE TITLE
NPE in DrawerFragment if syncthing is terminated

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing-android#1148]
If syncthing was terminated while Drawer is expanded and run conditions change:
When the user then would hit "show qr code" a NPE occured before the PR. (see list in issue #1146)

Error Log
java.lang.NullPointerException: at com.nutomic.syncthingandroid.service.RestApi.getGui (RestApi.java:375) at com.nutomic.syncthingandroid.fragments.DrawerFragment.showQrCode (DrawerFragment.java:210) at com.nutomic.syncthingandroid.fragments.DrawerFragment.onClick (DrawerFragment.java:241)

**Comment by AudriusButkevicius** [comment]
Doesn't this apply on anything the user might click?

**Comment by Catfriend1** [comment]
Yes, we might have more PR's about this in the future to fix outstanding issues.
