### ISSUE TITLE
Default camera folder name is the same on multiple identical devices and should be unique

### ISSUE THREAD

**Issue by msiep** [syncthing/syncthing-android#1159]
After installing Syncthing for Android on two family member's phones that are the same make and model, I encountered confusing behavior where photos taken on one phone were showing up on the other.

The problem was caused by Syncthing on both phones coming by default with a camera folder with the same Folder ID, based on the device make and model ("lg-m210-photos" in this case).

I've now manually fixed the problem, by removing the folder on one device and recreating it with a different ID.

I hope future versions of the app will assign a default camera folder name that is almost certain to be unique, even on multiple identical devices.

For example, how about appending a couple of random letters, e.g. on these LG M210 phones the folder names might have defaulted to "lg-m210-photos-hz" and "lg-m210-photos-ej".

### Version Information

    App Version: 0.10.4
    Syncthing Version: v0.14.43
    Android Version: Android 7.0

**Comment by AudriusButkevicius** [comment]
Thanks for the report, yeah this is not ideal.

**Comment by AudriusButkevicius** [comment]
Can you check if the same happens with the latest version of the app?

**Comment by msiep** [comment]
Sure. I just installed it 0.10.11 on a Samsung Galaxy S4 (model SGH-M919) that had not had the app before and the Folder ID of its Camera folder is "sgh-m919-photos"

**Comment by AudriusButkevicius** [comment]
Are you saying that if you add a new folder it defaults to device ID? Because if someone else shares a folder, we'd copy their folder ID, so it would only happen on identical devices.

**Comment by msiep** [comment]
No, there's no problem when you add a _new_ folder. 

The problem is with the Camera folder that is there _by default_ when you install the app. Instead of the kind of random Folder ID you get when adding a new folder, it has a folder name that is completely determined by the device model, e.g. if it's an LG M210 the Folder ID will be "lg-m210-photos" on every LG M210 device and if it's a Samsung SGH-M919 (T-Mobile version of Galaxy S4) then the Folder ID will be "sgh-m919-photos" on every Samsung SGH-M919 device. 

The problem arose because two family members both have LG-M210 phones. Once the default camera folders on both of those devices were both shared with a common device (a laptop I use as a home server), Syncthing treated them as the same folder because they had the same Folder ID, so it started syncing photos taken from either phone onto both the server laptop and the other phone.

**Comment by Catfriend1** [comment]
Would a simple hack be okay as a fix when reading the appfirststartedtime datetimestamp and append the sum of digits to the folder id? It would then be rare to have the same id twice.

**Comment by AudriusButkevicius** [comment]
I think it's enough just generate a random 8 character string that does not have simillar symbols like 0OIl etc, like we do for syncthing.

**Comment by msiep** [comment]
I think it would be fine to just use a random name the same as when the user creates a new folder. For a new user, even though in one sense it might seem friendlier to have a meaningful Folder ID by default, in another sense it's actually a bit confusing since it seems to suggest that the Folder ID is supposed to be meaningful, when in fact it's supposed to be unique, and isn't supposed to need to be meaningful.
