### ISSUE TITLE
Missing .stfolder in default Camera folder

### ISSUE THREAD

**Issue by nobikik9** [syncthing/syncthing-android#1160]
Hello everyone!
Yesterday I bought a new phone. So tried to configure Syncthing to synchronize my default Camera folder (internal storage, it was already created) with a laptop (it's the first time I used Syncthing) . But I encountered a problem with synchronization, because "Folder Marker Missing" error was raised (to see the error I switched to the Web GUI). I found [#168](https://github.com/syncthing/syncthing-android/issues/168) and creating .stfolder folder resolved the issue. But anyway it required some some effort. Is it an intended behavior not to create .stfolder?

I also want to apologize if my question is bad/trivial/stupid (probably, the folder wasn't created because of default r/w permissions, not sure), but it's the first time for me to report a problem.
Thank you!

### Version Information

    App Version: 0.10.11
    Syncthing Version: v0.14.48
    Android Version: Android 7.1
    Phone: Xiaomi Readmi 5A

**Comment by Catfriend1** [comment]
@AudriusButkevicius  : Is it okay for you if we precreate .stfolder on new folder creation from the app UI via java code to circumvent the write permission problems? This would be a good workaround for people using android app just for sendonly folders.

**Comment by AudriusButkevicius** [comment]
No, because the marker can only be created if syncthings database is empty, if its not empty, it implies the storage disappeared, at which point pre-creating the marker would cause all files to be considered as deleted.

Unless the OP has a way to reproduce this, I am not sure there is much todo. If syncthing failed to create the marker, there would be an error in the logs. If the error is due to permission issue, then there is nothing we can do.

**Comment by nobikik9** [comment]
Hm... I cannot find any mention of the marker error in the log file. And I cannot reproduce the error with Android emulator either. Maybe I managed to mess up with Syncthing somehow, I'm no sure now. 
Anyway, thank you for your help.

**Comment by Catfriend1** [comment]
Yes and no, but if we reuse a folder that exists on the other we should be careful. Anyways, we don't have strange mount points on android. If one creates a folder with existing data in the path on sdcard and the card is removed, .stfolder cannot be written acidentially on that empty mount when saving the folder as android limits access to /mnt.

**Comment by AudriusButkevicius** [comment]
@imsodin sure, but the suggestion is for the wrapper to create it unconditionally on startup. 

On adding a folder it's probably on, not startup is probably not ok.

**Comment by Catfriend1** [comment]
I'd go with creating the marker on folder add via the wrapper UI. PR and testing from my side okay?
