### ISSUE TITLE
Forever scanning

### ISSUE THREAD

**Issue by DamienCassou** [syncthing/syncthing-android#1167]
One of the folders stays in "Scanning" mode for what seems to be forever. The folder is large (the whole /storage/emulated/0) but it was working fine last week. I'm expecting Syncthing to stop displaying "Scanning" next to the folder name.

### Version Information

    App Version: 0.14.48-dirty (f-droid)
    Syncthing Version: v0.10.11
    Android Version: Android 8.1.0 / LineageOS 15.1 (nightly, updated today)

**Comment by DamienCassou** [comment]
```
06-26 08:03:31.516 W/chmod   (7215): type=1400 audit(0.0:8): avc: denied { setattr } for name="libsyncthing.so" dev="dm-0" ino=1532011 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0
```

**Comment by AudriusButkevicius** [comment]
The folder most likely contains something that is constantly changing, like a database or something.

**Comment by DamienCassou** [comment]
I hope that bug gets automatically fixed with #1168 (maybe Syncthing is just no doing anything anymore). I don't know which file/folder could trigger this, especially as I don't think anything changed in the last days and it was working before.

**Comment by AudriusButkevicius** [comment]
If you do manage to start it up, there is "Recent changes" section in the web ui that shows what has recently changed, so you can try to understand where the changes are coming from.

**Comment by Catfriend1** [comment]
Btw scanning emulated/0 should e.g. exclude the .android_secure, Android and WhatsApp (database) folder. Android folder contains the syncthing.log constantly changing. Try syncing a smaller part or subfolder first for diagnosis.

**Comment by DamienCassou** [comment]
> .android_secure

I can't find this file on my phone. Is it at the root?

> Android

I'm not sure what this folder contains exactly but it seems it could be important to restore my phone: I'm using this Syncthing folder as a way to backup my phone to my laptop which is backed up separately.

Nevertheless, I confirm that ignoring `Android/`fixed my problem. Thank you.

> and WhatsApp

I don't use that.

> Android folder contains the syncthing.log constantly changing

it would be nice to have error messages regarding such files. That way, I could ignore only those and keep the rest synching.

> Try syncing a smaller part or subfolder first for diagnosis.

2 other folders seems to be syncing fine
