### ISSUE TITLE
Non existing 'Crash Reports' directory

### ISSUE THREAD

**Issue by DamienCassou** [syncthing/syncthing-android#1169]
I can see that in my logs:

    06-26 08:04:09.636 W/cr_CrashFileManager(7166): /data/user/0/com.nutomic.syncthingandroid/cache/WebView/Crash Reports does not exist or is not a directory

### Version Information

    App Version: 0.14.48-dirty (f-droid)
    Syncthing Version: v0.10.11
    Android Version: Android 8.1.0 / LineageOS 15.1 (nightly, updated today)

**Comment by Catfriend1** [comment]
I'll have those too since switching from aosp webview to google webview app. This can be safely ignored.
