### ISSUE TITLE
Disable Syncthing in Flightmode

### ISSUE THREAD

**Issue by Wiiilmaa** [syncthing/syncthing-android#1173]
I use syncthing with conditions "run in background" "only if wifi active".
Theese settings cause syncthing to start, when flightmode is activated.
expected behaviour: Do not run syncthing in flightmode if Wifi is deactivated or not connected.

**Comment by Catfriend1** [comment]
I also experienced this problem before. I think its a question of what fits best to most users.
Personally, I disagree with the request as I'm often in flight mode when I don't need my mobile phone/data plan but having wifi enabled.  So syncthing definitely should run.

Anyways, I got your point, you want to have it off as you're not in the network you want. I think we should note this for my future-planned work on the run-conditions as I intent to suggest a refactor for that.
A suitable new option I would like to suggest is adding "Respect flight mode and put syncthing off" so users preferring your scenario can tick the box and others like me can sync when wifi-connected during flight mode. Compare it - e.g. to the app FolderSync - which has a similar option.

There are more tickets with discussion about more granular run conditions that are conceptually fitting the requirement that syncthing can sync both ways within an undefined timeframe when device come online.

**Comment by Wiiilmaa** [comment]
Your point is absolutely valid. I also have a tablet, which is in Flight Mode 100% of the time with Wifi enabled.
But is there no way to determine if Wifi is enabled (or even better connected)? I don't see why "only if wifi active" option has to start syncthing in Flightmode with no networks enabled..
In my opinion it fits best to all users, if "only if wifi active" option enables synthing "only if wifi is active" instead of "only if wifi active or ( wifi disabled and flightmode activated )"

**Comment by Catfriend1** [comment]
It is, user can decide by pref.
