### ISSUE TITLE
Windows project build exception

### ISSUE THREAD

**Issue by ninad458** [syncthing/syncthing-android#1179]
`./build-syncthing.bash`

Running the above command in cygwin gives the output as follows. Maybe I'm doing something wrong.

```
./build-syncthing.bash: line 2: $'\r': command not found
: invalid optiong.bash: line 3: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./build-syncthing.bash: line 4: $'\r': command not found
./build-syncthing.bash: line 29: syntax error near unexpected token `$'do\r''
'/build-syncthing.bash: line 29: `for ANDROID_ARCH in arm x86 arm64; do
```
Windows 8

**Comment by AudriusButkevicius** [comment]
Git checked out the files with windows line endings.

**Comment by ninad458** [comment]
@AudriusButkevicius Is there anything I have to do on my side to fix it?

**Comment by AudriusButkevicius** [comment]
Convert the line endings to unix

**Comment by Catfriend1** [comment]
According to https://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows
git config --global core.autocrlf false

**Comment by Catfriend1** [comment]
So I suspect this can be closed?

**Comment by AudriusButkevicius** [comment]
Not really, we should rewrite the build script in something runnable on windows.

**Comment by Catfriend1** [comment]
Related topic on the forum: https://forum.syncthing.net/t/how-to-build-syncthing-for-android-android-studio-in-windows/11814/20

**Comment by Catfriend1** [comment]
Closed by improved build script @AudriusButkevicius 
Quote from forum:
> Audrius Butkevicius Syncthing Maintainer 1d
The build script was rewritten, try building master and see what errors you get.

**Comment by Catfriend1** [comment]
**ninad458 commented 7 minutes ago**
Build Syncthing using ./gradlew buildNative.When I ran ./gradlew buildNative on powershell, I gotConfigure project :app Signing not ready. Did you specify a signingConfig for the variation Release?   FAILURE: Build failed with an exception.   What went wrong: Execution failed for task ':syncthing:buildNative'.  Process 'command 'python'' finished with non-zero exit value -1073741515
--

**Comment by Catfriend1** [comment]
perhaps do a ./gradlew lint first?

**Comment by ninad458** [comment]
@Catfriend1 I'm afraid that didn't work either. On a side note, the android studio build apk works( Just so that there is no confusion).

**Comment by AudriusButkevicius** [comment]
Do you have python installed? It seems you don't? Or its not on the PATH envirinment variable.

**Comment by ninad458** [comment]
There were two versions of python involved. I removed the 3.x version from the path. Then the script ran. But unfortunately I think, there is a problem with my machine.
I'm getting the following error:
````
Building for arm
Building syncthing
runtime/cgo
# runtime/cgo
In file included from _cgo_export.c:2:
In file included from C:\Users\user\Desktop\training\syncthing-android\syncthing\gobuild\standalone-ndk\android-16-arm\b
in\..\sysroot/usr/include\stdlib.h:34:
In file included from C:\Users\user\Desktop\training\syncthing-android\syncthing\gobuild\standalone-ndk\android-16-arm\b
in\..\sysroot/usr/include\malloc.h:22:
In file included from C:\Users\user\Desktop\training\syncthing-android\syncthing\gobuild\standalone-ndk\android-16-arm\b
in\..\sysroot/usr/include\stdio.h:42:
In file included from C:\Users\user\Desktop\training\syncthing-android\syncthing\gobuild\standalone-ndk\android-16-arm\b
in\..\sysroot/usr/include\sys/types.h:36:
C:\Users\user\Desktop\training\syncthing-android\syncthing\gobuild\standalone-ndk\android-16-arm\bin\..\sysroot/usr/incl
ude\linux/types.h:21:10: fatal error: 'asm/types.h' file not found
exit status 2
exit status 1
Traceback (most recent call last):
  File "./build-syncthing.py", line 119, in <module>
    ] + pkg_argument + ['-no-upgrade', 'build'], env=environ, cwd=syncthing_dir)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'run', 'build.go', '-goos', 'android', '-goarch', 'arm', '-pkgdir', 'C:\\
Users\\user\\Desktop\\training\\syncthing-android\\syncthing\\gobuild\\go-packages\\arm', '-no-upgrade', 'build']' retur
ned non-zero exit status 1
````
**Although I think it is safe to assume that there is not an issue with the project. So it seems, this issue should be closed now.**

**Comment by AudriusButkevicius** [comment]
Seems like an issue with the NDK paths.
