### ISSUE TITLE
ANR probability during run conditions UI stress test

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing-android#1196]
There is an ANR problem already on my bugs-to-fix todo list. The ANR happens when you stress test the run conditions UI and change the checkboxes too quickly one after another. Since we've synchronized stuff to wipe out race crashes, the ANR is more suspect to happen. GPlay console proves this by a slightly higher ANR rate since app version 0.10.11.

Maybe related to issue: #1193 "Run conditions disregarded"

### Version Information
    App Version: 0.10.12, 0.10.11
    Syncthing Version: v0.14.49
    Android Version: Android 7.1.2

**Comment by AudriusButkevicius** [comment]
I don't think this can have anything todo with ANR.

**Comment by Catfriend1** [comment]
@AudriusButkevicius Not directly. But I got it to reproduce more than 5 times on my phone. It's a timing issue if the RunConditionsMonitor immediately follows the UI check box ticks/unticks and the user does it so fast. The fast response to pref changes as it's always been in this app is good for development but bad for users as they just can help themselves against the ANR by force-closing the app when the screen turns "black". My suggestion by the PR #1197 is to "apply" the changed preferences when the user quits the prefs screen or presses the home button.

**Comment by AudriusButkevicius** [comment]
Why would a race on the checkboxes or values on the config or whatever cause the application to hand?

**Comment by Catfriend1** [comment]
Android considers the app hanging if the main thread is allocated for more than x seconds (for service mode 5 seconds since android 8+). Then it issues warnings in the logcat about this. Newer android's halt the process completely forever (see GPlay Console ANR reports). If you stress test the conditions and toggle the "apps decision" fastly from "false" to "true" to "false" and so on, messages got sent via the onPrefsChangedListener and queued up, so you end up on permanently starting and ending syncthing on the main service thread. Plus delays that has always been in there to allow safe startup, polling and shutdown you get a delay "per on/off cycle" from 2 to 3 seconds. More cycles --> ANR.
