### ISSUE TITLE
Adding a folder from internal sd card causes syncthing to crash

### ISSUE THREAD

**Issue by jtrees** [syncthing/syncthing-android#1201]
### Steps to Reproduce

1. Tap "Create folder" icon
2. Enter a folder label
3. Select a directory that starts with `/storage/emulated/0/` (e.g. `/storage/emulated/0/Alarms`)
4. Tap "Create" icon

### Expected Result

The folder should be created.

### Actual Result

The app crashes.

    Syncthing has stopped

### Version Information

    App Version: 0.10.12 (F-Droid)
    Syncthing Version: v0.14.49-dirty
    Android Version: Android 8.0.0 (Samsung)
    Rooted/Unlocked Bootloader: no

**Comment by AudriusButkevicius** [comment]
This is fixed in the next version. I forgot to push the tags to git, so F-Droid should pick it up shortly.
