### ISSUE TITLE
Disable symlinks sync on internal storage

### ISSUE THREAD

**Issue by ranfdev** [syncthing/syncthing-android#1203]
When synching the symbolic links I get: "Operation not permetted".
The synchronization between my computer and my phone is stuck. Syncthing keeps trying to synchronize some symlinks, but it's impossible to create symbolic links inside the internal storage of android (at least on my phone). Syncthing should know this, and skip those files.

 

### Version Information

    App Version: 0.10.13
    Syncthing Version: v0.14.49
    Android Version: Android 8.1 (custom ROM)

**Comment by AudriusButkevicius** [comment]
This is probably should be raised as a bug report with syncthing, as the android UI doesn't have much say in this. Perhaps the answer is not to sync symlinks on android period, as syncthing itself has no idea if it's on internal storage or not.

As a workaround you can add (all...) symlinks to ignored files.
