### ISSUE TITLE
Syncthing upset saying not synced at Android end through 'ignore delete' flag

### ISSUE THREAD

**Issue by businessBoris** [syncthing/syncthing-android#1206]
1. Folder happily synced  "Alice" Samsung S6 Android 7.0 =>  "Bob" Desktop (Fedora Linux 28) [i.e. both latest and greatest]
2. Alice set to be SendOnly. Bob SendRecieve
3. Bob set IgnoreDelete

[effective double-down on ensuring files are never deleted from Bob by Alice]

4. Delete file from Alice. This happened as part of a regularly scheduled clean up in actual fact but no matter.
5. (syncthing syncs in the normal course of events)
6. Bob shows in sync, but obviously one more file local than global; through ignoredelete flag
7. Alice shows not in sync with the previously deleted file as the difference.

Bob: v0.14.49, Linux (64 bit) ; syncthing-0.14.49-1
Alice: v0.14.49 android (AArch64) ; App version 0.10.13 approx. 27 July 2018

Beta NOT enabled on Android Google Play; F-Droid accessible but not ruling presently.

**Comment by AudriusButkevicius** [comment]
Working as intended. Ignore delete is a local state, so remote devices will always think of you as out of sync.

**Comment by businessBoris** [comment]
I don't agree with you, but it's your program. ;D

**Comment by AudriusButkevicius** [comment]
I am just saying how it is from the implementation side and that this is expected behaviour. Sure, it could be more user friendly, but it is what it is.
