### ISSUE TITLE
Is there any event to listen for in automate/llama/etc when synced folder is changed?

### ISSUE THREAD

**Issue by kepi** [syncthing/syncthing-android#1224]
I would like to automate some action after specific synced folder is synchronized (when something change in it). It is possible to use inotify or something similar in automate but it seems to me little redundant.

Is there any way to do it? Listen for some intent, event notification?

In Wiki there are only intents for interacting with Syncthing, not listening for something from it.

**Comment by AudriusButkevicius** [comment]
Syncthing itself has a rest api you can query, that's what the android app does, but to do that you need the api key. There is no event or broadcast that is funneled to and queriable from android
