### ISSUE TITLE
Feature Request: Different synchronisation conditions per folder

### ISSUE THREAD

**Issue by cdrfun** [syncthing/syncthing-android#1225]
Hi there, it would be great if you could define different synchronisation conditions per folder.

**Possible use case**:

- One folder which is important should always be up to date - no matter if I'm on WiFi or battery. For me this would be my folder with the password manager database.
- Other folders like photos could be synched only with WiFi and/or battery.

Would this be possible given the current architecture? 

What do you think about this idea, aside from technicalities.

Greetings!

**Comment by Otiel** [comment]
Duplicate #511
