### ISSUE TITLE
0.14.49 (latest for Android right now) has hang bug

### ISSUE THREAD

**Issue by JonasT** [syncthing/syncthing-android#1226]
It appears that the Android fork is still on 0.14.49 even though it has this showstopper bug that basically made the app useless for me half a month ago with no workaround that I'd know off: https://forum.syncthing.net/t/oneother-item-stuck-in-out-of-sync-items/11938

I assume this is a volunteer effort, so I just wanted to point this issue with the currently shipped version in case you weren't aware. (and that a syncthing core version bump would be super helpful if you find the time to squeeze it in whatever the regular release schedule is)

### Version Information

    App Version: 0.10.13
    Syncthing Version: v0.14.49
    Android Version: LineageOS 14.1

**Comment by JonasT** [comment]
Since there still doesn't seem to be an update in f-droid and this has been broken for many months, I don't see many other options for me than to move to another software... :cry: kind of sucks, syncthing is pretty neat

**Comment by AudriusButkevicius** [comment]
@licaon-kter any ideas why fdroid is still on 0.10.13?
It seems 0.10.14 is in the metadata https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.nutomic.syncthingandroid.txt#L698

**Comment by AudriusButkevicius** [comment]
@JonasT I can only suggest trying to download the APK from gplay. There is also a beta release with fixes backported from the fork.

**Comment by imsodin** [comment]
The problem is #1047 and their build server not having go1.9 anymore. We really need to find the cause of that (well, create a reproducer to report upstream). I tried a one or two months ago and gave up after failing a few times...

**Comment by licaon-kter** [comment]
@imsodin I was doing the same, thanks for being quicker ;)

**Comment by licaon-kter** [comment]
@AudriusButkevicius 

Builds live (kinda): https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500

Failed builds (updated at the end of the cycle): https://f-droid.org/wiki/page/Category:Apps_with_failing_builds

Your favourite app status: https://f-droid.org/wiki/page/com.nutomic.syncthingandroid ( on top right see updated and last buildlog, scroll down for versions status)

**Comment by licaon-kter** [comment]
@JonasT Refresh F-Droid repos ;)

**Comment by AudriusButkevicius** [comment]
Closing. If bad stuff still happens, scream.
