### ISSUE TITLE
Feature Request: Quit button

### ISSUE THREAD

**Issue by JonasT** [syncthing/syncthing-android#1227]
Right now, the syncthing app is useless for me ( #1226 ) but happily burns through 100% CPU usage doing nothing (probably related to that bug). Now I would simply turn it off - except that I don't know how. Last time I used "Force Stop", it corrupted the database and broke everything, and there is no Quit button in the menu, just "Restart", which isn't very helpful for terminating a buggy version indefinitely.

Therefore, please add a "Quit" button to be able to safely turn off syncthing without risking database breakage that may require me to wipe all settings to get it to work again - that is what happened last time when I force stopped it

### Version Information

    App Version: 0.10.13
    Syncthing Version: v0.14.49-dirty
    Android Version: LineageOS 14.1

**Comment by JonasT** [comment]
Oh. Just realized this is because of the always run in background option.

That does seem a little silly. Why not make a "Launch when Android starts" option, and allow Exit at any time? The way it's currently done seems very non-intuitive... especially since I'm also confused about whether disabling the always run in background means there won't be a service anymore? So will it get stopped by Android all the time when it goes in background? Because that's not really something I want to change, I just want to terminate it for now so I can relaunch it when this issue is fixed. (changing the always background thing I'm somewhat bound to forget and reset back...)

**Comment by AudriusButkevicius** [comment]
The way it works now is how android deals with this. Its either a service that runs always or it's an app, and runs when you open it. If you register the app as a service android makes sure its running etc. 

What does force quit even mean in that context?
Turning it off from being a service? Which means it won't auto start...

#1223 has more discussions.

**Comment by JonasT** [comment]
Ok, I'll make a feature request with a more concrete suggestion then
