### ISSUE TITLE
The application is not fully translated into Russian

### ISSUE THREAD

**Issue by Rakleed** [syncthing/syncthing-android#1236]
### What happened
In the Russian localization in the application is not translated text, also some translations are made with errors.

### What you expected to happen instead
The application is fully translated into Russian and there are no errors in the localization.

### Screenshots
<details><summary>Screenshots where the translation is missing completely</summary>

![screenshot_20181023-123454_syncthing](https://user-images.githubusercontent.com/19418601/47361096-cbc91380-d6d9-11e8-85bc-963fa53ab0f0.png)

![screenshot_20181023-123501_syncthing](https://user-images.githubusercontent.com/19418601/47361101-cff53100-d6d9-11e8-8652-fd0c6339d6d7.png)

![screenshot_20181023-123520_syncthing](https://user-images.githubusercontent.com/19418601/47361113-d4214e80-d6d9-11e8-8c48-24daa20c6459.png)

![screenshot_20181023-123802_syncthing](https://user-images.githubusercontent.com/19418601/47361132-e00d1080-d6d9-11e8-83da-8f912babfec4.png)

![screenshot_20181023-131540_syncthing](https://user-images.githubusercontent.com/19418601/47361171-f7e49480-d6d9-11e8-8fcb-b0c961a459d8.png)

![screenshot_20181023-131543_syncthing](https://user-images.githubusercontent.com/19418601/47361189-ffa43900-d6d9-11e8-834f-d846ac3ecd0f.png)

![screenshot_20181023-123837_syncthing](https://user-images.githubusercontent.com/19418601/47361209-08950a80-d6da-11e8-9003-4f81c739a3ce.png)

</details>
<details><summary>Screenshot where the translation is made with errors</summary>

![screenshot_20181023-123837_syncthing 2](https://user-images.githubusercontent.com/19418601/47361085-c4a20580-d6d9-11e8-9456-8fab26aaf733.png)

</details>

### Version Information
App Version: 0.10.14
Syncthing Version: v0.14.50
Android Version: Android 8.1.0 / LineageOS 15.1

**Comment by licaon-kter** [comment]
https://www.transifex.com/projects/p/syncthing-android/

Login-Github-....

Join Team....wait for confirmation....fix it yourself

Cheers
