### ISSUE TITLE
Trouble modifying ignore patterns

### ISSUE THREAD

**Issue by gradha** [syncthing/syncthing-android#1239]
When I try to edit the ignore patterns of a folder, my text editor (Markor) opens up but shows a weird banner at the top, stating that nothing can be saved because there are no permissions given and changes will be lost.

![edit patterns](https://user-images.githubusercontent.com/101927/47869608-accc2f00-de07-11e8-8ee4-1275ef269d72.png)

It is thus impossible to edit ignore patterns. If I uninstall Markor then I get a toast saying there is no editor. I don't think a full blown editor should be needed for typing in patterns, but if so, it would be at least handy to get a link to an application which works along syncthing.

### Version Information

    App Version: 0.10.14
    Syncthing Version: v0.14.50
    Android Version: Android 8.1.0 MIUI 10.0.2.0

**Comment by AudriusButkevicius** [comment]
You probably need to grant permissions to the editor?

**Comment by gradha** [comment]
There was something weird with that, system preferences said it had permissions. After uninstalling and installing again the note doesn't show up, but the edition doesn't work anyway. Whatever is written into a hypothetical `.stignore` file does not persist.

**Comment by AudriusButkevicius** [comment]
Try a different editor? ES File Explorer has a notes editor (yet be aware it's a very malware'y app that wants permissions for everything)

**Comment by gradha** [comment]
Thanks, did switch to fork.
