### ISSUE TITLE
Status Update: External SD Card Support

### ISSUE THREAD

**Issue by josephernest** [syncthing/syncthing-android#1245]
I've already read https://github.com/syncthing/syncthing-android/issues/1008, [the FAQ](https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions#user-content-what-about-sd-card-support), [this reddit thread](https://www.reddit.com/r/Syncthing/comments/64mazv/problem_syncing_folder_on_external_sd_card_on/), [this bounty](https://www.bountysource.com/issues/2523046-repositories-on-extsdcard), but I thought that maybe, now nearly one year later, there's an update?

**Are there (not too difficult-to-use) workarounds to have write support on external SD card, for a standard non-rooted Android?** (Rooting is currently not an option).

If not, what is the planned schedule for this feature? One month, one year, five years? 

(If not available, I'll sadly be unable to use SyncThing which seems super great otherwise, but my phone's internal SD card is simply too small to host the folder I need to sync).

Congratulations to all the team for this wonderful project.

**Comment by AudriusButkevicius** [comment]
Please don't open pointless tickets, if there was any progress it would have been made as a comment on the original ticket.

There has been no progress, and there is no schedule.

**Comment by daviewales** [comment]
@josephernest Note that [using Syncthing's application specific directory](https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions#what-about-sd-card-support) on your external SD card works without root.

**Comment by josephernest** [comment]
@daviewales Yes, I'm using this method currently indeed.
