### ISSUE TITLE
Add an option to bypass the initial hashing-scan and use more lightweight file comparison 

### ISSUE THREAD

**Issue by josephernest** [syncthing/syncthing-android#1246]
**Suggestion: Would it be possible to add the following feature for folder scan?** 

    [X]  Use normal comparison (hashing, requires to read all the data)
    [ ]  Use lightweight comparison (use size, name, datetime metadata only) 

Of course it would be in the "Experimental" setting menu, and I do know that file comparison via size+name+modification datetime is less secure (can be easily fooled) than SHA256 or any other hash.

But it would be useful in many cases. I have read many posts on various forums about people that have a 200 GB repo for which initial scan takes a lot of time.

____

Context: I have:

* a 100 GB MP3 folder on computer D:\MP3
* an identical 100 GB MP3 folder on the phone's micro SD card (using the trick /storage/extSdCard/Android/data/com....)

I have cloned them by temporarily inserting the phone's micro SD card into the computer.

Now I'd like the phone to sync in `Receive only` mode from the computer. 

It would be interesting to avoid the initial scan on phone that requires **to read all the 100 GB and hash them** and just use the "filesize+filename+modification datetime" metadata for the comparison...

**Comment by calmh** [comment]
This would be rather tricky as it is today. In order to have sizes, times, etc to compare to we must already have received that information from someone else. But we need to scan and so on when the folder is added, which is before we know if anyone else has it.

We also don't know 100% when the other side has sent us all their metadata or not - they may be slow and there's more to come, or it might be that they don't have that file we haven't heard about yet. If so we need to scan it fully.

So while I can see the attraction of this, I think it's trickier that it's worth.

**Comment by AudriusButkevicius** [comment]
There are a number of features that rely on hashes, namely block reuse from other files, download resumption, tamper proofing, etc.

I don't think that it's possible for syncthing to function without these things and I think we should simply close this as won't fix.

**Comment by josephernest** [comment]
Thank you for your answers. 

> We also don't know 100% when the other side has sent us all their metadata or not - they may be slow and there's more to come, or it might be that they don't have that file we haven't heard about yet. 

Isn't it the same with hash: "We also don't know 100% when the other side has sent us all their hash or not"?

> If so we need to scan it fully.

Yes, what I suggested is also a full scan, but without the hash, and just the file metadata (modification datetime, etc.).

Now, indeed, by re-reading https://docs.syncthing.net/users/syncing.html#scanning, I see it's more tricky as it seems, because hash is really in the center of the design of SyncThing, and I agree there are good reasons for it.

So I understand that bypassing hash would not make sense.

___

Still, the *"initial scan of big folders problem"* remains. 

Example : during the night I launched ST on my phone with the 100 GB folder. The phone was on AC, without any battery saving mode, with Wifi enabled (to keep ST alive). I thought that this morning the scan would be finished, but it's not, it seems that after a certain point, it has "slept".

Wouldn't there be at least a hack to transfer the "databases of hashes" from PC to phone (only used once, when we do know that the two folders are initially totally identical)?

**Comment by calmh** [comment]
Indeed we never fully know if the other side has completed sending their index data or not, but in the normal case it doesn't matter. Now ,if we had to wait for their metadata in order to be able to evaluate whether to hash a local file or not it *would* matter.

**Comment by AudriusButkevicius** [comment]
We agree that hashing is required, so closing this.

**Comment by josephernest** [comment]
Yes indeed @AudriusButkevicius, I understand that hashing is totally mandatory.

A last thing:

* Let's say the 100 GB folder `D:\MP3\` is successfully scanned+hashed on DeviceA(Computer).

* Let's say this folder is exactly replicated in `/storage/emulated/0/MP3/` of DeviceB(Phone), **before the first run** of Syncthing-Android on this device.

How could I copy certain files of `index-v0.14.0.db/*.ldb` from DeviceA to DeviceB, to avoid the 1-day-long hashing on slow DeviceB?

**Comment by wweich** [comment]
You can't there are no "certain" files for a specific folder. That folder needs to be the only one on Device A.

Also this won't work because of Android. As on Android, we cannot set the mtime, we store the "to be synced" mtime beside the mtime on the Android storage. This data won't be there in device A's index.
