### ISSUE TITLE
Syncthing Android doesn't receive files from Syncthing GTK

### ISSUE THREAD

**Issue by martin-sweeny** [syncthing/syncthing-android#1248]
# What happened

Syncthing doesn't sync at all, and produces multiple notifications for the same folder on both devices.

# What you expected to happen instead

Expected matching folders (with matching IDs) to sync

# Any steps to reproduce the problem.

- Install Syncthing on Linux (I'm running Fedora Workstation 29) and on Android. 
- Add a sync'd folder from the Linux computer, add Android device as shared with, then accept it on Android.
- Try to rescan from either device

### Version Information

    App Version: 0.x.y
    Syncthing Version: v0.14.51
    Android Version: Android 8.1.0

**Comment by AudriusButkevicius** [comment]
This is not concrete enough to be a bug (not clear what needs fixing).
I suggest you start by asking for support on the forum.

**Comment by martin-sweeny** [comment]
Syncthing Android doesn't see any files in my sync'd folders

**Comment by martin-sweeny** [comment]
![image](https://user-images.githubusercontent.com/3329959/49126278-fbe37380-f290-11e8-9aa7-6ee295f131ae.png)

**Comment by martin-sweeny** [comment]
![image](https://user-images.githubusercontent.com/3329959/49126472-b2dfef00-f291-11e8-8dfc-1d200dd1a579.png)

**Comment by Catfriend1** [comment]
Where did the path default folder come from?

**Comment by martin-sweeny** [comment]
On which devices? @catfriend1

**Comment by martin-sweeny** [comment]
It was populated by default. Should I replace `~` with `/storage/emulated/0` maybe?

**Comment by imsodin** [comment]
> I suggest you start by asking for support on the forum.

This is clearly a support question. Please continue in the forum and stop discussing here. Every post here gets mailed to all contributors requiring their attention and time. I promise you will get the help you need on the forum.
