### ISSUE TITLE
Chromebook no longer visable by any other device

### ISSUE THREAD

**Issue by LanceHaverkamp** [syncthing/syncthing-android#1251]
Syncthing for Android **used to work** on my Asus Chromebook c302.  A few months ago it stopped being able to locate, or be seen by, any other device.  I've uninstalled & reinstalled.  The other machines here (Linux, Windows, and Android Motorola phones) all work fine.  But the Android/Chromebook can't see, or be seen at all.  I'm wondering if there's been a chromebook firewall added by Google, that has started blocking the Syncthing app...that's what it feels like, but I see no way to access any type of firewall in this **stock chromebook** setup.

Any suggestions?

**Comment by AudriusButkevicius** [comment]
Support happens on the forums, just like the issue template explains.
