### ISSUE TITLE
Unable to revert "Run on specified Wi-Fi networks"

### ISSUE THREAD

**Issue by mdev88** [syncthing/syncthing-android#1252]
Hello

I have enabled the option "Run on specified Wi-Fi networks", gave the app permissions, everything works fine.
But now I want to go back to the previous configuration, connect on any wifi network, and I don't see a way of doing that...
If I click the settings entry opens a dialog with a list of known WiFi networks, but I don't see an option to select "Any" network, or disable this filter completely.

### Version Information

    App Version: 0.10.15
    Android Version: Android 8.1.0

**Comment by Nutomic** [comment]
I think the setting will be disabled if you deselect any Wifi in the list.

**Comment by mdev88** [comment]
1. That did it
2. I find a little confusing that unselecting all SSIDs means "connect on any SSID". Other than that... closed.

Thanks!
