### ISSUE TITLE
Splash screen cannot slide to another page by gesture.

### ISSUE THREAD

**Issue by ChardLiu** [syncthing/syncthing-android#1254]
Do not report security issues in this bug tracker. Instead, contact security@syncthing.net directly - see https://syncthing.net/security.html for more information.

If your issue is a support request ("How do I get my devices to connect?" or similar), please use the support forum at https://forum.syncthing.net/ where a large number of helpful people hang out. This issue tracker is for reporting bugs or feature requests directly to the developers.

If your issue is a bug report, replace this boilerplate with a description of the problem, being sure to include at least:

    As described by the title.

Also fill out the version information below and add log output or screenshots as appropriate.

If your issue is a feature request, simply replace this template text in its entirety.

### Version Information

    App Version:0.10.15
    Syncthing Version: v0.14
    Android Version: Android 9.0 / Cyanogenmod x / ...

**Comment by Catfriend1** [comment]
Hi
This was intentionally disabled as it's a wizard and not a PowerPoint. If you need more, please consider filing a PR to improve this.
Thanks for your report.
