### ISSUE TITLE
Can't connect to syncthing API  using Android 4.4 due to missing TLS 1.2

### ISSUE THREAD

**Issue by bbaserdem** [syncthing/syncthing-android#1255]
Posting this issue here after being asked for in the [forum](https://forum.syncthing.net/t/cant-get-binary-to-work-on-android-4-4-4/12552/3). I am using a custom rom based on Android 4.4. Syncthing-android becomes unresponsive.  I have the following error on the log;

```
W/SyncthingNativeCode(7710): <DATE> http: TLS handshake error from 127.0.0.1:xxxxx: tls: client offered and unsupported, maximum protocol; version 300
W/SyncthingNativeCode(7710): <DATE> http: TLS handshake error from 127.0.0.1:xxxxx: tls: client offered and unsupported, maximum protocol; version 301
```

Which tells me that the app can't connect to the interface because TLS 1.2 is not supported. From [this blogpost](https://blog.dev-area.net/2015/08/13/android-4-1-enable-tls-1-1-and-tls-1-2/) I understand that the problem is with using API level older than 20, and from 20 and onward TLS 1.2 is enabled. (apparently, bear in mind I personally don't understand anything software/android development)

What happened;

* Syncthing-android is stuck at "Starting syncthing" prompt after launch.

What you expected to happen instead;

* The starting prompt to disappear and show synching content.

Steps to reproduce;

* Install any Android 4.4 without Gapps
* Install Syncthing-android from F-droid (I tried both the original app, previous versions on F-Droid, and the [syncthing-fork](https://github.com/Catfriend1/syncthing-android) versions.
* Launch app, and app is stuck at the starting prompt after secure keys are generated
    what happened,
    what you expected to happen instead, and
    any steps to reproduce the problem.

App Version: 0.10.15
Syncthing Version: ???
Android Version: Android 4.4.4 / [SlimKat 9.1 (grouper)(2018-05-31)](https://forum.xda-developers.com/nexus-7/orig-development/rom-unofficial-slimkat-9-0-grouper-t3214142)

P.S.: The reason for using an outdated android version is because I am trying to re-purpose an old tablet (Asus Nexus 7 2012) as an e-reader for books/papers. There are hardware issues that makes this tablet slightly better than dead weight with more recent android versions. I momentarily switched to 6.1 and the issue disappeared; but tablet very quickly becomes unusable. Although `upgrade to more recent version of android` is a solution; this is not a avery applicable solution for me.

**Comment by capi** [comment]
As noted in the forum discussion, I do think that a possible easier fix than trying to get TLS 1.2 to work on older versions could be to fall back to HTTP as long as the socket is bound to 127.0.0.1.

**Comment by LinuxLover9** [comment]
version 0.10.17 still not working on andriod 4.4.2 / tablet SM-T320.
Version 4.4.2 of Android is the latest available update for my device...

**Comment by jacek-1** [comment]
Hi,
just installed version 0.10.17 on Samsung A5 **(android 7.0**) and cannot run the app

> 02-22 12:15:49.246 W/SyncthingNativeCode( 8706): 2019/02/22 11:15:49 http: TLS handshake error from 127.0.0.1:39548: remote error: tls: illegal parameter
> 
> 02-22 12:15:49.259 W/SyncthingNativeCode( 8706): 2019/02/22 11:15:49 http: TLS handshake error from 127.0.0.1:39550: tls: client offered an unsupported, maximum protocol version of 301

**Comment by AudriusButkevicius** [comment]
Yeah, new version of go dropped support for vulnerable tls implementations, so it seems you need android 8 or onwards. I'll try to make a patch disabling tls over the weekend to get it working again.

**Comment by imsodin** [comment]
Is this something Go related, because I can't find anything in the release notes. Or is it our recentish move to only support tls1.2? However tls1.2 should be supported on android >5.

**Comment by jacek-1** [comment]
> 
> 
> Yeah, new version of go dropped support for vulnerable tls implementations, so it seems you need android 8 or onwards. I'll try to make a patch disabling tls over the weekend to get it working again.

chances that samsung will publish android 8 update for that phone are rather low :-)

preparing a patch in order to have the most up to date version (0.10.17) running on my samsung with android 7 would be great

**Comment by AudriusButkevicius** [comment]
I think we just force tls 1.3 in syncthing, which android does not support.

**Comment by jacek-1** [comment]
> 
> 
> I think we just force tls 1.3 in syncthing, which android does not support.

might be I dont get the point, but is there a chance for me that I could use the 0.10.17 version on my android 7 device ?

**Comment by imsodin** [comment]
Yes, the patch Audrius talks about wont use tls at all, so the version won't matter.

However it's 1.2, not 1.3 that Syncthing requires, see #5276:

>    - We always use TLS 1.2, both for sync connections (as previously) and
>       the GUI/REST/discovery stuff. This is a tightening of the requirements
>       on the GUI. AS far as I can tell from caniusethis.com every browser from
>       2013 and forward supports TLS 1.2, so I think we should be fine.

So it should already work on 7.0 (and does on 7.1 for me). For 4.4 it definitely doesn't work, so the issue is valid still.

**Comment by jacek-1** [comment]
> 
> 
> Yes, the patch Audrius talks about wont use tls at all, so the version won't matter.
> 
> However it's 1.2, not 1.3 that Syncthing requires, see [syncthing/syncthing#5276](https://github.com/syncthing/syncthing/pull/5276):
> 
> > * We always use TLS 1.2, both for sync connections (as previously) and
> >   the GUI/REST/discovery stuff. This is a tightening of the requirements
> >   on the GUI. AS far as I can tell from caniusethis.com every browser from
> >   2013 and forward supports TLS 1.2, so I think we should be fine.
> 
> So it should already work on 7.0 (and does on 7.1 for me). For 4.4 it definitely doesn't work, so the issue is valid still.

ok, what would you recommend to do to tackle with this issue on my phone ? I have pasted logs from syncthing in a post above, would you be so kind and help me out with root cause analysis ?

**Comment by AudriusButkevicius** [comment]
The root cause is explained above. Android version does not support the protocol in question.

**Comment by jacek-1** [comment]
ok but as stated above as well
"So it should already work on 7.0 (and does on 7.1 for me)"
and I have android 7.0 (not 4.4) standard one and it doesnt work

**Comment by AudriusButkevicius** [comment]
It can be disabled by some vendors, and I think it might be 7.1 not 7.0.

**Comment by AudriusButkevicius** [comment]
The beta that is about to go out should have a fix.

**Comment by LinuxLover9** [comment]
Thank you!
Will this be downloadable through the play store?

**Comment by AudriusButkevicius** [comment]
Yes, tho you have to be on the beta track to download it. You can check on google how to check the beta track.

**Comment by Catfriend1** [comment]
Who reviewed this? As my work has been often accused not having reviews I think this a security relevant change in the official app.  One might tell it's minor connecting to localhost unencrypted and one might say it's major. Just to give a pointer: Syncthing Fork has a proper fix so it works with https and on all versions. Let's say the chance that someone intercepts localhost traffic via proxy or vpn is rare...

**Comment by Nutomic** [comment]
Agreed, you disabled TLS completely, and apparently not a single person reviewed that change. I thought you were the one who wanted thorough code reviews to find security flaws. @AudriusButkevicius

**Comment by Catfriend1** [comment]
Ref:
- https://github.com/Catfriend1/syncthing-android/issues/266
- https://github.com/Catfriend1/syncthing-android/pull/359 (Draft PR to fix this more accurate)
- https://forum.syncthing.net/t/android-and-tls1-2/12931/31 (Discussion on Forum)
