### ISSUE TITLE
Keeps dropping the VPN

### ISSUE THREAD

**Issue by robsonsobral** [syncthing/syncthing-android#1259]
Hi! It keeps dropping the VPN. I've noticed because CloudFlare DNS keeps being disconnected, then I tested with ProtonVPN and the same thing happens.

### Version Information

    App Version: 0.10.15
    Syncthing Version: v0.14.51
    Android Version: Android 9 on Moto X4

**Comment by Catfriend1** [comment]
Hi, does this apply to syncthing, the run conditions or the vpn app? Mayb you'll have an "adb logcat -v" or Matlog App verbose Log at hand to help us investigate this?

**Comment by robsonsobral** [comment]
I tried to change run conditions without luck,

How can I provide the logs you need?

**Comment by AudriusButkevicius** [comment]
Support happens on the forum.
