### ISSUE TITLE
Run conditions: Tell user which applies/inhibits the startup [FEATURE REQUEST]

### ISSUE THREAD

**Issue by NicoWeio** [syncthing/syncthing-android#1263]
When the `"Syncthing is disabled - Would you like to change the run conditions?" [translated]`  popup appears, it would be really nice to see *which* condition(s) inhibit(s) the start.

**Comment by capi** [comment]
I have hacked a simple prototype for this that I'm not yet really happy with and that does not yet cover all cases, but I hope I can open a PR for this in a few days for review.

**Comment by capi** [comment]
See #1264 for the PR.

**Comment by capi** [comment]
Fixed by merge of #1264.

**Comment by aslmx** [comment]
Is there an ETA for this fix? 

I constantly get this popup and can not find a way to work around it. 

I've allowed to start with WIFI, to start with a metered connection (altough it wouldn't reach the peers then), use mobile data is allowed. I tried to change the battery/charging/battery+charging setting. I tried with regard energysaving and not and the also the sync settisngs...

How can i start synchting?

**Comment by capi** [comment]
It is merged, so it should be available with the next release. I don't know, however, when a new update will be published to the Play Store.
/cc @AudriusButkevicius

**Comment by aslmx** [comment]
THanks for your quick reply.
actually I'd be more interested in a f-droid update ;)

**Comment by capi** [comment]
@aslmx: If you have WiFi network restrictions, it could be that you have disabled location services. Recent versions of Android don't give the WiFi SSID anymore, if the location service is disabled, since looking up WiFi SSIDs in database will give a you coarse location nowadays.
