### ISSUE TITLE
dns-sd support

### ISSUE THREAD

**Issue by legrostdg** [syncthing/syncthing-android#1266]
At least on linux, it's simple to configure avahi to support dns-sd for syncthing. It is not as easy on android, where it would help a lot to have native support... According to https://developer.android.com/training/connect-devices-wirelessly/nsd it does not seem to be something hard to add to the app.

**Comment by Catfriend1** [comment]
According to calmh a wontfix?! 
What benefit would that have for a standard Android app user?

**Comment by legrostdg** [comment]
The user could still configure avahi himself on the desktop app, that's not the case on android...

**Comment by legrostdg** [comment]
(and that is a wontfix-by-myself, not a wontfix-at-all)

**Comment by Catfriend1** [comment]
Why not ask google to implement the avahi package in Android Linux?

**Comment by Catfriend1** [comment]
Hey I don't disagree but wanted to learn more about that as that's surprising new for me.

**Comment by legrostdg** [comment]
Thanks for the correction concerning the binary. The point of this is that it brings a simple/standard solution for pairing local devices on different subnets, without having to rely on a remote relay. Even without native support, it's still easy to configure dns-sd for syncthing on linux, with a simple config file, and I guess the same apply on other platformsg. This is not the case on android, though.

**Comment by legrostdg** [comment]
@AudriusButkevicius you mention other alternative discovery protocols, but I'm not sure of what we have now. Is there a way to do local pairing on different subnets, with a computer and an android smartphone? With a very simple configuration file, we already have dns-sd do this for all pair of (linux) computers. Adding android support would permit to have a solution for this problem.

**Comment by Catfriend1** [comment]
@legrostdg Just use the global Discovery option and it will connect fine after discover as long your gateway allows tcp traffic between subnets.

**Comment by AudriusButkevicius** [comment]
There is no such thing as android support in this case, as "android" is just a GUI that runs linux version of syncthing and pokes at it via the rest API.

I don't really see why avahi is better than bonjour etc.

You can already pair computers across subnets by configuring device addresses manually, hence I am closing this.

@Catfriend1 it won't as we don't advertise local IP addresses not to expose internal network topology.

**Comment by legrostdg** [comment]
@AudriusButkevicius avahi implements bonjour/zeroconf, this or another similar solution I don't mind. That seems to be the standard, and a simple, even native solution exist for android.
You mean hardcoding the ip addresses for each device? What if the devices don't have static ip, or can connect on different subnets? That seem less than ideal.
