### ISSUE TITLE
crash in native code: panic: leveldb/table: corruption on data-block

### ISSUE THREAD

**Issue by stuart12** [syncthing/syncthing-android#1267]
Syncthing starts, connects to machine I'm trying to sync from and then crashes. At some point it was able to copy 923 MB but now it appears to crash immediately.  There is perhaps a problem with my SD card but the UI should report an error.  At the moment the UI does not show that there is any problem at all. I can see that syncthing has crashed by clicking on "Show device ID" which says "Could not access device ID."  Or by showing the "Web GUI" which says "Web page not available".

The log from [adb logcat | grep -i syncthing](https://github.com/syncthing/syncthing-android/files/2775838/syncthing.txt).

I have an SD card that might have errors. The folder I'm trying to sync is receive only.

### Version Information

    App Version: 0.10.15 (from F-Droid)
    Syncthing Version: v0.14.51-dirty
    Android Version:  lineage-15.1-20190113-UNOFFICIAL-z3tcw

**Comment by AudriusButkevicius** [comment]
You have the option in settings to reset the database if it's corrupt.
