### ISSUE TITLE
Barcode Scanner

### ISSUE THREAD

**Issue by physk** [syncthing/syncthing-android#1273]
Just an FYI the barcode scanner app you use has been removed from the playstore

[Link to zxing's Github Issue](https://github.com/zxing/zxing/issues/1133)

**Comment by capi** [comment]
Thanks for the information.

**Comment by klausenbusk** [comment]
FWIW: The mentioned "plus" version works flawless with Syncthing.

https://play.google.com/store/apps/details?id=com.srowen.bs.android&hl=en_US

**Comment by capi** [comment]
It seems to be back on Play Store: https://github.com/zxing/zxing/issues/1133#issuecomment-467217095
I'm closing this, since the issue at hand has resolved itself and the proposal for integrating a QR-code scanner directly in Syncthing-Android is being discussed in #709.
