### ISSUE TITLE
Cannot ignore/block connection requests from removed device

### ISSUE THREAD

**Issue by colans** [syncthing/syncthing-android#1275]
### What happened

I removed a device from the network by:
1. Unsetting *Introducer* for all devices connected to the one I wanted to remove.
1. Deleted the device.

Then, I periodically get notifications:

`Device X wants to connect`

I tried the following, but neither worked:

1. Deleting the notification from the list by swiping it away.
1. Clicking on it, and then backing out of the device-add form, which is what comes up.

As confirmed in #938, there doesn't appear to be a way to tell the app: "I'd like to silently ignore future requests from this device; please stop asking me."  even though there's an option to reset that list as per #1185.

### What you expected to happen instead

After clicking on the notification, there should be a Block (or similarly named) button that silently rejects device connection requests from the offending device if they continue to occur, by adding the device to the ignore list.

### Version Information

    Syncthing Version: v0.14.51-dirty
    Syncthing-Android Version: 0.10.15
    Android Version: Android 6.0.1

**Comment by Catfriend1** [comment]
Check this out to see how the ignore button looks like: https://github.com/syncthing/syncthing-android/pull/1177

**Comment by colans** [comment]
Makes sense.  It's strange that I wasn't seeing it.  Anyway, thanks for your help, again.
