### ISSUE TITLE
Keep syncthing synchronized without wakelock. 

### ISSUE THREAD

**Issue by crocket** [syncthing/syncthing-android#1276]
Currently, wakelock is used as an experimental option to keep syncthing always connected.
However, wakelock drains battery quickly.

I read that a native android binary would make wakelock unnecessary.

Does syncthing occasionally wake up during maintenance windows of Doze mode? Or, does it simply sleep indefinitely without wakelock?

When does syncthing synchronize without wakelock?

**Comment by AudriusButkevicius** [comment]
Syncthing is just a linux binary compiled for arm slapped with an ui on top, so the fact that it works on android is pure luck that you can cross-compile go. There is no such thing as doze mode etc in go.

**Comment by crocket** [comment]
When does syncthing synchronize if android is sleeping?

**Comment by imsodin** [comment]
Please use forum.syncthing.net for support.
