### ISSUE TITLE
Inaccurate sync percentage + Strange conflicts created with music files

### ISSUE THREAD

**Issue by warmsweater** [syncthing/syncthing-android#1277]
I'm fairly new to creating bug reports, so let me know if I need to do anything differently.

I set my Music folder as "Send & Receive" on my laptop and desktop, and receive only on the microSD card on my Android phone like:
`/storage/014A-7323/Android/data/com.nutomic.syncthingandroid/files/Music`
When I change a file, for example of I were to take "meow.mp3" and change the artist from "My Cat" to "Your Cat" via tag, the new file is uploaded but the old was is named ".sync-conflict-XYZ"

It doesn't seem to happen all the time, but becomes especially apparent when all the files from a folder are removed, here's a snippet from an old log file:
`INFO: Puller (folder "Music" (*****-*****), file "Kevin Rose/The Kevin Rose Show"): delete dir: directory is not empty`

I tried adding this to the ignore file with no change:
  `(?d)*sync-conflict*`

I have tried rebuilding my database, resetting the delta indexes, and removing all Syncthing related files and doing a complete rescan, but nothing seems to change it.

My youtube-dl files in a directory next to it on my SD card seem to sync fine, but I do remember having a similar issue with it that I cannot reproduce.

Also, my desktop seems to report a seemingly random sync percentage for the device, despite the files being synced over:
![screenshot_2019-02-19_12-15-59](https://user-images.githubusercontent.com/45935087/53056111-15532080-3478-11e9-94ba-865375b8b811.png)\

My Android just going between "Scanning" and "Out of Sync"
![mobile](https://user-images.githubusercontent.com/45935087/53056580-ca3a0d00-3479-11e9-8f1d-43b61dfa66f8.png)

Not sure if that has anything to do with it.

Please let me know if there's anything I can do to assist with this bug, Syncthing has simplified my life a lot and I'd love to help if I can.

### Version Information

    App Version: 1.0.1 (currently using Syncthing-Fork by catfriend, but this issue stands with the original Android version on F-Droid.
    Syncthing Version: v8.0.0
    Android Version: Android 8.0.0 (tested on Samsung Galax S5 and LG G6

**Comment by AudriusButkevicius** [comment]
Support is handled on the forums.
