### ISSUE TITLE
"Syncthing is disabled: Not connected to wifi" - I AM!

### ISSUE THREAD

**Issue by snow-frog** [syncthing/syncthing-android#1280]
I am connected on Wifi and no settings have been changed, but syncthing refuses to exit this condition. It was working fine until tonight. Fully stock phone, Android 8.0.0, Syncthing 0.10.17

**Comment by capi** [comment]
I'm sorry to hear this. I've reworked the decission logic somehow to get the indication to the UI why we are not connected. Can you provide an `adb` log so that we can debug why it is considering your status as "not connected"?

**Comment by mlda065** [comment]
I just had the same issue.

I'm using a VPN client. ([Private Internet Access](https://play.google.com/store/apps/details?id=com.privateinternetaccess.android))
When I disable the VPN, Syncthing starts.

I have already whitelisted Syncthing in my VPN app, so supposedly Syncthing shouldn't notice the VPN. But clearly there's still something different to no-VPN. Not sure what.

I haven't had time to check my adb logs. I'll do that later.

**Comment by capi** [comment]
When connected to a WiFi, Android reports the WiFi as not connected. I know that there is a way to detect that the VPN is connected via a certain WiFi, because Tasker can do it ("Active" setting "Yes", "No", "Any", you need the "any" setting). But I need to have a look how they do it.

**Comment by Catfriend1** [comment]
This is interesting, I guess it depends which vpn app you're using. I'm running NetGuard VPN here and this doesn't cause problems in STA's WiFi detection.

**Comment by mlda065** [comment]
I think this bug is fixed. About a week after posting this an update fixed the problem. I'm assuming that was a deliberate patch.

**Comment by shawn1thompson** [comment]
I am having this issue with ProtonVPN. I have enabled split tunnelling in the Proton app to no avail.
