### ISSUE TITLE
RC build released to the stable channel (again...)

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing-android#1286]
So, [history tends to repeat itself](https://github.com/syncthing/syncthing-android/issues/961)...
Syncthing-android v.0.10.18 was just released to the Play Store, which is cool as always :)
But - the bundled syncthing is v1.1.0-rc.1

RCs contain stuff like mandatory statistics that will override users' preferences once upgraded. And of course it is not the "stable" one...
This should not be used in a stable channel for a global release.

Version Information:

App Version: 0.10.18
Syncthing Version: v1.1.0-rc.1

**Comment by Catfriend1** [comment]
Thanks for the info, I think the release script didn't pick up the stable for some reason we need to check. I'm currently on chat with @imsodin to get into the process how releasing the official correctly works.
I'll file a commit for the correct stable reference to st v1.1.0 when on a computer next time.

**Comment by imsodin** [comment]
Sorry, my bad - seems I am missing not a single pitfall here. Any objections to releasing like this as 0.10.19?

**Comment by Catfriend1** [comment]
0.10.19 is okay.

**Comment by scienmind** [comment]
Closing as v0.10.19 is out with ST v1.1.0.

But, checks should be added to the android build/release system to fail the release if a non-stable (RC) version is mistakenly pushed to stable channel.
