### ISSUE TITLE
Option for rescanning

### ISSUE THREAD

**Issue by peey** [syncthing/syncthing-android#1293]
Essentially a duplicate of https://github.com/syncthing/syncthing-android/issues/98

I don't agree with the closing reason: 

> I added inotify for 0.5.0, so there's no point in having a manual rescan any more.

Since the app lets you disable watching for changes, there should be an option to manually trigger rescanning if required.

If you're interested in the use-case, then:

I plan to use syncthing once or twice a day (on very few days in a month) for syncing changes in specific folders. There's no reason for me to have the app always running. 

The changes to files will happen when app isn't running. I plan to use syncthing to just sync manually when I want to.

**Comment by wweich** [comment]
So why not disable autorun and start the app when you want to sync and check the sync status. When it's finished Quit the app.
That*s possible with the current app.

**Comment by peey** [comment]
Thanks! Exiting the app and restarting works. I suppose it forces the app to sync when it starts. I'm not sure though what you meant by "check the sync status".

I'll leave it up to you to close this issue or leave it open then. This works for my case but feels like a hack. 

I have another feature request: being able to kill the app when you exit it and all syncing which was commenced has finished. Should I put that in a new issue? Same use case, I don't plan to keep syncthing running beyond when I manually initiate syncs, and it'd be nifty if app exits after the syncs than me having to manually kill it.

**Comment by AudriusButkevicius** [comment]
Closing as you found a solution, having to open an app for it to do it's thing does not feel like a hack to me.

Regarding exiting once finished, that won't happen as finished can mean many things.

**Comment by peey** [comment]
@AudriusButkevicius yep, finished can mean many things, but in the context of the workflow where you're syncing things manually, it means when the last manually triggered sync was finished.

It feels like a hack because the web gui does provide a folder-specific sync option. There you can re-trigger the sync without having to force exit and start the app if you wish to.
