### ISSUE TITLE
Syncthing always shows number 1 in icon badge

### ISSUE THREAD

**Issue by MarceloRuiz** [syncthing/syncthing-android#1297]

**Comment by MarceloRuiz** [comment]
The application always shows a number 1 on the badge but there is no way to know what the notification is about.
![20190402_210740](https://user-images.githubusercontent.com/1209270/55445938-a1825880-558b-11e9-892e-9c8965b26756.jpg)

App Version: 0.10.19
Android Version: 8.0.0

**Comment by AudriusButkevicius** [comment]
This is not syncthing but the wrapper you are using.

**Comment by Catfriend1** [comment]
... it's caused by Android 8.0 which shows badges for services in some versions (lineage).

**Comment by AudriusButkevicius** [comment]
Sorry, I thought this was the main repo. Anyways, it seems this is expected.
