### ISSUE TITLE
Android syncing issues big files

### ISSUE THREAD

**Issue by axet** [syncthing/syncthing-android#1302]
Hello!

Seems like synching-android not properly scan android files. When big files copied to synching folder from another android folder syncthing start syncing too earlier. So, if 200mb file appear in sync folder it start syncing at 64mb.

I did a little research around but unfortunately (yet?) here is no solution but wait and rescan for new files after 10 seconds to see if files are completely transfered (no size change or last access time changed). I tried to check if files are opened by OS (using lsof, proc, etc) but no such hack worked only rescanning the folder.

### Version Information

    App Version: 0.10.15
    Syncthing Version: 0.14.51
    Android Version: 7.1.2 lineagos

**Comment by Catfriend1** [comment]
Hi axet!
Thanks for reporting the issue. From reading it, I guess it may be an upstream problem with the file watcher enabled and SyncthingNative starting to sync 10 seconds after the change was detected. There is already a thread on the Syncthing Forum. I'd suggest you add this to the thread as @imsodin already has created a PR to fix this - not sure if this also works for Android. But the wrapper cannot influence file sync start and detections.

**Comment by imsodin** [comment]
That PR has nothing to do with this. It does fix something that can come up if there is a program that writes changes to files in two steps, which seems to be the case here too. It might even be android itself, I think I can remember similar reports. In any case there is nothing Syncthing can do here: If a program decides to first create the file without any data in it, and then quite a bit later (more than 10s) writes the actual data without modifying the file metadata, then Syncthing simply can't know about this.

**Comment by axet** [comment]
I would be so sure about closing this issue. It does mean copying files to folder under synching control on android platforms is not possible and it is ok?

BTW I treid to to locking files to be sure files is not opened (in my app):

```java
            FileOutputStream fis = new FileOutputStream(f, true);
            FileLock lock = fis.getChannel().tryLock();
```

But those locks allows allowed no matter if files used by another app. Using /proc checks requires root which is bad. So, rescanning required.

**Comment by Catfriend1** [comment]
Does it help if you try to increase the fileWatcherIntervalS to, let's say, 40s?

**Comment by axet** [comment]
I guess it would for most times, but this check should be done for files individually since every 40s it breaks the files. Copy operation can takes longer than 40s, in between check requests current file will be damaged. Yes, i forget to mention it, files get truncated on booth devices (including source one) if sync started too earlier.

**Comment by imsodin** [comment]
@axet I am not disputing that there is a problem in your use case, I am saying there is no clear, actionable bug in syncthing-android and it's not even yet clear, what exactly is happening. We like to do the debugging on forum.syncthing.net, to keep the volume on the issue tracker low. Please open a thread there and we can investigate what exactly is going on and open an issue here or on syncthing if anything actionable arises.
