### ISSUE TITLE
the dot is always shown

### ISSUE THREAD

**Issue by 532910** [syncthing/syncthing-android#1305]
![image](https://user-images.githubusercontent.com/14617699/56287340-c0085800-6124-11e9-9e55-e173fd09488b.png)

Please don't tell this is due a permanent notification. as there are many other apps, like linphone or battery charge lime, that also have a permanent notification but without a dot on the icon.

**Comment by Catfriend1** [comment]
This is due to running a service.
Please don't tell we should remove it.

**Comment by 532910** [comment]
You don't should remove it!

**Comment by 532910** [comment]
Have you fixed it?

**Comment by AudriusButkevicius** [comment]
No, it's there for a reason and it's staying.

**Comment by 532910** [comment]
What the reason is?

**Comment by 532910** [comment]
There are not "news" for me to show a dot, so there are no reason.

**Comment by AudriusButkevicius** [comment]
It is enforced by the OS (we don't ask to have it) if the app runs as a service. We do not do anything special or ask it to be shown, it's not our decision.

**Comment by 532910** [comment]
I'll repeat once again as you have totally ignored my words:
[Linphone](https://github.com/BelledonneCommunications/linphone-android) HAS permanent notification. But it shows the dot only when I have incoming message or missed call.

[BatteryChargeLimit](https://github.com/sriharshaarangi/BatteryChargeLimit) HAS permanent notification. But it never shows the dot at all.

The all three notification on this screenshot are permanent, and only Syncthing shows the damn dot:
![image](https://user-images.githubusercontent.com/14617699/56326354-5e74d780-617e-11e9-8bf7-5bdb92b629da.png)

**Comment by AudriusButkevicius** [comment]
Sure, but you also miss what I wrote, we don't do anything special to show the dot. Perhaps those apps do something special not to show it, but I don't know what it is, and frankly I don't really care.

If you know what code changes to make to not show the dot, file a pull request with a code change, until then the dot stays.

**Comment by 532910** [comment]
Sure! I suppose those apps spawn a separate process. Or may be I'm wrong: https://developer.android.com/training/notify-user/badges.html I not an android developer.
Frankly you don't really like me and other users.
It's wrong behaviour: there are no reason to bother people with the badge. It cares other people, and I'm not the only one: https://github.com/syncthing/syncthing-android/issues/1297

**Comment by AudriusButkevicius** [comment]
I can keep the ticket open if that makes you feel better, but until someone proposes a PR with the fix it will stay this way, as this is purely cosmetical and does not cause critical functional isues.

**Comment by 532910** [comment]
I don't ask you to fix it immediatily. But closing such bugs you just say you're against to solve it at all. It should be open untill fixed by you or someone else. Don't take it personal.

**Comment by AudriusButkevicius** [comment]
I am fine to keep it open, but I don't see it being fixed until someone who cares about it puts in the leg work.
