### ISSUE TITLE
Glitch in web UI

### ISSUE THREAD

**Issue by bege10** [syncthing/syncthing-android#1306]
### Version Information

    App Version: Syncthing-Fork 1.1.1.1
    Android Version: LineageOS for microG 15.1 (Android 8.1)
    Device: Samsung Galaxy S5 Plus (SM-G901F)

I have posted this in the Syncthing-Fork bugtracker and have been told that the web UI is an issue of Syncthing itself.

![Screenshot_20190407-132149_Syncthing-Fork](https://user-images.githubusercontent.com/1184237/56374935-8c9cfa80-6204-11e9-9f51-8c20aefbe237.png)

This is a screenshot of not synchronized files in the web UI (German locale).
Please, write the blue information in second line.
Thank you very much.

**Comment by AudriusButkevicius** [comment]
Still the wrong repo.

**Comment by calmh** [comment]
It's a valid issue on -core though, unless it was fixed by just merged syncthing/syncthing#5565
