### ISSUE TITLE
Manually stopping syncthing process

### ISSUE THREAD

**Issue by mjwhite** [syncthing/syncthing-android#131]
Is there currently any way to ensure the background syncthing process is stopped, other than shutting it down from the web UI?

Personally I would prefer it to be running only as long as the app is (ie start when app starts, stop when app stops). Looking at #6 and 9bb5401d78e8b2afe2f787a09cdf383868c23841, I suspect this may be complicated by the newer features responding to power/wifi changes.

I am running syncthing on Sailfish under Alien Dalvik, by the way - the syncthing process doesn't stop when the app exits - but it's possible this isn't what happens under native Android. (In all other ways it seems to work absolutely fine.)

**Comment by gerroon** [comment]
Hi

The android app uses alot of cpu for no apperant reason. Sometimes I find my batter drained %30 in less than a minute and I can see that the syncthing.so runs and uses alot of cpu for no apperant reason (even when there should not be any updates from other clients or from a non existing file update). 

It would be nice to have the synthing app running but being able to control a stop and start process of the Syncthing binary.
