### ISSUE TITLE
Global State mis-reported. Synchronization seem to be working fine.

### ISSUE THREAD

**Issue by Hob111** [syncthing/syncthing-android#1312]
I'm running Syncthing on a Tablet (Android 6) and a Windows 10 PC. It worked fine for a while and then the Android device started to mis-report the Global State although everything still seems to be working.

![Screenshot_20190426-120930](https://user-images.githubusercontent.com/38910411/56852274-058d0800-6911-11e9-841c-00c37c0ac426.png)

The Local State reported by the tablet matches the Local and the Global State of the PC when everything is up to date. The differences on the tablet are constant, always 302 files, 5 directories and 0.4 GiB. 

I wasn't sure whether to post this here or on the main Syncthing thread, my apologies if I've chosen the wrong one - let me know and I'll close this and report it there.

### Version Information

    App Version: 1.1.1
    Syncthing Version: v1.1.1-dirty, android (ARM), Windows v1.1.1 (64 bit)
    Android Version: Android 6.0.1

**Comment by AudriusButkevicius** [comment]
This should go on the forum for starters.
