### ISSUE TITLE
Language in F-Droid

### ISSUE THREAD

**Issue by gloeyisk** [syncthing/syncthing-android#1325]
Hello.
I'm glad that if the team (especially Indonesian) did the translation as well for this language, I just want giving an idea to change the language in F-Droid to use English instead of Indonesian. So everyone wherever they live that can be easily to translate to their native language. Here's I attached screenshot.
Thank you.

![IMG_20190514_231306](https://user-images.githubusercontent.com/43908341/57714643-7730ba00-7664-11e9-9523-0a29be15dce5.jpg)

**Comment by Catfriend1** [comment]
Translations are done on Transifex. Feel free to help us there.
