### ISSUE TITLE
Locales considered invalid by release build

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing-android#1347]
A locale that worked just fine previously (zh_TW) and that is supported according googling, is now considered invalid at publishRelease stage - no idea why. Currently the only way forward I see is backwards by reverting the publisher and gradle stuff. I'll wait a moment on that.

**Comment by AudriusButkevicius** [comment]
We have a special task which delete invalid locales.

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing-android/blob/master/app/build.gradle#L87

Perhaps it's valid but was changed. It's google who decides that, not gradle and not us I think.

**Comment by imsodin** [comment]
Top thanks, together with the official list of supported languages by google play (https://support.google.com/googleplay/android-developer/answer/3125566) I was finally able to get the stuff built (it still felt due to a 500 error, but somehow the release candidate is still listed in the play console). I assume the publisher just ignored invalid languages before.
