### ISSUE TITLE
Target api level 28 until November

### ISSUE THREAD

**Issue by imsodin** [syncthing/syncthing-android#1355]
Due to google play requirements. That's not yet the level with the (potential) scoped storage stuff, so hopefully is simple to transition to.

**Comment by Catfriend1** [comment]
Hi @imsodin!

I can share my experience at this point and say its totally okay to target api 28 until Android Q beta 4 (which is currently the most recent version). STF already is on that api level for a longer time. Probably api 29 will be more difficult to reach and keep backward compatible.
