### ISSUE TITLE
Unable to sync when WLAN with no Internet and data transfer enabled

### ISSUE THREAD

**Issue by dxtr85** [syncthing/syncthing-android#1363]
App Version: 1.2.0
    Syncthing Version: v1.2.0
    Android Version: Android 7.0 NRD90M
When I am connected to WiFi network with no Internet access
and also I have Data Transfer enabled on my phone,
then I am not able to sync with a PC that is also in that WiFi network.

When I disable Data Transfer, then I am able to sync between Android device and a PC on the same WLAN with no Internet.

I wish I was able to sync regardless of Data Transfer state.

**Comment by AudriusButkevicius** [comment]
This is am android problem I think, not a syncthing problem. Android apps only see a single connection, whichever android decides is the healthy one.

**Comment by acolomb** [comment]
In my experience, it helps if the non-Internet-connected WLAN is the only connection. So you should just try to disable "Mobile Internet" in that situation.
