### ISSUE TITLE
Support for QR scanner with zxing library

### ISSUE THREAD

**Issue by TsukihiAraragi** [syncthing/syncthing-android#1385]
It seems syncthing Android hard code zxing team's official barcode scanner. 

![Screenshot_20190827-150931_Syncthing](https://user-images.githubusercontent.com/38233179/63749723-9c2cfe00-c8de-11e9-9ecb-0f555fa2c586.png)

But, there's some QR scanner (like this one: Binary Eye - https://f-droid.org/app/de.markusfisch.android.binaryeye) have integrated zxing library and can handle zxing intent. 

They have beautiful UI/UX and some enhanced functions, so I don't want install another repeat application.

**Comment by AudriusButkevicius** [comment]
Sure, PR's welcome to convert it to an intent, as I don't think anyone cares strongly. 

It's easier for us to use a library which deals with the glue.

**Comment by TsukihiAraragi** [comment]
I found [this comment.](https://github.com/markusfisch/BinaryEye/issues/2#issuecomment-525297243)

**Comment by AudriusButkevicius** [comment]
Closing this as dupe.

**Comment by TsukihiAraragi** [comment]
@AudriusButkevicius dupe? This is true and I don't know your means. I'm not a programmer, I can not make a PR to support it. 

If you don't want support it just said won't fix and close it.

**Comment by AudriusButkevicius** [comment]
The other ticket talks about handling the intents ourselves, which means we could accept using a different scanner, which is essentially what this ticket is about, hence dupe.

I don't mind it being supported, but someone has to put in the time to make it happen. I don't care about this at all, so I am not going to spend my time on this.

**Comment by ialokim** [comment]
See https://github.com/markusfisch/BinaryEye/issues/2#issuecomment-525297243 for what should be done. It should be as simple as bumping the version number as soon as a future PR for the zxing library is accepted.
