### ISSUE TITLE
Syncthing for Android destroys original file modification times

### ISSUE THREAD

**Issue by 101101100** [syncthing/syncthing-android#1389]
Syncthing for android V1.2.0 gives the downloaded files the modification time of the download on my devices!

I expected, (accordingly to FAQ 2.2.4) that file modification times are synced frome the source files.
After having been copied from an old to a new phone, all photos etc. now show up in the gallery as being of today - and in a totally weird order (random sync sequence was configured).
The new smartphone runs Android Pie, another device in the group runs Android Oreo.

I think the issue is most easy to reproduce: just sync two photos with the config setting "newest first".

The problem becomes more serious because
- the wrong modification times are then distributed (being the most recent date) to the other devices, thus annihilating the original information everywhere
- it is very tedious to correct some thousands of photos manually
- android phones do not provide SMB access to the files (except for Mac owners or when rooted) for automated correction using EXIF information (for photos) or filename information (for videos / other documents)
- standard USB and WebDAV access do not provide means to change the file modification timestamps.

### Version Information

    App Version: 1.2.0
    Syncthing Version: v1.2.0
    Android Version: Android 9 (Huawei EMUI 9.1.0), same on Android 8.0.0

**Comment by imsodin** [comment]
Modification time on android is broken. There's a mechanism in Syncthing that should keep track of the correct modification though, such that your first bullet point shouldn't apply. If you can reproduce that, please reopen. We can't do anything about the rest though (I suggest getting a photo gallery which sorts by exif capture time, not modification time - sorting by mod time by default (or even as only option) is simply insane).

**Comment by 101101100** [comment]
I agree for pure pictures that EXIF information can be used. Unfortunately, that is not true for videos, arbitrary documents, images that were not taken with the camera etc.

Could you please be so kind to explain, what is broken regarding modification time on android, so Syncthing is really unable to set it right? I made the following test with my device:

1. set up USB-debugging, entered `ADB shell` and navigated to a user folder containing a file
2. :
`$ ls -l`

`-rw-rw---- 1 root sdcard_rw    40280 2019-08-08 22:51 190418\ Schwarzes\ Loch.jpg`

`$ touch -d 2019-04-18T22:51:00 190418\ Schwarzes\ Loch.jpg`

`-rw-rw---- 1 root sdcard_rw    40280 2019-04-18 22:51 190418\ Schwarzes\ Loch.jpg`

This looks flawless?

**Comment by AudriusButkevicius** [comment]
This is a root shell, root can change mtimes, normal apps cannot.

**Comment by calmh** [comment]
Also it's the wrong experiment.

```
$ ls -l
-rw-rw---- root     sdcard_rw        0 2019-09-03 19:29 test1
$ touch -d 2018-01-02T12:34:56 test1
$ ls -l
-rw-rw---- root     sdcard_rw        0 2019-09-03 19:29 test1
```

Note silent failure to set the time to anything other than *now*.

**Comment by AudriusButkevicius** [comment]
https://issuetracker.google.com/issues/36930892

**Comment by AudriusButkevicius** [comment]
Also, try restarting your phone, it's likely the date will change.

**Comment by calmh** [comment]
Also the behavior is not universal. On my (older) Android phone it's a silent failure.

```
$ ls -l
-rw-rw---- root     sdcard_rw        0 2019-09-03 19:29 test1
$ touch -d 2018-01-02T12:34:56 test1
$ ls -l
-rw-rw---- root     sdcard_rw        0 2019-09-03 19:29 test1
```

**Comment by 101101100** [comment]
This is a first screenshot after reboot.
Everything is fine.
![Unnamed2](https://user-images.githubusercontent.com/54818961/64196240-b8531100-ce83-11e9-9bb9-09fefc596563.PNG)
I then installed Terminal Emulator from the play store and typed directly without ADB
`touch -d 2011-02-03T04:05:06 csm.gif`
resulting in
![Unnamed3](https://user-images.githubusercontent.com/54818961/64196567-6c549c00-ce84-11e9-877a-02327447fc04.PNG)
after another reboot.
Thank you for your contributions ... but I think everything just works as intended. As I wrote, it's android 9, maybe it was really fixed

**Comment by AudriusButkevicius** [comment]
Well we don't do anything special to make it not work

**Comment by 101101100** [comment]
I confirm that on my android 8 device I get a
`touch: 'csm.gif': Operation not permitted` error.
I can only report it works fine unter android 9.

**Comment by 101101100** [comment]
> 
> 
> Modification time on android is broken. There's a mechanism in Syncthing that should keep track of the correct modification though, such that your first bullet point shouldn't apply. If you can reproduce that, please reopen. 

I confirm that there is strong evidence that the first bullet point applied in my sync set.
First occurrence seems to have been on 8/8/2019, when I started syncing with the new, abovementioned Android 8 device. Now as of 9/10/2019, lots of files have this modify date on the main Windows 10 PC, though they have older file dates in the PC backup. This only applies to folders which are synced with this Android device, not to folders which are only synced between Windows devices.
There are other suspiciously large groups of files with similar modification time much later than the file name indicates, modify date > create date though never edited, and now newer than in the backup, especially 8/26/2019, when I think I added this device to more folder sync device groups.

However, the Android 9 device seems to be another victim, not another suspect. It was first used with Syncthing-Android on 8/23/2019, but there are no suspicious files with that date.

**Comment by AudriusButkevicius** [comment]
Not sure of you analysis is trying to state something, or wether its just an FYI.

**Comment by gdt** [comment]
Did you by any chance do a fresh install of syncthing but with the files you want to sync already present in external storage?  This happened to me when reinstalling the OS on a phone while not wiping external storage.   I surmise that the mod time metadata (and perhaps other data) was stored in the app/internal and thus these showed up as files with modified mod times.

Or, was your first sync with the device with an empty target folder?

**Comment by 101101100** [comment]
@gdt: it was the first sync to a new android device with an empty target folder. 
@AudriusButkevicius: to my understanding from his first response, imsodin was interested in this, because he mentioned a mechanism that should avoid it.
