### ISSUE TITLE
Syncthing for Android destroys original file modification times

### ISSUE THREAD

**Issue by 101101100** [syncthing/syncthing-android#1390]
Because it is unfortunately impossible for me to reopen the original issue  #1389 
I hope not to upset anyone if I draw the attention to the topic again with this new issue. The unprofessional experiments I could think of, indicate to me, that at least on android 9, file modification time can be changed without root.
So, if Syncthing supported this where possible, it might make quite a number of users happy.

**Comment by AudriusButkevicius** [comment]
No point reopening issues. Our stance has not changed and it's still an android bug.
