### ISSUE TITLE
Android 10 startup issue

### ISSUE THREAD

**Issue by ericfowler303** [syncthing/syncthing-android#1391]
Just updated from Android 9 to 10 using the OTA method from google (didn't use any android betas). When opening Syncthing after the update, this appears in the syncthing log when starting the app:
--------- beginning of main
--------- beginning of crash
09-03 13:29:51.756 W/SyncthingNativeCode( 7489): error: "/data/app/com.nutomic.syncthingandroid-pCdyCkBfkyTKS54dI9MnOA==/lib/arm64/libsyncthing.so": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic

My install was previously configured and has existing connections to other devices. I assume this is related to some change in Android 10.

### Version Information

    App Version: 1.2.2
    Syncthing Version: latest (can't get into app menus)
    Android Version: Android 10.0 (Pixel 2 XL)

**Comment by AudriusButkevicius** [comment]
#1291
