### ISSUE TITLE
Non-Functional on Android 10

### ISSUE THREAD

**Issue by Athanasius** [syncthing/syncthing-android#1392]
I got the shiny new Android 10 update on my Google Pixel 2 XL today.  Most things are working, but SyncThing is one that isn't.

It starts with phone boot, but the notificaiton is stuck on "Syncthing is starting.", and opening the Syncthing app just endless spins the "Loading" spinner, not allowing for any interaction until it times out.  When it does the log appears to only contain

"-------- beginning of main"

and the Android Log is full of

"<timestamp> I/chatty (<number>) uid=<number> (com.nutomic.syncthingandroid) identical <count> line(s)"

Going back from there to the main screen still only shows a spinner, the Folders/Devices tabs react to tap, but nothing displayed in either, and the menu burger (or swiping out from left) does nothing.

I've signed up for Play beta access for the app if that helps.

### Version Information

    App Version: 1.2.2
    Syncthing Version: v1.2.2 (on a Debian Stretch/oldstable system)
    Android Version: Android 10.0 (5 September 2019, build QP1A.190711.020)

**Comment by AudriusButkevicius** [comment]
Check closed issues.
