### ISSUE TITLE
[RFE] make connection to peer only if necessary

### ISSUE THREAD

**Issue by sopos** [syncthing/syncthing-android#1394]
If there are only "send only" folders there's no need to keep connections to peers open if there's nothing to sync. This might save some battery life.

**Comment by AudriusButkevicius** [comment]
How do you know there is nothing to sync, what if the other side modified something and reverted their changes? What the other side cannot connect to you and only you can connect to them? Do you want to leave them indefinitely out of sync?

**Comment by AudriusButkevicius** [comment]
Its a continuous sync application, hence wanting a continuous connection is a pretty understandable thing. You can disable syncthing if you don't want it to consume your battery.

**Comment by sopos** [comment]
> How do you know there is nothing to sync, what if the other side modified something and reverted their changes? What the other side cannot connect to you and only you can connect to them? Do you want to leave them indefinitely out of sync?

Is there are only "send only" folders, we should not care about the remote changes. As far as I understood the local app is watching changes, so if there's no change detected, no sync is necessary.

..just an idea for optimization

**Comment by AudriusButkevicius** [comment]
I think it's a bad idea, as you cannot guarantee that the other side can reach you if it needs to, leading to outcries of users complaining their stuff is out of sync because their devices refuse to connect. Also, maintaining a connection is not actually expensive in terms of battery.

**Comment by sopos** [comment]
> Also, maintaining a connection is not actually expensive in terms of battery.
Ok, this is good argument. Thanks
