### ISSUE TITLE
.stfolder(s) keep disappearing automatically

### ISSUE THREAD

**Issue by maks-io** [syncthing/syncthing-android#1396]
Hi everyone,

I don't know if it is my phone, or the app itself, but my `.stfolder`s keep disappearing, and therefore causing the error message `Error (folder marker missing)`. They randomly (?) disappear from time to time, only for my two syncthing folders on my internal storage (!). I also have another syncthing folder on my external storage (read-only for other devices, since it seems to be impossible right now to write to external sd cards), and it seems like i do not lose the `.stfolder` there!

I can always fix it manually, by just creating new `.stfolder`s, but that's not a long-term solution of course.

### Version Information

    Phone: Huawei P20 lite (ANE-LX1)
    App Version: 1.2.2
    Syncthing Version: v1.2.2
    Android Version: Android 9 (EMUI version 9.1.0)

**Comment by AudriusButkevicius** [comment]
Your OS is deleting empty directories.
Create something inside of the .stfolder directory yourself.

**Comment by pansa** [comment]
> Your OS is deleting empty directories.
Hi all! 
I think that is some of cleaning activity on Android is removing empty folder. I have got same problem on Xiaomi mi6 after do "Clean device". 

So, I think it is a good feature for Syncthing will create any little stub file inside .stfolder in case problem reproduces.

**Comment by Catfriend1** [comment]
Xiaomi has a cleaner app with system permissions in place doing this. You could probably work around this by force uninstalling the cleaner with "adb uninstall --k user 0 pkg_name" from a pc command line to get rid of the problem. Careful: this may break your MiUi Rom and prevent the phone to boot if Xiaomi protected the app from being deleted. Tried it with success on my phone under MIUI 9+10 but cannot assure it will be non-damaging in future.

**Comment by pansa** [comment]
Thank you, Catfriend1
but creating a few-byte stub file is more simplier and safetier, isn't it?

**Comment by Catfriend1** [comment]
Sure...
