### ISSUE TITLE
1.2.2.2 immediately force closing on launch

### ISSUE THREAD

**Issue by wangmaster** [syncthing/syncthing-android#1397]
I just got 1.2.2.2 and was excited that the android 10 issue was supposed to be fixed, but it now crashes immediately at start.

System logs on feedback show:
java.lang.SecurityException: Permission Denial: startForeground froom pid=xxxxx uid=xxxxx requires android.permission.FOREGROUND_SERVICE

This is on a pixel 2 xl and pixel 2 with syncthing 1.2.2.2.  I cleared data on one of the devices and it started up with the initial wizard but then crashed as soon as completing the wizard steps

**Comment by aamadorj** [comment]
Same issue here, but it's happening with Android 9, after Play Store updated the previous version of the app. I tried clearing cache but it didn't fix the immediate crash at start.

**Comment by hijewpositive** [comment]
Same thing on Pixel 3 w/Android 10

**Comment by sinatosk** [comment]
Same issue on Pixel 3a xl on Android 10

**Comment by kafji** [comment]
Happen on my S10 on Android 9 as well.

Stacktrace:
![Screenshot_20190909-112420_Google Play services](https://user-images.githubusercontent.com/1842143/64501785-74ce2c00-d2f5-11e9-9464-262eaaf8acee.jpg)

I think this commit, c9a1b2b04828fd6325856e8fdc35d7bae6c1bd2b, that causes the issue.

**Comment by wangmaster** [comment]
Looks like this was a documented change for api version 28 and higher:
https://developer.android.com/about/versions/pie/android-9.0-changes-28

I'm not an android developer by any stretch, so don't feel comfortable doing a PR but this doesn't look like anything too ugly to fix.

**Comment by TrentSPalmer** [comment]
Confirm, v1.2.2.2 crashing on Moxo X4 Android One, and on a Pixel XL, but v1.2.0 still works fine on another Pixel.

**Comment by xzsk2** [comment]
I add the FOREGROUND_SERVICE permission and build it myself, everything works fine.
Easy to fix but I don't really know how to make a proper PR.

**Comment by AudriusButkevicius** [comment]
You can modify the text file with github editor.

**Comment by kafji** [comment]
@wangmaster @xzsk2 Yup, adding that permssion solve the crash issue.

I've submitted a PR for it https://github.com/syncthing/syncthing-android/pull/1401.

**Comment by kafji** [comment]
Welp, just noticed that you guys made the changes already https://github.com/syncthing/syncthing-android/commit/b16be9a08508b477745f2f11aa6c67e49222159c

Thanks!

**Comment by AudriusButkevicius** [comment]
I've released 1.2.2.3 from my mobile, might take some time to flow through the play store pipelines

**Comment by bwuyun** [comment]
same issue on xiaomi mix2s on android 9

**Comment by AudriusButkevicius** [comment]
Seems the update trickled through, can someone verify?

**Comment by AudriusButkevicius** [comment]
New release seems to fix it for me, closing it.

**Comment by novoid** [comment]
> Seems the update trickled through, can someone verify?

2019-09-09T17:18 CET in Austria: no update available yet.
