### ISSUE TITLE
Crash on launch on android 10 with F-Droid build

### ISSUE THREAD

**Issue by dantuck** [syncthing/syncthing-android#1409]
Fresh install after 1.2.2.2 issues. App crashes on load. Android version 10.

3.18.137-g382d7256ce44
#1 Fri Jul 12 06:00:07 UTC 2019

--------- beginning of main
09-11 20:24:35.781 W/SyncthingNativeCode( 7866): error: "/data/app/com.nutomic.syncthingandroid-pgCuVRaUM3EPcTIh_Mvp6Q==/lib/arm64/libsyncthing.so": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
--------- beginning of crash

**Comment by AudriusButkevicius** [comment]
I don't think this is 1.2.2.3, this has to be an older version as 1.2.2.3 fixes this issue exactly

**Comment by octos** [comment]
I installed Syncthing using F-Droid, and I'm getting the same error. Some users report that 1.2.2.3 fixed their 1.2.2.2 issues here: [1291](https://github.com/syncthing/syncthing-android/issues/1291); is is possible that they installed the update off the Play Store and that their build is somehow different?

I hoped that by changing the run conditions to disable Syncthing while it's trying to run, I'd be able to access the settings and export my configuration to reinstall the app. It almost worked, but the Backup option is disabled!

**Comment by dantuck** [comment]
I have tried several installs from F-Droid. I have verified that I am installing the 1.2.2.3 version from the repository and verified in the versions section.

**Comment by AudriusButkevicius** [comment]
Ah, fdroid still builds with an old version of go, so stuff won't work until they move forward.

**Comment by dantuck** [comment]
According to the PR there is a merge conflict which needs resolved.

**Comment by dantuck** [comment]
I found that the PR was fixed and merged. Since the version is likely the same `1.2.2.3` will there be issues in the upgrade in F-Droid? Will we need to uninstall `1.2.2.3` and then reinstall?

**Comment by maave0** [comment]
It should update fine. Android apps have a separate versionCode (integer used to track updates) and versionName (arbitrary string like "1.2.2.3")

**Comment by imsodin** [comment]
I had to push a new "release" 1.2.2.4, which to make F-Droid rebuild and re-distribute 1.2.2.3 for F-Droid. It has been recognized (https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.nutomic.syncthingandroid.yml) but not yet built (https://f-droid.org/packages/com.nutomic.syncthingandroid/) by F-Droid. There's nothing to do there but to just wait until that happens.

**Comment by hubertbanas** [comment]
Thank you all for working this out.
