### ISSUE TITLE
1.3.0  crash soon after startup (phone reboots)

### ISSUE THREAD

**Issue by khumarahn** [syncthing/syncthing-android#1421]
Hi, I am on android 9, lineageos, zuk z1.

After upgrade to 1.3.0 (fdroid), the app crashes a few seconds after startup (the phone reboots). An attempt to downgrade with f-droid gives "unknown error".

Not sure how to even find what the error is.

**Comment by AudriusButkevicius** [comment]
https://forum.syncthing.net/t/phones-reboot-with-syncthing-1-30-under-lineageos-16-on-htc-m8/

**Comment by klausenbusk** [comment]
See also: https://github.com/syncthing/syncthing-android/issues/1425
