### ISSUE TITLE
Syncthing does not write to external storage on Android 8.0.0

### ISSUE THREAD

**Issue by jonaheinrichs** [syncthing/syncthing-android#1424]
I want to sync my external SD-Card 2-way. But Syncthing says it is read-only.

Syncthing has the permission to edit the sd-card.
![Screenshot_20191011-124253_Package installer](https://user-images.githubusercontent.com/26126206/66646052-583f4f80-ec25-11e9-8524-c2da3a607a3d.jpg)

But it does not request the write permissions to write to the external SD-Card:

![Screenshot_20191011-125207_Settings](https://user-images.githubusercontent.com/26126206/66646292-14007f00-ec26-11e9-9be9-844cd47a348e.jpg)

![Screenshot_20191011-125650_Syncthing](https://user-images.githubusercontent.com/26126206/66646652-18796780-ec27-11e9-804d-74253a4621d6.jpg)

Why not?

### Version Information

    App Version: 1.3.0
    Syncthing Version: v1.3.0
    Android Version: Android 8.0.0 / Samsung

**Comment by AudriusButkevicius** [comment]
Check existing open issues. Write access to sd card is only supported at a specific path due to limitations of android/go.
