### ISSUE TITLE
Syncthing Android not detecting changes 

### ISSUE THREAD

**Issue by jeff9315** [syncthing/syncthing-android#1429]
Syncthing Android not detecting changes 

This appears to be related to #1353

Whenever I make a change to any file on my Android phone (in any Syncthing monitored folder), it fails to get propagated to my Win 10 PC ... until I restart Syncthing-Android. It doesn't matter whether I restart Syncthing on my Win 10 PC. It's only when I restart Syncthing-Android. 

My phone is an Honor 7x.

Before restarting Synctrhing-Android, I go to my Win 10 PC, in Syncthing, under the correct folder, it shows "Latest Change" and it actually shows the file, but if I open the folder it's still the old one with the old date ... until I restart Syncthing-Android. 

### Version Information

    App Version: 1.3.0
    Syncthing Version: v1.3.0
    Android Version: Android 8.0

**Comment by AudriusButkevicius** [comment]
Seems like a dup of the ticket you referred to. This should ideally be debugged on the forums.
