### ISSUE TITLE
folders on the SD card ignore .stignore

### ISSUE THREAD

**Issue by JGJP** [syncthing/syncthing-android#1442]
So I imagine that the "Ignore Patterns" feature was disabled for SD cards because of the other issues with doing two way sync on the SD card.

However, I am able to create an .stignore file through other means, would it be possible to have syncthing still honor the .stignore file? Since we know it's able to read the contents of the SD card, if not write.

**Comment by AudriusButkevicius** [comment]
It is honored. You can try opening it over web ui, I suspect you got the path wrong.

Also, support happens on the forums.

**Comment by JGJP** [comment]
Ok seems that it requires a restart
