### ISSUE TITLE
Battery usage

### ISSUE THREAD

**Issue by deatsev** [syncthing/syncthing-android#1446]
The last few days, the battery started to discharge very quickly. Over the last night, the application discharged the phone almost completely, while no synchronization was performed, the application was just launched in the background.

    Device: Oneplus 5T
    Syncthing Version: v1.3.1
    Android Version: Android 9.0 / Oxygen OS Open Beta 33

![image](https://user-images.githubusercontent.com/58027505/69321772-bd3e8a00-0c54-11ea-9cbe-009167c93b59.png)

**Comment by AudriusButkevicius** [comment]
Please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for simillar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.
