### ISSUE TITLE
Active wifi but no connection eats battery

### ISSUE THREAD

**Issue by erikvanoosten** [syncthing/syncthing-android#1449]
Recently I started using a wifi network that requires me to login every day. Typically I only do this a couple of hours after my phone connects to the wifi. Exactly since the same day Syncthing started using a lot more battery.

What happened:
* battery could easily support my phone for 2 days, now not anymore.
* I expect an active wifi without connection to have no influence on battery usage.
* To reproduce you need to find a wifi network with a login page. Simply do not login and see battery usage going up.

### Version Information

    App Version: 1.3.1
    Syncthing Version: v1.3.1
    Android Version: Android 9 (Aarch64)

**Comment by AudriusButkevicius** [comment]
Hey, 

Can you try and get the logs as this is happening?

There is also a bug that was fixed in 1.3.2rc, so you might want to try that.

**Comment by Catfriend1** [comment]
Hi,

Thinking about possible causes I don't get any path to why WiFi without internet connection should drain battery more. May this be related to discovery then? I expected discovery to have little impact as it shouldn't happen every second?!

**Comment by AudriusButkevicius** [comment]
I suspect it's the quic non-stop accept loop that should be fixed in 1.3.2 I believe.

**Comment by erikvanoosten** [comment]
I have 1.3.2 now and the situation did not improve :(

**Comment by AudriusButkevicius** [comment]
You should check whats happening in the logs.

**Comment by erikvanoosten** [comment]
Its working fine again!
A space character was used to separate two addresses of a remote. After replacing the space with a comma, battery usage dropped to normal levels.

**Comment by erikvanoosten** [comment]
I'll open a new issue.
