### ISSUE TITLE
Files containing "non-NFC UTF-8 sequences" cannot be scanned in android

### ISSUE THREAD

**Issue by AvakianB** [syncthing/syncthing-android#145]
Files containing "non-NFC UTF-8 sequences" such as Inspiración.mp3 are properly scanned on my os x platform and then synced to android. At that point if they are deleted or changed on android it appears to be registered on the mac. However, if the file is first introduced on the android, then it is not scanned or recognized and I receive the error message: File "..." contains non-NFC UTF-8 sequences and cannot be synced. Consider renaming.

This error seems to be associated with Syncthing 0.8.19 in the main branch. I am running v0.9.19 on android.

**Comment by Zillode** [comment]
Fixed in upstream https://github.com/syncthing/syncthing/commit/8311162be31d5f3e5fb4bd4c21ddf5e7356802cf
