### ISSUE TITLE
Cell disconnects when local discovery is enabled

### ISSUE THREAD

**Issue by daradib** [syncthing/syncthing-android#1461]
When Syncthing Android is running with local discovery enabled (default), the cell connection disconnects (and reconnects a few seconds later) every ~30 or ~60 seconds, breaking cellular voice calls. When run options are set to wifi-only (default) and wifi is connected (so Syncthing is running), the cell connection still interrupted. If local discovery is disabled, the app is force stopped, or a VPN is used, the cell connection is not interrupted.

With the beacon debugging facility enabled, I see local announcement packets coinciding with the cell disconnects. Cell carrier is Visible (Verizon MVNO) which is LTE-only so cell service requires IMS/VoLTE.

The carrier might be triggering the disconnect, but was I unable to reproduce it in Termux running:

    echo -n hello | socat - udp-datagram:<cellular link broadcast address>:21027,broadcast
    echo -n hello | socat - udp-datagram:255.255.255.255:21027,broadcast
    echo -n hello | socat - udp-datagram:[ff12::8384]:21027

### Version Information

    App Version: 1.3.2
    Syncthing Version: v1.3.2
    Android Version: Android 10.0.0 (QQ1A.191205.008, Dec 2019) on Pixel 3 XL - affects both stock and AOSP build

**Comment by AudriusButkevicius** [comment]
First of all this is the wrong repo, second of all, this is an issue with the phone and not the app, as no app should be able to affect cellular connection of the device. I think there already exists a similar issue in the android issue tracker and it's only an issue with some specific rom.

**Comment by calmh** [comment]
Right repo tho

**Comment by AudriusButkevicius** [comment]
Ah sorry, same icon, hence confused.

**Comment by AudriusButkevicius** [comment]
I can't find the original issue to point to, But regardless, the stance is the same, it's a rom/provider issue rather than an application issue. as no application should be able to do that (and we don't try to do something dodgy intentionally).

**Comment by Catfriend1** [comment]
Ref.: https://forum.syncthing.net/t/syncthing-killing-phone-connection-calls-android-10/13825/13

**Comment by daradib** [comment]
Thanks @Catfriend1. Same carrier, (almost) same phone, looks like the same issue. Can we unlock the topic so I can reply there? Otherwise, I can start a new thread.

**Comment by AudriusButkevicius** [comment]
I've unlocked it

**Comment by daradib** [comment]
Thank you!
