### ISSUE TITLE
After Android 10 upgrade sync folder missing. Can only choose Downloads folder.

### ISSUE THREAD

**Issue by bre75** [syncthing/syncthing-android#1462]
Hello,

Since I upgrade to Android 10 (OnePlus 6, OxygenOS 10.3.0), my sync folder disappeared and when i want to configure a new one it doesn't let me choose anything but the Download folder.
I can't navigate anywhere else to choose another folder.
If i create a folder in the Download one and choose it it's saying i can't use it and i must choose one on the internal or external memory.

Syncthing app (F-Droid) : 1.3.2 

Thx for any help.

Regards,

**Comment by hardycz** [comment]
Why is this issue closed? It's still impossible to select any folder except the "downloads" one.

**Comment by Catfriend1** [comment]
Because this is an Android issue and not Syncthing's.
