### ISSUE TITLE
Don't work on white-listed wifi 

### ISSUE THREAD

**Issue by ANOka79** [syncthing/syncthing-android#1466]
Syncting can't work, when I set a white-listed wifi. My phone use the right wifi.
(See attachments.)

![Screenshot_20200117-210953_Syncthing](https://user-images.githubusercontent.com/60072903/72686039-a4d1db00-3af0-11ea-9572-84ae6ca73d74.jpg)
![Screenshot_20200117-211000_Syncthing](https://user-images.githubusercontent.com/60072903/72686040-a4d1db00-3af0-11ea-85fd-139af82a2950.jpg)
![Screenshot_20200117-211018_Syncthing](https://user-images.githubusercontent.com/60072903/72686041-a56a7180-3af0-11ea-8eb1-052dc713f1e5.jpg)

### Version Information

    App Version: 1.3.3
    Syncthing Version: v1.3.3
    Android Version: Android 9 / Samsung Galaxy A40 (SM-A405FN)

**Comment by Catfriend1** [comment]
Hi,

Could you please grab some logs and - preferably - open a forum thread at forum.syncthing.net please?

**Comment by capi** [comment]
If I interpret your 2nd screenshot correctly, you have location disabled. Unfortunately Android >= 8 (I think) has tied getting the SSID to location services.

**Comment by capi** [comment]
https://forum.syncthing.net/t/white-listed-wifi-bug/14362

**Comment by AudriusButkevicius** [comment]
Pretty sure this is due to android requiring location being enabled for ssid names.
