### ISSUE TITLE
Syncthing-android on Chromebook hangs on generating keys

### ISSUE THREAD

**Issue by OfotViking** [syncthing/syncthing-android#1467]
App Version: 1.3.3 and 1.3.4-rc.1
    Android Version: 9, January 1. 2020 security patch
    Android kernel version 4.14.157-14174-g4f85102f3af2
    Build number R80-12739.37.0
    ChromeOS 80.0.3987.58 beta octopus

First start of syncthing-android on chromebook hangs on message "Generating secure keys. This may take a few minutes."

Nothing seems to happen.

Force close and second run just result in the orange spinning circle

**Comment by AudriusButkevicius** [comment]
I think this is a dup of #1451 hence closing.
