### ISSUE TITLE
Recreate @folder marker@

### ISSUE THREAD

**Issue by mrkingmidas** [syncthing/syncthing-android#1468]
Hello!

Situation: on some phones (for example, Xiaomi), the standard “garbage removal” also deletes empty folders, as a result of which the “folder marker” is lost and the folders in Syncthing are no longer synchronized. Unfortunately, the manufacturer did not provide for a “permanent” setting to not do this, and since several “initial” users use the phones and lose their settings, this is very inconvenient.

Question / suggestion: Add a setting to the program that would automatically try to recreate the marker. In order not to go in cycles, add a check-if it didn’t work, then no longer try to create it.

### Version Information

    App Version: 1.3.2
    Syncthing Version: v1.3.2
    Android Version: Android 8.0

**Comment by imsodin** [comment]
Please search existing issues: https://github.com/syncthing/syncthing-android/issues/1396
