### ISSUE TITLE
Bug: setting WiFi SSID condition for a SSID disable ST

### ISSUE THREAD

**Issue by maudam** [syncthing/syncthing-android#1469]
I set a condition to use only my WiFi for sync but Syncthing answer with "Disabled: Current WiFi unauthorized" but the WiFi is up and connected to the authorized SSID.

I'm unable to get logs for WiFi check:
SSTRACE enabled: connections, discover.
Do i have to enable others ?

V 1.3.2 on android 9

**Comment by Catfriend1** [comment]
Hi,

You nees to turn location on.

**Comment by maudam** [comment]
Thanks
Not a ST bug but an android limit.
