### ISSUE TITLE
Android listing changelog url adding extra bracket

### ISSUE THREAD

**Issue by hartraft** [syncthing/syncthing-android#1475]
I wanted to upgrade to version 1.3.4 of Syncthing and I see the changelog in the Google Play Store appends a bracket ")" to the end of the changelog url. This results in a 404 when clicking the link. See screenshots below

The related [commit](https://github.com/syncthing/syncthing-android/commit/299ad5cc06b09812f24f7c2b2bab2aaea80a7cb5#diff-ec03a38b85b014c60378b0c111312f73) looks correct in the markdown.

https://imgur.com/wPMQh5i
https://imgur.com/Lb25yl5

### Version Information

    App Version: 1.3.3
    Syncthing Version: v1.3.3

**Comment by Catfriend1** [comment]
I suggest using a space like: text ( link )

**Comment by hartraft** [comment]
@Catfriend1 The markdown for the links are working well in the Google Play Store now. Closing this issue.

**Comment by imsodin** [comment]
Ah yes thanks for the suggestion and noticing the fix - I forgot about his issue :)
