### ISSUE TITLE
Ability to local-sync to Wi-Fi-/USB-/Bluetooth-tethered devices

### ISSUE THREAD

**Issue by drws** [syncthing/syncthing-android#1476]
The title actually says it all. These options could be implemented as run conditions in the UI.

The idea should work with minimal changes with Wi-Fi- and USB-tethered devices as these are Ethernet-type devices. I'm not sure about Bluetooth or its Android implementation, but at least the first two would be really useful (and more secure/reliable) to have.

**Comment by AudriusButkevicius** [comment]
Sorry, but this is not going to happen. The application is mostly targeted towards desktops, in which these options make no sense.

You can already sync locally over local network using local discovery.

**Comment by imsodin** [comment]
I think they are talking about the android UI. It's already possible by activating the run condition for no connections or airplane mode (don't remember the name). See https://github.com/syncthing/syncthing-android/issues/1308#issuecomment-506848636
