### ISSUE TITLE
"Syncthing is starting" permanent notification

### ISSUE THREAD

**Issue by SkyWheel** [syncthing/syncthing-android#1484]
Hi folks,
I'm using rooted LineageOS 16 with AFWall+.
All outgoing traffic is allowed for Syncthing, inbound connections from LAN enabled. But Syncthing is always "starting". It starts working if AFWall+ disabled.
Does anybody have any idea how to fix that?

**Comment by AudriusButkevicius** [comment]
First of all, this is not really a bug report but a support requests, which are not handled on the issue tracker, they are handled on the forum.

Secondly, disabling your firewall helps, so just keep it disabled. We can't really tell you how to make other applications not screw up syncthing.

**Comment by Catfriend1** [comment]
If you are reading this and having the same problem, please join the discussion / debug at https://forum.syncthing.net/t/syncthing-afwall/14799 instead of posting here. Thank you.
