### ISSUE TITLE
different OS, same computer (issue?)

### ISSUE THREAD

**Issue by zvoxmedia** [syncthing/syncthing-android#1492]
I use several computers, with OSes ran from USBflash drives.
I had syncthing on the same machine, but 2 different OSes.
The second one I installed ST on seems to have ST removed.
I wonder if this is a security measure, (which makes sense if some 3rd party was usig ST for deleterious ends).

ST has been the greatest application I've ever used! It really optimizes my workflow!
Wondering if I can help fix this issue so that i can use it my way, but also mitigate security issues. 

Thanks!

**Comment by AudriusButkevicius** [comment]
Hey,

This is the android application issue tracker, so I think you are in the wrong place.

Questions usually go on the forum, but I suggest you do a search there before hand as I am pretty certain this was answered before.

Thanks.

**Comment by zvoxmedia** [comment]
Thanks! Will check out the forum!
