### ISSUE TITLE
Folder status not showing synching

### ISSUE THREAD

**Issue by dpsenner** [syncthing/syncthing-android#1502]
I propose to improve the status in the folder tab. Currently it is shown only in the devices tab. It would be great if the status 'synching' is visible in the folders tab, too.  Progress in percent is optional and possibly hard to calculate when folders are shared with multiple devices, but could be a nice further improvement.

### Version Information

    App Version: 1.4.0
    Syncthing Version: v1.4.0
    Android Version: Android 8.0.0

**Comment by wweich** [comment]
Folder status is about what you are doing.
Device status is about what that device is doing.

So if you are in sync, folder status is "in sync".
If a device needs files from you, that device's status is "syncing".

**Comment by dpsenner** [comment]
Thanks for the quick feeback. Just to make sure we understand both the same on the proposed feature. You do not think that it would be an improvement to show 'synching' on a folder while it is being synched with another device?

**Comment by wweich** [comment]
No I don't, as you then would not know, if you are in sync or not.
Also, Syncthing Android displays the status as it is reported by syncthing and should stay consistent.

**Comment by imsodin** [comment]
I am not quite sure I understand, but please lets have this discussion to get on the same page on it on https://forum.syncthing.net/, not here on the issue tracker - thanks.

**Comment by AudriusButkevicius** [comment]
He's suggesting that folder status should show remote device completion of that folder. This would hide local folder progress, hence it's not something that makes sense to do, hence I feel it will not be a fruitful discussion.
