### ISSUE TITLE
Am I crazy or is syncing to SD card working in Android 11?

### ISSUE THREAD

**Issue by anderspitman** [syncthing/syncthing-android#1503]
I've read through #29 and most of the links in there. From what I gather, syncthing shouldn't work with an SD card. Unfortunately I don't have a physical device to test this on. But I started up an Android R AVD emulator with an SD card, and syncthing seems to be writing to the SD card ok. I set it up as a separate storage device, not combined with internal memory. I can see the files from both the Amaze File Manager and Files by Google apps.

Am I missing something?

**Comment by AudriusButkevicius** [comment]
If you want to have a discussion about this or have questions, please use the forum. This doesn't look like a ticket that is actionable, so I Don't see any point keeping it open.

I don't think emulator is representative of a real environment.

**Comment by anderspitman** [comment]
Ok, I'll try the forum.

**Comment by imsodin** [comment]
As this issue might get a bit of traffic, here's the forum topic: https://forum.syncthing.net/t/am-i-crazy-or-is-syncing-to-sd-card-working-in-android-11/14983  
Please put any further posts in the forum, not here.
