### ISSUE TITLE
Strange behaviour on "Ignoring templates" action.

### ISSUE THREAD

**Issue by DMantis** [syncthing/syncthing-android#1512]
1. Open folder settings
2. Click on "Ignoring templates" (should be like that, I have different language version)
3. Bitcoin wallet is opened instead of any templates settings.

Screen record (russian interface, but I guess it's recognisable by icons): https://streamable.com/3b7a3x

### Version Information

    App Version: 1.5.0
    Syncthing Version: v1.5.0
    Android Version: Android 9 / EMUI 9.1.0 (Huawei ROM)

**Comment by AudriusButkevicius** [comment]
This opens a default text editor, your bitcoin thing registers itself as a text editor.
