### ISSUE TITLE
TOR active even though disabled in settings

### ISSUE THREAD

**Issue by somm0s** [syncthing/syncthing-android#1517]
After setting up a new firewall I noticed that the threat detection system was flagging TOR traffic coming from/going to my phone. I observed the alerts for a few weeks and managed to reproduce the issue by uninstalling/installing syncthing-android. So whenever the app is stopped or uninstalled the alerts stop.
I also have a few other devices running syncthing (windows & linux) on the same network. Their traffic sometimes gets flagged as TOR too, but only when syncthing-android on my phone is started. 

![Screenshot from 2020-06-09 13-34-20](https://user-images.githubusercontent.com/36193673/84144344-65cd0380-aa58-11ea-9e41-5a9782850e81.png)
In the screenshot above you have the detection timestamp in the rightmost column. Notice that between 1:22pm and 1:33pm no traffic has been flagged. This matches exactly with me uninstalling, waiting, and then installing+starting up syncthing-android.

TOR is obviously disabled in Settings > Experimental > Use Tor.

### Version Information

    App Version: 1.6.1
    Syncthing Version: v1.6.1
    Android Version: OxygenOS 10.3.3 (Android 10)

**Comment by imsodin** [comment]
One of those is a relay, and by extension I am quite sure all of them are (https://relays.syncthing.net/). Whatever you use to "detect TOR" is simply wrong.
