### ISSUE TITLE
Metered networks (not on wifi) only sync files smaller than x

### ISSUE THREAD

**Issue by jtagcat** [syncthing/syncthing-android#1518]
Most of my syncs are a few kB, I would normally allow cellular syncs, but because there can be one large file, I'm keeping it non-metered networks only. It would be nice to limit file size for (cellular) metered networks.

**Comment by AudriusButkevicius** [comment]
Sorry, but I don't think it's reasonable specialising this way, as people will want various other options, file extensions etc, which I think it's a pandoras box.
