### ISSUE TITLE
Run sync as superuser

### ISSUE THREAD

**Issue by morfikov** [syncthing/syncthing-android#1521]
I found out that syncthing has issues with syncing SD card files, which is formatted as portable storage. One solution to that was to run the sync process as root, which can be set via Experimental subconfig option. My phone runs android 7.0 and I rooted the device earlier via Magisk. When I check the experimental option, syncthing is detected by Magisk and I grant the superuser access. Then weird things happen. 

When I restart syncthing, on the bottom of the phone's screen I see the message "syncthing was granted superuser rights", but  it looks like the sync process is stopped and my phone can connect to any device it syncs files to/from -- it simply says disconnected in the device tab. Basically, I'm unable to turn the sync on when the root access is granted. When I uncheck the experimental option, then everything backs to normal.

Also when the experimental option is checked, I often see lots of the "syncthing was granted superuser rights" messages on the bottom of the screen. 

### Version Information

    App Version: 1.6.1 (Downloaded via F-Droid)
    Syncthing Version: v1.6.1
    Android Version: Android 7.0, stock rooted via Magisk

**Comment by AudriusButkevicius** [comment]
As you yourself said, superuser is an experimental feature, and it's possible that it does not work on all devices/roms.

I think we use libsuperuser for privilege elevation, so it might be that it's not compatible with Magisk, and you need to root with chainfire.

I suggest you check existing issues (open and closed ones) to see if you can find some information which might help.
Also, you could try searching the forum, or open a thread there with the logs to see if anyone has any input.

Closing this, as I think this is more of a support request than an issue we'd be fixing, given it's an experimental "best effort" feature anyway.

**Comment by tomasz1986** [comment]
I do not have Magisk root installed right now, but I believe that I did have Syncthing working with it on a device with Android 7.1 before.

I would rather think that the problem may be something (e.g. a firewall) blocking rooted applications from accessing the Internet (see https://forum.syncthing.net/t/syncthing-afwall/14799/11). Please open a forum thread if that is the case and you need more assistance.

**Comment by morfikov** [comment]
I can confirm that the problem was in afwall.
