### ISSUE TITLE
Avoid recreating unnecessary "stfolder" in syncthing folders

### ISSUE THREAD

**Issue by crazyuploader** [syncthing/syncthing-android#1526]
After reinstalling the app, and adding folders to syncthing (were added to syncthing before), I've noticed a duplicate of `stfolder` named as such `stfolder (1)` which is quite unnecessary. But this issue isn't present in desktop version of syncthing. 

### Version Information

    App Version: 1.7.0-rc.1
    Syncthing Version: 1.7.0-rc.1
    Android Version: Android 9/MIUI 12

**Comment by AudriusButkevicius** [comment]
I don't think we create that

**Comment by crazyuploader** [comment]
> I don't think we create that

Who does? I've had this issues many times after changing ROM, I would install Syncthing and add folders in which `stfolder` exists, and there's another `stfolder (1)` existing there after adding it to Syncthing.

**Comment by AudriusButkevicius** [comment]
Our folder starts with a dot first and locally having removed and readded the folder a few times, I can't reproduce it.

**Comment by crazyuploader** [comment]
I'll attach a video as well steps to reproduce later to make myself more clear here ;)

**Comment by pashkamelnyk** [comment]
> I'll attach a video as well steps to reproduce later to make myself more clear here ;)

It is simple. Another side has unnecessary folders ".stfolder (1)", ".stfolder (2)" - they were lost during previous attempt to pair.
Just remove folders in Syncthing on both sides, remove unnecessary folders like ".stfolder (1)" in file system for both sides, then try to create pair of folders in Syncthing again and everything will be ok.

It is not issue, so the ticket can be closed.
