### ISSUE TITLE
application does not start after uptate

### ISSUE THREAD

**Issue by gabriel-tandil** [syncthing/syncthing-android#1528]
After the last update to version 1.6.1 (fdroid) the application does not start. A message is left in the message area saying "syncthing is starting". If I try to open the application from the icon it will not start

### Version Information

    App Version: 0.x.y
    Syncthing Version: v1.6.1
    Android Version: Android 4.4

**Comment by AudriusButkevicius** [comment]
Hi,

Try enabling switching to the beta channel and trying the 1.7.0 beta. (I am not sure how to do that on fdroid, might only be available on play store).

Thanks.

**Comment by gabriel-tandil** [comment]
i can't find it on fdroid, i'll wait for that version to be published, thanks

**Comment by AudriusButkevicius** [comment]
You could also check the logs via ADB, but I suspect it's the same as:
https://github.com/syncthing/syncthing-android/issues/1520

hence closing.
