### ISSUE TITLE
Your android version only grants Syncthing readonly access to the selected folder

### ISSUE THREAD

**Issue by Barkole** [syncthing/syncthing-android#1531]
### Version Information

    App Version: 1.7.0
    Syncthing Version: v1.7.0
    Android Version: Android 10

No sync is possible as syncthing only allows readonly: "Your android version only grants Syncthing readonly access to the selected folder"

**Comment by AudriusButkevicius** [comment]
I think the message is self explanatory?

**Comment by Barkole** [comment]
That is unfortunate. I wanted to move over from Resilio Sync to Syncthing. Resilio Sync is able to write. But Syncthing is not. It is a pity.

**Comment by martini097** [comment]
As all those apps do, you need to save your files under the syncthing folder on the sd card as described here: https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions

> Create your destination folders under Syncthing's application-specific folder, e.g. /storage/014A-7323/Android/data/com.nutomic.syncthingandroid/files

>
