### ISSUE TITLE
Switch to a less invasive QR scanner app

### ISSUE THREAD

**Issue by michaeljensen** [syncthing/syncthing-android#1533]
The Syncthing app requires "Barcode Scanner" by ZXing Team when scanning host IDs.
This app has started requiring more and more permissions that are invasive to users' privacy.
As demonstrated by the screenshot below, it is requesting/using permissions that aren't required to function with Syncthing and that are invasive to privacy; including:
* Device & app history
* Contacts
* Wi-fi

![Screenshot](https://www.cybersecurityroad.com/wp-content/uploads/2020/07/Screenshot_20200723-080240-488x1024.png)

**Comment by sumit-anantwar** [comment]
Agreed,
When I saw that the Barcode scanner app was being used, I immediately ignored it and preferred typing in the whole identifier manually.
Implementing an internal scanner activity is extremely trivial.
Let me know if you are interested and I can create a PR for that.

**Comment by AudriusButkevicius** [comment]
Sure, PRs welcome

**Comment by sumit-anantwar** [comment]
PR created :point_up:

**Comment by michaeljensen** [comment]
I'm glad this dependency was removed already...
https://blog.malwarebytes.com/android/2021/02/barcode-scanner-app-on-google-play-infects-10-million-users-with-one-update/

**Comment by acolomb** [comment]
I feel like @michaeljensen's statement requires a rectification.  As the linked blog post itself clarifies, the scanner app formerly used by this Syncthing Android wrapper **has nothing to do with the malware incident**.  It simply shares the same short name.  Thanks @imsodin for locking this to stop more FUD from spreading.

**Comment by michaeljensen** [comment]
Thank you for rectifying my comment.  I didn't research it as much as I should have and the creators of the app referenced in this issue is not the same as the one mentioned in the article.  I apologize for that.  I don't want to spread FUD regarding this situation.   

Just to clarify, the ZXing "Barcode Scanner" IS NOT the same as the one that turned to malware.
