### ISSUE TITLE
Enhance the sync by timeline (5 min every hour) feature

### ISSUE THREAD

**Issue by DaDuFan** [syncthing/syncthing-android#1536]
First, thank you for this great App.

There is a feature to sync only for 5 minutes every hour.

Instead of syncing every hour for 5 minutes, it would be great when the times could be configured.

So that we could sync e.g. for 15 minutes every 4 hours

**Comment by AudriusButkevicius** [comment]
There is no feature to sync for 5 minutes every hour, it syncs continuously, and I don't think we want to add this sort of feature
