### ISSUE TITLE
Excessive battery usage

### ISSUE THREAD

**Issue by zaheernathani** [syncthing/syncthing-android#1541]
![Screenshot_2020-08-11-15-15-02-886_com miui securitycenter](https://user-images.githubusercontent.com/67725000/89883486-d5d94080-dbe5-11ea-853e-bce69e48e776.jpg)
Battery usage of Syncthing is highest even though I dont keep it open always

**Comment by AudriusButkevicius** [comment]
Please check existingssues and search the forum.

If you have further questions, use the forum.

**Comment by zaheernathani** [comment]
Don't find any issues raised?

**Comment by AudriusButkevicius** [comment]
There are ton of closed issues talking about battery usage with tips how to improve it:

![image](https://user-images.githubusercontent.com/1144861/89920297-235caa00-dbf4-11ea-9546-d04123250553.png)
