### ISSUE TITLE
Using second instance in work profile

### ISSUE THREAD

**Issue by chilliger** [syncthing/syncthing-android#1547]
I like to isolate some apps in the work profile with shelter. I tried to set up a second syncthing instance in the work profile being able to sync my password database between the main profile and the work profile. When I did this the instance in the main profile did not start normaly anymore. I only saw a loading dialog. I dont have the logs anymore but other clients state that my main profile device/client now has a"unexpected device id". I assume that syncthing generates the same device id for both profiles.

Is there a way to use a second instance in the work profile?

**Comment by AudriusButkevicius** [comment]
Sorry, but I don't think so, you'd need android OS to do the isolation, effectively installing the app twice.

**Comment by LinAGKar** [comment]
The main profile and work profile instances need to run on different ports

**Comment by chilliger** [comment]
> The main profile and work profile instances need to run on different ports. By default they both try to run on the same port, and one of them will win, which means the main profile app ends up connecting to syncthing on the work profile or vice versa.

So a second installation on the work profile works for you when changing the port?

**Comment by LinAGKar** [comment]
Yes, it does (well, until Google started messing around with the storage access).

**Comment by chilliger** [comment]
> Yes, it does (well, until Google started messing around with the storage access).

What setting exactly? Gui listen address?

**Comment by imsodin** [comment]
Please move this discussion/the debugging to https://forum.syncthing.net.

**Comment by LinAGKar** [comment]
>What setting exactly? Gui listen address?

Yes that one. If that doesn't work, I suppose you should create a forum thread as @imsodin suggested
