### ISSUE TITLE
Included Syncthing is a subversion behind. Mind updating it sometime?

### ISSUE THREAD

**Issue by CravenInsomniac** [syncthing/syncthing-android#1550]
The title says it all. Included Syncthing is v1.8.0, the current is Syncthing version v1.9.0.

    App Version: 1.8.0.4241
    Syncthing Version: v1.8.0

**Comment by tomasz1986** [comment]
The Play Store version is already 1.9.0. Do mean perhaps F-Droid? If yes, then you will have to wait for the F-Droid team to recompile and release a new version there. It usually should not take more than a few days.
