### ISSUE TITLE
Syns not start, via wi-fi from whitelist

### ISSUE THREAD

**Issue by andrewoficial** [syncthing/syncthing-android#1551]
Program version 1.9.0
Android 9
Emui 9.1.0
![Screenshot_20200916_112756](https://user-images.githubusercontent.com/28807056/93313104-b18a0880-f810-11ea-9c86-b9d5c5074302.jpg)
![Screenshot_20200916_112724](https://user-images.githubusercontent.com/28807056/93313171-cb2b5000-f810-11ea-8883-9418109c765b.jpg)
![Screenshot_20200916_112848](https://user-images.githubusercontent.com/28807056/93313208-da120280-f810-11ea-9e70-dbdacdd4f870.jpg)
![Screenshot_20200916_112929](https://user-images.githubusercontent.com/28807056/93313228-e26a3d80-f810-11ea-8b15-2b1e05cccd3f.jpg)
![Screenshot_20200916_113805](https://user-images.githubusercontent.com/28807056/93313421-1f363480-f811-11ea-9c4a-6efe823b2cc0.jpg)

**Comment by AudriusButkevicius** [comment]
Check existing closed issues. 

Reading wifi names requires "location" to be enabled the app to have permissions to read location, because google things knowing wifi name reveals your location.

**Comment by andrewoficial** [comment]
many thanks!
