### ISSUE TITLE
Syncing stops when the app is closed on MIUI 11

### ISSUE THREAD

**Issue by stz184** [syncthing/syncthing-android#1571]
I am using Syncthing 1.10.0 installed through F-Droid on my Xiaomi Redmi Note 5 Plus (Android 8.1.0/MIUI 11.0.2).
If the app is closed, the service stops and my laptop displays the device as "Not connected". 
My expectations were that the syncing will continue to work even if the app is not running. That's the way Syncthing behave on my girlfriend's phone with stock Android 10 - when the app is closed there is still a notification "Syncthing is running" and the syncing does not stop.

### Version Information

    App Version: 1.10.0
    Syncthing Version: v1.10.0
    Android Version: Android 8.1.0 /MIUI 11.0.2/

**Comment by mdeff** [comment]
Did you disable "battery optimization" for syncthing? The OS might not allow it to run in the background.

**Comment by contrapunctus-1** [comment]
@stz184 the solutions at https://dontkillmyapp.com/xiaomi will probably help.
