### ISSUE TITLE
Separate configuration for portable hotspot case

### ISSUE THREAD

**Issue by denis-yanko** [syncthing/syncthing-android#1587]
Hi All,

1st of all - huge thx for great tool! This is for sure in my top-10 SW ever list.

Here is my use-case and my small-issue==feature request.
1. I have Win OS dektop and syncthing there - let's call it D
2. I have my Androind phone and syncthing there - let's call it P
3. I have Adroid head unit in the car and syncthing there - let's call it H
4. D has 1 syncthing folder with P - let's call it F1
5. P has 1 syncthing folder with H - let's call it F2

Normal flow is == set of actions:
1. D&P are connected to WiFi at home and some files are synced from D to P via F1
2. When I come to car -> I turn on portable hot spot and H is connected to it
2a. I must go to Syncthing CFG and set option to let it work on mobile networks
3. On P I manually move files from F1 and F2
4. Profit - I do have files available on H

Issue:
1. To make sure I don't use mobile network during action #1 -> I need to a) don't forget to connect to WiFi net at home as 1st actiob and b) just in case turn off the thing from 2a action
2. And also I need to repeat 2a every time I come at car 

Notes:
1. This is small "nice to have" issue and I for sure will go on using your SW even if you do nothing about this request
2. Of course I will be happy if you (somewhere in advanced configuration) add the flag to handle my situation - somehow
3. I do understand that every product roadmap has its own priorities so this is OK if you leave this in backlog but I will be happy to hear something about the plans even if there are no plans

Once again - huge thx for great tool! 

WBR, Denis.

**Comment by AudriusButkevicius** [comment]
I still don't understand what you are asking for.

Things like connecting/disconnecting to networks can be done via tasker.

**Comment by denis-yanko** [comment]
OK ... sorry - likely I was not clear enough - let me try to comment from "another end".

What I am  asking for:
I as end user will be happy to have CFG parameter in Syncthing (in "Run Conditions" section) with name "Run on mobile data only if I have my mobile hotsopt turned on" and behaviour should be to allow SW to work only if I have mobile data + hotspot turned on. Of course, this parameter will work in pair with already existing "Run on mobile data" parameter.

What it will give to me:
1. I will have "Run on mobile data" and "Run on mobile data only if I have my mobile hotsopt turned on" always turned on and 
1a. When I am at home I will be sure that only home WiFi net is used
1b. When I am at car SW SW will still work since it will use connection to "syncthing-servers" to make connection between P&H but "local" hotspot network will be used for files transfer between P&H

As of now:
1. When I come to home and forget to turn off hotspot and turn on wifi -> all traffic on sync between D&P will go through my mobile data - this is why I turn off "Run on mobile data" when I stop P&H sync.
2. Whem I come to car I need to recall that I need to turn on "Run on mobile data" every time

Do you see what I mean?

**Comment by denis-yanko** [comment]
Forgot to mention - "What I am asking for" is previous comment is of course not written on stone in anyway --- meannig that if it will be some other parameter or I can solve me "issues" some other way -> it is of course OK

**Comment by AudriusButkevicius** [comment]
You can start/stop syncthing via tasker intents, I think anything more advanced than what we have should be managed by that.

We will not be able to cover every combination of scenarios people will ever want.

**Comment by denis-yanko** [comment]
> We will not be able to cover every combination of scenarios people will ever want.
understood - thx!

I was thiking that you may consider to put more attention in the SW on the case(s) when SW is using mobile data "as client" vs cases when we have "kind of local network" using mobile hotspot way + care about cost of mobile traffic vs home WiFi.

This is one of reasons why I have explained my usecase in details - hoping that it will drive you to wider thoughts about what I wrote above.

Of course, last thing I wanted is to make "excrescent" changes to CFG of the SW

Once again thanks for great tool and for your support!
