### ISSUE TITLE
PlayStore version not updated?

### ISSUE THREAD

**Issue by auanasgheps** [syncthing/syncthing-android#1589]
Hi,
On PlayStore I can see version 1.10 is the latest, whilst on F-Droid is 1.11.x as expected.
Are you dismissing Playstore in favour of F-Droid?
Just wanted to keep in sync :)

    App Version: 1.10.0
    Syncthing Version: v1.10.0
    Android Version: Android 11 / OnePlus 8T

**Comment by imsodin** [comment]
There were a few issues with google play that prevented us from publishing releases. The beta for Syncthing v1.12.1 has now been published, see https://forum.syncthing.net/t/call-for-testing-of-syncthing-android-1-12-1-rc-1/16016. Barring problems with that, the stable release will happen on 2.1.2021.

**Comment by auanasgheps** [comment]
Thanks for the prompt response.

**Comment by auanasgheps** [comment]
>  Barring problems with that, the stable release will happen on 2.1.2021.

Did you mean the 2nd of January or the 1st of February? PlayStore is still on 1.10.

**Comment by imsodin** [comment]
https://forum.syncthing.net/t/syncthing-version-behind-in-play/16177/3:

> After the policy issues it is now a “technical issue” and my request for support has been forwarded to the “correct department” a while ago. I am yet to hear back.

If you can, use F-Droid. Or the gplay beta channel, which for now still works.

**Comment by auanasgheps** [comment]
Will go for F-Droid, thanks.

**Comment by acolomb** [comment]
Today I received the v1.12.1 update through Play Store.  Just if anyone is interested and still waiting.

**Comment by auanasgheps** [comment]
Me too, on the device I hadn't switched over F-Droid, so everything should be good now.
