### ISSUE TITLE
'Permission denied' syncing symlinks to Android

### ISSUE THREAD

**Issue by JimBreton** [syncthing/syncthing-android#1590]
I am trying to use Syncthing to sync a Linux directory containing Emacs Org Mode files (*.org) to my Android device, for using with Orgzly.  Mostly it works great, except periodically Emacs will write a symlink into the Sync directory.  I am not sure when, but it is intermittent/occasional, I believe for the Emacs 'interlock' but not certain.  At any rate, when Syncthing on Android attempts to sync this symlink, it throws a 'permission denied' error and goes out of sync.

Not sure if it's possible to ignore the symlink, or, if it's possible to actually sync it.  Maybe the permission denied error is due to the 'apparent' fs permissions on a symlink (rwxrwxrwx)?  Just guessing.

    'Permission denied' error
    Actually sync the symlink; or ignore it
    Can be reproduced by creating a symlink in the directory that gets synced to the Android device

Thanks!

### Version Information

    App Version: 1.10.0
    Syncthing Version: v1.10.0
    Android Version: Android 11

**Comment by imsodin** [comment]
For the most part Android does not support symbolic links. It uses some FS that "simulates" FAT (sdcardfs). However I think there are workaround to that, probably only applicable to custom ROMs/rooted devices. Anyway, not something the app can handle and ignoring by type isn't possible in Syncthing itself.
