### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by DorKeinath** [syncthing/syncthing-android#1597]
I would like to sync files stored in a container encrypted with VeraCrypt. I'm opening that container with [EDS lite ](https://github.com/sovworks/edslite).

Activating the extended folder choice it would be great to see the opened/encrypted folder. 

The _files_ manager of LOS tells me the Uri _content://com.sovkworks.eds.android.providers.documents.lite/document/...._ and the Raw mimetype _vnd.android.document/directory_

May be it helps you to implement this feature if you know that [OpenCamera](https://sourceforge.net/p/opencamera/code/ci/master/tree/) is getting access to this kind of folders, too.

**Comment by AudriusButkevicius** [comment]
Sadly, we sync simple files. There are thousands of different container types out there, and we don't want to be in the business of having to understand them.
