### ISSUE TITLE
Missing App permissions

### ISSUE THREAD

**Issue by breakwaterlabs** [syncthing/syncthing-android#160]
Currently SyncThing on Android will not sync files to the /storage/emulated/0/Music folders, due to "access denied".

I believe it needs to request either SD card access or media file access.

**Comment by lkwg82** [comment]
Is this still relevant?

**Comment by plittlefield** [comment]
No, please close it.

**Comment by lkwg82** [comment]
@plittlefield my fault, it is already closed
