### ISSUE TITLE
Allow configuring of encryption password to share with untrusted devices

### ISSUE THREAD

**Issue by ni-ka** [syncthing/syncthing-android#1615]
New Syncthing user, so may be missing something here. 

According to https://docs.syncthing.net/branch/untrusted/html/users/untrusted.html it is possible to configure an encryption password per device which allows to encrypt the data. This could be quite useful to share with cloud providers or other plattforms that do not support full disk encryption.

**Comment by imsodin** [comment]
Untrusted devices/encryption has not been released.and you should not yet use it in production. The docs link above points at preliminary docs that are still in review. For more info on the feature read: https://forum.syncthing.net/t/early-testing-for-untrusted-encrypted-devices/15873

I'll close this issue for now. Re-opening can be considered once the feature is released in Syncthing. Though unless a new contributor steps up to implement it, controls in the app will likely not happen regardless (still accessible through web-ui as usual).

**Comment by ni-ka** [comment]
Thanks @imsodin , it wasn't clear to me that it was not yet released. I landed on that page from Google, it might be good to have some kind of indication or header that this is not for a release.

**Comment by Dmole** [comment]
@imsodin can we re-open this?
un-trusted server support from Android would be nice.

**Comment by androw** [comment]
Looks like we can set the password on Android in web GUI but sync failed with generic error

**Comment by mostlyvirtual** [comment]
> We can set the password on Android in web GUI.

This worked well for me as a workaround. No issues thus far.

**Comment by DeflateAwning** [comment]
Just want to bump this issue. Seems like this feature should have been integrated a long time ago.

**Comment by imsodin** [comment]
Please don't bump, it doesn't help, quite the contrary: https://github.com/syncthing/syncthing/wiki/NoPlusOne

Also closing this ticket as a feature request, see https://github.com/syncthing/syncthing-android#no-feature-request-taken-feature-contributions-case-by-case
