### ISSUE TITLE
Syncthing fails to ask for root permissions

### ISSUE THREAD

**Issue by JacobRoth** [syncthing/syncthing-android#1619]
I'm trying to run Syncthing as root in order to properly sync files on an SD card. I have Magisk set up and it works for other apps. But when I tap "Run Syncthing as Superuser" option, I don't get the root allow/deny prompt, I just get the message "Did not get root permissions" followed by "Syncthing was denied Superuser rights". Is it not asking correctly?

### Version Information

    App Version: 1.13.0
    Syncthing Version: 1.13.0
    Android Version: Lineageos 17.1 with MicroG (Android 10)

**Comment by AudriusButkevicius** [comment]
We only support chainfire

**Comment by imsodin** [comment]
Works for me with magisk, exact same setup. We handle support on the forum, please post there to see if we can get this working: https://forum.syncthing.net/

**Comment by tomasz1986** [comment]
> We only support chainfire

I really wouldn't suggest this one. It is completely closed source, and on top of that for at least a few years now also owned by unknown developers.

**Comment by imsodin** [comment]
That's the library we use to handle all thing root within syncthing-android, and it's definitely open source: https://github.com/Chainfire/libsuperuser  

Now lets stop this here and move discussions (if any)/support about root to the forum as requested.
