### ISSUE TITLE
ST Stopped Writing to SD Card 

### ISSUE THREAD

**Issue by r4taw2mg** [syncthing/syncthing-android#1620]
I know, there are numerous discussion about writing to SD all over the place. I have scanned what I could find, but it still does not explain my observations. I recently noticed that ST is reporting my sync folders in /storage/0000-0000/Android/data/com.nutomic,syncthingandroid/files as readonly. This has been working before and one of the earlier syncs even wrote a complete copy to the SD card and now is refusing to be write any updates.

Any help is appreciated as this behaviour puts my complete backup regime at stake.

Not working: ST 1.13.1 with Android 6.01 on a Sony Z3, ST 1.13.1 with Android 10 on a Samsung Tab S6
Working ST 1.13.1 with Android 8.0.0 on a Samsung S7

**Comment by imsodin** [comment]
Issues are meant to track actionable items. Any discussions, questions, ... are handled on https://forum.syncthing.net. The forum has a lot more eyes and friendly people on it than the issue tracker.

**Comment by r4taw2mg** [comment]
Yeah, still this is a behaviour, the app is not expected to show. Am I wrong?

**Comment by imsodin** [comment]
You are not wrong, just at the wrong location: https://forum.syncthing.net
