### ISSUE TITLE
Welcome wizard: Transparent overlay on location-screen

### ISSUE THREAD

**Issue by Jonta** [syncthing/syncthing-android#1626]
- Got to slide 3 on Welcome wizard
- Got: Transparency at the bottom
- Expected: Prettier, non-glitchy-looking. =)

![syncthing-transparent-overlay](https://user-images.githubusercontent.com/359397/112546617-eecfe400-8db9-11eb-8f77-811244306dda.jpg)

### Version Information

    App Version: 1.14.0
    Syncthing Version: v1.14.0
    Android Version: 10
    Android theme: Dark

**Comment by PotatoGod123** [comment]
I'll Work on this! Do you have a way to contact you?

**Comment by Jonta** [comment]
> I'll Work on this! Do you have a way to contact you?

@PotatoGod123 This thread is fine. =)
