### ISSUE TITLE
Feature Request: Copy Paste Text to/from clipboard

### ISSUE THREAD

**Issue by eabase** [syncthing/syncthing-android#1629]
I'm looking for a copy/paste text to to/from remote device. 

Since I was not able to find this functionality in this app or its documentation, I would like to suggest that this very useful feature is added. It seem that the only app able to do this privately across devices is [TexFer](https://play.google.com/store/apps/details?id=com.ebizzapps.texttransferbetweenmobiledesktop&hl=en_US&gl=US). However, that app is requiring to use an unsafe local non-TLS connection and PC based browser.  Therefore I would like to see this copy *clipboard* functionality implemented more consistently across platforms Win/OSX/nix/Andoid/Apple.

**Comment by AudriusButkevicius** [comment]
Sorry, but this is out of scope. The application syncs files, not clipboards.

**Comment by eabase** [comment]
@AudriusButkevicius 
> The application syncs files, not ...

Exactly, and the clipboard is handled like a file in any *nix system, so this feature should be easy and straight forward to implement for anyone of you who are used to this code base. So I simply don't see how you can say this is *"out of scope"*, when it seem to be exactly in the scope of what this tool is supposed to do? Please explain.

**Comment by AudriusButkevicius** [comment]
No it's not. Clipboard is not a file:
https://unix.stackexchange.com/a/255600

Even if it is on your platform, it's not a file on all platforms.

**Comment by eabase** [comment]
You're probably right, but whether or not it's a virtual device or a direct memory pipe, many nixes are using `/dev/clipboard` for access. Regardless, how it's done. It should still be simple manner of being able to paste some text into a box and have it appear as a pop-up box on the other device. 

Anyway, thanks for the info. Just wanted to make this app a little better, by offering a useful and fairly original feature. Looks like I have to stick with the insecure and adware ridden TexFer, as I'm not interested in having to use cloud-based 100+ MB, signup apps like *Evernote*... :(

**Comment by imsodin** [comment]
Go to https://forum.syncthing.net, open a topic explaining your use case and asking for how to do that. If it's about notes, I do remember reading about people having done exactly that with Syncthing. Basically you can do anything with Syncthing, if you embrace that it **synchronizes files**, i.e. you need to represent whatever you need as a file and you are done.
