### ISSUE TITLE
cant detect file changes smaller than 1kbyte

### ISSUE THREAD

**Issue by H3n-beep** [syncthing/syncthing-android#1633]
i dont know the process of recreation of such malfunction. but for me, i tried to sync my keepass data base file but the changes are too small for recognition(?). it cant find small changes to files

**Comment by AudriusButkevicius** [comment]
Databases are not written out like normal files. They are usually memory mapped files that don't fire change notification events.

You can rely on periodic scanning to detect changes like this.
