### ISSUE TITLE
sd card root folder write access MIUI12

### ISSUE THREAD

**Issue by trinity0091** [syncthing/syncthing-android#1634]
All app have write access in sd card root folder Except the sycthing. 

Phone/OS : Poco MIUI 12

in other apps there will be apopup for the write permision page but it is not asking in this app

**Comment by imsodin** [comment]
There's a ton of previous issues, wiki articles and forum topics on the issue of sd card write access. Please search and read them. If you still have questions, support is handled on https://forum.syncthing.net.
