### ISSUE TITLE
Android 11 cannot access Android/data folder & subfolder

### ISSUE THREAD

**Issue by zzjjbb** [syncthing/syncthing-android#1638]
After I select and add `Android/data` folder or its subfolder, a red line appears saying `error (open /storage/emulated/0/Android/data/com.xxx/xxx: permission denied)`

By the way, I heard someone says developers are possible to access these locations in Android 11, but need some circumvention (without root).

### Version Information

    App Version: 1.16.0-rc.1
    Syncthing Version: v1.16.0-rc.1
    Android Version: Android 11

**Comment by imsodin** [comment]
That's a restriction in Android 11: We do still opt out of scoped storage, thus do get the permission to access "all files" on 11. However starting with 11, all files means "all public files". Files in `Android/data/...`, i.e. internal data directories of other apps, is explicitly not allowed.

Only workaround around this is root (or changing the system - vendors/rom devs could in principle do anything).

**Comment by konwin** [comment]
With TotalCommander it is possible to access files in `Android/data/...` without root even in Android 11! Looks like there is a way to access it!

**Comment by AudriusButkevicius** [comment]
Not from Go. Total commander is probably written in Java, which has access to the file system abstraction (which is only available in Java applications, not Go)

**Comment by licaon-kter** [comment]
Can this be tackled?

As more apps move there, eg. Osmand, this makes Syncthing unusable :(

**Comment by imsodin** [comment]
Unfortunately not - Android entirely prevents apps from accessing `Android/data`.

**Comment by licaon-kter** [comment]
As said above, Total Commander can access it just fine, so no, Android does not prevent all apps...just that apps need to adapt to the new storage permissions.

**Comment by imsodin** [comment]
We are using `MANAGE_EXTERNAL_STORAGE`, from https://developer.android.com/training/data-storage/manage-all-files

> Apps that are granted this permission still cannot access the app-specific directories that belong to other apps because these directories appear as subdirectories of Android/data/ on a storage volume.

Also https://developer.android.com/about/versions/11/privacy/storage#other-private-dirs

> Access to data directories on internal storage
> 
> Android 9 (API level 28) started to restrict which apps could make the files in their data directories on internal storage world-accessible to other apps. Apps that target Android 9 or higher cannot make the files in their data directories world-accessible.
> 
> Android 11 expands upon this restriction. If your app targets Android 11, it cannot access the files in any other app's data directory, even if the other app targets Android 8.1 (API level 27) or lower and has made the files in its data directory world-readable.
>
> Access to app-specific directories on external storage
>
> On Android 11, apps can no longer access files in any other app's dedicated, app-specific directory within external storage.

That app has a super-user mode, probably that's why it works. And even if there is indeed a way to somehow access to directories using some Android APIs without root, that is not something syncthing-android can do. It might be doable in principle, but it's definitely not doable because no-one is actively working on it in general, let a alone for major changes like this.

**Comment by licaon-kter** [comment]
> not doable because no-one is actively working on it in general

**This** I understand, just pointing out that this will be needed soon as Syncthing becomes less able. The other posts just say that "it's impossible", which is not true. :(

Total Commander, no root, targetsdk 30
![](https://i.imgur.com/5O04aYC.png)

Simple File Manager, no root (FOSS app fyi), targetsdk 30
![](https://i.imgur.com/8Al2BdS.png)

**Comment by wweich** [comment]
I don't know what `///_Android_data/` is, but Total Commander cannot access `/storage/emulated/0/Android/data/` beside it's own subdir on my Pixel 4a.

**Comment by licaon-kter** [comment]
Above are TotalCommander 3.30b2 and Simple File Manager 6.11.2 (from F-Droid).

**Comment by licaon-kter** [comment]
> e.g. your "app X does Y statements" lack any info on android version

I don't follow, this is a thread about Android 11, and I am using Android 11, sorry if that wasn't clear.

The pictures above are from the current device on Android 11.

**Comment by licaon-kter** [comment]
Ref: https://github.com/SimpleMobileTools/Simple-File-Manager/pull/1202 

Ref:
https://github.com/SimpleMobileTools/Simple-File-Manager/pull/520

**Comment by wweich** [comment]
Total Commander uses an Android API to access a virtual file system, which cannot be done by syncthing, as it is written in go and has no access to Android APIs.

**Comment by prestidigitonium** [comment]
I've a rooted crdroid 7.x on (android 11), I gave privileged access to syncthing and I flagged "run as superuser" option. I also rebooted the smartphone but there is no way to access /storage/emulated/o/Android/data neither with File (stock android file manger nor with the built-in "file explorer" of syncthing. Anyway I can access any privileged path with other file manager having root privileges.
Why can't I access the path even with a privileged syncthing instance?

**Comment by imsodin** [comment]
If you enable the "advanced folder picker" (or similar), you basically get a text field to enter any path you want. Other option is to use the web UI.

**Comment by kid1412621** [comment]
Wonder if there is any update on this? or mark as non-doable at all.

**Comment by udance4ever** [comment]
this is definitely frustrating not to be able to explicitly define/declare what apps "trust" each other with their files.

I noticed the default Files app on my Pixel 6a (Android 12) no longer access Android/data but this shortcut does:

https://play.google.com/store/apps/details?id=com.marc.files

Syncthing is awesome to sync my entire `saves` directory from Batocera Linux and able to map directories in RetroArch, Drastic, and Citra on Android.

No go on Dolphin and Aether though and having to manually copy into `Android/data`
