### ISSUE TITLE
Syncthing binary crashed with error code 2 (V0.5.4, V0.5.2 was OK)

### ISSUE THREAD

**Issue by pluby** [syncthing/syncthing-android#164]
Syncthing binary crashed with error code 2 appears as a notification. It stops working and requires a forced stop.

Raised sepately to #92 relating to 0.4 as this appears to have been introduced between 0.5.2 (which works) to 0.5.4.

Android 4.4.3.

**Comment by Zillode** [comment]
Closing this as many changes happened in this codebase and in upstream, which means it is probably solved;)
