### ISSUE TITLE
apk in release

### ISSUE THREAD

**Issue by Dmole** [syncthing/syncthing-android#1649]
I'd like to accept a bountysource payout but f-droid does not have the latest apk for testing yet.
Please add an apk asset to the releases.

**Comment by imsodin** [comment]
For now you can get the latest release from here: https://build.syncthing.net/buildConfiguration/Syncthing_Release_ReleaseSyncthingAndroid/101688?buildTab=artifacts (there's a button to login as guest). Any release can be obtained from here by selecting the respective build and navigating to artifacts: https://build.syncthing.net/buildConfiguration/Syncthing_Release_ReleaseSyncthingAndroid?branch=&mode=builds&focusLine=0

I'll have to adjust the release CI to create signatures and then remember uploading that when releasing.

**Comment by imsodin** [comment]
The latest RC has an apk artifact

**Comment by Dmole** [comment]
https://github.com/syncthing/syncthing/releases/tag/v1.17.0-rc.3
was "3 days ago", but I'll check again whenever rc.4 is out.

**Comment by AudriusButkevicius** [comment]
You're checking in the wrong place: https://github.com/syncthing/syncthing-android/releases/tag/1.17.0-rc.3

**Comment by Dmole** [comment]
Thanks.
