### ISSUE TITLE
KB or Kb

### ISSUE THREAD

**Issue by justusiv** [syncthing/syncthing-android#165]
Have option to display KB

**Comment by Nutomic** [comment]
Marking this as wontfix, because it's not worth the effort imo.

**Comment by Nutomic** [comment]
On second thought, keeping it open makes sense in case someone wants to implement this.

**Comment by lkwg82** [comment]
This can be closed for the sake of cleanup.  No one else is interested.

**Comment by Nutomic** [comment]
Yeah I guess that's right, and it's not really important.
