### ISSUE TITLE
the program is lying

### ISSUE THREAD

**Issue by babut85** [syncthing/syncthing-android#1651]
App Version: 1.16.0
    Syncthing Version: v1.16.0
    Android Version: Android 10.0 / / ...

the program, refusing to write to an external flash drive, claims that "your android version only grants read only access to the selected folder", but this is a lie, android in its architecture has no restrictions on writing to an external flash drive. the program requests permission(which it does not need in principle) to access a folder on an external flash drive, but nothing changes from getting permission(which is most likely a bug in the program itself). if the author, for some reason, wants users to kill an internal flash drive(with which the program has no problems), then he should have written so, and not put the blame on google.
in confirmation of my words i will say that other programs have no problems with writing to an external flash drive

**Comment by ProactiveServices** [comment]
You've had this question answered on the forum. It's also answered on other bug reports here. Please stop wasting the project's time.
