### ISSUE TITLE
Airplane mode

### ISSUE THREAD

**Issue by God-Asimov** [syncthing/syncthing-android#1652]
Hope to support the ability to connect with local users in airplane mode.  
Because I use multi-user mode, but I can’t search for other saved users under no network conditions.

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
