### ISSUE TITLE
Stuck syncing with filename start with '.' , even in receive only mode

### ISSUE THREAD

**Issue by YueYue2002** [syncthing/syncthing-android#1662]
For example : I set folder `Music` in my phone to `receive only` mode to receive music files from my PC. My music application then create an folder called `.thumb` under `Music`. The `.thumb` folder will keep syncing.

### Version Information

    App Version: 1.16.9
    Syncthing Version: v1.16.0
    Android Version: Android 11 / OxygenOS 11

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
