### ISSUE TITLE
Fails to start on LineageOS 18.1 - River - Moto G7

### ISSUE THREAD

**Issue by checkpoint20** [syncthing/syncthing-android#1665]
Fails on the first start immediately after going through the welcome screen. 

Logs:
[SyncthingFailsToStartOnLineageOs18Logs.txt](https://github.com/syncthing/syncthing-android/files/6635519/SyncthingFailsToStartOnLineageOs18Logs.txt)

Exception in logs:
```
06-10 22:49:23.830 21266 21266 E WindowManager: android.view.WindowLeaked: Activity com.nutomic.syncthingandroid.activities.MainActivity has leaked window DecorView@1d1edc0[MainActivity] that was originally added here
06-10 22:49:23.830 21266 21266 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:736)
06-10 22:49:23.830 21266 21266 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:720)
06-10 22:49:23.830 21266 21266 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:399)
06-10 22:49:23.830 21266 21266 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
06-10 22:49:23.830 21266 21266 E WindowManager: 	at android.app.Dialog.show(Dialog.java:340)
06-10 22:49:23.830 21266 21266 E WindowManager: 	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1007)
06-10 22:49:23.830 21266 21266 E WindowManager: 	at com.nutomic.syncthingandroid.activities.StateDialogActivity.showLoadingDialog(StateDialogActivity.java:170)
06-10 22:49:23.830 21266 21266 E WindowManager: 	at com.nutomic.syncthingandroid.activities.StateDialogActivity.onServiceStateChange(StateDialogActivity.java:83)
06-10 22:49:23.830 21266 21266 E WindowManager: 	at com.nutomic.syncthingandroid.activities.StateDialogActivity.lambda$uNRRb03q4MIgOMMHx
...
```

### Version Information

- App Version: 1.17.0, 1.16.0, 1.15.1
- Syncthing Version: 1.17.0, 1.16.0, 1.15.1
- Android Version: 11
- LineageOS Version: 18.1

**Comment by Catfriend1** [comment]
Hi,

those lines don't look good to me:

> Failed to ensure /mnt/expand/5aa56297-c982-4899-9a64-22fe81c32629/user/0/com.nutomic.syncthingandroid/cache: mkdir failed: ENOENT (No such file or directory)

It says it cannot create shared prefs and other (app specific) required android internals later on. finally the log says "app died".

I'd suggest you reach out to the ROM developer.

**Comment by checkpoint20** [comment]
Interesting. This Moto G7 actually is my daily driver. All applications but Syncthing work fine. It does not look like an issue on the ROM end.

**Comment by imsodin** [comment]
It's not that absolute. In any case, not being able to create a directory in what should be syncthing's internal directory definitely counts as support. As in should be debugged on https://forum.syncthing.net or in this case as Catfriend suggested, maybe even the ROM support venue. Also usually the internal dir is below `/data/data`, your `/mnt/expand/...` prefix looks weird and is one more pointer that this is some ROM peculiarity.
