### ISSUE TITLE
Please document circumstances in which other apps can access Syncthing data (& support app-private storage)

### ISSUE THREAD

**Issue by jgoerzen** [syncthing/syncthing-android#1668]
I want to use Syncthing to sync some sensitive data.  Since it uses the storage area on my Pixel 4a (which does not have an SD slot), it is unclear to me when other apps can have access to it.  (I am on Android 11).

It would be fantastic to have documentation around this, as it seems to be a very complicated topic, varying between Android versions.

The fundamental question is: can I prevent other apps from accessing my Syncthing data without my explicit consent?  I'm unsure, even on Android 11, about the potential for legacy apps to do this, or even Android 11 apps.

Thanks!

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
