### ISSUE TITLE
Syncthing is disabled - 2nd update and no go.

### ISSUE THREAD

**Issue by Mr-Ek** [syncthing/syncthing-android#1671]
Hi all,
On my note Samsung Note 20, two updates ago syncthing worked perfectly and I was verily happy. Then at some stage an update occured and it no longer runs - well does anything useful. I get the following message on the bootup:

"Syncthing is disabled
Do you want to change the run conditions?
Reasons:
Not connected to WiFi
(A Config file crucial to operation is missing)"

So when I go to change settings, The only checked box is "Run of WiFi".
When I select "Run on moblie data" it starts to perform but I want it to run only on wifi for obvious reasons.
I have trauled the Net for  quite some time and no help so asking here. Any info would be muchly appreciated.
Oh and "Run on specified Wi-Fi networks" reports "run on all networks". When I select this to change, I'm told to "connect to a Wi-Fi to add it to the list".
Thanks again.

### Version Information

    App Version: 1.17.0
    Syncthing Version: ?? Won't say
    Android Version: Android 11

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
