### ISSUE TITLE
Encryption password is overwritten for any change to any folder using the Android UI

### ISSUE THREAD

**Issue by sashee** [syncthing/syncthing-android#1673]
I noticed constant crashes when I use encrypted (untrusted) folders. When I set up a folder, I use the Web UI to set the password. But later I found that the password was empty.

This crashes Syncthing and I see an error on the other end:

```
... Failure checking encryption consistency with device ... for folder ...: remote expects to exchange plain data, but is configured to be encrypted
```

Seems like if I use the Android UI (not the Web UI), open a folder than make any change to any folder, it clears the password for all folders.

Steps to reproduce:

- Open the Web UI and add a folder (Test), share it with a device and set a password
- Go back to the Android UI, open any folder and make any change (for the test I opened a different folder (Folder2) and unshared it)
- Back on the Web UI, the original folder (Test) is still shared with the device but with no password

### Version Information

    App Version: 1.18.0
    Syncthing Version: v1.18.0
    Android Version: Android 10

**Comment by AudriusButkevicius** [comment]
This is the same as: 

https://github.com/syncthing/syncthing-android/issues/1650

Effectively, Android does not support encrypted folders.

**Comment by imsodin** [comment]
Or more like the same as https://github.com/syncthing/syncthing-android/issues/1648: The app could make sure to not erase the encryption password without actually supporting to set the password.

The wrapper operates on the entire config and mirrors that in java classes. So one has to keep them up-to-date with config changes in Syncthing, and they aren't up-to-date. The better change would be to switch to only querying and setting (patching) the config elements the wrapper actually cares about. Thus it stays correct even if something changes in Syncthing.

**Comment by sashee** [comment]
Well, "unsupported" in my mind means that it does not provide a way to set it up, and not "change something totally unrelated for a different folder and now the app is in a crash loop".

At least preventing any modification on the Android UI (saying something like "your setup is using something unsupported, so please use the Web UI until it's supported) would be a great help in this case. For now anyone who uses untrusted folders need to be *very* aware not to accidentally touch the folders on the Android UI as that throws Syncthing into an endless crash cycle.
