### ISSUE TITLE
Treat (explicitly set) unmetered wi-fi connections as wi-fi

### ISSUE THREAD

**Issue by cobratbq** [syncthing/syncthing-android#1675]
Issue #409 teaches Syncthing to not perform full-speed synchronization on metered connections. However, it is possible to explicitly set a wi-fi connection to __unmetered__. This should be a sign for Syncthing to use full network speed, but it still syncs with low speeds around 150 kB/s.

### Version Information

    Syncthing on android 1.18.0
    Syncthing v1.18.0
    Android 10 + 11 (tested on 2 devices)

**Comment by AudriusButkevicius** [comment]
I don't think we adjust speed on the network type. We decide whether to run or not based on network type.

**Comment by cobratbq** [comment]
> I don't think we adjust speed on the network type. We decide whether to run or not based on network type.

I believe the referred issue (#409) shows how we do limit syncing for wifi networks classified as "metered".

**Comment by imsodin** [comment]
That's an all or nothing switch: The wrapper either runs Syncthing on metered wifis, or not at all - there's not speed limiting in the android wrapper.
