### ISSUE TITLE
Error: Folder Marker Missing on /storage/extSdCard/ repositories

### ISSUE THREAD

**Issue by zombielinux** [syncthing/syncthing-android#168]
I've got an error with two previously working repositories on the extSdCard. The error reads "Folder Marker Missing".The paths haven't changed. The permissions to said paths haven't changed. Deleting and readding doesn't help. No settings have changed. 

I am running v0.10.2 with the latest Play Store version. My phone is a Galaxy S5 running 4.4.2

Anyone else have the same issue?

**Comment by tristan-k** [comment]
There is an xposed module for that: http://repo.xposed.info/module/de.defim.apk.handleexternalstorage Installed it but the issue remains.
