### ISSUE TITLE
Feature request: Remote online device file browser build in Syncthing

### ISSUE THREAD

**Issue by eteropczyk** [syncthing/syncthing-android#1686]
Hi devs, 
great app. I just want to add my thoughts.

I am using Syncthing as prived cloud backup solution. It is great. I set my mobile devices to send gallery to windows based NAS and sync with other places too. It would also be great if there would be a nice way to view photos from remote device in Syncthing (something like simple file explored with grid, sorting and picture tumbnails generator). 

I have found neat solution using SFTP server on NAS and CX File Explorer app (great gallery functions, super fast!), but it would be superb addon for syncthing to browse other online devices files instead.

Cheers
Piotr

**Comment by AudriusButkevicius** [comment]
This will not happen.

Syncthing is a generic file sync application, it does not care about file types, and even if it did have a file manager (which is very unlikely), I don't think start rendering thumbnails of things.

I think you should assume it's closer to being a continuous `rsync` oppose to something like Dropbox, which allows you do to file management.
