### ISSUE TITLE
Syncthing terminates in MIUI 12 (even with no restrictions and autostart enabled)

### ISSUE THREAD

**Issue by Lumenbolt** [syncthing/syncthing-android#1690]
I am currently using Xiaomi Poco X3 Pro with the MIUI 12.5.3 (For POCO) running Android 11. Despite of setting no restrictions on Syncthing on its built-in battery saver and allowing to run in background, Syncthing stops running whenever I clear out (optimize) the RAM.

I understand this is neither an issue pertaining to the android app nor can the developers do anything about it (rather an issue with vendor's software), but is there any way I can keep Syncthing running on background even if I clear/optimize my memory?

If anyone uses MIUI and had found a fix/workaround to keep Syncthing running as long as the phone is on, please help sharing it.

**Comment by AudriusButkevicius** [comment]
I'm closing this as there is nothing we can do. If you have questions, forum is the place. Potentially the MUI ones, as its not really related to syncthing.
