### ISSUE TITLE
pdf modification doesn't synced from android to win10

### ISSUE THREAD

**Issue by playdougher** [syncthing/syncthing-android#1692]
What happened: 
when I add notes on PDF of android device, the modification won't sync automatically until I click "rescan" button. While the modification on win10 will sync normally.

What you expected to happen instead:
sync PDF files after adding notes on android

Steps to reproduce the problem:
s1. Add notes on a PDF file and save it
s2. Wait for one or two minutes, find nothing synced on win10
s3. Click "Rescan" on android syncthing website
s4. Find notes of PDF are synced

### Version Information

![02f475389429fe007f80513927aaee1](https://user-images.githubusercontent.com/26463515/132136603-d2f28a33-233b-4f14-bc85-b10b5fc3ee2a.jpg)

![529d232529ecb4f8b299130318a8ac6](https://user-images.githubusercontent.com/26463515/132136615-40a4b145-3622-481d-bf72-c1b638b22d85.jpg)

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
