### ISSUE TITLE
Syncthing cannot sync files with names like 2021-09-12_12:02:25 of any extension

### ISSUE THREAD

**Issue by simplepad** [syncthing/syncthing-android#1693]
### What happened
I tried to sync a file named 2021-09-12_12:02:25.png from pc (arch linux) to android and it was stuck at "Syncing", no files were created on the phone. This behaviour repeates with any extension and file size, provided the name is "2021-09-12_12:02:25".

### Steps to reproduce:
    1) Establish a sync between a pc and an android phone
    2) Add folder on both ends with type Send&Receive
    3) On the pc, create a file named "2021-09-12_12:02:25.png" in the syncing folder
    4) Folder will sync all files but the one created in step 3, constantly showing "Syncing" status.

### Version Information

    PC App Version: 1.18.1
    Android App Version: 1.18.2
    Android Version: Android 11

![syncthing_pc](https://user-images.githubusercontent.com/35456194/132983494-6858455b-06ec-444e-a970-48a97abcba76.png)
![syncthing_phone](https://user-images.githubusercontent.com/35456194/132983499-37022f11-8a57-46fd-837f-f281e6111e99.jpg)

**Comment by AudriusButkevicius** [comment]
Android/windows filesystems do not support filenames with colons, not something we can fix.

**Comment by rasa** [comment]
We allow filenames with colons on Android/Windows in https://github.com/syncthing/syncthing/pull/7876.
