### ISSUE TITLE
"Syncthing is disabled: Not connected to wifi" - I AM!

### ISSUE THREAD

**Issue by rmst** [syncthing/syncthing-android#1694]
Same problem as in https://github.com/syncthing/syncthing-android/issues/1280 remains for me. Would have reopened the issue but it's locked. The problem seems to go away when I disable Netguard VPN even though Syncthing is whitelisted and sometimes works even with Netguard activated

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by AudriusButkevicius** [comment]
Also see: https://github.com/syncthing/syncthing-android/issues/1568
