### ISSUE TITLE
feature request: Only disable Syncthing when Battery power and not connected to Wi-Fi

### ISSUE THREAD

**Issue by ivysrono** [syncthing/syncthing-android#1698]
I'd like to enable sync when
- Wi-Fi + AC
- Wi-Fi + Battery power
- no Wi-Fi + AC

Only disable sync when
- no Wi-Fi + Battery power

### Version Information

    App Version: 1.18.2
    Syncthing Version: v1.18.2
    Android Version: Android 11.0

**Comment by AudriusButkevicius** [comment]
We support controlling the application over tasker, so I think more advanced configurations should use that, as we will not be able to support more complicated usecases.

**Comment by ivysrono** [comment]
Tasker is not FOSS.

**Comment by imsodin** [comment]
There's easer: https://f-droid.org/en/packages/ryey.easer/

And that doesn't change the point that it's both quickly getting too clunky when adding settings for every imaginable scenario/combination, and there's also no-one actively working on features on this app.

**Comment by ivysrono** [comment]
Ok, I'll try it.
