### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [syncthing/syncthing-android#1707]
```
image/color
image
github.com/vitrun/qart/qr
golang.org/x/crypto/blowfish
golang.org/x/crypto/bcrypt
golang.org/x/text/runes
internal/profile
os/signal
exit status 2
exit status 1
Traceback (most recent call last):
  File "./build-syncthing.py", line 102, in <module>
    env=environ, cwd=syncthing_dir)
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'run', 'build.go', '-goos', 'android', '-goarch', 'arm', '-cc', '/opt/android-sdk/ndk/23.0.7599858/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang', '-pkgdir', '/home/vagrant/build/com.nutomic.syncthingandroid/syncthing/gobuild/go-packages/arm', '-no-upgrade', 'build']' returned non-zero exit status 1
> Task :syncthing:buildNative FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':syncthing:buildNative'.
> Process 'command 'python'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 32s
```

Could you please take a look? Thanks!

**Comment by linsui** [comment]
It should not be that reason. https://github.com/Catfriend1/syncthing-android-fdroid builds fine.

**Comment by imsodin** [comment]
They don't use docker, they build on something based on debian. According to their metadata they also use ndk r23 and go 1.17.2, so that looks good. I just ran the build process myself not in docker, as I am on debian, and it worked for me.

**Comment by Catfriend1** [comment]
It seems to select the wrong compiler on some systems, I assume this depends on the presence of packages (gcc?).  My fix was to modify the "clang" file to point to the right compiler (part of the ndk). See https://forum.syncthing.net/t/android-ndk-r23-build-problem/17319/40?u=catfriend1

**Comment by Catfriend1** [comment]
@AudriusButkevicius Honestly this should be fixed by the NDK devs.

**Comment by linsui** [comment]
The full log is in https://monitor.f-droid.org/builds/log/com.nutomic.syncthingandroid/4286#site-footer.

**Comment by licaon-kter** [comment]
This can be closed?

**Comment by linsui** [comment]
Yes, thanks!

**Comment by imsodin** [comment]
For the record: Looks like the work-around on F-Droids side was to build with ndk 21e (not 23): https://gitlab.com/fdroid/fdroiddata/-/commit/fa71329048810f38c30bb677544c30df7e3e40e2

**Comment by linsui** [comment]
It was a bug in fdroidserver that the ndk is unziped incorrectly. But finally I found that ndk r23 is not required...
