### ISSUE TITLE
browse all the files and selectively download if needed

### ISSUE THREAD

**Issue by tapionx** [syncthing/syncthing-android#1708]
I was a happy user of syncthing lite, but not it's not working anymore.
Is there any way to accomplish the same thing with the official Syncthing Android app?
My use case is to browse the file of my home folder when I'm not at home, and selectively download only the file that I need on the phone.
I cannot / don't want to download my entire home folder to my phone, it's too big and running Syncthing in background would waste power (given my use case, the sync can happen only when I open the app).
I can't code android app, but I'm open to help with raising money to found the development of such feature (or updating syncthing-lite).

**Comment by AudriusButkevicius** [comment]
Syncthing is sync software, it tries to make two folders the same, it's not a remote file access application. Perhaps nextcloud would work better for you.

**Comment by jpmorris** [comment]
By that logic you all  should probably remove any wifi-only or .stignore capabilities.  The whole goal of this project is to get two folders the same, damn the other considerations (cost .git folder conflicts or fewer SPACE, bandwidth, cpu resources).
