### ISSUE TITLE
syncthing binary crashes every time wifi turns off

### ISSUE THREAD

**Issue by ovizii** [syncthing/syncthing-android#171]
In my android wifi settings I had set this option: 
Settings => WiFi => Advanced => Keep WiFi on during sleep => "only when plugged in"
so every time my phone went into sleep it turned off wifi and syncthing binary crashed.

I have now set it to "Always" and haven't seen anymore crashes - just wanted to report this as it seems reproducible on my phone. Wasn't sure how to send feedback without opening an issue though :-/

P.S. Syncthign is set to run in the background but only sync on wifi!

**Comment by Nutomic** [comment]
Does this still occur to anyone?

**Comment by ovizii** [comment]
nope. all perfectly fine now!

**Comment by Nutomic** [comment]
:)

**Comment by ovizii** [comment]
Not sure I should have closed it, just realized quite a few other people had the same issue. Lets see what the feedback is.

**Comment by StrikerTwo** [comment]
Fine here.
