### ISSUE TITLE
Can't connect to relay on Android 6

### ISSUE THREAD

**Issue by Ratio2** [syncthing/syncthing-android#1728]
Some listening addresses could not be enabled to accept connections:

dynamic+https://relays.syncthing.net/endpoint: Get "https://relays.syncthing.net/endpoint": x509: certificate has expired or is not yet valid: current time 2021-11-15T09:06:48+03:00 is after 2021-09-30T14:01:15Z

Android 6.0.1
Google nexus 5
Syncthing 1.18.3

Some research:
1. "after 2021-09-30T14:01:15Z" - looks like "DST Root CA X3" certificate used
2. I disable "DST Root CA X3" and install "ISRG Root X1" and "Let’s Encrypt R3" - no luck, looks like software use internal bundled certificates

**Comment by AudriusButkevicius** [comment]
The certificate is valid according to la few machines checked. The issue will be on your device, I don't think there is anything for us to fix, hence closing.


If you need support, please use the forum.

**Comment by wweich** [comment]
Android 7.1 is the oldest Android Version which trusts Let's Encrypt's own Root Cert.
