### ISSUE TITLE
Simplify integration with Synching by third-party apps

### ISSUE THREAD

**Issue by rouanth** [syncthing/syncthing-android#1732]
Hi!

First of all, thank you for this great project.

I encountered the need, and, if `syncthing` becomes the next big thing, I'm sure others will as well, to integrate `syncthing` with an Android application. The application stores its state privately, but should still allow sharing it with other devices. Usually, for this case, Dropbox is used, and they make it easy to integrate with them by providing a handy simple SDK: https://github.com/dropbox/dropbox-sdk-java/tree/master/examples/android

My huge request:
* If I understand the technical details correctly, there is no shared identity at all in Syncthing, only devices and hierarchies of synchronization rules between them. However, on a single device, probably a single identity is enough: configuring synchronization between applications on a single device is pretty cumbersome.
* Provide a simple SDK for other people to use if they want their applications to support Syncthing *at least if the Syncthing application is running* (so the other apps don't have to deal with synchronization).
* Implement some permission system so that the applications using the SDK are not given blanket permissions to access arbitrary sensitive files.
* With this change, it would make sense to synchronize some directories in the non-shared app storage. Currently, it is the case that every app with the filesystem permissions can read anything from Syncthing, right? I kind of see why this is so, since the only thing that Syncthing itself can do with the files is to, maybe, copy them into the clipboard buffer, and implementing a text editor/image viewer/etc. for a protected part of the filesystem is out of scope of this project, and there is no granular configuration of app permissions for specific directories on Android. However, if, say, a password manager or a text editor implements Syncthing integration, maybe there is some secure channel of communication between Android applications that could be utilized?

**Comment by AudriusButkevicius** [comment]
Syncthing is an application that syncs users files (albeit quite poorly on Android).
I don't think we are interested in going in some sort SDK route for other applications to piggy back on.

**Comment by imsodin** [comment]
Though of course there's nothing stopping anyone to continue the java implementation of the BEP (https://github.com/syncthing/syncthing-java) and building such an SDK. Or use the rest api to leverage Syncthing for such purposes: https://docs.syncthing.net/dev/rest.html (probably not advisable, due to the android oddities).

**Comment by rouanth** [comment]
> Syncthing is an application that syncs users files

Yes, and some of these files are sensitive. You certainly recognize this, given how you advertise privacy as the first distinguishing feature of this project. However, this is moot if the thread model includes other programs. While there is not much one can do on the desktop, on the phones, there's sandboxing, which you can leverage to improve privacy by only allowing specific applications to access specific data.

> for other applications to piggy back on.

More like "to enable other applications to share sensitive information securely".

> to continue the java implementation of the BEP (https://github.com/syncthing/syncthing-java) and building such an SDK

Does one really need to continue that implementation, is it not enough to wrap the Go library, as is done in this project? Sorry, I'm not knowledgeable in the inner workings of Syncthing.

> Or use the rest api to leverage Syncthing for such purposes: https://docs.syncthing.net/dev/rest.html (probably not advisable, due to the android oddities).

Could you please elaborate on this? Which oddities do you mean?

In any case, my proposal goes beyond what can be done without collaboration from the main Android implementation: see the points about having a per-device identity and improving the privacy of the Syncthing Android client itself.

**Comment by rouanth** [comment]
@AudriusButkevicius @imsodin ping

**Comment by imsodin** [comment]
Please use the forum for general questions on/related to syncthing: https://forum.syncthing.net
