### ISSUE TITLE
Stuck at starting

### ISSUE THREAD

**Issue by github-account1111** [syncthing/syncthing-android#1735]
When I open Syncthing it loads for a while, then a popup appears saying "Syncthing is taking too long to load. Check log to see errors." The log is empty.

Sometimes I get "App is not responding. Wait/Close." Waiting does nothing.

There's also a notification saying "Syncthing is starting."

    App Version: 1.18.3
    Syncthing Version: v1.18.3
    Android Version: Android 12

PS battery optimization is off.

PPS clearing cache does nothing.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by codethief** [comment]
@github-account1111 Have you had any luck resolving this? I've been having this issue for a while now (sporadically, not always).

**Comment by imsodin** [comment]
As Audrius latest comments explained, please use https://forum.syncthing.net/  for support.
