### ISSUE TITLE
Clean sync no longer works and stops at 99%, some files are always out-of-sync

### ISSUE THREAD

**Issue by codethief** [syncthing/syncthing-android#1738]
I have been using Syncthing for years across multiple phones and laptops. I've run into a quirk or two at times but never into anything that could not be fixed by restarting Syncthing or rebooting. This time, however, it's different:

### Preface
I generally only ever use one laptop and one phone on a day-to-day basis. I have various old devices (multiple old laptops, phones and tablets) which I only use rarely if ever (they basically serve as backup in case of a hardware failure). My current laptop more or less serves as the single source of truth when it comes to my documents & files – meaning that it always has a copy of *all* my files –, while my phone generally only receives a selected subset of folders & files due to size constraints. 

The way I set up a new device (a new phone, a new laptop) has always been the following: I use Syncthing to transfer all relevant files to the new device and make sure all files got transferred properly; then I stop using the old device and rarely (if ever) turn it on again.

### The bug
I recently got a new phone (a Pixel 5) and had my other devices (my old phone, my laptop) share their folders with it. None of these folders had existed on the new phone yet, so it should have been one huge clean sync of ~70 GiB.

After a few hours, I looked at the new phone: For pretty much every folder, syncing had stopped at 99% and the UI said "out of sync". In the web UI it would also list the names of (only) a handful of files that were out-of-sync. Meanwhile, on my laptop, Syncthing's web UI would list also the same files as "out-of-sync items" for my new phone and, in addition, it also said that my old phone was the "modifying device".

Here's the thing, though: Both on my old phone and my laptop (and also on my old laptop), the files in question are present and identical. Indeed, my laptop's Syncthing instance also says that all folders (on my laptop) are up-to-date, confirming that it is indeed the "single source of truth" mentioned earlier. In short, there is no reason for Syncthing not to sync them to my new phone. Yet, they are not present on my new phone.

### Further investigation
I have since repeated this process multiple times: Every single time, in every folder some (seemingly?) random files don't get transferred to my new phone. I have tried the whole sync process with my old phone not known to my new phone (i.e. my new phone only knew about my laptop) and, another time, also with my new phone knowing and being connected to both my laptop and my old phone. The result in both cases was the same.

Actually, now that I've investigated this further, for my *old* phone my laptop is now also showing 8 items in one particular folder (out of a dozen folders) as being "out of sync" and, indeed, those file are not present on my old phone, either. I'm not sure how long this has been the case but I don't think it's been like this for a long time. In any case, my laptop's crucially listing one of my old laptops as the "modifying device" with all modifications (except one) being precisely 128B in size. But, as I already said, all my folders on my (new) laptop are shown as "up to date", so any modification my old laptop might have introduced should be present on my new laptop, as well. Unfortunately, I can't verify this right now because my old laptop is a couple thousand km away but suffice it to say, the files in question are files I haven't touched in 5-10 years, so it's downright impossible my old laptop might have introduced a change, let alone in recent times and let alone with a delta of precisely 128B in every case. (I also looked at the files on my new laptop – mostly PDFs – and they all seem fine.)

Any help would be very much appreciated! I'm starting to become desperate and to doubt in how far I can still trust Syncthing.

### Misc

Not sure if it's of any relevance but I've noticed a second marker folder `.stfolder (1)` with a file `DO_NOT_DELETE.txt` show up in the relevant (out-of-sync) folders. (Meanwhile, `.stfolder` is also present but empty.)

### Version Information

New phone (Google Pixel 5):

    Syncthing Version: v1.18.4
    Android Version: Android 12 / GrapheneOS (SPA1A.211105.004)

Laptop:

    OS: Ubuntu 21.04
    Syncthing Version:  v1.18.4

Old phone:

    Syncthing Version: v1.18.4
    Android Version: Android 9 / LineageOS

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by codethief** [comment]
Thanks for the fast response, @AudriusButkevicius! To be honest, to me it feels very much like a bug. It's faulty behavior and it's reproducible (on my end, with my files). As mentioned I'm not exactly a Syncthing novice and have been using it for years without any issues. The only reason this might not be a full bug report yet is that I have a hard time figuring out what exactly one would need to do reproduce the issue from scratch. So I'd appreciate any help to turn this into a full bug report!

**Comment by AudriusButkevicius** [comment]
Yes, something is not right, yet its not clear what it is, and what needs fixing. Until we know precisely what needs fixing, this should be on the forums, as I don't want to have open ended github issues that potentially can never be closed.

**Comment by codethief** [comment]
I have created a thread in the forum: https://forum.syncthing.net/t/clean-sync-to-new-device-does-not-work-and-stops-at-99/17698

**Comment by kamysheblid** [comment]
Hi, I had the same problem with 28 files. It turns out that every single file that was not syncing had a colon (:) in the name of the file. I am not familiar enough with Java to fix this, but it has to do with the filenames.

This is 100% a bug and the issue should be reopened.
