### ISSUE TITLE
unnedded access to /Android/data lead to access denied warning

### ISSUE THREAD

**Issue by jkumeboshi** [syncthing/syncthing-android#1742]
I've set the sync path to the root, with an exclude path as follow:

```
!/Android/media
!/DCIM
!/Documents
*
```
the `/Android/media` is accessible and is correctly synced.
But I get a warning since syncthing tries to set a filesystem watcher also in /Android/media, that is being excluded.

![IMG_20211129_213347](https://user-images.githubusercontent.com/25344258/143939390-5cdf6699-3c71-45fa-a4b5-64ba1cb615a7.jpg)

**Comment by imsodin** [comment]
Yes, this is a know limitation in Syncthing's ignore mechanism: Watches must be set up for all paths if there is include patterns (starting with `!`), even if they are ignored.
