### ISSUE TITLE
Having colons in a file/folder name causes 'operation not permitted'

### ISSUE THREAD

**Issue by compu42** [syncthing/syncthing-android#1743]
What happened:
Files with a : causes them to not sync. The error reads 'operation not permitted'

What was expected:
The colons should be replaced with an underscore in the file name so that the filesystem plays nice. i.e. `title: subtitle.odt` to `title_ subtitle.odt`

How to reproduce:
Attempt to sync a file with a colon in the filename to the device.

Additional Notes:
There might be some extra characters that have this problem, I haven't been able to find others.
### Version Information

    App Version: 1.18.3 - F-Droid
    Syncthing Version: v1.18.3, android (64-bit ARM)
    Android Version: Android 11 / LineageOS 18.1

**Comment by imsodin** [comment]
This won't happen, too many problems. E.g. what if a file with an underscore actually exists? And before you answer, search the forum please. This has been discussed at length. Just rename your file to something that is supported.

**Comment by rasa** [comment]
Possible solution in https://github.com/syncthing/syncthing/pull/7876
