### ISSUE TITLE
[feature request] sync only when screen is up to avoid battery draining

### ISSUE THREAD

**Issue by eoli3n** [syncthing/syncthing-android#1747]
It would be great to be able to let syncthing sync only when screen is unlocked.

I see two ways of doing this:

- ability to enable android background restriction for SyncThing app.
  For now, SyncThing limits this.
  Not sure if it will work as I want, or if it will completely disable syncthing if the app isn't open in foreground.

<img src="https://user-images.githubusercontent.com/14223657/147550998-b5438f79-b424-4c00-9a11-4dd89a4277f4.png" width="400" />

- add a new syncthing run condition

Is that possible ?

**Comment by imsodin** [comment]
It might be possible, but as many other requests like this it will lead to a near-infinite amount of options to control when the app runs. That's gets out of hand and is not something we want. As you wrote on IRC/matrix/whatever it is, there are apps to automate conditions like this:

> ok, so to let you know guys, I found an app "easer" -> https://f-droid.org/en/packages/ryey.easer/
> with this, i can toggle android data sync based on screen lock events
> when screen is locked -> disable sync, when screen is unlocked -> enable sync
> it works pretty well

**Comment by eoli3n** [comment]
That's what I used -> https://eoli3n.eu.org/2021/12/29/syncthing-battery-draining.html
But it would be great to manage this, in the app directly...

**Comment by tomasz1986** [comment]
> ok, so to let you know guys, I found an app "easer" -> [f-droid.org/en/packages/ryey.easer](https://f-droid.org/en/packages/ryey.easer/)

While having a million of options is not a good thing, I personally wouldn't recommend Easer. The app so complicated that there is no way a non-power user is going to figure out how to set conditions and tasks up. The design is also very clunky and doesn't support DPI and/or font scaling. I've personally given it a try quite a few times, but always eventually gave up due to the overall complexity. Sadly, there doesn't seem to be any other open source solution allowing for similar automation yet.

**Comment by imsodin** [comment]
This wasn't meant to be a discussion of the merits of easer. The point is that power users have options. For non-power users there are the runtime options the app has, and I don't want to make it more convoluted by having more options. Plus the app is in maintenance mode, i.e. only bug-fixes and any improvements I care about/find time for, which is close to 0. If anyone wants to co-maintain, we can discuss design choices like this again. Until then it's more honest and helpful to close issues to make it clear they won't be addressed.

**Comment by eoli3n** [comment]
Using third party app to make another one usable is not a good solution.
I don't trust Syncthing-fork, or Easer as much as I trust Syncthing.

Syncthing is a battery eater, and it should be consider as an issue.
That unique feature would benefit a lot to all users than the energy spent to implement it. ([see](https://duckduckgo.com/?q=syncthing+battery+draining&t=newext&atb=v273-1&ia=web))

**Comment by imsodin** [comment]
There's also plenty of reports of users without any battery drain. If you are interested in getting to the bottom of your issue (battery usage), please open a topic on https://forum.syncthing.net to debug why syncthing-android is using so much energy on your phone.

That isn't related to this feature/issue though. I am locking this issue, please move any discussions/debugging to the forum.
