### ISSUE TITLE
manual language selection

### ISSUE THREAD

**Issue by Ingegneus** [syncthing/syncthing-android#1750]
i am new here so sorry if this is not the right place for this. i can't find an option to manually select the app language. i think is is very needed. if this already exists can someone point me to the right place to look for?
thanks

**Comment by imsodin** [comment]
There is no such option and none is planned to be added.

**Comment by tomasz1986** [comment]
Recently, while translating the app, I've encountered these strings in Transifex.

![image](https://user-images.githubusercontent.com/5626656/151627107-a610edd1-e442-4851-8ebe-fc042be4f334.png)

These translations come from ~4 years ago. Was such an option present in the app at that time? Or, was it just planned but never implemented?
