### ISSUE TITLE
Syncthing process keeps running even after uninstalling the app

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing-android#1751]
Steps to reproduce:

1. Install and start the app.
2. Change the GUI address to `0.0.0.0` to allow remote access.
3. Open the Web GUI remotely on a different device.
4. Uninstall the app on the Android device.
5. The Web GUI remains accessible and functional.
6. `libsyncthing.so` also remains running in background.

### Version Information

    App Version: 1.18.3
    Syncthing Version: v1.18.3
    Android Version: Android 4.4

**Comment by imsodin** [comment]
Is this a problem? I mean sure, I'd expect it to stop too on uninstall. However it's a slight annoyance until next restart, I'd doubt the value of tracking this on an active project, and even more so on one like this with more or less maintenance only. If you feel this should be kept open/tracked, please explain why.

And generally I don't think it's worth tracking any issues that are not reproducible on a recent-ish android (or very problematic).

**Comment by tomasz1986** [comment]
I haven't had time to check on a different Android version, but I've got a feeling the behaviour's got nothing to do with this particular one. I think this is a big problem, because this means the app won't work after reinstalling (because the port `8384` will be taken, and it's hard-coded in the app). There will be no explanation why it's not working, and the user will think it's just broken.

Android devices nowadays almost universally use non-removable batteries, which means that most of them are very rarely rebooted (unless there's an update or something).

**Comment by imsodin** [comment]
Yeah right. There's much more pointless tickets being open on this project. I'll need to go through the issues and mark those that are relevant (purely subjectively) with a tag or something to keep track.

**Comment by tomasz1986** [comment]
I'm closing this one, as I can't see the behaviour in Android 11, so it may indeed be limited to either older versions of Android or simply to my device. There haven't been more similar reports though, so the issue isn't probably widespread anyway. It can be always re-opened if someone experience the same type of problem later on.
