### ISSUE TITLE
Syncthing silently stops working after network switch

### ISSUE THREAD

**Issue by Almtesh** [syncthing/syncthing-android#1763]
### Context Information
```plain
App Version: 1.19.0
Syncthing Version: v1.19.0.3
Source: F-droid official repository
Android Version: Android 10, official OS
Hardware: Fairphone 3+, no SD, one SIM
```
### Problem description

When my phone disconnects from or connects to a Wifi network, it can happen quite often that Syncting crashes silently. It restarts on its own in minutes, but the time can reach quite often several hours.  
The problem seems to be there since 2nd of February 2022. I update all applications from F-droid once a update is available.

### Current workaroud

In order to keep it working as much as possible, I activated the notification when Syncthing crashes and when I get it, I open Syncthing to check if it's working and restart it if not.  
The log displayed after the crash can be empty or just display that the device has been disconnected from another peer. I don't have any saved log, but I will save them one it happens again and put them here.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by Almtesh** [comment]
Actually, I tested it in Syncthing-fork and Termux, that's the same. That's not actually a bug from this app, but from syncthing. That's why I openned #1765.
