### ISSUE TITLE
Allow syncing some directories via Mobile Data

### ISSUE THREAD

**Issue by mic-e** [syncthing/syncthing-android#1764]
Some of my syncthing directories are large and should only be synced when connected to an unmetered Wifi (e.g.: Photos).
Others are low-bandwidth and should be synced always (e.g.: Orgzly TODOs).

It would be nice to have fine-grained control over for which directories Syncthing runs.

**Comment by AudriusButkevicius** [comment]
Dupe of #511 

Please search before opening new issues.
