### ISSUE TITLE
App gets stuck to Upgrade Information screen after update to `1.19.0.3`

### ISSUE THREAD

**Issue by crash-g** [syncthing/syncthing-android#1767]
After upgrading to `1.19.0.3` I am presented with this screen:

![screen3](https://user-images.githubusercontent.com/14766854/156450296-19c4fa36-2bee-45dd-8e3b-ebacf04b6e19.jpg)

and if I try to click on **FINISH** I get this error

![screen4](https://user-images.githubusercontent.com/14766854/156450508-db558643-1909-440b-b1bd-0f195f3aef2f.jpg)

However, I **cannot find the button to reset the database**. Trying to scroll or click around does not help, nothing happens.

Could the issue be related to the Android version I'm using, which is very old? 

### Version Information

    App Version: 1.19.0.3
    Syncthing Version: v1.19.0
    Android Version: Android 5.1.1

**Comment by imsodin** [comment]
Yeah, that's poorly done: The button is at the button, you need to scroll (swipe?) down to get to it.

**Comment by crash-g** [comment]
Thanks @imsodin for the quick answer. However, as I mentioned, swiping does not work: it looks like the screen is frozen, I can only click the BACK or the FINISH button.

**Comment by tomasz1986** [comment]
Something seems up with the phone. It's probably not the Android version (as I had this working on Android 4.x). I'd suggest trying to connect a wireless or Bluetooth mouse or keyboard and then try to scroll the screen (or alternatively use a remote desktop type of software to connect to the phone and operate on it remotely).

If the above tips don't work, then please open a topic on the forum where we can further investigate into the issue.

**Comment by crash-g** [comment]
I've found a different workaround: changing to landscape mode for some reason enabled me to scroll down and find the reset database button.

Thanks anyway @tomasz1986 and @imsodin for your suggestions
