### ISSUE TITLE
a strange speed problem

### ISSUE THREAD

**Issue by luckyfatpig** [syncthing/syncthing-android#1776]
Do not report security issues in this bug tracker. Instead, contact security@syncthing.net directly - see https://syncthing.net/security.html for more information.

If your issue is a support request ("How do I get my devices to connect?" or similar), please use the support forum at https://forum.syncthing.net/ where a large number of helpful people hang out. This issue tracker is for reporting bugs or feature requests directly to the developers.

If your issue is a bug report, replace this boilerplate with a description of the problem, being sure to include at least:

    what happened,
    what you expected to happen instead, and
    any steps to reproduce the problem.

Also fill out the version information below and add log output or screenshots as appropriate.

If your issue is a feature request, simply replace this template text in its entirety.

### Version Information

    App Version: 0.x.y
    Syncthing Version: v0.x.y
    Android Version: Android x.y / Cyanogenmod x / ...
1.transfer file from mobile to pc has full speed
2.trasnfer a small file(about several hundred mb but smaller than 1gb) from pc to mobile the speed stuck into a low speed about 300kb/s (files which bigger than 1gb doesnt have this problem and transfer with full speed)
both devices connect in a same wifi

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
