### ISSUE TITLE
SyncThing is always disabled.

### ISSUE THREAD

**Issue by iwilliamson** [syncthing/syncthing-android#1778]
Newly configured setup.  

What happened:
First sync worked, but now SyncThing is showing as "disabled".  When I open the App, I get that my WiFi isn't "whitelisted.  Change Settings?".  Disabling and re-enabling the selected WiFi SSID makes it run, but then it goes to "disabled" again.

Expected operation:
I would expect SyncThing to be running when I'm connected to my WiFi.

Steps to reproduce:
Just be on my Wifi and try and get things to sync.

### Version Information

    App Version: 1.19.2
    Syncthing Version: 1,19.2
    Android Version: 12 - stock.

**Comment by AudriusButkevicius** [comment]
You need to grant the app location permissions most likely. Wifi ssid is assumed to give away location position.

**Comment by iwilliamson** [comment]
Thanks!  

That does seem to have fixed the issue, so I guess the problem is really the error message that the WiFi "isn't whitelisted".  

That's a little misleading.  Maybe the error message could be a little more specific.  Just a thought.

**Comment by AudriusButkevicius** [comment]
I think we explain that when we ask for location permissions.

**Comment by iwilliamson** [comment]
Yeah - I think I may have missed the fact that the service running does count as "While the app is running".  That explains why when I start the actual "app", it seems to work.  

Anyway - thanks for the help!
