### ISSUE TITLE
Typo in res/values-it/strings.xml: Nessono -> Nessuno

### ISSUE THREAD

**Issue by ilmessere** [syncthing/syncthing-android#1781]
Hi, there is a small typo in  **syncthing-android/app/src/main/res/values-it/strings.xml**, line **265**:

`<item>Nessono</item>`

It should be:
`<item>Nessuno</item>`

### Version Information

    App Version: 1.19.2
    Syncthing Version: v1.19.2

**Comment by AudriusButkevicius** [comment]
Translations are handled in transifex.
