### ISSUE TITLE
can't add folders under android/data

### ISSUE THREAD

**Issue by ToriAmos1963** [syncthing/syncthing-android#1782]
The directory/file picker does not show the Android/data folder. The app has permission to access to all files and media on my phone, the same as my file explorer. 

I have an application that stores its data in this folder after Android 12.

### Version Information

    App Version: 1.19.2
    Syncthing Version: v1.19.2
    Android Version: Android 12

**Comment by imsodin** [comment]
That's an Android restriction that Syncthing can't do anything about. Only workaround is root and adding the folder manually (advanced folder picker or web UI).

**Comment by acolomb** [comment]
That's true for Java applications. Unfortunately not possible for apps written in Go, despite it being a language promoted by Google.

**Comment by tomasz1986** [comment]
> That's true for Java applications. Unfortunately not possible for apps written in Go, despite it being a language promoted by Google.

Are you sure about that? I've just checked two file explorer apps (the built-in Samsung one and Material Files) under Android 11 and none of them are able to access `/sdcard/Android/data`. Material Files specifically says that root is required to access them.

**Comment by ToriAmos1963** [comment]
> That's true for Java applications. Unfortunately not possible for apps written in Go, despite it being a language promoted by Google.

Excuse my ignorance as I'm not a developer, but why would the choice of language dictate what folders the application can access? Isn't folder/file access governed by the operating system?

**Comment by tomasz1986** [comment]
> I use X-plore file manager running on Android 12 and can access that folder.

You're right. I've just checked the app myself, and it can access the folder, but in order to do so, it required both "all files access" (which Syncthing does too), and "internal storage access" (which Syncthing doesn't do).

![image](https://user-images.githubusercontent.com/5626656/166516919-4a847309-e6f1-40e5-b060-63b55eff0226.png)

**Comment by ToriAmos1963** [comment]
> > I use X-plore file manager running on Android 12 and can access that folder.
> 
> You're right. I've just checked the app myself, and it can access the folder, but in order to do so, it required both "all files access" (which Syncthing does too), and "internal storage access" (which Syncthing doesn't do).
> 
> ![image](https://user-images.githubusercontent.com/5626656/166516919-4a847309-e6f1-40e5-b060-63b55eff0226.png)

So this special access is only available to apps written in Java and not in Go or Cotlin?
