### ISSUE TITLE
gradlew should use `python` instead of `python3` when compiling in Windows

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing-android#1783]
I'm not sure if this is something that can be controlled within the repository or rather something that needs to be fixed in Gradle itself, but currently, when trying to use `gradlew` under Windows, it tries to execute the `python3` command, which isn't used at all by the Windows release of Python, which has always used just `python` (or `python.exe` specifically).

A clunky workaround is to create a symlink or hardlink named `python3.exe` linked to the proper `python.exe` executable. The caveat here is that the path changes upon each Python version update, so it needs to be created dynamically, e.g. by using a batch script as follows.

```
for %%a in (python.exe) do mklink /h "python3.exe" "%%~$path:a"
```

**Edit**:

I think the culprit is https://github.com/syncthing/syncthing-android/commit/c505c1b5257b70eb8938839c0d44d72ec2c82806.

**Comment by imsodin** [comment]
Yeah, python distros/installations are broken beyond reasonable: Your system should have python3 and our build docker image should have python - there's just no reason not to ship all of them for compatibility. Anyway I'll try adding it to our docker such that we can use "python" and hope there won't be someone else on a system that doesn't have that.
