### ISSUE TITLE
Feature Request: Notification exit button

### ISSUE THREAD

**Issue by APN-Pucky** [syncthing/syncthing-android#1789]
Hi,

I just want to raise the idea of adding an exit button to the permanent "syncthing is running" notification, instead of manually closing it from the app. Or is that not possible?

Best
APN

**Comment by imsodin** [comment]
That's dependent on your android version. On newer ones android lets you control visibility of them (before they were mandatory): Just long press on the notification and it gives you options.

**Comment by tomasz1986** [comment]
I think the proposition here was about adding a button to the notification that could be used to exit Syncthing 😉.

Many apps do offer some basic actions in the expanded view, e.g.

![image](https://user-images.githubusercontent.com/5626656/169697542-212bd056-795a-432c-8398-a8039b70aec0.png)

Syncthing at the moment doesn't use the expanded view at all though.

**Comment by imsodin** [comment]
Ah right, indeed I did misunderstand. Seems like a reasonable ask, but as always, feature request are unlikely to (read wont) happen unless someone does the work.

**Comment by YellowOnion** [comment]
There's literally no official way of closing the app. 

And for some reason on my Pixel 4a my display doesn't turn off while syncthing is running and I'm worried about OLED burn in.

**Comment by YellowOnion** [comment]
What the hell I don't have it, nor has it shown on older phones I have:

![Screenshot_20220604-192448.png](https://user-images.githubusercontent.com/364160/171989349-f376a873-5a4a-4e4f-8ae9-0c5f3ed11bb3.png)

**Comment by tomasz1986** [comment]
I've dug into the code and found that the "Exit" button is visible only when you haven't ticked the following option.

![image](https://user-images.githubusercontent.com/5626656/171989916-dd88dfaa-401c-433d-8f9f-cbbcfe2932b1.png)

In other words, the button is shown only when the app is set not to "start service automatically on boot".

**Comment by Tom4tot** [comment]
Just a quick bump, I think it would be a nice feature. Of course I understand it won't be magically done and someone has to do it, but I'm showing interest.
If it can motivate any volunteer, I'd be happy to donate a reasonable amount.

**Comment by imsodin** [comment]
Do [not plus-1 comment](https://github.com/syncthing/syncthing/wiki/NoPlusOne)!  
Also this plus-1 comment just caused the issue to be closed because of https://github.com/syncthing/syncthing-android?tab=readme-ov-file#no-feature-request-taken-feature-contributions-case-by-case
