### ISSUE TITLE
Feature request: Folder path missing

### ISSUE THREAD

**Issue by DocMAX** [syncthing/syncthing-android#1793]
Hi, can you do me a favour and give an option to disable this warning?
In my environment it's normal. that hosts sometimes power off.
In this situation Snycthing simply shall not sync anything and shut up.
Thanks.

**Comment by imsodin** [comment]
It shows an error, and does exactly what you do. We wont change that to show no error, and do nothing. It's always better if the user knows why it's not syncing.

**Comment by marek22k** [comment]
I think the FR could be useful. I get the same error message, but everything is perfectly synchronized.
