### ISSUE TITLE
Spurious file deletion due to MediaStore/ContentResolver delete race

### ISSUE THREAD

**Issue by gwillen** [syncthing/syncthing-android#1801]
Syncthing Version v1.20.3
Syncthing-Android Version 1.20.3
Android 12, Pixel 6 Pro (SP2A.220505.002)

This morning I discovered an issue where some files of mine, stored in a SyncThing folder, went mysteriously missing. I believe this _could_ also be the cause of some issues I've seen unsolved in the forums, such as:
https://forum.syncthing.net/t/renaming-caused-file-deletion-bug/17591 (both the original issue, and most suggestively, the similar issue described by the last poster, whose setup is identical to mine.)
https://forum.syncthing.net/t/syncthing-destroyed-at-least-two-photos/16242/8

The issue I observe: When a file is deleted and then rapidly recreated, if it is being synced to a Syncthing Android client, sometimes (maybe half the time), the Android client will spuriously delete the file within a few seconds to a minute or so afterwards. Example:

<img width="860" alt="Screen Shot 2022-07-09 at 6 06 22 PM" src="https://user-images.githubusercontent.com/458997/178127485-5252a4b7-b642-4135-960b-b487c9dc76f7.png">

The cause I suspect: When Syncthing Android finishes receiving a sync event, if it is a deletion, it calls out to MediaStore/ContentResolver, to cause the Android media system to de-index the file.

https://github.com/syncthing/syncthing-android/blob/d376ed793839983446e6b2a2c9a5f372706119cb/app/src/main/java/com/nutomic/syncthingandroid/service/EventProcessor.java#L144

HOWEVER, as far as I can tell, it is _not_ safe to use ContentResolver.delete() in this way, because it will not only delete the file from the media database, it will also _delete the file itself_ if it's still on the filesystem. And it looks like (for whatever reason -- I don't know if the delay is in Syncthing Android or in MediaStore somewhere), the call to delete the item from the MediaStore can take over 10 seconds to complete. Which means that, if the file gets recreated as quickly as possible, there is a race, and the ContentResolver.delete() can finally finish processing _after_ Syncthing has recreated the file, and re-delete it. (At which point Syncthing will detect this as a deletion and remove the file on both ends.)

To reproduce easily:
- Create a test file (from either end) and let it sync between the Android client and another client (the "desktop").
- Delete the file on the desktop client. Wait for the delete to propagate to the Android client.
- Recreate the file manually _on the Android side_ as soon as it's deleted. (This is faster than waiting for it to re-sync from the desktop side, so it's easier to win the race this way.)
- Wait 1-15 seconds.
- You will find that the file has disappeared again.

To fix:
... honestly I don't really understand the Android ContentProvider/MediaStore/MediaProvider/ContentResolver machinery or how it's supposed to work. I think this issue _may_ be new with Android 10/11, which changed how external storage access is managed, but I'm really not sure. The documentation is all uselessly vague. 

I assume the delete() call was added to fix a problem like the one described in https://stackoverflow.com/questions/29875744/deleted-file-resurrects-after-action-media-scanner-scan-file-intent/ , which is linked in the source. I am not an Android dev, and I don't know what a better fix is. But if you're with me this far, let me know if you'd like me to try to help figure that part out too.

Thanks!

**Comment by gwillen** [comment]
For the closest thing I can find to a smoking gun on the Android version issue, see:

https://stackoverflow.com/questions/70288256/android-10-contentresolver-delete-is-not-deleting-file-from-the-file-system

> This is happening only in Android 10. In Android 11, that file is deleted from filesystem as well as MediaStore.Files db

This person is complaining about the opposite problem (they _want_ the file deleted), but it at least documents the apparent behavior change.

**Comment by imsodin** [comment]
Awesome, very nice investigation! It hasn't even occurred to me that the android app might do operations on the filesystem, I was only ever considering what "syncthing-core" is doing. Given with scoped storage around android 10/11 the filesystem access is going through some Android virtualisation layer, it's quite conceivable that some interaction here is the cause.

Also likely that code is response for: https://github.com/syncthing/syncthing/issues/7974 It's a slightly different case there, however in the logs the line you linked came up too:

```
05-12 14:52:46.061  9031  9031 I EventProcessor: Rescanned file via MediaScanner: /storage/emulated/0/srv/test/health.txt
```

I wronlgy assumed `EventProcessor` was some android-internal thing, while it's actually from syncthing-android. In that case it looks like that call is case-insensitive and thus causes problems.

In either case, the linked questions and introduction/activation of scoped storage paint a consistent image: Before one needed/could handle the file in the filesystem and the file in the media database separately. Thus the app needed to take care of the db. Nowadays scoped storage means when syncthing interacts with the "filesystem" it actually interacts with android libraries, which take care of both filesystem and db(s).

I'll skip that code for >= Android 10 (scoped storage).

**Comment by imsodin** [comment]
Actually for https://github.com/syncthing/syncthing/issues/7974 a more fundamental problem is that the operation uses some weird method that uses an sql `LIKE` operation to match the path to items in mediastore, which from what I read is likely case-insensitive, i.e. is clearly wrong. I don't see why it even uses `LIKE` over a simple equality check, but I am neither an SQL nor Android expert, so maybe there's a reason.

**Comment by gwillen** [comment]
> Awesome, very nice investigation!

Thank you! It took me about a day, I was very pleased with myself when I figured it out.

> It hasn't even occurred to me that the android app might do operations on the filesystem, I was only ever considering what "syncthing-core" is doing.

I didn't think about that either, it was almost the last thing I figured out. But it made sense with Android being the only place this happens.

> I wronlgy assumed EventProcessor was some android-internal thing, while it's actually from syncthing-android.

Heh, I had exactly the same confusion when I was first looking in the logs. Once I found EventProcessor in syncthing-android I was pretty sure I had found the cause.

> Nowadays scoped storage means when syncthing interacts with the "filesystem" it actually interacts with android libraries, which take care of both filesystem and db(s).
> 
> I'll skip that code for >= Android 10 (scoped storage).

That makes sense -- do you have multiple versions available to test with? I have at least 12 (stock Android) and 11 (tablet, some Samsung thing), but I'm not sure if I have 10. I guess there's the emulator. I'm concerned that the exact behavior might be kind of subtle. (I think skipping that code will fix my problem for sure, just trying to think about whether it might add new problems.)

Thanks for your prompt response! I'm happy to test a build, although I guess that may not be feasible on a device where I have important state in the production app.

**Comment by gwillen** [comment]
> Actually for [syncthing/syncthing#7974](https://github.com/syncthing/syncthing/issues/7974) a more fundamental problem is that the operation uses some weird method that uses an sql `LIKE` operation to match the path to items in mediastore, which from what I read is likely case-insensitive, i.e. is clearly wrong. I don't see why it even uses `LIKE` over a simple equality check, but I am neither an SQL nor Android expert, so maybe there's a reason.

I am not an Android expert, but I know SQL pretty well. I definitely can't think of a reason for this. I think the `LIKE` is probably cargo-culted -- it worked for someone once, and then people just copied it. 

I found another tutorial that does it using `=` instead of `LIKE`, but their approach is broken in a different way (they use manual quoting of the path, instead of a placeholder `?` in the query, so it will break horribly if a path has quote marks in it.)

https://sandersdenardi.com/querying-and-removing-media-from-android-mediastore/

The whole API is really a mess. :-(

**Comment by imsodin** [comment]
Thanks a lot again!  
PR with test artifact here: https://github.com/syncthing/syncthing-android/pull/1803
If you don't want to test with that, checking out the next RC would also be helpful.

> The whole API is really a mess. :-(

Welcome to Android. Also if there's any documention what the content provider actually does when calling `.delete` (just update db, or remove the actual file, or ???) it's really well hidden. And user/dev reports suggets that behaviour changed with new Android releases. Pure joy.
