### ISSUE TITLE
Syncthing Android shows that the device is updated while it is still syncing

### ISSUE THREAD

**Issue by reportxx** [syncthing/syncthing-android#1804]
Syncthing Android shows that the device is updated while it is still syncing. See attachment
![syncthing screenshot](https://user-images.githubusercontent.com/84130654/178677816-6f1c2779-a02f-4e79-8480-1b49c969cfa5.jpeg)
.

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
