### ISSUE TITLE
[Feature Request/Security] Make All files access optional

### ISSUE THREAD

**Issue by Blocked** [syncthing/syncthing-android#1806]
It seems the app already uses storage access framework[SAF] to access specific folders. But, when the app is opened, it immediately asks for all files access and the app is unusable without that permission. This request is to make that permission optional. 

### Reasons:

- Privacy: Only folders that needed to be synced are provided with fine grained permission 
- Security: In case of hidden security vulnerabilities now or in the future, the rest of the filesystem cannot accessed  due to the OS enforcing permissions. 

Implementing this improves the overall permissions profile of this app, resulting in better trust among most users, who cannot read the source code and decide for themselves.

**Comment by tomasz1986** [comment]
Just a comment, but "all files access" doesn't mean that the app can access absolutely everything. The actual access is limited to the `/sdcard` partition, and not even the whole of it (e.g. other apps' data located in `/sdcard/Android/data` still isn't accessible).

**Comment by Blocked** [comment]
@tomasz1986 

Thanks for the comment. AFAICT, the [permission](https://developer.android.com/training/data-storage/manage-all-files) grants  compete access  to all user accessible system. If I were to create a malicious fork, I'm able to access everything except root fenced folders on a non-root device. 

>The actual access is limited to the /sdcard partition

If that's the case, all the more reason to make this permission  completely optional. Most modern devices lack a sd card and it's not reasonable to enforce this permission as mandatory on all devices/users.

**Comment by imsodin** [comment]
The app does not use SAF, it's a go application that doesn't care for androids java application. To allow that raw/direct access, said permission is necessary.

**Comment by tomasz1986** [comment]
> AFAICT, the [permission](https://developer.android.com/training/data-storage/manage-all-files) grants compete access to all user accessible data.

There was a discussion about this, either here or on the forum. The Syncthing app specifically couldn't access anything beyond what was mentioned above.

> Most modern devices lack a sd card

The `/sdcard` partition on Android is the internal storage. It's called `/sdcard` for historical reasons, because first Android devices used actual sd cards for this purpose.

**Comment by Blocked** [comment]
@imsodin I am extremely disappointed that you make choices based on UX and potential fear of backlash by inexperienced users over actual security and privacy.

**Comment by Blocked** [comment]
@acolomb Even if it is a technical limitation, it's a choice to enforce this as well. As @imsodin says,

>And while it might be possible to make it optional and make Syncthing work with just it's own private folder,

If the app cannot work without raw sockets, it'll still have access to `/data/data/com.nutomic.syncthingandroid` and even possibly `/storage/emulated/0/Android/data/com.nutomic.syncthingandroid`. The internal storage `data/data/com.nutomic.syncthingandroid` can be exported through the inbuilt files app(eg: termux does this). If a user chooses to use only these storages, they shouldn't have to give all files access. If a user chooses to receive only and not send or send only files put in these storages, they shouldn't have to give this permission. The reason cited for enforcing this mandatory all files access is simply UX:

>then they'll be annoyed about not being able to access the files they need

Which is frankly insulting the end users.  On demand runtime permissions are already a thing and any user familiar with file systems and  synchronization knows what folders are not accessible, when they denied that permission. Furthermore, the permissions screen shouldn't be put first on first open, but when a folder is about to be chosen. The current model is bad UX in itself - forcing a permission screen without the user even getting to see anything. If a user denies it during folder choosing, they can be informed that only "hidden folders" are available to sync and that all files access can be enabled in settings. If all that sounds a bit complicated, let me quote [my  favorite FAQ from the official docs](https://docs.syncthing.net/users/faq.html#why-is-the-setup-more-complicated-than-bittorrent-resilio-sync):

>Why is the setup more complicated than BitTorrent/Resilio Sync?

>>Security over convenience. In Syncthing you have to setup both sides to connect two devices. An attacker can’t do much with a stolen device ID, because you have to add the device on the other side too. You have better control where your files are transferred.

**Security over convenience**! I just hope this will be the case even with this android wrapper, that developers chose security over convenience every time. There are other sync apps for convenience. People choose this for security and good security apps don't require users to trust them.

**Comment by imsodin** [comment]
You are welcome to (try to) discuss this on https://forum.syncthing.net, though I'd suggest you first think about or search for use-cases and problems encountered by users on android, should be enlightening. I am locking this issue.
