### ISSUE TITLE
work only when charging

### ISSUE THREAD

**Issue by Anatoliyr210** [syncthing/syncthing-android#1810]
The application remains in the notification area and continues to work even if the charging of the smartphone is stopped, and in the execution conditions there is an option to work only when charging.
It was the same in previous versions of the application.

Samsung note 9, android 10.
Syncthing 1.20.4rc1

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
