### ISSUE TITLE
cannot sync /sdcard anymore, message sounds weird

### ISSUE THREAD

**Issue by emdete** [syncthing/syncthing-android#1819]
I always had a sync of /sdcard to my notebook but when i now installed syncthing to a new phone i cannot choose that directory anymore. It tells me "Zum Schutz deiner Daten einen anderen Ordner wählen" ("for safety of you data choose another folder" or the like). no explanation why that would increasy safety not to be able to backup my sdcard, no way to overwrite that rule. is this a bug? 

![Screenshot_20220808-172924_Dateien](https://user-images.githubusercontent.com/3251523/183455634-54f93df2-5af7-40b3-a1b6-cbb6b848e3a4.png)

**Comment by tomasz1986** [comment]
This is expected with the changes in the app and targeting the newer Android versions. You may want to try using the advanced file picker (can be enabled in the app settings) or the Web GUI (can be opened using the left slide-out menu) and type the path manually with it. If it works, then you're good to go, and if it doesn't, then you probably need root to access and sync that specific path.

**Comment by emdete** [comment]
sorry for blaming syncthing for that ugly message - i really like st, it's an amazing piece of software.

with an ignore of `Android/` the `/sdcard` can be synced without root just fine. your hint to use the web-gui worked fine too. thank you!
