### ISSUE TITLE
Possible error in the localization in Italian v1.20.4 and earlier

### ISSUE THREAD

**Issue by hixcube** [syncthing/syncthing-android#1820]
In the Italian Syncthing Settings, under Backup, starting the "Export configuration" option, a warning is produced which may be incorrect.  

The sentence also contains a trivial typo that can be eliminated: The typo is a letter "n" after "Vuoi veramente esportare la tua configurazione? I files esistenti verrano sovrascritti.n"  The letter "n" has no reason to be there and can be eliminated.

The second possible and most important mistake in case it is confirmed, is in the sentence: 
"ATTENZIONE!  le altre applicazioni POTREBBERO NON ESSERE IN GRADO di leggere la chiave privata dalla localizzazione di backup e usarla per scaricare/modificare i files sincronizzati"

(In English:  "WARNING! Other applications MAY NOT BE ABLE to read the private key from the backup location and use it to download / modify the synchronized files".

Well, the sentence as written - in the general context - makes little sense and is perhaps wrong....

In my opinion, the sentence should be like this:

 "ATTENZIONE!  altre applicazioni potrebbero ESSERE IN GRADO di leggere la chiave privata dalla localizzazione di backup e usarla per scaricare/modificare i files sincronizzati". 

(In English:  "WARNING! Other applications MAY BE ABLE to read the private key from the backup location and use it to download / modify the synchronized files".

Thus removing the word "non".  Greetings.

**Comment by AudriusButkevicius** [comment]
Localization is managed via transifex, you can make the change there.

**Comment by hixcube** [comment]
can you please give me the link?

**Comment by hixcube** [comment]
#

**Comment by hixcube** [comment]
I found the translation on Transifex and discovered that months ago I added this fix myself, acquired as a suggestion but never applied.

**Comment by imsodin** [comment]
Thanks for catching and supplying a fix in transifex - I applied it now. Generally please login there and ask to become a team member, to apply changes directly. I think many languages don't have people going over suggestions of others and applying them.

**Comment by hixcube** [comment]
Well done!
