### ISSUE TITLE
Android 13 Support

### ISSUE THREAD

**Issue by justinormont** [syncthing/syncthing-android#1825]
Android 13 has been released to AOSP and Pixel devices -- https://androidpolice.com/android-13-stable-available-for-google-pixel-phones

Q: Has the Android wrapper for, and Syncthing itself, been tested with Android 13?

### CI/CD
Side note -- setting up a CI/CD which tests PRs against various Android versions would be beneficial. That's where I looked first to see if Android 13 passed tests, only to find there's no automated CI/CD setup for this repo. The CI/CD ([GitHub overview](https://resources.github.com/ci-cd), [GitHub instructions](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle)) could be setup to run the existing unit tests (`gradle connectedAndroidTest`, via [CONTRIBUTING.md](https://github.com/syncthing/syncthing-android/blob/733f873ae32636f55307e0678712bcfdb1fce6ac/CONTRIBUTING.md#contributing-code)).

**Comment by imsodin** [comment]
There hasn't been any testing that I know off, I also don't know any reason why it shouldn't work

And there is CI/CD, what's lacking is tests.

Anyway for general questions like these please use the forum - https://forum.syncthing.net/. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
