### ISSUE TITLE
WebGUI is not displayed correctly on 1080p screen with over 420 dpi

### ISSUE THREAD

**Issue by lyaaz** [syncthing/syncthing-android#1831]
![Screenshot_20220907-112756_Syncthing](https://user-images.githubusercontent.com/45838887/188862658-76a83d83-cc64-4070-a340-c138249f701c.png)

### Version Information

    App Version: 1.20.4 f-droid build
    Syncthing Version: v1.20.4
    Android Version: Android 12.1
    Device: Xiaomi MI 9

**Comment by imsodin** [comment]
This would be a syncthing issue, as the web gui isn't android specific. However the web UI not working well on small screens is partly why the wrapper UI exists. Plus the syncthing web UI is an old piece of hard to maintain code, if anyone wants to improve anything they are welcome but it's hard and unlikely to happen. Or in other words not worth having an open issue for that.

**Comment by tomasz1986** [comment]
The GUI is actually fine on a small screen. It's the tablet version (which your phone's large screen triggers) that breaks like that. I've seen it break like that that before even on desktop with a small monitor.

**Comment by imsodin** [comment]
@tomasz1986 If you feel this is something that is worth fixing and can be fixed with reasonable effort (no need for you to commit to do it, just your judgment as you have done some work on the UI) - feel free to move the ticket to syncthing and reopen.

**Comment by tomasz1986** [comment]
I do think this is worth fixing, but I also remember seeing a similar issue in the main repository already. I can't find it now though :sweat:, but it could be something old (from around ~2015) and without the standard `ui` label, so not easy to find without going through the issue list by hand.

I will try to check UI-related issues again and mark the old one to fix if I find it, or open a new one in the main repo if it is just my imagination and the issue doesn't actually exist yet.
