### ISSUE TITLE
No deletions on Android

### ISSUE THREAD

**Issue by gutjuri** [syncthing/syncthing-android#1832]
I use Syncthing to sync my phone's filesystem to my PC. This has always worked fine. However, a few days ago a bug appeared: deletions performed on the PC are no longer realised on the Phone. 

An example (let A be the Pictures folder on my Phone and B be the Pictures folder on my PC):

1. I take a Picture (img.jpg) on the Phone (A's contents: img.jpg, B: empty)
2. It gets synced to my PC (A: img.jpg, B: img.jpg)
3. I delete the Picture on my PC (A: img.jpg, B: empty)
4. img.jpg is NOT deleted on the phone. A never receives the update that img.jpg is to be deleted

Overall, this leaves the devices in an inconsistent state.

Is this a known problem? 

Thanks for your time for investigation :)

### Version Information

    App Version: 1.21.0
    Syncthing Version: v1.21.0
    Android Version: Android 10

**Comment by AudriusButkevicius** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by gutjuri** [comment]
Alright, thanks
