### ISSUE TITLE
Publish 1.21.0 on F-Droid

### ISSUE THREAD

**Issue by Word66** [syncthing/syncthing-android#1836]
Please publish version 1.21.0 on F-Droid.

**Comment by AudriusButkevicius** [comment]
We don't manage fdroid publishing, fdroid does.

**Comment by Word66** [comment]
Just figured at least one person that maintains this project would have at least a passing interest in 1.21 not being available on F-Droid 3 weeks after release. Even if F-Droid handles builds/publishing, still seems like someone here would want to check into it.

**Comment by tomasz1986** [comment]
They know already 🙂. There was an issue about it somewhere, which I cannot find right now, but basically their Go version was too old and the compilation was failing.
