### ISSUE TITLE
Does not autostart and run in background, making it a pain to rely on

### ISSUE THREAD

**Issue by firefoxlover** [syncthing/syncthing-android#1841]
The Android app does not autostart, and there is no such feature to do it manually like on Linux.
There is a permission to autostart on Android, please add it.

### Version Information

    App Version: 1.20.4 F-Droid
    Syncthing Version: 1.20.4
    Android Version: LineageOS 19.1 unofficial

**Comment by tomasz1986** [comment]
Have you enabled the option "start on boot" in the app settings?

**Comment by firefoxlover** [comment]
> Have you enabled the option "start on boot" in the app settings?

Thank you! I would request that this has to be enabled by default, to make it user-friendly.

**Comment by imsodin** [comment]
That's just your use case, not generally applicable. An option or a hint in the first start wizzard would totally make sense. I'll link to this ticket for that: https://github.com/syncthing/syncthing-android/issues/622
