### ISSUE TITLE
[bug] [Android] "Syncthing seems to be down, or this is a problem with your Internet connection... Retrying" --- receiving this error often, and syncthing must be restarted to sync

### ISSUE THREAD

**Issue by arooni** [syncthing/syncthing-android#1842]
### Does your log mention database corruption?

No

If your Syncthing log reports panics because of database corruption it is
most likely a fault with your system's storage or memory. Affected log
entries will contain lines starting with `panic: leveldb`. You will need to
delete the index database to clear this, by running `syncthing
-reset-database`.

### Include required information

Please be sure to include at least:

 - which version of Syncthing and what operating system you are using
 - Android 13 ; 1.21.0
 - browser and version, if applicable
 - what happened,
 - what you expected to happen instead, and
 - any steps to reproduce the problem.
Currently trying to transfer 18gb or so from android to android.  The only way to get the files to transfer is to actively run syncthing as the foreground app on the S22 Ultra phone.  If it gets sent to the background I get this error message and must restart syncthing manually.  Additionally I have permitted syncthing to run in the background with no battery optimizations.

**Comment by imsodin** [comment]
Some vendors are known to aggressively kill apps in background irrespective of android settings - I'd guess that's the case here. Please provide logs for the time this happens, and if it's not being killed by the OS we can re-open this issue and investigate.  If you need assistance with that or have other questions, please use the forum - https://forum.syncthing.net/ - first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
