### ISSUE TITLE
App does not have 'start automatically' in settings checked by default

### ISSUE THREAD

**Issue by 91rl** [syncthing/syncthing-android#1844]
### Issue

The app comes by default with the 'start automatically' disabled in settings, which according to users on the syncthing reddit is not typical.

### Version Information

    App Version: v1.21.0
    Syncthing Version: v1.22.0
    Android Version: Android 12
    Device: Samsung Xcover Pro

**Comment by 91rl** [comment]
> Duplicate of #1841, which is closed in favor of #622

I don't understand how this just for my (or the other user from #1841) use case, I don't know how else someone would even use this app without it autstarting. (I'm not trying to be snarky, just don't understand how else it'd be used, and appreciate your feedback.)

**Comment by acolomb** [comment]
I do have the option disabled. When the phone needs to be restarted (seldomly), I open the app once and then it stays active in the background. Works like a charm.

Setting it to run as a service causes the "Quit" menu entry to be hidden, so there is no clear way to stop it anymore. I want some control over whether it's running in the background, so the default is actually my preferred configuration.

**Comment by 91rl** [comment]
Ah okay I didn't know about it hiding the quit menu entry. Is tht a limitation imposed how background processes work, or just a feature of the app?

**Comment by acolomb** [comment]
I'd guess it's a feature of the app, because when I tell it to *always* run in background, there's no sense in providing a button that will cause that to be no longer true.
