### ISSUE TITLE
Unable to create new folder on Android TV 12

### ISSUE THREAD

**Issue by Cacha21** [syncthing/syncthing-android#1845]
Until today I was using syncthing on my google chromecast with google TV on android version 10 without issues.

After upgrading it to android 12 I'm now unable to create new folders. After setting uo the label and ID for the folder, when i click to select the destination directory I get a toast message that pops up on the bittom of the screen that says: "You don't have an app that can do this".

I'm using the latest version of Syncthing from the Play Store for Google TV.

Thanks in advance!

**Comment by tomasz1986** [comment]
I remember the same problem having been reported already, but I can't find the issue right now. It could have been on the forum. Nevertheless, you should still be able to enable the "advanced folder picker" in the settings and then type the folder path manually.

**Comment by imsodin** [comment]
I guess that's a stripped down environment without a normal filepicker, so no app can serve the action request to pick a path syncthing is sending. If you need further help to get this sorted out please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker. Thanks!
