### ISSUE TITLE
Propose gallery/paths with pictures as sync folders

### ISSUE THREAD

**Issue by thewh1teagle** [syncthing/syncthing-android#1846]
I think that the most useful thing I can do with this app is to sync my photos and contacts to my server.
but configuring manually each folder that has images in my phone it's a sisyphean job.
I would like to have the ability to select gallery libraries to sync (like a checkbox to select all or multiple)
and then maybe it will create unique base folder on the server and in that folder I will have multiple folders per gallery library.

https://stackoverflow.com/questions/23686024/android-how-to-get-all-folders-with-photos

**Comment by imsodin** [comment]
The only thing that is reasonably doable (as in only requires android wrapper functionality, not redisigning syncthing itself) would be to get a list/prompt of directories with folders and allow the user to select them to sync. Creating some synthetic folder (album) that collects all of them is not (unless you want to make full copies on your android in a single place for every folder).

**Comment by thewh1teagle** [comment]
> 

I mean the same as how google photos works -- it finds all the pictures on the phone and upload them to google drive
and the same as how google contacts works -- it takes all your contacts and upload it to google contacts.
If I had this options I could completely leave google photos / contacts and use my own backup server.

**Comment by imsodin** [comment]
Ok, if that's the only use-case then lets close this - no point having a ticket for a feature no-one is asking for. The google photos approach is not doable for this app - as in would likely require writing a BEP/syncthing compatible app (which has been worked on in https://github.com/syncthing/syncthing-lite)
