### ISSUE TITLE
Operation Not Permitted

### ISSUE THREAD

**Issue by leuchtturmsss** [syncthing/syncthing-android#1859]
Hey ya'll,
Just wanted to let you know syncing files appears to be broken from Trisquel GNU/Linux to LineageOS.

![Screenshot_20221118-205952_Syncthing](https://user-images.githubusercontent.com/118345067/202833338-97b5e1c5-41ec-45ff-b9bd-c86711d11834.png)

I'm aware this is a common issue among `chmod` users on GNU/Linux. Is there a working work-around for Android users? 
How should I go about syncing my files?

Let me know if there are any settings/permissions I should check as well!

### Version Information

    App Version: [1.22.1.1](https://f-droid.org/en/packages/com.nutomic.syncthingandroid/)
    Syncthing Version: v1.22.2-dev.1.
    Android Version: Lineage OS
    Device: Pixel 3a XL

**Comment by leuchtturmsss** [comment]
I apologize, I believe this may be a duplicate of #146

However, the issue appears to persist in a much newer release?

**Comment by tomasz1986** [comment]
You need to remove special characters like `:` from the filenames. The FAT filesystem that is used on Android doesn't support those.

**Comment by leuchtturmsss** [comment]
> You need to remove special characters like `:` from the filenames. The FAT filesystem that is used on Android doesn't support those.

Thank you so much, apologize I didn't catch that beforehand.

Removing the `:` characters fixed the issue.
