### ISSUE TITLE
"Folder path missing" even if path has become accessible in the meantime

### ISSUE THREAD

**Issue by StrikerTwo** [syncthing/syncthing-android#186]
I use SyncThing to sync a path inside an encrypted EFS container, so the path is only accessible while the container is mounted. 
Syncthing handles this gracefully (show a notice "folder path missing" and does not do anything). But if I mount the container while SyncThing is running, it still shows the notice although it starts syncing the folder successfully.
I guess all that is missing is that the folder status should be checked regularly, not just on startup.

Thanks, and keep up the good work!

**Comment by Nutomic** [comment]
Can you check if this still happens? I just checked the code, and restarting the web GUI should also trigger a reload of the app GUI.

And I don't think Android provides events for device (un)mount, so there's probably no good way to reload automatically (polling is bad for battery).

**Comment by Zillode** [comment]
Feel free to reopen if this is still an issue. The current code seems ok to tackle this pattern.

**Comment by StrikerTwo** [comment]
Yeah, looking good now.

**Comment by agharbeia** [comment]
I confirm having this issue as of version v0.14.43, Linux (64 bit) running as a system service.
The folder exists and is synching properly.
The user running Syncthing is the owner of the root of Syncthing and has rwx access to it.
Here's a [screenshot](https://snag.gy/EznXpI.jpg)

**Comment by StrikerTwo** [comment]
This is an issue in the Syncthing Android app. I think you're looking for https://github.com/syncthing/syncthing/issues

**Comment by AudriusButkevicius** [comment]
Pls use the forum for suport matters.
