### ISSUE TITLE
Android version of syncthing has problems with case-insensitive backends

### ISSUE THREAD

**Issue by Unode** [syncthing/syncthing-android#187]
I noticed this after renaming some folders on a linux machine.
The android version eventually stopped syncing (100% was never reached) and when I visited the web interface there was a warning stating that I should check the logs as something strange was happening.

The logcat:

    ...
    I/SyncthingNativeCode( 2485): [7AJHV] 23:13:53 INFO: Desperation mode ON
    I/SyncthingNativeCode( 2485): [7AJHV] 23:13:53 INFO: Puller (folder "books", dir "Book/Chapter"): delete: remove /storage/emulated/0/Book/Chapter: directory not empty
    I/SyncthingNativeCode( 2485): [7AJHV] 23:13:53 INFO: Puller (folder "books", dir "book/Chapter"): delete: remove /storage/emulated/0/book/Chapter: directory not empty
    I/SyncthingNativeCode( 2485): [7AJHV] 23:13:53 WARNING: Folder "books" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.
    ...

The folder is now called `book/chapter`, and contains files and folders. This folder was originally called `Book/Chapter`.

I fixed it by removing and re-adding the folder in order to have it forget about past files/folder names.

I'm still new to the android world but it seems the storage backend is case-<b>in</b>sensitive. I would expect this if I was using the external sdcard (FAT32) but it seems the internal storage follows the same rules. Can't think of any good excuse for it to do so.

Performing `cd BOOK/CHAPTER` on the `adb shell` actually opens the folder even if `ls` indicates the name to be `book/chapter`.

**Comment by Nutomic** [comment]
syncthing/issues#439

**Comment by Nutomic** [comment]
This should be fixed in Syncthing. If you still have this problem, please report it at the syncthing repo.
