### ISSUE TITLE
External sdcard permisions: Syncthing app can create a folder but no sync

### ISSUE THREAD

**Issue by altbert** [syncthing/syncthing-android#1881]
Can someone explain this behaviour to me?

I wanted to add a folder located in the sdcard (According to the wiki, android 10 should support sdcard write) and the app showed me a warning that it cannot write to the sdcard. But when i select a folder in the sdcard, the app creates a folder named ".stfolder".
Why is this folder created if syncthing doesn't have file write permissions? Shouldn't be impossible for the app to create a folder?

First, i create an empty folder named "Test" in the root path of the sdcard
<img src="https://user-images.githubusercontent.com/42727644/213005557-cf084685-b8f6-4eb1-931b-3eccb757c992.jpg" width="200" height="350" />
 
Next step add a new folder to Syncthing
<img src="https://user-images.githubusercontent.com/42727644/213006683-5e45f5b1-d1fe-4537-ac16-8e39166c63eb.jpg" width="200" height="350" />
 
Then select the folder created in the sdcard
<div style="  content: ""; clear: both; display: table;">
        <img src="https://user-images.githubusercontent.com/42727644/213006891-65f98746-0ec0-4ad3-b140-dc530f46457d.jpg" widht="200" height="350">
        <img src="https://user-images.githubusercontent.com/42727644/213006945-dd8297b9-6c04-4c96-bdea-3d634a9e5eff.jpg" widht="200" height="350">
</div><br>
In the above steps, the app shows that syncthing can't write to the sdcard. But...

<img src="https://user-images.githubusercontent.com/42727644/213008752-4237775b-e8bc-4dd5-993d-cd7898218307.jpg" widht="200" height="350">
Now the folder has a new folder created by Syncthing app or so it seems.
<br><br>
Device: Samsung S9<br>
Android Version: 10<br>
One UI: 2.5<br>
Syncthing Version: 1.23.0

**Comment by tomasz1986** [comment]
According to a recent discussion on the forum, the wiki is wrong. You need Android 11 and up to be able to utilise the all files access permission. Otherwise, the only other option is to run Syncthing with root privileges.

**Comment by altbert** [comment]
Okay, i understand. But why/how is the folder ".stfolder" created if it doesn't have permissions to write?

**Comment by imsodin** [comment]
I am not 100% sure here. It might also just be wrong logic that tells you that you don't have permission to write. Someone with android 10 and the time coud investigate, I don't have it. I updated the wiki.

**Comment by altbert** [comment]
@Catfriend1 sorry to bother. Maybe you can help in the understanding of this behavior.

**Comment by altbert** [comment]
https://forum.syncthing.net/t/folder-created-at-read-only-sd-card/11973 i have found the explanation
