### ISSUE TITLE
Crashes due to syncthing event parsing failure

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing-android#1884]
Hi,

Not sure when this started, but syncthing no longer runs on my pixel 4a running android 13. I have the 4th of Jan version of syncthing-android installed from google play.

The app starts, and my folders start to scan and sync, but after about 10 seconds the app just disappears and the "syncthing is running" notification goes away too. I can restart syncthing, but it always dies shortly after.

I can't run the app long enough to prod around in settings or look at logs. I've tried clearing the cache, no joy.

I have 3 folders shared, about 10,000 files in total. Sharing to OpenBSD nodes.

Is there anything I can try? Thanks

### Version Information

    App Version: 1.23.0
    Syncthing Version: 1.22.3
    Android Version: Stock Android 13

**Comment by vext01** [comment]
Even if I pause all folders, it still crashes.

**Comment by vext01** [comment]
Still a problem. Can anyone help?

**Comment by tomasz1986** [comment]
Can you open a topic at https://forum.syncthing.net? At this point, this is non-actionable.

In the forum topic, at the very least please check inside `Android/data/com.nutomic.syncthingandroid/files` on the internal storage and upload the log file from after the crash. You may also want to provide a logcat (see https://developer.android.com/studio/command-line/logcat), although this is a bit more advanced (as you need to have ADB installed and use the command line to grab the log, etc.). If you do decide to get the logcat, I'd suggest doing `logcat --clear` first, then start the app and wait for the crash, then do `logcat -f <path-to-file>` and upload the resulting log.

**Comment by vext01** [comment]
Thanks so much. I'll have a look at that when I can!

**Comment by jonathancross** [comment]
Syncthing `v1.23.4` is consistently crashing for me after ~10-20 seconds on 2 phones:
* Pixel 4a running GrapheneOS `TQ2A.230505.002.2023050500` (based on Android 13)
* Pixel 2 running stock Android 11 build `RP1A.201005.004.A1`


[2023-05-17_Syncthing_Crash.txt](https://github.com/syncthing/syncthing-android/files/11500914/2023-05-17_Syncthing_Crash.txt)

**Comment by imsodin** [comment]
Thanks for the crash log - that's the app assuming event data is a map of strings to any type. While it actually is any type. I'll try to get that fixed - I hope there's not too many usages to fix...

**Comment by jonathancross** [comment]
@imsodin Anything we can do to move this forward?

I'm also curious, if the JSON format of Syncthing changed, all Android installations would break, no?

PS: A friend's Pixel 3 with GOS is also broken.

**Comment by imsodin** [comment]
Ahem, nothing except the bump you just made. Usually bumps are more annoying than helpful, but here it's absolutely warranted: I did start to work on it but didn't finish and then forgot about it. I can't guarantee any timeline, but I do intend to fix it. Feel free to bump after a reasonable time if you don't hear anything.

Of course me having started doesn't mean that no-one else should work on it in the meantime, but I guess that's not what is being asked/proposed here :)
