### ISSUE TITLE
Android 13 on Google Pixel 6a: Syncthing shows synchronizing at 99%, but all files synchronized

### ISSUE THREAD

**Issue by LittleAlf** [syncthing/syncthing-android#1885]
After a recent update to Android 13 on my Google Pixel 6a it seems like Syncthing stumbles about finishing the synchronizing process properly:

- All connected devices (1 Windows device and 1 Linux device) show '`Synchronizing (99%)`' with '`Download: 0 B/s`" and '`Upload: 0 B/`s'
- I know that it is one file which is synchronized very frequently; this file is actually up to date on the Google phone as well - I just tried it again today!
- This behavior is now for several days already
- Restarting Snycthing does not change anything

I would expect, that after updating successfully, Syncthing shows this and not 99%.

### Version Information

    App Version: 1.23.0
    Syncthing Version: v1.23.0
    Android Version: Android 13.

**Comment by imsodin** [comment]
I am not saying this is not a bug, but it isn't actionable thus doesn't help in the bug tracker. We get quite a few similar reports, often it's explainable and sometimes not, i.e. looks like a bug but isn't resolvable.  To get some help for your situation, please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker. Thanks!
