### ISSUE TITLE
Filenames with colon fail to synchronize

### ISSUE THREAD

**Issue by nicobo** [syncthing/syncthing-android#1886]
Some files I share have colons in their names, because they are named after an hostname AND port (e.g. `hostname:port.ini`).

For the record, in my case this allows sharing a configuration referential for automation scripts, using services's unique URL (part of) to identify the correct file. But there are other usages.
I'm sync-ing this store with several Linux machines so I am not concerned with weak/Windows filesystem naming limitations.

I've observed that, although the Linux hosts were correctly sync-ing, the Android one was failing on some items and I could not find a way to fix it with reloading nor re-scanning.

After renaming the files without colons, the Android app finally synced the files (but breaking my use case).

### Version Information

    App Version: v1.23.0
    Syncthing Version: v1.23.0
    Android Version: Android 12 / LineageOS 19-20221218-microG-FP3

**Comment by AudriusButkevicius** [comment]
Not all filesystems support colons in filenames.
Namely fat32/exFat do not.

This is not a syncthing limitation, but a limitation of the underlying filesystem.

**Comment by rasa** [comment]
See potential solution in https://github.com/syncthing/syncthing/pull/7876 .
