### ISSUE TITLE
Feature request: Sync to/from ¨Android/Data¨ directory.

### ISSUE THREAD

**Issue by Gonckzilla** [syncthing/syncthing-android#1891]
Using v1.23.1 on Android 12.

The request is adding the ability to sync files from /Android/Data folders. In my specific case, this would allow for syncing of game data from a console emulator (AetherSX2, which uses /0/Android/Data/xyz.aethersx2.android) with its PC counterpart (PCSX2). I'm aware this isn't a simple task due to the new ¨prohibitions¨ on Android 11+, which make it harder to get access to this directory. There are workarounds, check out Amaze File Manger, which is open source and available on [GitHub](https://github.com/TeamAmaze/AmazeFileManager) - allows you to manage files in this directory.

I think this is similar to #1240  but opening a new issue because I think the objectives are different. 
As a last comment, thank you very much for this app.

**Comment by tominysun** [comment]
I have used FolderSync, it can acess the /Android/Data folders too.
Hope Syncthing can add this feature. There are many files need to sync in this folder.
The same question was discussed on [other website](https://www.v2ex.com/t/728162) 3 years ago, unfortunately, they gave up on solving this problem.

**Comment by imsodin** [comment]
The syncing mechanism is written in Go, i.e. does not use the android APIs (directly). Any workarounds are using those APIs, which is not an option for this app. In addition the general feature policy applies, see https://github.com/syncthing/syncthing-android#no-feature-request-taken-feature-contributions-case-by-case
