### ISSUE TITLE
Feature request: Access file from work profile through file shuttle (shelter/island/insular)

### ISSUE THREAD

**Issue by N1N74** [syncthing/syncthing-android#1892]
Hello!
I'm using work profile apps and the data stored there doesn't seem to be easily accessible through personal account or vice versa. I am currently using file shuttle feature of shelter to transfer files to personal account. This feature does not seem to be working with syncthing (accessing work folder files in personal account) as it throws a folder path missing error. It would be nice to be able to access files from there similar to files app (documentsui) which seems to be able to.
Related apps: [Shelter](https://gitea.angry.im/PeterCxy/Shelter) or [Island](https://github.com/oasisfeng/island) or [Insular](https://gitlab.com/secure-system/Insular)
Additional information: [Insular claims this should be possible](https://secure-system.gitlab.io/Insular/files.html)

**Comment by N1N74** [comment]
related: Catfriend1/syncthing-android#968

**Comment by imsodin** [comment]
This project isn't accepting feature requests - see https://github.com/syncthing/syncthing-android#status-maintenance-mode---co-maintainers-welcome
