### ISSUE TITLE
User interface suggestions

### ISSUE THREAD

**Issue by contrapunctus-1** [syncthing/syncthing-android#1897]
1. Bottom-bar-oriented interface for easier one-handed operation and less hand/finger travel - move the three tabs and the hamburger menu into a bottom bar. Make "Add folder" a FAB for the Folders tab, "Add device" a FAB for the Devices tab, and the settings gear a FAB for the Status tab.

2. Having folder icons to the right of each folder's entry makes it difficult to access them if you're using the phone with only the left hand. To make them accessible for cases of one-hand use, open folders in a file manager with a swipe left or swipe right gesture, or by long-pressing the folder entry.

   (Currently, swipe left/right is bound to switching tabs, which I rarely if ever find myself doing. If swiping for switching through tabs is desired, it could be implemented by swiping along the tab bar itself.)

Thank you.

**Comment by imsodin** [comment]
This project is not currently taking any feature requests, unless the wants to discuss contributing one. For context refer to the [section on mantenance status in the readme](https://github.com/syncthing/syncthing-android#status-maintenance-mode---co-maintainers-welcome).
