### ISSUE TITLE
Dynamic discovery does not work

### ISSUE THREAD

**Issue by 0verEngineer** [syncthing/syncthing-android#1899]
I have Syncthing running in a container on a vm, latest version.

Clients:
Android 13 GrapheneOS device and 2 Android 11 Samsung devices all with the latest syncthing app.

On the server local and global discovery is turned on.

However all 3 devices fail to connect to the server. It is the same inside the network as outside. Sometimes (very rare) it works on my grapheneOS device.

I have read many times that this should work if one side (the server) is not an android device, but thats not the case for me.

Addition: It works fine on my mothers macbook from another network.

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by 0verEngineer** [comment]
I have already checked the forum, i have the info from there that it should work if one side is not an android device but it does not work most of the time but on rare occasions.

So to me this looks like a bug and syncthing on android does absolutely have problems like this bcs i have found multiple posts online with similar problems.

Also other devices have no problems with dynamic discovery with the same server.


And also this problem exists with is related and not fixed: https://github.com/syncthing/syncthing-android/issues/1628

**Comment by 0verEngineer** [comment]
@imsodin why do you think this is not an issue?

**Comment by tomasz1986** [comment]
Usually, issues here need to either provide clear reproducible steps or debug logs with relevant information. At the moment, we can't do anything with the information provided here. That's why you were welcomed to the forum, so that others could ask you for more information to help investigate the problem.

The other problem about local discovery not working (https://github.com/syncthing/syncthing-android/issues/1628) is already very well known, so there is no need to have another issue talking about that.

**Comment by 0verEngineer** [comment]
@tomasz1986 
First of all not all users know what debug logs are and they just create an issue, which should be totally ok, because the alternative these users do is just uninstall and never try it again.

I am not such a user and i have no problems providing debug logs or other data, but there was no github issue template that said i should do so. So i just created an issue.

I'll just need the info what logs we need and where to gather them and i will happily provide them.

**Comment by tomasz1986** [comment]
There actually should be an issue template, just like below:

```
Do not report security issues in this bug tracker. Instead, contact security@syncthing.net directly - see https://syncthing.net/security.html for more information.

If your issue is a support request ("How do I get my devices to connect?" or similar), please use the support forum at https://forum.syncthing.net/ where a large number of helpful people hang out. This issue tracker is for reporting bugs or feature requests directly to the developers.

If your issue is a bug report, replace this boilerplate with a description of the problem, being sure to include at least:

    what happened,
    what you expected to happen instead, and
    any steps to reproduce the problem.

Also fill out the version information below and add log output or screenshots as appropriate.

If your issue is a feature request, simply replace this template text in its entirety.

### Version Information

    App Version: 0.x.y
    Syncthing Version: v0.x.y
    Android Version: Android x.y / Cyanogenmod x / ...

```

Did you not see it? You should have unless GitHub still has this bug where if you press the "New issue" button before logging in and only log in when asked to later, then the template isn't shown to you.

Anyhow, at this moment the proper route to investigate would still be to create a topic at the forum first.
