### ISSUE TITLE
Starts syncthing twice

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing-android#190]
http://imgur.com/8nZONW0

**Comment by Nutomic** [comment]
I'm not sure what changed, but this doesn't seem to occur any more.

Can you confirm this?

**Comment by generalmanager** [comment]
Works fine for me. I couldn't test on Android tough, because it insta-crashes on the only device it's currently installed on. Will have to take a look at that at some point...

**Comment by Nutomic** [comment]
Can you post a logcat of the crash? (in a seperate issue)
