### ISSUE TITLE
In sharing all devices are activated 

### ISSUE THREAD

**Issue by vepman** [syncthing/syncthing-android#1903]
All devices are always activated under sharing and after correction to one device, next time, they are all activated again.

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
