### ISSUE TITLE
Announce server broken (again)

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing-android#191]
Need to replace `udp4://announce.syncthing.net:22026` with `udp4://*server-ip*:22026` in config.

**Comment by nathan-thenut** [comment]
So that is the reason as to why it won't find the announce server? Can that be fixed sometime soon?

**Comment by AudriusButkevicius** [comment]
You can change the hostname to the IP and it should work.
As for getting it fixed, feel free to chip in and fix it :+1:

**Comment by nathan-thenut** [comment]
Ah. Didn't realize I could manually type in the IP in the Web GUI. Ugh. Sorry. It certainly works this way though... I'll fork it and change the config.

**Comment by AudriusButkevicius** [comment]
The config gets generated by syncthing binary. And apparently syncthing's DNS resolution is broken on Android, so what @Nutomic does, is replaces the hostname with the IP on first start.

You should grep for the announce server hostname and you should find where it happens.

There is another bug which I am not sure if you noticed (and whether or not you want to chip in).
But in case you do, here's how it goes:
The `OK/Not OK` announce server status in the app, we previously used to have a single boolean indicating whether it works or not, but now syncthing binary supports multiple servers, hence it's no longer a boolean but rather a map of <address, bool> values, and the app doesn't seem to handle that. The web UI now shows OK if all bool values are true, or shows N/M where N is the number of ok bools, M is the total lengh of the map.

**Comment by nathan-thenut** [comment]
Ah, so that's why I still had the announce server hostname in the config. 
Looking at the Web UI one does not seem to be able to enter multiple announce servers though or am I wrong?

**Comment by AudriusButkevicius** [comment]
You should be able to by doing space or comma separation.

It could be that you are on an intermediate version which had the format changed, but no support for multiple servers, but even then you should have been able to enter multiple words there.

**Comment by Zillode** [comment]
https://github.com/Zillode/syncthing-android/commit/dec9921c5dec17d8a0558dccfd76498eb429ce01
