### ISSUE TITLE
two android couldn't connect each other in `LAN`

### ISSUE THREAD

**Issue by uiolee** [syncthing/syncthing-android#1911]
two samsung android devices couldn't connect each other in `LAN`.

## what happened

In default setting, disable `global discovery`.
I set windows 10, samsung phone and samsung tablet sync.
three devices in the same wifi, same router.

1. PC can connect two android devices via `local` connection, vice versa. and it works fine.

1. Two android devices could not connect each other via `local`.

<details><summary>android Syncthing, Remote Devices</summary>

![RemoteDevices](https://github.com/syncthing/syncthing-android/assets/22849383/95d6cbdf-837c-4255-a3f3-0350c2e453af)

</details> 

<details><summary>android Syncthing, Discovery Details</summary>

I have turned off IPv6.

![Discovery](https://github.com/syncthing/syncthing-android/assets/22849383/7b1d5190-3b66-4639-a901-03214d937e99)

</details> 

## Expected 

The two android devices should connect fine via `local`, I think this is a normal usage.

## Addtional Information

In `LAN` software `Sync`, `LANdrop`, `Snapdrop`, my devices can connect and work,
so in my humble opinion, the problem might not be caused by the network or device.

## Version Information

    The two android devices in same version.

    App Version: 1.23.4
    Syncthing Version: v1.23.4
    Android Version: Android 13, Samsung One UI 5.1

**Comment by acolomb** [comment]
This is a known problem on recent Android versions. Google blocked access to some network features that are needed for Syncthing's local discovery. The workaround is using the global discovery servers, so just don't disable that and you should be fine.
