### ISSUE TITLE
Fix option to run only when plugged in

### ISSUE THREAD

**Issue by PulsarFX** [syncthing/syncthing-android#1919]
Operating conditions currently has checkboxes to run syncthing 
- when connected to wifi 
- when connected to mobile data 
- when on battery or when charging.

I miss the option to run it in a combined condition, like "run on mobile data AND while charging."
I see this as a bug, as running on battery and on mobile data drains my battery like crazy. 

### Version Information

    App Version: 1.23.5
    Syncthing Version: v1.23.5
    Android Version: Android 12

**Comment by imsodin** [comment]
That's definitely a feature request, thus closing due to current maintenance situation - see: https://github.com/syncthing/syncthing-android#no-feature-request-taken-feature-contributions-case-by-case
