### ISSUE TITLE
Pause for xxx Minutes

### ISSUE THREAD

**Issue by Backi67** [syncthing/syncthing-android#1931]
Sometimes my Tablet is stopping playing Video's when Syncthing is working in Background.

So I Pause to Sync .. But often I forget and wonder why it is not in Sync..

In other applications there is a possibility to pause for xx Minutes...
Maybe you can think about this? (Could also be helpful for other users)

Yours
Stephan

**Comment by imsodin** [comment]
Closing as it is a feature request, see: https://github.com/syncthing/syncthing-android#no-feature-request-taken-feature-contributions-case-by-case
