### ISSUE TITLE
Define space for database other than >1%

### ISSUE THREAD

**Issue by honjarado** [syncthing/syncthing-android#1932]
I might be missing something because on the desktop version it's easy to set min space as whatever you want, but I can't find how to do that on Syncthing for Android.

Lets say that you have a 256GB phone that you only use for apps whose data you value and you are an avid picture/video taker. You use the phone until you get a warning from Android that the sdcard is full and then you proceed to copy the pictures to your computer (so you can remove them from your mobile device) using Syncthing to discover that you have to delete 2.56GB of your precious data before you can use Syncthing.
That's what I am facing each time I use Syncthing. It's completely useless.

How I would workaround it:
- In advance, Syncthing always makes a temp file at least twice as big as the biggest expected database size increase.
- If device storage is full, Syncthing warns user that only device->remote files can be copied, no new files can be copied to the device (i.e. you can copy files out of the phone and then delete them at destination which might delete them at source according to your settings).
- Syncthing then deletes the temp file to make space for database size increases and starts all device->remote copying operations as well as all remote deletions.
- When that's done, folders that have pending remote->device coping operations that can't be done due to insufficient space will show a % of how much is done and a warning that the folder can't proceed syncing due to insufficient space.
- that would allow user to delete/move files from destination and rescan the folder to sync those deletes.

### Version Information

    App Version: 1.23.5
    Syncthing 1.23.4
    Android Version: 5.0

**Comment by imsodin** [comment]
You can use the "Web GUI" to get the same interface as on desktop and change that setting there.

Closing this issue, as adding a control for this in the app is a feature request, see https://github.com/syncthing/syncthing-android#no-feature-request-taken-feature-contributions-case-by-case
