### ISSUE TITLE
Wifi tethering and "Wi-Fi only option"

### ISSUE THREAD

**Issue by derlaft** [syncthing/syncthing-android#194]
Situation:
  * "Use Wi-Fi only" option is checked
  * Device works as router (mobile network is enabled and wifi-router is enabled)

Current behavior:
  * Syncthing disables service

Desired behavior:
  * Syncthing starts service
  * Service doesn't use mobile network
  * Synchronization is available between device and it's wireless clients

**Comment by Nutomic** [comment]
Yeah I'm closing this as wontfix, because I don't see a good way to implement this in the UI (and as I said, it's quite niche).
