### ISSUE TITLE
Hang on start: double-spinner; forever loading

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [syncthing/syncthing-android#1943]
When I run Syncthing 1.23.6, I see a large spinner and text, with its own spinner, saying 'loading'. The double spinners confuse a little. After approximately one minute I see an error message, in dubious English, complete with a link. The link is in an illegible colour. On all this please see attached screenshot.The link is meant to point to a log. The log does not open. Indeed the app will not do anything.

![Screenshot_20230717-174912333](https://github.com/syncthing/syncthing-android/assets/47056543/cc23a6fd-85c0-47a4-930b-55937b385bb7)

My phone: ZenFone 8, running Android 13.

![Screenshot_20230717-174912333](https://github.com/syncthing/syncthing-android/assets/47056543/251c4a38-15d6-4c61-964c-b8e97af10d41)

**Comment by blsz** [comment]
I have exactly the same issue on Pixel 5a, Android 13.  Clearing app cache and restarting the phone has no effect.

**Comment by petcap** [comment]
Same issue here.

I see nothing in the Syncthing logs:
![signal-2023-07-17-195035](https://github.com/syncthing/syncthing-android/assets/8736529/927ce16a-4220-4b52-849d-55fed24cab83)

The Android logs contains more information:
![signal-2023-07-17-195037](https://github.com/syncthing/syncthing-android/assets/8736529/5fa0ae66-9022-4bd4-bfd7-cdf804228dd1)

### Copy of Android logs
`--------- beginning of main
07-17 19:49:35.377 I/ViewRootImpl@44b34c3[MainActivity](19086): MSG_WINDOW_FOCUS_CHANGED 1 0
07-17 19:49:35.377 I/ViewRootImpl@44b34c3[MainActivity](19086): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb4000074aaea7840}
07-17 19:49:36.537 I/ViewRootImpl@44b34c3[MainActivity](19086): ViewPostIme pointer 0
07-17 19:49:36.602 I/ViewRootImpl@44b34c3[MainActivity](19086): ViewPostIme pointer 1
07-17 19:49:36.613 I/MSHandlerLifeCycle(19086): removeMultiSplitHandler: no exist. decor=DecorView@b34dac2[MainActivity]
07-17 19:49:36.615 I/ViewRootImpl@44b34c3[MainActivity](19086): dispatchDetachedFromWindow
07-17 19:49:36.649 I/DecorView(19086): [INFO] isPopOver=false config=true
07-17 19:49:36.650 I/DecorView(19086): updateCaptionType: isFloating=false isApplication=true hasWindowDecorCaption=false this=DecorView@493ff9[]
07-17 19:49:36.650 I/DecorView(19086): getCurrentDensityDpi: from real metrics. densityDpi=450 msg=resources_loaded
07-17 19:49:36.650 I/DecorView(19086): setWindowBackground: isPopOver=false color=ff191c1e d=android.graphics.drawable.ColorDrawable@ff51d9f
07-17 19:49:36.660 I/MSHandlerLifeCycle(19086): check: return. pkg=com.nutomic.syncthingandroid parent=null callers=com.android.internal.policy.DecorView.setVisibility:4416 android.app.ActivityThread.handleResumeActivity:5476 android.app.servertransaction.ResumeActivityItem.execute:54 android.app.servertransaction.ActivityTransactionItem.execute:45 android.app.servertransaction.TransactionExecutor.executeLifecycleState:176 
07-17 19:49:36.660 I/MSHandlerLifeCycle(19086): removeMultiSplitHandler: no exist. decor=DecorView@493ff9[]
07-17 19:49:36.666 I/ViewRootImpl@13c1ec6[LogActivity](19086): setView = com.android.internal.policy.DecorView@493ff9 TM=true
07-17 19:49:36.667 I/MSHandlerLifeCycle(19086): removeMultiSplitHandler: no exist. decor=DecorView@493ff9[LogActivity]
07-17 19:49:36.672 I/ViewRootImpl@13c1ec6[LogActivity](19086): performTraversals params={(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030309
07-17 19:49:36.672 I/ViewRootImpl@13c1ec6[LogActivity](19086):   fl=81810100
07-17 19:49:36.672 I/ViewRootImpl@13c1ec6[LogActivity](19086):   pfl=12020040
07-17 19:49:36.672 I/ViewRootImpl@13c1ec6[LogActivity](19086):   bhv=DEFAULT
07-17 19:49:36.672 I/ViewRootImpl@13c1ec6[LogActivity](19086):   fitSides= naviIconColor=0}
07-17 19:49:36.672 I/ViewRootImpl@13c1ec6[LogActivity](19086): performTraversals mFirst=true windowShouldResize=true viewVisibilityChanged=false mForceNextWindowRelayout=false params={(0,0)(fillxfill) sim={adjust=resize forwardNavigation} ty=BASE_APPLICATION wanim=0x1030309
07-17 19:49:36.672 I/ViewRootImpl@13c1ec6[LogActivity](19086):   fl=81810100
07-17 19:49:36.672 I/ViewRootImpl@13c1ec6[LogActivity](19086):   pfl=12020040
07-17 19:49:36.672 I/ViewRootImpl@13c1ec6[LogActivity](19086):   bhv=DEFAULT
07-17 19:49:36.672 I/ViewRootImpl@13c1ec6[LogActivity](19086):   fitSides= naviIconColor=0}
07-17 19:49:36.680 I/ViewRootImpl@13c1ec6[LogActivity](19086): updateBlastSurfaceIfNeeded mBlastBufferQueue=null isSameSurfaceControl=false
07-17 19:49:36.681 I/BLASTBufferQueue(19086): new BLASTBufferQueue, mName= ViewRootImpl@13c1ec6[LogActivity] mNativeObject= 0xb40000741ae8ba30 sc.mNativeObject= 0xb4000073aae963e0 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2909 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 android.view.Choreographer$CallbackRecord.run:1309 android.view.Choreographer.doCallbacks:923 android.view.Choreographer.doFrame:852 android.view.Choreographer$FrameDisplayEventReceiver.run:1283 
07-17 19:49:36.681 I/BLASTBufferQueue(19086): update, w= 1080 h= 2340 mName = ViewRootImpl@13c1ec6[LogActivity] mNativeObject= 0xb40000741ae8ba30 sc.mNativeObject= 0xb4000073aae963e0 format= -1 caller= android.graphics.BLASTBufferQueue.<init>:84 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2909 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 
07-17 19:49:36.681 I/ViewRootImpl@13c1ec6[LogActivity](19086): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=8 res=0x3 s={true 0xb4000074aaee0ff0} ch=true seqId=0
07-17 19:49:36.682 I/ViewRootImpl@13c1ec6[LogActivity](19086): mThreadedRenderer.initialize() mSurface={isValid=true 0xb4000074aaee0ff0} hwInitialized=true
07-17 19:49:36.683 I/ViewRootImpl@13c1ec6[LogActivity](19086): reportNextDraw android.view.ViewRootImpl.performTraversals:4438 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 android.view.Choreographer$CallbackRecord.run:1309 
07-17 19:49:36.684 I/ViewRootImpl@13c1ec6[LogActivity](19086): Setup new sync id=0
07-17 19:49:36.684 I/ViewRootImpl@13c1ec6[LogActivity](19086): Setting syncFrameCallback
07-17 19:49:36.684 I/ViewRootImpl@13c1ec6[LogActivity](19086): registerCallbacksForSync syncBuffer=false
07-17 19:49:36.686 I/ViewRootImpl@13c1ec6[LogActivity](19086): Received frameDrawingCallback syncResult=0 frameNum=1.
07-17 19:49:36.686 I/ViewRootImpl@13c1ec6[LogActivity](19086): Setting up sync and frameCommitCallback
07-17 19:49:36.688 I/BLASTBufferQueue(19086): [ViewRootImpl@13c1ec6[LogActivity]#5](f:0,a:0) onFrameAvailable the first frame is available
07-17 19:49:36.689 I/ViewRootImpl@13c1ec6[LogActivity](19086): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
07-17 19:49:36.691 I/ViewRootImpl@13c1ec6[LogActivity](19086): onSyncComplete
07-17 19:49:36.691 I/ViewRootImpl@13c1ec6[LogActivity](19086): setupSync seqId=0 mSyncId=0 fn=1 caller=android.view.ViewRootImpl$$ExternalSyntheticLambda11.accept:6 android.window.SurfaceSyncer.lambda$setupSync$1$android-window-SurfaceSyncer:128 android.window.SurfaceSyncer$$ExternalSyntheticLambda1.accept:8 android.window.SurfaceSyncer$SyncSet.checkIfSyncIsComplete:382 android.window.SurfaceSyncer$SyncSet.markSyncReady:359 android.window.SurfaceSyncer.markSyncReady:151 android.view.ViewRootImpl.performTraversals:4503 
07-17 19:49:36.691 I/ViewRootImpl@13c1ec6[LogActivity](19086): reportDrawFinished seqId=0 mSyncId=-1 fn=1 mSurfaceChangedTransaction=0xb4000073dae82230
07-17 19:49:36.737 I/ViewRootImpl@968b4dc[MainActivity](19086): handleAppVisibility mAppVisible = true visible = false
07-17 19:49:36.755 I/ViewRootImpl@968b4dc[MainActivity](19086): performTraversals mFirst=false windowShouldResize=false viewVisibilityChanged=true mForceNextWindowRelayout=false params=null
07-17 19:49:36.762 I/ViewRootImpl@968b4dc[MainActivity](19086): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)8 dur=7 res=0x2 s={false 0x0} ch=true seqId=0
07-17 19:49:36.763 I/ViewRootImpl@968b4dc[MainActivity](19086): stopped(true) old = false
07-17 19:49:36.763 I/ViewRootImpl@968b4dc[MainActivity](19086): WindowStopped on com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.MainActivity set to true
07-17 19:49:36.764 I/MSHandlerLifeCycle(19086): removeMultiSplitHandler: no exist. decor=DecorView@4741aa[MainActivity]
07-17 19:49:36.764 I/ViewRootImpl@13c1ec6[LogActivity](19086): MSG_WINDOW_FOCUS_CHANGED 1 0
07-17 19:49:36.764 I/ViewRootImpl@13c1ec6[LogActivity](19086): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb4000074aaee0ff0}
07-17 19:49:36.764 I/InputMethodManager(19086): startInputInner - mService.startInputOrWindowGainedFocus
07-17 19:49:40.322 I/ViewRootImpl@13c1ec6[LogActivity](19086): MSG_WINDOW_FOCUS_CHANGED 0 0
07-17 19:49:41.726 I/ViewRootImpl@13c1ec6[LogActivity](19086): MSG_WINDOW_FOCUS_CHANGED 1 0
07-17 19:49:41.726 I/ViewRootImpl@13c1ec6[LogActivity](19086): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb4000074aaee0ff0}
07-17 19:49:41.727 I/InputMethodManager(19086): startInputInner - mService.startInputOrWindowGainedFocus
07-17 19:49:42.156 I/ViewRootImpl@13c1ec6[LogActivity](19086): ViewPostIme pointer 0
07-17 19:49:42.162 I/ViewRootImpl@13c1ec6[LogActivity](19086): ViewPostIme pointer 1
07-17 19:49:42.198 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): setView = android.widget.PopupWindow$PopupDecorView@9861c54 TM=true
07-17 19:49:42.205 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): performTraversals params={(518,92)(551x314) gr=TOP START CENTER DISPLAY_CLIP_VERTICAL sim={state=unchanged adjust=resize} ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT surfaceInsets=Rect(17, 17 - 17, 17) (manual)
07-17 19:49:42.205 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   fl=41860200
07-17 19:49:42.205 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   pfl=2018000
07-17 19:49:42.205 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   bhv=DEFAULT
07-17 19:49:42.205 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR naviIconColor=0
07-17 19:49:42.205 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   sfl=20000}
07-17 19:49:42.205 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): performTraversals mFirst=true windowShouldResize=true viewVisibilityChanged=false mForceNextWindowRelayout=false params={(518,92)(551x314) gr=TOP START CENTER DISPLAY_CLIP_VERTICAL sim={state=unchanged adjust=resize} ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT surfaceInsets=Rect(17, 17 - 17, 17) (manual)
07-17 19:49:42.205 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   fl=41860200
07-17 19:49:42.205 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   pfl=2018000
07-17 19:49:42.205 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   bhv=DEFAULT
07-17 19:49:42.205 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR IME naviIconColor=0
07-17 19:49:42.205 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   sfl=20000}
07-17 19:49:42.212 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): Resizing android.view.ViewRootImpl@7b3d7fd: frame = [518,92][1069,406] reportDraw = true forceLayout = false syncSeqId = 0
07-17 19:49:42.215 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): updateBlastSurfaceIfNeeded mBlastBufferQueue=null isSameSurfaceControl=false
07-17 19:49:42.215 I/BLASTBufferQueue(19086): new BLASTBufferQueue, mName= ViewRootImpl@34dcda8[PopupWindow:45b01cb] mNativeObject= 0xb40000741ae68490 sc.mNativeObject= 0xb4000073aae95fc0 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2909 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 android.view.Choreographer$CallbackRecord.run:1309 android.view.Choreographer.doCallbacks:923 android.view.Choreographer.doFrame:852 android.view.Choreographer$FrameDisplayEventReceiver.run:1283 
07-17 19:49:42.215 I/BLASTBufferQueue(19086): update, w= 585 h= 348 mName = ViewRootImpl@34dcda8[PopupWindow:45b01cb] mNativeObject= 0xb40000741ae68490 sc.mNativeObject= 0xb4000073aae95fc0 format= -3 caller= android.graphics.BLASTBufferQueue.<init>:84 android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2909 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 
07-17 19:49:42.216 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): Relayout returned: old=(518,92,1069,92) new=(518,92,1069,406) req=(551,314)0 dur=10 res=0x3 s={true 0xb4000074aaee7620} ch=true seqId=0
07-17 19:49:42.217 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): mThreadedRenderer.initialize() mSurface={isValid=true 0xb4000074aaee7620} hwInitialized=true
07-17 19:49:42.223 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): reportNextDraw android.view.ViewRootImpl.performTraversals:4438 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 android.view.Choreographer$CallbackRecord.run:1309 
07-17 19:49:42.224 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): Setup new sync id=0
07-17 19:49:42.224 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): Setting syncFrameCallback
07-17 19:49:42.225 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): registerCallbacksForSync syncBuffer=false
07-17 19:49:42.225 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): Received frameDrawingCallback syncResult=0 frameNum=1.
07-17 19:49:42.225 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): Setting up sync and frameCommitCallback
07-17 19:49:42.230 I/BLASTBufferQueue(19086): [ViewRootImpl@34dcda8[PopupWindow:45b01cb]#6](f:0,a:0) onFrameAvailable the first frame is available
07-17 19:49:42.230 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): Received frameCommittedCallback lastAttemptedDrawFrameNum=1 didProduceBuffer=true
07-17 19:49:42.236 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): onSyncComplete
07-17 19:49:42.237 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): setupSync seqId=0 mSyncId=0 fn=1 caller=android.view.ViewRootImpl$$ExternalSyntheticLambda11.accept:6 android.window.SurfaceSyncer.lambda$setupSync$1$android-window-SurfaceSyncer:128 android.window.SurfaceSyncer$$ExternalSyntheticLambda1.accept:8 android.window.SurfaceSyncer$SyncSet.checkIfSyncIsComplete:382 android.window.SurfaceSyncer$SyncSet.markSyncReady:359 android.window.SurfaceSyncer.markSyncReady:151 android.view.ViewRootImpl.performTraversals:4503 
07-17 19:49:42.237 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): reportDrawFinished seqId=0 mSyncId=-1 fn=1 mSurfaceChangedTransaction=0xb4000073dae61cb0
07-17 19:49:42.238 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): handleResized, msg = 5 frames=ClientWindowFrames{frame=[518,92][1069,406] display=[-100000,-100000][100000,100000] parentFrame=[0,0][0,0] parentClippedByDisplayCutout=false} forceNextWindowRelayout=false displayId=0 resizeMode=-1 frameChanged=false displayFrameChanged=false configChanged=false displayChanged=false
07-17 19:49:42.238 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): handleResized mSyncSeqId = 0
07-17 19:49:42.238 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): reportNextDraw android.view.ViewRootImpl.handleResized:2450 android.view.ViewRootImpl.-$$Nest$mhandleResized:0 android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl:6728 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6697 android.os.Handler.dispatchMessage:106 
07-17 19:49:42.238 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): Setup new sync id=1
07-17 19:49:42.239 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): Setting syncFrameCallback
07-17 19:49:42.239 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): registerCallbacksForSync syncBuffer=false
07-17 19:49:42.240 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): Received frameDrawingCallback syncResult=0 frameNum=2.
07-17 19:49:42.240 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): Setting up sync and frameCommitCallback
07-17 19:49:42.242 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): Received frameCommittedCallback lastAttemptedDrawFrameNum=2 didProduceBuffer=true
07-17 19:49:42.242 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): onSyncComplete
07-17 19:49:42.243 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): setupSync seqId=0 mSyncId=1 fn=2 caller=android.view.ViewRootImpl$$ExternalSyntheticLambda11.accept:6 android.window.SurfaceSyncer.lambda$setupSync$1$android-window-SurfaceSyncer:128 android.window.SurfaceSyncer$$ExternalSyntheticLambda1.accept:8 android.window.SurfaceSyncer$SyncSet.checkIfSyncIsComplete:382 android.window.SurfaceSyncer$SyncSet.markSyncReady:359 android.window.SurfaceSyncer.markSyncReady:151 android.view.ViewRootImpl.performTraversals:4503 
07-17 19:49:42.243 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): reportDrawFinished seqId=0 mSyncId=-1 fn=2 mSurfaceChangedTransaction=0xb4000073dae61cb0
07-17 19:49:42.253 I/ViewRootImpl@13c1ec6[LogActivity](19086): MSG_WINDOW_FOCUS_CHANGED 0 0
07-17 19:49:42.271 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): MSG_WINDOW_FOCUS_CHANGED 1 0
07-17 19:49:42.271 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): mThreadedRenderer.initializeIfNeeded()#2 mSurface={isValid=true 0xb4000074aaee7620}
07-17 19:49:43.021 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): ViewPostIme pointer 0
07-17 19:49:43.085 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): ViewPostIme pointer 1
07-17 19:49:43.154 I/DecorView(19086): notifyKeepScreenOnChanged: keepScreenOn=false
07-17 19:49:43.156 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): performTraversals params={(518,92)(551x314) gr=TOP START CENTER DISPLAY_CLIP_VERTICAL sim={state=unchanged adjust=pan} ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT surfaceInsets=Rect(17, 17 - 17, 17) (manual)
07-17 19:49:43.156 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   fl=41840218
07-17 19:49:43.156 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   pfl=2018000
07-17 19:49:43.156 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   bhv=DEFAULT
07-17 19:49:43.156 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR naviIconColor=0
07-17 19:49:43.156 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   sfl=20000}
07-17 19:49:43.157 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): performTraversals mFirst=false windowShouldResize=false viewVisibilityChanged=false mForceNextWindowRelayout=false params={(518,92)(551x314) gr=TOP START CENTER DISPLAY_CLIP_VERTICAL sim={state=unchanged adjust=pan} ty=APPLICATION_SUB_PANEL fmt=TRANSLUCENT surfaceInsets=Rect(17, 17 - 17, 17) (manual)
07-17 19:49:43.157 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   fl=41840218
07-17 19:49:43.157 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   pfl=42018000
07-17 19:49:43.157 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   bhv=DEFAULT
07-17 19:49:43.157 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR naviIconColor=0
07-17 19:49:43.157 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086):   sfl=20000}
07-17 19:49:43.169 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): updateBlastSurfaceIfNeeded mBlastBufferQueue=0xb40000741ae68490 isSameSurfaceControl=true
07-17 19:49:43.170 I/BLASTBufferQueue(19086): update, w= 585 h= 348 mName = ViewRootImpl@34dcda8[PopupWindow:45b01cb] mNativeObject= 0xb40000741ae68490 sc.mNativeObject= 0xb4000073aae910b0 format= -3 caller= android.view.ViewRootImpl.updateBlastSurfaceIfNeeded:2898 android.view.ViewRootImpl.relayoutWindow:9847 android.view.ViewRootImpl.performTraversals:3884 android.view.ViewRootImpl.doTraversal:3116 android.view.ViewRootImpl$TraversalRunnable.run:10885 android.view.Choreographer$CallbackRecord.run:1301 
07-17 19:49:43.170 I/ViewRootImpl@34dcda8[PopupWindow:45b01cb](19086): Relayout returned: old=(518,92,1069,406) new=(518,92,1069,406) req=(551,314)0 dur=12 res=0x0 s={true 0xb4000074aaee7620} ch=false seqId=0
07-17 19:49:43.173 I/ViewRootImpl@13c1ec6[LogActivity](19086): performTraversals params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030309
07-17 19:49:43.173 I/ViewRootImpl@13c1ec6[LogActivity](19086):   fl=81810100
07-17 19:49:43.173 I/ViewRootImpl@13c1ec6[LogActivity](19086):   pfl=12020040
07-17 19:49:43.173 I/ViewRootImpl@13c1ec6[LogActivity](19086):   bhv=DEFAULT
07-17 19:49:43.173 I/ViewRootImpl@13c1ec6[LogActivity](19086):   fitSides= naviIconColor=0}
07-17 19:49:43.175 I/ViewRootImpl@13c1ec6[LogActivity](19086): performTraversals mFirst=false windowShouldResize=false viewVisibilityChanged=false mForceNextWindowRelayout=false params={(0,0)(fillxfill) sim={adjust=resize} ty=BASE_APPLICATION wanim=0x1030309
07-17 19:49:43.175 I/ViewRootImpl@13c1ec6[LogActivity](19086):   fl=81810100
07-17 19:49:43.175 I/ViewRootImpl@13c1ec6[LogActivity](19086):   pfl=12020040
07-17 19:49:43.175 I/ViewRootImpl@13c1ec6[LogActivity](19086):   bhv=DEFAULT
07-17 19:49:43.175 I/ViewRootImpl@13c1ec6[LogActivity](19086):   fitSides= naviIconColor=0}
`

**Comment by imsodin** [comment]
Awesome, looks like the new shiny AAB forced by google play on me didn't work out as it should have. And I'll likely not be able to revert this, as it doesn't allow me to publish apks anymore...  
You might be able to get back into a working state by manually installing the old APK (or of course move to f-droid, but I guess that's not an option).

**Comment by imsodin** [comment]
Ah, enabling legacy behaviour for the win - I'll release a fix soon (hopefully a fix - no guarantee that just because it works locally it also does through the google play blackbox (yes I am (maybe not very rationally) ranting about google play here, it's just been too annoying recently).

**Comment by chris6125** [comment]
I am also experiencing the same issues with the new Syncthing update (1.23.6). I tried uninstalling and reinstalling after encountering the hang on start with double spinners, but now Syncthing will no longer start (as @blsz has experienced). I'm on a Pixel 6 running Graphene OS.

**Comment by imsodin** [comment]
No need for further updates - 1.23.6.1 will soon-ish become available and should fix the issue. If it persists after the upgrade, please report again.

**Comment by mexsudo** [comment]
android syncthing log:
--------- beginning of system
07-17 11:57:49.052 I/Quality (24835): JankCountInfo: com.nutomic.syncthingandroid.activities.LogActivity basic:0-0-0 action:-1 data:0-2 action:1 data:0-1 action:2 data:0-10 action:8 data:0-7 action:10 data:0-0 type:5 stage:1-0-0 action:13 data:0-0 type:2 stage:6-0-0
07-17 11:57:54.932 I/Quality (24835): JankCountInfo: com.nutomic.syncthingandroid.activities.LogActivity basic:0-0-0 action:2 data:0-11 action:6 data:0-2 action:8 data:0-12 action:10 data:0-0 type:5 stage:0-0-0 action:13 data:0-0 type:2 stage:0-0-0
--------- beginning of main
07-17 11:57:56.928 I/oplus.android.OplusFrameworkFactoryImpl(24835): get feature:IOplusDynamicVsyncFeature
07-17 11:57:56.928 I/oplus.android.OplusFrameworkFactoryImpl(24835): get feature:IOplusDynamicVsyncFeature
07-17 11:57:56.928 I/oplus.android.OplusFrameworkFactoryImpl(24835): get feature:IOplusDynamicVsyncFeature
07-17 11:57:56.944 I/Quality (24835): Skipped: false 0 cost 7.187812 refreshRate 8291126 bit true processName com.nutomic.syncthingandroid
07-17 11:57:57.138 E/FrameEvents(24835): addLatch: Did not find frame.
07-17 11:57:57.138 E/FrameEvents(24835): addRelease: Did not find frame.
07-17 11:57:57.138 E/FrameEvents(24835): addPreComposition: Did not find frame.
07-17 11:57:57.138 E/FrameEvents(24835): addPostComposition: Did not find frame.
07-17 11:58:06.470 I/oplus.android.OplusFrameworkFactoryImpl(24835): get feature:IOplusDynamicVsyncFeature
07-17 11:58:06.470 I/oplus.android.OplusFrameworkFactoryImpl(24835): get feature:IOplusDynamicVsyncFeature
07-17 11:58:06.470 I/oplus.android.OplusFrameworkFactoryImpl(24835): get feature:IOplusDynamicVsyncFeature

**Comment by imsodin** [comment]
This is not a general purpose "things arent working" issue - locked the ticket. If you have any questions, please search teh forum -- https://forum.syncthing.net/ -- and start a new topic if needed.

Of course if any clear/major issue arises/is still there in the new release, feel free to open a new ticket.
