### ISSUE TITLE
[Feature Request] Automatic Export

### ISSUE THREAD

**Issue by j0hann3s** [syncthing/syncthing-android#1946]
**Feature description**
The **Settings->Backup** menu should have an option to make automatic exports of my configuration. This can only be done manually right now. This feature should trigger any set time of day/set time of delay. One should be able to dictate the path where the export should be placed and replace the current export, if one exists already.

**Why do you want this feature?**
I request this feature to be able to recover from a crashed, stolen or lost phone (where one does not keep post-it notes reminding one to backup daily like a chore). This makes it possible to have peace of mind when using this service exclusively and not rely on backup solutions that require root access on ones phone (TitaniumBackup and the likes...) to backup the keys and settings.

**Additional information**
I am not a skilled Android developer which is why I am not able to implement this on my own via a PR, unfortunately.

**Comment by imsodin** [comment]
This project isn't accepting any feature requests - see https://github.com/syncthing/syncthing-android#status-maintenance-mode---co-maintainers-welcome
