### ISSUE TITLE
Android will not Add Device.

### ISSUE THREAD

**Issue by mexsudo** [syncthing/syncthing-android#1947]

**Comment by tomasz1986** [comment]
Likely related:

https://forum.syncthing.net/t/i-cannot-add-second-device-on-android/20544
https://forum.syncthing.net/t/adding-device-from-android/20538

**Comment by blsz** [comment]
Try tapping the empty white space at the top right of the screen or switch to the dark theme.  There is an invisible "+" icon that is not visible.  Version 1.23.6.3 seems to have changed the UI framework and has white icons on white backgrounds in several views in the app.  Add Folder and Delete Folder icons are similarly affected.

**Comment by mexsudo** [comment]
> 

that does work
