### ISSUE TITLE
Serious GUI bug

### ISSUE THREAD

**Issue by Pr0pHesyer** [syncthing/syncthing-android#1948]
The Nav bar become white but the operation icon of secondary menu is still white,the icon emerge into the Nav Bar so that could not found. 

Enter any Device/Folder menu,there looks like no icon actually just because the Nav Bar and the icons all are white.

The Nav Bar should go back to the original color or change the color of the icon .

https://github.com/syncthing/syncthing-android/assets/74277431/4c25f169-2855-4b4d-894c-76a890d6fdef
![Screenshot_20230720-183346](https://github.com/syncthing/syncthing-android/assets/74277431/bf5f4dfe-bb16-428f-b80e-62cb970fc710)

### Version Information

    App Version: 1.23.6.3
    Syncthing Version: v1.23.6
    Android Version: Android 12L

**Comment by tomasz1986** [comment]
Looks like a duplicate of https://github.com/syncthing/syncthing-android/issues/1947, however it does provide a little more context.

**Comment by Pr0pHesyer** [comment]
> Looks like a duplicate of #1947, however it does provide a little more context.

Yes
