### ISSUE TITLE
[request] Native Ignore Patterns support without needing 3rd party editor

### ISSUE THREAD

**Issue by garylkz** [syncthing/syncthing-android#1951]
It'd be nice to allow user to directly edit the ignore patterns in the app instead of redirecting user to 3rd party editor (yes, I don't have one). It could be implemented in textarea or something. 

It would be way better than getting into web gui, editing the ignore patterns, then get out.

**Comment by imsodin** [comment]
This project isn't accepting feature requests - see https://github.com/syncthing/syncthing-android#status-maintenance-mode---co-maintainers-welcome
