### ISSUE TITLE
Create / edit folder - the tick / ok button is virtually invisible / same color as background

### ISSUE THREAD

**Issue by tomwaldnz** [syncthing/syncthing-android#1952]
On my Pixel 4a (completely up to date) and my wife's Samsung S22 (completely up to date) the tick at the top right of the add folder / edit folder screen is white on white, and is therefore virtually invisible. If you look _really_ carefully you can just see it. I've done some image manipulation, with enough mucking around you can make it visible. I've two screenshots below, the original and the processed to show the difference.

### Version Information

    App Version: 1.23.6.3 (installed from Google Play)
    Syncthing Version: v1.23.6
    Android Version: Android 13 (Pixel 4a Android security update June 1 2023)

**Steps to reproduce**

Run Syncthing on Android
Hit the + button top right hand corner of the screen
 - or click on any existing folder

**Expected**
There should be an easily visible tick at the top right corner of the screen to confirm creation / editing of a folder

**Actual**
The tick is there, but it's white on white so it's extremely difficult to see.

 **Original Screenshot**
![original](https://github.com/syncthing/syncthing-android/assets/8381145/ceed9b8e-528a-4aa4-a483-dbfb30ad3aee)

**Processed Image**
I went through multiple rounds of changing exposure / contrast / etc to make the tick visible
![processed](https://github.com/syncthing/syncthing-android/assets/8381145/22f5565a-db6f-46a3-8eec-e5f9d541630b)

**Comment by AudriusButkevicius** [comment]
Dup of #1950
