### ISSUE TITLE
V 1.23.6 and 1.23.6.3 Lose Blue Title Colour in Light Theme

### ISSUE THREAD

**Issue by ProperBrgdbald** [syncthing/syncthing-android#1959]
When I upgraded devices to Syncthing v1.23.6.3, the pleasant blue colour that matches the Syncthing logo in the Light theme is replaced by white. Screenshots are shown here:
![Syncthing_v1-23-5_20230812-144429](https://github.com/syncthing/syncthing-android/assets/64764903/62d73029-e794-428d-9739-d988821f2cd3)
![Syncthing_v1-23-5_20230812-144433](https://github.com/syncthing/syncthing-android/assets/64764903/02759c13-8bf1-4c52-a383-3640e80dad8e)
![Syncthing_v1-23-6_20230812-144650](https://github.com/syncthing/syncthing-android/assets/64764903/6104cdca-7cc8-4e75-b129-63d43dd73ee7)
![Syncthing_v1-23-6_20230812-144653](https://github.com/syncthing/syncthing-android/assets/64764903/4db8f584-f029-4773-bafc-96d20960e2da)

Additional testing shows the issue appears in v1.23.6.

I expected the theme to remain the same between v1.23.y versions.

Upgrading to or installing v1.23.6 or 1.23.6.3 cause this colour to be removed.

### Version Information

    App Version: v1.23.6 (4353) and v1.23.6.3 (4357)
    Syncthing Version: v1.23.6 and 1.23.6.3
    Android Version: Android 7.1.2 / Android 10 / Android 11 / LineageOS 14.1 / LineageOS 17.1

**Comment by uok** [comment]
Thanks for reporting! On my phone the Android status bar (time, battery, ...) at the top is invisible, because after upgrade it is white text on white background

**Comment by imsodin** [comment]
That would be a different thing, if you are already on 1.23.7 and still have the white on white issue, please report a separate issue (there were some fixes for that in that update).

I agree the blue looked nicer - afaik the new way basically removed all/most custom theming and uses system wide accent colors (which is no accent I guess by default).  
@Bnyro If you have time and inclination, could you check out if the "blue (by default)" color there could be restored with the new theming?

**Comment by Bnyro** [comment]
We could only do that programmatically by checking if Material You colours can be used, and if they're not available, manually set the top app bar background and text color as well as the top bar color.
Unfortunately, I don't think we can restore that behavior via XML without breaking the top bar with Material You (since we changed that top bar colors just because there have been issues with the old colors).

**Comment by imsodin** [comment]
If it's doable from code in a reasonable way, I personally would welcome that. Another white-on-white issue that @uok mentioned above and now reported at https://github.com/syncthing/syncthing-android/issues/1963 seems more important though.

**Comment by Bnyro** [comment]
> If it's doable from code in a reasonable way, I personally would welcome that. Another white-on-white issue that @uok mentioned above and now reported at #1963 seems more important though.
>
I'll look into the status bar thing - however I don't really want to work on that blue color top bar thing because that code will get really messy, and I'm not a fan of setting UI things programmatically.

**Comment by imsodin** [comment]
Closing this as it's basically a feature request for other theming at this point (invisibility issues have been dealt with, hopefully all of them by now): https://github.com/syncthing/syncthing-android#no-feature-request-taken-feature-contributions-case-by-case

**Comment by ProperBrgdbald** [comment]
I have the preference of being able to distinguish one application from another easily. The title colour enabled easy distinction. It seems like other applications are subject to turning to black text on white background, which makes everything look too similar.

While I don't think a white title colour is acceptable, I accept that it can be considered a feature request. Maybe I can see if I can contribute to solve this later, based on the notes above. I agree that #1963 was more important and it appears fixed which is good.
