### ISSUE TITLE
Settings | Syncthing Options | Restart on Wakeup

### ISSUE THREAD

**Issue by businessBoris** [syncthing/syncthing-android#1961]
This option apparently defaults to true, but as long as I've used Syncthing it has never stayed checked when I have explicitly checked it, and has never been checked, as is the default, on a new installation or when I've returned to this page after checking this box on.

Please indicate that it is on by marking the option checked, if it on or unchecked If it is off.

The reason for logging this issue is that I am not convinced that it is ever on, or it is switched off as you leave this page..

If your issue is a bug report, replace this boilerplate with a description of the problem, being sure to include at least:

Restate:
* What happened:  checkbix off always when you open this settings page item whether you check the box before leaving or not. Sb checked as the default is on.
* What you expected to happen instead:
-  the checkbox defaults to on and is checkmarked on when it is on.
- please confirm that this option does what it says; restarts Syncthing when the mobile is woken.
* any steps to reproduce the problem.: Observe that the checkbox is never checked regardless of manual attempts to check when returning to that options page.
 - unable to confirm that the Syncthing is restarted when the mobile is allowed to time out and awoken.

### Version Information

    App Version: 1.23.7
    Syncthing Version: 1.23.7
    Android Version: Android 13. Security update 5 August 23 
Kernel 5.10.157-android13-4-00003-g776d0a76f6aa-ab10208116
#1 Thu May 25 12:11:12 UTC 2023

**Comment by businessBoris** [comment]
I have a sync between two devices which takes a perceivable time to scan. The scans don't seem to start on Wakeup as they should do with the default.

**Comment by tomasz1986** [comment]
> * please confirm that this option does what it says; restarts Syncthing when the mobile is woken.

I can't test this right now but I think this option may be "dead". There used to be a setting in Syncthing itself that restarts the program on resume from sleep (on any OS), however it was removed in https://github.com/syncthing/syncthing/issues/8448.

It should probably be removed from the Android app as well, and also from the Docs (see https://docs.syncthing.net/search.html?q=restartonwakeup).

**Comment by businessBoris** [comment]
Thanks @tomasz1986 . That may explain why I can't get it to work or 'set' it!
