### ISSUE TITLE
Notifications not working in 1.25.0-rc.1.1

### ISSUE THREAD

**Issue by schlamar** [syncthing/syncthing-android#1976]
After updating to 1.25.0-rc.1.1, I'm no longer getting a notification from Syncthing. Looks like notifications are completely disabled for the application, as there is no configuration setting for notifications in Android App-Info for Syncthing (Settings -> Apps -> Syncthing). Other apps has a notification setting above Permissions in App-Info. This section is completely missing for Syncthing.

Could be a regression from #1972

### Version Information

    App Version: 1.25.0-rc.1.1
    Syncthing Version: v1.25.0-rc.1
    Android Version: 13

**Comment by imsodin** [comment]
Thanks for reporting this, especially during beta!

Seems like some new permission we need to specify/ask for: https://developer.android.com/develop/ui/views/notifications/notification-permission

Lovely how they mention notification behaviour changes in the android 13 change guide, but fail to mention that this permission is new...

**Comment by githubashutoshsoni** [comment]
Sure, I'm willing to take this up. @schlamar can you assign this to me?

**Comment by imsodin** [comment]
No need just sending a pr is fine and would be much appreciated.

**Comment by githubashutoshsoni** [comment]
Great, @imsodin. I think I've added this and tested in android 13.  Can you please verify?

**Comment by githubashutoshsoni** [comment]
#1983 mostly fixes this issue with notification.
