### ISSUE TITLE
Obsidian notes modified on Android sometimes not updated to desktop

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [syncthing/syncthing-android#1987]
I've googled for a while, and I'm not sure what to make of this, whether anyone else has had this issue, or what might be the cause. Android filesystem? Permissions? Ugh, help me out here!

![alt text](https://i.imgur.com/Hzb9XOI.png)

I have a desktop and two Android phones - one phone is always turned on at home, in order to sync stuff when either my desktop or real phone might be turned off. I set it up as a sort of "server", mainly just to avoid syncthing conflicts.

However, it still didn't help with this - if I've modified a markdown/Obsidian file on Android, sometimes it doesn't get updated on desktop, until I modify it on android again later.

I *think* this might be happening because the file was modified while my desktop was off, and after turning my desktop on, the file would need yet another modification from Android in order for the desktop recognize it.

However, since I have an always-on phone "server", shouldn't it have detected the changes while the desktop was off? I'll have to check since I'm not sure whether:
- such files gets updated between the two android phones, but are ignored by desktop
- such files are ignored by both the desktop and the always-on phone 

The two times I noticed this happening, I tried restarting syncthing on all the devices, but this didn't register/rescan the changed files.

I'll also have to check whether making a change to the outdated unsynced desktop file would overwrite the phone file. Illustrating that might be easier than explaining:

![alt text](https://i.imgur.com/jdevw7E.png)

If this does happen, I hope I haven't lost any Obsidian information because of it yet.  

### Version Information

    App Version: v1.23.6
    Syncthing Version: v1.23.6 (Android) v1.25.0 (Windows)
    Android Version: LineageOS 18.1, rooted with Magisk

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!

**Comment by iFUCKINGHATEcomputers** [comment]
Made a thread there:
https://forum.syncthing.net/t/obsidian-notes-modified-on-android-sometimes-not-updated-to-desktop-and-can-get-destructively-overwritten/21350
