### ISSUE TITLE
Device appears to be disconnected from other devices, but reconnects when the app is open

### ISSUE THREAD

**Issue by o-alquimista** [syncthing/syncthing-android#1994]
Sometimes device appears disconnected from other devices, but reconnects as soon as I open the app. The persistent notification says it's online the whole time. This feels like some power saving issue, like Android is halting the process after a while.

This happens more often when roaming wifi APs.

### Version Information
    App Version: 1.23.7
    Syncthing Version: 1.23.7
    Android Version: Android 12
    Device: Nokia 5.4 (arm64)

**Comment by imsodin** [comment]
Android killing the app is a known problem. We prompt you to disable battery optimisation, beyond that there's nothing (that I know of) that we could do here. To try to get info/help on any workarounds or more info on the situation on your device/OS version, please use the forum - https://forum.syncthing.net/ - first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
