### ISSUE TITLE
app crashes immediately after start

### ISSUE THREAD

**Issue by valentin-mu** [syncthing/syncthing-android#201]
app version: 0.5.13
android version: 4.2.2
device: philips xenium w6500
installed via google play.

will provide any additional data, if necessary.

**Comment by AudriusButkevicius** [comment]
Please provide logs, or logcat output

**Comment by valentin-mu** [comment]
here is what i could get:

PHONE SPECS:
Device model: W6500
Firmware version: 4.2.2
Kernel version: 3.4.5
builder@server) )
#1 SMP PREEMPT Wed Dec 18 15:51:28 CST 2013
Build number: W6500_M6589A_1351_00_V25A_RU

CRASH LOG:
--------- beginning of /dev/log/main
01-06 22:53:51.235 D/dalvikvm(31677): zygote get new systemTid : 31677
01-06 22:53:51.236 D/dalvikvm(31677): threadid=2: interp stack at 0x5a51e000
01-06 22:53:51.240 D/dalvikvm(31677): threadid=3: interp stack at 0x5a626000
01-06 22:53:51.240 D/dalvikvm(31677): Elevating priority from 0 to -8
01-06 22:53:51.240 D/dalvikvm(31677): threadid=4: interp stack at 0x5a72e000
01-06 22:53:51.241 D/dalvikvm(31677): zygote get thread init done
01-06 22:53:51.241 D/dalvikvm(31677): create interp thread : stack size=32KB
01-06 22:53:51.241 D/dalvikvm(31677): create new thread
01-06 22:53:51.241 D/dalvikvm(31677): new thread created
01-06 22:53:51.241 D/dalvikvm(31677): update thread list
01-06 22:53:51.241 D/dalvikvm(31677): threadid=5: interp stack at 0x5c8e5000
01-06 22:53:51.241 D/dalvikvm(31677): threadid=5: created from interp
01-06 22:53:51.241 D/dalvikvm(31677): start new thread
01-06 22:53:51.241 D/dalvikvm(31677): create interp thread : stack size=32KB
01-06 22:53:51.241 D/dalvikvm(31677): create new thread
01-06 22:53:51.241 D/dalvikvm(31677): new thread created
01-06 22:53:51.241 D/dalvikvm(31677): update thread list
01-06 22:53:51.241 D/dalvikvm(31677): threadid=5: notify debugger
01-06 22:53:51.241 D/dalvikvm(31677): threadid=5 (ReferenceQueueDaemon): calling run()
01-06 22:53:51.242 D/dalvikvm(31677): threadid=6: interp stack at 0x5c8ed000
01-06 22:53:51.242 D/dalvikvm(31677): threadid=6: created from interp
01-06 22:53:51.242 D/dalvikvm(31677): start new thread
01-06 22:53:51.242 D/dalvikvm(31677): create interp thread : stack size=32KB
01-06 22:53:51.242 D/dalvikvm(31677): create new thread
01-06 22:53:51.242 D/dalvikvm(31677): new thread created
01-06 22:53:51.242 D/dalvikvm(31677): update thread list
01-06 22:53:51.242 D/dalvikvm(31677): threadid=6: notify debugger
01-06 22:53:51.242 D/dalvikvm(31677): threadid=6 (FinalizerDaemon): calling run()
01-06 22:53:51.242 D/dalvikvm(31677): threadid=7: interp stack at 0x5c8f5000
01-06 22:53:51.242 D/dalvikvm(31677): threadid=7: created from interp
01-06 22:53:51.242 D/dalvikvm(31677): start new thread
01-06 22:53:51.263 D/dalvikvm(31677): threadid=7: notify debugger
01-06 22:53:51.263 D/dalvikvm(31677): threadid=7 (FinalizerWatchdogDaemon): calling run()
01-06 22:53:51.284 I/dalvikvm(31677): Turning on JNI app bug workarounds for target SDK version 4...
01-06 22:53:51.286 D/dalvikvm(31677): threadid=8: interp stack at 0x5c8fd000
01-06 22:53:51.307 D/dalvikvm(31677): threadid=9: interp stack at 0x5c905000
01-06 22:53:51.371 D/dalvikvm(31677): open_cached_dex_file : /data/app/com.greatbytes.crashreport-1.apk /data/dalvik-cache/data@app@com.greatbytes.crashreport-1.apk@classes.dex
01-06 22:53:51.444 D/skia    (31677): Flag is not 10
01-06 22:53:51.455 D/skia    (31677): Flag is not 10
01-06 22:53:51.458 D/skia    (31677): Flag is not 10
01-06 22:53:51.458 D/skia    (31677): Flag is not 10
01-06 22:53:51.464 D/skia    (31677): Flag is not 10
01-06 22:53:51.467 D/skia    (31677): Flag is not 10
01-06 22:53:51.470 D/skia    (31677): Flag is not 10
01-06 22:53:51.472 D/skia    (31677): Flag is not 10
01-06 22:53:51.472 D/AbsListView(31677): checkAbsListViewlLogProperty get invalid command
01-06 22:53:51.475 D/skia    (31677): Flag is not 10
01-06 22:53:51.492 I/webkit/webview_proxy(31677): WebView() constructor=android.webkit.WebView{418d9a90 IFE.HV.. ......I. 0,0-0,0 #7f06000a app:id/webMailHide}
01-06 22:53:51.509 D/dalvikvm(31677): create interp thread : stack size=32KB
01-06 22:53:51.509 D/dalvikvm(31677): create new thread
01-06 22:53:51.511 D/dalvikvm(31677): new thread created
01-06 22:53:51.511 D/dalvikvm(31677): update thread list
01-06 22:53:51.511 D/dalvikvm(31677): threadid=10: interp stack at 0x5d08c000
01-06 22:53:51.511 D/dalvikvm(31677): threadid=10: created from interp
01-06 22:53:51.511 D/dalvikvm(31677): start new thread
01-06 22:53:51.511 D/dalvikvm(31677): threadid=10: notify debugger
01-06 22:53:51.511 D/dalvikvm(31677): threadid=10 (WebViewCoreThread): calling run()
01-06 22:53:51.522 V/Provider/Settings(31677): invalidate [system]: current 1227 != cached 0
01-06 22:53:51.526 V/Provider/Settings(31677): from db cache, name = show_password , value = null
01-06 22:53:51.528 D/dalvikvm(31677): create interp thread : stack size=32KB
01-06 22:53:51.528 D/dalvikvm(31677): create new thread
01-06 22:53:51.528 D/webkit/webcore(31677): sWebCoreHandler.handleMessage() 0 obj=android.webkit.WebViewCore@418dd3e0
01-06 22:53:51.529 D/dalvikvm(31677): new thread created
01-06 22:53:51.530 D/dalvikvm(31677): update thread list
01-06 22:53:51.530 D/dalvikvm(31677): threadid=11: interp stack at 0x5d194000
01-06 22:53:51.530 D/dalvikvm(31677): threadid=11: created from interp
01-06 22:53:51.530 D/dalvikvm(31677): start new thread
01-06 22:53:51.530 D/dalvikvm(31677): threadid=11: notify debugger
01-06 22:53:51.530 D/dalvikvm(31677): threadid=11 (Thread-24168): calling run()
01-06 22:53:51.531 D/dalvikvm(31677): create interp thread : stack size=32KB
01-06 22:53:51.531 D/dalvikvm(31677): create new thread
01-06 22:53:51.531 D/dalvikvm(31677): new thread created
01-06 22:53:51.531 D/dalvikvm(31677): update thread list
01-06 22:53:51.535 D/dalvikvm(31677): threadid=12: interp stack at 0x5d29c000
01-06 22:53:51.535 D/dalvikvm(31677): threadid=12: created from interp
01-06 22:53:51.535 D/dalvikvm(31677): start new thread
01-06 22:53:51.539 D/dalvikvm(31677): threadid=12: notify debugger
01-06 22:53:51.540 D/dalvikvm(31677): threadid=12 (CookieSyncManager): calling run()
01-06 22:53:51.549 D/dalvikvm(31677): create interp thread : stack size=32KB
01-06 22:53:51.549 D/dalvikvm(31677): create new thread
01-06 22:53:51.549 D/dalvikvm(31677): new thread created
01-06 22:53:51.549 D/dalvikvm(31677): update thread list
01-06 22:53:51.549 D/dalvikvm(31677): threadid=13: interp stack at 0x5d3a4000
01-06 22:53:51.549 D/dalvikvm(31677): threadid=13: created from interp
01-06 22:53:51.549 D/dalvikvm(31677): start new thread
01-06 22:53:51.550 D/dalvikvm(31677): threadid=13: notify debugger
01-06 22:53:51.550 D/dalvikvm(31677): threadid=13 (AsyncTask #1): calling run()
01-06 22:53:51.557 D/skia    (31677): Flag is not 10
01-06 22:53:51.561 D/dalvikvm(31677): create interp thread : stack size=32KB
01-06 22:53:51.562 D/dalvikvm(31677): create new thread
01-06 22:53:51.562 D/dalvikvm(31677): new thread created
01-06 22:53:51.562 D/dalvikvm(31677): update thread list
01-06 22:53:51.562 D/dalvikvm(31677): threadid=14: interp stack at 0x5d5ac000
01-06 22:53:51.562 D/dalvikvm(31677): threadid=14: created from interp
01-06 22:53:51.562 D/dalvikvm(31677): start new thread
01-06 22:53:51.562 D/dalvikvm(31677): threadid=14: notify debugger
01-06 22:53:51.562 D/dalvikvm(31677): threadid=14 (SharedPreferencesImpl-load): calling run()
01-06 22:53:51.563 D/dalvikvm(31677): threadid=14: exiting
01-06 22:53:51.563 D/dalvikvm(31677): threadid=14: bye!
01-06 22:53:51.575 D/skia    (31677): Flag is not 10
01-06 22:53:51.586 D/skia    (31677): Flag is not 10
01-06 22:53:51.588 D/skia    (31677): Flag is not 10
01-06 22:53:51.598 D/skia    (31677): Flag is not 10
01-06 22:53:51.601 D/skia    (31677): Flag is not 10
01-06 22:53:51.602 D/skia    (31677): Flag is not 10
01-06 22:53:51.604 D/skia    (31677): Flag is not 10
01-06 22:53:51.605 D/skia    (31677): Flag is not 10
01-06 22:53:51.606 D/skia    (31677): Flag is not 10
01-06 22:53:51.614 D/skia    (31677): Flag is not 10
01-06 22:53:51.628 D/dalvikvm(31677): create interp thread : stack size=32KB
01-06 22:53:51.628 D/dalvikvm(31677): create new thread
01-06 22:53:51.628 D/dalvikvm(31677): new thread created
01-06 22:53:51.628 D/dalvikvm(31677): update thread list
01-06 22:53:51.629 D/dalvikvm(31677): threadid=14: interp stack at 0x5d5ac000
01-06 22:53:51.629 D/dalvikvm(31677): threadid=14: created from interp
01-06 22:53:51.629 D/dalvikvm(31677): start new thread
01-06 22:53:51.632 D/dalvikvm(31677): threadid=14: notify debugger
01-06 22:53:51.632 D/dalvikvm(31677): threadid=14 (AsyncTask #2): calling run()
01-06 22:53:51.633 D/dalvikvm(31677): create interp thread : stack size=32KB
01-06 22:53:51.633 D/dalvikvm(31677): create new thread
01-06 22:53:51.633 D/dalvikvm(31677): new thread created
01-06 22:53:51.633 D/dalvikvm(31677): update thread list
01-06 22:53:51.633 D/dalvikvm(31677): threadid=15: interp stack at 0x5d6b4000
01-06 22:53:51.633 D/dalvikvm(31677): threadid=15: created from interp
01-06 22:53:51.633 D/dalvikvm(31677): start new thread
01-06 22:53:51.639 D/dalvikvm(31677): threadid=15: notify debugger
01-06 22:53:51.639 D/dalvikvm(31677): threadid=15 (java.lang.ProcessManager): calling run()

**Comment by AudriusButkevicius** [comment]
Sadly, it doesn't seem relevant.

**Comment by valentin-mu** [comment]
i didn't even think that collecting log of crashed app is such a tricky thing %)
can you post link google play for logcat app you use(or at least you know it works)?
does it need root or any special permissions to work?

btw, i used standart android tool to send report when app crashed(tapped button 'Report' in 'app crashed' popup) but i don't know where does it send data :(

**Comment by lupa18** [comment]
Here the same problem with CM 11 (android 4.4.4) - Here an image: https://github.com/syncthing/syncthing/issues/1193

**Comment by AudriusButkevicius** [comment]
That's the one I've used:
https://play.google.com/store/apps/details?id=com.nolanlawson.logcat&hl=en

**Comment by lupa18** [comment]
Sorry but we don't want/need install play services

**Comment by Nutomic** [comment]
As Audrius said, there's nothing relevant in this log. Can you post a longer/unfiltered one please?

**Comment by lupa18** [comment]
Would you please say us what kind of log do you need and how collect it ?

**Comment by AudriusButkevicius** [comment]
We need logcat from android, or the log when invoking the libsyncthing.so.

**Comment by arcusfelis** [comment]
Phone: Sony Xperia
OS: Android 4.4
Syncthing version: 0.5.15
Stacktrace: https://www.dropbox.com/sh/t2ulbs0md5xduge/AABoSkvgP1NdbcIyKbvjUWb5a?dl=0 it's images :)
So, basically it's https://github.com/syncthing/syncthing/issues/298
```
Caused by: java.io.FileNotFoundException: /data/data/com.nutomic.syncthingandroid/config.xml: open failed: ENOENT (No such file or directory)
```

**Comment by kmq** [comment]
Android: 4.4.2 (Cyanogenmod 11)
Version: 0.5.15

Have had syncthing-android installed from F-Droid for a while, and recently updated, I'm not 100% sure, but I think this issue has been affecting me since I updated to 0.5.15 unfortunately I can't tell you anymore from which version I updated.

From the stacktrace (via adb logcat, see below) I could see that the XML parser is throwing an exception. I logged onto the device and discovered that the file 
```
/data/data/com.nutomic.syncthingandroid/file/config.xml 
```
exists, but has 0 bytes. It seems that got mangled during the update somehow.
Next to it, there are two files 

```
config.xml.v4 
config.xml.v6
```
Which look ok.

```
E/AndroidRuntime(11025): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(11025):        at android.os.AsyncTask$3.done(AsyncTask.java:300)
E/AndroidRuntime(11025):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(11025):        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(11025):        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(11025):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(11025):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(11025):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(11025):        at java.lang.Thread.run(Thread.java:841)
E/AndroidRuntime(11025): Caused by: java.lang.RuntimeException: Failed to open config file
E/AndroidRuntime(11025):        at com.nutomic.syncthingandroid.util.ConfigXml.<init>(ConfigXml.java:61)
E/AndroidRuntime(11025):        at com.nutomic.syncthingandroid.syncthing.SyncthingService$StartupTask.doInBackground(SyncthingService.java:268)
E/AndroidRuntime(11025):        at com.nutomic.syncthingandroid.syncthing.SyncthingService$StartupTask.doInBackground(SyncthingService.java:263)
E/AndroidRuntime(11025):        at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/AndroidRuntime(11025):        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(11025):        ... 4 more
E/AndroidRuntime(11025): Caused by: org.xml.sax.SAXParseException: Unexpected end of document
E/AndroidRuntime(11025):        at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:125)
E/AndroidRuntime(11025):        at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:183)
E/AndroidRuntime(11025):        at com.nutomic.syncthingandroid.util.ConfigXml.<init>(ConfigXml.java:59)
E/AndroidRuntime(11025):        ... 8 more
W/ActivityManager( 2135):   Force finishing activity com.nutomic.syncthingandroid/.activities.MainActivity
```

**Comment by Zillode** [comment]
@arcusfelis: could you disable XPrivacy and report your findings? In our case a service running a background process which creates this file, so the popup might be missing.

@AudriusButkevicius : we should to catch an error when saving the config fails ( https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/main.go#L442 ) (related to @kmq 's issue) Maybe restore the old version if the new config fails or panic.

**Comment by AudriusButkevicius** [comment]
yeah that doesn't solve the issue though?

**Comment by Zillode** [comment]
maybe @kmq has invalid values which caused the empty config file? I think the other issues are different because the config file is actually missing and not being recreated.

**Comment by AudriusButkevicius** [comment]
I guess he could just remove it and recreate it

**Comment by Nutomic** [comment]
@arcusfelis The config file should always be created if it doesn't exist, so that might be due to XPrivacy. But on the other hand, the config is in the app's data folder, and writing there shouldn't be blocked, right?

@AudriusButkevicius So you think I should just delete an empty config file? What about invalid configs? And should I copy any `config.xml.vX` to `config.xml` or does syncthing do that?

**Comment by AudriusButkevicius** [comment]
We seem to fatal out if the config is invalid XML, which an empty file is, which I guess is not great.
Running on a desktop it's easy to fix, on a phone perhaps you should just nuke the file.

**Comment by Nutomic** [comment]
Yeah that makes sense.
