### ISSUE TITLE
Web GUI is broke after last update

### ISSUE THREAD

**Issue by not-programmer98** [syncthing/syncthing-android#2011]
Web GUI is broken, here's a screenshot.
![ResizedImage_2023-11-17_19-25-44_1629](https://github.com/syncthing/syncthing-android/assets/126913926/8e3571d1-28dd-4c5f-a999-d19298504053)

### Version Information

    App Version: 1.26.0
    Syncthing Version: v1.26.0
    Android Version: Android 12
I got this error on 2 different phones with 2 different android versions

**Comment by tomasz1986** [comment]
Duplicate of https://github.com/syncthing/syncthing-android/issues/1996. Please try upgrading to v1.26.1 and see if the GUI loads there.
