### ISSUE TITLE
Android 13 saf file path support

### ISSUE THREAD

**Issue by expoli** [syncthing/syncthing-android#2016]
In Android 13, the permission control of some application data in android/data has become stricter, but some applications provide SAF ways to expose their own data. Now syncthing can call the file manager to browse SAF files as synchronization addresses. However, after selecting, it prompts that the corresponding file address cannot be used. (Is this an inability to resolve the saf file path?) Here are some screenshots.

![993c0332921c7c5ec0cf2c6f34d5492](https://github.com/syncthing/syncthing-android/assets/31023767/0159bc6a-068e-4533-a49c-06dfb0bdc896)

![7045cde8cd80489380b733dd068b04c](https://github.com/syncthing/syncthing-android/assets/31023767/7fffedf8-cb83-4310-bbad-b74c075f68b7)

![6ed84e2add16be2c4d7a04a52f3bef8](https://github.com/syncthing/syncthing-android/assets/31023767/5f451891-b742-4c05-b279-ede890268162)

### Version Information

    App Version: 1.26.1
    Syncthing Version: 1.26.1
    Android Version: Android 13

**Comment by imsodin** [comment]
Closed as it's a feature request: https://github.com/syncthing/syncthing-android#no-feature-request-taken-feature-contributions-case-by-case

Also if you do some search here or on the forum you'll find plenty of similar requests and why it's not possible.
