### ISSUE TITLE
app crashes on open

### ISSUE THREAD

**Issue by xplat** [syncthing/syncthing-android#202]
app version: 0.5.7-0.5.13 (F-droid, bisected)
platform info: Acer Iconia Tab 8
  Model #: A1-840
  Android version: 4.4.4 (x86)
  UEFI version: 1.0.5
  Kernel version: 3.10,20+
  Image version: Acer_AV0K1_A1-840_RV0ERC02_WW_GEN1
  Build number: Acer_AV0K1_A1-840_1.061.00_WW_GEN1
  CPU: Intel Atom (Bay Trail-T CR 3735F/3735G) 4 cores 1.8GHz
  Screen: 800x1280

If necessary I'll attach logs once I get somewhere I can use ADB.

**Comment by AudriusButkevicius** [comment]
syncthing binary shipped with the app is an arm binary, hence you probably need two do your own packaging to include the right architecture binary, or replace the binary after you've installed the app.

**Comment by xplat** [comment]
Ah, so the culprit for the hard crash would then be https://github.com/syncthing/syncthing-android/commit/df48d75127132f720fa99a78584e24f59bafe925 ?  It's true the syncthing binary always exits with error 1 even with other versions.  I guess that means the binary translation isn't working on syncthing.  Can I replace the binary on a non-rooted device?  If so how do I do it?  And why does the package with arm binary get listed as supporting x86 ABI?

**Comment by AudriusButkevicius** [comment]
I dont think there is any translation happening. The exec call just fails.

Not sure if you are able to replace the binary, never ran stock android.

**Comment by xplat** [comment]
What am I supposed to replace in here?  lib/x86/libsyncthing.so already says it's an x86 binary according to 'file'...

james@nanaka:~/Downloads$ aapt list ~/Downloads/com.nutomic.syncthingandroid_50.apk 
META-INF/MANIFEST.MF
META-INF/21B5F25B.SF
META-INF/21B5F25B.RSA
META-INF/buildserverid
META-INF/fdroidserverid
AndroidManifest.xml
res/anim/abc_fade_in.xml
res/anim/abc_fade_out.xml
res/anim/abc_slide_in_bottom.xml
res/anim/abc_slide_in_top.xml
res/anim/abc_slide_out_bottom.xml
res/anim/abc_slide_out_top.xml
res/color/abc_background_cache_hint_selector_material_dark.xml
res/color/abc_background_cache_hint_selector_material_light.xml
res/color/abc_primary_text_disable_only_material_dark.xml
res/color/abc_primary_text_disable_only_material_light.xml
res/color/abc_primary_text_material_dark.xml
res/color/abc_primary_text_material_light.xml
res/color/abc_search_url_text.xml
res/color/abc_secondary_text_material_dark.xml
res/color/abc_secondary_text_material_light.xml
res/drawable-hdpi-v4/abc_ab_share_pack_holo_dark.9.png
res/drawable-hdpi-v4/abc_ab_share_pack_holo_light.9.png
res/drawable-hdpi-v4/abc_btn_check_to_on_mtrl_000.png
res/drawable-hdpi-v4/abc_btn_check_to_on_mtrl_015.png
res/drawable-hdpi-v4/abc_btn_radio_to_on_mtrl_000.png
res/drawable-hdpi-v4/abc_btn_radio_to_on_mtrl_015.png
res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png
res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png
res/drawable-hdpi-v4/abc_cab_background_top_mtrl_alpha.9.png
res/drawable-hdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
res/drawable-hdpi-v4/abc_ic_clear_mtrl_alpha.png
res/drawable-hdpi-v4/abc_ic_commit_search_api_mtrl_alpha.png
res/drawable-hdpi-v4/abc_ic_go_search_api_mtrl_alpha.png
res/drawable-hdpi-v4/abc_ic_menu_copy_mtrl_am_alpha.png
res/drawable-hdpi-v4/abc_ic_menu_cut_mtrl_alpha.png
res/drawable-hdpi-v4/abc_ic_menu_moreoverflow_mtrl_alpha.png
res/drawable-hdpi-v4/abc_ic_menu_paste_mtrl_am_alpha.png
res/drawable-hdpi-v4/abc_ic_menu_selectall_mtrl_alpha.png
res/drawable-hdpi-v4/abc_ic_menu_share_mtrl_alpha.png
res/drawable-hdpi-v4/abc_ic_search_api_mtrl_alpha.png
res/drawable-hdpi-v4/abc_ic_voice_search_api_mtrl_alpha.png
res/drawable-hdpi-v4/abc_list_divider_mtrl_alpha.9.png
res/drawable-hdpi-v4/abc_list_focused_holo.9.png
res/drawable-hdpi-v4/abc_list_longpressed_holo.9.png
res/drawable-hdpi-v4/abc_list_pressed_holo_dark.9.png
res/drawable-hdpi-v4/abc_list_pressed_holo_light.9.png
res/drawable-hdpi-v4/abc_list_selector_disabled_holo_dark.9.png
res/drawable-hdpi-v4/abc_list_selector_disabled_holo_light.9.png
res/drawable-hdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png
res/drawable-hdpi-v4/abc_popup_background_mtrl_mult.9.png
res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png
res/drawable-hdpi-v4/abc_switch_track_mtrl_alpha.9.png
res/drawable-hdpi-v4/abc_tab_indicator_mtrl_alpha.9.png
res/drawable-hdpi-v4/abc_textfield_activated_mtrl_alpha.9.png
res/drawable-hdpi-v4/abc_textfield_default_mtrl_alpha.9.png
res/drawable-hdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png
res/drawable-hdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png
res/drawable-hdpi-v4/ic_delete.png
res/drawable-hdpi-v4/ic_drawer.png
res/drawable-hdpi-v4/ic_launcher.png
res/drawable-hdpi-v4/ic_qrcode.png
res/drawable-ldrtl-hdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
res/drawable-ldrtl-hdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
res/drawable-ldrtl-hdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
res/drawable-ldrtl-hdpi-v17/abc_spinner_mtrl_am_alpha.9.png
res/drawable-ldrtl-mdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
res/drawable-ldrtl-mdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
res/drawable-ldrtl-mdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
res/drawable-ldrtl-mdpi-v17/abc_spinner_mtrl_am_alpha.9.png
res/drawable-ldrtl-xhdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
res/drawable-ldrtl-xhdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
res/drawable-ldrtl-xhdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
res/drawable-ldrtl-xhdpi-v17/abc_spinner_mtrl_am_alpha.9.png
res/drawable-ldrtl-xxhdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
res/drawable-ldrtl-xxhdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
res/drawable-ldrtl-xxhdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
res/drawable-ldrtl-xxhdpi-v17/abc_spinner_mtrl_am_alpha.9.png
res/drawable-ldrtl-xxxhdpi-v17/abc_ic_ab_back_mtrl_am_alpha.png
res/drawable-ldrtl-xxxhdpi-v17/abc_ic_menu_copy_mtrl_am_alpha.png
res/drawable-ldrtl-xxxhdpi-v17/abc_ic_menu_cut_mtrl_alpha.png
res/drawable-ldrtl-xxxhdpi-v17/abc_spinner_mtrl_am_alpha.9.png
res/drawable-mdpi-v4/abc_ab_share_pack_holo_dark.9.png
res/drawable-mdpi-v4/abc_ab_share_pack_holo_light.9.png
res/drawable-mdpi-v4/abc_btn_check_to_on_mtrl_000.png
res/drawable-mdpi-v4/abc_btn_check_to_on_mtrl_015.png
res/drawable-mdpi-v4/abc_btn_radio_to_on_mtrl_000.png
res/drawable-mdpi-v4/abc_btn_radio_to_on_mtrl_015.png
res/drawable-mdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png
res/drawable-mdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png
res/drawable-mdpi-v4/abc_cab_background_top_mtrl_alpha.9.png
res/drawable-mdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
res/drawable-mdpi-v4/abc_ic_clear_mtrl_alpha.png
res/drawable-mdpi-v4/abc_ic_commit_search_api_mtrl_alpha.png
res/drawable-mdpi-v4/abc_ic_go_search_api_mtrl_alpha.png
res/drawable-mdpi-v4/abc_ic_menu_copy_mtrl_am_alpha.png
res/drawable-mdpi-v4/abc_ic_menu_cut_mtrl_alpha.png
res/drawable-mdpi-v4/abc_ic_menu_moreoverflow_mtrl_alpha.png
res/drawable-mdpi-v4/abc_ic_menu_paste_mtrl_am_alpha.png
res/drawable-mdpi-v4/abc_ic_menu_selectall_mtrl_alpha.png
res/drawable-mdpi-v4/abc_ic_menu_share_mtrl_alpha.png
res/drawable-mdpi-v4/abc_ic_search_api_mtrl_alpha.png
res/drawable-mdpi-v4/abc_ic_voice_search_api_mtrl_alpha.png
res/drawable-mdpi-v4/abc_list_divider_mtrl_alpha.9.png
res/drawable-mdpi-v4/abc_list_focused_holo.9.png
res/drawable-mdpi-v4/abc_list_longpressed_holo.9.png
res/drawable-mdpi-v4/abc_list_pressed_holo_dark.9.png
res/drawable-mdpi-v4/abc_list_pressed_holo_light.9.png
res/drawable-mdpi-v4/abc_list_selector_disabled_holo_dark.9.png
res/drawable-mdpi-v4/abc_list_selector_disabled_holo_light.9.png
res/drawable-mdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png
res/drawable-mdpi-v4/abc_popup_background_mtrl_mult.9.png
res/drawable-mdpi-v4/abc_spinner_mtrl_am_alpha.9.png
res/drawable-mdpi-v4/abc_switch_track_mtrl_alpha.9.png
res/drawable-mdpi-v4/abc_tab_indicator_mtrl_alpha.9.png
res/drawable-mdpi-v4/abc_textfield_activated_mtrl_alpha.9.png
res/drawable-mdpi-v4/abc_textfield_default_mtrl_alpha.9.png
res/drawable-mdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png
res/drawable-mdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png
res/drawable-mdpi-v4/ic_delete.png
res/drawable-mdpi-v4/ic_drawer.png
res/drawable-mdpi-v4/ic_launcher.png
res/drawable-mdpi-v4/ic_qrcode.png
res/drawable-v21/abc_cab_background_top_material.xml
res/drawable-xhdpi-v4/abc_ab_share_pack_holo_dark.9.png
res/drawable-xhdpi-v4/abc_ab_share_pack_holo_light.9.png
res/drawable-xhdpi-v4/abc_btn_check_to_on_mtrl_000.png
res/drawable-xhdpi-v4/abc_btn_check_to_on_mtrl_015.png
res/drawable-xhdpi-v4/abc_btn_radio_to_on_mtrl_000.png
res/drawable-xhdpi-v4/abc_btn_radio_to_on_mtrl_015.png
res/drawable-xhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png
res/drawable-xhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png
res/drawable-xhdpi-v4/abc_cab_background_top_mtrl_alpha.9.png
res/drawable-xhdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
res/drawable-xhdpi-v4/abc_ic_clear_mtrl_alpha.png
res/drawable-xhdpi-v4/abc_ic_commit_search_api_mtrl_alpha.png
res/drawable-xhdpi-v4/abc_ic_go_search_api_mtrl_alpha.png
res/drawable-xhdpi-v4/abc_ic_menu_copy_mtrl_am_alpha.png
res/drawable-xhdpi-v4/abc_ic_menu_cut_mtrl_alpha.png
res/drawable-xhdpi-v4/abc_ic_menu_moreoverflow_mtrl_alpha.png
res/drawable-xhdpi-v4/abc_ic_menu_paste_mtrl_am_alpha.png
res/drawable-xhdpi-v4/abc_ic_menu_selectall_mtrl_alpha.png
res/drawable-xhdpi-v4/abc_ic_menu_share_mtrl_alpha.png
res/drawable-xhdpi-v4/abc_ic_search_api_mtrl_alpha.png
res/drawable-xhdpi-v4/abc_ic_voice_search_api_mtrl_alpha.png
res/drawable-xhdpi-v4/abc_list_divider_mtrl_alpha.9.png
res/drawable-xhdpi-v4/abc_list_focused_holo.9.png
res/drawable-xhdpi-v4/abc_list_longpressed_holo.9.png
res/drawable-xhdpi-v4/abc_list_pressed_holo_dark.9.png
res/drawable-xhdpi-v4/abc_list_pressed_holo_light.9.png
res/drawable-xhdpi-v4/abc_list_selector_disabled_holo_dark.9.png
res/drawable-xhdpi-v4/abc_list_selector_disabled_holo_light.9.png
res/drawable-xhdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png
res/drawable-xhdpi-v4/abc_popup_background_mtrl_mult.9.png
res/drawable-xhdpi-v4/abc_spinner_mtrl_am_alpha.9.png
res/drawable-xhdpi-v4/abc_switch_track_mtrl_alpha.9.png
res/drawable-xhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png
res/drawable-xhdpi-v4/abc_textfield_activated_mtrl_alpha.9.png
res/drawable-xhdpi-v4/abc_textfield_default_mtrl_alpha.9.png
res/drawable-xhdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png
res/drawable-xhdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png
res/drawable-xhdpi-v4/ic_delete.png
res/drawable-xhdpi-v4/ic_drawer.png
res/drawable-xhdpi-v4/ic_launcher.png
res/drawable-xhdpi-v4/ic_qrcode.png
res/drawable-xxhdpi-v4/abc_ab_share_pack_holo_dark.9.png
res/drawable-xxhdpi-v4/abc_ab_share_pack_holo_light.9.png
res/drawable-xxhdpi-v4/abc_btn_check_to_on_mtrl_000.png
res/drawable-xxhdpi-v4/abc_btn_check_to_on_mtrl_015.png
res/drawable-xxhdpi-v4/abc_btn_radio_to_on_mtrl_000.png
res/drawable-xxhdpi-v4/abc_btn_radio_to_on_mtrl_015.png
res/drawable-xxhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png
res/drawable-xxhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png
res/drawable-xxhdpi-v4/abc_cab_background_top_mtrl_alpha.9.png
res/drawable-xxhdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
res/drawable-xxhdpi-v4/abc_ic_clear_mtrl_alpha.png
res/drawable-xxhdpi-v4/abc_ic_commit_search_api_mtrl_alpha.png
res/drawable-xxhdpi-v4/abc_ic_go_search_api_mtrl_alpha.png
res/drawable-xxhdpi-v4/abc_ic_menu_copy_mtrl_am_alpha.png
res/drawable-xxhdpi-v4/abc_ic_menu_cut_mtrl_alpha.png
res/drawable-xxhdpi-v4/abc_ic_menu_moreoverflow_mtrl_alpha.png
res/drawable-xxhdpi-v4/abc_ic_menu_paste_mtrl_am_alpha.png
res/drawable-xxhdpi-v4/abc_ic_menu_selectall_mtrl_alpha.png
res/drawable-xxhdpi-v4/abc_ic_menu_share_mtrl_alpha.png
res/drawable-xxhdpi-v4/abc_ic_search_api_mtrl_alpha.png
res/drawable-xxhdpi-v4/abc_ic_voice_search_api_mtrl_alpha.png
res/drawable-xxhdpi-v4/abc_list_divider_mtrl_alpha.9.png
res/drawable-xxhdpi-v4/abc_list_focused_holo.9.png
res/drawable-xxhdpi-v4/abc_list_longpressed_holo.9.png
res/drawable-xxhdpi-v4/abc_list_pressed_holo_dark.9.png
res/drawable-xxhdpi-v4/abc_list_pressed_holo_light.9.png
res/drawable-xxhdpi-v4/abc_list_selector_disabled_holo_dark.9.png
res/drawable-xxhdpi-v4/abc_list_selector_disabled_holo_light.9.png
res/drawable-xxhdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png
res/drawable-xxhdpi-v4/abc_popup_background_mtrl_mult.9.png
res/drawable-xxhdpi-v4/abc_spinner_mtrl_am_alpha.9.png
res/drawable-xxhdpi-v4/abc_switch_track_mtrl_alpha.9.png
res/drawable-xxhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png
res/drawable-xxhdpi-v4/abc_textfield_activated_mtrl_alpha.9.png
res/drawable-xxhdpi-v4/abc_textfield_default_mtrl_alpha.9.png
res/drawable-xxhdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png
res/drawable-xxhdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png
res/drawable-xxhdpi-v4/ic_delete.png
res/drawable-xxhdpi-v4/ic_drawer.png
res/drawable-xxhdpi-v4/ic_launcher.png
res/drawable-xxhdpi-v4/ic_qrcode.png
res/drawable-xxxhdpi-v4/abc_btn_check_to_on_mtrl_000.png
res/drawable-xxxhdpi-v4/abc_btn_check_to_on_mtrl_015.png
res/drawable-xxxhdpi-v4/abc_btn_radio_to_on_mtrl_000.png
res/drawable-xxxhdpi-v4/abc_btn_radio_to_on_mtrl_015.png
res/drawable-xxxhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png
res/drawable-xxxhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png
res/drawable-xxxhdpi-v4/abc_ic_ab_back_mtrl_am_alpha.png
res/drawable-xxxhdpi-v4/abc_ic_clear_mtrl_alpha.png
res/drawable-xxxhdpi-v4/abc_ic_menu_copy_mtrl_am_alpha.png
res/drawable-xxxhdpi-v4/abc_ic_menu_cut_mtrl_alpha.png
res/drawable-xxxhdpi-v4/abc_ic_menu_moreoverflow_mtrl_alpha.png
res/drawable-xxxhdpi-v4/abc_ic_menu_paste_mtrl_am_alpha.png
res/drawable-xxxhdpi-v4/abc_ic_menu_selectall_mtrl_alpha.png
res/drawable-xxxhdpi-v4/abc_ic_search_api_mtrl_alpha.png
res/drawable-xxxhdpi-v4/abc_ic_voice_search_api_mtrl_alpha.png
res/drawable-xxxhdpi-v4/abc_spinner_mtrl_am_alpha.9.png
res/drawable-xxxhdpi-v4/abc_switch_track_mtrl_alpha.9.png
res/drawable-xxxhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png
res/drawable/abc_btn_check_material.xml
res/drawable/abc_btn_radio_material.xml
res/drawable/abc_cab_background_internal_bg.xml
res/drawable/abc_cab_background_top_material.xml
res/drawable/abc_edit_text_material.xml
res/drawable/abc_item_background_holo_dark.xml
res/drawable/abc_item_background_holo_light.xml
res/drawable/abc_list_selector_background_transition_holo_dark.xml
res/drawable/abc_list_selector_background_transition_holo_light.xml
res/drawable/abc_list_selector_holo_dark.xml
res/drawable/abc_list_selector_holo_light.xml
res/drawable/abc_switch_thumb_material.xml
res/drawable/abc_tab_indicator_material.xml
res/drawable/abc_textfield_search_material.xml
res/layout-v11/abc_screen_content_include.xml
res/layout-v21/abc_screen_toolbar.xml
res/layout/abc_action_bar_title_item.xml
res/layout/abc_action_bar_up_container.xml
res/layout/abc_action_bar_view_list_nav_layout.xml
res/layout/abc_action_menu_item_layout.xml
res/layout/abc_action_menu_layout.xml
res/layout/abc_action_mode_bar.xml
res/layout/abc_action_mode_close_item_material.xml
res/layout/abc_activity_chooser_view.xml
res/layout/abc_activity_chooser_view_include.xml
res/layout/abc_activity_chooser_view_list_item.xml
res/layout/abc_expanded_menu_layout.xml
res/layout/abc_list_menu_item_checkbox.xml
res/layout/abc_list_menu_item_icon.xml
res/layout/abc_list_menu_item_layout.xml
res/layout/abc_list_menu_item_radio.xml
res/layout/abc_popup_menu_item_layout.xml
res/layout/abc_screen_content_include.xml
res/layout/abc_screen_simple.xml
res/layout/abc_screen_simple_overlay_action_mode.xml
res/layout/abc_screen_toolbar.xml
res/layout/abc_search_dropdown_item_icons_2line.xml
res/layout/abc_search_view.xml
res/layout/abc_simple_dropdown_hint.xml
res/layout/device_list_item.xml
res/layout/folder_list_item.xml
res/layout/folder_picker_activity.xml
res/layout/loading_dialog.xml
res/layout/local_device_info_fragment.xml
res/layout/main_activity.xml
res/layout/preference_list_fragment.xml
res/layout/scan_qr_code_widget.xml
res/layout/support_simple_spinner_dropdown_item.xml
res/layout/web_gui_activity.xml
res/menu/device_settings.xml
res/menu/folder_picker.xml
res/menu/folder_settings.xml
res/menu/main.xml
res/xml/app_settings.xml
res/xml/device_settings_create.xml
res/xml/device_settings_edit.xml
res/xml/folder_settings_create.xml
res/xml/folder_settings_edit.xml
resources.arsc
classes.dex
lib/armeabi-v7a/libsyncthing.so
lib/armeabi/libsyncthing.so
lib/x86/libsyncthing.so

**Comment by AudriusButkevicius** [comment]
actually there does seem to be a x86 binary, so my suggestion is completely useless.
I genuinely thought it wasn't there. 

Then I am not sure what the crash is about, it's possibly same as #201.
It would be more clear if you could invoke the x86 so yourself, but I guess you need root access for that?

**Comment by Nutomic** [comment]
If you have root, you can `cd /data/data/com.nutomic.syncthingandroid/lib` and try to run `./libsyncthing.so`. 

Otherwise, I really don't know what could cause this (error code 1 is just misc errors). But logs might be helpful

**Comment by xplat** [comment]
OK, just for you guys I borrowed a Windows computer to root my tablet even though there's no bootloader unlock.  Here's the result:

> root@ducati2hd:/data/data/com.nutomic.syncthingandroid/lib # ./libsyncthing.so
> tmp-mksh: ./libsyncthing.so: No such file or directory
> 1|root@ducati2hd:/data/data/com.nutomic.syncthingandroid/lib # 

Hopefully this means more to you than it does to me.

**Comment by AudriusButkevicius** [comment]
Can you do `file libsyncthing.so` and `ldd libsyncthing.so`?

**Comment by xplat** [comment]
I don't have **file** or **ldd** on the tablet.  Here's the results on a 'real' computer.

> grabby5:nanaka:~/proj/syncthing$ md5sum lib/x86/libsyncthing.so 
> 82f115b7fd684d5384a3c8d75a159145  lib/x86/libsyncthing.so
> grabby5:nanaka:~/proj/syncthing$ file lib/x86/libsyncthing.so 
> lib/x86/libsyncthing.so: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), not stripped
> grabby5:nanaka:~/proj/syncthing$ ldd lib/x86/libsyncthing.so 
>         linux-gate.so.1 =>  (0xb77d7000)
>         libpthread.so.0 => /lib/i386-linux-gnu/i686/cmov/libpthread.so.0 (0xb7793000)
>         libc.so.6 => /lib/i386-linux-gnu/i686/cmov/libc.so.6 (0xb762e000)
>         /lib/ld-linux.so.2 (0xb77da000)
> grabby5:nanaka:~/proj/syncthing$ 

The tablet *does* have **md5** and I checked that this is the same file.

On the tablet I have the LD_LIBRARY_PATH of /system/lib:/vendor/lib and the only related library name I see in there is libc.so (no .6 suffix).

**Comment by AudriusButkevicius** [comment]
it seems that it somehow got shipped dynamically linked. @Nutomic ?

**Comment by AudriusButkevicius** [comment]
You should be able just to swap that out for an official release, given you pick the right arch and rename it correctly.

**Comment by Nutomic** [comment]
IIrc the binaries show as dynamically linked, but it should still work (I'm using the same build process after all).

What happens if you just execute the binary on the phone?

**Comment by AudriusButkevicius** [comment]
I initially though the ELF loader doesn't want to load it, but I can now see that the instructions you've given him are incorrect as the library is in:
`/data/data/com.nutomic.syncthingandroid/lib/x86` rather than `/data/data/com.nutomic.syncthingandroid/lib`

@xplat can you run:
`/data/data/com.nutomic.syncthingandroid/lib/x86/libsyncthing.so`?
Make sure that the file is in that directory though.

**Comment by xplat** [comment]
Actually /data/data/com.nutomic.syncthingandroid/lib/x86/ is a nonexistent directory on the tablet.  It seems the install process selects the architecturally appropriate native libraries to place in /data/data/*package*/lib rather than keeping them all.

After swapping in an official linux-386 release of syncthing (shows as statically linked from file; ldd won't run on it) for /data/data/com.nutomic.syncthingandroid/lib/libsyncthing.so the app seems to run fine; it generated keys, connected to my cluster and synced about half a gig of files.

Nutomic, maybe the binary that shows as dynamically linked should work but it just doesn't seem to on my OEM KitKat...

**Comment by Nutomic** [comment]
Hm that's weird, because the build process should be the same.

@AudriusButkevicius Can you see anything wrong in the [build script](https://github.com/syncthing/syncthing-android/blob/master/build-syncthing.sh#L69)?

**Comment by calmh** [comment]
@Nutomic The "staticness" or not of the linkage depends on how the Go standard library was built. In the "official" build I rebuild the 386 version of the library with CGO disabled (i.e. no dynamic linking) and no SSE instructions to better serve the lowest common denominator. If you use the *official Go* release (i.e. 386 download from golang.org) you'll get the dynamic linkage variant. In this case it seems it needs one or more libraries not present on @xplat's device.

To rebuild the 386 version to be more friendly, do something like this:

```
cd /usr/local/go/src
export CGO_ENABLED=0
export GO386=387
export GOARCH=386
./make.bash --no-clean
```

Keep the same CGO_ENABLED and GO386 envvars set when building the actual binary later.

**Comment by AudriusButkevicius** [comment]
Huh, missed notifications on this one somehow. Calmh already answered.
