### ISSUE TITLE
App keeps crashing after setting fswatcher delay to 0.1 sec

### ISSUE THREAD

**Issue by Jayant-Goyal** [syncthing/syncthing-android#2025]
Hi. I am using the 1.27.0 version of syncthing on Android 11. I set the fs watcher delay of 1 folder to 0.1 sec. Now the app keeps crashing as soon as it starts. How can I fix this without having to full clean and start over.

**Comment by tomasz1986** [comment]
> How can I fix this without having to full clean and start over.

If your device is rooted, then you could try to modify the `config.xml` file directly. Otherwise, you are probably out of luck, meaning that uninstalling and re-installing the app may be your only option.

**Comment by Jayant-Goyal** [comment]
Even though my device it rooted, I can access the data folder in Android using workaround. I searched the internet where to find config.xml but there is only the log file in the data/(syncthing)/files folder.

**Comment by Jayant-Goyal** [comment]
I was not able to access the data folder because my device is not rooted hence I decided to start over. Thanks for your help.

**Comment by tomasz1986** [comment]
Sorry you had to do that. The crash itself isn't normal though. I can set the file watcher to `0.1` on my Android device (also running Android 11) with no issues.

**Comment by Jayant-Goyal** [comment]
Detailed description of what I did:
I am running the syncthing app v1.27.0 on a phone running Android 11. I have multiple folders syncing with my PC from my phone. Some folder are on the internal storage and some are on the SD card that I have put in my phone. I changed the fs watcher delay of one of the folder on my SD card to 0.1 sec. As soon as I clicked save the app closed. I opened it but it kept closing. I tried cleaing cache, didn't work. I tried changing the name of the folder on my SD card to something else so that Syncthing thinks that the folder does not exist anymore hence the fs watcher delay won't matter but that did not help either. I have set it to run only when connect to wifi so I turend the wifi off and opened the app and it asked me to change the run conditions. From there I was able to enable Notify about Syncthing crashes in Debug menu. Then I closed the app and tured wifi on and opened the app again. It closed automatically and when I opened it again it again closed and my system said that Syncthing keeps stopping as it was doing from the start. I checked but there was no notification about crash. I noticed that when I open the app and it closes, there is a notification that says the server is starting but after sometime disappears. In the end I tried to find the config.xml but was unsuccessfull because my phone is not rooted. I ended up just doing clean start.

**Comment by acolomb** [comment]
Just a thought, you might got hit by a bug in the a recent release, see syncthing/syncthing#9269.  It's about to get fixed in the next hotfix release v1.27.1.

In addition, I think your config file might have gotten corrupted by the crash.  So probably your best bet was to start from scratch anyway.  Sorry for the trouble!

**Comment by imsodin** [comment]
At this point this this looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - to continue discussions on this. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
