### ISSUE TITLE
Autostart on connection to a "home" WiFi network

### ISSUE THREAD

**Issue by DragoonAethis** [syncthing/syncthing-android#203]
Essentially, Syncthing service could start automatically while the device connects to a chosen ("home") network. WiFi network should be identified by both SSID and BSSID (usually router's MAC address). This can be done with these:

- https://developer.android.com/reference/android/net/wifi/WifiManager.html (getConnectionInfo)
- https://developer.android.com/reference/android/net/wifi/WifiInfo.html
- `<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />`
- `<action android:name="android.net.wifi.WIFI_STATE_CHANGED"/>` and `<action android:name="android.net.wifi.STATE_CHANGE"/>` in NetworkReceiver `<intent-filter>`.

**Comment by Nutomic** [comment]
There's an option in the settings to run automatically when connected a (any) wifi. 

Now this option does not care which wifi it is connected to, but in my opinion that's enough.

**Comment by DragoonAethis** [comment]
The point of this is just connecting to a single network to save battery. :)

**Comment by Nutomic** [comment]
Imo that's not something that should be in the app, but you can probably do it with tasker or so.

**Comment by AudriusButkevicius** [comment]
:+1:

**Comment by iggs0** [comment]
I have to turning on part running with tasker. So far so good. But I want syncthing to "close" once the wifi disapears to save battery (mobile device - IMPORTANT). This does not really work. Syncthing just stays there.

**Comment by Zillode** [comment]
@iggs0 enable the option 'Sync only on Wifi'

**Comment by Nutomic** [comment]
You could call `localhost:8080/rest/shutdown` from tasker.
