### ISSUE TITLE
photo gallery

### ISSUE THREAD

**Issue by nob13** [syncthing/syncthing-android#204]
Hi great app. I use it to sync a lot of photos on to the android device.

However, how can I add these photos to the (Google) image gallery app when they are to be stored on the external sd-card?

Due to the KitKat problems Syncthing is only allowed to sync into a subdirectory of /storage/sdcard1/Android/data/com.nutomics/syncthingandroid/files. The images however do not show up in the gallery app.

I did not tried the DCIM-Directory because it should'nt mess up with the camera images.

Maybe syncthing-android could offer to save images on Environment.getExternalStoragePublicDirectory(
            Environment.DIRECTORY_PICTURES);

**Comment by AudriusButkevicius** [comment]
Syncing is not handled by the android wrapper but rather syncthing. And syncthing does not have access to the api's you are pointing out.

**Comment by Nutomic** [comment]
That would be possible, but then we'd probably also have to add `DIRECTORY_DOCUMENTS`, `DIRECTORY_MOVIES` etc, which might be rather messy in the UI (there are currently 10 of those dirs, plus those we already have).

Still, this would definitely be useful.

#205 is also related

**Comment by Kernald** [comment]
I'm trying any way to sync images to my SD card (on Lollipop) too, and can't get them to sync anywhere else than `/storage/sdcard1/Android/data/com.nutomics/syncthingandroid/files` - where only Syncthing looks, not the media scanner. If I understand right, even if `Environment.getExternalStoragePublicDirectory(
Environment.DIRECTORY_PICTURES);` is not listed, Syncthing is supposed to have the permission to write to it?
