### ISSUE TITLE
App not working despite phone is connected to wifi

### ISSUE THREAD

**Issue by rgabbo** [syncthing/syncthing-android#2042]
As you can see in the screenshot, my phone is perfectly connected to the wifi but syncthing is reporting that the service is disabled because of the lack of network connection.

![Inkedphoto_2024-01-21_23-09-34](https://github.com/syncthing/syncthing-android/assets/58396985/89b81b5c-fb97-469c-ab22-add790de1270)

### Version Information

    App Version: 1.27.2.1
    Syncthing Version: v1.27.2
    Android Version: Android 13

**Comment by tomasz1986** [comment]
Please make sure that location services are enabled in the Android settings, and also that the Syncthing app is allowed to access location all the time (also in the Android settings). Especially with the latter, allowing it to access location only "while in use" is not enough, it has be all the time.
