### ISSUE TITLE
status about android10 (sony xperia XZ2 phone) and syncthing not being able to write in sdcard folder (DCIM one...)

### ISSUE THREAD

**Issue by iostrym** [syncthing/syncthing-android#2056]
Hello,

using last version of syncthing on my old sony xperia XZ2 phone (android 10, not rooted, last official release of the OS), I can't perform sent and receive synchro on my phone.

I have the message : "Your android version only grants Syncthing readonly access to the selected folder"

I read some post (old ones) and the FAQ but the FAQ is not clear about android10 status... should it work or not ?

On my phone, when I select the DCIM folder on the sdcard, the phone ask me if I want to grand access to the selected folder (famous folder android autorization) but is right that write or read access is not specified in the question asked by android. I say yes but the synchro is still limited to sent only.

is there a solution or a bug in syncthing app ?

something very strange is that I did a lot of trials and maybe I did a mistake but at the end, there was a loop that make the 100ANDRO folder (that contains photo) inside DCIM, being written inside the 100ANDRO folder, and again, 100ANDRO folder inside 100ANDROD folder, and then taking all the sdcard free space.

the "loop" bug is not a problem, I did some trials so maybe I did a mistake but what is strange, is that syncthing was able to create 100ANDRO folder inside 100ANDRO folder... so it means that write access was still possible...

any idea ?

**Comment by tomasz1986** [comment]
Not sure about the specific folder creation loop bug, but Android 11 or newer is required if you want to two-way sync files located on an SD card. The only alternative is running Syncthing as root.

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
