### ISSUE TITLE
Unable to run in background -- unable to set battery usage to Unrestricted

### ISSUE THREAD

**Issue by tarkeez** [syncthing/syncthing-android#2060]
### Version Information

    App Version: 1.27.3
    Syncthing Version: v1.27.3
    Android Version: Android 12 (Onyx Boox software version 3.5)
    Device: Onyx Boox Note Air 3 C

### Description

(The following only happens for syncthing; all other apps I've tested work)

Syncthing is constantly killed and can't run in the background; other apps can, e.g. KDE connect

I am unable to set "Manage battery usage" to "Unrestricted" (see pics below); for other apps, I can set the setting just fine

running `adb shell dumpsys deviceidle whitelist +com.nutomic.syncthingandroid` succeeds in command but does not change setting. For other apps this works

I have another Boox device, running Android 11 -- there syncthing works as expected.

Syncthing-fork behaves exactly the same way.

Strange behaviour when changing battery settings: Picking Unrestricted turns blank, picking Optimized turns to Restricted, picking Restricted stays Restricted.

**Set unrestricted:**
![image](https://github.com/syncthing/syncthing-android/assets/156511381/76c37a31-fbb8-4d0d-837a-51f165a41d41)

**Back out of menu and back in to find it unset:**
![image](https://github.com/syncthing/syncthing-android/assets/156511381/6df0eb48-5d55-4ddf-bd9e-ba4cd33c5213)

**Set "optimized":**
![image](https://github.com/syncthing/syncthing-android/assets/156511381/2b668b9b-7ff4-4cf2-96fd-542217ffce6e)

 **and find it reset to "Restricted":**
![image](https://github.com/syncthing/syncthing-android/assets/156511381/75b6cb95-c185-4911-9080-8d696df89eb1)

**Comment by tomasz1986** [comment]
This looks like some peculiar restrictions imposed by the specific Android device manufacture. I would try to keep Syncthing set to "optimized", and then in the Syncthing app, try enabling "Keep the CPU awake while Syncthing is running" in the Experimental settings.

**Comment by zeeyado** [comment]
I guess it's a device/manufacturing specific thing, but it's really strange that only syncthing (of the apps I've tested) does this, and interesting that it doesn't happen on the A11 build. 

Makes you wonder what is causing it, something specific about how syncthing reports its background service? Any idea how to debug this? Can provide logs etc. 

Maybe look at how KDE connect dealt with it in comparison? I know it has a "persistent notification" setting. Maybe it specifically asked to be exempted frok battery opt/allow to run in background during setup, can't remember.

> try enabling "Keep the CPU awake while Syncthing is running" in the Experimental settings.

Will try this

**Comment by tarkeez** [comment]
I guess it's a device/manufacturing specific thing, but it's really strange that only syncthing (of the apps I've tested) does this, and interesting that it doesn't happen on the A11 build. 

Makes you wonder what is causing it, something specific about how syncthing reports its background service? Any idea how to debug this? Can provide logs etc. 

Maybe look at how KDE connect dealt with it in comparison? I know it has a "persistent notification" setting. Maybe it specifically asked to be exempted frok battery opt/allow to run in background during setup, can't remember.

> try enabling "Keep the CPU awake while Syncthing is running" in the Experimental settings.

Will try this

**Comment by tarkeez** [comment]
So it seems that with enabling "Keep the CPU awake while Syncthing is running" syncthing stays active but loses notification.

Closing as I'm not able to debug this and at least the syncing is working. Will reopen and try to debug if I find the time or syncthing stops working.

Btw the system's "start on boot" setting also works for other apps but not syncthing, so maybe the same reason there for why battery settings won't stick.

**Comment by tarkeez** [comment]
Figured it out for anyone with a boox device who should happen to have done what I did -- I added syncthing to auto start on boot in the android/boox settings, instead of in the syncthing app.

**Comment by neilfranci** [comment]
ugh, nope. This still happens in 1.27.6.2 
I'm on PocoM4 Miui 14 A13 devices.
Even if Autostart on and No Restrictions options are selected the synching app still gets killed after swiping it from the "recent"? On the windows, it just said connection disconnected.
