### ISSUE TITLE
[request] Option to override "Run on" options for folder

### ISSUE THREAD

**Issue by legioner0** [syncthing/syncthing-android#2075]
The default settings "Run on Wi-Fi" and "Run on mobile data" are good enough for work purposes. But at the same time I don't want to waste expensive data plan on uploading personal photos and video via mobile data. I suppose it would be useful to have option to override "Run on" options for each folder.

**Comment by tomasz1986** [comment]
Closing, as the project currently doesn't accept feature request (see [https://github.com/syncthing/syncthing-android#status-maintenance-mode---co-maintainers-welcome](https://github.com/syncthing/syncthing-android#status-maintenance-mode---co-maintainers-welcome)).

You may want to check out Syncthing Fork (see [https://github.com/Catfriend1/syncthing-android](https://github.com/Catfriend1/syncthing-android)), which does have various per-folder configuration settings (although I cannot say for sure that this specific one is there).

**Comment by legioner0** [comment]
ok, thanks for advice.
