### ISSUE TITLE
Windows - .stfolder keep disappearing automatically

### ISSUE THREAD

**Issue by enanotg** [syncthing/syncthing-android#2081]
Using Windows 2019 Server as a "Send Only" shared folder keeps failing with:
"folder marker missing (this indicates potential data loss, search docs/forum to get information about how to proceed)"

Noticed the folder ".stfolder" keeps disappearing automatically without me doing anything.

Version: v1.27.7, Windows (64-bit Intel/AMD)

**Comment by enanotg** [comment]
Some SS:
![image](https://github.com/syncthing/syncthing-android/assets/50530936/3ccdfbcc-957d-49c0-acc0-274712097800)
![image](https://github.com/syncthing/syncthing-android/assets/50530936/0e8d8a60-fc2a-4d17-8832-e0b41c8195e0)

**Comment by bt90** [comment]
If it's not you, then it's an application that's interfering.

As this sounds like a support topic, let's take this to our forum: https://forum.syncthing.net/
