### ISSUE TITLE
Syncthing Linux to/from Android Extremely Slow II

### ISSUE THREAD

**Issue by platise** [syncthing/syncthing-android#2083]
Looks similar to #619 I cannot figure out why transfer rate is around <100 kbps to my PC on one of mine Android. 
Connection is TCP-LAN, network is both ipv4 and ipv6. Please suggest what extra data would you need to debug this down.

While from another Android everything works fine.

### Version Information

    App Version: 1.27.3
    Syncthing Version: v1.27.3
    Android Version: Android 14

**Comment by imsodin** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - https://forum.syncthing.net/ - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

Thanks!
