### ISSUE TITLE
"<options><minHomeDiskFree unit="%">20</minHomeDiskFree></options>" Options exist but not shown on Android Web GUI Advanced

### ISSUE THREAD

**Issue by businessBoris** [syncthing/syncthing-android#2084]
Excuse the perhaps totally incorrect XML nomenclature I've used.

I'd like to set the default "minimum disk free parameter" from the GUI.

Each folder has a node called  'minDiskFree'. 
For example `<minDiskFree unit="%">20</minDiskFree>`
The 'options' node has a node called 'minHomeDiskFree'.
For example `<minHomeDiskFree unit="%">20</minHomeDiskFree>`

One can set the individual minDiskFree values on the folders using the Android Web GUI page,
but one cannot set the default although the option value / XML is there. It simply cannot be seen in the WebGUI on Android.

##     what happened,
I wanted to set the default Minimum Space Required on Android Syncthing using the `[Gear wheel] | Advanced`.

##     what you expected to happen instead

I expected to find the Minimum Space Required double dialogue items (number, representation (% etc)).
The value (probably) exists in the config XML but is not shown and the default cannot be set.

## any steps to reproduce the problem.

Try to set the default `Minimum Space Required`

I can't provide screenshots because the I'm trying to show the absence of an item in the screen dialog.
I'm sure everyone has had the Amazon message "Provide proof your item has not arrived" and they reply with an empty hand photo.

### Version Information

    App Version: 1.27.3
    Syncthing Version: v1.27.3
    Android Version: Android 14   AP1A.240505.005   (5 May 2024 security update)

**Comment by tomasz1986** [comment]
The option seems to be missing from the Advanced Configuration in the Web GUI in general. Because of this, I think the issue should be moved to the regular https://github.com/syncthing/syncthing/issues tracker, as doesn't seem to be specific to Android in any way.

**Comment by imsodin** [comment]
You can set defaults, including free disk space, in standard settings at the bottom of the general tab, no need to go to advanced. It's likely not in the advanced settings, as it is an object (value plus unit), and advanced settings are generated and can only deal with simple values.
