### ISSUE TITLE
Problem with android files (particularly directories) with trailing spaces in the name

### ISSUE THREAD

**Issue by p-d-hodgson** [syncthing/syncthing-android#2094]
In Android, it is possible to create files and folders with names with trailing spaces. When these are sync'd to a Windows machine, certain problems can arise, particularly with folders. For instance, if you have a folder that has been sync'd to Windows and you try to delete it in Windows File Explorer you get a very confusing message saying that the file does not exist, similarly, if you press F2 (to rename the folder) it opens the name to edit... if you remove the space it says the name is not changed, if you change anything else it says the file does not exist. (There is a known workaround published on the web where you have to use WinRAR to archive the file and remove it, then you can delete the archive).

The problem occurs more frequently because autocomplete using the proposed word list above the keyboard, on my Android phone, adds a space at the end of the selected word.

Is there a way to avoid this? e.g. add a configuration parameter that says what to do with filenames with trailing spaces

### Version Information

    App Version: 1.27.3 (on Android)
    Syncthing Version: v1.27.9 (on Windows)
    Android Version: Android 12 / Cyanogenmod x / ...

**Comment by tomasz1986** [comment]
This is a common problem, not really related to Syncthing per se, when using different operating and file systems. In general, if you want to make sure that your filenames are compatible with all of them, you should follow the FAT conventions (see https://averstak.tripod.com/fatdox/names.htm). When it comes to Syncthing, there currently is no way to work around this other than manually renaming the files.

Closing the issue, as this problem isn't really related to the Syncthing app for Android. You may want to follow https://github.com/syncthing/syncthing/issues/9539, which discusses and proposes possible solutions on how to deal with illegal characters.
