### ISSUE TITLE
Feature Request: Shizuku for **non-root**, R/W access to `/storage/emulated/0/Android/Data/**` on Android 14 and later

### ISSUE THREAD

**Issue by BinToss** [syncthing/syncthing-android#2097]
Re: https://github.com/syncthing/syncthing-android/issues/1883

Disclaimer: some files and subdirectories are inaccessible even with ADB privileges.

Android 13, you could use Android's [SAF](https://developer.android.com/guide/topics/providers/document-provider) to prompt for access to folders under `.../Android/Data/`. Android 14 just denies access.

[Some users have been able to bypass this restriction via the Web GUI](https://www.reddit.com/r/Syncthing/comments/wgxlvc/comment/jwc0i62/), but [there are complications user must overcome](https://www.reddit.com/r/Syncthing/comments/wgxlvc/comment/kgi96lk/).

> Do not file a feature request unless you want to implement it yourself. This is
due to the maintenance status of this project, see [the readme for
context](https://github.com/syncthing/syncthing-android#status-maintenance-mode---co-maintainers-welcome).

I can get around to implementing this in...over a year from now. I have too many other higher-priority commitments.

# notes
https://web.archive.org/web/20240705000016/https://zdevs.ru/en/za/android_data_obb.html

- ZArchiver's UX of Shizuku integration is a good example. https://web.archive.org/web/20240705000016/https://zdevs.ru/en/za/android_data_obb.html
- Shizuku's service cannot start on boot without root. Non-root users should be guided to re-enable Wireless Debugging in Android's "Settings > System > Developer Settings" (you can use an app activity to go to that setting!) after every boot. Also, users should be recommended to enable "Disable adb authorization timeout" just below "Wireless debugging" so they don't need to re-pair Shizuku with wireless debugging every week. If setting up Shizuku for the first time, user should refer to [Shizuku's instructions](https://shizuku.rikka.app/guide/setup/#start-via-wireless-debugging).
  - User have created Automate flows to aid and/or automate at-boot startup of Shizuku's service. https://llamalab.com/automate/community/?q=shizuku
- Shizuku functionality should be used via [Shizuku-API](https://github.com/RikkaApps/Shizuku-API?tab=readme-ov-file#guide).
- To use this feature, users will need to use the advanced folder picker—typing the directory path they want to sync. The system file picker will not leverage Shizuku for ADB-privileged access.
- Source Code
  - https://github.com/syncthing/syncthing-android/blob/main/app/src/main/AndroidManifest.xml
    - Add Shizuku manifest modifications
  - https://github.com/syncthing/syncthing-android/blob/main/app/src/main/java/com/nutomic/syncthingandroid/util/PermissionUtil.java
    - add Shizuku's custom permissions?
  - https://github.com/syncthing/syncthing-android/blob/5b50f72a3d36b8d3185562530fff7ea61d590e38/app/src/main/java/com/nutomic/syncthingandroid/util/Util.java#L178-L184
    - users _must_ [set up `rish`](https://github.com/RikkaApps/Shizuku-API/tree/master/rish)
- syncthing-fork had a similar feature request. It was closed as "won't implement" because users can use the web gui to bypass the permissions issue.

**Comment by imsodin** [comment]
https://github.com/syncthing/syncthing-android?tab=readme-ov-file#no-feature-request-taken-feature-contributions-case-by-case

**Comment by BinToss** [comment]
Acknowledged. This is more of a reminder for myself.
