### ISSUE TITLE
Initial scanning of folder causes app to slow and eventually freeze device...

### ISSUE THREAD

**Issue by cattledogit** [syncthing/syncthing-android#210]
...requiring that battery be removed to restart. This happened first at 200 files and ~2GB, and again at 300 files and ~6GB. Folder is ~14GB. v. 0.5.16, Note 2, 4.4.2.

After a couple of restarts it did finish scanning (~3K files, 15GB).

**Comment by Nutomic** [comment]
I haven't experienced this myself. To me, it sounds like a problem with the ROM. 

Anyway, we need a logcat for this.

**Comment by Zillode** [comment]
I think this should be fixed by https://github.com/syncthing/syncthing-android/commit/2bac0d9504957d41eb5acd7eb9ff8b63be08833e
