### ISSUE TITLE
[Bug] Android application doesn't notify about new Folder Shares

### ISSUE THREAD

**Issue by Arcitec** [syncthing/syncthing-android#2104]
Thanks for an amazing application!

I've noticed a bug (?) though. When you connect to a remote device from the Android app, you will not be notified by the Android app that there's a new Folder Share available.

You have to go into the menu and "Web GUI" on the phone, and then manually add the share via the Web's "detected a new share" banner. Because the Web interface detects the new folders correctly.

As far as I've been able to see from older YouTube videos, the Syncthing app for Android is supposed to detect new shares in the main app GUI too and should not require usage of the Web version for accepting shared folders?

### Version Information

    App Version: 1.27.10 (FDroid)
    Syncthing Version: v1.27.12, Linux (64-bit Intel/AMD Container)
    Android Version: Android 10 (Huawei EMUI 12)

**Comment by tomasz1986** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - [forum.syncthing.net](https://forum.syncthing.net/) - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

For the record, I think you may want to look into your OS settings and check whether the app is allowed to run in background and show notifications. This is especially so on Chinese Android ROMs, which are known to heavily limit background app activity.

**Comment by Arcitec** [comment]
@tomasz1986 No, it's not a support request. It's a bug report.

> I think you may want to look into your OS settings and check whether the app is allowed to run in background

It is. I have disabled Battery Optimizer for the app so that it can run in the background, and the background service + persistent notification are enabled.

> and show notifications.

It is. I see the persistent "Syncthing is running" notification from the background service.

Does Syncthing on your Android device show notifications for detected folders? Or do you have to visit the Web GUI to see it just like I do?

**Comment by tomasz1986** [comment]
> No, it's not a support request. It's a bug report.

I understand that the problem exists on your device, but it's non-actionable on our side. The notifications do work on stock Android, so unless there is a developer that owns a device from the same manufacturer and experience the same problem, nothing can be done about it at this point.

Without having direct access to the device in question, we would need to have at least debug logs from Android itself (i.e. `logcat`) that would show what actually happens in the background when the app is supposed to show a notification. When it comes to dealing with Syncthing issues, all this kind of investigating is usually done on the forum first, not here.

**Comment by Arcitec** [comment]
@tomasz1986 Ah, thanks for letting me know that it's trying to send notifications. It's weird because local notifications and push notifications work in all my other apps (I have hundreds). I'll help debug this with logcat later (adding to my todo list). :)
