### ISSUE TITLE
Use synthing for keepass

### ISSUE THREAD

**Issue by enboig** [syncthing/syncthing-android#2105]
### Version Information

    Syncthing Version: v1.27.10
    Android Version: lineageOS 21

I had a phone with old rom, now upgraded to lineageOS 21 and discovered I cannot use it sync my keepass passwords.

I have read #1366 , is this still a issue? I checked the work around in the wiki, but didn't understood how it helps me to sync "up and down" my passwords.

**Comment by tomasz1986** [comment]
This looks more like a support request than a clear bug or feature request. Please use the forum - [forum.syncthing.net](https://forum.syncthing.net/) - for support, first by searching for any similar issues and then by posting a new one when required. The forum has a lot more eyes and friendly people on it than the issue tracker.

When creating a new topic on the forum, please include information such as the exact path of your KeePass database and also the specific KeePass app that you're using on Android.
