### ISSUE TITLE
Please Support Multi User Mode as when one user has Synching running others are unable to start Synching

### ISSUE THREAD

**Issue by SubZero5** [syncthing/syncthing-android#2107]
We use devices in business environment and share device across multiple (3~4) users in their shifts. Each user has its own user account created on the device. Each profile has its own Synching app installed on their own user profile. If one of the users have Synching on or left running in their profiles, the others are unable to start Synching.

Device:
Pixel 2 XL
Android 14
LineageOS 21

**Comment by tomasz1986** [comment]
This is already supported if you adjust the GUI listen address in the app settings. For example, by default it is set to `8384`, but you can change that to `8385`, 8386`, etc. for the other profiles. You also need to do a few other port-related tweaks inside the Advanced Configuration once you've got the GUI running (see https://forum.syncthing.net/t/two-users-on-the-same-machine/18218/2).
