### ISSUE TITLE
Web UI's popups are making interaction with UI impossible on small screen

### ISSUE THREAD

**Issue by SpiritQuaddicted** [syncthing/syncthing-android#211]
If I open the Web UI on my 800x480 device, all I can see is the popup that asks me to share anonymous statistics (I unchecked that in the app already?). If I try to scroll down or zoom, I can see the scrollbar move, but the popup stays in place. This makes the Web UI impossible to use.

**Comment by Nutomic** [comment]
@calmh @AudriusButkevicius ^

If you already changed the setting in the app, I'm probably setting a wrong value, too.

**Comment by Nutomic** [comment]
Closing this here, please reopen at [syncthing](https://github.com/syncthing/syncthing) if it still happens.
