### ISSUE TITLE
adding comma separated dns-names/ip-addresses inserts duplicated comma

### ISSUE THREAD

**Issue by kmindi** [syncthing/syncthing-android#212]
In the edit screen of the web-interface it displays two commas, whereas in the edit mask of the app it is either not shown , or only one comma is shown...

**Comment by napseis** [comment]
hi, could you tell wichi one works for you ? I don't get to make it work via internet, despite i put the ddns of my server...

**Comment by kmindi** [comment]
I'm afraid not. I'm not using it right now.

**Comment by Zillode** [comment]
@napseis : DNS addresses are not supported in syncthing-android due to an upstream bug, see https://github.com/syncthing/syncthing-android/issues/57
