### ISSUE TITLE
Non-0 scan interval as default

### ISSUE THREAD

**Issue by ndarilek** [syncthing/syncthing-android#213]
Perhaps this isn't an issue but is a misunderstanding on my part. Yesterday I installed the app and experienced the slowdown on initial scans that others have reported here (I'll get a logcat next time, at that moment I was trying to get Syncthing working across several machines so wasn't ready to debug individual issues less significant than "the whole thing isn't working everywhere." :)

When I loaded my folder configuration, I noticed the scan interval was set to 0. This is not the default on either my Windows desktop or on my Linux server.

Does Syncthing/the app use inotify or something if the scan interval is set to 0? If not, might setting a scan interval to 0 cause excessive rescanning of files and poor performance?

If 0 is a bad default, should it be changed to 60 to reflect the other interfaces? I've been changing it manually but it's a slightly annoying step which I don't think should be needed when configuring a new folder.

Thanks.

**Comment by Nutomic** [comment]
Yep, there's inotify and scan interval 0 disables syncthing's built-in scanner ;)
