### ISSUE TITLE
Texts in landscape ari Icons in portrait mode of tablet pc

### ISSUE THREAD

**Issue by merlinuwe** [syncthing/syncthing-android#214]
When I rotate my galaxy tab 3 7" into "portrait" mode, I see darkgrey icons instead of the texts "Aktuell" and "getrennt".

**Comment by AudriusButkevicius** [comment]
That is intentional.
When we lack width we replace the text with green/blue/grey/orange squares to represent the status.

**Comment by AudriusButkevicius** [comment]
Is this in the web ui?
If it is, then that is intentional.
When we lack width we replace the text with green/blue/grey/orange squares to represent the status.
