### ISSUE TITLE
Cannot exit the app properly

### ISSUE THREAD

**Issue by Ondalf** [syncthing/syncthing-android#217]
Hi,

Even if I check or leave unchecked "run in background", the exit button doesn't appear. I saw it ONCE and never after it. I'd like this program to work when background, when charging (like it works, and it works well), but when I change it back to non-background operating mode, there's no exit button and it might suddenly start syncing leaving message to notification area. Even if I have unchecked the background mode. I think the service doesn't stop or it randomly reruns the program and starts syncing.

Please let me know, how to help debugging this matter.

-Ondalf

**Comment by Nutomic** [comment]
I just fixed a bug where the exit button would not be added or removed until app restart.

Until I'm updating the app, you can work around this by exiting the app with the back button.

Please reopen/comment if you meant something else ;)
