### ISSUE TITLE
There is no Windows build script

### ISSUE THREAD

**Issue by carstenhag** [syncthing/syncthing-android#219]
There already is a shell script that downloads the binaries and what-not, it would be great for us Windows users/developers to have a script too get this stuff.

Android Studio always complains about starting the build-syncthing.sh script:

```
Error:Execution failed for task ':buildNative'.
> A problem occurred starting process 'command './build-syncthing.sh''
```

**Comment by Nutomic** [comment]
The instructions [here](https://github.com/syncthing/syncthing-android#getting-syncthing-without-building-natively) should be a workaround. However, the build.gradle needs to be changed to remove references to `build-syncthing.sh`: [updated build.gradle](https://gist.github.com/Nutomic/b1953b230e07f373067a).

@Zillode What are your thoughts on a windows build?

**Comment by Zillode** [comment]
I'm not planning to write a .bat script. I could rewrite it in Ruby but this introduces another dependency.
So I guess 'wontfix' unless someone provides an alternative or you want me to write to Ruby version.

**Comment by AudriusButkevicius** [comment]
Write it in Go. You need Go to compile syncthing anyway.

**Comment by Nutomic** [comment]
Right, cygwin would be an option, though I don't know if that works with gradle.

I'm not gonna fix this either, so it's up for grabs :)

**Comment by Nutomic** [comment]
I just noticed there was a bounty on this issue. @AudriusButkevicius you should claim that ;) (if you dont want it, just put it towards another issue)
