### ISSUE TITLE
AP white/black list

### ISSUE THREAD

**Issue by MauroMombelli** [syncthing/syncthing-android#221]
A suggestion, can you implement some sort of black and white list?
It is common to find around limited wifi (in speed or quantity), so it would be nice to automatically prevent the app from  sucking all the juice on know AP.

**Comment by Nutomic** [comment]
Honestly, that sounds way too complicated, seeing as "sync on wifi" is more of an an ancillary option.

If you need this, you should disable "always run in background", or use an external app like tasker (see #91).
