### ISSUE TITLE
dst create chmod operation not permitted

### ISSUE THREAD

**Issue by Gregy** [syncthing/syncthing-android#222]
Synchronization gets stuck at ~80 percent and android log is full of messages like these:
```
03-05 21:43:03.525 I/SyncthingNativeCode(32092): [6PY5D] 20:43:03 INFO: Puller (folder "telefon", file "Abaddon's gate/Abaddon's Gate (Unabridged) Part 1.m4a"): dst create chmod: chmod /storage/sdcard1/sync/Abaddon's gate/.syncthing.Abaddon's Gate (Unabridged) Part 1.m4a: operation not permitted
```

Ignore permissions setting is set on both android and remote node. I tried to delete everything and start from scratch. That worked for a while but same thing happened again.

I am using version 0.5.17 on android and v0.10.24 on the other linux node.

Thank you for any tips.

**Comment by Zillode** [comment]
@Gregy could you reply to https://github.com/syncthing/syncthing/issues/1404#issuecomment-77520130 ?

**Comment by Zillode** [comment]
Fixed, see https://github.com/syncthing/syncthing/issues/1404
