### ISSUE TITLE
Announce server not accessible ?

### ISSUE THREAD

**Issue by Salamandar** [syncthing/syncthing-android#227]
Every minute i think, i got this error (visible on the web interface) :
discover udp6://announce-v6.syncthing.net:22026: broadcast: stat /etc/resolv.conf: no such file or directory; trying again in 1m0s

**Comment by AudriusButkevicius** [comment]
This is fixed in the master branch, and you need to wait for a new release.

**Comment by Salamandar** [comment]
That's great, thanks :)
