### ISSUE TITLE
Could not support chinese of folder ID and directory

### ISSUE THREAD

**Issue by renyouguo** [syncthing/syncthing-android#228]
Android 4.4.4
Syncting 0.5.18

**Comment by Nutomic** [comment]
What exactly happens, is there an error message?

Does it work if you use the web GUI?

**Comment by renyouguo** [comment]
When I creat folder ID "司考"，error message:
The folder ID must be a short indentifier(64 characters or less)consisting of letters,numbers and the dot(.),dash(-) and underscode(_) characters only.

The error message shows by chinese in the web GUI either.

**Comment by Nutomic** [comment]
Sorry I don't understand, does it work in the web GUI or not?

@calmh @AudriusButkevicius Is this something we can/want to support?

**Comment by renyouguo** [comment]
Not，it does not work in the web GUI.
It is ok in PC.

**Comment by Nutomic** [comment]
For the folder ID, you'll have to open an issue at syncthing/syncthing.

**Comment by mapleshadow** [comment]
Please repair, there still exist the problem.
Folder, garbled, no recognition

**Comment by Nutomic** [comment]
I haven't updated the app yet, it will be fixed in the next release (I'll probably make one today).

**Comment by mapleshadow** [comment]
The new version of flash back......
Date: 2015-3-15 version
My system: Android 5.0.2 CM12
