### ISSUE TITLE
Where are private keys stored?

### ISSUE THREAD

**Issue by viric** [syncthing/syncthing-android#229]
Are the private keys stored without cipher in the filesystem, so other processes can read them?

I couldn't find this documented.

Thank you.

**Comment by Nutomic** [comment]
They are stored in `/data/data/com.nutomic.syncthingandroid/files` which can only accessed by the app itself, or by root users.

Where would you document this?

**Comment by viric** [comment]
I think that this issue is enough. Thank you!
