### ISSUE TITLE
Support GCM?

### ISSUE THREAD

**Issue by renyouguo** [syncthing/syncthing-android#230]
Push message by GCM just like BtSync.

**Comment by Nutomic** [comment]
What do you mean? What exactly would this do?

**Comment by renyouguo** [comment]
I want to set syncthing to run only while get the files changed message pushed by GCM.

**Comment by StrikerTwo** [comment]
So every node that adds a change would somehow have to know which of it's peers are Android devices and what GCM token they use? That's certainly not something syncthing-android can implement all alone.

**Comment by Nutomic** [comment]
Do you perhaps mean #130? That doesn't need GCM.

**Comment by Zillode** [comment]
No he means launching syncthing on android only when other nodes have changes. But I'd advice to not depend on GCM infrastructure.
@renyouguo just keep Syncthing running all the time in the background, it will do exactly what you want at the expense of a little bit of ram but with much faster syncing time.

**Comment by Nutomic** [comment]
This would also need some kind of support in syncthing directly, and I really doubt that will happen.

Also not a fan of this myself.
