### ISSUE TITLE
Could not support baidu's wifi

### ISSUE THREAD

**Issue by renyouguo** [syncthing/syncthing-android#234]
http://wifi.baidu.com/

It makes PC to be wifi.
BtSync is ok by the baiduwifi at the same time.However,in syncthing,my phone could not be found,never.

**Comment by Nutomic** [comment]
So it opens a Wifi on the PC and the phone connects to that Wifi?

@calmh @AudriusButkevicius Sounds like an upstream problem.

**Comment by AudriusButkevicius** [comment]
Sorry how is this different from a normal access point?

**Comment by renyouguo** [comment]
@Nutomic Yes.
@AudriusButkevicius I do not know.
The wifi is ok all the time,it is in the same Lan with the PC.
BtSync is working by it now.

**Comment by AudriusButkevicius** [comment]
Is local discovery enabled on both devices?

**Comment by renyouguo** [comment]
@AudriusButkevicius Yes.

**Comment by AudriusButkevicius** [comment]
You should try running wil STTRACE=discovery environment variable, and also make sure that both devices are in the same subnet.

**Comment by renyouguo** [comment]
How？

**Comment by AudriusButkevicius** [comment]
Sadly if you don't know how todo these things, it will be very hard for me to help you. 

Best I can suggest is googling around. Hopefully syncthing will eventually be end user friendly not to require a Computer Science degree to run :(

**Comment by renyouguo** [comment]
I will try my best to study it……

**Comment by Nutomic** [comment]
@AudriusButkevicius I don't have my degree yet, and I can already use it, woo :D 

@renyouguo For Android, there's a setting called debug settings for this.

**Comment by AudriusButkevicius** [comment]
i guess the first step would be to provide the IPs of both devices together with the subnet mask.
