### ISSUE TITLE
With "Sync only on Wifi" active, it keeps running when both Wifi and data are off.

### ISSUE THREAD

**Issue by pinapl** [syncthing/syncthing-android#235]
Steps to reproduce:
Open app.
Make sure "Sync only on Wifi" is enabled.
Turn Wifi on, turn data (4G, 3G, EDGE, etc) off.
The app will run and try to sync since Wifi is on.
Turn Wifi off, do not turn data on. This takes away its internet connection.
The app will still run and try to connect to other devices.

What I expect to happen instead:
When Wifi is off, syncthing should stop running until a wifi connection is re-established.

My assumption from this behavior is that the app uses the data on/off state as its indicator of whether Wifi is on or off. If data is active, wifi is assumed to be off; If data is inactive, wifi is assumed to be on. 

Phone: Samsung Galaxy Note 3 (SM-N900V) on Verizon Wireless.
Android version: 4.4.2 Kitkat (Rooted)
Version: Google Play 0.5.18.

**Comment by Nutomic** [comment]
So it works as long as you don't change data state?

Sounds like NetworkReceiver should ignore intents with `wifiInfo == null`.

**Comment by pinapl** [comment]
That's right.
Sorry for the late reply, but that's exactly what's going on. When data is off, the app doesn't appear to notice when Wifi is off.
This probably doesn't affect most people, but I turn both data and wifi off to save battery when I'm at work or in church where LTE is gobbled up and Wifi is spotty.

**Comment by Nutomic** [comment]
So if you keep data disabled, and toggle WiFi on/off, the app also doesn't notice that?

**Comment by pinapl** [comment]
That's right. I recorded a [video](Unlisted video - Syncthing looking at wifi: http://youtu.be/MqiiyipPFQ0)
