### ISSUE TITLE
When rotated Syncthing stops working

### ISSUE THREAD

**Issue by fcastilloec** [syncthing/syncthing-android#236]
When I rotate my phone the Syncthing app just stops working, all devices are shown as disconnected and the side panel doesn't show any information on the current device. The only way to fix this is to restart syncthing.
I'm using a Nexus 5 with Android 5.1

**Comment by Nutomic** [comment]
I just tried this, and it seems there is a bit of delay until that info is displayed again. But after a few seconds, it shows up again.

This is because the fragments are recreated on rotate, and have to connect to the service again. I can't think of a good way to fix this.

**Comment by Zillode** [comment]
Use static variables to retain the retrieved values from ST. Then onCreate, you need to fill the fields (maybe using an updateView method).

**Comment by Nutomic** [comment]
Just tried this again in 0.6.1 and couldn't reproduce it.

Please reopen with a log if you get it again.
