### ISSUE TITLE
0.5.19: crash after update and even after reinstalling

### ISSUE THREAD

**Issue by merlinuwe** [syncthing/syncthing-android#238]
I soon updated to 0.5.19.
The application crashes, even after a complete deinstallation and new install. (I sent some reports via the tablet.)
The device is a Samsung Galaxy Tab 3 7" with Android 4.4.2

When I start Syncthing on my PC, I get the following message:

17:57:18: Folder "Tab3Download" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.

Can I solve the problem by myself or is it caused by a bug of syncthing-android?

Greetings,

Uwe

**Comment by marcelpaulo** [comment]
Same problem here, with `Android 4.4` on a `Motorola E XT1022`. Also tried uninstalling/reinstalling from scratch, but syncthing keeps on crashing.

**Comment by marcelpaulo** [comment]
@merlinuwe, I've just discovered that `F-Droid` allows you to install previous versions of the software it hosts, so, as a workaround, you can install `0.5.18` from [F-Droid](https://f-droid.org/). I installed their client, searched for `syncthing` and then chose version `0.5.18` to install.

**Comment by jonathanmtran** [comment]
OnePlus One (Android 4.4.4) here. I did what @marcelpaulo did as well and installed the previous version from F-Droid

**Comment by chucic** [comment]
Same here: Crash after start. When I choose "Report" and "Show", it says it is java.lang.NullPointerException in DevicesAdapter.java line 76.

I didn't actually send report to google yet. Shall I? Will it get to you? It seems it will contain system log and event log...

**Comment by redjamesg** [comment]
I see the same issue, here is a logcat of what is happening on my device.
ActivityManager: START u0 {cmp=com.nutomic.syncthingandroid/.activities.MainActivity} from uid 10079 on display 0
03-14 21:03:18.283   557   876 W ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.nutomic.syncthingandroid/.activities.MainActivity }
03-14 21:03:18.341   557   571 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@24dd701a attribute=null, token = android.os.BinderProxy@3477b960
03-14 21:03:18.543   733   733 D PhoneStatusBar: disable: < expand icons* alerts system_info* back home recent clock search >
03-14 21:03:18.805  4833  5638 D OpenGLRenderer: Render dirty regions requested: true
03-14 21:03:18.816  4833  4833 D Atlas   : Validating map...
03-14 21:03:18.882  4833  5638 I Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.AF.1.1_RB1.05.00.00.006.012_msm8960_LA.AF.1.1_RB1__release_AU ()
03-14 21:03:18.882  4833  5638 I Adreno-EGL: OpenGL ES Shader Compiler Version: E031.25.03.00
03-14 21:03:18.882  4833  5638 I Adreno-EGL: Build Date: 01/04/15 Sun
03-14 21:03:18.882  4833  5638 I Adreno-EGL: Local Branch: mybranch6743007
03-14 21:03:18.882  4833  5638 I Adreno-EGL: Remote Branch: quic/LA.AF.1.1_rb1.8
03-14 21:03:18.882  4833  5638 I Adreno-EGL: Local Patches: NONE
03-14 21:03:18.882  4833  5638 I Adreno-EGL: Reconstruct Branch: NOTHING
03-14 21:03:18.883  4833  5638 I OpenGLRenderer: Initialized EGL, version 1.4
03-14 21:03:18.902  4833  5638 D OpenGLRenderer: Enabling debug mode 0
03-14 21:03:18.943   557   574 D Sensors : LightSensor readEvents x = 2.000000, raw = 2
03-14 21:03:18.943  4833  4833 W RestApi : Failed to read devices
03-14 21:03:18.943  4833  4833 W RestApi : org.json.JSONException: Value metadata at Compression of type java.lang.String cannot be converted to boolean
03-14 21:03:18.943  4833  4833 W RestApi : 	at org.json.JSON.typeMismatch(JSON.java:100)
03-14 21:03:18.943  4833  4833 W RestApi : 	at org.json.JSONObject.getBoolean(JSONObject.java:413)
03-14 21:03:18.943  4833  4833 W RestApi : 	at com.nutomic.syncthingandroid.syncthing.RestApi.getDevices(RestApi.java:410)
03-14 21:03:18.943  4833  4833 W RestApi : 	at com.nutomic.syncthingandroid.fragments.DevicesFragment.initAdapter(DevicesFragment.java:61)
03-14 21:03:18.943  4833  4833 W RestApi : 	at com.nutomic.syncthingandroid.fragments.DevicesFragment.onApiChange(DevicesFragment.java:44)
03-14 21:03:18.943  4833  4833 W RestApi : 	at com.nutomic.syncthingandroid.syncthing.SyncthingService.registerOnApiChangeListener(SyncthingService.java:363)
03-14 21:03:18.943  4833  4833 W RestApi : 	at com.nutomic.syncthingandroid.activities.MainActivity.onServiceConnected(MainActivity.java:214)
03-14 21:03:18.943  4833  4833 W RestApi : 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1204)
03-14 21:03:18.943  4833  4833 W RestApi : 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1221)
03-14 21:03:18.943  4833  4833 W RestApi : 	at android.os.Handler.handleCallback(Handler.java:739)
03-14 21:03:18.943  4833  4833 W RestApi : 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-14 21:03:18.943  4833  4833 W RestApi : 	at android.os.Looper.loop(Looper.java:135)
03-14 21:03:18.943  4833  4833 W RestApi : 	at android.app.ActivityThread.main(ActivityThread.java:5256)
03-14 21:03:18.943  4833  4833 W RestApi : 	at java.lang.reflect.Method.invoke(Native Method)
03-14 21:03:18.943  4833  4833 W RestApi : 	at java.lang.reflect.Method.invoke(Method.java:372)
03-14 21:03:18.943  4833  4833 W RestApi : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
03-14 21:03:18.943  4833  4833 W RestApi : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
03-14 21:03:18.943  4833  4833 D AndroidRuntime: Shutting down VM
03-14 21:03:18.944  4833  4833 E AndroidRuntime: FATAL EXCEPTION: main
03-14 21:03:18.944  4833  4833 E AndroidRuntime: Process: com.nutomic.syncthingandroid, PID: 4833
03-14 21:03:18.944  4833  4833 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at com.nutomic.syncthingandroid.util.DevicesAdapter.add(DevicesAdapter.java:76)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at com.nutomic.syncthingandroid.fragments.DevicesFragment.initAdapter(DevicesFragment.java:61)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at com.nutomic.syncthingandroid.fragments.DevicesFragment.onApiChange(DevicesFragment.java:44)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at com.nutomic.syncthingandroid.syncthing.SyncthingService.registerOnApiChangeListener(SyncthingService.java:363)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at com.nutomic.syncthingandroid.activities.MainActivity.onServiceConnected(MainActivity.java:214)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1204)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1221)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5256)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
03-14 21:03:18.944  4833  4833 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
03-14 21:03:18.945   557  1026 W ActivityManager:   Force finishing activity com.nutomic.syncthingandroid/.activities.MainActivity
03-14 21:03:19.248   557  1026 I WindowManager: Screenshot max retries 4 of Token{1f59510e ActivityRecord{2f3a7b09 u0 com.nutomic.syncthingandroid/.activities.MainActivity t4115 f}} appWin=Window{2ab0f16c u0 com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.MainActivity} drawState=1
03-14 21:03:19.249   557  1026 E ActivityManager: Invalid thumbnail dimensions: 288x288
03-14 21:03:19.251   557  1026 W ActivityManager:   Force finishing activity com.readystatesoftware.ghostlog/.MainActivity
03-14 21:03:19.333   557  3394 I OpenGLRenderer: Initialized EGL, version 1.4
03-14 21:03:19.750   557   577 W ActivityManager: Activity pause timeout for ActivityRecord{2f3a7b09 u0 com.nutomic.syncthingandroid/.activities.MainActivity t4115 f}
03-14 21:03:19.796  1944  1944 D Finsky  : [1] DetailsDataBasedFragment.rebindViews: Page [class=DetailsFragment2] loaded in [24040 ms] (hasDetailsDataLoaded? false)
03-14 21:03:19.877  1944  1944 D Finsky  : [1] DetailsDataBasedFragment.rebindViews: Page [class=DetailsFragment2] loaded in [24118 ms] (hasDetailsDataLoaded? true)
03-14 21:03:19.896  1944  1944 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1e608747 time:936314
03-14 21:03:19.943   557   574 D Sensors : LightSensor readEvents x = 3.000000, raw = 3
03-14 21:03:20.282   557   589 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{2690235a u0 com.android.vending/com.google.android.finsky.activities.MainActivity t4112} time:936700
03-14 21:03:20.945   557   574 D Sensors : LightSensor readEvents x = 3.000000, raw = 3
03-14 21:03:21.397   217   641 D ALSADevice: standby: handle 0xb7c61848 h 0x0
03-14 21:03:21.438   217   641 D alsa_ucm: snd_use_case_set(): uc_mgr 0xb7c40280 identifier _verb value Inactive
03-14 21:03:21.438   217   641 D alsa_ucm: Set mixer controls for HiFi Lowlatency enable 0
03-14 21:03:21.438   217   641 D alsa_ucm: Setting mixer control: PRI_RX Audio Mixer MultiMedia5, value: 0
03-14 21:03:21.440   217   641 D alsa_ucm: snd_use_case_set(): uc_mgr 0xb7c40280 identifier _disdev value Speaker
03-14 21:03:21.440   217   641 D alsa_ucm: Set mixer controls for Speaker enable 0
03-14 21:03:21.440   217   641 D alsa_ucm: Setting mixer control: RX4 MIX1 INP1, value: ZERO
03-14 21:03:21.442   217   641 D alsa_ucm: Setting mixer control: SLIM RX1 MUX, value: ZERO
03-14 21:03:21.443   217   641 D alsa_ucm: Setting mixer control: SPK DAC Switch, value: 0
03-14 21:03:21.444   217   641 D alsa_ucm: Setting mixer control: RX4 Digital Volume, value: 0
03-14 21:03:21.445   217   641 D alsa_ucm: Setting mixer control: SPK DRV Volume, value: 0
03-14 21:03:21.445   217   641 D AudioUsbALSA: exitPlaybackThread, mproxypfdPlayback: -1
03-14 21:03:21.445   217   641 D AudioUsbALSA: closeDevice handle 0x0
03-14 21:03:21.445   217   641 D AudioUsbALSA: closeDevice handle 0x0
03-14 21:03:21.475   853   853 I wpa_supplicant: wlan0: CTRL-EVENT-SCAN-STARTED 
03-14 21:03:21.503  1717  1797 D HeadsetStateMachine: Disconnected process message: 10, size: 0
03-14 21:03:21.943   557   574 D Sensors : LightSensor readEvents x = 1.000000, raw = 1
03-14 21:03:22.943   557   574 D Sensors : LightSensor readEvents x = 3.000000, raw = 3
03-14 21:03:22.953   557   691 E AudioTrack: AudioTrack::set : Exit
03-14 21:03:22.961  4833  4833 I Process : Sending signal. PID: 4833 SIG: 9
03-14 21:03:22.961   217   640 D ALSADevice: route: devices 0x2 in mode 0
03-14 21:03:22.961   217   640 D ALSADevice: No valid input device: 0
03-14 21:03:22.961   217   640 D alsa_ucm: snd_use_case_set(): uc_mgr 0xb7c40280 identifier _enadev value Speaker
03-14 21:03:22.961   217   640 D ALSADevice: switchDevice: mCurTxUCMDevivce None mCurRxDevDevice Speaker
03-14 21:03:22.961   217   640 D alsa_ucm: snd_use_case_set(): uc_mgr 0xb7c40280 identifier _verb value HiFi Lowlatency
03-14 21:03:22.962   217   640 D alsa_ucm: Set mixer controls for Speaker enable 1
03-14 21:03:22.962   217   640 D alsa_ucm: acdb_id 15 cap 1 enable 1
03-14 21:03:22.962   217   640 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 15, path =  0
03-14 21:03:22.962   217   640 D ACDB-LOADER: ACDB -> send_adm_topology
03-14 21:03:22.962   217   640 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
03-14 21:03:22.962   217   640 D ACDB-LOADER: ACDB -> send_audtable
03-14 21:03:22.962   217   640 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
03-14 21:03:22.962   217   640 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
03-14 21:03:22.962   217   640 D ACDB-LOADER: ACDB -> send_audvoltable
03-14 21:03:22.962   217   640 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_VOLTBL_STEP_COPP
03-14 21:03:22.962   217   640 E ACDB-LOADER: Error: ACDB AudProc vol returned = -8
03-14 21:03:22.962   217   640 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
03-14 21:03:22.962   217   640 D ACDB-LOADER: ACDB -> send_afe_cal
03-14 21:03:22.962   217   640 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
03-14 21:03:22.962   217   640 E ACDB-LOADER: Error: ACDB AFE returned = -8
03-14 21:03:22.962   217   640 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
03-14 21:03:22.962   217   640 D alsa_ucm: Setting mixer control: PRI_RX Channels, value: One
03-14 21:03:22.963   217   640 D alsa_ucm: Setting mixer control: RX4 MIX1 INP1, value: RX1
03-14 21:03:22.964   217   640 D alsa_ucm: Setting mixer control: SLIM RX1 MUX, value: AIF1_PB
03-14 21:03:22.965   217   640 D alsa_ucm: Setting mixer control: SPK DAC Switch, value: 1
03-14 21:03:22.967   217   640 D alsa_ucm: Setting mixer control: RX4 Digital Volume, value: 68
03-14 21:03:22.968   217   640 D alsa_ucm: Setting multi value: SPK DRV Volume
03-14 21:03:22.968   217   640 D alsa_ucm: Set mixer controls for HiFi Lowlatency enable 1
03-14 21:03:22.968   217   640 D alsa_ucm: Setting mixer control: PRI_RX Audio Mixer MultiMedia5, value: 1
03-14 21:03:22.969   217   640 D ALSADevice: close: handle 0xb7c61848 h 0x0
03-14 21:03:22.969   217   640 D ALSADevice: open: handle 0xb7c61848, format 0x2
03-14 21:03:22.969   217   640 D ALSADevice: Device value returned is hw:0,14
03-14 21:03:22.975   217   640 D ALSADevice: handle->format: 0x2
03-14 21:03:22.975   217   640 D ALSADevice: setHardwareParams: reqBuffSize 1024 channels 2 sampleRate 48000
03-14 21:03:22.978   217   640 D ALSADevice: setHardwareParams: buffer_size 2048, period_size 1024, period_cnt 2
03-14 21:03:23.072   557  1075 I libprocessgroup: Killing pid 4854 in uid 10079 as part of process group 4833
03-14 21:03:23.072   557  1075 I libprocessgroup: Killing pid 4857 in uid 10079 as part of process group 4833
03-14 21:03:23.072   557  2074 I WindowState: WIN DEATH: Window{2ab0f16c u0 com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.MainActivity}
03-14 21:03:23.074   557  1075 I libprocessgroup: Killing pid 4854 in uid 10079 as part of process group 4833
03-14 21:03:23.074   557  1075 I libprocessgroup: Killing pid 4857 in uid 10079 as part of process group 4833
03-14 21:03:23.077   557  1075 I libprocessgroup: Killing pid 4854 in uid 10079 as part of process group 4833
03-14 21:03:23.077   557  1075 I libprocessgroup: Killing pid 4857 in uid 10079 as part of process group 4833
03-14 21:03:23.078   557  1075 I libprocessgroup: Killing pid 4854 in uid 10079 as part of process group 4833
03-14 21:03:23.078   557  1075 I libprocessgroup: Killing pid 4857 in uid 10079 as part of process group 4833
03-14 21:03:23.079   557  1075 I libprocessgroup: Killing pid 4854 in uid 10079 as part of process group 4833
03-14 21:03:23.079   557  1075 I libprocessgroup: Killing pid 4857 in uid 10079 as part of process group 4833
03-14 21:03:23.082   557  1075 I libprocessgroup: Killing pid 4854 in uid 10079 as part of process group 4833
03-14 21:03:23.082   557  1075 I libprocessgroup: Killing pid 4857 in uid 10079 as part of process group 4833
03-14 21:03:23.086   557  1075 I libprocessgroup: Killing pid 4857 in uid 10079 as part of process group 4833
03-14 21:03:23.093   557  1075 I libprocessgroup: Killing pid 4857 in uid 10079 as part of process group 4833
03-14 21:03:23.106   557  1075 I libprocessgroup: Killing pid 4857 in uid 10079 as part of process group 4833
03-14 21:03:23.312   557  1075 I ActivityManager: Process com.nutomic.syncthingandroid (pid 4833) has died
03-14 21:03:23.312   557  1075 W ActivityManager: Service crashed 2 times, stopping: ServiceRecord{396023a3 u0 com.nutomic.syncthingandroid/.syncthing.SyncthingService}
03-14 21:03:23.906   557   709 D TaskPersister: removeObsoleteFile: deleting file=4109_task.xml
03-14 21:03:23.907   557   709 D TaskPersister: removeObsoleteFile: deleting file=4115_task.xml
03-14 21:03:23.910   557   709 D TaskPersister: removeObsoleteFile: deleting file=4109_task_thumbnail.png

**Comment by Zillode** [comment]
Thanks, a new version will be released soon...

**Comment by Nutomic** [comment]
Fixed in 96a266e7fd52f282869b71a2dd6aa5741e388bc7.
