### ISSUE TITLE
Syncthing crashes on opening after upgrade to 0.5.19

### ISSUE THREAD

**Issue by bungabunga** [syncthing/syncthing-android#240]
Sony Xperia Z3c, stock Kitekat, rooted.

**Comment by Zillode** [comment]
Please search existing issues first, this has been fixed a few minutes ago: https://github.com/syncthing/syncthing-android/issues/238

**Comment by bungabunga** [comment]
sorry, i guess the first one was already closed when i submited this one, so i didn't see it.

**Comment by Nutomic** [comment]
Yeah we're that fast :D
