### ISSUE TITLE
0.5.20: "Device Name" in "Settings -> Syncthing Options" not being saved

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-android#241]
Any changes to `Device Name` in `Settings -> Syncthing Options` are lost when leaving the `Settings` page.

If changed on `Settings -> Web GUI`, it is preserved. However, it is still not shown on `Settings -> Syncthing Options`.

PS: I'm running Android 4.4.4 on a Motorola E XT1022

**Comment by Nutomic** [comment]
Duplicate of #239.
