### ISSUE TITLE
crash when trying to add /efs 

### ISSUE THREAD

**Issue by schuft69** [syncthing/syncthing-android#244]
syncthing 0.5.20 craches when trying to add /efs or /data (and others) via "add folder" dialog.

Maybe these folders are not readable anyway - but the app should not crash.

Device: Samsung S4mini Android 4.4.2 stock (not rooted).

**Comment by Zillode** [comment]
Could we get a log? My phone is rooted so I can't reproduce this easily (see [Contributing](https://github.com/syncthing/syncthing-android/blob/master/CONTRIBUTING.md#bug-reports))

**Comment by MartinX3** [comment]
My phone is rooted and i can produce it easily.
(Galaxy S2 I91000 with Cyanogenmod 11.0)
Syncthing Version v0.10.26
Syncthing-Android Version v.0.5.20

Here are my steps do reproduce the problem
1. Open Syncthing
2. Click on "Add folder"
3. Click on "Folder"
4. In the folder chooser i click on the last entry "/"
5. Now i click on the folder "data"
6. Now the error message "syncthing has closed" happen.

And here is my log


build.board: smdk4210
build.bootloader: unknown
build.brand: Samsung
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: GT-I9100
build.display: cm_i9100-userdebug 4.4.4 KTU84Q 4563c6f27c test-keys
build.fingerprint: samsung/GT-I9100/GT-I9100:4.1.2/JZO54K/I9100XWMS2:user/release-keys
build.hardware: smdk4210
build.host: cyanogenmod
build.id: KTU84Q
build.manufacturer: samsung
build.model: GT-I9100
build.product: GT-I9100
build.radio: I9100XXLS8
build.serial: 8F9E7C7AE6E444FD
build.tags: test-keys
build.time: 1425865225000
build.type: userdebug
build.user: jenkins
version.codename: REL
version.incremental: 4563c6f27c
version.release: 4.4.4
version.sdk_int: 19

03-16 21:18:51.540 I/Timeline(8379): Timeline: Activity_launch_request id:com.nutomic.syncthingandroid time:21157962
03-16 21:18:51.540 I/ActivityManager(7795): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nutomic.syncthingandroid/.activities.MainActivity} from pid 8379
03-16 21:18:52.105 W/RestApi (13143): at com.nutomic.syncthingandroid.syncthing.RestApi.getDevices(RestApi.java:410)
03-16 21:18:52.105 W/RestApi (13143): at com.nutomic.syncthingandroid.fragments.DevicesFragment.initAdapter(DevicesFragment.java:61)
03-16 21:18:52.105 W/RestApi (13143): at com.nutomic.syncthingandroid.fragments.DevicesFragment.onApiChange(DevicesFragment.java:44)
03-16 21:18:52.105 W/RestApi (13143): at com.nutomic.syncthingandroid.syncthing.SyncthingService.registerOnApiChangeListener(SyncthingService.java:363)
03-16 21:18:52.105 W/RestApi (13143): at com.nutomic.syncthingandroid.activities.MainActivity.onServiceConnected(MainActivity.java:214)
03-16 21:18:52.205 I/ActivityManager(7795): Displayed com.nutomic.syncthingandroid/.activities.MainActivity: +633ms
03-16 21:18:52.205 I/Timeline(7795): Timeline: Activity_windows_visible id: ActivityRecord{447fe1d8 u0 com.nutomic.syncthingandroid/.activities.MainActivity t51} time:21158627
03-16 21:18:53.820 I/Timeline(13143): Timeline: Activity_launch_request id:com.nutomic.syncthingandroid time:21160242
03-16 21:18:53.835 I/ActivityManager(7795): START u0 {act=folder_settings_fragment cmp=com.nutomic.syncthingandroid/.activities.SettingsActivity (has extras)} from pid 13143
03-16 21:18:54.230 W/RestApi (13143): at com.nutomic.syncthingandroid.syncthing.RestApi.getDevices(RestApi.java:410)
03-16 21:18:54.230 W/RestApi (13143): at com.nutomic.syncthingandroid.fragments.FolderSettingsFragment.onApiChange(FolderSettingsFragment.java:151)
03-16 21:18:54.230 W/RestApi (13143): at com.nutomic.syncthingandroid.syncthing.SyncthingService.registerOnApiChangeListener(SyncthingService.java:363)
03-16 21:18:54.230 W/RestApi (13143): at com.nutomic.syncthingandroid.fragments.FolderSettingsFragment.onServiceConnected(FolderSettingsFragment.java:179)
03-16 21:18:54.230 W/RestApi (13143): at com.nutomic.syncthingandroid.activities.SyncthingActivity.onServiceConnected(SyncthingActivity.java:52)
03-16 21:18:54.340 I/ActivityManager(7795): Displayed com.nutomic.syncthingandroid/.activities.SettingsActivity: +485ms
03-16 21:18:54.655 I/Timeline(7795): Timeline: Activity_windows_visible id: ActivityRecord{4489c330 u0 com.nutomic.syncthingandroid/.activities.SettingsActivity t51} time:21161076
03-16 21:18:56.060 I/Timeline(13143): Timeline: Activity_launch_request id:com.nutomic.syncthingandroid time:21162483
03-16 21:18:56.060 I/ActivityManager(7795): START u0 {cmp=com.nutomic.syncthingandroid/.activities.FolderPickerActivity} from pid 13143
03-16 21:18:56.275 I/ActivityManager(7795): Displayed com.nutomic.syncthingandroid/.activities.FolderPickerActivity: +194ms
03-16 21:18:56.610 I/Timeline(7795): Timeline: Activity_windows_visible id: ActivityRecord{448aa7b8 u0 com.nutomic.syncthingandroid/.activities.FolderPickerActivity t51} time:21163031
03-16 21:18:58.330 E/AndroidRuntime(13143): Process: com.nutomic.syncthingandroid, PID: 13143
03-16 21:18:58.330 E/AndroidRuntime(13143): at com.nutomic.syncthingandroid.activities.FolderPickerActivity.displayFolder(FolderPickerActivity.java:182)
03-16 21:18:58.330 E/AndroidRuntime(13143): at com.nutomic.syncthingandroid.activities.FolderPickerActivity.onItemClick(FolderPickerActivity.java:203)
03-16 21:18:58.335 W/ActivityManager(7795):   Force finishing activity com.nutomic.syncthingandroid/.activities.FolderPickerActivity
03-16 21:18:58.840 W/ActivityManager(7795): Activity pause timeout for ActivityRecord{448aa7b8 u0 com.nutomic.syncthingandroid/.activities.FolderPickerActivity t51 f}
03-16 21:19:00.280 I/WindowState(7795): WIN DEATH: Window{447ffe48 u0 com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.SettingsActivity}
03-16 21:19:00.280 I/ActivityManager(7795): Process com.nutomic.syncthingandroid (pid 13143) has died.
03-16 21:19:00.285 W/ActivityManager(7795): Service crashed 2 times, stopping: ServiceRecord{4496cc28 u0 com.nutomic.syncthingandroid/.syncthing.SyncthingService}
03-16 21:19:00.285 I/WindowState(7795): WIN DEATH: Window{44875458 u0 com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.FolderPickerActivity}
03-16 21:19:00.295 I/WindowState(7795): WIN DEATH: Window{447ebc00 u0 com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.MainActivity}
03-16 21:19:00.370 I/ActivityManager(7795): Start proc com.nutomic.syncthingandroid for activity com.nutomic.syncthingandroid/.activities.SettingsActivity: pid=13446 uid=10220 gids={50220, 1028, 1015, 3003}
03-16 21:19:00.455 D/ActivityThread(13446): handleBindApplication:com.nutomic.syncthingandroid
03-16 21:19:01.155 I/SyncthingService(13446): Web GUI will be available at http://127.0.0.1:47924
03-16 21:19:01.160 I/SyncthingService(13446): Starting syncthing according to current state and preferences
03-16 21:19:01.525 I/Timeline(7795): Timeline: Activity_windows_visible id: ActivityRecord{4489c330 u0 com.nutomic.syncthingandroid/.activities.SettingsActivity t51 f} time:21167948
03-16 21:19:01.825 I/ActivityManager(7795): Displayed com.nutomic.syncthingandroid/.activities.MainActivity: +683ms (total +1s529ms)
03-16 21:19:01.825 I/Timeline(7795): Timeline: Activity_windows_visible id: ActivityRecord{447fe1d8 u0 com.nutomic.syncthingandroid/.activities.MainActivity t51} time:21168248
03-16 21:19:11.915 I/SyncthingNativeCode(13446): [3B3RC] 20:19:11 INFO: syncthing v0.10.26 (go1.4 linux-arm android) unknown-user@T420 2015-03-11 20:15:55 UTC
03-16 21:19:11.920 I/SyncthingNativeCode(13446): [3B3RC] 20:19:11 INFO: My ID: 
03-16 21:19:12.555 I/SyncthingNativeCode(13446): [3B3RC] 20:19:12 INFO: Starting web GUI on http://127.0.0.1:47924/
03-16 21:19:21.630 I/SyncthingService(13446): Web GUI has come online at http://127.0.0.1:47924
03-16 21:19:21.670 I/RestApi (13446): Syncthing version is v0.10.26
03-16 21:19:21.715 W/RestApi (13446): at com.nutomic.syncthingandroid.syncthing.RestApi.getDevices(RestApi.java:410)
03-16 21:19:21.715 W/RestApi (13446): at com.nutomic.syncthingandroid.fragments.DevicesFragment.initAdapter(DevicesFragment.java:61)
03-16 21:19:21.715 W/RestApi (13446): at com.nutomic.syncthingandroid.fragments.DevicesFragment.onApiChange(DevicesFragment.java:44)
03-16 21:19:21.715 W/RestApi (13446): at com.nutomic.syncthingandroid.syncthing.SyncthingService.onApiChange(SyncthingService.java:397)
03-16 21:19:21.715 W/RestApi (13446): at com.nutomic.syncthingandroid.syncthing.SyncthingService.access$500(SyncthingService.java:45)
03-16 21:19:21.715 W/RestApi (13446): at com.nutomic.syncthingandroid.syncthing.SyncthingService$StartupTask$1.onApiAvailable(SyncthingService.java:292)
03-16 21:19:21.715 W/RestApi (13446): at com.nutomic.syncthingandroid.syncthing.RestApi.tryIsAvailable(RestApi.java:248)
03-16 21:19:21.715 W/RestApi (13446): at com.nutomic.syncthingandroid.syncthing.RestApi.access$100(RestApi.java:39)
03-16 21:19:21.715 W/RestApi (13446): at com.nutomic.syncthingandroid.syncthing.RestApi$3.onReceiveSystemInfo(RestApi.java:233)
03-16 21:19:21.715 W/RestApi (13446): at com.nutomic.syncthingandroid.syncthing.RestApi$7.onPostExecute(RestApi.java:460)
03-16 21:19:21.715 W/RestApi (13446): at com.nutomic.syncthingandroid.syncthing.RestApi$7.onPostExecute(RestApi.java:436)
03-16 21:19:21.790 I/SyncthingNativeCode(13446): [3B3RC] 20:19:21 INFO: Starting UPnP discovery...
03-16 21:19:27.805 I/SyncthingNativeCode(13446): [3B3RC] 20:19:27 INFO: UPnP discovery complete (found 1 device).
03-16 21:19:28.150 I/SyncthingNativeCode(13446): [3B3RC] 20:19:28 WARNING: Failed to create UPnP port mapping
03-16 21:19:28.165 I/SyncthingNativeCode(13446): [3B3RC] 20:19:28 INFO: Starting local discovery announcements
03-16 21:19:28.165 I/SyncthingNativeCode(13446): [3B3RC] 20:19:28 INFO: Starting global discovery announcements
03-16 21:19:28.165 I/SyncthingNativeCode(13446): [3B3RC] 20:19:28 OK: Ready to synchronize rollenspiele (read-write)

**Comment by Nutomic** [comment]
@Zillode If your phone is rooted or not does not make a difference because the app doesn't have root ;)
