### ISSUE TITLE
Crash on Folder-Selection - Root

### ISSUE THREAD

**Issue by MartinX3** [syncthing/syncthing-android#247]
I want to sync the files in the folder
/data/data/com.money.manager.ex/databases/data.mmb

I enabled the advanced folder picker and selected the root "/".
After that, i clicked on the "data" folder, path "/data/" and the app crashed.
I think it is because, it don't asks for root and don't catch the "you don't have access to folder"-exception.
Please make an optional option, to enable a "root data browser". :)

Galaxy S 2 (I9100)
Cyanogenmod 11.0

**Comment by Zillode** [comment]
Duplicate of https://github.com/syncthing/syncthing-android/issues/244
