### ISSUE TITLE
Only 1 of 2 announce servers

### ISSUE THREAD

**Issue by craibuc** [syncthing/syncthing-android#249]
Only one of two announce servers are available.  Is this related to issue #239?

![screenshot_2015-03-16-08-58-10](https://cloud.githubusercontent.com/assets/216592/6667722/009bd73c-cbbc-11e4-98b7-99517450ac2a.png)

Syncthing: 0.10.26
Syncthing-Android: 0.5.20

**Comment by AudriusButkevicius** [comment]
This is expected if you don't have IPv6 support.
