### ISSUE TITLE
Configurable option to run media scan after filesystem changes

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-android#251]
Not sure if this is viable (or desirable) but certainly would be useful: to have a configurable option to tell `syncthing` to fire an Android's media scan (I don't know how this is done, whether through an API or by calling the Android process responsible for media scanning) after a batch of filesystem changes (add a file, remove a file, change a file) completes.

I use `syncthing` on Android primarily to sync images, and whenever I add or delete an image from a synced folder on another device, I have to manually rescan the SD cards on my Android device, so that the changes become visible to the other apps. Syncing would be more seamless if `syncthing` itself could fire off this media scanning, whenever it changes any files on the Android device. Of course, this could be configured through a Settings option.

**Comment by Zillode** [comment]
We are happy to accept patches, here is a hint: http://stackoverflow.com/questions/13270789/how-to-run-media-scanner-in-android

**Comment by Nutomic** [comment]
And the [event interface](https://github.com/syncthing/syncthing/wiki/Event-Interface) could be used to trigger the media scan.

Closely related to #130.

**Comment by capi** [comment]
That would be very handy option. `btsync` offers this since a few versions and I think its a nice option.

**Comment by mkaito** [comment]
:+1:
