### ISSUE TITLE
Percent over 100

### ISSUE THREAD

**Issue by urza** [syncthing/syncthing-android#253]
When syncing folder for the first time, the CPU usage percent goes above 100%. See attached picture.

However this was few days back before recent app update, so it is possible that it is already fixed.

(Galaxy Note2 GT-N7100 with Android 4.1.2)

![syncthing-cpu-200percent](https://cloud.githubusercontent.com/assets/189804/6682316/3b8e0a02-cc77-11e4-86da-65fcdb03ce9f.png)

**Comment by Zillode** [comment]
Fixed by https://github.com/syncthing/syncthing/commit/4b1b56fee87dc96139882957d01632e7c0b9f7c7 (19 days ago). Feel free to reopen if the yet-to-be published version does not fix it. I guess there will be a new release today or tomorrow.
