### ISSUE TITLE
Slow startup, should ignore .thumbnails

### ISSUE THREAD

**Issue by Spiritdude** [syncthing/syncthing-android#262]
I had a problem that the app hung since weeks, "Waiting for API" forever, de- and reinstalled multiple times whenever new version came, no remedy. Then I looked at my files on my smartphone closely, even though I had 10 photos, it showed 2000 files? They were remaining thumbnails of photos I deleted earlier to make room, in a hidden directory, once I deleted those manually, syncthing finally came up. 

My guess: a lot of small files in a directory makes syncthing stall, crash or whatever.

Galaxy GT-I9100 Android 4.1.2 2GB RAM.

**Comment by Nutomic** [comment]
What directory were those pictures in, and which app showed that file count?

Btw you should have just commented on #216 ;)

**Comment by Zillode** [comment]
I think we can add a default ignore for .thumbnails. It syncs and adds a watcher for many unnecessary/unwanted files.

**Comment by Nutomic** [comment]
I just don't see why this would prevent syncthing and/or the app from starting.

**Comment by Spiritdude** [comment]
@Nutomic /storage/sdcard0/DCIM/.thumbnails, and syncthing reported 2000+ files before I purged them. I just wanted to report my "remedy" for reference.

**Comment by Nutomic** [comment]
So folder observers are now added in a background thread (which is a good idea anyway).

I'm not sure if that's really the cause for this problem, but let's see.
