### ISSUE TITLE
0.5.21. asks for a force close when trying to add device

### ISSUE THREAD

**Issue by agit8** [syncthing/syncthing-android#263]
As mentioned. On android 2.3.6. I just hit "add device" and force close is the app's response - I don't get to the details screen so on point checking on the web gui

**Comment by Zillode** [comment]
@agit8 Can you try the builds provided in https://github.com/syncthing/syncthing-android/issues/256? We will release a new version soon..

**Comment by Zillode** [comment]
Fixed in https://github.com/syncthing/syncthing-android/commit/2b9a79bdada5b8bce2d310cc145fe17122d97e63
Will be in F-Droid tomorrow and Play store within a few hours.

**Comment by agit8** [comment]
Thanks for this. Version 0.5.24 seems to work fine for me

Regards

nick



Quoting Zillode <notifications@github.com> on Sat, 21 Mar 2015 
05:31:44 -0700:



Fixed in

https://github.com/syncthing/syncthing-
android/commit/2b9a79bdada5b8bce2d310cc145fe17122d97e63



Will be in F-Droid tomorrow and Play store within a few hours.



---

Reply to this email directly or view it on GitHub:

https://github.com/syncthing/syncthing-
android/issues/263#issuecomment-84327812




____________________________________________________________________
eKit - the global phonecard with more!

Spend less on overseas calls, receive messages worldwide.
Visit http://www.ekit.com/ for details.
