### ISSUE TITLE
changing "compression" of a device sometimes crash the app

### ISSUE THREAD

**Issue by MauroMombelli** [syncthing/syncthing-android#274]
1. device tab
2. click to edit a device
3. compression
4. change compression

Sometimes it works and it ask to reboot the service; sometimes it does not and the app crash.

VERSION: 0.5.22 from f-droid
device one plus one, android 4.4.4

**Comment by Nutomic** [comment]
I can't reproduce this, could you post a logcat?

**Comment by Zillode** [comment]
Probably related with an invalid mDevice reference.
However, I think the current behavior is confusing when selecting a compression option as it does not update the summary. Should we update this immediately or wait for ST to report back?

**Comment by Nutomic** [comment]
I just fixed the summary ;)

**Comment by Zillode** [comment]
amazing
@MauroMombelli : feel free to reopen if it still exists in version 0.5.25 which will be released later today (I think)

**Comment by MauroMombelli** [comment]
@Nutomic sorry, no root

also, if compression's setting are different between device, what is used?

**Comment by MauroMombelli** [comment]
fix confirmed, thanks
