### ISSUE TITLE
device duplicated in folder's list

### ISSUE THREAD

**Issue by MauroMombelli** [syncthing/syncthing-android#275]
1. add a new device
2. go into folder tab
3. click a existing folder
4. click device
5. all device are listed 2 times

does not seems to happen if you don't add a new device. didn't try to replicate again.

VERSION: 0.5.22 from f-droid
device one plus one, android 4.4.4

**Comment by Nutomic** [comment]
I can't reproduce this either. Btw the latest version is 0.5.24 (but F-Droid doesn't seem to have it yet).
