### ISSUE TITLE
Disable automatic-updates in syncthing configuration

### ISSUE THREAD

**Issue by capi** [syncthing/syncthing-android#276]
The default configuration used by syncthing-android enables auto-updates, which fails due to permission problems. While this doesn't seem to cause any problems, I still think it would be best if auto-update is disabled, if it's not going to work anyways.

    03-22 12:59:26.087   8776-10853/com.nutomic.syncthingandroid.debug I/SyncthingNativeCode? [FB3K2] 11:59:26 INFO: Automatic upgrade (current "v0.10.26" < latest "v0.10.28")
    03-22 12:59:28.387   8776-10853/com.nutomic.syncthingandroid.debug I/SyncthingNativeCode? [FB3K2] 11:59:28 WARNING: Automatic upgrade: open /data/app-lib/com.nutomic.syncthingandroid.debug-1/syncthing256180981: permission denied
    03-22 12:59:28.387   8776-10853/com.nutomic.syncthingandroid.debug I/SyncthingNativeCode? [FB3K2] 11:59:28 INFO: Connected to device AAAAAAA-BBBBBB-CCCCCC-DDDDDDD-EEEEEE-FFFFF-A0A0A0A0-B0B0B0B0 with a newer version (current "v0.10.26" < remote "v0.10.28"). Checking for upgrades.
    03-22 12:59:28.947   8776-10853/com.nutomic.syncthingandroid.debug I/SyncthingNativeCode? [FB3K2] 11:59:28 INFO: Automatic upgrade (current "v0.10.26" < latest "v0.10.28")

**Comment by Nutomic** [comment]
@calmh @AudriusButkevicius Looks like the [-no-upgrade compile flag](https://github.com/syncthing/syncthing-android/blob/master/build-syncthing.sh#L71) is broken?

**Comment by capi** [comment]
@Nutomic oh sorry, if this is a compile-time flag, then it's entirely my fault, because I didn't compile `syncthing` myself but grabbed the binary ARM release.

**Comment by Nutomic** [comment]
Is there a reason you didn't run the gradle build?

**Comment by capi** [comment]
I was testing from a Windows machine with no Go installed.

**Comment by Nutomic** [comment]
Ah, #219. 

The flag is now set, but it would be nice if we could have the proper build process. Maybe you wanna give it a try? ;)
