### ISSUE TITLE
Do not generate .stfolder files to help Syncthing

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-android#277]
https://github.com/syncthing/syncthing-android/blob/d5bbaafdb4deaf8a6e32b015732d063e6fa9e41b/src/main/java/com/nutomic/syncthingandroid/util/ConfigXml.java#L144 should be disabled.

**Comment by Nutomic** [comment]
`SyncthingService#moveConfigFiles()` is also not needed any more.
