### ISSUE TITLE
No information shown

### ISSUE THREAD

**Issue by urza** [syncthing/syncthing-android#281]
I have syncthing app on android and syncthing on PC.

Because I had problems with "folder xxx is making no progress" when synchronizing one folder from android to pc, I just removed that folder on PC from syncthing web gui and deleted its content from harddisk.

Then I started android syncthing app, on my PC synchig asked me that my andoid wants to share new folder, I said yes and added that.

Now it says on my PC that it is synchronizing, but on android the app is kind of "empty" there is no "Device ID" shown. No CPU usage, no ram usage, download etc. All devices are listed as "disconected" which is not true, because the synchronization is in progress.. all folders are listed but without status info.

**Comment by Zillode** [comment]
Please provide a [logcat](https://github.com/syncthing/syncthing-android/blob/master/CONTRIBUTING.md#bug-reports)
(Note to self: We should add a dialog showing the current syncthing log)

**Comment by urza** [comment]
Sorry that's beyond my geek level.

**Comment by Nutomic** [comment]
@urza There should be several logcat apps on Google Play.

@Zillode We could save the logcat to a file on sdcard, but I don't know any app that does this. Not sure how you'd design that dialog.

**Comment by Zillode** [comment]
Ref https://github.com/syncthing/syncthing-android/issues/311
