### ISSUE TITLE
Use different default port for Syncthing GUI (8080)

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-android#282]
We should not use 8080 as a default port for Syncthing as this is reserved for development purposes.
Maybe this should be updated in upstream as well?
@calmh @AudriusButkevicius

Could be related to https://github.com/syncthing/syncthing-android/issues/279 and https://github.com/syncthing/syncthing-android/issues/216

**Comment by Nutomic** [comment]
We could certainly randomize the port on install.

If we just change the port number (across all installs), that should be handled upstream imo.

**Comment by Zillode** [comment]
Ref https://github.com/syncthing/syncthing-android/commit/593a36af55e34d74cd46166448c1ef4dab691661
