### ISSUE TITLE
Show Notification When New Folder is Shared to Device

### ISSUE THREAD

**Issue by jdrch** [syncthing/syncthing-android#295]
The only way to be notified of a folder being shared from the desktop client with the Android device is to have the Web UI open at the time the folder is shared. There is no notification in the client, and if you miss the web notification, you have to delete the folder from the desktop client and reshare the folder.

**Comment by AudriusButkevicius** [comment]
Or inverse the addition process, or add it manually with the same name on the android device.

**Comment by jdrch** [comment]
Fair enough. That's a workaround though, not a true solution.

**Comment by Zillode** [comment]
I think your solution is a work around, the cases @AudriusButkevicius work as intended.
However, we should show requested folder sharing (as mentioned at https://discourse.syncthing.net/t/how-does-syncing-among-3-or-more-devices-work/2181/4).

**Comment by Cysioland** [comment]
:+1:

**Comment by edrex** [comment]
I agree that the native experience expectation is a system notification when a new folder or device is offered.

**Comment by anarcat** [comment]
This was a critical issue raised in my usability review here: https://forum.syncthing.net/t/first-time-user-usability-review/6974/5

I strongly encourage the syncthing team to focus on this issue. At least documenting somehow that a share with the same name will magically work (which is really odd to me) would be an improvement.
