### ISSUE TITLE
Syncthing freezes during initial scan of large folders

### ISSUE THREAD

**Issue by jdrch** [syncthing/syncthing-android#299]
I have a large folder (~32 GB, 10^4 files) I added. The GUI freezes during the scanning process, and the only way to get it to update is to Force Close and restart the app.

**Comment by Nutomic** [comment]
This is suprising, because the scanning is all done by syncthing (not by the Android app) in a background thread.

Are other apps also slowed down, or only syncthing? Logcat might also be helpful.

**Comment by jdrch** [comment]
I decided to try again but to just let the phone sit for a bit instead of trying to interact with the client UI. Turns out it does update, just very slowly. The folders are LARGE so that's probably why. Faster updating would be nice in the future, but it is working right now.

**Comment by Nutomic** [comment]
I suppose it's a problem of your phone being too slow for syncthing (or the other way round).

But after the initial scan, it shouldn't be a problem because we use inotify.

**Comment by jdrch** [comment]
Well 1) the folder's on a MicroSD card 2) Scanning it on a desktop client eats >50% CPU. So I really think it's just a tough case, not really a fault of the app or my phone.

**Comment by Nutomic** [comment]
You should report this at syncthing (assuming there isn't already an issue for it).

**Comment by jdrch** [comment]
I'm not surprised at a folder of that size and with that many files eating up CPU and I/O. Same thing happens with BitTorrent Sync (albeit less pronounced). Are you saying that, in your expertise, such a thing is surprising?

**Comment by Nutomic** [comment]
I haven't experienced it myself, but if you can't use your device any more, that's definitely a bug imo.
