### ISSUE TITLE
Please support unitag QR Scanner

### ISSUE THREAD

**Issue by ManuelSchneid3r** [syncthing/syncthing-android#327]
[This](https://play.google.com/store/apps/details?id=com.unitag.scanner&hl=de) one.
id=com.unitag.scanner

**Comment by Zillode** [comment]
Done but untested as it is an application which I don't have on my device.
I guess it'll be part of the next release and then you can test it.

**Comment by Zillode** [comment]
Just tested it, it doesn't work and I don't want to spend time on integrating closed source software.

**Comment by Nutomic** [comment]
Agreed.
