### ISSUE TITLE
Menu-Button to open Options-Dialogue

### ISSUE THREAD

**Issue by NeroBurner** [syncthing/syncthing-android#329]
I've got a phone with 3 buttons on the bottom
- Menu
- Home
- Back

and it seems that the menu-button isn't doing anything. It would be nice If it would open the Options-Dialogue (the one which shows CPU Usage, and the options to open Web GUI, Settings and Exit) the same way as when swiping the screen from the left to the right.

Device: Samsung Galaxy S3 (GT-I9300)
Rom: slimkat (slimroms, Android 4.4.4)
Syncthing-Android: Version 0.5.27

**Comment by Nutomic** [comment]
Fix implemented, but looks like this Android issue has to be fixed before it works:
https://code.google.com/p/android/issues/detail?id=159703
