### ISSUE TITLE
Problem: App wont install on Android Phone

### ISSUE THREAD

**Issue by Lighter007** [syncthing/syncthing-android#331]
Hi!
I´ve got a problem with the Android App because I can´t install it. It starts the android installer when you use the .apk directly and Google Play Store also begins but the actual installing progress doesn´t start. There are just this blue lines going from left to right again and again.
Phone: LG-P880
Android Version: 4.1.2
Fix please, I love syncthing ;)

**Comment by Nutomic** [comment]
Sounds like a problem with Google Play.

You can install [F-Droid](https://f-droid.org/) instead and install it from there.
