### ISSUE TITLE
Syncthing binary crashed with error code 132

### ISSUE THREAD

**Issue by tnm-** [syncthing/syncthing-android#336]
Installed latest syncthing-android (0.5.28) on HTC Wildfire with CM7 (Android 2.3)

On first start loading circle goes around forever, while in logcat the following three lines repeat endlessly:

> E/SyncthingNativeCode( 1513): Syncthing binary crashed with error code 132
> W/ConfigXml( 1513): Failed to open config, moving to config.xml.invalid and creating blank config
> W/SyncthingNativeCode( 1513): [1]   Illegal instruction     HOME=/mnt/sdcard...

(BTW thanks for ARM5 support! syncthing/syncthing-android#333 )

**Comment by Zillode** [comment]
Could you post the complete illegal instruction line?

**Comment by tnm-** [comment]
As far as I can tell that's all in the log (I did not truncate the line, this is how it appears in logcat.)

Is there anywhere else I could look for it?

**Comment by Nutomic** [comment]
Maybe try reinstalling the app and rebooting the device.

Is there anything else logged on app start? (before those lines appear)

**Comment by tnm-** [comment]
It was a fresh install (not update). Here's the logcat of startup:
http://tnm.no-ip.biz/ftp/syncthing_armv5_startup_logcat.txt

**Comment by rodmoncada** [comment]
Hello Guys,
First of all, thanks for the support..!

I have also an ARM v5 just like "#336"
Linux Dacave 2.6.24.4 #1 Thu Apr 1 16:43:58 CST 2010 armv5tejl unknown
I checked topics: "#336", "#1132" which I believe are the same issue I'm having as well, I tried to build the toolchain from #399 = https://github.com/syncthing/syncthing-android/commit/6a97e6d719f51ded392d1000e954a608f5e590fa
I made some changes in the script to adjust my environment, nevertheless I'm stuck in this step:
[synct@Dacave synct]$ pwd
/opt/synct
[synct@Dacave synct]$ sh build-syncthing.sh
build-syncthing.sh: line 9: git: command not found
--10:45:13--  http://golang.org/dl/go1.4.2.src.tar.gz
           => `go.src.tar.gz'
Resolving golang.org... 74.125.141.141
Connecting to golang.org|74.125.141.141|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/golang/go1.4.2.src.tar.gz [following]
--10:45:13--  https://storage.googleapis.com/golang/go1.4.2.src.tar.gz
           => `go.src.tar.gz'
Resolving storage.googleapis.com... 216.58.219.65
Connecting to storage.googleapis.com|216.58.219.65|:443... connected.
WARNING: Certificate verification error for storage.googleapis.com: unable to get local issuer certificate
WARNING: certificate common name `*.googleusercontent.com' doesn't match requested host name `storage.googleapis.com'.
HTTP request sent, awaiting response... 200 OK
Length: 10,921,896 (10M) [application/x-gzip]

100%[=========================================================================================================================================================>] 10,921,896   231.67K/s    ETA 00:00

10:45:56 (247.40 KB/s) - `go.src.tar.gz' saved [10921896/10921896]

/opt/synct/build/go/src /opt/synct
# Building C bootstrap tool.
cmd/dist
./make.bash: line 132: gcc: command not found
/opt/synct
/opt/synct/build/go/src /opt/synct
# Building C bootstrap tool.
cmd/dist
./make.bash: line 132: gcc: command not found
/opt/synct
/opt/synct/build/go/src /opt/synct
# Building C bootstrap tool.
cmd/dist
./make.bash: line 132: gcc: command not found
/opt/synct
build-syncthing.sh: line 59: cd: ext/syncthing/: No such file or directory
build-syncthing.sh: line 63: /opt/synct/build/go/bin/go: No such file or directory
build-syncthing.sh: line 68: cd: src/github.com/syncthing/syncthing: No such file or directory
build-syncthing.sh: line 69: /opt/synct/build/go/bin/go: No such file or directory
build-syncthing.sh: line 72: /opt/synct/build/go/bin/go: No such file or directory
mv: unable to rename `syncthing': No such file or directory
build-syncthing.sh: line 74: /opt/synct/build/go/bin/go: No such file or directory
build-syncthing.sh: line 77: /opt/synct/build/go/bin/go: No such file or directory
mv: unable to rename `syncthing': No such file or directory
build-syncthing.sh: line 79: /opt/synct/build/go/bin/go: No such file or directory
[synct@Dacave synct]$

I'm not to experienced but I'm totally commited to have this done, thanks for any reply.
By the way today was released version 0.11.8 but I'm experiencing the same "Illegal Instruction" issue. It's a WD MyBook World Edition I White light.

Thanks for any help

**Comment by AudriusButkevicius** [comment]
You don't have a compiler installed (gcc)

**Comment by rodmoncada** [comment]
I installed gcc using this instructions:

in /opt/etc/ipkg/armel-feed.conf change:
src armel http://ipkg.nslu2-linux.org/feeds/optware/cs05q1armel/cross/unstable
into:
src armel http://ipkg.nslu2-linux.org/feeds/optware/cs08q1armel/cross/unstable
now update your feed:
# ipkg update
and install gcc:
# ipkg install gcc

Took from this link: http://mybookworld.wikidot.com/forum/t-256393/gcc-compiler-in-optware

I believe build-syncthing completed (took a while), nevertheless still throwing some missing files or directories, is there specific instructions or a path to execute this script build-syncthing,sh?

**Comment by Zillode** [comment]
Please post the output so we can verify if everything is alright.
build-syncthing.sh should build without additional instructions.

**Comment by rodmoncada** [comment]
Sure, please find below the output's script:

===
[root@Dacave synct]# sh build-syncthing.sh
fatal: Not a git repository (or any of the parent directories): .git
--06:44:38--  http://golang.org/dl/go1.4.2.src.tar.gz
           => `go.src.tar.gz'
Resolving golang.org... 74.125.141.141
Connecting to golang.org|74.125.141.141|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/golang/go1.4.2.src.tar.gz [following]
--06:44:38--  https://storage.googleapis.com/golang/go1.4.2.src.tar.gz
           => `go.src.tar.gz'
Resolving storage.googleapis.com... 216.58.219.161
Connecting to storage.googleapis.com|216.58.219.161|:443... connected.
WARNING: Certificate verification error for storage.googleapis.com: unable to get local issuer certificate
WARNING: certificate common name `*.googleusercontent.com' doesn't match requested host name `storage.googleapis.com'.
HTTP request sent, awaiting response... 200 OK
Length: 10,921,896 (10M) [application/x-gzip]

100%[=========================================================================================================================================================>] 10,921,896   195.43K/s    ETA 00:00

06:45:36 (185.15 KB/s) - `go.src.tar.gz' saved [10921896/10921896]

/shares/synct/build/go/src /shares/synct
# Building C bootstrap tool.
cmd/dist
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/libc.so.6: warning: sh_link not set for section `.ARM.exidx'
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/ld-linux.so.3: warning: sh_link not set for section `.ARM.exidx'

# Building compilers and Go bootstrap tool for host, linux/arm.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/5l
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/libc.so.6: warning: sh_link not set for section `.ARM.exidx'
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/ld-linux.so.3: warning: sh_link not set for section `.ARM.exidx'
cmd/5a
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/libc.so.6: warning: sh_link not set for section `.ARM.exidx'
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/ld-linux.so.3: warning: sh_link not set for section `.ARM.exidx'
cmd/5c
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/libc.so.6: warning: sh_link not set for section `.ARM.exidx'
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/ld-linux.so.3: warning: sh_link not set for section `.ARM.exidx'
cmd/5g
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/libc.so.6: warning: sh_link not set for section `.ARM.exidx'
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/ld-linux.so.3: warning: sh_link not set for section `.ARM.exidx'
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
time
os
reflect
fmt
encoding
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
cmd/go
go tool dist: FAILED: /shares/synct/build/go/pkg/tool/linux_arm/5g -pack -o $WORK/_go_.a -p main /shares/synct/build/go/src/cmd/go/bootstrap.go /shares/synct/build/go/src/cmd/go/build.go /shares/synct/build/go/src/cmd/go/clean.go /shares/synct/build/go/src/cmd/go/context.go /shares/synct/build/go/src/cmd/go/env.go /shares/synct/build/go/src/cmd/go/fix.go /shares/synct/build/go/src/cmd/go/fmt.go /shares/synct/build/go/src/cmd/go/generate.go /shares/synct/build/go/src/cmd/go/get.go /shares/synct/build/go/src/cmd/go/go11.go /shares/synct/build/go/src/cmd/go/help.go /shares/synct/build/go/src/cmd/go/list.go /shares/synct/build/go/src/cmd/go/main.go /shares/synct/build/go/src/cmd/go/pkg.go /shares/synct/build/go/src/cmd/go/run.go /shares/synct/build/go/src/cmd/go/signal.go /shares/synct/build/go/src/cmd/go/signal_unix.go /shares/synct/build/go/src/cmd/go/test.go /shares/synct/build/go/src/cmd/go/testflag.go /shares/synct/build/go/src/cmd/go/tool.go /shares/synct/build/go/src/cmd/go/vcs.go /shares/synct/build/go/src/cmd/go/version.go /shares/synct/build/go/src/cmd/go/vet.go /shares/synct/build/go/src/cmd/go/zdefaultcc.go
/shares/synct
/shares/synct/build/go/src /shares/synct
# Building C bootstrap tool.
cmd/dist
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/libc.so.6: warning: sh_link not set for section `.ARM.exidx'
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/ld-linux.so.3: warning: sh_link not set for section `.ARM.exidx'

# Building compilers and Go bootstrap tool for host, linux/arm.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/5l
cmd/8l
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/libc.so.6: warning: sh_link not set for section `.ARM.exidx'
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/ld-linux.so.3: warning: sh_link not set for section `.ARM.exidx'
cmd/5a
cmd/8a
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/libc.so.6: warning: sh_link not set for section `.ARM.exidx'
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/ld-linux.so.3: warning: sh_link not set for section `.ARM.exidx'
cmd/5c
cmd/8c
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/libc.so.6: warning: sh_link not set for section `.ARM.exidx'
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/ld-linux.so.3: warning: sh_link not set for section `.ARM.exidx'
cmd/5g
cmd/8g
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/libc.so.6: warning: sh_link not set for section `.ARM.exidx'
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/ld-linux.so.3: warning: sh_link not set for section `.ARM.exidx'
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
time
os
reflect
fmt
encoding
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
cmd/go
go tool dist: FAILED: /shares/synct/build/go/pkg/tool/linux_arm/5g -pack -o $WORK/_go_.a -p main /shares/synct/build/go/src/cmd/go/bootstrap.go /shares/synct/build/go/src/cmd/go/build.go /shares/synct/build/go/src/cmd/go/clean.go /shares/synct/build/go/src/cmd/go/context.go /shares/synct/build/go/src/cmd/go/env.go /shares/synct/build/go/src/cmd/go/fix.go /shares/synct/build/go/src/cmd/go/fmt.go /shares/synct/build/go/src/cmd/go/generate.go /shares/synct/build/go/src/cmd/go/get.go /shares/synct/build/go/src/cmd/go/go11.go /shares/synct/build/go/src/cmd/go/help.go /shares/synct/build/go/src/cmd/go/list.go /shares/synct/build/go/src/cmd/go/main.go /shares/synct/build/go/src/cmd/go/pkg.go /shares/synct/build/go/src/cmd/go/run.go /shares/synct/build/go/src/cmd/go/signal.go /shares/synct/build/go/src/cmd/go/signal_unix.go /shares/synct/build/go/src/cmd/go/test.go /shares/synct/build/go/src/cmd/go/testflag.go /shares/synct/build/go/src/cmd/go/tool.go /shares/synct/build/go/src/cmd/go/vcs.go /shares/synct/build/go/src/cmd/go/version.go /shares/synct/build/go/src/cmd/go/vet.go /shares/synct/build/go/src/cmd/go/zdefaultcc.go
/shares/synct
/shares/synct/build/go/src /shares/synct
# Building C bootstrap tool.
cmd/dist
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/libc.so.6: warning: sh_link not set for section `.ARM.exidx'
/opt/lib/gcc/arm-none-linux-gnueabi/4.2.3/../../../../arm-none-linux-gnueabi/bin/ld: /lib/ld-linux.so.3: warning: sh_link not set for section `.ARM.exidx'

# Building compilers and Go bootstrap tool for host, linux/arm.
lib9
libbio
liblink
cmd/cc
cmd/gc
cmd/5l
cmd/5a
cmd/5c
cmd/5g
runtime
errors
sync/atomic
sync
io
unicode
unicode/utf8
unicode/utf16
bytes
math
strings
strconv
bufio
sort
container/heap
encoding/base64
syscall
time
os
reflect
fmt
encoding
encoding/json
flag
path/filepath
path
io/ioutil
log
regexp/syntax
regexp
go/token
go/scanner
go/ast
go/parser
os/exec
os/signal
net/url
text/template/parse
text/template
go/doc
go/build
cmd/go
go tool dist: FAILED: /shares/synct/build/go/pkg/tool/linux_arm/5g -pack -o $WORK/_go_.a -p main /shares/synct/build/go/src/cmd/go/bootstrap.go /shares/synct/build/go/src/cmd/go/build.go /shares/synct/build/go/src/cmd/go/clean.go /shares/synct/build/go/src/cmd/go/context.go /shares/synct/build/go/src/cmd/go/env.go /shares/synct/build/go/src/cmd/go/fix.go /shares/synct/build/go/src/cmd/go/fmt.go /shares/synct/build/go/src/cmd/go/generate.go /shares/synct/build/go/src/cmd/go/get.go /shares/synct/build/go/src/cmd/go/go11.go /shares/synct/build/go/src/cmd/go/help.go /shares/synct/build/go/src/cmd/go/list.go /shares/synct/build/go/src/cmd/go/main.go /shares/synct/build/go/src/cmd/go/pkg.go /shares/synct/build/go/src/cmd/go/run.go /shares/synct/build/go/src/cmd/go/signal.go /shares/synct/build/go/src/cmd/go/signal_unix.go /shares/synct/build/go/src/cmd/go/test.go /shares/synct/build/go/src/cmd/go/testflag.go /shares/synct/build/go/src/cmd/go/tool.go /shares/synct/build/go/src/cmd/go/vcs.go /shares/synct/build/go/src/cmd/go/version.go /shares/synct/build/go/src/cmd/go/vet.go /shares/synct/build/go/src/cmd/go/zdefaultcc.go
/shares/synct
build-syncthing.sh: line 59: cd: ext/syncthing/: No such file or directory
build-syncthing.sh: line 63: /shares/synct/build/go/bin/go: No such file or directory
build-syncthing.sh: line 68: cd: src/github.com/syncthing/syncthing: No such file or directory
build-syncthing.sh: line 69: /shares/synct/build/go/bin/go: No such file or directory
build-syncthing.sh: line 72: /shares/synct/build/go/bin/go: No such file or directory
build-syncthing.sh: line 74: /shares/synct/build/go/bin/go: No such file or directory
build-syncthing.sh: line 77: /shares/synct/build/go/bin/go: No such file or directory
mv: unable to rename `syncthing': No such file or directory
build-syncthing.sh: line 79: /shares/synct/build/go/bin/go: No such file or directory
[root@Dacave synct]#
===
