### ISSUE TITLE
Waiting for API

### ISSUE THREAD

**Issue by gekkeabt** [syncthing/syncthing-android#343]
When I start the app I sometimes get the message: Waiting for API. And it won't go away.

Steps to reproduce:
1. Open the app
(I don't exactly know what the real reason behind it is, but it happens when I start the app)

I would expect it to start normally and show the list of folders, but it shows the message: Waiting for API.

Syncthing version 0.5.28
Samsung Galaxy Note II - N7100 - Android 4.4.4

**Comment by AudriusButkevicius** [comment]
https://github.com/syncthing/syncthing-android/issues/196

I feel this will be fixed in some future release.

**Comment by Zillode** [comment]
@gekkeabt could you provide a log using adb logcat?

**Comment by Zillode** [comment]
Fixed in v0.6.0
