### ISSUE TITLE
Reduce CPU usage using push-based folder summaries

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-android#344]
See https://github.com/syncthing/syncthing/commit/454e688c3d626f8e2413d8c0d8acc65c204d8981

**Comment by Zillode** [comment]
https://github.com/syncthing/syncthing/issues/1555#issuecomment-93560689

**Comment by Nutomic** [comment]
@Zillode: Do you think it's possible to take the code for this from the silk client?

**Comment by Zillode** [comment]
The license doesn't allow this :/
I also think it wouldn't be too easy because the whole core is written in an asynchronous manner using JavaRX. The Syncthing event interface is quite simple tho

**Comment by Catfriend1** [comment]
Frozen due to age. In the meantime, we get filewatcher soon and the app gui is updating every second when in the foreground.
