### ISSUE TITLE
Uses lots & lots of battery time

### ISSUE THREAD

**Issue by Profpatsch** [syncthing/syncthing-android#349]
When I leave Syncthing running it reduces my battery life to a few hours.

**Comment by AudriusButkevicius** [comment]
If you have a lot of files, it will use a lot of CPU in the beginning to perform indexing, it should settle after that.

The reason startup takes a while is because it performs peer discovery, gateway discovery, rescanning and a bunch of other things

**Comment by Profpatsch** [comment]
I’m gonna do some measurings.

**Comment by Profpatsch** [comment]
So my phone crashed two times today. Coincidence?

Will try again tomorrow.

**Comment by Nutomic** [comment]
Your phone crashed or the app? Apps should never make your phone crash :o

**Comment by Profpatsch** [comment]
> Apps should never make your phone crash :o

It’s Android …

My phone crashed twice. Probably just coincidence.

**Comment by Profpatsch** [comment]
Okay, it is actually reasonable, but still not negligible.

Not running:
![screenshot_2015-04-12-18-21-03](https://cloud.githubusercontent.com/assets/3153638/7184468/b8654cd6-e45d-11e4-9535-a8424fcae431.png)

Running:
![screenshot_2015-04-16-01-07-49](https://cloud.githubusercontent.com/assets/3153638/7184476/c0f8a01e-e45d-11e4-9139-46516eb075bc.png)

**Comment by Zillode** [comment]
@Profpatsch does it happen when you enable the 'run in background' option (and thus close the GUI)?

**Comment by Profpatsch** [comment]
@Zillode I’m gonna test that for a few days. Didn’t know about that option, nice.

**Comment by Profpatsch** [comment]
When I enable the `run in background` option, the battery usage shrinks down to next to nothing!

**Comment by Zillode** [comment]
:+1: !

**Comment by Profpatsch** [comment]
@Zillode Maybe that option should be default? Probably I was asked after installation and just forgot.

**Comment by Profpatsch** [comment]
Then again, not running in background uses way too much battery.

**Comment by Zillode** [comment]
@Nutomic ?

**Comment by Nutomic** [comment]
Making that default would be my preference. Though it's news to me that battery usage is "next to nothing". We should confirm that with other users/devices first.

Alternatively, we could ask after installation, but I'm not a fan of that (makes it more complicated for new users).

**Comment by Profpatsch** [comment]
@Nutomic It could be because the version on my PC changed so the two weren’t able to connect anymore, which saved folder scans on Android.
