### ISSUE TITLE
Startup takes very long

### ISSUE THREAD

**Issue by Profpatsch** [syncthing/syncthing-android#350]
When Sycthing is started, it takes between five and ten seconds until it is usable.

This might not be a problem if it could be left running (see #349).

**Comment by Zillode** [comment]
How many files are indexed? I guess this is Syncthing loading the database.

**Comment by Profpatsch** [comment]
Only around 1000.

**Comment by AudriusButkevicius** [comment]
Total size wise?

**Comment by Profpatsch** [comment]
About 10GB

**Comment by AudriusButkevicius** [comment]
Yeah, SHA256 over all of that on a phone might take a while.

**Comment by Profpatsch** [comment]
I wonder why this has to be done at startup.

**Comment by AudriusButkevicius** [comment]
This is done in a blocking way in syncthing, though the web UI starts listening before that, hence the app should start fine.
Plus the expensive indexing is only done once upon first start.

**Comment by canton7** [comment]
I've also seen Syncthing take over 10 seconds to start listening on its API - I think that's causing https://github.com/canton7/SyncTrayzor/issues/47 and https://github.com/canton7/SyncTrayzor/issues/48

**Comment by calmh** [comment]
We walk the database to find and drop info for no longer existing folders, before starting the HTTP server (https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/main.go#L510). This can take a while, if the database is large (compared to the available CPU and IO capacity...). I don't **think** there should be any negative effects to moving this after creating the model and starting the GUI...

**Comment by Zillode** [comment]
This should be fixed in the next release (0.6.0), feel free to reopen if this is still an issue.
