### ISSUE TITLE
The consistency of the app degenerates when not restarting immediately

### ISSUE THREAD

**Issue by Profpatsch** [syncthing/syncthing-android#355]
When you ignore the restart prompt (which can happen by accident, since tapping outside dismisses it), pretty much no internal consistency is guaranteed anymore.

Examples of this:
* Folders with the same ID can be created
* New folders are not displayed
* Deleted folders are still displayed
* probably even more things

**Comment by Profpatsch** [comment]
The easiest way to fix this is to make restart mandatory. But that is a problem, see #350.

**Comment by Nutomic** [comment]
I think it should be enough to refresh `mConfig` and possibly call `onApiChanged()` to fix this.

#353 is also part of this.
