### ISSUE TITLE
Menu jumps downwards on first open

### ISSUE THREAD

**Issue by Profpatsch** [syncthing/syncthing-android#357]
When you first open the menu and want to hit “Exit”, it jumps downwards under your finger (so you hit “Donate” by accident) because the statistics get loaded after the menu is already pulled out and expand afterwards.

**Comment by Nutomic** [comment]
That's because it takes a bit to load the device ID. 

I think the best solution would be to hardcode the TextView line count in the layout. But this might not work because different devices will use different amounts of space for the ID (depending on font size etc).

**Comment by Profpatsch** [comment]
@Nutomic How about pre-loading the device ID into a data structure and then using that inside the UI?

**Comment by Nutomic** [comment]
What do you mean by data structure?

As another option, we could set a string of all spaces with the same length as the device ID.

**Comment by Zillode** [comment]
I tried that, even with monospacing it didn't work well:o
Maybe I missed something.

**Comment by Nutomic** [comment]
Seems to be because space allows line breaks and the actual device id doesn't. It works if you set `android:layout_width="match_parent"` on `device_id_title`.

**Comment by Profpatsch** [comment]
> What do you mean by data structure?

Class or whatever you call it in Java.
The offending string is my client UUID and that should be globally the same, so something like `globalClientOptions.getID()`.

**Comment by Nutomic** [comment]
The problem is, we need to read the key from the API first, and that takes some time. Besides, global variables are evil ;)

**Comment by Profpatsch** [comment]
Then just do it asyncronously after startup. Would be generally a good idea to get rid of the API waiting time imho.

**Comment by Profpatsch** [comment]
This I get directly after launch in logcat:

    I/SyncthingNativeCode(14808): [QLVJ2] 08:38:13 INFO: My ID: QLVJ26E-AK5LXNM-FRFG4IS-4MFLEZO-SUWQWOV-DMV7K7Y-POJ2JKT-P25LKAV

**Comment by Profpatsch** [comment]
This is fixed in 0.11 as well.
