### ISSUE TITLE
UX (textual) problems - more or better info to the user needed

### ISSUE THREAD

**Issue by jockbert** [syncthing/syncthing-android#358]
Rephrasing needed: Sign "Syncthing is disable - Do you want to change your preferences?". Given options "Exit" and "Change Settings". It is not obvious that this (in my case) is related to the settings option "Running in background".

Rephrasing needed: The sign "Waiting for API", shown on GUI start, does not tell you anything more than that you are waiting. Waiting for an Application Programming Interface? Almost anything is or can be an API. Is it some local API or is it a call to a server on the Internet? What is the API for?

Further details needed: What does the value in the setting "Rescan interval" represent? For e.g. 60, is it 60 seconds or 60 days? What does the rescan interval mean for the value 0? Is it ever scanned? Is it scanned only once or all the time?

**Comment by Nutomic** [comment]
Do you have a concrete suggestion for this? Preferably in one sentence.

We changed the "Waiting for API" text to "Loading" for the next version, that's probably the best/most concise option.

Rescan interval is removed for the next version. We have inotify, so this was really a leftover.

**Comment by jockbert** [comment]
## Regarding *"Waiting for API"*
The change to *"Loading"* is IMHO a great improvement.


## Regarding *"Syncthing is disable"*
After further investigations it seems that the reason is a little bit more complicated than just having *"Always run in background"* checked. I also had to have some of the options *"Sync only when charging"* or *"Sync only on wifi"* checked and unfulfilled. If the message just depends on these conditions I think it may be a good idea to be specific about it. Also perhaps not mix the words *"preferences"* and *"settings"*. Suggestion: 

* message heading: *Syncthing only runs when on wifi and/or charging.*
* message body: *Do you want to change the settings?*

If it is possible to show different message headers for different conditions, these might be better:
* *Syncthing only runs when on wifi.*
* *Syncthing only runs when charging.*
* *Syncthing only runs when on wifi and charging.*

Somewhat off-topic question in the perspective of a user - why shouldn't I be able to fiddle around in the GUI just because folder syncing is not active according to some setting? I don't know the inner workings of Syncthing and I guess there are some technical reasons, but as a user, do I care?  Isn't it possible to just override the conditional settings when manually starting the GUI?

**Comment by Nutomic** [comment]
The problem is that the app depends on the Rest API for all funtionality. If the API isn't available, we don't know anything about the folders, devices etc that the user has configured. So there's no sense having the GUI in that case.

**Comment by Zillode** [comment]
This information is also available when reading the config file

**Comment by jockbert** [comment]
@Nutomic OK, but why not just start the Rest API? I don't know if it is a good or feasible idea but I want to at least raise the question in the prospect of reducing UX friction. Getting a message saying *"Syncthing is disabled"* or *"Syncthing only runs when charging"* is definitely friction. The user probably wanted to do something useful when starting the app. 

So, when **not** set to run in the background, "underlying things" starts automatically when the app is started. Right? Why not **always** start the "underlying things" when you start the app? When closing, you can fall back to the behavior in the settings.

**Comment by Nutomic** [comment]
@Zillode Reading the config is a ton of extra complexity, and will probably break all the time.

@jockbert See syncthing/syncthing#215

**Comment by Zillode** [comment]
This is https://github.com/syncthing/syncthing-android/issues/254
