### ISSUE TITLE
[0.11] Can't add/delete folders using GUI, but manage it using Web GUI

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-android#363]
After creating these folders with the GUI:
![screenshot_2015-04-18-04-00-22](https://cloud.githubusercontent.com/assets/10074769/7214374/f12ff0f2-e57f-11e4-9ccb-fc021346b674.png)

couldn't create add any more folders using the GUI, but managed it using the Web GUI. Did exactly like I did with the previous 3 folders: filled the fields, clicked on `CREATE`, then restarted, but the folders were not created.

Running this version from the beta [APK](http://wilma.vub.ac.be/~lhoste/private/syncthing-0.11-beta-arm-debug.apk):
![screenshot_2015-04-18-02-02-02](https://cloud.githubusercontent.com/assets/10074769/7214304/5a56e030-e57c-11e4-86d9-6ec5298e7831.png)
on a Motorola E XT1022 with Android 4.4.4.

Tried to debug it:

1. Set `Debug Options` to `files,events,model`, but I confess I wasn't sure which facilities were more appropriate to catch the problem
2. Tried to add this folder using the GUI:

    **Folder ID**: *sd.download*
    **Directory**: */storage/sdcard1/Download*
    **Devices**: *monk*
3. Captured the [log](http://paste.ubuntu.com/10842772/). New option `Open Log` makes this so much simpler !
4. Successfully added the folder using the Web GUI
5. Captured the [log](http://paste.ubuntu.com/10842777/)

When I first managed to create the folder using the Web GUI, I tried to delete it so that I could start from scratch with debugging, but couldn't delete it either using the GUI, although managed it with the Web GUI. In other words, **after creating those first 3 folders, couldn't add nor delete any more folders using the GUI, only using the Web GUI**.

Just to confirm, after adding `sd.download` using the Web GUI, tried to add another folder using the GUI:

**Folder ID**: *whatsapp*
**Directory**: */storage/emulated/0/WhatsApp/Media*
**Devices**: *monk*

but failed just the same, so continued adding folders using only the Web GUI.

Let me know if those debug options were appropriate to catch the problem, and whether you need me to do anything else to debug this further.

**Comment by marcelpaulo** [comment]
Decided to try a different approach:

1. Reinstall from scratch
2. Create all folders from */storage/emulated/0*
3. Create all folders from */storage/sdcard1*

I'll describe all steps, so that they can be correlated with the logcat

1. Uninstall, reinstall APK
2. Connect phone to desktop, start `adb logcat | grep -i syncthing | tee logcat` on desktop
3. Start syncthing on phone
4. Delete default folder `camera`
5. Restart
6. Configure, without intervening restart:

    ***Always run in background***: *yes*
***Sync only on wifi***: *yes*
***Use advanced Folder Picker***: *yes*
***Device Name***: *thelonious*
***Global Discovery***: *no*
***Enable UPnP***: *no*
***Anonymous Usage Reporting***: *yes*
7. Restart
8. On the GUI, create all folders from ***/storage/emulated/0***, without intervening restart
9. Restart. They were all created as expected:
![02 - screenshot_2015-04-18-17-56-56](https://cloud.githubusercontent.com/assets/10074769/7217331/ace41b14-e5fa-11e4-8065-813877e78eda.png)
10. On the GUI, create all folders from ***/storage/sdcard1***, without intervening restart
11. Restart. None of them were created !
12. On the Web GUI, create them again, without intervening restart:
![02 - screenshot_2015-04-18-18-16-57](https://cloud.githubusercontent.com/assets/10074769/7217332/f0bc2584-e5fa-11e4-8e36-3b1a1382357f.png)
13. Restart. Now they were created:
![02 - screenshot_2015-04-18-18-26-12](https://cloud.githubusercontent.com/assets/10074769/7217334/08b0f0e8-e5fb-11e4-84d0-72a54aa548e9.png)
14. Stopped logcat.

The resulting logcat is [here](http://paste.ubuntu.com/10847379/).

**Comment by marcelpaulo** [comment]
A weird side effect of the preceding procedures. On the *Web GUI*, the desktop appears (correctly) connected:
![02 - screenshot_2015-04-18-18-51-04](https://cloud.githubusercontent.com/assets/10074769/7217353/5dab8990-e5fc-11e4-9ee4-b2bf6dbca813.png)
but on the *GUI*, it appears (incorrectly) disconnected:
![02 - screenshot_2015-04-18-18-51-11](https://cloud.githubusercontent.com/assets/10074769/7217354/76b69182-e5fc-11e4-9333-6510d66f4477.png)

**Comment by marcelpaulo** [comment]
Can't be reproduced anymore with latest beta [apk](http://wilma.vub.ac.be/~lhoste/syncthing/unofficial/syncthing-0.11-1-arm-release.apk).

**Comment by Zillode** [comment]
(no idea why)
