### ISSUE TITLE
[0.10 and 0.11] Export configuration to a folder under /storage/emulated/0

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-android#364]
Would it be neater to export the configuration files to a folder under */storage/emulated/0* instead of directly under it, as it's done now for both 0.10 and 0.11 branches ?

This is almost cosmetic, but I catch myself always doing this manually: exporting the configuration, then moving the 3 files:
```
cert.pem
config.xml
key.pem
```
to another folder (to be synced to my laptop using syncthing !).

**Comment by Nutomic** [comment]
I'm pretty undecided about this. What folder would you suggest?

**Comment by marcelpaulo** [comment]
Don't know if there's a standard such as FSH for Android, but I've seen
that there's already a:

*/sdcard/Android/data/com.nutomic.syncthingandroid.debug/files*

so would something like:

*/sdcard/Android/data/com.nutomic.syncthingandroid/backup*

fit in?

**Comment by Nutomic** [comment]
Two problems with that:
- the folder is rather difficult to find if you don't know it
- if you uninstall the app, that folder is deleted, possibly including your just backed-up keys and config

So I wouldn't use it.

**Comment by marcelpaulo** [comment]
Agreed, it makes sense.

After I export my configuration, I move the 3 files to:

`/storage/sdcard1/data/syncthing`

and, of course, `/storage/sdcard1/data` is defined as a syncthing folder, so that it syncs with my laptop.

So, I'd suggest:

`/storage/emulated/0/data/syncthing`

Would this respect Android filesystem standards and solve the 2 problems you raised ?

**Comment by Nutomic** [comment]
I have a data folder on my sd card, but the only folder in there is from Titanium Backup, so not sure if it's a standard one. Do you know any documentation on this?

Also, this has the same problem of being difficult to find for new users (if they don't read the toast very carefully).

**Comment by marcelpaulo** [comment]
>  Do you know any documentation on this?

I googled around but only stumbled across very generic articles, such as [this](https://www.anantshri.info/andro/file_system.html). Very far from FHS.

I posted this [question](http://androidforums.com/threads/is-there-a-filesystem-hierarchy-standard-for-android.915347/) on [AndroidForums](http://androidforums.com/), let's see if something comes out of it. Off topic perhaps, do you know of any good, solid forums for Android ?

> this has the same problem of being difficult to find for new users

Not if it's documented. Whatever directory is chosen will be difficult to find if not documented. For that matter, the way it is done now, new users won't intuitively spot which files belong to syncthing's exported configuration.

**Comment by marcelpaulo** [comment]
The discussion on the AndroidForums [thread](http://androidforums.com/threads/is-there-a-filesystem-hierarchy-standard-for-android.915347/) is stretching on. What I've read and tested so far confirms my vote for:

`/storage/emulated/0/data/syncthing`

or alternatively:

`/storage/emulated/0/backups/syncthing`

after I observed that apps such as `ES File Manager` keep their backups under `/storage/emulated/0/backups`.

**Comment by Nutomic** [comment]
[xda-developers](https://xda-developers.com) is quite popular, as is the [Android Subreddit](https://reddit.com/r/Android).

`backups/` sounds like a good option actually, I'll implement that :+1:

**Comment by marcelpaulo** [comment]
Great, @Nutomic, happy that you changed this !

Thanks for the tips about Android forums: have already created accounts on both !

**Comment by Nutomic** [comment]
Maybe that gives you something else to do than opening issues /s

**Comment by marcelpaulo** [comment]
Serial issue opener :D

I better lay low for a while lest I be hunted down and caught !
