### ISSUE TITLE
[0.11] Not exiting even if "Always run in background" is disabled

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-android#365]
syncthing-android is not exiting even if `Always run in background` is disabled and `Exit` is tapped.

Running version:
![01 - screenshot_2015-04-18-02-02-02](https://cloud.githubusercontent.com/assets/10074769/7215373/20ff3e16-e5ab-11e4-9d4b-3c93b7d54845.png)
on a Motorola E XT1022 with Android 4.4.4

To reproduce it:

1. Connected the phone to the desktop, and run `adb logcat | grep -i syncthing | tee log` on the desktop
2. Disabled ``Always run in background`:

![01 - screenshot_2015-04-18-08-56-39](https://cloud.githubusercontent.com/assets/10074769/7215389/b997e984-e5ab-11e4-9b91-dd0d04d11743.png)
3. Tapped `Exit`:

![01 - screenshot_2015-04-18-08-56-51](https://cloud.githubusercontent.com/assets/10074769/7215391/d83bdc9c-e5ab-11e4-85a9-acb3b8b655b0.png)
4. Checked notifications, confirmed that syncthing didn't exit:

![01 - screenshot_2015-04-18-08-57-10](https://cloud.githubusercontent.com/assets/10074769/7215393/fd7a40ac-e5ab-11e4-9a06-85c846f0c20a.png)
5. Stopped logcat. [Here](http://paste.ubuntu.com/10844119/) is the log.

Let me know if there's anything else I can do to help debug this.

**Comment by Nutomic** [comment]
I just tried this, and the notification is dismissed in my case. Your log also says the service was stopped. Maybe you have to wait a few seconds for the notification to disappear?

**Comment by marcelpaulo** [comment]
> Maybe you have to wait a few seconds for the notification to disappear?

Waited for exactly 5 min, and it didn't disappear. Let me show you, please check the time on the following screenshots:

1. Confirmed that the notification was being shown:
![screenshot_2015-04-19-20-24-00](https://cloud.githubusercontent.com/assets/10074769/7221860/c708dd8e-e6d3-11e4-80ce-d396b9dd1848.png)
2. Disabled `Always run in the background`:
![screenshot_2015-04-19-20-24-38](https://cloud.githubusercontent.com/assets/10074769/7221861/d6576af8-e6d3-11e4-9320-058362926dbf.png)
3. Tapped `Exit`
4. Checked currently running apps. syncthing didn't exit:
![screenshot_2015-04-19-20-25-19](https://cloud.githubusercontent.com/assets/10074769/7221864/f93fdbc2-e6d3-11e4-8a42-6ea19851a9c8.png)
5. Swiped syncthing to the right, to close it:
![screenshot_2015-04-19-20-25-41](https://cloud.githubusercontent.com/assets/10074769/7221865/1f73d9ce-e6d4-11e4-844c-e9b9d6e8d232.png)
6. Waited for exactly 5 min, you can confirm looking at the time displayed on the screenshots
7. Checked the notifications. syncthing was still there:
![screenshot_2015-04-19-20-30-13](https://cloud.githubusercontent.com/assets/10074769/7221867/5559b34c-e6d4-11e4-86b6-e9b4eab3ace8.png)
8. Run `top -m 10 -s cpu` on `Terminal Emulator for Android`. Monitored for 1 min. The CPU-hungry syncthing process didn't show up. As I showed on #362, it always uses 30—50% CPU, so if it were running, it would have shown up.

My conclusions:

1. `Exit` is not exiting the app
2. The notification is still shown even if the app is closed and `Always run in the background` is disabled.

**Comment by Nutomic** [comment]
@Zillode I suppose this is related to one of your changes.

**Comment by Zillode** [comment]
Fixed by https://github.com/syncthing/syncthing-android/commit/767177e28d2a63a78fa87542c838cf8897f3b177
