### ISSUE TITLE
"Syncthing is running" notification is not dismissable

### ISSUE THREAD

**Issue by carltonwhitehead** [syncthing/syncthing-android#366]
This notification is [built](https://github.com/syncthing/syncthing-android/blob/master/src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingService.java#L203) with `.setOngoing(true)`. The documentation for [NotificationBuilder.setOngoing(boolean)](https://developer.android.com/reference/android/app/Notification.Builder.html#setOngoing%28boolean%29) is as follows at the time of submission:

> Set whether this is an "ongoing" notification. Ongoing notifications cannot be dismissed by the user, so your application or service must take care of canceling them. They are typically used to indicate a background task that the user is actively engaged with (e.g., playing music) or is pending in some way and therefore occupying the device (e.g., a file download, sync operation, active network connection).

This doesn't seem to be an appropriate use case for an "ongoing" notification, since the background service is merely waiting to receive updates from other connected devices or local file changes by the user. The user is not actively engaged in any way, and the SyncthingService is barely occupying the resources of the device unless a sync operation happens to be underway (which would be an appropriate use of an "ongoing" notification).

**Comment by Nutomic** [comment]
I think the ongoing notification is appropriate, because it is an ongoing sync operation. I agree that it shouldn't be necessary if the app can run completely in the background, but #349 and #362 suggest that we're not there yet.

Besides, the notification has low priority, so you shouldn't usually notice it.

**Comment by Nutomic** [comment]
Closing this as wontfix for now, we can think about this again once CPU usage gets better ;)

**Comment by Nutomic** [comment]
Reopening because more people are requesting this now.

**Comment by wbedard** [comment]
This sounds like it could be re-implemented as a user-configurable option (i.e. to have a persistent notification) as many such "background" apps do.

**Comment by Nutomic** [comment]
Yeah, it would be trivial to add a checkbox.

The problem I see is that we are getting a lot of options, and should put some thought into organizing them (see [this thread](https://forum.syncthing.net/t/improve-android-settings-layout/2365/4)).

**Comment by wbedard** [comment]
I've seen a lot of very successful and highly rated apps simply lump all their options into one (occasionally long...) scrolling "Settings" screen.  You can subdivide it into various functionality sections to keep related options together.  I wouldn't over-think how you organize such settings in the early stages of this app.  With some anonymous usage feedback, you could get a better understanding of which options are being used the most and factor that into a more "thematic" redesign of the UI down the road.

**Comment by plittlefield** [comment]
Does it take a lot to show the icon in the top status bar? I'd like to see it. Just an option to hide icon in notification is required. Thanks.

**Comment by Nutomic** [comment]
Looks like we should implement these three options:
- normal notification
- low priority notification
- no notification

**Comment by Eddy2909** [comment]
and icon on statusbar :-)

Am 28. Juni 2015 14:22:19 MESZ, schrieb Felix Ableitner <notifications@github.com>:

**Comment by Nutomic** [comment]
That's what normal notification is ;)

**Comment by plittlefield** [comment]
Not sure you need to go to THAT much trouble, just a simple yes or no would
be fine honestly :-)

**Comment by plittlefield** [comment]
Screenshots to show you that it's on the drop-down, but missing from top
status bar...

**Comment by Nutomic** [comment]
There's already a yes/no option for 2/3. But people also want option 1, so we'll need a dropdown.

**Comment by plittlefield** [comment]
I know it's a small mute point but it would be nice to be able to glance at
the phone and go, "yeah, syncthing is running" without touching the phone
:-)

**Comment by plittlefield** [comment]
Not sure if this the correct place, but thank you SO much for providing this feature in the new version 0.6.5. Much appreciated. More money on its way to you! I am a very happy bunny  :-)

**Comment by Nutomic** [comment]
I didn't know we have bunnies in our userbase, glad to help the animal realm :D 

Thanks for the donation, still gotta figure out how Bountysource works.

**Comment by plittlefield** [comment]
:-)

**Comment by nelsonblaha** [comment]
Did this get removed since? I can't find a way to hide ongoing "syncthing is disabled" notification.

**Comment by Nutomic** [comment]
If you're using Android 8, you can change it by long clicking the notification.
