### ISSUE TITLE
Enormous amount of files in cache directory

### ISSUE THREAD

**Issue by yix** [syncthing/syncthing-android#374]
Application creates enormous amount of files in Cache directory (29k+):

/data/data/com.nutomic.syncthingandroid/app_webview/Cache # ls | wc
    29844     29844    567014

**Comment by Nutomic** [comment]
I'm not really sure how the WebView cache works. Deleting that folder did not change the data or cache size values in the app settings. Same with opening the WebView in the app again.

I didn't find any info on this, but I guess Android is smart enough to clear this automatically. So I assume this is ok, but I'd like to see some documentation.

**Comment by calmh** [comment]
Are these cached REST responses? We could/should perhaps include the relevant cache-disabling headers on the server side.

**Comment by calmh** [comment]
Actually, we do set `Cache-Control: no-cache` on those, so that should be fine already.

**Comment by calmh** [comment]
I added some more, just to be super duper clear to whatever user agent is in use.

https://github.com/syncthing/syncthing/commit/f5211b0697a711b5e6aa133b393698ba06111c9f

**Comment by yix** [comment]
Hi Jakob, thanks for this fix. I will test it.

**Comment by Nutomic** [comment]
If that doesn't work, we can probably also disable caching on the Android side.
