### ISSUE TITLE
Freezes device when syncing (2 androids) 

### ISSUE THREAD

**Issue by sreich** [syncthing/syncthing-android#379]
I'm syncing between 2 android devices. I originally thought my nexus 5 was having some really bad android issues with the update, or a hw issue. It will often get laggier and laggier quickly.. Until it seems to just freeze up entirely. I managed to show process stats before it got extremely bad, and it turns out it is because of syncthing. 

Setting it to do this only when charging of course doesn't fix it.. Because then it'd just be unresponsive when I pick it up. 

There are 2 dirs, one with 2k files, 6.2gib. The other with 500 files, 300mib. 

I wish there was a mechanism to give it an upper limit of how much cpu and IO time it can use, because this is just ridiculous. I've used syncthing for several months, haven't had this issue before. Only happened like in the past month or two. 

Or maybe it's just gotten worse as I've added more videos.. Either way, this makes it pretty unusable. The files are entirely synced over, too. So it's not like I just made a lot of things and it's transferring. 

It really needs to be made as more of a "run in the background, when idle" as much as possible, and to never hog the CPU. I don't know, maybe there are cpu and IO hints you can give to android for its scheduler, to at least help going into the direction of being responsive.

**Comment by Zillode** [comment]
1) As mentioned in the [guidelines for contributing](https://github.com/syncthing/syncthing-android/blob/master/CONTRIBUTING.md), please provide logs.

2) Also, as discussed in the [FAQ](https://github.com/syncthing/syncthing/wiki/FAQ#synchronization-does-not-complete-when-using-multiple-android-devices), syncing multiple android devices does not work properly and might cause endless loops.

3) Please provide which version you are using, the newer versions have support for 'niceing' IO on Android.

4) There are GOGC and GOMAXPROCS flags which you can use to limit RAM & CPU usage

5) In the config.xml file you can customize the hashers and pullers

**Comment by sreich** [comment]
Hm, I am using multiple android devices.. Shame that syncing them both isn't really supported... I'm sure a lot of people want to eg sync their DCIM dirs together. 

Version 0.5.28 on play store. 

Thanks.

**Comment by Zillode** [comment]
Feel free to implement this feature or vote for it at https://www.bountysource.com/issues/5226549-option-to-not-sync-mtime
