### ISSUE TITLE
Unable to set global discovery servers

### ISSUE THREAD

**Issue by merlinuwe** [syncthing/syncthing-android#380]
On my Medion tablet with Android 4.4.4 (kitkat) I cannot always change the global discovery servers in your wrapper and also not in the web-interface. I have tried to put in 2-6 entries. I most often get (after a restart of the app) the previous set of entries. The system often "forgets" the last added entries.

**Comment by Zillode** [comment]
Probably duplicate of https://github.com/syncthing/syncthing-android/issues/212
