### ISSUE TITLE
Tune number of hashers

### ISSUE THREAD

**Issue by neclepsio** [syncthing/syncthing-android#384]
When active, the whole system freezes, even if running in background. I have a stock Nexus 5 with Android 5.1. The only other application that can freeze my entire device, in the very same way, is BTSync, so maybe the problem is elsewhere. Please tell how can I help you investigate the issue.

UPDATE: I think the problem is very, very high CPU usage.

UPDATE 2: after indexing my >10GB camera directory, things seem a little better. Usage dropped from >80% to 40%. Still, doesn't it seem a bit too high?

**Comment by Zillode** [comment]
1) We should tune the hashers for Android devices.

2) It is high, but expected, see https://github.com/syncthing/syncthing-android/issues/362

**Comment by neclepsio** [comment]
Thanks.
