### ISSUE TITLE
[0.11-6RC] Installing 0.11-6RC on top of 0.11-3 generates another installed ST instance

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-android#387]
Installing 0.11-6RC on top of 0.11-3 generates another installed ST instance:

![screenshot_2015-05-06-00-13-37](https://cloud.githubusercontent.com/assets/10074769/7487195/0537761c-f389-11e4-996b-60de930f50dc.png)

Shouldn't there be only 1 resulting ST instance if the upgrade path is within the same branch ?

**Comment by Zillode** [comment]
This was a debug version, so no.
