### ISSUE TITLE
Change green, blue, purple colors in UI to be the same as in Web GUI

### ISSUE THREAD

**Issue by acriptis** [syncthing/syncthing-android#390]
When I use syncthing there are 3 colors used for states description in web GUI:
 - green (#29b74e)
 - blue (#3498db)
 - purple (#7f4bab)
 
By the way android app expose different set of colors:
https://github.com/syncthing/syncthing-android/blob/master/src/main/res/values/colors.xml

Although there is no style guidline for syncthing related projects I think this minor enhancement would make android app look better and more in "syncthing style".

**Comment by Nutomic** [comment]
Yep, I think syncthing changed these colors at some point.

I suggest taking the exact color codes from [here](https://developer.android.com/design/style/color.html).

Btw, it should be trivial to change the values and make a pull request ;)

**Comment by Nutomic** [comment]
I'm closing this, as we don't really indent to follow the design of the web GUI directly (we use material design instead).
