### ISSUE TITLE
[0.6.0] ST crashes and restarts on "Open Log"

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-android#391]
When I try to run `Open Log` from Settings, ST crashes and restarts:
![screenshot_2015-05-13-22-18-45](https://cloud.githubusercontent.com/assets/10074769/7624464/3985e692-f9bf-11e4-828c-6004681acd2e.png)

Here's a [logcat](http://paste.ubuntu.com/11122449/) with `Debug Options` set to `all`, started before tapping on `Open Log`, and stopped after ST restarted.

Running ST-A **0.6.0** on a Motorola Moto E XT1022 with Android KitKat 4.4.4.

**Comment by chucic** [comment]
Duplicate #389?

**Comment by marcelpaulo** [comment]
I did search for open or closed issues before opening, I shouldn't have missed that. 

I'm going to take another logcat, but not filtered as I've done, to check whether that Java exception happens. Then we'll whether it's really a duplicate.

**Comment by marcelpaulo** [comment]
@chucic, I took another logcat but didn't filter it on `syncthing`, and couldn't see the Java exception right before ST-A crashes, as shown in #389. [Here](http://paste.ubuntu.com/11125754/) it is. So perhaps it's not a duplicate, not sure, I confess.

**Comment by chucic** [comment]
I got same error as you when I was using one of Zillode's builds. With this release I got it too, but this time I have option to send report to Google and "Stack trace" shows exactly same think as first post in  #389. I didn't try logcat though. I guess it's for dev's to decide if this is duplicate...

Also ST-A 0.6.6 on KitKat 4.4.4, on Prestigio 5454. From screenshot I see that you don't have button "Send report to Google", so I guess you are using F-Droid?

**Comment by marcelpaulo** [comment]
> I have option to send report to Google and "Stack trace" shows exactly same think as first post in #389 

Oh, I see, so it does look you're right, @chucic. My bad.

> From screenshot I see that you don't have button "Send report to Google", so I guess you are using F-Droid?

I didn't know there was this difference. You're right: I am using F-Droid. Because it allows you to downgrade to earlier versions. I have needed that in the past.

> I guess it's for dev's to decide if this is duplicate

Let's see what @Zillode or @Nutomic say about this. But your findings do point to closing this issue as duplicate.

Thanks for shedding light !

**Comment by Nutomic** [comment]
Yep this is a duplicate, will be fixed in the next release.
