### ISSUE TITLE
Sync working, odd gui feedback

### ISSUE THREAD

**Issue by zbits** [syncthing/syncthing-android#393]
Hi.

Since moving to the 11 protocol my two devices continue to sync and I verify the files are transferred, but the feedback I'm getting is odd.  I'm using Syncthing to sync my photos on my Android 5.0 device (set as Master) to an Arch linux desktop.  After a sync is complete the Android side says -103/28 Files and 685.3 MiB/685.4 MiB, and in green Idle (99%).  The desktop says my camera folder is up to date 28/28 items, but the right side has my Android device permanently displaying Syncing (100%) in blue.  Perhaps I'm not understanding what it is displaying.

The latest Syncthing v0.11.5 on both sides.

**Comment by Nutomic** [comment]
@calmh @AudriusButkevicius Looks like a syncthing bug to me?  (wrong API values)

**Comment by AudriusButkevicius** [comment]
Screenshots would be useful.

**Comment by zbits** [comment]
I removed the photos directory from my desktop/server side GUI and had it recreated.  This issue went away and all is working perfectly.
