### ISSUE TITLE
Add "Override Changes" Button

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing-android#396]

**Comment by nonbinary** [comment]
Seconded. This function is quite important IMO. I'm syncing my camera folder, but any photographs that I delete stays on my sync receivers. The "folder master" setting isn't really functional without the override.

**Comment by nonbinary** [comment]
Lovely! Sadly, I'm no longer using syncthing for the camera solution, but I'll check the latest app ASAP. I still recommend syncthing to others, occasionally in my work role.
