### ISSUE TITLE
LogActivity not working in Release Builds

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing-android#397]
<nutomic> zillode: it seems that LogActivity is not working in release builds
<nutomic> tried 0.6.1 release from f-droid and 0.6.1 debug build
<nutomic> didn't see any error

**Comment by Zillode** [comment]
wfm

**Comment by Nutomic** [comment]
Does it display the log? 

For me it shows "Retrieving Logs..." forever. (on Lollipop)

**Comment by Zillode** [comment]
Yeah, but I use a custom rom, no logs? Try the adb command from the commandline and see if it fails?

**Comment by Nutomic** [comment]
Just tried it again and it works :o 

And yeah, I tried adb logcat of course.
