### ISSUE TITLE
Syncthing binary crashed with error code 4 (ARM5)

### ISSUE THREAD

**Issue by tnm-** [syncthing/syncthing-android#401]
Taking one small step forward from #336 
Updated and started syncthing-android (0.6.2) on HTC Wildfire with CM7 (Android 2.3)
Logcat available here: http://tnm.no-ip.biz/ftp/syncthing_armv5_startup_logcat_no2.txt
Thanks for your continued effort!
(I'll soon switch from this device to a newer one, but I will test the updated syncthing versions on this one until it works, unless you say not to :) or you decide to drop ARM5 support.)

**Comment by Zillode** [comment]
Fix will be part of 0.6.3. Feel free to reopen the previous issue when it would not be fixed.

**Comment by tnm-** [comment]
ok, but non-collaborators cannot re-open issues if they were closed by a collaborator. (Plus where I work we like to keep different issues --like crashing with different error codes-- in separate tickets so that's my mindset. :) )

**Comment by Nutomic** [comment]
We also get a notification if you comment ;)

Feel free to open a new issue, to.

**Comment by tnm-** [comment]
Still crashes:

I/SyncthingService( 1162): Starting syncthing according to current state and preferences
I/ConfigXml( 1162): App started for the first time. Generating keys and config.
E/SyncthingNativeCode( 1162): Syncthing binary crashed with error code 4
W/ConfigXml( 1162): Failed to open config, moving to config.xml.invalid and creating blank config
E/SyncthingNativeCode( 1162): Syncthing binary crashed with error code 4
W/ConfigXml( 1162): Failed to open config, moving to config.xml.invalid and creating blank config
E/SyncthingNativeCode( 1162): Syncthing binary crashed with error code 4
W/ConfigXml( 1162): Failed to open config, moving to config.xml.invalid and creating blank config
E/SyncthingNativeCode( 1162): Syncthing binary crashed with error code 4
W/ConfigXml( 1162): Failed to open config, moving to config.xml.invalid and creating blank config
E/SyncthingNativeCode( 1162): Syncthing binary crashed with error code 4
W/ConfigXml( 1162): Failed to open config, moving to config.xml.invalid and creating blank config
D/dalvikvm( 1162): GC_CONCURRENT freed 471K, 50% free 3182K/6279K, external 128K/512K, paused 6ms+21ms
E/SyncthingNativeCode( 1162): Syncthing binary crashed with error code 4
W/ConfigXml( 1162): Failed to open config, moving to config.xml.invalid and creating blank config
E/SyncthingNativeCode( 1162): Syncthing binary crashed with error code 4
W/ConfigXml( 1162): Failed to open config, moving to config.xml.invalid and creating blank config
E/SyncthingNativeCode( 1162): Syncthing binary crashed with error code 4
W/ConfigXml( 1162): Failed to open config, moving to config.xml.invalid and creating blank config
E/SyncthingNativeCode( 1162): Syncthing binary crashed with error code 4
W/ConfigXml( 1162): Failed to open config, moving to config.xml.invalid and creating blank config
W/SyncthingNativeCode( 1162): usage: ionice <pid> [none|rt|be|idle] [prio]
W/SyncthingNativeCode( 1162): usage: ionice <pid> [none|rt|be|idle] [prio]
I/SyncthingRunnableIoNice( 1162): ionice performed on libsyncthing.so
D/SiMiClock(  687): onUpdate
D/SiMiClock(  687): onUpdate - 4
W/SyncthingNativeCode( 1162): usage: ionice <pid> [none|rt|be|idle] [prio]
E/SyncthingRunnableIoNice( 1162): Failed to set ionice 1
W/SyncthingNativeCode( 1162): usage: ionice <pid> [none|rt|be|idle] [prio]
I/SyncthingRunnableIoNice( 1162): ionice performed on libsyncthing.so
E/SyncthingRunnableIoNice( 1162): Failed to set ionice 1
D/dalvikvm( 1162): GC_CONCURRENT freed 437K, 49% free 3260K/6279K, external 128K/512K, paused 27ms+80ms
I/SyncthingRunnableIoNice( 1162): ionice performed on libsyncthing.so
E/SyncthingRunnableIoNice( 1162): Failed to set ionice 1
I/SyncthingRunnableIoNice( 1162): ionice performed on libsyncthing.so
E/SyncthingRunnableIoNice( 1162): Failed to set ionice 1
W/SyncthingNativeCode( 1162): usage: ionice <pid> [none|rt|be|idle] [prio]
I/SyncthingRunnableIoNice( 1162): ionice performed on libsyncthing.so
E/SyncthingRunnableIoNice( 1162): Failed to set ionice 1
E/SyncthingNativeCode( 1162): Syncthing binary crashed with error code 4
W/ConfigXml( 1162): Failed to open config, moving to config.xml.invalid and creating blank config
W/SyncthingNativeCode( 1162): usage: ionice <pid> [none|rt|be|idle] [prio]
W/SyncthingNativeCode( 1162): usage: ionice <pid> [none|rt|be|idle] [prio]
I/SyncthingRunnableIoNice( 1162): ionice performed on libsyncthing.so
E/SyncthingRunnableIoNice( 1162): Failed to set ionice 1
I/SyncthingRunnableIoNice( 1162): ionice performed on libsyncthing.so
E/SyncthingRunnableIoNice( 1162): Failed to set ionice 1
W/SyncthingNativeCode( 1162): usage: ionice <pid> [none|rt|be|idle] [prio]
I/SyncthingRunnableIoNice( 1162): ionice performed on libsyncthing.so
E/SyncthingRunnableIoNice( 1162): Failed to set ionice 1
W/SyncthingNativeCode( 1162): usage: ionice <pid> [none|rt|be|idle] [prio]
I/SyncthingRunnableIoNice( 1162): ionice performed on libsyncthing.so
E/SyncthingRunnableIoNice( 1162): Failed to set ionice 1
E/SyncthingNativeCode( 1162): Syncthing binary crashed with error code 4
D/ViewConsistency( 1162): AbsListView android.widget.ListView@406006b8 enabled= false
D/ViewConsistency( 1162): AbsListView android.widget.ListView@406006b8 enabled= false
D/ViewConsistency( 1162): AbsListView android.widget.ListView@4058e9b0 enabled= false
D/ViewConsistency( 1162): AbsListView android.widget.ListView@4058e9b0 enabled= false
W/KeyCharacterMap( 1162): No keyboard for id -1
W/KeyCharacterMap( 1162): Using default keymap: /system/usr/keychars/qwerty.kcm.bin
W/SyncthingNativeCode( 1162): usage: ionice <pid> [none|rt|be|idle] [prio]
I/SyncthingRunnableIoNice( 1162): ionice performed on libsyncthing.so
E/SyncthingRunnableIoNice( 1162): Failed to set ionice 1
W/SyncthingNativeCode( 1162): usage: ionice <pid> [none|rt|be|idle] [prio]
I/SyncthingRunnableIoNice( 1162): ionice performed on libsyncthing.so
E/SyncthingRunnableIoNice( 1162): Failed to set ionice 1
W/InputManagerService(  183): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@408e0f08

**Comment by Nutomic** [comment]
Do you have Syncthing moved to sdcard by any chance? If you have root, can you check that the binary in `/data/data/com.nutomic.syncthingandroid/lib` has the execute flag set?

**Comment by tnm-** [comment]
it is not moved to sdcard,
permissions

-rwxr-xr-x    1 system   system     9076808 Jun 19 20:24 libsyncthing.so

**Comment by Nutomic** [comment]
The exit code 4 in your log seems to indicate that [Syncthing is upgrading](https://github.com/syncthing/syncthing/blob/master/cmd/syncthing/main.go#L63). Updates are disabled, so no idea why that would happen. Where did you install the app from? Have you tried reinstalling, rebooting etc?

@calmh @AudriusButkevicius Any idea?

**Comment by tnm-** [comment]
I installed (recently just updated) it from google play store. I feel like the reinstall, reboot stuffs are just stabs in the dark, but anyway I did them and the exact same thing happened as far as I can tell from logcat.

Might be that upgrading is not disabled (properly) on the armv5 build?

**Comment by AudriusButkevicius** [comment]
Can you just exec the .so and see what syncthing log produces?

**Comment by Nutomic** [comment]
Are you still having this problem?

**Comment by tnm-** [comment]
Sorry for the absence.
The device is no longer in use, to answer your question I tried to update syncthing, but google play store claims the device is not compatible with the current version.

I think this can be a solution as these device slowly fade out completely, and probably wouldn't not be powerful enough to run syncthing with acceptable user experience.

**Comment by Nutomic** [comment]
Yeah we stopped to support Android 2.x a while ago. I'm closing this issue then.
