### ISSUE TITLE
Add Android TV devices compatibility in Google Play and/or FDroid

### ISSUE THREAD

**Issue by Zranz** [syncthing/syncthing-android#402]
I sideloaded the syncthing apk on my Nexus Player both on the stock rom and cm12.1 and I was able to sync files across computers in both systems. All parts of the interface were accessible only using the remote, although a mouse is more convenient on occasions (specially in the web interface menu).

It would be very convenient to get automatic updates from both markets, if the device Nexus Player was listed as compatible. Thank you.

**Comment by Nutomic** [comment]
Do you know how to enable this? I found [this](https://developer.android.com/training/tv/index.html), but the link "Distributing to Android TV" is dead. And I couldn't find any settings in Google Play.

**Comment by Nutomic** [comment]
Ah, there's a field for "TV screenshot". If you can send me one, I can upload that and maybe it'll work. Ideally by pull request.

**Comment by Zranz** [comment]
So, as far as I know, there are like two markets for Android Tv. The "official" Android TV market is the one you can access from the TV, and has very few Apps. All of them are reviewed by Google team before being published, and have strict quality (interface) restrictions.

The other way to install apps is with Google Play from a web browser with the computer. Some apps appear as compatible to install on the Nplayer (although they do not appear in the Android TV market) and can install automatically and update. An example of this is [ES File Explorer File Manager](https://play.google.com/store/apps/details?id=com.estrongs.android.pop&hl=en), or SuperSu. Syncthing appears using this method as "device is not compatible" though.

I attach a photo of the app in the TV, since I do not know how to take screenshot with the NPlayer. If you really need it, I will investigate further.
![20150527_231830](https://cloud.githubusercontent.com/assets/10563919/7848055/b0b2bf1a-04c8-11e5-82a6-9cbc4d36bc78.jpg)

**Comment by Nutomic** [comment]
Yeah I meant an actual screenshot that I can upload to the store ([like these](https://github.com/syncthing/syncthing-android/tree/master/graphics)).

Otherwise, we'll have to wait until that link works.

**Comment by Zranz** [comment]
It happens I don't know how to make a pull request (and I tried)     :(
I have the screenshots, though. If you let me know how I can pass them to you, great!

Meanwhile, a friend gave me these two links. Maybe they are helpful:
http://stackoverflow.com/questions/9510649/how-to-restrict-android-app-to-specific-device-make
http://developer.android.com/google/play/filters.html

**Comment by Zranz** [comment]
Dropbox may be faster:
https://www.dropbox.com/sh/plbmc4sxl0lqek2/AAC935unV6PZdttQgW2WsgEQa?dl=0

**Comment by Nutomic** [comment]
Should be fixed with the next version, let me know if not ;)

**Comment by Nutomic** [comment]
I just noticed I have to enable this in Google Play, so I did that and got this mail back:

>Hello,
>
>Thanks for submitting your app for Android TV. This is a notification that your application, >Syncthing, with package ID com.nutomic.syncthingandroid, is not being distributed on the Play >Store for Android TV.
>
>
>Version Name: 0.6.5
>
>Version code: 471
>
>Current track: PRODUCTION
>
>REASON FOR EXCLUSION:
>Your app crashes immediately after launch, resulting in inability to review your app for Android TV >inclusion.

>Please refer to our TV Activity documentation for details:
>http://developer.android.com/training/tv/start/start.html#tv-activity
>------------
>You may revise and upload an Android TV compliant version of this application.
>
>
>If you feel we have made this determination in error, please reply to this email for additional >information.
>
>Regards,
>The Google Play Team 

Can you (or someone else) send me a logcat of that crash?

**Comment by Zranz** [comment]
Hi, I have uninstalled and installed again with Google Play from the web, and it works. First opening message appears, and keys are generated too.

Do you still want me to send you a logcat? I do not see any crash.

I am using stock rom 5.1.1, by the way (rooted)

**Comment by Nutomic** [comment]
No, I just asked them for a logcat, so let's see.

**Comment by Nutomic** [comment]
Huh, now they say they did a "re-review" and apparently it works (not that I changed anything).

So Syncthing should become available for Android TV in the next days.
