### ISSUE TITLE
Material design?

### ISSUE THREAD

**Issue by roberth1990** [syncthing/syncthing-android#404]
When will you transition to material design?

**Comment by unfa** [comment]
Could you explain what is it?

**Comment by roberth1990** [comment]
http://www.google.com/design/spec/material-design/introduction.html#

**Comment by Nutomic** [comment]
The AppCompat theme we're using uses Material Design on Lollipop.

I don't think this works on Kitkat or below, and I don't know of any approach that does.

**Comment by Nutomic** [comment]
Closing this, comment if you have more info ;)

**Comment by roberth1990** [comment]
Google has expanded full backwards compatibility on material down to android 2.0.

**Comment by Nutomic** [comment]
Do you have a link for that? I couldn't find any info.

**Comment by roberth1990** [comment]
https://www.youtube.com/watch?v=8UicJ0SxBwA at 20:00 he announces it. Actually 2.1, but who uses anything older than 2.3?

**Comment by Nutomic** [comment]
I didn't watch the video, is that already released?

**Comment by roberth1990** [comment]
Yes. He said "starting from today".

**Comment by Nutomic** [comment]
Okay so there will probably an update of the AppCompat library.

Also, we still support 2.2 (which I find rather pointless).

**Comment by roberth1990** [comment]
It would better if you saw it yourself, but as far as I understood, yes.

**Comment by Cysioland** [comment]
:+1:

**Comment by veniosg** [comment]
I'm very keen to do this. Material dialogs mostly come for free due to appCompat but metrics, styling and behavior we have to do ourselves. 
Related to how restrictive preference customisation is, I'd love to move the add folder/add device fragments to regular views before proceeding. Is there a specific reason why they're PreferenceFragments? We can still use preferences to store the values if that's a requirement by means of a SharedPreferences object.

**Comment by Nutomic** [comment]
The only reason I did it this way is that it seemed to make sense (seeing as it is configuration). They don't use SharedPreferences, so using views would also be possible.

The [silk client](https://forum.syncthing.net/t/unofficial-opensilk-android-application/2614/45?u=nutomic) uses some very nice dialogs.

**Comment by veniosg** [comment]
I've tried the silk client but while it did look good in screenshots I felt it lacked polish, hence why I'm helping here. I'll start work on a branch on my fork and will PR when each part is done.
