### ISSUE TITLE
Don't treat metered wi-fi connections as wi-fi

### ISSUE THREAD

**Issue by cdhowie** [syncthing/syncthing-android#409]
The "sync only on wifi" option should not cause Syncthing to start if the connected wi-fi network is metered.

Here is an example of the feature to which I'm referring:

![syncthing-wifi-metered-example](https://cloud.githubusercontent.com/assets/354641/8163934/f60bb5b4-1353-11e5-8834-0c9228f28d11.png)

Enabling this feature for a network causes Android to apply background data restrictions to apps as though they were on a cellular data connection.  It would be nice if Syncthing respects this so that I'm not incurring charges on my cellular data plan when I have my wi-fi-only tablet connected through a mobile hotspot.

**Comment by Nutomic** [comment]
Makes sense. This should be fixed with 0.6.4 (not today's version).

**Comment by cdhowie** [comment]
That was fast. :+1:
