### ISSUE TITLE
Upload / Download limits not settable via App menu

### ISSUE THREAD

**Issue by uvok** [syncthing/syncthing-android#413]
The upload and download limits are not respected when set via the setting menu If I set them via the web interface, the options are remembered (and displayed correctly in the settings menu)

Android 4.2.2
Syncthing Android 0.6.4, Syncthing v0.11.9 (F-Droid version)

Steps to reproduce:
- Open Syncthing
- press menu key
- Open settings
- Open Syncthing options
- Set Upload or download limit
- Restart as required

Actual behaviour: The new limit is not remembered, not used (full bandwidth usage)
Expected behaviour: New speed limit appears in the settings menu, network usage should be reduced respectively

**Comment by uvok** [comment]
Same goes for Sync Protocol Listen Addresses

**Comment by Nutomic** [comment]
Should be fixed in 0.9.0-beta1. If not, please open a new issue.
