### ISSUE TITLE
"invalid argument" for files with incorrect chars

### ISSUE THREAD

**Issue by emersion** [syncthing/syncthing-android#415]
Android version: 4.4, Syncthing version: 0.11.9, Synthing-Android version: 0.6.4

I get this message for files containing `"` and `?` in their names:

```
I/SyncthingNativeCode(24840): [PH234] 14:03:09 INFO: Puller (folder "music", file "Black Eyed Peas/Elephunk/13 - Where Is The Love?.mp3"): dst create: open /storage/sdcard0/Music/Black Eyed Peas/Elephunk/.syncthing.13 - Where Is The Love?.mp3.tmp: invalid argument
```

On the web ui, a message is displayed (`Folder "music" isn't making progress - check logs for possible root cause. Pausing puller for 1m0s.`). The sync stops until I rename the invalid file.

**Comment by Nutomic** [comment]
@calmh @AudriusButkevicius ping

**Comment by AudriusButkevicius** [comment]
Are " and ? legal characters on the android file system?
I assume not, as it's exFAT32, isn't it?

**Comment by Nutomic** [comment]
```
$ touch 'a"?'
$ $ ls -l 'a"?'                                       
-rw-rw---- root     sdcard_r        0 2015-06-30 20:08 a"?
$ echo test > 'a"?'
$ cat 'a"?'              
test
```
Seems to work fine (Nexus 5, Android 5.1).

**Comment by AudriusButkevicius** [comment]
In which case I don't have a clue, but it's probably a golang bug.
Can you compile a binary which writes and reads to a file containing `"?` and run it on the phone?

**Comment by Nutomic** [comment]
I made this test program and it works correctly:
```
package main

import "fmt"
import "os"

func main() {
    name := "b?\""
    f1, _ := os.Create(name)
    _, err := f1.Write([]byte("teststring\n"))
    if (err != nil) {
        fmt.Println(err)
    }
    err = f1.Close()
    if (err != nil) {
        fmt.Println(err)
    }
    
    f2, _ := os.Open(name)
    content := make([]byte, 10)
    f2.Read(content)
    fmt.Println(string(content[:10]))
    f2.Close()
}
 ```

**Comment by AudriusButkevicius** [comment]
@emersion are you sure its `"?`? I think your shell might just not be able to print the character replacing it with a question mark.

**Comment by Nutomic** [comment]
If you're still having this problem, please open an issue at syncthing.
