### ISSUE TITLE
[UX] Change name of default folder on Android

### ISSUE THREAD

**Issue by generalmanager** [syncthing/syncthing-android#418]
I think the name "camera" for the folder created by default isn't ideal. If one has several android devices, this will inevitably lead to problems one has to solve.

I propose to change it to something rather individual like "model-photos". The device model (found as "model number" in the settings) is accessible to apps (not sure if it requires additional permissions), user-recognizable and rather individual.

Another option would be to only check if the device is a phone or a tablet and name the folder mobile-photos/cell-photos/tablet-photos or similar accordingly to its classification.

I would avoid phone-photos as it seems a bit confusing. I would also avoid the term pictures, because Android expects an additional folder called pictures on internal and external storage devices, which is for stuff like user-provided background images.

Any comments and improvements on my proposal are appreciated!

**Comment by Nutomic** [comment]
Great idea :+1: 

I also made the name translatable.

**Comment by generalmanager** [comment]
Awesome, thanks!
Those little details are what differentiates great tools from good and mediocre ones. That was astonishingly fast btw ;-)

**Comment by Nutomic** [comment]
If you find more such things, let me know ;)

It was fast because the change was quite simple, and because I'm too lazy to do my homework right now :D

**Comment by generalmanager** [comment]
Yeah I knew it wouldn't be complex, but usually more discussion ensues before a proposal like this gets adopted ;-)
And why do you think I'm thinking about possible improvements to FOSS projects? Exams are coming...

**Comment by Nutomic** [comment]
Hehe 😂
