### ISSUE TITLE
[UX] Use first id-block as name for unknown devices

### ISSUE THREAD

**Issue by generalmanager** [syncthing/syncthing-android#419]
The current behavior for the names of introduced devices seems to be leaving them empty. This makes the UI appear broken and/or incomplete tough. 
Thus I'd like to propose the same behaviour as in the web interface: just truncate the ID to the first 7 chars.

Any comments and improvements appreciated :-)

**Comment by Nutomic** [comment]
Ah, I've never noticed that because I never used that functionality :D

**Comment by generalmanager** [comment]
Yeah, this way the death of a device has at least some advantage. Otherwise I wouldn't have had to setup everything again.

**Comment by Nutomic** [comment]
@calmh In the web GUI, do you just display the first characters of the ID if the device name is empty? Wouldn't it be cleaner to write that into the config as device name instead?
