### ISSUE TITLE
Restart button in the UI

### ISSUE THREAD

**Issue by janjachnik** [syncthing/syncthing-android#420]
It would be useful to have a restart button in the UI to use after selecting "restart later" following some changes.

I'd suggest something which only appears or is highlighted when a restart is required.

**Comment by generalmanager** [comment]
Below the donate button in the slider on the left would probably a good idea. If it doesn't appear all the time but only on delayed restarts, we should highlight it by using a red font.

**Comment by Nutomic** [comment]
Good idea :+1:

**Comment by theAdmiral777** [comment]
+1

**Comment by Dinduks** [comment]
Good idea but I disagree with showing it only when a restart is required: the final user should be able to restart the app, anytime they want to (for debugging purposes for example).
