### ISSUE TITLE
[UX] Change default setting for compression

### ISSUE THREAD

**Issue by generalmanager** [syncthing/syncthing-android#421]
At least for the default folder. Pictures and Videos are basically uncompressable anyway and it's the new default in syncthing.

I assume that most users won't have huge logfiles or similar textfiles on their phones which they sync regularly. And those who do are the kind of people who change default options.

What do you think?

**Comment by Nutomic** [comment]
Hm, seems to be "always" by default, I thought it was "metadata only". 

@Zillode What's your opinion?

**Comment by generalmanager** [comment]
Exactly, it's always in the android version, but the default in upstream was changed to metadata only some time ago.

**Comment by Zillode** [comment]
The reasoning behind that decision was that compression (i.e. CPU) takes less energy than exchanging data (i.e. Wifi/ 3G).
A lot of ppl also use Syncthing to exchange txt files between desktop and phone, so I'm not sure what the best option is.
A small benchmark that uncovers the costs of compressing images would shed some light here.

**Comment by Nutomic** [comment]
Tough call. Can anyone make such a benchmark?

**Comment by generalmanager** [comment]
@Zillode Yes, but compressing text files only scales if they are extremely large. I know many people who use ST + text tiles as a kind of shopping list / todo list. But on average it would probably lead to more saved energy on a global scale if we only compress metadata. That's because nearly everybody with ST on their phone/tablet uses it to sync photos and videos taken with the device. Every picture, video, music file and already compressed file you try to compress wastes CPU time. And that the average size of a photo or video is a lot bigger than the average text file is probably agreeable.

I am familiar with embedded electronics and while I can't cite a comprehensive study comparing the energy consumption while active of all phone/tablet CPUs compared to their GSM/LTE/wifi stack, the following back of the envelope calculation should make it clear that trying to compress pictures creates more energy loss than not compressing textfiles:

Let's assume that the number of synced text files and synced pictures is identical (probably a good assumption, people take lots of pictures on some days and none on other days while they probably update their todo lists and shopping lists once a day).

Let's assume the average size of a photo  taken with a decently modern smartphone is 3MB. That's probably on the low side as the amount of pixels on phone cameras is exploding.

Let's also assume the average text file size at 10kb. That's taken from here:
https://www.lexisnexis.com/applieddiscovery/lawlibrary/whitePapers/ADI_FS_PagesInAGigabyte.pdf 

1000MB/677963 files per GB = 0,0014750067 MB/file or 1.4 kB. And that is for 20 page text files.

In my experience the LTE and GSM modems have a maximum energy consumption about 3 to four times as high as the CPU. But my assumptions mean that they would have to use 3MB/1.4kB = 2143 times as much energy.

**Comment by Zillode** [comment]
:+1:

**Comment by generalmanager** [comment]
Great, thanks!
