### ISSUE TITLE
Tablet Screenshots

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing-android#422]
Google Play says I should add those, for 7 inch and 10 inch tablets.

Can someone with such a device take some screenshots? Ideally as a pull request, but anything works really ;)

Edit: Updated phone screenshots are also welcome!

**Comment by wweich** [comment]
The pull request would only consist of the 3 image files in  `/market/`, right?
I took some current shots from my Nexus 4: https://goo.gl/photos/XtSbQCLiwT8wqAVPA
Its a fresh install which will be removed, so the ID and such don't have to by obfuscated ;)
I will upload Screenshots from my old Nexus 7 once the battery is loaded enough to power on :)

If you want just the current 3 shots updated / in tablet form, I can make a PR once I have the tablet shots.

**Comment by wweich** [comment]
Here are the 7 inch tablet shots: https://goo.gl/photos/gXPzjE7nszpYZMd27
Again,  it's a fresh install which will be removed, so the ID and such don't have to by obfuscated ;)

**Comment by Nutomic** [comment]
Yeah exactly, with the tablet screenshots named something like `screenshot_tablet_7_inch_x`.

Also, there's a limit of 8 pictures per type, so I'd just leave the "loading" and "restart needed" pictures out. They don't make for good advertising anyway :D

**Comment by wweich** [comment]
My PR with updated phone and 7inch screenshots is in #423.
