### ISSUE TITLE
modals without contour

### ISSUE THREAD

**Issue by Eddy2909** [syncthing/syncthing-android#425]
![screenshot_2015-07-09-15-27-45](https://cloud.githubusercontent.com/assets/12877411/8596578/7f87c210-2650-11e5-9686-1e7eff21b627.png)

**Comment by Eddy2909** [comment]
using cyanogenmod 11

**Comment by Nutomic** [comment]
I suspect this is a problem with the support library, it works fine on Lollipop. 

Note to self, can be fixed with 
```
if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.KITKAT)
      dialog.getWindow.setBackgroundDrawable(new ColorDrawable(0))
```

**Comment by veniosg** [comment]
There's a comment in v11/styles.xml hinting that the resource qualifier was meant to be v21 instead.
