### ISSUE TITLE
arrange discovery addresses

### ISSUE THREAD

**Issue by Eddy2909** [syncthing/syncthing-android#426]
after the last update I got:
![screenshot_2015-07-09-15-29-05](https://cloud.githubusercontent.com/assets/12877411/8596678/060cc59c-2651-11e5-92e3-d25a03941d1c.png)

**Comment by Nutomic** [comment]
This is displayed correctly for me (on a new install). Did you change the value before? What does the web GUI show?

**Comment by Eddy2909** [comment]
I changed them weeks ago (while I had these crashes).. 
on the webgui, the addresses are mixed up too.. 

Am 9. Juli 2015 16:21:29 MESZ, schrieb Felix Ableitner <notifications@github.com>:

**Comment by Nutomic** [comment]
Do you know what you changed it to?

Anyway, it doesn't seem to be an Android problem then.

**Comment by Eddy2909** [comment]
well I just changed from the default addresses to my own disco server addresses..

**Comment by Nutomic** [comment]
Do you still have this problem? If so, can you send me your discovery server addresses to reproduce? (by mail if you want)

**Comment by Eddy2909** [comment]
working fine so far ;)

**Comment by Nutomic** [comment]
Ok closing this issue then, feel free to reopen.
