### ISSUE TITLE
Key exists; will not overwrite

### ISSUE THREAD

**Issue by mkaito** [syncthing/syncthing-android#429]
I ended up deleting application data, because I was in a hurry to get sync working, but here's a [logcat](http://pastie.org/private/qfkpcthhcjdewver0a). It came out of nowhere. Was working yesterday, and today it wouldn't boot. It seemed to be stuck in a loop, and the phone eventually told me the app was stuck, and asked me whether I'd like to kill it.

The logcat probably contains private-ish data, so if there's a better way to share it with you, please let me know.

Edit: `adb logcat -d | grep -i syncthing` should include everything relevant, yes?

**Comment by Zillode** [comment]
Not sure what the best approach is to fix this problem. I think we should empty the folder if we fail to create a config file.

**Comment by Nutomic** [comment]
I'd rather find the root cause of the problem than try to fix it by deleting data. Maybe we can add some more logging to find the cause? Or the Syncthing source may help?

Also, there's a lot of messages related to root, maybe it has to do with that in some way?

**Comment by mkaito** [comment]
Most of the root-related messages were eliminated by the grep, but it was just some ~10 more lines per instance, eventually resulting in root permission being granted.
