### ISSUE TITLE
Devices added by introducer do not show in application UI, do show in web UI

### ISSUE THREAD

**Issue by brycied00d** [syncthing/syncthing-android#432]
In my "network" of Syncthing nodes, I have one node I've designated as the introducer for all other nodes. Connecting a new device is as simple as adding to my introducer, and it's subsequently added automatically to all other nodes, and all other nodes are added to the new node. I expected the same thing to happen with syncthing-android, but the other nodes never appear under "Devices."

The new syncthing-android node is distributed to all other nodes and they show connections with the device. Opening the webui in syncthing-android, I see the other devices have been added. It's just the application "Devices" tab that is not updated. (Which in turn makes adding new folders to share with certain devices/nodes rather difficult.)

I have restarted syncthing-android several times. I have also restarted the device. No change.

Let me know if there's any other information or details I can provide. I am happy to test.

**Comment by brycied00d** [comment]
And no sooner than I opened this issue did they suddenly appear. Weird.

**Comment by Nutomic** [comment]
Be sure to check the logs if it happens again ;)

**Comment by brycied00d** [comment]
Thanks @Nutomic.
And for my future reference, consult https://github.com/syncthing/syncthing-android/blob/master/CONTRIBUTING.md for which logs those are.
