### ISSUE TITLE
Panic: cannot add empty folder id

### ISSUE THREAD

**Issue by RunningDroid** [syncthing/syncthing-android#433]
Sometimes if syncthing is running in the background and I open the app it will get "stuck" loading.

steps to reproduce:
I have no clue. I might have switched apps while syncthing was doing something, and on this device that means it gets pushed out of memory.

[(trimmed) logcat][1]

[1]: https://gist.github.com/RunningDroid/73a2f20ee67c8e642e67

**Comment by Nutomic** [comment]
"panic: cannot add empty folder id" Did you configure a folder with an empty id by any chance?

**Comment by RunningDroid** [comment]
No, and I checked to see if maybe i had just forgotten to add the id but the gui doesn't allow saving a folder with an empty id.

While trying to remember how I triggered this I stumbled on another bug that does the "gui never stops loading" thing, so I'm changing the title of this bug to something more descriptive

**Comment by Nutomic** [comment]
Can you check the config file in `/data/data/com.nutomic.syncthingandroid/files/`? (needs root)

@calmh @AudriusButkevicius Should this really be a panic at this point? How about setting a default id, so users can easily fix this problem? (without editing the config)

**Comment by RunningDroid** [comment]
Sorry, I wiped syncthing's data so i could try to reproduce this bug, but I forgot to make a backup first.

**Comment by Nutomic** [comment]
If you're still having this problem, please open a new issue at syncthing.
