### ISSUE TITLE
FolderObserver should not monitor MODIFY events

### ISSUE THREAD

**Issue by majedev** [syncthing/syncthing-android#435]
[FileObserver.MODIFY](https://github.com/syncthing/syncthing-android/blob/master/src%2Fmain%2Fjava%2Fcom%2Fnutomic%2Fsyncthingandroid%2Futil%2FFolderObserver.java#L58) event is emitted while the file is changing. This includes appending file data while copying/moving, which causes redundant calls to /rest/db/scan. I believe that FileObserver.CLOSE_WRITE suffices for detecting changes to trigger db rescan.

**Comment by Nutomic** [comment]
I think you're right. Do you know if `CLOSE_WRITE` is also called when someone forgets to call `close()`?

Do you wanna make a PR for this?

**Comment by majedev** [comment]
Sorry for taking long, got persuaded by other tasks. Here are my comments:

>Do you know if CLOSE_WRITE is also called when someone forgets to call close()?

Most probably not, unless the process that opened the file was closed somehow. Either way, this calls for a more robust file monitoring heuristics. For example, if a file was opened for writing but didn't receive MODIFY events for a long period of time, then it's safe to assume that the process failed to close the file.

>Do you wanna make a PR for this?

I would, but not very soon though. For the time being, I believe removing MODIFY event is better than leaving things as-is. The performance/battery impact is huge. Also, unclosed files are a rare occurrence that can be overcome by triggering Syncthing's auto-scanner (for now).

**Comment by Nutomic** [comment]
Okay that makes sense. We already use a rescan value of 3 days in case inotify misses something, so I don't think we need any extra monitoring.

And I just went ahead and fixed this. Thanks for bringing it up :)
