### ISSUE TITLE
Stuck at "Loading..." after adding new folder

### ISSUE THREAD

**Issue by onnokort** [syncthing/syncthing-android#437]
When adding a new folder to sync (selected folder exists on the phone, with about a hundred small files in it), syncthing asks to restart now or later.

In both scenarios (restart now, restart later and restarting manually), syncthing will be stuck with a 'Loading...'  message on screen after adding the folder and seems to be stuck. At least nothing happens for ~10min. 

After force-killing the app and restarting it, the new folder entry is missing.

Without adding the new folder, the message 'Loading...' does take quite a while to disappear, too. But it does eventually happen (<1min). (This might be another suggestion for enhancement: Add some indication that stuff is happening of some sort).

I have two other folder entries syncing just fine. I just can't add  new folder to sync anymore, apparently. Newest version from google play store.

Thanks for the otherwise great software and any input/help on this issue.

**Comment by Nutomic** [comment]
Can you post a logcat?

**Comment by PolyFloyd** [comment]
I had the same problem. It may be related to Syncthing performing some initialization tasks. With this in mind, I disabled UPnP as it showed taking a long time between log entries, and it resolved the issue for me.

**Comment by onnokort** [comment]
Ok, a little bit of update. I tried using the web GUI and that then worked eventually. However:

As I now have three folders, I tried to create a fourth one through the non-web GUI and this eventually did work, but it took *quite* a while. Samsung-S3 here.  So it looks a bit like a heisenbug.

I ran a logcat in parallel but honestly I don't really want to post the full log here - it is way too big and contains personal data. If you can tell me what to grep for or how to further constrain logcat output to your liking, I might be able to provide that. 

FWIW, there were a lot of messages of this form:

W/GetTask (22381): Retrying GetTask Rest API call (5/10)
W/GetTask (22381): Failed to call Rest API at https://127.0.0.1:8384/rest/db/status?folder=XYZ?folder=XYZ?folder=XYZ ...
W/GetTask (22381): org.apache.http.conn.HttpHostConnectException: Connection to https://127.0.0.1:8384 refused
W/GetTask (22381): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:183)
W/GetTask (22381): 	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:164)
W/GetTask (22381): 	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:119)
W/GetTask (22381): 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:360)
W/GetTask (22381): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:670)
W/GetTask (22381): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
W/GetTask (22381): 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
W/GetTask (22381): 	at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:73)
W/GetTask (22381): 	at com.nutomic.syncthingandroid.syncthing.GetTask.doInBackground(GetTask.java:28)
W/GetTask (22381): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
W/GetTask (22381): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
W/GetTask (22381): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
W/GetTask (22381): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
W/GetTask (22381): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
W/GetTask (22381): 	at java.lang.Thread.run(Thread.java:841)
W/GetTask (22381): Caused by: java.net.ConnectException: failed to connect to /127.0.0.1 (port 8384): connect failed: ECONNREFUSED (Connection refused)
W/GetTask (22381): 	at libcore.io.IoBridge.connect(IoBridge.java:114)
W/GetTask (22381): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
W/GetTask (22381): 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
W/GetTask (22381): 	at java.net.Socket.connect(Socket.java:842)
W/GetTask (22381): 	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:119)
W/GetTask (22381): 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:144)
W/GetTask (22381): 	... 14 more
W/GetTask (22381): Caused by: libcore.io.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
W/GetTask (22381): 	at libcore.io.Posix.connect(Native Method)
W/GetTask (22381): 	at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
W/GetTask (22381): 	at libcore.io.IoBridge.connectErrno(IoBridge.java:127)
W/GetTask (22381): 	at libcore.io.IoBridge.connect(IoBridge.java:112)
W/GetTask (22381): 	... 19 more


note the repeated ?folder= argument.

**Comment by Zillode** [comment]
It seems Syncthing is not running at that point in time

**Comment by onnokort** [comment]
Yes, it was the restart phase after I added the folder. I was just thinking the same argument to the web interface multiple times looked funny, that's all. I can't really reproduce this bug anymore, so I guess I should close it.
