### ISSUE TITLE
colorAccent does not have enough contrast

### ISSUE THREAD

**Issue by veniosg** [syncthing/syncthing-android#438]
I've noticed that the accent colour is a green tone and the primary is a blue, both similar hues. This is in contrast to what the material design guidelines outline: ["Don’t use the accent color over a background color if there isn’t enough contrast."](http://www.google.com/design/spec/style/color.html#color-color-palette). 

A more vivid and bold colour choice for colorAccent would make more sense in this case. How would you feel about orange, for example FF9100 (A400), it complements the primary blue nicely and makes the actions pop out without being too bright or distracting.

**Comment by Zillode** [comment]
Thanks!
