### ISSUE TITLE
Double Dialog on non-Lollipop devices

### ISSUE THREAD

**Issue by thesuperdavis** [syncthing/syncthing-android#441]
To reproduce, open a dialog on a device with Android 4.4 or less, and it shows the dialog in front of another (screenshot). On a device with Android 5, threre is one dialog.

![screenshot](https://cloud.githubusercontent.com/assets/12485647/9061279/0c4f75c0-3abb-11e5-9f6d-f8c7c9ae54a3.png)

versions:
Syncthing: v0.11.13
Syncthing-Android: 0.6.5

**Comment by veniosg** [comment]
Pretty sure this is a duplicate of #425, which is fixed in 90b5d2ff9abfee0d000ef0156858c3978ad861c8.

**Comment by Zillode** [comment]
Indeed
