### ISSUE TITLE
Lag after unlocking screen

### ISSUE THREAD

**Issue by lordloh** [syncthing/syncthing-android#444]
Each time I unlock the screen, there is a circular progress indicator for a few seconds - this ruins my experience. Can the app display the last known state instead of refreshing it after every unlock and blocking the UI?

**Comment by Nutomic** [comment]
Do you have "sync only on wifi" enabled? Your device might disconnect from your wifi when the screen is off, causing syncthing to shut down.

**Comment by lordloh** [comment]
No, I have "Sync only on WiFi" disabled. Sync thing seems to keep on as
expected.

**Comment by Nutomic** [comment]
Then I don't see why this would happen (I can't reproduce it). Can you post a log please?

**Comment by lordloh** [comment]
How do I get the log. And surprisingly, I am not able to recreate it again :-/

**Comment by Nutomic** [comment]
Either in the settings, or using a logcat app (or logcat from a pc).

**Comment by lordloh** [comment]
i'll reopen this if I can reproduce it in future :-( (hopefully not). Thank you.
