### ISSUE TITLE
Stuck loading: leveldb/table: corruption on table footer

### ISSUE THREAD

**Issue by devanubis** [syncthing/syncthing-android#445]
Hia, I've had this issue a couple of times on my phone now. The first time I reinstalled the app,but it's occurred again.

Syncthing seems to be having trouble accessing its leveldb. Once this has happened once I can't get the app to launch correctly, even after force-killing syncthing or a cold reboot.

logcat:
```
08-16 21:38:34.913 I/SyncthingNativeCode(4010): [RWPVW] 20:38:34 INFO: Database block cache capacity 14597 KiB
08-16 21:38:34.915 I/SyncthingNativeCode(4010): [RWPVW] 20:38:34 INFO: Database block cache capacity 14597 KiB
08-16 21:38:34.920 I/SyncthingNativeCode(4010): [RWPVW] 20:38:34 FATAL: Cannot open database: leveldb/table: corruption on table-footer (pos=1517404): bad magic number [file=000308.ldb] - Is another copy of Syncthing already running?
08-16 21:38:34.927 E/SyncthingNativeCode(4010): Syncthing binary crashed with error code 1
08-16 21:38:43.971 W/PackageManager(1013): Failure retrieving resources for com.nutomic.syncthingandroid: Resource ID #0x0
08-16 21:38:45.003 W/PackageManager(1013): Failure retrieving resources for com.nutomic.syncthingandroid: Resource ID #0x0
```

**Comment by AudriusButkevicius** [comment]
The index is corrupt, which implies hardware issues/bit rot.

**Comment by devanubis** [comment]
That's not encouraging. My HTC M8 is only 10 months old...

I've just done another uninstall/reinstall and I'll see if it recurrs again...

I've not had any issues with any other apps (many of which use DBs but probably nothing like syncthing in terms of data integrity checking.
