### ISSUE TITLE
Change minimum Android version to Jelly Bean

### ISSUE THREAD

**Issue by veniosg** [syncthing/syncthing-android#448]
Not sure where else to ask. The app would be losing a potential 9% of global Play store users but effectively I'm inclined to believe the number will be much lower. 

Background: I need this for a number picker, don't feel like writing my own or bringing in a library.
https://developer.android.com/about/dashboards/index.html

**Comment by Nutomic** [comment]
Can you point to the concrete class you want to use? I only found [NumberPicker](http://developer.android.com/reference/android/widget/NumberPicker.html), which is 11+.

Generally, I would be okay with upping the API version if needed, but I would prefer 4.0 (that would affect only 1,5% of Play Store users). Unfortunately, there are no version stats for F-Droid (that I know of).
![numbers](https://cloud.githubusercontent.com/assets/1044450/9424998/f614865c-4900-11e5-984b-8f23d6e67303.png)

**Comment by veniosg** [comment]
That's the one, NumberPicker. It is be fine increasing to to 4.0.3 for my purposes, just though it would make sense to jump straight to Jellybean considering the numbers.

I have no idea about F-droid as well but my guess would be they're even more favourable considering the audience of that store.

**Comment by Nutomic** [comment]
As I said, I would be fine with this. But @Zillode is rather opposed to this, so I'll wait for his comment.

Anyway, we'll need to do a new minor (not patch) release for this, and preferably some kind of warning to users.

**Comment by veniosg** [comment]
Sounds good, if my PR is to make it through it'd make sense for it to be a minor release. 
Let's wait for @Zillode.

**Comment by Zillode** [comment]
I'd at least try to support the lowest sdk possible for your PR (11) ;)
But I'm ok with bumping it. Maybe we should actually have an app that only offers the webgui for old devices

**Comment by veniosg** [comment]
Awesome, I'll bump to 11 then :) 
The PR may take some time as I'll be on vacation the next weeks; it's certainly coming though.
The WebUI fallback sounds like a nice idea btw, it's even possible for that option to be in the same app if there's some startup decider activity.

**Comment by Nutomic** [comment]
Web gui fallback in the same app is actually a good idea. However, that means we can't actually increase the min api version. Also, it will most likely confuse lint (but I guess we could make reasonable ignores).

**Comment by veniosg** [comment]
Yeah, not increasing was the idea, it means users can hold on to the same app and it won't confuse new ones. This can still happen in the future, after bumping to 11, play store handles these updates afaik, it'll just ignore in-between versions for incompatible devices. 
We'll still get the benefits of being able to use new APIs as these parts won't be exposed to older devices.

**Comment by Nutomic** [comment]
The code change would actually be simple (just make a FirstStartActivity that either launches MainActivity WebGuiActivity depending on API version). 

The problem is that lint would mark every use of APIs above 8 as error, and we'd have to add `@TargetApi(11)` to every single file.

**Comment by veniosg** [comment]
I'm pretty sure only files (or methods rather) containing new APIs would have to be annotated for lint to keep happy.

**Comment by Zillode** [comment]
I meant providing it as a separate app;)

**Comment by veniosg** [comment]
I know, I counterproposed doing it in the same app so that we don't confuse users :)
