### ISSUE TITLE
Update to latest Syncthing release

### ISSUE THREAD

**Issue by sbrunk** [syncthing/syncthing-android#450]
Upstream has now things like [Optionally ignore remote deletes](https://github.com/syncthing/syncthing/issues/1254) which is particularly useful for removing photos/videos from a phone after having them synced.

It would be great to have that feature in the Android version.

**Comment by Nutomic** [comment]
You're right, I'll make a new release today.

@Zillode Do you think we should enable ignoreDelete for the default camera folder?

**Comment by Nutomic** [comment]
Done ;)

**Comment by sbrunk** [comment]
Awesome! Thanks a lot. :smile:
