### ISSUE TITLE
Long press on fields like "Device ID", "Name" in add device, "Folder ID" does not bring the Android copy/paste/cut menu

### ISSUE THREAD

**Issue by licaon-kter** [syncthing/syncthing-android#454]
Steps to reproduce:

1. Try to add a folder/add a device
2. Click on "Device ID" or "Name" or "Folder ID"
3. Long press to paste an ID, or a special name or something

The default Android menu to copy/paste/cut menu should appear.
Actually nothing happens.

not working: Sony Xperia Sola with CM 12.1 ( 2015-08-22 ) 0.6.6 via F-Droid
working ok: Nexus 7 (2012) with CM 12.1 ( 2015-08-25 ) 0.6.6 via PlayStore

**Comment by Nutomic** [comment]
I doubt this has anything to do with syncthing, as it's only broken on your one device (also works fine for me). Have you checked the logs, and other apps on that device?

**Comment by licaon-kter** [comment]
Looks like it's working today.
