### ISSUE TITLE
[Feature Request] Periodic Sync

### ISSUE THREAD

**Issue by tinloaf** [syncthing/syncthing-android#460]
Hi,

I think it would be great if Syncthing on Android would not just have the two "start me manually" and "always run" modes, but could also be configured to start every couple of hours, look for changes, sync if there are any, and then shut down again. This would provide a nice trade-off between data/battery consumption and "oh damn, my files are out of sync since I forgot to start Syncthing again".

Obviously, some sane assumptions must be made: If a device cannot be connected to within timeframe X, assume it to have no changes and shut down, etc pp

**Comment by Nutomic** [comment]
This can be done with broadcast intents now, see the [instructions here](https://github.com/syncthing/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents). I'm closing this as out of scope.
