### ISSUE TITLE
Syncthing v0.12

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing-android#462]
- [x] [New announce servers](https://forum.syncthing.net/t/syncthing-v0-12-beryllium-bedbug-release-notes-v0-12-0-beta1/5480/9?u=nutomic)
- [ ] There's a problem with certificates, need to look into that. Can you do that @Zillode?

My code is currently on the syncthing-v0.12 branch.

**Comment by Zillode** [comment]
wfm

**Comment by Nutomic** [comment]
Right, not sure what was going on there.
