### ISSUE TITLE
Slovak localization of playstore description is a mess

### ISSUE THREAD

**Issue by kozec** [syncthing/syncthing-android#463]
Hi,

this is probably more comical than actual problem, but Slovak version of syncthing-android's description in Play store reads:

`Nahradiť properitálne služby s niečim. Otvorená, dôverihodná a decentralizovaná.`

This roughly translates back to

`Let's(?) replace proprietary services with something. She is open, trustable and decentralized.`

Dunno who thought using google translator for this was good idea, but it certainly weren't :)

**Comment by chucic** [comment]
Same for czech. Could this line or maybe whole description of an app be added to Transifex?

**Comment by Nutomic** [comment]
Are the translations on Transifex good? If so, I can manually copy them in.

Related to #408.

**Comment by kozec** [comment]
> Are the translations on Transifex good? If so, I can manually copy them in.

Czech looks good, Slovak is untranslated.

**Comment by Nutomic** [comment]
Okay added Czech localization, notify me when you add a slovak one ;)
