### ISSUE TITLE
inotify doesn't always detect changes

### ISSUE THREAD

**Issue by teresaejunior** [syncthing/syncthing-android#465]
There was a small discussion about this problem on https://forum.syncthing.net/t/does-not-always-sync/5857/15

Syncing between my laptop and Android mobile don't always work. It may show on both sides as "Up to date", while the number and sizes of files on both devices may differ. Opening the web interface and running a "Rescan" manually works. I don't know if the fact that my folder is in an external CD card is related to this problem.

syncthing-android version: 0.6.6
Device name and Android version: LG E425f, Android 4.1.2
versions of involved Syncthing nodes: 0.11.26 on Debian 7
logcat: https://gist.github.com/teresaejunior/059e7b8e476dec2173d3

**Comment by Nutomic** [comment]
So this happens when you update an existing file, correct?

Unfortunately, there's no relevant info in your log. Can you run `adb logcat -s PostTask:v`? There should be a call to `https://127.0.0.1:8384/rest/db/scan` immediately after your change.

Also, I just noticed a huge fuckup in the way inotify events are sent to Syncthing (we don't set the URL parameters, which probably means Syncthing rescans everything). But I'm pretty sure that has nothing to do with your problem.

**Comment by teresaejunior** [comment]
> So this happens when you update an existing file, correct?

Not necessarily, I still couldn't figure out a pattern.

> Unfortunately, there's no relevant info in your log. Can you run adb logcat -s PostTask:v? There should be a call to https://127.0.0.1:8384/rest/db/scan immediately after your change.

Should I run this right now, or should I try to reproduce the error and run it immediately after that?

Thank you for your attention!

**Comment by Nutomic** [comment]
You should confirm that this is logged when the error occurs. That way we can narrow down the issue. And ideally, you'd figure out a way to reproduce this reliably, so it's easier to fix.

**Comment by teresaejunior** [comment]
OK, I'll try to reproduce the problem and come back with adb's output.

**Comment by teresaejunior** [comment]
Hello! This is what I did today:

1. Opened a terminal emulator in Android and run `adb logcat -s PostTask:v 2>&1 | tee logcat`
2. Copied around 60 small text files to the shared folder in Android: they synced back to the laptop.
3. Copied 10 bigger APK files to the shared folder in Android: they synced back to the laptop.
4. Run the script as I usually do in the laptop. It generated around 400 files: they synced back to Android.
5. Removed all the files in the shared folder in Android. Now the problem appeared: it shows both sides as synced as if I had not deleted any files at all.
6. Went back to see the log, the only output is `- waiting for device -`.

I have not triggered a "Rescan" in the web interface yet, just left Syncthing open as it is.

**Comment by teresaejunior** [comment]
Now, the test from yesterday was really pathetic. I think I was half asleep, and when I *Removed all the files in the shared folder in Android*, this included .stfolder... I'm sorry for this! But the other times this was not the issue.

One thing I have noticed in the log available from within the app, though:
> W/SyncthingNativeCode(31503): sh: <stdin>[1]: grep: not found
> W/SyncthingNativeCode(31503): usage: ionice <pid> [none|rt|be|idle] [prio]

I didn't know syncthing-android depended on Busybox, could the failure to set the ionice have any effect on this?

**Comment by AudriusButkevicius** [comment]
No.

**Comment by joelostblom** [comment]
I just started using syncthing and I am having a similar issue. When I edit files on my computer, they are promptly synced to my phone (interval set to 30s). However, when I created a new file on my phone, it was not synced to my computer.

I waited for a few minutes after creating the file, exported the log-file and then hit rescan in the web interface on the phone. The file now synced and I exported the log for that as well. I attach both log files in case they can be helpful.

As a workaround, would it be very battery intensive to set the sync interval to 30 s on the phone as well?

[syncthing_android_after_rescan. log.txt](https://github.com/syncthing/syncthing-android/files/32005/syncthing_android_after_rescan.log.txt)
[syncthing_android.log.txt](https://github.com/syncthing/syncthing-android/files/32006/syncthing_android.log.txt)

**Comment by licaon-kter** [comment]
In the WebUI on the phone you can set (per folder) scan from 295200 to something lower.

**Comment by joelostblom** [comment]
Yeah I saw that and understood it as the interval is set that high since inotify should normally handle syncing on Android. I am considering lowering the interval time as a workaround, but since it is not the default behavior, I am wondering if it would have a big effect on battery life.

**Comment by Nutomic** [comment]
There's nothing relevant in the logs I can see. Can you figure out a way to reproduce this problem?

I have no idea how much you battery usage would increase, you'll just have to test that.

**Comment by alanthehat** [comment]
There are 2 bugs listed on the manpage for inotifywait(1) on linux.die.net which may be relevant

**Comment by teresaejunior** [comment]
Does syncthing-android run inotifywait from the command-line? I thought it accessed the inotify API directly! If that is the case, could it be that an OOM is killing inotifywait?

**Comment by Nutomic** [comment]
We use the [Android API](http://developer.android.com/reference/android/os/FileObserver.html). And references are kept as long as the service is alive.

[The code is here](https://github.com/syncthing/syncthing-android/blob/master/src/main/java/com/nutomic/syncthingandroid/util/FolderObserver.java)

**Comment by alanthehat** [comment]
It struck me that the manpage was probably referencing an underlying problem...

**Comment by teresaejunior** [comment]
I have not seen this problem anymore in more recent versions of syncthing-android after all this time. 

Syncthing seems to have improved a lot lately, thanks for your work!
