### ISSUE TITLE
Enabling HTTPS for Web GUI locks user out of it for good

### ISSUE THREAD

**Issue by Aeyoun** [syncthing/syncthing-android#475]
1. Open Web GUI: Settings and check Use HTTPS
2. Restart and open Web GUI

(It is super easy to run into this issue because of issue #474.)

It should be possible to use the Web GUI over HTTPS.

**Comment by Nutomic** [comment]
HTTPS should be enabled by default, and works fine for me. What app version and Android version are you running? Is there anything relevant in the logs?

**Comment by Aeyoun** [comment]
This was actually a duplicate of #440.
