### ISSUE TITLE
syncthing 0.6.6/Android and 0.12.0 or 0.12.1/Ubuntu 64bits don't talk to each other

### ISSUE THREAD

**Issue by rdarioc** [syncthing/syncthing-android#476]
Is it a known bug?

Android doesn't discover the dynamic server on Ubuntu and vice versa.

Android 4.4.2, Ubuntu (Lubuntu 14.04 64bit)

If I set the address of the android instead of dynamic with its own address ... Ubuntu server tries to connect but fails with something like "File limit exceeded" ... if I try to set the address of Ubuntu server on Android, it doesn't get it and keeps reporting "dynamic".

I may say that a while ago, with different releases of both the installation, it worked fine, so the issue has nothing to do with my local configuration, neither of my phone nor of my server.

**Comment by AudriusButkevicius** [comment]
Read the release notes of syncthing. v11 is not compatible with v12, and v12 android is not released yet. There is a beta on the forums which you can install.

**Comment by rdarioc** [comment]
Thank you for your immediate support. 

Do you know where I can download the 0.11 for Linux 64 bit? 

---
R.D. Contarino


On November 6, 2015, 19:30, Audrius Butkevicius wrote:
Read the release notes of syncthing. v11 is not compatible with v12, and v12 android is not released yet. There is a beta on the forums which you can install.

**Comment by AudriusButkevicius** [comment]
On the release page on syncthing github

**Comment by rdarioc** [comment]
You are great! Thank you so much. Great work by the way. 

---
R.D. Contarino


On November 6, 2015, 19:55, Audrius Butkevicius wrote:
On the release page on syncthing github
