### ISSUE TITLE
Ondemand download

### ISSUE THREAD

**Issue by lordloh** [syncthing/syncthing-android#477]
I would like to sync all my folders with the phone, but do not have enough storage space.

It would be great to have meta data sync, but not the files. So, I should be able to see the list of files, but download them on demand - much the way Dropbox app works.

**Comment by AudriusButkevicius** [comment]
Have you checked existing issues? I feel this is a duplicate.

**Comment by lordloh** [comment]
I tried a few searches and nothing turned up. I hope more people than me want this :-)

**Comment by Lumax-Rus** [comment]
https://github.com/syncthing/syncthing-android/issues/81

**Comment by lordloh** [comment]
No. #81 is not the right use case. The use case in my context would be - 

"I have several series on my PC what I watch on my phone when commuting. I have synced my TV series folder on my PC and I only have several episodes on my phone downloaded (cached), when I finish an episode, I download new ones, and the old ones are removed from the phone cache according to some caching scheme (leas recently accessed?). By the time I finis a series I have the master copy on the PC and the last accessed episodes on the phone, which I may clear by clearing the cache. If I like an episode, I pin it to keep it on the phone (not counted towards the cache size limit)."

**Comment by Nutomic** [comment]
This is already in #205. I adjusted the title so it's easier to find :)
