### ISSUE TITLE
Upload Betas to Play Store in beta channel

### ISSUE THREAD

**Issue by ogarcia** [syncthing/syncthing-android#479]
The Google Play Store have a very good support to maintain a Beta and an Alpha channel.

I think that this is better and most secure than provide APK directly.

**Comment by iexos** [comment]
Having it on f-droid would be nice too.

**Comment by dper** [comment]
It's been a long time with F-Droid's version essentially useless. This is definitely driving off users. Breaking back compatibility can be necessary, but does it really take this long to get everything going again? :-(

**Comment by licaon-kter** [comment]
F-Droid is up to date now at 0.6.6 ( ignoring todays release that is).
Hopefully you can provide Github builds too for those without PlayStore, if F-Droid stalls at least..

**Comment by Nutomic** [comment]
@Zillode It seems F-Droid didn't pick up the beta releases, can you figure out what the problem is there?

Google Play betas are a bit annoying, because we'd need a Google Plus group for access, and we'd have to adjust Jenkins to push there.

**Comment by ogarcia** [comment]
@Nutomic Not necessarily. Now you can do the Open Beta option that provides a simple link to access to beta. :wink:

**Comment by Nutomic** [comment]
Ah I didn't know about that, thanks. I'll try to remember this for the next time we do a beta :)

**Comment by imraro** [comment]
FYI:  v0.7 can't be built on F-Droid:
```
INFO: Creating log directory
INFO: Creating temporary directory
INFO: Creating output directory
INFO: Building version 0.7.0 (75) of com.nutomic.syncthingandroid
INFO: Getting source for revision 0.7.0
INFO: Initialising submodules
INFO: Creating local.properties file at build/com.nutomic.syncthingandroid/local.properties
INFO: Cleaned build.gradle of keysigning configs at build/com.nutomic.syncthingandroid/build.gradle
INFO: Cleaning Gradle project...
INFO: Scanning source for common problems...
ERROR: Found unknown maven repo 'https://raw.github.com/kolavar/android-support-v4-preferencefragment/master/maven-repository/' at build.gradle
WARNING: Found possible binary at market/screenshot_phone_1.png
WARNING: Found possible binary at market/screenshot_phone_3.png
WARNING: Found possible binary at market/screenshot_phone_2.png
Could not build app com.nutomic.syncthingandroid due to BuildException: Can't build due to 1 errors while scanning
```

**Comment by wweich** [comment]
Thats why #484 remove unneeded stuff, so that 0.7.1 can now build on f-droid.

**Comment by licaon-kter** [comment]
Any timeframe?

**Comment by Nutomic** [comment]
0.7.4 is finally available on F-Droid now :)

**Comment by licaon-kter** [comment]
Thanks

**Comment by Nutomic** [comment]
For reference, they are [here](https://play.google.com/apps/testing/com.nutomic.syncthingandroid).
