### ISSUE TITLE
99% stuck

### ISSUE THREAD

**Issue by axet** [syncthing/syncthing-android#480]
It just stuck syncing on 2998 of 3007 files. Idle (99%)

```
--------- beginning of main
11-10 13:12:23.100  5541  5561 I SyncthingNativeCode: [32LGZ] 10:12:23 INFO: Folder "private" isn't making progress. Pausing puller for 1m0s.
11-10 13:13:25.768  5541  5561 I SyncthingNativeCode: [32LGZ] 10:13:25 INFO: Folder "private" isn't making progress. Pausing puller for 1m0s.
11-10 13:14:28.286  5541  5561 I SyncthingNativeCode: [32LGZ] 10:14:28 INFO: Folder "private" isn't making progress. Pausing puller for 1m0s.
11-10 13:15:30.852  5541  5561 I SyncthingNativeCode: [32LGZ] 10:15:30 INFO: Folder "private" isn't making progress. Pausing puller for 1m0s.
11-10 13:16:33.421  5541  5561 I SyncthingNativeCode: [32LGZ] 10:16:33 INFO: Folder "private" isn't making progress. Pausing puller for 1m0s.
11-10 13:17:39.014  5541  5561 I SyncthingNativeCode: [32LGZ] 10:17:39 INFO: Folder "private" isn't making progress. Pausing puller for 1m0s.
```

http://pastebin.com/ECCgZziU

![screenshot_20151110-131946](https://cloud.githubusercontent.com/assets/298672/11059944/064b3e62-87ae-11e5-9204-7261ff0c4358.png)

**Comment by licaon-kter** [comment]
What Android client version?

**Comment by axet** [comment]
Recent 0.7.

Restart app does not help.

Syncthing laptop app shows 100% synching, do not shows done.

**Comment by licaon-kter** [comment]
Laptop app at version 0.12.x right?

**Comment by axet** [comment]
Sure. 0.12.2

**Comment by capi** [comment]
Could it be that the remaining 9 files match an ignore pattern on either side?

**Comment by axet** [comment]
<img width="627" alt="screen shot 2015-11-10 at 15 34 23" src="https://cloud.githubusercontent.com/assets/298672/11062515/92fc2bb6-87c0-11e5-83c3-e4cbdf5c48a9.png">

screenshot of desktop app

**Comment by capi** [comment]
Check the pending files on both sides, to get some idea why they are not being synced. You can do so in the Web-UI on the mobile application.

**Comment by axet** [comment]
It seems like it was a conflict files.

I did not sync my mobile devices for a while, because here were no syncthing for android for 0.12 release.

After removing conflict files and readding them, issue was fixed. They are were in "Out of sync items" and  seems like not causing any issues, but sync is failed.
