### ISSUE TITLE
Android 6.0 - Ask for Storage Permission

### ISSUE THREAD

**Issue by fti7** [syncthing/syncthing-android#483]
Hi,
had some issues with a brand new Android 6.0 Device and the newest Syncthing Android (0.12.1)

The /storage/emulated/0 Folder was just empty.
After granting the App the Storage Permission manually (App -> Permissions) its now able to see the real content (not sandboxed)

I think you should ask for the Storage Permission on Startup (Android 6.0 changed its Permission Model)
On upgraded Smartphones that wouldnt happen because the old legacy permission are passed over to the new Model as an Default

Best Regards,
Frank

**Comment by Nutomic** [comment]
I stupidly changed the target API without testing it. I'll downgrade it until we implement the permissions handling properly
