### ISSUE TITLE
Side menu is not usable without touch/pointer input

### ISSUE THREAD

**Issue by wweich** [syncthing/syncthing-android#486]
I just tried Syncthing Android on Android TV (to make new screen shots).
Unfortunately when I open the side menu, it gets "stuck". Pressing the arrow buttons does nothing (and no navigation sound either) as does pressing OK.
The only buttons that works are home and back (which closes Syncthing Android).

**Comment by Nutomic** [comment]
I don't have an Android TV, and no idea what would cause this. @veniosg Do you happen to know anything here? 

I do agree that the back button should close the drawer.

**Comment by wweich** [comment]
When connecting a keyboard to a tablet (and probably phone too) you can reproduce this by trying to use only the keyboard. As soon as you open the side menu, the arrow keys and enter will do nothing and the only thing you can do is hit ESC to close Syncthing.

I connected a keyboard with touchpad to my Android TV to get a mouse cursor. With that I could then use the side menu.

So it's nothing specific to Android TV, just the lack of pointer input.

**Comment by Nutomic** [comment]
I also don't have a keyboard. Would it be enough to have the back button close the side menu?

**Comment by wweich** [comment]
With that change, the menu could be opened and closed without mouse or touchpad.
One would still need a mouse or touchpad to get into the settings.
I don't know why the Arrow keys don't work for the side menu.

**Comment by veniosg** [comment]
Maybe they do work but the visual indication is not there. Have you tried
pressing down a couple of times and the enter/ok?

**Comment by wweich** [comment]
Tried that. There is neither a visual indication nor an audible one.
Navigating through the rest of the App highlights the element which is currently in focus and I get the navigation sound.

**Comment by Nutomic** [comment]
But does something happen when you "click" while the drawer is open?

**Comment by wweich** [comment]
No. I tried pressing every arrow key a few dozen times with OK in between. Nothing happens.
Only Back and Home have an effect.

**Comment by Nutomic** [comment]
Hm, I really know nothing about Android TV, so I have no idea how to fix this.

**Comment by veniosg** [comment]
I'll have a quick look tomorrow on a genymotion, I doubt this is specific
to Android TV.

**Comment by veniosg** [comment]
Confirmed this happens on normal devices with a keyboard/trackball whatever. The issue seems to be that the views in the list don't and can't get focus when the drawer is open. Haven't looked for a solution.

**Comment by holyoaked** [comment]
Until this is fixed,I think SyncThing should be removed from the Android TV Play Store. It's misleading to suggest it's supported when you can't actually do anything with the app.

**Comment by xEtherealx** [comment]
why is this closed?  Still unusable...

**Comment by Nutomic** [comment]
@xEtherealx What kind of device are you using? And what exactly is unusable? I tested on an Android TV emulator, and everything worked fine after my changes.

**Comment by xEtherealx** [comment]
SHIELD TV, and I cannot use syncthing without a BT keyboard/mouse.  If a pointer showed up when using the right joystick this would alleviate the problem.

**Comment by wweich** [comment]
I just tested it on my Shield TV with the TV Remote (CEC) and it works without a problem.

**Comment by xEtherealx** [comment]
I don't have the remote, just the game controller -- would you mind checking with that device?

**Comment by wweich** [comment]
I don't have the Shield remote either. I tested the controller and it works.

**Comment by xEtherealx** [comment]
Did you test via the play store version or a dev release?  I'll try again
tonight to confirm.

**Comment by Nutomic** [comment]
You should be able to select the hamburger icon with your arrow buttons, and then just click to open the drawer. Iirc that's how I did it in the emulator.

**Comment by xEtherealx** [comment]
Just tested; I cannot select a directory when adding a folder, the
controller skips the selection area altogether.  My web UI is failing to
load through the hamburger bar, but when it did I couldn't navigate the
settings with the controller.  I'll try reinstalling later to get more
specifics, but my idea now is to enable the web interface and use it to
configure...
