### ISSUE TITLE
One folder reporting "Out of Sync Items...", not sure how to find out what's wrong.

### ISSUE THREAD

**Issue by chris-thorn** [syncthing/syncthing-android#487]
I've done a couple of completely fresh installs of Syncthing for Android using the Play Store version, but the problem still reappears. My device is an LG G4 running Android 5.1.

One of my folders is reporting the following:

**Global State** 3 items, ~ 11.4 MiB
**Local State** 3 items, ~ 11.4 MiB
**Out of Sync Items** 2 items, ~ 10.7 MiB
**Failed Items** <spinner>
**Ignore Permissions** Yes
**Shared With** node1, node2, node3, ...
**Last File Received** file1

After the fresh install it worked just fine, and synced three three items in that folder no problem. But after updating two of these files on another machine, it's now reporting that these two items are out of sync.

Is there any way I can view a log on my device or investigate what's causing the issue?

Thanks,

Chris

**Comment by wweich** [comment]
I think this is fixed by syncthing/syncthing#2462.

**Comment by chris-thorn** [comment]
Thanks for the heads-up.

Incidentally, the folder that was having trouble syncing is now synced, and another folder is reporting that a file is out of sync. The file being reported as out of sync on my phone is a simple *.txt file that has just been open on my PC in Notepad++.

As a quick test, I added some characters to the *.txt file then saved it on the PC. It synced almost straight away to my phone. I saw the folder on my phone briefly report "syncing 99%", and I saw the "Out of Sync Items"  file size change accordingly, but that one item still remains "out of sync".

**Comment by chris-thorn** [comment]
Well, I've just updated to 0.7.2 and all my folders immediately started syncing and they're all showing green now :) Changes to files made on my PC are reflected on my Android device straight away, and there don't seem to be any errors.

Many thanks to @Nutomic for fixing it so quickly! Great job :)

**Comment by Nutomic** [comment]
It was actually @Zillode who suggested pulling this fix in ;)

**Comment by chris-thorn** [comment]
My apologies - thank you @Zillode!

**Comment by Zillode** [comment]
:dancers:
