### ISSUE TITLE
Disabling both discovery methods prevents startup

### ISSUE THREAD

**Issue by brianhlin** [syncthing/syncthing-android#488]
Syncthing gets stuck on the 'Loading...' screen indefinitely. I was able to reproduce this on a fresh install:

1. Disable Global Discovery 
2. Disable Local Discovery
3. Restart Syncthing

LG G2, Android 5.1.1
Syncthing Android version: 0.7.0
Node Syncthing version: n/a

I noticed this exception in my logcat:

> V/GetTask (27844): API call result: {"alloc":11275960,"cpuPercent":23.676138370492076,"goroutines":39,"myID":"PGK3VGR-3JC72PL-XUSE6FM-5X6SUDF-KLJJLAY-JXLGJGF-F2UKCKE-H5UYDQC","pathSeparator":"/","startTime":"2015-11-12T18:43:55.423463807Z","sys":17570940,"tilde":"/storage/emulated/0","uptime":43}
> W/RestApi (27844): Failed to read system info
> W/RestApi (27844): org.json.JSONException: No value for discoveryMethods
> W/RestApi (27844):      at org.json.JSONObject.get(JSONObject.java:389)
> W/RestApi (27844):      at org.json.JSONObject.getInt(JSONObject.java:478)
> W/RestApi (27844):      at com.nutomic.syncthingandroid.syncthing.RestApi$6.onPostExecute(RestApi.java:443)
> W/RestApi (27844):      at com.nutomic.syncthingandroid.syncthing.RestApi$6.onPostExecute(RestApi.java:432)
> W/RestApi (27844):      at android.os.AsyncTask.finish(AsyncTask.java:636)
> W/RestApi (27844):      at android.os.AsyncTask.access$500(AsyncTask.java:177)
> W/RestApi (27844):      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
> W/RestApi (27844):      at android.os.Handler.dispatchMessage(Handler.java:102)
> W/RestApi (27844):      at android.os.Looper.loop(Looper.java:135)
> W/RestApi (27844):      at android.app.ActivityThread.main(ActivityThread.java:5294)
> W/RestApi (27844):      at java.lang.reflect.Method.invoke(Native Method)
> W/RestApi (27844):      at java.lang.reflect.Method.invoke(Method.java:372)
> W/RestApi (27844):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
> W/RestApi (27844):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

config.xml: http://pastebin.com/b3GEWjK7

Let me know if you need anything else.

**Comment by uok** [comment]
thanks for debugging, I also have both discoveries off and same error (see #481)

**Comment by zcalusic** [comment]
Same here, loading... forever, never starts :(

**Comment by licaon-kter** [comment]
@zcalusic are you sure it's not like this: https://github.com/syncthing/syncthing-android/issues/481#issuecomment-155801901 ?

**Comment by zcalusic** [comment]
Pretty. I haven't rooted a device and never saw the error message from the other issue. OTOH, I do have both discovery options disabled. I also tried to connect via web UI but it's not available either. :(

**Comment by zcalusic** [comment]
OK, have some progress, finally managed to log in via web UI (don't know why it wasn't working before), enabled local announce, killed syncthing processes, and after that I was able to start the app normaly. Tried also to disable the same setting again, and then I can't pass the "loading..." stage again.

**Comment by brianhlin** [comment]
If it's the same issue, your configuration may not have taken. Check the contents of `/sdcard/backup/syncthing/config.xml`and make sure you've got the following under `<options>`

```
<localAnnounceEnabled>true</localAnnounceEnabled>
```

If not, I'd try the following (full disclosure, I haven't tried this):

1. Backup your current config file
2. Force stop syncthing
3. Add the above line to your config under `<options>`

**Comment by brianhlin** [comment]
PR submitted #496
