### ISSUE TITLE
Puller fails on OxygenOS with "operation not permitted"

### ISSUE THREAD

**Issue by vrinek** [syncthing/syncthing-android#489]
Syncthing on OxygenOS fails to fetch files from Syncthing on PC. More specifically:

- Syncing from Android to PC works
- Syncing _empty folders_ from PC to Android works
- Syncing _files_ from PC to Android fails

### Steps to reproduce:

- Connect Android to PC
- Add a folder on the PC with some files in it (afaik, file size does not matter)
- Add Android to the PC's folder's devices at "~/Synced/Something" (afaik, the folder name does not matter)

**Observed behaviour:** files fail to sync
**Expected outcome:** files should be syncing normally

More specifically, the GUI does not display the new folder at all. The web ui displays the folder as "out of sync" with most of its items as "failed items" with "operation not permitted". When I navigated to the phone's folder, I found that it is populated by subfolders that match the original (on the PC side) folder structure.

I have tried this with two folders, the 1Password keychain (lots of little files) and another one containing a single *.epub file. Both displayed the same behaviour.

syncthing-android version: **0.7.0**
Device name and Android version: **OnePlus 2, OxygenOS 2.1.1 (based on Android 5.1.1)**
versions of involved Syncthing nodes: **v0.12.1, Mac OS X (64 bit)**

### Part of log file
```
[...]
I/SyncthingNativeCode( 3770): [5GZE3] 19:53:54 INFO: Puller (folder "1Password-keychain", file "data/default/BC9C6C6F79EC42A29BE904923B78DD74.1password"): dst create chmod: chmod /storage/emulated/0/Synced/1Password.agilekeychain/data/default/.syncthing.BC9C6C6F79EC42A29BE904923B78DD74.1password.tmp: operation not permitted
I/SyncthingNativeCode( 3770): [5GZE3] 19:53:54 INFO: Puller: final: chmod /storage/emulated/0/Synced/1Password.agilekeychain/data/default/.syncthing.BC9C6C6F79EC42A29BE904923B78DD74.1password.tmp: operation not permitted
[...]
I/SyncthingNativeCode( 3770): [5GZE3] 19:53:54 INFO: Folder "1Password-keychain" isn't making progress. Pausing puller for 1m0s.
```

**Comment by wweich** [comment]
How did you add the folder on android?
The Syncthing Android App usually enables the "ignore permissions" setting for each folder.
This settings will prevent the attempts to set the file/folder permissions according to the source, which is not possible on Android.

**Comment by vrinek** [comment]
> How did you add the folder on Android?

Since no popup came up on the GUI, I went to the web ui and added the folder from there. I checked right now and the "Ignore Permissions" setting was off. I switched it on before writing this reply and it has already synced my files.

Thanks for the suggestion!

I'll try now to add a couple more folders by waiting for the GUI to ask me about them.

**Comment by wweich** [comment]
The Syncthing Android App currently does not have the "Device x want's to share folder y with, you: accept, decline" dialog.
You can accept that in the WebUI and set the ignore permissions, the rest should be fine.
