### ISSUE TITLE
Keep Syncthing notification on after disconnecting from wifi 

### ISSUE THREAD

**Issue by spjps2009** [syncthing/syncthing-android#490]
It would be helpful if the syncthing notification would stay when connected to mobile data and syncing only over wifi is enabled. Similar to bittorrent sync and it would not prompt to exit.

**Comment by Nutomic** [comment]
The notification is shown when Syncthing is running. You have specifically set it to shut down when not connected to wifi, so it wouldn't make any sense to show the notification. For what reason do you want this?

**Comment by spjps2009** [comment]
I was thinking similar behavior to bittorrent sync, where it's always on and when disconnected from wifi it stops syncing but notification is still on and a message says connected to mobile data and when wifi is connected then it resumes syncing.

**Comment by capi** [comment]
If this is added, please add this as a configurable option. I really like the way it is now. :-)

**Comment by Nutomic** [comment]
I guess this could make sense when/if you can access files on demand. But right now, all you can do in that case is close the app or change the settings. Closing as wontfix for now.
