### ISSUE TITLE
Android device disconnects, Web GUI unavailable

### ISSUE THREAD

**Issue by janusgrave** [syncthing/syncthing-android#498]
I've been using Syncthing heavily and keep running into an issue where the Android client disconnects from the cluster. This occurs when I have "Always run in background" enabled.

In the Syncthing Android app, all information in the left panel (Device ID, CPU usage, etc) is now blank. When I try to open the Web GUI, a "Webpage not available" screen appears. When I try to view logs through the options menu, the app just displays "Retrieving logs..." and never loads.

So it seems Syncthing android's app GUI is still running but Syncthing itself has crashed. Restarting the Android device corrects the problem, but it eventually happens again when "Always run in background" is enabled.

Running Syncthing 0.12.1 / 0.7.0 on a device running Android 4.4.2

Other devices running 0.12.2 (Linux 64) and 0.12.2 (Linux ARM)

I'm attaching a log taken just after restarting the device and launching syncthing android
[log-syncthing.txt](https://github.com/syncthing/syncthing-android/files/34972/log-syncthing.txt)

**Comment by Nutomic** [comment]
Can you post a log right after Syncthing stops working? I don't think logs are kept during a restart.

**Comment by lawfulintercept** [comment]
I've been unable to reproduce the Web GUI unavailable part of the issue, but I just upgraded syncthing-android to v0.7.4 (Syncthing v0.12.2+18-g56f1c29) and now the Android device isn't connecting at all when it's not on the same network as the other nodes.

I've attached an android log - it should show my android device disconnected after the update, then re-connecting once I switch to to the same Wi-Fi network as the other devices
[syncthing-android.txt](https://github.com/syncthing/syncthing-android/files/35828/syncthing-android.txt)

**Comment by capi** [comment]
The default port-mapping for 0.12 syncthing-client changed, you are sure that your router/firewall is not blocking the 0.12 ports?

**Comment by lawfulintercept** [comment]
It's been working just fine ever since Syncthing 0.12 - so that wouldn't be the case unless it changed with the most recent update that went out today. In either case, my network configuration hasn't changed in that time, and I've been using UPnP and global discovery (which should obviate the need for port-forwarding, no?)

**Comment by frabcus** [comment]
For what it's worth, I get the same symptoms as this. I don't think it is to do with the networking - when I trick Syncthing into restarting (e.g. by changing a setting back and forth) it then works fine.

It is like the background daemon can die, but without giving any clear error message.

**Comment by NickPyz** [comment]
+1 similar weirdness here

(1) Some devices are slow to connect to my Android device. After showing green "Up to Date" for a few minutes they suddenly show as "Disconnected" on my Android device. (But they are not disconnected from each other)

(2) If I play with settings and restart, I get the connection "Up to Date" back.

(3) Sometimes a device on the same LAN won't connect at all. Usually it connects very slowly, but by relay .. even though dynamic Address + Local and Global Discovery are enabled and port 22000 TCP forwarded to both devices behind the same router.

Seems to be intermittent - or at least I don't see a pattern to this.

**Comment by NickPyz** [comment]
I believe that Local Discovery is broken in Syncthing Android v.0.7.4 - 0.12.2+18-g56f1c29 ... (unless it's just me)

My droid device is in the same LAN behind the same router at 2 other devices. One of them is running Windows 10, the other ubuntu linux. On all devices, Local and Global discovery are enabled. The default setting allowing relay is enabled.

The Android device connects to the linux machine using Global Discovery (router public IP:22000). Not sure why Local Discovery is not happening. Then android device slowly connects to the Windows machine via relay. Again, NO local discovery happening. 

Anyone else notice this?

**Comment by AudriusButkevicius** [comment]
The ports used for local discovery changed, so check your firewall.

**Comment by NickPyz** [comment]
Audrius:

I'm not sure what to do here.

Since local discovery is .. well, LOCAL - I assumed it wasn't necessary to go into the router firewall and forward port (21027) to my devices. Does that make sense?

My Android phone is unrooted, and I have no firewall installed on this device. What am I missing?

THANKS

**Comment by NickPyz** [comment]
More testing, different result: (remember, all 3 devices on the same LAN)

droid to windows - local discovery
droid to NAS - global discovery (port 22000)
windows to NAS - local discovery

I was incorrect when I said local discovery is broken on android. However, the randomness of connections between local devices (via local, global, relay) and occasional disconnects seems a little odd.

**Comment by AudriusButkevicius** [comment]
Can we stop polluting some random issue with your problems? Open a new issue if you believe one exists.

**Comment by lawfulintercept** [comment]
I was able to reproduce the original issue where the android node disconnects and the app's GUI shows blank fields. This should be a log from immediately after that crash: 
[syncthing-log2.txt](https://github.com/syncthing/syncthing-android/files/41185/syncthing-log2.txt)

As a side note, I believe the issues mentioned above are at least partially related to this. In general, syncthing-android seems to disconnect or not connect at random, both on and off the local network with local discovery + global discovery + UPnP enabled. I've tried to figure out a pattern but to no avail - Sometimes it simply works and stays connected to the other nodes; other times it take a long time to connect; and sometimes it never connects at all.

**Comment by AudriusButkevicius** [comment]
Well log after the crash is not very useful.

**Comment by lawfulintercept** [comment]
Yeah, it doesn't seem to have captured the crash itself.

Is there a recommended way of accessing / capturing syncthing-android's logs immediately after a crash occurs, without using the app GUI?

**Comment by Nutomic** [comment]
Use adb logcat from a PC, or a logcat app on the device.

**Comment by C0R10L4NU2** [comment]
Same issue as OP and frabcus on shamu running CM13's recent nightlies.

**Comment by C0R10L4NU2** [comment]
Okay, I tried to produce a meaningful logcat. And failed. 

As long as adb logcat runs on a connected pc, Syncthing does not crash. I watched it over 30 min. Could adb or adb logcat prevent the device from entering deepsleep?

When the screens turns off, the device is not connected to any power source and no file syncs or transfers are running, Syncthing usually crashes within the next 5min.

I tend second frabcus here. Android's ram management seems to kill the background daemon.

Shamu CM13
Syncthing 7.5

**Comment by capi** [comment]
Maybe the binary does not keep a wake-lock and cannot handle if the device CPU goes to sleep (which it does if not connected to power source and screen is turned off).

**Comment by AudriusButkevicius** [comment]
Not sure how the android kernel works, but for example if we notice time drifft (due to sleep) we restart the binary, so maybe thats the problem? I don't think we can acquire the wakelock from go, so it would have to be done by the app.

**Comment by capi** [comment]
Yeah, I was thinking about that as well already, problem being that keeping the wake-lock "forever" drains battery pretty quickly and also due to applications abusing wake-locks, behavior has been changed in Android 6 (actually the wake-lock now is a no-op, see [Doze](http://android-developers.blogspot.co.at/2015/10/how-google-cloud-messaging-handles-doze.html)).

I am quite sure that the issues reported here are due to device going to sleep, since I use it with "Only while connected to power" mode and I never got any crash over night.

**Comment by C0R10L4NU2** [comment]
I want to add, that I use normal priority (the highest setting) for the permanent notification and disabled android's battery optimization feature for syncthing. The later did not help.

**Comment by capi** [comment]
@C0R10L4NU2 Doze disables the possibility to hold a partial wake lock. Since the native binary and the hosting application is not holding any, I suppose it won't make a difference to allow that. But good to know that you already tried the whitelist.

**Comment by C0R10L4NU2** [comment]
Would bothering to install ST as a system app a viable workaround?

**Comment by capi** [comment]
I don't think it has anything to do with being a system-app or not, I just think that there is something going wrong inside the binary when the Android device goes to sleep, and/or enters Doze mode.

**Comment by C0R10L4NU2** [comment]
I had the impression that android's ram management treats system apps differently from normal apps. 

But to answer my own question: No. I just tried it.

**Comment by AudriusButkevicius** [comment]
If something goes wrong with the binary there should be logs in logcat

**Comment by C0R10L4NU2** [comment]
here is a logcat covering last night. I get basically these 4 sets of messages over and over again.

As soon as I plug my phone into my computer and fire up adb logcat, Syncthing magically does not get killed/ does not crash anymore and syncs.

[crashlog-syncthing-cm13-shamu.txt](https://github.com/syncthing/syncthing-android/files/83614/crashlog-syncthing-cm13-shamu.txt)

**Comment by Nutomic** [comment]
@C0R10L4NU2 You could try to install a logcat app on your phone and use that. The log you attached is incomplete, there's nothing helpful inside.

**Comment by Nutomic** [comment]
Can people with this issue test the [apk in #547](https://github.com/syncthing/syncthing-android/pull/547#issuecomment-175269141) and comment on the pr?

**Comment by Catfriend1** [comment]
According to the comments in https://github.com/syncthing/syncthing-android/pull/547#issuecomment-175269141 this issue got solved by adding an experimental option for partial wake lock.
