### ISSUE TITLE
syncthing breaks when password is set

### ISSUE THREAD

**Issue by klement** [syncthing/syncthing-android#500]
When I set a password for the GUI, the syncthing breaks - when opening the app, "Loading..." is shown but nothing happens.
Also, there is a spam of notifications about requested and granted root access.

**Comment by klement** [comment]
UPDATE: the same thing happens when changing device name, the only way to fix the app is to wipe data.

Also, when root is disabled, changing the password / device name works

**Comment by licaon-kter** [comment]
Be aware that changing to root will taint the config, and changing back the app might not open the config anymore, see: https://github.com/syncthing/syncthing-android/issues/481#issuecomment-156825513

**Comment by klement** [comment]
I first checked "use root" and then did the other changes - that's how it breaks.

Now it's broken again - I cannot start the app at all and see the root granted spam again. Sigh.

**Comment by licaon-kter** [comment]
@klement then you experience this: https://github.com/syncthing/syncthing-android/issues/453

**Comment by Nutomic** [comment]
Yeah this is actually a duplicate.
