### ISSUE TITLE
No new folder form other host alert

### ISSUE THREAD

**Issue by MauroMombelli** [syncthing/syncthing-android#505]
When i share a new folder form other host no alert appear. adding folder by ID does not seems to work; the two host see each other connected.

**Comment by AudriusButkevicius** [comment]
The prompt is not implemented in android, only in the web ui.

**Comment by MauroMombelli** [comment]
even if i launch the web GUI no alert apper

**Comment by Nutomic** [comment]
Duplicate of #295.
