### ISSUE TITLE
0.7.5 beta 1 always crashing

### ISSUE THREAD

**Issue by sniperle** [syncthing/syncthing-android#506]
After updating from (F-Droid version) 0.7.4 to 0.7.5-beta 1 syncthing is always crashing.
I tried to reinstall the app so all old data should be deleted but that doesn't help, it's still crashing.
Can provide two logs, the first from the updating try and the second is from the fresh install try.

[update from 074 to 075beta1.txt](https://github.com/syncthing/syncthing-android/files/42494/update.from.074.to.075beta1.txt)

[fresh install of 075.txt](https://github.com/syncthing/syncthing-android/files/42495/fresh.install.of.075.txt)

**Comment by capi** [comment]
The stacktrace indicates that the bundled native `libsyncthing.so` is missing from the apk.

**Comment by sniperle** [comment]
Then it seems like the people from F-Droid forgot that while building the package.

**Comment by wweich** [comment]
Unfortunately the beta on F-Droid is currently broken: https://forum.syncthing.net/t/syncthing-android-0-7-5-beta1-now-with-dns-support/6233/2

**Comment by sniperle** [comment]
Then I'm closing the issue, because it's a F-Droid related issue.

**Comment by Nutomic** [comment]
0.7.5-beta2 is up and should be on F-Droid soon.
