### ISSUE TITLE
Small GUI bugs

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing-android#508]
Thanks for the 0.7.5 update!

I found these small bugs
- while editing the device address, it takes a little longer than usual for Android to show the keyboard (seems to be related with displaying the current address/version below the introducer switch)
- the device address(es) are shown in escaped style, e.g. `tcp:\/\/` instead of `tcp://` (even after edit and restart)
- even if the device is disconnected Syncthing shows the lines "current address" and "syncthing version" after some time (timeout?) although not needed

**Comment by Nutomic** [comment]
Fixed the second point. There's nothing that should cause your first point (and I couldn't reproduce it). Third point doesn't really matter imo, as the web gui also shows the address field for disconnected devices.
