### ISSUE TITLE
Can't connect to my computer

### ISSUE THREAD

**Issue by MickeyKnox** [syncthing/syncthing-android#509]
I just installed syncthing on android and wanted to connect to my computer. Trying to scan the QR-Code failed; nothing ever happened. At last I resorted to just type in the code. Once I was finished, the app crashed. Did I miss something? How should I proceed to connect to my computer?

My phone is a Samsung Galaxy S2 running Replicant.

**Comment by licaon-kter** [comment]
Generate log from application Settings?

**Comment by MickeyKnox** [comment]
Could you expand on that? What exactly should I do?

**Comment by licaon-kter** [comment]
In Settings -> About -> Open Log -> menu -> Share -> use https://gist.github.com to share I guess.

**Comment by MickeyKnox** [comment]
I don't see how I can "use https://gist.github.com". The available options are:
Bluetooth, Messaging, Term here, Aard, Face Slim, Barcode Scanner and K-9 Mail.

Besides, the only text on screen (before I go to menu -> Share) is:
[code]Retrieving logs...[/code]

**Comment by licaon-kter** [comment]
No logs shown?

**Comment by MickeyKnox** [comment]
Nothing besides "Retrieving logs..."

**Comment by Nutomic** [comment]
Do you have a QR scanner app installed? Can you post a log for the crash?

**Comment by MickeyKnox** [comment]
I could not reproduce the crash. But I've made some progress It seems like I connected with my computer and for a moment it looked like, they can see each other. Since then however, they both show each other as disconnected. I have no idea why.

The log however shows something new:
Unable to open log device '/dev/log/main': Permission denied

**Comment by MickeyKnox** [comment]
Sorry, I overlooked your first question. I have Barcode Scanner installed, as suggested by the syncthing app. It doesn't scan the QR code on my computer however. I can see it in the app, but the app seems not to be able to scan it. Nothing happens. I winded up entering the device ID by hand.

**Comment by Nutomic** [comment]
I can't help you with the QR problem, that seems to be a problem with the scanner app. 

As for the device connection, it sounds like some kind of firewall issue (assuming both devices have been added to each other). Logs and [sttrace options](http://docs.syncthing.net/dev/debugging.html) might help, or ask on the forum/irc.
