### ISSUE TITLE
Folder never finishes syncing

### ISSUE THREAD

**Issue by jon-proulx** [syncthing/syncthing-android#512]
syncing camera images directory hangs with:

 Global State 	4281 items, ~10.2 GiB
 Local State 	3258 items, ~10.1 GiB
 Out of Sync Items 	1023 items, ~34.4 MiB

renaming the out of sync items on the phone gets them to sync (there were previously two more items)

android side is v0.12.6 on ATT Note4 running 5.0.1 (folder set to "Master" mode)
other point is v0.12.7, Linux (64 bit) on Ubuntu14.04

**Comment by AudriusButkevicius** [comment]
Is that the stats on the PC or on the phone?
Also, check the logs or `Failed Items` for clues as to why it's happening.

**Comment by jon-proulx** [comment]
stats are from PC side (phone agrees with "global state") `failed items` is just a spinning wheel no link or count.  On the phone side there's not hints in the logs & embarased to admit I can't find PC side logs.

This has been a long standing issue for me (at least since v0.11 series maybe earlier) that I'm revisiting & one thing I should have tried sooner is deleting the folder definition on the phone and resyncing (had already flushed PC side hard ).  That is currently in progress I image it will take a while for the phone to sift through 10.2G...

**Comment by AudriusButkevicius** [comment]
Well figure out where logs go on the PC side to figure out whats causing the failures.
It will either be ignored items, permissions. disk space or ignored files.

**Comment by jon-proulx** [comment]
Ok thanks, running fresh sync in foreground now so I can see what it's doing.

**Comment by jon-proulx** [comment]
Sigh, seems I just needed to turn it far enough off (undefine on both ends) before turning it back on again...
