### ISSUE TITLE
Enhancement request: local changes reported on the notification bar

### ISSUE THREAD

**Issue by rdarioc** [syncthing/syncthing-android#513]
Would it be possible to be notified of changes on the local file system directly in the notification bar of Android?

Maybe this option could be enabled on a per directory basis or even per type of event (new file, deleted file, modified file, etc).

 I keep syncthing always on and it would be nice to have a simple notification informing when a large new file has been downloaded.

Thanks
Rosario

**Comment by Nutomic** [comment]
Duplicate of #130 ;)

**Comment by rdarioc** [comment]
Sorry man, I swear I searched it before posting. My fault. Well, hope it will be implemented some day.
Great work anyway.
