### ISSUE TITLE
Request notification only visible in status line 

### ISSUE THREAD

**Issue by redjamesg** [syncthing/syncthing-android#516]
I have a request, that the notification selection wilm have an added selection, where in addition to the "normal", " low priority" and "none" will be an "icon only" selection, where it is only the syncthing icon beeing shown in the status line, and not the "syncthing is running' in the notification area.

**Comment by licaon-kter** [comment]
I don't think it's possible in Android.

**Comment by Nutomic** [comment]
Nope, not possible (except maybe with some vendor specific hacks which I won't implement).
