### ISSUE TITLE
FR: DIsable "loading" during startup

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-android#517]
Hi

I personally find the loading window that blocks the startup quite annoying. The reason is that I do not know what the heck is going on undernath when that happens. SOmetimes it takes a long time to start sometimes it is a bit faster. In any case would not it better if the app opens the log viewer instead the blocking loading window and then move to the actual window once it starts up. This way the user can see what is going on and can debug the issues if there are.

**Comment by Zillode** [comment]
1. We need to handle syncthing exit codes and show the log if needed
2. Loading will become faster in the [future](https://github.com/syncthing/syncthing/pull/2515)

**Comment by Nutomic** [comment]
I would say this is fixed with the latest version, startup time is now less than one second on my Nexus 5.
