### ISSUE TITLE
Inconsistent folder id restriction 

### ISSUE THREAD

**Issue by xadh00m** [syncthing/syncthing-android#519]
Hi,

I recognized that the folder id is checked [here](https://github.com/syncthing/syncthing-android/blob/master/src/main/java/com/nutomic/syncthingandroid/fragments/FolderFragment.java#L301) and rejected if it contains 'invalid' characters. This restriction does not seem to exist in syncthing. E.g. it is no problem to create a folder with id 'foo/bar' in the web interface. But on android this id is rejected because of the slash.

Any chance the behavior could be made more consistently here?

Thank you.

**Comment by Nutomic** [comment]
Looks like this restriction was removed from Syncthing at some point.

**Comment by xadh00m** [comment]
Great! Thank you.
