### ISSUE TITLE
Manual Start and Stop

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-android#521]
Hi

The android app uses alot of cpu for no apperant reason. Sometimes I find my battery drained %30 in less than 10 minutes by the Sycnthing app and I can see that the syncthing.so runs and uses alot of cpu for no apperant reason (even when there should not be any updates from other clients or from a non existing file update). Also the Battery app shows that most of the battery was used by the ST app.

So the solution could be this. It would be nice to have the synthing app running in the bg but the user should be able to control a stop and start process of the Syncthing binary. That way the binary is paused (or something like that) and check for files modifications etc. it does it only when the suer asks for it.

@Nutomic
added a fix f383393

" Added functionality to manually stop sync (fixes #131).

This functionality can not be used together with wifi/charging settings.

By default, this is set so that syncthing is only active when requested,
and can be stopped by the user."

However I am not seeing this functionality anywhere on the ui.

**Comment by Nutomic** [comment]
Opening the app starts Syncthing, and the exit button in the drawer stops it. This only works if "run in background" is disabled.

**Comment by gerroon** [comment]
Well, that is not a feature is it? I mean opening and closing an app should naturally start and stop the app? 

Anyway the issue with that approach is that it would trigger extra processing which is bad for the battery. The whole point of manual stop start is to save on processing therefor gaining extra battery time. 

I wish to see this implemented at some point.

thanks

**Comment by veniosg** [comment]
I may be understanding your request wrong but if you disable "run in
background" you are essentially getting what you asked. Furthermore, no app
in the Android system actually stops when you press back and stop seeing
it, let alone sync services.
As for the battery concern, I have not seen the drain you are experiencing
and I have used the app on several low end devices. If you use the Web UI
you can see the refresh interval of your folders, maybe they are set too
low? On Android it's meant as a safeguard against automatic change
detection not working (Felix correct me if I'm wrong).

Anyway, imo if there is indeed a battery issue, this is a user facing
workaround instead of a real fix and I think it adds unnecessary friction
to the usage experience when syncthing would ideally be fire and forget
like drive/dropbox/whichever service.

**Comment by gdt** [comment]
I have been running syncthing with "run in background" and "sync only on wifi" and "sync only when charging" and that has worked well, without (apparently - it's hard to be sure) causing excess battery drain.

What I object to is that when run in background is on, there's then no exit button.  I realize the android philosophy is different, but I want to be able to say "please shutdown now", being fully aware that it will start on next boot and deviate from the "run in background" config.  I would be fine with a "syncthing is configured to run in the background - are you sure" popup.   As it is I of course can do what I want, but I have to first go turn off automatic sync.  Then if I start it again, it will sync on battery and cell data, so I'm finding this to be a bad UX.   Perhaps I should use force quit instead :-)

**Comment by gerroon** [comment]
@veniosg 

Syncthing binary seems to check files very frequently even though when I set my scan time to "0" which is supposed to disable the scan. I see very frequently that the binary starts using high cpu for no appearant reason (and the other nodes should not send file updates because there are no updates on those nodes since I am the only user of these node). 

The way I am asking is  this. The syncthing binary(not the ui) is paused therefor the binary never tries to engage in any kind of disc or cpu activity. It becomes alive only when the users presses on start.

What is the difference between this and restarting the app? Well restarting does various checks beside file scanning. And those checks take up cpu as well. And sometimes the ST Android app takes a long time to start which is annoying too.

**Comment by Zillode** [comment]
>I see very frequently that the binary starts using high cpu for no appearant reason (and the other nodes should not send file updates because there are no updates on those nodes since I am the only user of these node)

Note that reconnections also cause a full db scan and the transmission of index data.

**Comment by gerroon** [comment]
@Zillode 

The kind of high cpu happens while Syncthing is running not when it starts up. The high cpu usage during startup is one of the issue I want to avoid that is why I was suggesting to implement start stop syncthing binary so that I do not have to go through this Syncthing app startup procedure (db scanning, file scanning, wifi usage etc)

**Comment by wweich** [comment]
>Syncthing app startup procedure (db scanning, file scanning, wifi usage etc)

This is done by the Syncthing binary, not the App. The only thing the App does when starting, is start the binary and wait until it is running to see the status. The App itself does next to nothing, which would cause significant CPU or data usage.

**Comment by gdt** [comment]
From the user viewpoint, there is no difference between the app and the binary.   That's just an artifact of how it is constructed.   So the App is responsible for all usage by the other parts.

**Comment by gerroon** [comment]
Well whatever it is, the user cant distunguish the binary. I  just had Syncthing Android eat up %65 of my battery in 1 hour so. I had %80 battery left when I started Syncthing,  in an hour or so my battery went down toi terrible %15. Please bear in mind that my device has 4800a battery

**Comment by Nutomic** [comment]
How should "run in background" and exit on demand work together? For example:
1. "run in background" and "sync on wifi" are enabled
2. user presses exit
3. device connects to wifi

Shoud Syncthing run? 

You could argue yes or no, but neither is clear to the user. If you can think of a good UX for this, we can consider it.

As for the battery usage, can you check the logs what the app was doing? In my experience, data usage (including index exchange) can use a lot of CPU, so if there's a sync running or devices connecting, that may be the reason. For either of those, you should open an issue at Syncthing directly.
