### ISSUE TITLE
Folder created using Web GUI doesn't show up in GUI

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#522]
I can't select `/data/data` in GUI (even with "advanced picker"), so created it using Web UI.

I expect GUI to detect this and show folder in the list.

**Comment by licaon-kter** [comment]
`/data/data` needs root access, see https://github.com/syncthing/syncthing-android/issues/453

**Comment by vi** [comment]
Yes, it works with root access, but I can't still input "/data/data" in GUI. It only allows to select a directory that can be accessed as non-root, and `/data/` is normally not enumeratable as user. Either Android UI for Syncthing should also browse filesystem from root when it's enabled or there should be option to input directory name manually from keyboard (not picking existing directory).

Workaround is to use Web UI and input it manually from keyboard.

**Comment by licaon-kter** [comment]
Then close this.
