### ISSUE TITLE
Can't sync folder with space in ID

### ISSUE THREAD

**Issue by JohnMaguire** [syncthing/syncthing-android#527]
I have folders with spaces in their IDs on multiple machines (OSX/Linux). When I try to add one on the Android client, I get the error that you can't have a space in your Folder ID. I do not believe this is true.

Thanks!

**Comment by licaon-kter** [comment]
Might have been fixed already: https://github.com/syncthing/syncthing-android/issues/519

**Comment by Zillode** [comment]
> ^

will be fixed in the next release

**Comment by JohnMaguire** [comment]
Thanks, sorry for the dupe. :+1:
