### ISSUE TITLE
Turkish playstore description hasn't been updated

### ISSUE THREAD

**Issue by canerbasaran** [syncthing/syncthing-android#530]
https://www.transifex.com/syncthing-android/syncthing-android/translate/#tr/description_fulltxt/50664209

**Comment by Nutomic** [comment]
Yeah, I've been on vacation for the past weeks and didn't have time to update the description. I tried to change it now, but the Google Play API is just giving back errors, no idea why. Will keep trying though.

**Comment by canerbasaran** [comment]
Forum link needs updating in google play. Link is https://forum.syncthing.net/ in my translation. But other language pages in google play, still https://discourse.syncthing.net/

**Comment by Nutomic** [comment]
Ah that's right, thanks for letting me know :)
