### ISSUE TITLE
Failure to connect - Windows 10 and Samsung Note 5.

### ISSUE THREAD

**Issue by evogel99** [syncthing/syncthing-android#531]
Windows 10 and Samsung Note 5. other device shows up on both instances but had never connected.

**Comment by licaon-kter** [comment]
Software versions?

**Comment by evogel99** [comment]
Windows 10 is newly installed and up to date, 64 bit. 

Syncthing amd 64-v0.12.11 on Windows machine.

v0.12.6, android (ARM)
