### ISSUE TITLE
Navigation Drawer Toggle tries to spin

### ISSUE THREAD

**Issue by dluco** [syncthing/syncthing-android#532]
When the navigation drawer is opened by dragging from the left-edge of the screen, the drawer toggle "hamburger" tries to spin and morph into the back-arrow. The `ActionBarDrawerToggle`'s spinning behaviour is, correctly, disabled because the drawer opens over the `Toolbar`. However, if the drawer is opened very slowly, the `ActionBarDrawerToggle` can be seen to "distort", as if it is spinning.

A quick solution to prevent the spin/distortion is to change the `Toggle` class in `MainActivity.java` to override `onDrawerSlide(View drawerView, int slideOffset)` and call `super.onDrawerSlide(drawerView, 0)`.

Note: the `Widget.Syncthing.DrawerArrowToggle` sets the attribute `spinBars` to false. This is supposed to disable the animation, but does not completely disable it.

**Comment by Nutomic** [comment]
Pull request welcome ;)
