### ISSUE TITLE
Feature Request: Sync when connected to WiFi but only when connected to certain networks

### ISSUE THREAD

**Issue by zekesonxx** [syncthing/syncthing-android#533]
Would love the ability to only sync when connected to certain WiFi networks. Currently it's pretty much the only thing stopping me from enabling always-in-the-background, as I don't want it trying to sync over the internet and waste bandwidth.

**Comment by licaon-kter** [comment]
Already merged: https://github.com/syncthing/syncthing-android/commit/0582c6700810d30a7d78b5db7d4de688900c073f wait for the next version.
