### ISSUE TITLE
alcatel one touch pop 2 5042d - not workning

### ISSUE THREAD

**Issue by evgenyigumnov** [syncthing/syncthing-android#535]
Hello

When I try to start application then it crushed. 
Application is notwork on alcatel one touch pop 2 5042d

**Comment by licaon-kter** [comment]
What Android version?

**Comment by evgenyigumnov** [comment]
Application say in Russian:
"Cant create configuration for Syncthing"
"Look at journal"

**Comment by evgenyigumnov** [comment]
Android 4.4.4
Kernel 3.10.28

**Comment by licaon-kter** [comment]
Do you have root and you activated root support in Syncthing? If yes, root does not work yet, see this: https://github.com/syncthing/syncthing-android/issues/453

Else, maybe see this to generate a log: https://github.com/syncthing/syncthing-android/issues/518#issuecomment-165199417

**Comment by evgenyigumnov** [comment]
I was root my android 5 minutes ago.
When I was try launch Syncthing It was crashed again. 
BTW, Application did not ask root access...

**Comment by licaon-kter** [comment]
Try to clean all app data in Settings->Application for Syncthing and retry.
If that fails try to uninstall and then reinstall it.

F-Droid or Google Play app?

**Comment by evgenyigumnov** [comment]
I do this: "Try to clean all app data in Settings->Application for Syncthing and retry."
and move from SD external to SD internal. It's working!
Thank you.

BTW. licaon-kter.  are you russian?

**Comment by licaon-kter** [comment]
No. :)
Oh, so that was the problem, yes most apps can behave strange on SD card, Android 6 will fix that, but your device will not go there. ;)

Feel free to close this issue then.

**Comment by evgenyigumnov** [comment]
Your github avatar very simmilar with https://en.wikipedia.org/wiki/Dunno
It is Russian children hero :)

**Comment by licaon-kter** [comment]
It's him, yes.

Russian influence reign for decades in a lot of adjacent countries, even the literature was obligatory, kids were not exempt.

**Comment by evgenyigumnov** [comment]
This is geo-politic. Some body says: "Border of Russia ends where cease to speak Russian"

**Comment by licaon-kter** [comment]
And yet that was not even the case. ;)
