### ISSUE TITLE
Delete folder, confusing to a user. 

### ISSUE THREAD

**Issue by JohnTheDaniel** [syncthing/syncthing-android#536]
When opening a folder, and press delete, a dialog shows up with the text 

"Are ypu sure you want to delete this folder?"

This confused me as a user, as I thought I was going to delete the data in the folder. 

Maybe a better dialog would show the text

"Are you sure you want to stop syncing this folder?"

**Comment by MartinX3** [comment]
Would that be better?

"Are you sure removing this folder from the syncing list?"

**Comment by Zillode** [comment]
Related discussion upstream: https://github.com/syncthing/syncthing/issues/1007
