### ISSUE TITLE
SSL error a few times a minute

### ISSUE THREAD

**Issue by sgtnoodle** [syncthing/syncthing-android#537]
I'm running syncthing v0.12.11 on my arch linux desktop. I just installed syncthing from the android store on my phone. I set it all up and it's been transferring files, but the connection craps out after 10-60 seconds. After another minute or so it reconnects, transfers some more files, then craps out again.

Log from my desktop:
Jan 15 22:37:47 XXX syncthing[21230]: [3YSOC] INFO: Device XXX client is "syncthing v0.12.6" named "localhost"
Jan 15 22:38:34 XXX syncthing[21230]: [3YSOC] INFO: Connection to XXX closed: local error: record overflow

The syncthing log on the phone says this:
06:48:02 INFO: Connection to YYY closed: remote error: bad record MAC

Even with this bug, the app is pretty slick! Nice work.

**Comment by Zillode** [comment]
@AudriusButkevicius any ideas?

**Comment by AudriusButkevicius** [comment]
It's something in the environment (proxy?). Potentially something trying to inject something into the TLS stream.

**Comment by AudriusButkevicius** [comment]
Or antivirus

**Comment by sgtnoodle** [comment]
On the non-android side of things, there isn't anything I can think of that would be trying to inject data into arbitrary TCP connections. My desktop is running up-to-date Arch installed by myself, and my WiFi router is running OpenWRT. On the phone end it's a Nexus device running stock and I don't install many apps, so I'd be surprised if there is anything malicious going on. If there is anything, then it's probably a "feature" of the Android operating system.

I've noticed that the connection has remained up more reliably since becoming 100% synced. While syncing it was pumping several MB/s through the connection, and now it's ~0. If this is a bug inside syncthing-android, it's possible that most folk don't notice it because it's rare to be pumping several MB/s for many seconds to a mostly synced phone.

Is it possible that some application buffer is overflowing and causing corruption in the stream after TLS encoding or before TLS decoding? I'm not familiar with TLS or what a TLS record is, but I could imagine corruption or drops in a serial stream leading to the appearance of larger-than-expected packets.

I can try transferring some big files desktop->phone and phone->desktop to see if it's symmetrical or not. Is there anything specific I can do to collect more information? tcpdump or something?

**Comment by sgtnoodle** [comment]
The disconnection only occurs when the phone is pushing files out, not when the phone is pulling files in. I've been experimenting in wireshark on my desktop, and I consistently see one or two out-of-order packets, followed by a 35-37ms gap in packets, followed by some duplicate ACKs from the phone right around when the record overflow error happens. There are plenty of other periodic gaps between packets as you would expect over WiFi, but most of them don't seem to correlate to anything.

**Comment by AudriusButkevicius** [comment]
So the android wrapper uses more or less the same binary as the desktop, so there is nothing different in how we send packets on either version. If it was a real issue, I think we'd have more reports, buy given we don't - I'd say its a faulty device. It could be a ton of things thats causing that, bad hardware, bad kernel, bad software, malware. If you phone is rooted, I'd try replacong the binary shipped with the phone app with a vanilla one off syncthing's release page.

**Comment by sgtnoodle** [comment]
I think you're right! I whipped up a TCP stress test and my nexus5 can't go longer than 50MB or so without corrupting the stream. :-/ I hate computers. :-)
