### ISSUE TITLE
Upgrade Syncthing Android to v0.12.15

### ISSUE THREAD

**Issue by MartinX3** [syncthing/syncthing-android#539]
Please Upgrade the Android Version to v0.12.15, like the Desktop one.

There is only version v0.12.06

**Comment by Nutomic** [comment]
Yes, we're onto that ;)

**Comment by MartinX3** [comment]
Thank you :)

I only asked, because i saw no hint, that you're on it :)
I thought the development of this APP is frozen, because the last commit were made 25.11.2015. :)

**Comment by Nutomic** [comment]
I was on vacation for the last few weeks, that's why. New release is out now :)

**Comment by MartinX3** [comment]
Thank you! :D
