### ISSUE TITLE
Android 2.2 support (Nook Simple Touch Glowlight is still a marvelous e-book reader)

### ISSUE THREAD

**Issue by tlaurion** [syncthing/syncthing-android#541]
Hey,

It would be awesome to have support for Android 2.2 so that it is installable on rooted nook devices that are still one of the most amazong e-reader for versavility outthere, with FBReader still suporting the beast.

From my understanding (i'm no Android dev) this application running on all my other devices doesn't require that much frontend support and the backend should be portable. Any thoughts?

Thanks.

**Comment by AudriusButkevicius** [comment]
http://developer.android.com/about/dashboards/index.html

The effort for 0.2% is not worth it, and it's not as straight forward as you think, as we'd be giving away a lot cool features to support ancient devices.

**Comment by Nutomic** [comment]
It would be rather easy to make a "legacy" version of the app that supports older Android versions. Basically, you'd have to remove the whole Android GUI, and just leave the web GUI in. 

I'm not interested in maintaining that, but let me know if you want to do it.

**Comment by Nutomic** [comment]
Closing this, like I said let me know if you want to work on a "legacy" app.

**Comment by tlaurion** [comment]
Sorry for duplicating, didn't remembered I actually opened a ticket.
Yeah, I would be interested.

Would it be possible to have a build that just deactivate such features for 2.2?
Can you pinpoint where and how I could do that? Or pinpoint to me a commit that actually worked for 2.2 So I can work y way up to creating such a build?

Please give me a bit of information, since i'm not that used to android development.

**Comment by AudriusButkevicius** [comment]
There is no point opening another issue, it was decided that no effort will be spent on that.

**Comment by Nutomic** [comment]
This is the last commit that supports Android 2.2: https://github.com/syncthing/syncthing-android/commit/819a3ffc66c5b693334415f82b071e7134d7530a

So you could just get the source code for that, update Syncthing, and compile it.
