### ISSUE TITLE
0.7.6 keeps adding space between https:// and the ip adress in the Global discovery line

### ISSUE THREAD

**Issue by irregularisnotrandom** [syncthing/syncthing-android#542]
Hi

0.7.6 has started complaining about invalid character " " in host name. I did not added the hostname between versions so this is something that has been introduced in 0.7.6

I never had this issue with the previous versions. I even edited the line and restarted syncthing, it still complains about it. I am using the exact same settings in 0.7.6. 

I am also using custom discovery

**Comment by Nutomic** [comment]
I can't reproduce this. Besides, we didn't change anything relevant since the last release. Are you sure it's not caused by your keyboard?

**Comment by capi** [comment]
Haven't yet had a look at the layout files, but still an idea: are we missing the correct auto-correction hints for keyboards on various fields?

**Comment by Nutomic** [comment]
Ah you're right, good call!

**Comment by Zillode** [comment]
:+1:
