### ISSUE TITLE
 "WiFi only" should not depend on "background/foreground", Wifi only should be default

### ISSUE THREAD

**Issue by fraternl** [syncthing/syncthing-android#549]
've been an early adopter of btsync and used it for a long time. When things became sour there I started investigating syncthing and watched if I could use it as an alternative.

After successfully running it for a while on both Linux (in datacentre) and Windows I started my first experiment on Android.

I had some trouble loading the sync as I expected "the sync" to be pushed to my Android just like on the other devices. When I did get it to work it immediately started sending all the data that was in the sync I was testing with.

I wasn't prepared that this could happen as all syncing software on mobile devices I've used thus far are made in a way that syncs are by default "on demand".
Now I know this hasn't been implemented (yet??).
This makes it useless for all my real world scenarios I have currently working with other software.

But my bad luck didn't stop there.
Whilst syncing I got a message that my dataplan was running out and before I could stop syncthing it burned 2.6 GB of the 3 GB dataplan.
I had my WiFi turned off because I travelled that morning by train which always gives me a bad WiFi-connection.

Some said I should have turned "WiFi only" off, but at this stage I was still running it as a foreground application. That option is not selectable then,,,,

IMHO the WiFi-only should be the initial setting and this should not depend on ""foreground/background"

I've removed the application for the time being, but I will install it immediately whenever an "on demand" is implemented.

Remark:

If "on demand" would be possible (and turned on by default) it would make sense to couple it with foreground/background. Now it doesn't (as I found out).
I would have rather paid the € 10,- to you instead of T-Mobile.

**Comment by Nutomic** [comment]
At the moment, the way we disable Syncthing is by shutting down the binary. This means the GUI is unusable at that time. We can probably change this now that Syncthing supports pausing devices.

See #81 regarding selective download.

**Comment by licaon-kter** [comment]
Maybe that would fix https://github.com/syncthing/syncthing-android/issues/543 and https://github.com/syncthing/syncthing-android/issues/540 too then.

**Comment by capi** [comment]
It would definitely be an improvement. Still the current behavior has the advantage that while sync is not running, the binary is not running and doesn't require resources.

**Comment by Nutomic** [comment]
Pausing devices also has the disadvantage that it only works while Syncthing is running. After a restart, it will be unpaused again. By the time we can pause it through the API, it might have already connected to other devices.

**Comment by AudriusButkevicius** [comment]
I think there is one already

**Comment by Nutomic** [comment]
You're right, there's `syncthing -paused`. Now someone just needs to implement this all :D

**Comment by fraternl** [comment]
I don't know why the title has changed, but I chose that title to indicate exactly what is wrong....

As a first-time user I will not have it set to run in the background and therefore I can't select the WiFi-only.  I don't see why there has to be a link between these 2

implementation should follow usage not the other way around.

**Comment by capi** [comment]
@fraternl while I mostly agree with you, as a first-time user you won't have any sharing configured (yet) and therefore this won't cause much traffic over your mobile connection (basically only discovery service).

**Comment by fraternl** [comment]
I was a first-time user of the Android app... not the desktop version. There are several months between my first usage of syncthing and the syncthing Android app.

Even if you are a first time user of the Android-app it is even more than likely you will have it setup on a desktop first.

**Comment by capi** [comment]
Still you first need to add the devices and shares, so you are not right away using data. In my opinion we should change the notification for the running service (connection status) to default-on, not hidden like it is at the moment.

**Comment by fraternl** [comment]
You are just repeating what you said before and assume others are doing things exactly like you

**Comment by jkufner** [comment]
"WiFi only" checkbox should be completely unrelated to everything else, just like any other application. It does not matter whether Syncthing is in foreground or not. Or whether user triggered sync manually. If "WiFi only" enabled, it must not communicate over any network except WiFi. If user wants to use mobile networks, he can uncheck the option.

**Comment by capi** [comment]
As I said, I completely agree with you. But unfortunately the way Syncthing on Android is realized at the moment, that cannot be easily done at the moment. That's what @Nutomic and I were trying to explain.

**Comment by fraternl** [comment]
OK...   that part wasn't clear to me..

There should be no need to say these things and implying that this is not that important or "does not happen that often". That's just clutter.

**Comment by Nutomic** [comment]
@fraternl Sorry, I found the title confusing and tried to clarify it. I changed it back now, so it's (hopefully) clearer and also correct.

**Comment by berkes** [comment]
Just weighing in with my case:

* Synching music. Had "background" and "only on wifi" checked. 
* A few weeks later I decide to uncheck "background" because I wanted to check if this was causing a recent battery-draining-issue.
* I did not review the settings closely after unchecking.
* Falsely assumed "only on wifi" was still on: I remember switching this on, not switching it off.
* Gone out of the door one day, forgetting to actively close Syncthing. 
* 3Gb bandwidth dataplan for February was consumed on 4th of February already. 24 more days to go.

In my case, reviewing the settings closely revealed that unchecking "background" would disable "only on wifi" since these settings are grouped. But this is not how most apps work, nor is it made abundantly clear that unchecking one, will uncheck the other too.

**Comment by erikvanoosten** [comment]
+1 for this feature request

I also accidentally burned through my entire data plan in 1 day. Syncthing is removed from my android phone for now. I will come back when this is implemented, preferably with an option to override per folder.

**Comment by erikvanoosten** [comment]
Thanks people, 0.13 seems to support this!

**Comment by petergaultney** [comment]
This bit me also. I prefer not having Syncthing run in the background, as it can be a bit of a battery hog if there's a lot of data. I can easily start Syncthing whenever I need it to sync things. But I also lost quite a bit of money because apparently my phone randomly decided to disconnect from a wifi network even though the wifi was working just fine, and I had Syncthing running a full sync of my 50GB music library to a new computer at the time.

**Comment by capi** [comment]
As a workaround: you could disable cellular data usage in the Android settings for the app.

**Comment by petergaultney** [comment]
So, I can disable Background data usage. But that's not necessarily the same thing as all cellular usage, right? If my app is in the foreground (because I originally had background running disabled, so I only ran Syncthing as a foreground app when I wanted to actively sync), then the app will continue to churn through my data merrily while running in the foreground.

**Comment by petergaultney** [comment]
Frankly, I would agree that it's relatively astonishing that Android itself doesn't support this use case natively. But most apps that deal with large data do offer it themselves as a non-dependent toggle.

**Comment by capi** [comment]
@petergaultney Oh, you are right. On my LineageOS I had the possibility to disable cellular in general, not only background. Was not aware that this was not a stock option, but see it now on my Moto G6+. Sorry. So this is _not_ a valid workaround.

**Comment by Catfriend1** [comment]
@fraternl Help is on the way ...

**Comment by petergaultney** [comment]
thank you, @Catfriend1 !
