### ISSUE TITLE
Missing Settings Gradle?

### ISSUE THREAD

**Issue by datgb** [syncthing/syncthing-android#551]
Curious when I went to see this is studio I cant find a settings gradle and got errors on the install. 

I was having the same issues as others that it states "failed to create config, please check the logs". New here and was wondering if this has anything to do with it?

**Comment by Zillode** [comment]
Could you post which errors you get? Both @Nutomic and I are using Android Studio. Don't check out the app folder but the entire repo as a project.

**Comment by licaon-kter** [comment]
@datgb: did you use *"Import project"->choose folder* to set it up?

**Comment by datgb** [comment]
What I did was hit the download to clone it in my git desktop, then I imported it into studio from there, 

The app installs but when i click it, it says failed to create a config. please check logs, and then it closes. I saw otheres with this same error in here already but no solution.

**Comment by datgb** [comment]
Downloaded straight from here. https://github.com/syncthing/syncthing-android 
 
Am I supposed to download from a different place?

**Comment by Zillode** [comment]
Sounds about right. Make sure you have the syncthing binaries in place. See https://github.com/syncthing/syncthing-android#build-instructions or manually copy them as explained in https://github.com/syncthing/syncthing-android#building-on-windows. The file `libs/armeabi/libsyncthing.so` needs to exist before you can run Syncthing on your phone.

**Comment by datgb** [comment]
@Zillode  Ok do you have a more in depth tutorial I can follow for this? Im a little new to this and need not sure about how to set it manually or if using terminal in the Studio

**Comment by Nutomic** [comment]
Did you follow the instructions in the links above? Then you should have a file `libs/armeabi/libsyncthing.so` in your repository, and you can run the app from Android Studio.

It might be easier to discuss this on [irc](https://kiwiirc.com/client/irc.freenode.net/#syncthing).
