### ISSUE TITLE
discosrv: Bad certificate error when using custom discovery server with CA on Android

### ISSUE THREAD

**Issue by Alex2395** [syncthing/syncthing-android#552]
After setting up Syncthing on my devices I decided to run my own discovery server.
I created a certificate/key pair using xca (PKI database tool) and signed it with my CA certificate.
I use my own PKI for other services and my root CA certificate is already installed on all devices.
The Syncthing Windows client works well with the custom discovery server but when trying to connect with my phone (Android 6.0) the discovery server debug output shows " TLS handshake error from 1.2.3.4:40256: remote error: bad certificate.

What I have tried to resolve this issue:
- I exported the certificate file from xca again, this time including the whole certificate chain.
- I removed my CA certificate from my Android phone and added it again.
- I used MoveCerts from F-Droid to move user certificates to the system certificate store (also suppresses warnings on Android).
- I issued a new server certificate with a shorter validity (3 years) because I found out that Chrome does not like certificates that last longer than 39 months. Now Chrome can connect but the Syncthing Android Client still does not.

Am I doing something wrong? Or is the Android app not correctly checking the certificate?

**Comment by AudriusButkevicius** [comment]
This is probably more suitable on the forum, given it's a question.

Android app uses more or less the same binary as windows etc, and that binary uses the certificate store of the distribution (which I assume is /etc/cacerts/ or something along these lines).

It depends on how you install the certificate, it might not be good enough for the binary.
Also, double check that when accessing the web page via chrome, you don't get a certificate warning.

You can perform certificate pinning by appending ?insecure=true&id=<id of the discovery servery> to the discovery server URL.

**Comment by Alex2395** [comment]
Accessing the web page via Chrome works. Certificate pinning works too.
Maybe this post is more suitable on the forum. On the other hand, this "It depends on how you install the certificate, it might not be good enough for the binary." could be explained in the documentation.

I just wanted to point out that I followed the tutorial for setting up a discovery server and it does not work out-of-the-box with Android unless I use certificate pinning.

**Comment by Nutomic** [comment]
I'm closing this, please post further questions to the forum or irc. Or open an issue/pr on the [docs repo](https://github.com/syncthing/docs).
