### ISSUE TITLE
Should be an option to run Syncthing only on WiFi with VPN

### ISSUE THREAD

**Issue by stooone** [syncthing/syncthing-android#553]
I use an adblocker on my device what operates through local VPN, but now Syncthing isn't running if I select "Sync only on wifi" because at /src/main/java/com/nutomic/syncthingandroid/syncthing/DeviceStateHolder.java:45 cm.isActiveNetworkMetered() returns true if VPN is used on the device.

It would be great to remove this from the if or have a checkbox what overrides it since in this case a local VPN is not really metered.

Thanks!

**Comment by licaon-kter** [comment]
AFAIK, at least using https://github.com/M66B/NetGuard (adblock via VPN) Syncthing works as expected. I'll recheck asap if "sync only on Wi-Fi" is enabled.

**Comment by stooone** [comment]
I use [adguard](adguard.com), and if "sync only on Wi-Fi" is enabled Syncthing doesn't starts.

**Comment by licaon-kter** [comment]
Oh well, you could test NetGuard, get the latest beta since it can load hosts files and such and report if it works for you. ;)

**Comment by stooone** [comment]
I checked out adguard, and it works with syncthing... and also in the Technical information it shows that Metered = false so I don't get it. It's true that sometimes it Syncthing works together adguard also, but in most of the times don't. And browsing through the code this was my only hope what could cause it.

**Comment by Nutomic** [comment]
@stooone Maybe you can try to step through the code, or add some debug logging?

**Comment by licaon-kter** [comment]
I confirm that "sync only on Wi-Fi" is enabled with NetGuard and it works fine.

**Comment by stooone** [comment]
I will try something in the near future.

**Comment by stooone** [comment]
Don't now what happened but now everything is fine. I'm closing this. Sorry.
