### ISSUE TITLE
Share files to Syncthing

### ISSUE THREAD

**Issue by alcor93** [syncthing/syncthing-android#561]
Hello,

It could be possible to use the application on external SD memory ? With android 6, we can change the location of the application on the external memory but the application can't start anymore.

One other thing, is it possible to have a link to the application to share / send automatically through syncthing ?

Thanks

**Comment by Nutomic** [comment]
Do you mean #87, or #29?

I changed the title so that we have seperate issues (and because we didn't have an issue for sharing yet).

**Comment by alcor93** [comment]
actually neither the one, neither the other.
First I installed the application on the main memory. Then I have changed
the location to the external memory. Syncthing is then installed on the
external memory card thanks to android 6. after that, when I launch the
application, it is always loading at it start up.
If I clear all the data of the syncthing application, and launch again the
application from external memory, I get a toast message saying in french,
not possible to create  the syncthing configuration. Please verify the log
file. and the application doesn't start.

2016-02-10 16:07 GMT+01:00 Felix Ableitner <notifications@github.com>:

**Comment by Nutomic** [comment]
That's basically #87. I changed the title there to make it more general.

**Comment by girzel** [comment]
I installed Syncthing Android pretty early on, and I would swear that for the first few months, when I went to "share" a file from some other Android app, Syncthing was in the list of apps that could "handle" the share (apologies, I don't know the proper Android terminology).

Ie, I could go in to the Gallery, select a photo, then touch the share icon, and Syncthing would be in the list. As far as I recall, choosing Syncthing would then prompt me for a Syncthing-managed folder, and picking the folder would copy the image into that folder.

This was enormously useful, but later on (I'm sorry, I don't know when) Syncthing disappeared from the list of share options.

I don't know who decides which apps appear in these Share menus, but I swear it was there before. It would be wonderful to have it back there again!

**Comment by Nutomic** [comment]
You must be confusing something, because we never had this feature.

**Comment by girzel** [comment]
Well, it wouldn't be the first time I hallucinated a computing experience, but I have a pretty clear memory of looking for the Syncthing icon in the share menu, and being surprised not to find it. Regardless! Consider this a +1 for the feature request.

**Comment by Nutomic** [comment]
Implemented in #843.
