### ISSUE TITLE
Directory won't select

### ISSUE THREAD

**Issue by frabcus** [syncthing/syncthing-android#562]
If I do the following:

1) "Create Folder" (touching + on the "Folders" tab)
2) Choose "Directory"
3) Browse to any directory
4) Touch "Select folder"
5) Goes back to the "Create Folder" page, but instead of the directory name showing, the entry is still blank just saying "Directory" in grey.

At step 2) above I get a popup "Warning: Your Android version does not allow sync to external storage devices". I've no idea what this means. Is an SDCard external or not? Anyway, doesn't matter what directory I pick, on internal or external SDCard.

My device is a new Fairphone 2 (Lollipop Android 5.1). This works fine on my previous phone Fairphone 1 (Android 4.2.2)

Can make logs if given instructions! Thanks for any help.

**Comment by frabcus** [comment]
This turns out to be a "privacy impact" setting bug - the workaround is to turn "privacy impact" back on. I think it is specific to Fairphone 2. Full details here:

https://forum.fairphone.com/t/syncthing-wont-let-me-set-directoy/13969

Also, another workaround which was good was to just use the Web GUI and type in the directory. To be honest, I quite like the Web GUI, and wouldn't mind too much if Syncthing just started in it all the time and there wasn't a main GUI...

**Comment by chrisveness** [comment]
I also had a message ‘Warning: Your Android version does not allow sync to external storage devices’ on my Nexus 5.

I took the suggestion to use the Web GUI which worked fine (didn’t bother to investigate further).

**Comment by wweich** [comment]
>I also had a message ‘Warning: Your Android version does not allow sync to external storage devices’ on my Nexus 5 running Android 6.0.1.

As the Nexus 5 does not have external storage, this message can be ignored and doesn't have anything to do with this issue.

**Comment by chrisveness** [comment]
I thought it was preventing me from adding a device, but perhaps I misunderstood... It's working ok now, anyway.
