### ISSUE TITLE
Empty files generating after deletion

### ISSUE THREAD

**Issue by lupa18** [syncthing/syncthing-android#563]
(originall posted on: https://github.com/syncthing/syncthing/issues/2675)

- Desktop version: v0.12.18, Linux (64 bit)
- Desktop version 2: idem
- Mobile version: 0.7.7

Logcat: "Retrieving logs..." (Stay there forever)

Config: [config.xml.txt](https://github.com/syncthing/syncthing-android/files/129366/config.xml.txt)

When I turn on mobile version, it generates some empty files. I delete them and appear again. 
If mobile version is offline, the other 2 dekstop versions works well, without creating empty files. 

To reproduce it,
1. let 3 instances run, 2 desktop and 1 mobile
2. Share your camera folder
3. Take some photos and let it synchronize
4. Go to desktop client and delete some photos
5. Mobile client will create them again with 0 kb size

**Comment by Nutomic** [comment]
This is a bug in Syncthing. It should be fixed [by this commit](https://github.com/syncthing/syncthing/commit/c4c6df179b5971a6c3e2f0b25990b70416ce48ac) which was in Syncthing v0.12.17, and Syncthing-Android 0.7.7. 

If you can still reproduce this, please report it in the Syncthing repo.
