### ISSUE TITLE
LG G4 sd card sync denied

### ISSUE THREAD

**Issue by rezad1393** [syncthing/syncthing-android#565]
in my LG G4 I cant choose to sync to a folder on sd card. if I add it any way I get permission denied error.

**Comment by licaon-kter** [comment]
Android version?

/duplicate of https://github.com/syncthing/syncthing-android/issues/29

**Comment by NYPD** [comment]
as I mentioned in #29 : 

> As others have pointed, creating a folder named "com.nutomic.syncthingandroid"
extSdCard/Android/data/com.nutomic.syncthingandroid

>Does allow syncthing to do its thing. I'm able to sync a large music collection under
extSdCard/Android/data/com.nutomic.syncthingandroid/Phone Music

>So at least this is an option for some perhaps.

>edit: This is on Android 5.1

This worked with my LG G4 running 5.1 and still works with the Marshmallow 6.0 update.

**Comment by rezad1393** [comment]
thanks
btw what version of g4 you have that has marshmallow?

**Comment by NYPD** [comment]
The LG H811 from T-Mobile.

**Comment by Nutomic** [comment]
Yep, same issue
