### ISSUE TITLE
Frequency of sync

### ISSUE THREAD

**Issue by fmarkos** [syncthing/syncthing-android#566]
In my Note3 cell-phone I sync 5 folders with 3 PCs. That drains the battery very fast.
I believe it would be useful to be able to set the sync interval.
e.g. sync once every 1 hour or every 10 minutes and not real time.
Maybe do this per folder? We all have some folder that we need constantly synced and others that are not that crucial.
Thanks.

**Comment by Nutomic** [comment]
Pausing individual folders isn't currently possible in Syncthing. But it would already be possible globally, or per device.

**Comment by capi** [comment]
Beware that pausing / unpausing currently results in a full index exchange. Depending on the size of synced data, this can be several MB (e.g. I am syncing about 12GB, each reconnect is about 4MB of traffic).

**Comment by Nutomic** [comment]
I just noticed that this is almost the same as #460, closing as a duplicate. Feel free to comment there about per folder settings.
