### ISSUE TITLE
New files never sync, instead *-sync-conflict* files appear zero byte long

### ISSUE THREAD

**Issue by Spiritdude** [syncthing/syncthing-android#569]
Client 1: Ubuntu 15.10, Syncthing 0.12.19
Client 2: Samsung Galaxy S2 Syncthing 0.12.19 for Android

Since upgrade to 0.12.19, on both clients, any files I place to Client 1 never makes it to Client 2, instead after 1-2 mins the files I put on Client 1 become zero-byte long and filename is *-sync-conflict* date/time:

Client 1 (Ubuntu):
1) place new file a.txt 10 bytes long
2) after 1-2 mins a-sync-conflict-2016...1.txt appears with 10 bytes length (content intact)
3) a.txt is 0 bytes length (content gone)
4) another a-sync-conflict-2016...2.txt 0 bytes length appears (content gone)

a.txt (0 bytes long)
a-sync-conflict-2016...1.txt (0 byte long)
a-sync-conflict-2016...2.txt (10 bytes long, content intact of former 'a.txt' file)

Client 2 (Android):
.a.txt.tmp (10 bytes long)
a.txt (0 bytes long)

.a.txt.tmp gets not updated to a.txt . . .  syncing stalls not reaching 100%

### Version Information
Syncthing Version: v0.12.19
OS Version: Ubuntu 15.10 & Android 2.1.2

**Comment by AudriusButkevicius** [comment]
So not sure what the 1.txt has todo with a.txt.

Regardless, you need to get syncthings logs, which will probably have issues setting permissions, or something along the lines. Make sure both sides have ignore permissoons set.

**Comment by Nutomic** [comment]
@AudriusButkevicius We set ignore permissions automatically on the Android site, and iirc it isn't needed on the other side. So that's probably not the problem.

**Comment by AudriusButkevicius** [comment]
Well there must be something in the logs, Plus you don't know if the user didn't use the web ui to add the folder.

**Comment by Nutomic** [comment]
We apply the change directly to the config after a restart, so that seems unlikely.

@Spiritdude Are you sure that you're running Android 2.1? We don't support that since a few months. Which version of syncthing-android are you running?

**Comment by Spiritdude** [comment]
@Nutomic Syncthing Android Version 0.7.8; and yes, it's Android 2.1.2 on Samsung Galaxy S2, I can't upgrade (Samsung cares nothing about 2+ yr old machines, "planned obsolescence" that is), perhaps CyanogenMod might work, but this as last resort as GPS and radio might not be supported anymore.

@AudriusButkevicius Will reply with a log excerpt.

**Comment by Spiritdude** [comment]
@AudriusButkevicius I had to restart syncthing on android so the log-file is trimmed, and let it run for 30+mins, typical log entry goes like this "SyncthingNativeCore(25326): [...] ... INFO Puller: final open /....something.tmp: invalid argument" - and checking with a file browser reveals 10+ .syncthing....tmp files which were listed in the log file residing in the shared folder on Android device.

@Nutomic from my user point of view, something has dramatically changed from pre 0.12.19 to 0.12.19 - I can't tell at which point when I upgraded on desktop or after also upgraded on Android too as it was done within 2 days time window: sync from Android to desktop worked fine, I began noticing problems when sync from Desktop to Android took forever and stalled, etc.

**Comment by licaon-kter** [comment]
@Spiritdude It's not 2+ but twice as much :) http://www.cmxlog.com/11/ -> Samsung ...

**Comment by Nutomic** [comment]
Thing is, we don't actually support Android 2 any more, so I'm not sure how you're running that version. Anyway, the problem sounds like a Syncthing problem, not specific to Android.

**Comment by Spiritdude** [comment]
A few hours Syncthing updated itself again (automatically), the version number is the same as before - but things are more stable now, it synced from Desktop/Ubuntu to Android, but on Desktop/Ubuntu it stated "Out of Sync" even it's the master, and Android should take all changes from Desktop/Ubuntu, I clicked now once "Override Changes"; I let it run and add more files to sync from Desktop/Ubuntu to Android and see how things go. I removed one stale .syncthing....tmp file which likely was incomplete from last night, before the Syncthing Android update.

Update: More "Out of Sync" files are listed at Desktop/Ubuntu, actually the new files I put in on Ubuntu/Desktop to sync to Android, as if Android reports back ... but since I marked Ubuntu/Desktop as master, why even tell me that the master is out of sync, it never is, that's the point of being a master.

**Comment by Spiritdude** [comment]
@Nutomic I don't know the details of the Syncthing core, but I noticed when I use nautilus file browser and delete a file which is synced to other clients, I end up with zero length files on Android client, to properly delete it I had to delete it on Android so it synced back on the Desktop and remove the zero length file (prior 0.12.19). When I deleted the file via CLI rm then this did not happen. The difference of nautilus delete vs CLI rm delete is, that the file in nautilus is moved into <mount-point>/.Trash-1000/*. Now, nautilus after a few days, sometimes 1-2 weeks, stops tracking actual changes in the directory, even restarting it won't resolve it and still shows outdated directory content. I use for a few hours another file browser, and then go back to nautilus, and all of the sudden the GUI shows the correct files (what I otherwise see with ls). Whether this is gvfs or inotify related I can't tell yet . . but one of them causes Syncthing to be confused on the Desktop/Ubuntu 15.10 (and earlier). Yesterday, with 0.12.19 the entire situation reminded me of the creation of the "deleted" file making its round between master/client/master again, creating an update loop confusion (who did what originally).

PS: I'm working with FUSE file system and inotify currently intensively (unrelated to Syncthing), so I'm quite deep in file system event tracking myself.

**Comment by licaon-kter** [comment]
Nautilus might just move it keeping the same inode, does Syncthing read inodes info for tracking file changes?

**Comment by Nutomic** [comment]
If you're still having this problem, please open an issue at syncthing.

**Comment by Spiritdude** [comment]
FYI: I had empty files on android & desktop, when I made desktop the MASTER then things escalated with multiple empty files and complaints desktop is out of sync, now that I updated both with 0.12.20 a few days ago and disabled MASTER on the desktop I still have empty files on android and desktop, but not more empty files reappear, just those I deleted via nautilus. I post this just for clarification, the issue can remain closed.

**Comment by Nutomic** [comment]
We can't fix this issue from the Android side. So as I said, if you still have this, please report it upstream ;)
