### ISSUE TITLE
Config import does not work

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing-android#570]

**Comment by bor** [comment]
Seems like with the last version (at least) a creation of config also doesn't work.
I've got smth like `Failed to create Syncthing config`

**Comment by bor** [comment]
But might be it's since to 'binary crashed ... signal 11'  mentioned #515 
what I have found in logs

**Comment by gerroon** [comment]
It also does not add custom discovery server. It pretends that it adds it but a restarter defaults it back to the standard one.

**Comment by gerroon** [comment]
Any word on this bug? It is a bit tedious to get everything back to normal after a new install without proper importart.

**Comment by Nutomic** [comment]
I'll look into it soon.

**Comment by wweich** [comment]
In the meantime, you can use the apk from #547 for fresh installs, to import the config and update to the current version through play store afterwards.

**Comment by Nutomic** [comment]
@calmh @AudriusButkevicius Does Syncthing store the current config to disk when it's shut down/restarted? Specifically if the config on disk is different from the current config. I suspect that would cause this problem.

**Comment by AudriusButkevicius** [comment]
Ofc it does, it can die at any point

**Comment by Nutomic** [comment]
Apparently it didn't do that before :D 

I'll adjust my import code then.
