### ISSUE TITLE
App is misspelled in Play Store: Synchting

### ISSUE THREAD

**Issue by opie4624** [syncthing/syncthing-android#572]

**Comment by Nutomic** [comment]
I can't see this. Which language do you use?

**Comment by opie4624** [comment]
This is US English. See screenshots attached.
![screenshot from 2016-02-26 19-27-01](https://cloud.githubusercontent.com/assets/6883/13370564/8979bf90-dcc0-11e5-97ed-814b2baf0517.png)
![screenshot from 2016-02-26 19-37-11](https://cloud.githubusercontent.com/assets/6883/13370565/897ed5ac-dcc0-11e5-862d-833a89c3f194.png)

**Comment by Nutomic** [comment]
Ah right. I removed the US english translation, because we already have UK english. Thanks for reporting this!
