### ISSUE TITLE
.stignore being ignored!

### ISSUE THREAD

**Issue by mrbrahman** [syncthing/syncthing-android#573]
I setup syncthing to sync my phone with laptop. I used .stignore to sync only 4 top folders (recursively) and ignore the rest.

This seemed to be working fine until now. However, today I notice that my laptop has the entire folder structure of my phone's internal storage (i.e. no files inside those folders that I setup to ignore)

I checked the "Open Log", but nothing came up. Not sure how I can find the old logs. (May be the structure was copied over before, and I noticed only today). Please let me know if there is anything I can provide to help debug.

**Comment by capi** [comment]
This seems to be an issue in `syncthing` binary itself, since the files are ignored and only the folders are replicated, it must have found the `.syncignore` file.

What comes to my mind as a possible cause is that maybe the folders are added if reported for scanning via `/rest/db/scan`. Could this be, @calmh ?

**Comment by AudriusButkevicius** [comment]
No. The only way this could happen is that the file was missing, or reported an error while opening.

**Comment by mrbrahma** [comment]
Thanks. 

"the file was missing, or reported an error while opening"

You mean the .stignore file, correct?

I checked the .stignore file after noticing this issue, and it seems to be in order. How can I find out if there was a problem opening it?

**Comment by AudriusButkevicius** [comment]
Check the logs, though I think it might not show up there.

**Comment by capi** [comment]
@AudriusButkevicius Since the files inside the folders are not there, it seems unlikely that it could not read the `.stignore`, because why would they be missing otherwise?

**Comment by AudriusButkevicius** [comment]
They are not missing, they are actually there when they should be ignored.

**Comment by capi** [comment]
Ok, then I misunderstood, because I read from the initial report, that the folders are there, but the files are not.

**Comment by mrbrahma** [comment]
Let me clarify a little and provide full details of the issue.

**Phone Setup:**

Folders Shared

1. "**My Phone**" (one share for the whole phone with `.stignore`)
Path: `/storage/emulated/0`
Shared with: Only one Linux Laptop (primarliy to serve as auto-backup of stuff)
    Contents of `.stignore`
<pre><code>
    // Sync these folders
    !/Download
    !/My Documents
    !/WhatsApp
    !/DCIM
    
    // ignore the rest
    *
</code></pre> 
2. "**My Mobile Documents**"
<br>Shared with: all my devices (2 laptops and a tablet). This is where I store docs that I need on the go<br>
Path: `/storage/emulated/0/My Mobile Documents`

Until yesterday, my Linux laptop showed only those 4 folders for the "My Phone" share. But yesterday, all of a sudden I saw the entire folder structure of my `/storage/emulated/0` on my laptop. I poked around a bunch of folders and saw there were no files in them. Of course I didn't verify this for every single folder nor did I check that all the folders from my phone were created here.

However, interestingly I did notice that the "My Mobile documents" (under `/storage/emulated/0/My Mobile Documents` on my phone) was also copied over to the "My Phone" share along with everything else, and **I found files in there**!

Also the sync status of "My Phone" showed 99% and my phone indicated that there were several files "out of sync" (even though it was not sync'ing them)

**Comment by AudriusButkevicius** [comment]
Anyways, I suspect this is due to a blip in how android deals with filesystems, such as having to do Stat calls 10 times before you are actually sure that it's not there, rather than just Stat failing.

**Comment by mrbrahma** [comment]
So for now, to get the system back in order, should I
- un-share / remove the "My Phone" share on both devices
- delete those extra folders on laptop
- share "My Phone" again

?

**Comment by AudriusButkevicius** [comment]
Ideally yes, to remove index blaot.

**Comment by Nutomic** [comment]
@mrbrahma What Android version are you running? I'm wondering if this is an oddity with an older version, or botched by a manufacturer.

**Comment by mrbrahma** [comment]
Android 5.0.2
HTC Sense 6.0

Model: HTC One M8

**Comment by mrbrahman** [comment]
I was cleaning up and restoring the folder, when I noticed that there were indeed a few loose files here and there that had got synced up.

So, it looks like (as @AudriusButkevicius mentioned) Syncthing probably did not find `.stignore` file initially, and began transferring my entire internal sd card contents. May be after a few moments, it did realize the presece of `.stignore` and stopped synching those further.

Does this indeed seem like an Android issue? Is there any fix that can be suggested to the Android dev team?

**Comment by Nutomic** [comment]
It seems pretty likely that this is a problem with Android, as it would have been reported on Linux or Windows otherwise. You could report that issue to HTC (I don't think Google takes reports for non-Nexus devices). But I'm not sure if they can do anything with this little information.

I'm gonna close this issue, because I don't think we can do anything about it.

**Comment by mrbrahman** [comment]
What amazes me is that of the 3 operating systems (Windows 8, Linux Mint, Android) that I use Syncthing (wrapper), Android is the fastest in terms of detecting changes. i.e. updates to a text file on my Android tablet are propagated within the same second to other devices. Yet, somehow Syncthing couldn't read `.stignore` before pushing files that were marked to be ignored!

Anyway, thanks for looking into this.

**Comment by Nutomic** [comment]
That's because we use inotify by default. On other platforms, you have to set it up manually (see [this repo](https://github.com/syncthing/syncthing-inotify)).
