### ISSUE TITLE
Out of Sync (.stignore further)

### ISSUE THREAD

**Issue by orlin** [syncthing/syncthing-android#574]
This issue started as several `.DS_Store` files that failed to sync to my android phone.  The Web UI said "peers who had this file went away, or the file has changed while syncing, will retry later".  I didn't use the single (master) source computer for anything (was away from it) white syncthing was syncing.  Don't know if that means Mac OS changes .DS_Store files on its own - without a user changing things by using any interface (Finder)...

Then I rediscovered `.stignore` and added `.DS_Store` to it.  This got my phone to be "in sync", but put the master source "out of sync".  That's many more `.DS_Store` files.  I'm guessing because the android recipient had them synced from before they were `.stignore`d.  Does the .stignore get synced / taken into account?

Also, are we missing a global `.stignore` - basically when I sync with a mac I'd like all folders to ignore `.DS_Store` files, without having to explicitly add each to every `.stignore` file.

**Comment by AudriusButkevicius** [comment]
Yes, .DS_Store can change for example when your file system decides to reindex, which is not in your control usually.

You need to add .DS_Store on both sides, turn !BOTH! sides off, and turn them back on.

**Comment by Nutomic** [comment]
Closing this as invalid because it's not an Android specific issue. Check the Syncthing issue tracker for the global ignores issue ;)
