### ISSUE TITLE
Option to start directly into Web GUI

### ISSUE THREAD

**Issue by unode** [syncthing/syncthing-android#578]
Would it be possible to add a setting that causes syncthing to skip the android interface and start directly into the web GUI?

**Comment by Nutomic** [comment]
For what purpose exactly?

**Comment by Unode** [comment]
There's always a certain lag between features that get implemented in the Web GUI and those made available in the android UI. There's also some which are only available in the android UI so this becomes a matter of preference and personal usage habits.

Given that whenever I'm on the computer the interface I usually interact with is the web GUI I tend to be more familiar with it. When I'm on android I often find myself starting syncthing-android and jumping straight to the web GUI. Having the option to do this by default would be nice.

It could perhaps also save some startup time by not initializing the android UI at boot but this is not part of the request.

**Comment by Nutomic** [comment]
Yeah I guess that makes sense.

**Comment by actinmyosin** [comment]
I like the idea of making the Web GUI the default UI, especially if it can be done without major feature or usability compromises. It offers some benefits from a cross device and cross platform perspective. I believe it would have made #591 an annoyance or non-issue rather than a show stopper. It may also assist those interested in using legacy Android devices as in #541 and #564.

**Comment by Nutomic** [comment]
#591 is fixed in 0.7.12. And dropping support for Android 2.x affected less than 1% of our users. 

On the other hand, the native UI makes for a much better user experience (eg the folder picker). So I don't think we should switch to the web GUI as default.

**Comment by thunderstorm99** [comment]
@Unode you could always use a bookmark for 127.0.0.1:8384 in your favorite mobile browser (if synching is running in the background).

**Comment by Unode** [comment]
@thunderstorm99 that doesn't always work as syncthing is often stopped when not in the foreground. That's what you get when apps are fighting for memory :disappointed: .

**Comment by LegoChicken** [comment]
Is there any update on this? I would like to run a rooted Nook Simple Touch.

**Comment by AudriusButkevicius** [comment]
This doesn't make much sense. You can just run vanilla syncthing if you do not intend to run the app.

**Comment by LegoChicken** [comment]
My understanding from #541 and #564 is that Syncthing won't run on the Nook due to it running Android 2.1. I would be prefer to use the GUI, but in the absence of that the Web GUI would do.

**Comment by AudriusButkevicius** [comment]
This would not make it work, this would just drop into web ui instead of the android ui on start.
Your best bet is to run vanilla syncthing as a process in the background and access web ui by typing in the url manually, as I don't think 2.1 will ever be supported.

**Comment by unode** [comment]
@AudriusButkevicius were you referring to the issue as initially described?
I don't see an official vanilla syncthing for andoid. Also unsure about how this would be launched on a non-rooted device...

The initial request's aim is to start Syncthing and go straight to the Web-UI, possibly bypassing the GUI (and therefore reducing start time and a little memory usage).
This would be done based on user settings. Making Web-UI the default is not a goal.

**Comment by AudriusButkevicius** [comment]
The android app just runs a linux syncthing binary behind the scenes (more or less), and I am referring to @LegoChicken's request.

**Comment by LegoChicken** [comment]
My goal (which is the same as closed #541) is to run on Nook Simple Touch (same as Nook Simple Touch Glowlight in #541, but without the light). This would enable wireless synchronisation from my Calibre library to the Nook.

**Comment by unode** [comment]
@LegoChicken would you mind opening another issue on it? Your goal is unrelated to this one as it has to do with compatibility with older android versions.

**Comment by LegoChicken** [comment]
OK. Is possible or desirable to reopen #541?

**Comment by AudriusButkevicius** [comment]
There is no point opening another issue, it was decided that no effort will be spent on that in #541

**Comment by LegoChicken** [comment]
That's a shame. Any suggestions for another sync tool which will run on Android 2.1 and Linux?

**Comment by AudriusButkevicius** [comment]
Extracting syncthing (.so) binary from the app and running manually from the command line on the device might work, but it's quite involved and you have to know what you are doing.

**Comment by LegoChicken** [comment]
Looking through the releases it appears https://github.com/syncthing/syncthing-android/releases/tag/0.7.0-beta1 raised it to Honeycomb minimum. I don't know if before that it would support 2.1 and whether it would still work with the latest client on other machines.

**Comment by AudriusButkevicius** [comment]
So I am going to stop replying as we are polluting issue with things that are off topic. Forum is there for a reason.

**Comment by unode** [comment]
@Nutomic thanks!
