### ISSUE TITLE
It should be possible to add a folder to Syncthing from a file manager

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing-android#586]
Sharing a folder in a file manager should show a Syncthing item, which would add that folder as a new share to Syncthing (bringing up the add folder activity).

Sharing folders is supported eg by Total Commander.

As suggested in [this forum thread](https://forum.syncthing.net/t/first-time-user-usability-review/6974/4).

**Comment by imsodin** [comment]
I think #843 did this.

**Comment by Nutomic** [comment]
No, that allows adding files to an existing Syncthing folder. This issue is for creating a new Syncthing folder from a file manager.

**Comment by Nutomic** [comment]
Looks like most file managers don't even allow sharing a folder.
