### ISSUE TITLE
Run condition to respect Android's "Auto-Sync" quick toggle

### ISSUE THREAD

**Issue by kluppy** [syncthing/syncthing-android#588]
Add an option to link Syncthing to the global Auto-Sync Setting as per [Coupling syncing to Android’s sync setting](https://forum.syncthing.net/t/coupling-syncing-to-androids-sync-setting/6987/9)

**Comment by Magissia** [comment]
It would be useful indeed, if you have the courage, we could have a sync per share.

**Comment by licaon-kter** [comment]
@Nutomic Thanks

**Comment by Nutomic** [comment]
I've reverted this commit, as #727 shows, there's more work required for this (like adding an option, and/or showing the reason syncthing is stopped).

**Comment by acornsirup** [comment]
The running conditions are now managed in a separate menu item, would it be difficult to add another switch enabling this useful feature? Cheers and thanks.

**Comment by Nutomic** [comment]
Not really that difficult. Contributions are welcome!

**Comment by acornsirup** [comment]
Awesome! Unfortunately I can't code. I wish I were able to contribute better.
