### ISSUE TITLE
Support Tor connectivity

### ISSUE THREAD

**Issue by steelman** [syncthing/syncthing-android#589]
There are three parts

1. Support connecting via SOCKS5 proxy. Not so Tor specific and may be useful anyway.

2. Support .onion names as described in https://tools.ietf.org/html/rfc7686

3. Provide a single checkbox labeled "Use Tor" that: a) configures socks5 proxy at localhost:9050, b) disables connecting to any non-.onion adresses.

Tor solves two problems both of which apply IMHO to Syncthing more or less. First, Tor provides hides communication from evasdroppers. Second, hidden services are quite convinient way to bypass NAT.

I suppose some of the above tasks apply to the syncthing engine rather than android app but as I am unfamiliar with syncthing internals please allow me to report them here.

**Comment by Nutomic** [comment]
Proxies are already supported by Syncthing, via the `all_proxy=socks5://ip:port` environment variable.

I'm won't implement this myself, but contributions are welcome!

**Comment by steelman** [comment]
I am afraid I won't be able to contribute. I know next to nothing about Android development. Please let this issue stay open.

**Comment by Nutomic** [comment]
Of course we'll keep it open ;)

**Comment by gerroon** [comment]
Can this "all_proxy=socks5://ip:port environment variable" be used in the app at the moment in an accesible way?

**Comment by Nutomic** [comment]
No, but it would be pretty easy to add support for that, if someone wants to make a PR.

**Comment by bashrc** [comment]
I am also wondering whether I can get the syncthing android app to go through Tor (Orbot).

**Comment by Nutomic** [comment]
I'm not interested in implementing this myself, but let me know if you want to work on this. 

Implementing the socks proxy as described in the OP would be pretty trivial, and I guess the other things just need some testing and playing around with it.

**Comment by Nutomic** [comment]
I just tried to implement this with the `all_proxy env var, but Syncthing will bypass the proxy if Tor isn't running. I opened an issue here: syncthing/syncthing#3006

Support for onion addresses has to be implemented in Syncthing directly. Can you open an issue for that in the [Syncthing repo](https://github.com/syncthing/syncthing/issues)?

**Comment by AudriusButkevicius** [comment]
Resolving addresses should be done by the proxy, so no need for a ticket.

**Comment by steelman** [comment]
Thanks.
