### ISSUE TITLE
Deletions are not propagated

### ISSUE THREAD

**Issue by Petef** [syncthing/syncthing-android#592]
I have found that deletions are never propagated, making it impossible to delete files that are synced.
If I delete a file while Syncthing is running, the file initially is removed, and that is mirrored by the other synced device. Within a few moments the file reappears on both devices with no content (sparse?).
Even when I manually delete a file from both devices with Syncthing closed, when Syncthing is restarted the deleted file reappears on both devices, again as an empty file.
The only way I have found to delete a file is:
1) Remove the containing folder from Syncthing on both devices.
2) Close Syncthing.
3) Delete the files from both devices.
4) Set-up the folder again in Syncthing from scratch.

Synching is between 2 identical Android devices.
Neither device is Master, though the same behaviour occurs when one is Master.
Simple set-up with no ignores etc.
Android 4.2.2

**Comment by AudriusButkevicius** [comment]
Is one of the devices using a network based filesystem? Whats the size of thr empty file?

**Comment by Petef** [comment]
I'm not familiar with network based file system? They both use standard Android file system.
File size is reported as 0 Bytes, time-stamped with identical date/time (of recreation?) on both devices.

**Comment by Nutomic** [comment]
Can you retry this, but trigger a rescan in the web GUI after you delete the files? Do you get the same behaviour in that case?

**Comment by Petef** [comment]
The short answer is it makes no difference.
I tried deleting 4 files from Folder BOOKMARKS on device2, while watching the web GUI on device1, The Global State and Local State changed from 8 to 4 Items and back to 8 Items in a few seconds.  Doing a rescan made no difference. All 4 files had 0 bytes, and new timestamp.

As part of this test, I also tried deleting a file in another synced folder, and this worked. The first time I've seen this. Could it be that some folders are affected and others not? Possible corruption?

What does Reset Database do in Settings? Is it worth trying?

**Comment by Petef** [comment]
To be clear: when I say it worked in the 2nd test, I mean without doing a Rescan.

**Comment by AudriusButkevicius** [comment]
It sounds either like a race condition (two things trying to sync the same thing), or some sort of network based filesystem being used causing sparse issues. Are both devices android?

**Comment by AudriusButkevicius** [comment]
So I suggest we close this and move this to the forum, as its definately something funky with the users setup and not an actual bug, especially as it happens only in a particular folder.

**Comment by Petef** [comment]
Both identical Android tablets running identical system software. Android 4.2.2
Both devices use local files only.
Not rooted.
The more I look, the more evidence there is of this behaviour, as my Syncing folders are littered with 0 byte files.
Although I believe this behaviour predates the update to v0.7.11, there have been definite issues with this version. Syncthing now crashes with great regularity, whereas I never had a crash on previous versions.

**Comment by Petef** [comment]
As far as I am aware this behaviour affects ALL folders, certainly several, not just 1.

**Comment by Petef** [comment]
I've done further tests and have been unable to replicate deletion being propagated correctly in any folder, so this behaviour is not folder dependent.
Also, I have found that when a file is deleted in a Master Folder, this deletion is not propagated to the other device, but neither is an empty file recreated in the Master Folder.

**Comment by Nutomic** [comment]
This seems to be a problem with Syncthing. Please open an issue there ;)
