### ISSUE TITLE
Crash with error code 9

### ISSUE THREAD

**Issue by licaon-kter** [syncthing/syncthing-android#595]
Android 5.1.1 w/ 0.7.12 got a bunch of crashes:

```
E AndroidRuntime: FATAL EXCEPTION: Thread-1277
E AndroidRuntime: Process: com.nutomic.syncthingandroid, PID: 11789
E AndroidRuntime: java.lang.RuntimeException: Syncthing binary crashed with error code 9, output:
E AndroidRuntime: 
E AndroidRuntime:        at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable.run(SyncthingRunnable.java:147)
E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)

```

**Comment by Nutomic** [comment]
The error output from Syncthing should be included with this exception, but for some reason it's missing. The logging should work in the next version. Alternatively, you can check for any errors with `adb logcat -s SyncthingNativeCode:v`.

**Comment by licaon-kter** [comment]
There is nothing there.

**Comment by Nutomic** [comment]
But the normal Syncthing logs (device ID etc) are shown with that command? What are you doing when you get that crash?

**Comment by licaon-kter** [comment]
Nothing special, my network connection might have been flipping on/off.

**Comment by Nutomic** [comment]
Is there anything interesting in `adb logcat -s SyncthingNativeCode:v SyncthingRunnable:v SyncthingRunnableIoNice:v SyncthingRunnableKill:v`, or in `adb logcat -s *:W`?

**Comment by licaon-kter** [comment]
There is nothing there now since the log only shows errors for (those) past events.
I'll keep an eye on it though.

**Comment by Nutomic** [comment]
Ah I thought you're getting that crash all the time. There's nothing we can do without logs.

**Comment by licaon-kter** [comment]
Getting this on another device, with `background+only sync on this Wi-Fi`, when Wi-Fi is turned off (but not always) it will crash like this.
I'll see if I can get some logs out.

**Comment by Nutomic** [comment]
I'm getting some logs from Google Play now with error code 9, most have the error "FATAL: Cannot open database: resource temporarily unavailable - Is another copy of Syncthing already running?". But I'm not sure how that happens.

**Comment by licaon-kter** [comment]
Once the selected Wi-Fi in turned off syncthing is killed, maybe here lies the answer.

**Comment by licaon-kter** [comment]
So I updated the other device to 0.7.13:

```
E/AndroidRuntime(31582): FATAL EXCEPTION: Thread-104458
E/AndroidRuntime(31582): Process: com.nutomic.syncthingandroid, PID: 31582
E/AndroidRuntime(31582): java.lang.RuntimeException: Syncthing binary crashed with error code 9, output:
E/AndroidRuntime(31582): [PFLDD] 19:57:06 INFO: syncthing v0.12.21 "Beryllium Bedbug" (go1.6 linux-arm) unknown-user@android.syncthing.net 2016-03-23 08:26:04 UTC
E/AndroidRuntime(31582): [PFLDD] 19:57:06 INFO: My ID: xxxxxx
E/AndroidRuntime(31582): [PFLDD] 19:57:07 INFO: Single thread hash performance is ~37 MB/s
E/AndroidRuntime(31582): [PFLDD] 19:57:09 OK: Ready to synchronize share1 (read only; no external updates accepted)
E/AndroidRuntime(31582): [PFLDD] 19:57:09 OK: Ready to synchronize share2 (read only; no external updates accepted)
E/AndroidRuntime(31582): 
E/AndroidRuntime(31582):        at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable.run(SyncthingRunnable.java:148)
E/AndroidRuntime(31582):        at java.lang.Thread.run(Thread.java:818)
```

And this goes on and on for each share.

Also crashes have no pattern, Wi-Fi was on all the time yet it was crashing-restarting-crashing, on and on.

**Comment by AudriusButkevicius** [comment]
Are you running some magic sandbox software or something?
The [PFLDD] changing implies that files we generate get removed.

Also, it seems it's not the full log.

**Comment by licaon-kter** [comment]
Magic? Really? Nope, plain Xperia 5.1.1 no-root stock (albeit I can confirm this with a rooted device too, see OP)

Full log as per open log->Android log (also confirmed by logcat via root as per OP)

**Comment by plittlefield** [comment]
Same for me, crashing several times a day. It's been fine for months.

Syncthing Android (0.12.21)
CyanogenMod 13 (cm-13-20160407-NIGHLY)
LG Google Nexus 5 (hammerhead)

**Comment by FlashSystems** [comment]
Same Problem here. Crashes every few minutes to half an hour.
Syncthing for Android Version 0.7.13
Syncthing Version 0.12.21.
Android Device is a Nexus 4 with Android 5.1.1 from Google.
Syncthing Server is 0.12.21 as well.

```
E/AndroidRuntime(21978): FATAL EXCEPTION: Thread-5039
E/AndroidRuntime(21978): Process: com.nutomic.syncthingandroid, PID: 21978
E/AndroidRuntime(21978): java.lang.RuntimeException: Syncthing binary crashed with error code 9, output:
E/AndroidRuntime(21978): [M4HDP] 22:54:04 INFO: syncthing v0.12.21 "Beryllium Bedbug" (go1.6 linux-arm) unknown-user@android.syncthing.net 2016-03-23 08:26:04 UTC
E/AndroidRuntime(21978): [M4HDP] 22:54:04 INFO: My ID: M4HDPAP-QPWHVKX-PUGSBO4-GVYHFXK-LNEUXG4-UKQRZRG-W6QFXFB-J6ZMDQM
E/AndroidRuntime(21978): [M4HDP] 22:54:04 INFO: Single thread hash performance is ~14 MB/s
E/AndroidRuntime(21978): 
E/AndroidRuntime(21978): 	at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable.run(SyncthingRunnable.java:148)
E/AndroidRuntime(21978): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by plittlefield** [comment]
Still crashing. I have stopped reporting it now. I have updated my Android to latest NIGHTLY.

**Comment by Nutomic** [comment]
Yeah I haven't made a new release yet.

**Comment by plittlefield** [comment]
OK, I'll be patient :-)

**Comment by Catfriend1** [comment]
Dito. Got a reproducer. It happens when syncthing is shutting down too fast after it just came up.

>
(Getting this on another device, with background+only sync on this Wi-Fi, when Wi-Fi is turned off (but not always) it will crash like this.)
