### ISSUE TITLE
option to 'only sync when battery is above X%'

### ISSUE THREAD

**Issue by actinmyosin** [syncthing/syncthing-android#602]
This is a feature request for an option to limit syncing when the battery is below a configurable percentage. An 'only sync when battery is above X%' option would make a good companion to the 'only sync when charging' and 'only sync on wifi' options.

Use cases:
1.) phone battery is down to 10%. Owner begins charging, but doesn't want to sync until charge is above 50%. This will make charging to 50% go faster (by initially not increasing power consumption).

2.) phone is not charging; owner is fine with syncing while on battery, as long as battery is more than 50% full.

**Comment by capi** [comment]
From implementation side, this would work similar to the restriction to WiFi etc. So it can be done. Question is, do we really need to handle the case "below x% and on power" or do we always sync on power.

**Comment by Nutomic** [comment]
I agree this feature makes sense. However, it's not clear how this should work in combination with the other settings. Right now, we use AND for the sync settings, so using OR would be inconsistent.

Does anyone know how other apps handle this kind of setting? Any suggestions to make it easy to understand for users?

**Comment by AudriusButkevicius** [comment]
Just allow the app to be controlled via tasker, and people can decide if they want ands or ors, etc.

**Comment by sqrt-1764** [comment]
See pull request #599 ;-)
My tests look promising.

**Comment by Nutomic** [comment]
@AudriusButkevicius That's a good point. I'm just not sure where we should draw the line between "use tasker" and "we should integrate that".

**Comment by actinmyosin** [comment]
Setting up the UI options as follows should handle all the cases already mentioned, and should keep them consistent.
Sync Control Options:
-allow sync while on WiFi (off/WiFi list/any WiFi) (radiobox, default any Wifi) (var wificheck=any)
-allow sync while on mobile data (off/allowed) (radiobox, default off) (var mobiledata=off)
-allow sync while on battery, if battery is above X% (slider, default 50%) (var batteryminimumwhileonbattery=50)
-allow sync while charging, if battery is above X% (slider, default 15%) (var batteryminimumwhilecharging=15)
-allow sync while in batterysaver mode (radiobox, default off) (var syncduringbatterysaver=off)

---

Pseudocode:

```
//subcheck 1
Is syncing allowed via current data path? (Return T or F)
 IF (connected to wifi AND current wifi is an allowed wifi network), Return T
 ELSE
 IF (connected to mobiledata AND mobiledata=allowed), Return T
 ELSE
 Return F

//subcheck 2
Is syncing allowed in the current power state? (Return T or F)
 IF (powersource=charging AND current battery % > batteryminimumwhilecharging), Return T
 ELSE
 IF (syncduringbatterysaver=off AND batterysaver mode is enabled), Return F
 ELSE
 IF (powersource=battery AND current battery % > batteryminimumwhileonbattery), Return T
 ELSE
 Return F

//main check
Is syncing currently allowed? (Return T or F)
 Is syncing allowed via current data path? (Return T or F)
 AND
 Is syncing allowed in the current power state? (Return T or F)
```


If there is an app UI, I think it is preferable to have these features native to the app. Strictly speaking, all the power control options in Syncthing could be handled by externally, including killing Syncthing in battery saver mode. If Syncthing Android only offers the native Syncthing Web UI, maybe these features aren't needed internally.

**Comment by Nutomic** [comment]
That sounds really complicated for the user. And it would still not be clear if those options are chained with AND or with OR. 

I'd rather keep it simple, and have people use external apps if they want more advanced options. Battery saver should be supported though, and I don't think we need an option there.

**Comment by actinmyosin** [comment]
I think my text paragraph makes it sound more complicated than it really is. There are 5 options, all of which have proposed sensible defaults that most users won't need to touch. Three are new options.

On AND/OR...it needs both to remain consistent. In the proposal the user can pick the combinations where syncing is allowed. From a user perspective, the user is saying "I allow syncing in these conditions."

The pseudocode indicates suggested chaining via IF ELSE statements that separately OR together the various related power conditions, and separately OR together related data conditions. These data and power categories are in turn ANDed together to know whether syncing is permitted to run now.

**Comment by Nutomic** [comment]
You can now use Tasker or similar to get this functionality. For this reason, I'm inclined to say this is out of scope.

**Comment by capi** [comment]
Almost all our automated syncing settings can now be automated via Tasker. Doesn't mean that all people have it and/or are able to configure it properly. Battery consumption is still one of the main complaints of this app, so I could imagine having such an option as proposed to be a sensible option to be implemented directly in the application.

**Comment by Nutomic** [comment]
Okay that's true.

**Comment by HaleTom** [comment]
To me this is a critical feature. Currently to reduce battery drain I have `Sync only when charging` turned on.

I'd love to be able to:

* sync on high battery only
* disable sync if charging and battery is below 20%

To keep the options being boolean `AND`ed together, how about:

* When charging, require battery above X%
* When on battery, require battery above Y%

I'd suggest sliders for each.

**Comment by capi** [comment]
@HaleTom Maybe integration with Tasker is a valid workaround for you to really customize when Syncthing is running?

**Comment by HaleTom** [comment]
1. If I disable Syncthing with Tasker, will it need to rescan when it starts again?
2. Would the behaviour be different if Syncthing shut itself down?
3. Is there a guide on how to do this with Tasker? (It seems to be the go-to workaround)

**Comment by capi** [comment]
1. Yes, in the sense that it does a scan for changed files in the directory, but re-hashing only those that have changed meta-data (mtime, size).
2. No, behavior is the same.
3. https://github.com/syncthing/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents

**Comment by Catfriend1** [comment]
I agree this should be done by Tasker. An app with high battery consumption does not make sense to drain the battery - lets say - until 20% when not charging and then leave the phone in this state. Personally, I would not like to go out of the house suddenly and seeing my phone has just 20% left because syncthing was on too long.
Sidenote - If syncthing is configured properly, it can well save battery.
