### ISSUE TITLE
Crash in Log press back arrow to go back to Settings

### ISSUE THREAD

**Issue by licaon-kter** [syncthing/syncthing-android#604]
This was in the Log->Android Log, not sure why or when:
```
E/AndroidRuntime(17900): FATAL EXCEPTION: main
E/AndroidRuntime(17900): Process: com.nutomic.syncthingandroid, PID: 17900
E/AndroidRuntime(17900): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
E/AndroidRuntime(17900):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
E/AndroidRuntime(17900):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
E/AndroidRuntime(17900):        at android.app.ActivityThread.access$800(ActivityThread.java:156)
E/AndroidRuntime(17900):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
E/AndroidRuntime(17900):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(17900):        at android.os.Looper.loop(Looper.java:211)
E/AndroidRuntime(17900):        at android.app.ActivityThread.main(ActivityThread.java:5373)
E/AndroidRuntime(17900):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17900):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(17900):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
E/AndroidRuntime(17900):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
E/AndroidRuntime(17900): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
E/AndroidRuntime(17900):        at com.nutomic.syncthingandroid.activities.SettingsActivity.onCreate(SettingsActivity.java:41)
E/AndroidRuntime(17900):        at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime(17900):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime(17900):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
E/AndroidRuntime(17900):        ... 10 more
```

**Comment by Nutomic** [comment]
That's pretty much an error that should never happen. 

SettingsActivity needs to have a parameter that tells it which fragment should be used (device settings / folder settings /app settings). That parameter is missing. 

Were you using the actionbar back button in the logs activity? Or somewhere else in the app settings?

**Comment by licaon-kter** [comment]
Don't know, just found it while looking for https://github.com/syncthing/syncthing-android/issues/595
After 0.7.11 it's crashing all the time.

**Comment by gerroon** [comment]
This app constantly crashes on 5 of my devices. I have devices run 4.4x and 5x from various brands. Sometimes it does not crash for a while sometimes it crashes after couple minutes. Whatever you guys did in recent couple versions in the .7x braches made this app super duper unstable. I think that the memory use went up with this device and in return android is killing the binary otherwise we cant explain the irregular crashes. The crashes happen when the app is running in the bg or devices are sleeping.

**Comment by licaon-kter** [comment]
Look at the logs in the app, I bet you see https://github.com/syncthing/syncthing-android/issues/595 and not this.

**Comment by Nutomic** [comment]
@gerroon We are now reporting some crashes that were silently ignored before. Can you post a log please, so that we can fix it?

**Comment by gerroon** [comment]
@Nutomic 

I will try however it is a bit hard to catch these because it is so irregular and running adb while trying to use the tablets is a bit hard

**Comment by licaon-kter** [comment]
In app->Open Log->Android Log shows nothing of use?

**Comment by licaon-kter** [comment]
Ok, got it, happens all the time, 0.7.16 F-Droid, Android 5.1.1
Settings->Open Log-> press back arrow to go back->crash: https://gist.github.com/licaon-kter/28a420967252442f3decdb93b7167131
