### ISSUE TITLE
Anonymous usage report keeps poping up

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing-android#606]
Press yes, get asked the same question again. Didn't go away until I killed and restarted the app. Needs to reload config maybe?

**Comment by Nutomic** [comment]
Ah right, that seems to happen if you don't choose to restart immediately.

**Comment by AudriusButkevicius** [comment]
Yes

**Comment by Nutomic** [comment]
Looks like it's actually your fault, because you didn't adjust the value for "usage report accepted in [your commit](https://github.com/syncthing/syncthing-android/commit/6deb304b020cdab85dbd23dff27df809342163d6) :p :p :p

**Comment by AudriusButkevicius** [comment]
You should have a int constant "Accepted" somewhere I guess.

**Comment by Nutomic** [comment]
Would the API actually ever return 1 for usage reporting in current versions? Or only -1, 0, 2?

**Comment by AudriusButkevicius** [comment]
I think it could return 1 if you accepted previous but not current one.
