### ISSUE TITLE
Feature request: option to always run Syncthing while app is foregrounded

### ISSUE THREAD

**Issue by DarwinAwardWinner** [syncthing/syncthing-android#612]
Most of the time, I only want Syncthing running when my phone/tablet is on wifi and charging. However, when I'm in the process of configuring it, I want it to run no matter what. It would be nice if there was an option to always run Syncthing while the Syncthing app is in the foreground. In other words, an option to prevent the "Sync only when charging" and "Sync only on wifi" settings from taking effect while the app is in the foreground. Or perhaps run the app but pause all Syncing, (equivalent to pressing "pause" on every device in the web GUI). This would allow me to configure Syncthing without having to plug my phone in first or change the settings and then change them back afterward.

**Comment by Nutomic** [comment]
Yeah this only really makes sense when we pause Syncthing (see #254). With the current implementation, there will be a full index exchange whenever Syncthing is started, and it will start to sync files.

**Comment by Catfriend1** [comment]
Solved by PR #1189 . Closed.
