### ISSUE TITLE
Multiple notifications for already shared folders

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing-android#615]
I am doing a three-way sync between a Windows machine, the aforementioned Linux laptop, and an Android phone running Lollipop. The Windows - Linux bit works fine. It's the Android bit that's a problem.

The problem is this. Syncing the other two devices is taking forever - it seems stuck - and this may be connected to the fact that I keep get notifications on the Android phone that seem to be requests to share folders. I say 'seem' because the text in the notifications gets truncated (it can't all fit in the notification rectangle; someone else has, just now, been kind enough to file that as a separate bug) (at https://github.com/syncthing/syncthing-android/issues/614). When I open the notifications, each seems like a request to share folders I have shared already.

I can provide further information if needed.

**Comment by wweich** [comment]
Are you sure, that you shared the folder with the other two devices on Android?
Go to the folder settings in the Syncthing Android App and check if the checkboxes / toggles for the devices are set.

**Comment by ACinnamonUserInUK** [comment]
Ah. That was the problem - although I do think that the application could make such things clearer. Thanks. Everything seems to work now, which is good!
