### ISSUE TITLE
Relay Option missing

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing-android#616]
Hi,

Thanks for syncthing-android. Very awesome!

I notice that some config options are not available in the GUI. The ones I noticed so far:

 * re-scan interval
 * relaying

The rescan interval would be nice to have, especially as the default is quite high (72 hours IIRC).

Thanks

**Comment by wweich** [comment]
As the Syncthing Android App uses inotify, there is no need for rescan. _That's also why it is set so high._

**Comment by vext01** [comment]
Ah! I see. Perfect.

Perhaps you should gray out this option in the web gui?

**Comment by Nutomic** [comment]
I don't think graying out the option is worth the trouble (we'd have to figure out a way to tell Syncthing that inotify is running).

By relaying, you mean the setting for relay servers?

**Comment by vext01** [comment]
Yeah. I've never used relaying, but I just noticed the missing option.

Thanks

**Comment by Nutomic** [comment]
The seperate relaying option was removed in v0.13, so this is obsolete.

**Comment by AudriusButkevicius** [comment]
It hasn't, there is still a checkbox whicb was readded just before the release.

**Comment by Nutomic** [comment]
Ah right, we're still missing that.
