### ISSUE TITLE
Add Folder notification allows adding duplicate Folder

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing-android#617]
Hi,

I set up syncing to my phone from my existing syncthing nodes. When I added the phone to the first node, an android notification ("xxx want to share the folder yyy" ) guided me though setting up the share. This is a nice touch.

However, when I added the phone to the second node, I got the same notification and guided setup screen. Afterwards, I had two conflicting folders.

I think the second notification should just guide the user through adding the new node to the existing folder?

**Comment by gerroon** [comment]
Yeah I just hit this issue :( It told me that such and such device wanted to share a folder with me. I went ahead and added the share without realizing that thata share wass already there before ;(

**Comment by xhabih** [comment]
Same problem here.
