### ISSUE TITLE
Other donation methods

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing-android#618]
To show my appreciation for this project, I would like to donate some money, but I don't have a bitcoin account.

Can I donate via another method? Paypal/stripe?

Thanks

**Comment by wweich** [comment]
Stripe donation is already possible: https://syncthing.net#donate "By Card"

**Comment by vext01** [comment]
OK, I already donated there. I wasn't sure if any of that would filter down to the android version.

Cheers!
