### ISSUE TITLE
Syncthing Linux to/from Android Extremely Slow

### ISSUE THREAD

**Issue by justinzane** [syncthing/syncthing-android#619]
This is the result after over 24 hours as shown by syncthing on the Linux Laptop and confirmed on the Android device:

```
 Download Rate 	0 B/s (203 MiB)
 Upload Rate 	0 B/s (165 MiB)
 Local State (Total) 	175 items, ~603 MiB
 RAM Utilization 	98.2 MiB
 CPU Utilization 	0.033%
 Discovery 	4/8
 Relays 	1/1
 Uptime 	1d 7m
 Version 	v0.12.22, Linux (64 bit
```
```
 Download Rate 	0 B/s (7.06 MiB)
 Upload Rate 	0 B/s (5.93 MiB)
Address 	192.168.0.67:39744
 Version 	v0.12.20
 Folders 	docs, music, pics, video
```

During this period, about 21 hours were spend with both hosts on the same WLAN and both able to send/rcv data at speeds limited by disk IO or 802.11n bandwidth. For the rest of the time, the Android device was in an area with limited 2G (EDGE) data service. It seemed that during the short periods with 2G data, syncthing was actually transferring at a similar rate to the WLAN!

During this period, the Android had the "experimental" "Keep CPU Awake = True" option set and the device itself set to "Performance" in the battery settings. At no point did I see that syncthing drew more energy than that drawn by cell standby.

**Comment by AudriusButkevicius** [comment]
Check if you have rate limiting enabled and wethet you are connected directly rather than via a relay.

**Comment by XDjackieXD** [comment]
I have the same problem since upgrading to Marshmallow (CM13) along with some other problems (wifi startup criteria and background worker not working correctly....)

**Comment by justinzane** [comment]
The only way to fix the slowness was to setup IPv6 on the Linux sync partner. Because I've got a crappy ISP, I've just skipped IPv6 on my internal LAN since it cannot leave without tunnelling. Apparently Syncthing requires IPv6 in order to maintain a decent transfer rate. 

Transfer over mobile data has not been tested simply because I rarely get anything faster than EDGE data rates here in rural northern CA, US. 

 __________________________________________________________________ 
/                                                                  \
|                       Justin Zane Chudgar                        |
| http://www.justinzane.com                          539-921-0738  |
|                                                                  |
| The ASCIIphant says:                                             |
|                                                                  |
| I got this powdered water -- now I don't know what to add.       |
|                                                                  |
\ -- Steven Wright                                                 /
 ------------------------------------------------------------------ 
 \     /\  ___  /\
  \   // \/   \/ \\
     ((    O O    ))
      \\ /     \ //
       \/  | |  \/ 
        |  | |  |  
        |  | |  |  
        |   o   |  
        | |   | |  
        |m|   |m|

**Comment by AudriusButkevicius** [comment]
Which implies you were connected via a relay.

**Comment by RinCat** [comment]
I have the same issue on Android version, even if using IPV6.
But on relay it has a normal speed.
Syncthing version 0.14.9 with Android 7.1.1.
The speed is only a few kb/s.

**Comment by nikel123** [comment]
this could be due some issues with local ipv6. It helped for me to used static ipv4 address for daemon on the server and specify it for the device on the android. Instead of 120 Kb/s upload i have now 5Mb/s
