### ISSUE TITLE
"Failed Uploads" when paused should be rather called "Paused Uploads"

### ISSUE THREAD

**Issue by adi-dev** [syncthing/syncthing-android#624]
It's very confusing and disturbing to see "Upload Failed" in notification area while it's been only paused due to no WiFi connection.

**Comment by Nutomic** [comment]
Which notification area do you mean exactly? Can you post a screenshot?

**Comment by adi-dev** [comment]
It's embarrassing, this comment should be on another git, please accept my apology.
