### ISSUE TITLE
ST crashing Android?

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-android#626]
Hi

Has there been changes that might affect the way the cpu handles processes or memory related issues in the latest version since the previous release one? My tablet heats up a bit while St is on.  I got 3 hard reboot while Syncthing was running in the background and I am scared to open one more time because I do not want to risk corrupting my sd card. 

Just wondering

thanks

**Comment by licaon-kter** [comment]
Logcat? Does not crash when running in foreground?

**Comment by Nutomic** [comment]
If your phone crashes because of an app, there's something wrong with your Android. I don't think there were any relevant changes either.

**Comment by gerroon** [comment]
Does ST keep logs between app reboots? 

It crashes only when ST is using alot of cpu. I tried couple other cpu intensive backup apps and they do not hard reset my tablet.

**Comment by licaon-kter** [comment]
> Does ST keep logs between app reboots?
Get ADB: http://forum.xda-developers.com/showthread.php?p=48915118#post48915118
Enable ADB on device: https://developer.android.com/tools/help/adb.html#Enabling
Connect to a PC via USB.
Run in a command line:
* `adb shell`
* `logcat -v threadtime`

**Comment by gerroon** [comment]
@licaon-kter 

The device hard resets meaning it restarts. I can grab the log while it is running, but I thought that Android resets the logs after a restart

**Comment by Nutomic** [comment]
If you record the logs from a PC, you can get them up to the point where the device crashes. And for a shorter command, you can just use `adb logcat`.

**Comment by skasync** [comment]
I just tested Syncthing Android from F-Droid on Xperia Z4 with Marshmallow 6.0 build 32.1.A.1.185. The destination folder is on the external USB card in the android/data tree.

I have installed Syncthing GUI v0.7.18 with Syncthing v0.13.0 from F-Droid.
I also tried to build syncthing from git with Syncthing 0.13.2 embedded. That has the same problem:

I have installed the F-Droid variant on thee SmartPhones: Android 4.4, Android 5.1 and Z4 (above one). On all but the Z4 the version syncs with ~1.5 MBit, sometimes less, but more or less stable, with a Linux host, which is configured staticly via tcp://<ip4-addre>:port . The Z4 is slow. Very slow. Sometimes it syncs with 2.4Mbit (displayed on Linux host, it is always lower, if web GUI is open on the smartphone), but most often it drops down to 500KB and less. Transmission also drops to 0 now and then for some seconds.

As long as adb logcat is running, you can lock / unlock the Z4 with running Syncthing web GUI, with Syncthing GUI, with syncing Syncthing. No reboots, nothing. I had it run adb logcat for 2.5 houres with a reboot. 

After I unplugged the Z4 from the USB cable, the screen was locked. I could not bring up the unlock screen with the power button *and* as I tried three or four times, the Z4 rebooted.

There are logs like these:
 W ipacm   : type=1400 audit(0.0:46984): avc: denied { sendto } for path="/dev/socket/ipacm_log_file" scontext=u:r:ipacm:s0 tcontext=u:r:ipacm-diag:s0 tclass=unix_dgram_socket permissive=0 ppid=1 pcomm="init" pgid=789 pgcomm="ipacm"
D TransmitPowerReceiver: Old PowerLevel: 5, current PowerLevel: 5
D QtiTetherService/IpaWrapper: getStats(false)
 I TetherStatsReporting:   [34] iface=wlan0 uid=10185 set=DEFAULT tag=0x0 rxBytes=30971 rxPackets=49 txBytes=9681 txPackets=64 operations=0
 V FolderObserver: Received inotify event 80 at /100ANDR2/DSC_0129.jpg
 MediaScannerReceiver: action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/EAB2-A836/Android/data/com.nutomic.syncthingandroid/files/bromi-bilder1/100AND
R2/DSC_0332.jpg
I MSM-irqbalance: Decided to move IRQ216 from CPU2 to CPU0
05-31 22:36:46.636  4999  5116 I SemcDlna: : No clients is registered now...
05-31 22:36:46.636  4999  5116 I SemcDlna: : disabling the server control point...
05-31 22:36:46.694  4999  5116 I SemcDlna: : ...Done!!
05-31 22:36:46.694  4999  5116 I SemcDlna: : disabling the renderer control point...
05-31 22:36:46.698  4999  5116 I SemcDlna: : ...Done!!
05-31 22:36:46.699  4999  5116 I SemcDlna: : The server list is clear, then refreshing in [2] secs...
05-31 22:36:46.699  4999  5116 I SemcDlna: : The renderer list is clear, then refreshing in [2] secs...
05-31 22:36:46.973  4999  4999 I SemcDlna: : destroying Upnp CP service...
05-31 22:36:46.979  4999  5116 I SemcDlna: : The [0] server(s) are found!!!
05-31 22:36:43.634  3361  3488 D QtiTetherService/IpaWrapper: getStats(false)
05-31 22:36:44.348   609  2279 D audio_hw_primary: out_standby: enter: stream (0xf21d1180) usecase(1: low-latency-playback)
05-31 22:36:44.397   609  2279 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
05-31 22:36:44.398   609  2279 D soundtrigger: audio_extn_sound_trigger_update_stream_status: uc_id 1 of type 0 for Event 2, with Raise=0
05-31 22:36:44.398   609  2279 D hardware_info: hw_info_append_hw_type : device_name = speaker
05-31 22:36:44.398   609  2279 D audio_hw_primary: disable_snd_device: snd_device(50: speaker)
05-31 22:36:44.405   609  2279 D hardware_info: hw_info_append_hw_type : device_name = vi-feedback
05-31 22:36:44.405   609  2279 D audio_hw_primary: disable_snd_device: snd_device(259: vi-feedback)
05-31 22:36:44.405   609  2279 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x103 of type 1 for Event 0, with Raise=0
05-31 22:36:44.405   609  2279 D audio_hw_primary: disable_audio_route: reset and update mixer path: spkr-vi-record
05-31 22:36:44.405   609  2279 D soundtrigger: audio_extn_sound_trigger_update_stream_status: uc_id 38 of type 1 for Event 2, with Raise=0
05-31 22:36:44.408   609  2279 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x32 of type 0 for Event 0, with Raise=0
05-31 22:36:44.408   609  2279 D audio_hw_extn: audio_extn_get_anc_enabled: anc_enabled:0
05-31 22:36:42.454 13095 13095 I EventProcessor: Unhandled event LocalIndexUpdated
05-31 22:36:42.454 13095 13095 I EventProcessor: Notified media scanner about /storage/EAB2-A836/Android/data/com.nutomic.syncthingandroid.debug/files/bromi-bilder1/100ANDR2/DSC_0272.jpg
05-31 22:36:42.456 13095 13095 I EventProcessor: Unhandled event FolderSummary
05-31 22:36:42.456 13095 13095 I EventProcessor: Unhandled event ItemStarted
05-31 22:36:42.456 13095 13095 I EventProcessor: Unhandled event FolderCompletion
05-31 22:36:42.456 13095 13095 I EventProcessor: Unhandled event FolderCompletion
05-31 22:36:42.456 13095 13095 I EventProcessor: Unhandled event LocalIndexUpdated
05-31 22:36:42.456 13095 13095 I EventProcessor: Notified media scanner about /storage/EAB2-A836/Android/data/com.nutomic.syncthingandroid.debug/files/bromi-bilder1/100ANDR2/DSC_0332.jpg
05-31 22:36:42.459 13095 13095 I EventProcessor: Unhandled event LocalIndexUpdated
05-31 22:36:42.459 13095 13095 I EventProcessor: Unhandled event DownloadProgress
05-31 22:36:42.460 13095 13095 I EventProcessor: Unhandled event FolderSummary
05-31 22:36:42.460 13095 13095 I EventProcessor: Unhandled event FolderCompletion
05-31 22:36:42.460 13095 13095 I EventProcessor: Unhandled event FolderCompletion
05-31 22:36:42.354 13095 13095 D EventProcessor: Reading events starting with id 891
05-31 22:36:42.354 13095 13140 V GetTask : Calling Rest API at https://127.0.0.1:8384/rest/events
05-31 22:36:42.357 13095 13140 I DpmTcmClient: RegisterTcmMonitor from: org.apache.http.impl.conn.TcmIdleTimerMonitor
05-31 22:36:42.453 13095 13140 V GetTask : API call result: [{"id":892,"time":"2016-05-31T20:36:27.617007856Z","type":"LocalIndexUpdated","data":{"filenames":["100ANDR2/DSC_0123.jpg"],"folder":"B
05-31 22:36:41.404  3417  3417 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@9351d74 time:5649258
05-31 22:36:41.406  1768  1775 I art     : Background partial concurrent mark sweep GC freed 77324(7MB) AllocSpace objects, 73(1852KB) LOS objects, 33% free, 29MB/43MB, paused 972us total 118.641ms
05-31 22:36:41.430 13646 13646 I Scenic  : com.sonyericsson.scenic.system.helpers.ScenicView.onPause(ScenicView.java:90): onPause
05-31 22:36:41.529  1768  1855 I Timeline: Timeline: Activity_windows_visible id: ActivityRecord{6963d9e u0 com.sonyericsson.home/com.sonymobile.home.HomeActivity t271} time:5649383
05-31 22:36:41.577 13646 13646 I Scenic  : com.sonyericsson.scenic.system.helpers.ScenicView.onStop(ScenicView.java:102): onStop
05-31 22:36:41.605  3640  5118 D MdnsClient: Multicast lock held. Releasing
05-31 22:36:32.339   712   712 I MSM-irqbalance: Decided to move IRQ115 from CPU2 to CPU1
05-31 22:36:32.340  3504  3567 D QcrilMsgTunnelSocket: readRilMessage: Buffer = [B@712efe2 HexData = [010000000404000011000000514f454d484f4f4bef0308000100000003]
05-31 22:36:32.340  3504  3567 D QcrilMsgTunnelSocket: Rcvd UNSOL response with 28 bytes data for SUB0
05-31 22:36:32.340  3504  3567 D QcrilMsgTunnelSocket: Response ID 525295 is not served in this process.
05-31 22:36:32.340  3504  3567 D QcrilMsgTunnelSocket: To broadcast an Intent via the notifier to external apps
05-31 22:36:32.340  3504  3504 D QcrilMsgTunnelIfaceManager: handleMessage what = 0
05-31 22:36:32.351  3372  3372 D QC_RIL_OEM_HOOK: Received Broadcast Intent ACTION_UNSOL_RESPONSE_OEM_HOOK_RAW
05-31 22:36:32.351  3372  3372 D QC_RIL_OEM_HOOK: Oem ID in QCRILHOOK UNSOL RESP is QOEMHOOK
05-31 22:36:32.355  1768  1768 D QC_RIL_OEM_HOOK: Received Broadcast Intent ACTION_UNSOL_RESPONSE_OEM_HOOK_RAW
05-31 22:36:32.355  1768  1768 D QC_RIL_OEM_HOOK: Oem ID in QCRILHOOK UNSOL RESP is QOEMHOOK
05-31 22:36:32.409  1768  2785 I TetherStatsReporting: getTetherStats() called NetworkStats: elapsedRealtime=9441998

5-31 22:36:30.874  1768  3404 I ActivityManager: Start proc 13740:com.sonyericsson.credentialmanagerservice:credentialmanagerservice/1000 for service com.sonyericsson.credentialmanagerservice/.CredentialMana
gerService
05-31 22:36:30.939 13740 13740 W System  : ClassLoader referenced unknown path: /system/priv-app/CredentialManagerService/lib/arm64
05-31 22:36:31.000 13740 13750 E linker  : readlink('/proc/self/fd/23') failed: Permission denied [fd=23]
05-31 22:36:31.000 13740 13750 E linker  : warning: unable to get realpath for the library "/system/lib64/libdevice_security.so". Will use given name.
05-31 22:36:31.068   638   638 D QSEECOMAPI: : QSEECom_get_handle sb_length = 0x20000
05-31 22:36:31.068   638   638 D QSEECOMAPI: : App is not loaded in QSEE
05-31 22:36:31.093   638   638 D QSEECOMAPI: : Loaded image: APP id = 50
05-31 22:36:31.108 13095 13147 V FolderObserver: Received inotify event 40 at /100ANDR2/.syncthing.DSC_0332.jpg.tmp
05-31 22:36:31.108 13095 13147 V FolderObserver: Received inotify event 80 at /100ANDR2/DSC_0332.jpg
05-31 22:36:31.180   638   638 D QSEECOMAPI: : QSEECom_dealloc_memory 
05-31 22:36:31.180   638   638 D QSEECOMAPI: : QSEECom_shutdown_app, app_id = 50
05-31 22:36:31.467 13646 13756 E linker  : readlink('/proc/self/fd/88') failed: Permission denied [fd=88]
05-31 22:36:31.467 13646 13756 E linker  : warning: unable to get realpath for the library "/system/lib64/libjhead_jni.so". Will use given name.
0

**Comment by capi** [comment]
If the device is getting really hot, maybe it reaches the point where CPU enters overheating protection and triggers a reboot. Would be a flaw in the thermal concept of the device, though and not much we could do on the software side about it. Syncthing uses a lot of CPU for hashing files, when/if it needs to hash new or changed files.

**Comment by skasync** [comment]
I wouldn't call it "getting really hot". I'm puzzled why it not happened during the time the device is plugged on the USB cable. It had plenty of files downloaded and probably hashed.

Anyway, does somebody happen to know an app to record the CPU temperature so I can check the condition between heat and reboot? A quick check on F-Droid and Play store didn't hit one.

**Comment by Nutomic** [comment]
@skasync I suggest you ask on a general Android forum. Closing this because it doesn't seem directly related to Syncthing.
