### ISSUE TITLE
caught a crash

### ISSUE THREAD

**Issue by irregularisnotrandom** [syncthing/syncthing-android#627]
I/ActivityManager(  874): Killing 8001:com.nutomic.syncthingandroid/u0a283 (adj 15): BG, 9300K, hotnessAdj=6, XmlFlag=false, oom_adj=15
D/PowerManagerService(  874): [api] handleWakeLockDeath : release WakeLock : PARTIAL_WAKE_LOCK              'SyncthingRunnable' (uid=10283, pid=8001, ws=null) (elapsedTime=16463913)
W/ActivityManager(  874): Scheduling restart of crashed service com.nutomic.syncthingandroid/.syncthing.SyncthingService in 70761ms
I/ActivityManager(  874): Start proc 28370:com.nutomic.syncthingandroid/u0a283 for service com.nutomic.syncthingandroid/.syncthing.SyncthingService
I/SyncthingService(28370): Web GUI will be available at https://127.0.0.1:8384
I/SyncthingService(28370): Starting syncthing according to current state and preferences
D/ApplicationPolicy(  874): isStatusBarNotificationAllowedAsUser: packageName = com.nutomic.syncthingandroid,userId = 0
I/System.out(28370): AsyncTask #2 calls detatch()
I/SyncthingNativeCode(28370): [CVMT6] 23:29:36 INFO: syncthing v0.12.22 "Beryllium Bedbug" (go1.6 linux-arm) unknown-user@testing32 2016-04-13 09:52:12 UTC
I/System.out(28370): AsyncTask #2 calls detatch()

**Comment by AudriusButkevicius** [comment]
And where is the crash? Looks like normal log output

**Comment by irregularisnotrandom** [comment]
W/ActivityManager( 874): Scheduling restart of crashed service com.nutomic.syncthingandroid/.syncthing.SyncthingService in 70761ms


The rest of the log up untilnthat point is just the rest api calls After thatvthere is the portion above and when i clicked on the tray icon for st it was in the reloading mode, which the log showed that indeed st was restarting

**Comment by AudriusButkevicius** [comment]
So there is no crashlog, just a message its restarting, which is not immensly useful.

**Comment by Nutomic** [comment]
The actual crash is probably before those logs. Try `adb logcat -s *:E`.

**Comment by irregularisnotrandom** [comment]
Sorry i got the crash on the go.

**Comment by Nutomic** [comment]
There's nothing we can do without a proper crash log...
