### ISSUE TITLE
Crash with log

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-android#635]
log
https://paste.debian.net/444747/

This is an Android 4.2.2

**Comment by Tiemichael** [comment]
not sure if it's the same or related:
The App  crashes when closing the log-file.
Steps to reproduce:
go to 'Settings' - 'Open Log'  -> current log is showing, but not updated
press the '<-- Log' - the app crashes 'Unfortunately, Syncthing has stopped'

If you press 'back' on the phone/tablet is works ok.

I see the same behavior on both a rooted Tablet (android 5.1.2) and a rooted Phone (android 5.0.2), using Syncthing 7.17 (12.22)

**Comment by Nutomic** [comment]
Not sure where the crash is in that log. Can you post steps to reproduce this?

@Tiemichael See #604.

**Comment by Petef** [comment]
I get identical crash to Tiemichael when closing log.

**Comment by Nutomic** [comment]
@Petef That would be #604.

**Comment by Tiemichael** [comment]
Sorry, I am unable to provide a proper log, but here is 3 screenshots. 
Steps to reproduce:
go to 'Settings' - 'Open Log' -> current log is showing, but not updated
press the '<-- Log' - the app crashes 'Unfortunately, Syncthing has stopped'

![screenshot_2016-05-20-11-23-15_com nutomic syncthingandroid_1463716176165](https://cloud.githubusercontent.com/assets/11308991/15416794/c9387cd6-1e81-11e6-9a9b-955ef1abf558.jpg)
![screenshot_2016-05-20-11-54-08_com nutomic syncthingandroid](https://cloud.githubusercontent.com/assets/11308991/15416796/c93a9e44-1e81-11e6-822e-5a59668636c5.png)
![screenshot_2016-05-20-11-48-19_com miui bugreport](https://cloud.githubusercontent.com/assets/11308991/15416795/c9391718-1e81-11e6-8f09-9489ce760717.png)

**Comment by lkwg82** [comment]
I'll close this as there is no crash.
