### ISSUE TITLE
Can't changes settings to enable Syncthing now.

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#637]
Usually Syncthing is set up to run only if it is Wi-fi _and_ the device is charging.

The device is now connected to Wi-Fi, but not charging.

I got this sequence:
1. I start Syncthing from home
2. It shows message about Syncthin being disabled with a button to open Syncthing's settings
3. I press the button. Settings open
4. I uncheck the "Only when charging" checkbox
5. I press back
6. I get to home screen (expected: to Syncthing's interface)
7. I start Syncthing again from home screen
8. Syncthing shows the same message as in "2."
9. I press button to go to settings
10. Checkbox about only-charging is already disabled.

After 3-4 of such attempts, Syncthing crashed (or maybe it's because of orientation change when displaying that message?) and after restarting it got to the UI and started backing up.

In the "2." message I also want to know why does Syncthing not run: because of Wi-Fi required, because of charging required or because of both.

**Comment by strout** [comment]
#634 possibly related?

**Comment by Nutomic** [comment]
True, but I'm leaving this issue open as it provides some clear, constructive feedback.

**Comment by Catfriend1** [comment]
According to https://github.com/syncthing/syncthing-android/issues/634 it is fixed.
