### ISSUE TITLE
Option to enable sync when tethering as a Wifi Hotspot 

### ISSUE THREAD

**Issue by toddnni** [syncthing/syncthing-android#641]
This is a feature request for an option to enable sync when when the phone is acting as a Wifi hotspot. The behaviour should be very similar to "Sync only on wifi". Maybe we could add "Sync also when acting as a Wifi hotspot" under the former option, and the option should be greyed out when wifi restriction is not selected.

Use case is to sync photos from a phone to a laptop when the phone acts as a hotspot for the laptop.

An older similar feature request was closed #194, but there was an additional requirement to limit mobile data transfer. My request is to have simple on/off functionality when hotspot is turned on or off.  One can disable mobile data transfer manually if there is a such requirement.

**Comment by capi** [comment]
Maybe it would be easiest to implement such special requirements via Tasker? There is now an API which you can use with applications like Tasker.

**Comment by Nutomic** [comment]
Agreed, I think this is too specific to have it directly in the app.

**Comment by edrex** [comment]
For those of us that tether this does not seem like a niche case at all.

IMO Syncthing, as well as the Android app, suffer from an over-reliance on configuration over just making nodes Do the Right Thing™.

This situation doesn't call for another config option: it can hang on the existing "sync only on wifi" option. I don't see a downside other than a bit of extra complexity to listen for hotspot activation and restart with the right config options.

**Comment by Nutomic** [comment]
@edrex I'm don't think this would be a good idea. Having "sync on wifi" also mean "sync on hotspot" means that when a user enables a hotspot, Syncthing will happily start syncing over mobile data. That isn't something an app should do without warning.

**Comment by edrex** [comment]
I'm not proposing changing the behavior for the outgoing interface, just the internal interface. I think discovery/syncing over the internal tethering WiFi interface should be allowed whenever syncing over WiFi would be allowed (and hotspot is enabled), since the cost for the device is the same (just WiFi power drain).

Aside 1: *I've gotten discovery and syncing to work over wifi "hotspot" in the field with no outbound data connection, another Android device connecting to the hotspot and both running Syncthing Silk.*

Aside 2: *There's nothing stopping Syncthing instances on devices connected to the tethering network from using global discovery/proxy over the mobile data connection, currently or with this changed behavior.*

**Comment by wweich** [comment]
> Aside 2: There's nothing stopping Syncthing instances on devices connected to the hotspot from using global discovery/proxy over the mobile data connection, currently or with this changed behavior.

If you don't tell Android, that this is a metered network, no, it doesn't. But if you tell Android, than Syncthing will also stop syncthing over the hotspot Wifi.

Are you sure Android gives Apps the ability to distinguish between internal Wifi connections (inside the hotspot) and external connections (mobile data), when even Android cannot handle Wifi without Internet and mobile data at the same time.

**Comment by toddnni** [comment]
Thanks for the discussion. I were able to find a solution to the original need by following the advice @capi gave. I don't have an opinion about the latter discussion, but please carry on if needed.

**Comment by Nutomic** [comment]
Maybe you can share that solution with the community? Either on the wiki or in the forum. After that, I'd close this issue.
