### ISSUE TITLE
Save Configuration

### ISSUE THREAD

**Issue by Tiemichael** [syncthing/syncthing-android#642]
Thank you for providing this app!

When  I change settings like  'Device Name' or 'Sync Protocol Listen Addresses', settings are not saved after restarting Syncthing. 
Workaround: As using root for Syncthing has reportedly problems, I edit config.xml with a root-editor under /data/data/com.nutomic.syncthingandroid/files 
My setup: 
Xiaomi Note2 running Android 5.02, rooted , and Samsung P600 running Android 5.1.2. rooted
Syncthing 0.7.17 (0.12.22)

**Comment by licaon-kter** [comment]
Root is not supported yet, hence experimental, see #453 

What is your use case/need for root exactly?

**Comment by Tiemichael** [comment]
My phone is rooted for various reasons like to use Titanium Backup, or Stop Advertisments.
But I did NOT use the root-option for Syncthing, so Syncthing only has 'normal access'.

**Comment by lkwg82** [comment]
I can confirm changing the device name is saved after restart. (Android 6)

**Comment by Nutomic** [comment]
@Tiemichael Can you give the exact steps to reproduce this issue? Otherwise I'm gonna close this.

**Comment by Tiemichael** [comment]
Everything seems working fine with the current version!
Thank you!
