### ISSUE TITLE
Synching on networking feature

### ISSUE THREAD

**Issue by Anthael** [syncthing/syncthing-android#644]
Hi
As the wifi setting might be possible to add an option to activate the sync on specific network 2g, 3g, 4g
Thanks by advance

**Comment by Nutomic** [comment]
This should probably be done with Tasker or a similar app:
https://github.com/syncthing/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents

**Comment by lkwg82** [comment]
closing as out of scope
