### ISSUE TITLE
Super active Libsynching.so

### ISSUE THREAD

**Issue by irregularisnotrandom** [syncthing/syncthing-android#646]
Hi

I see in the adb session that this process jumps to %20 or more of Cpu usage  constantly every couple seconds when no file or change activity is going on. There are no activities on other nodes as well at that timesince I am the only user.
I do not know how to debug this. Can someone try this? Adb to your device and run " adb shell top -m 10" 

You can also try it with bg syncing .

thnx

**Comment by licaon-kter** [comment]
And that's a problem because? Battery? Pics? Data? Pics?

**Comment by Nutomic** [comment]
Check the logs (in settings) to see what Syncthing is doing.

**Comment by irregularisnotrandom** [comment]
St is not doing anything when that is happening

**Comment by AudriusButkevicius** [comment]
well enable STTRACE=all and then check
