### ISSUE TITLE
Android device never connects, with or without relays

### ISSUE THREAD

**Issue by williamkray** [syncthing/syncthing-android#649]
Adding android device worked when I first attempted it, but it stopped showing up as "online" ever. I have removed, deleted app data, uninstalled and reinstalled, changed every conceivable config I can think of, and it still no workie.

Steps to reproduce:

1. Install Syncthing for Android
2. Add device via barcode or device-id
3. Observed behaviour: neither device ever finds the other, logs do not indicate any action at all
4. Expected behaviour: the device would be found

If I manually enter a connection string, like tcp://myhost:22000, then that remote host will recognize that the phone is attempting to connect, and ask for confirmation to add that device; but then the phone state in the web dashboard remains "disconnected" forever, and the android app logs indicate "incorrect magic"

syncthing-android version: 0.7.18

Device name and Android version: Nexus 5x, android 6.0.1

versions of involved Syncthing nodes: v0.13.0 (on android), v0.12.24 (on home server and on laptop)

logcat: http://hastebin.com/bikifaqezu.tex

**Comment by williamkray** [comment]
i should mention that this is all entirely on a local network, for example tcp://myhost:22000 resolves to 192.168.1.9 or something similar. I have also tested without using the local network, with the same results.

**Comment by licaon-kter** [comment]
> Syncthing nodes: v0.13.0 (on android), v0.12.24 (on home server and on laptop)

Umm, update to 0.13 on all nodes, stuff has changed: https://github.com/syncthing/syncthing/releases/tag/v0.13.0

**Comment by wweich** [comment]
As stated in the release notes, v0.12 and v0.13 cannot connect to each other.

_As the Discovery System had a doover, maybe local Discovery ist also incompatible and that's why they can't find each other._

**Comment by AudriusButkevicius** [comment]
Local discovery is also incompatible.

**Comment by williamkray** [comment]
Oh man do I feel dumb if that's the issue. 0.12 is what's in the Arch linux repos. I'll update to the git version. Sorry everyone! I'll update this thread to confirm that it resolves the issue later.

**Comment by williamkray** [comment]
ah yeah, that looks like it was the issue. maybe the app store version needs a notice in the version notes as well that it requires v0.13+ to function properly? not really the primary responsibility, but it certainly caused me some confusion.

marking as closed.
