### ISSUE TITLE
Unclear which button saves a devices configuration

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing-android#650]
I've just wasted a lot of time on Android's Syncthing, I am sad to say, because I was pressing the

> <-- Add device

text, which actually _cancels_ the addition of a device, rather than the little - somewhat cryptic - disk, i.e. save, icon to the right of the aforementioned text. I think it should be made easier for the user to know what to do in this situation.

**Comment by Nutomic** [comment]
Right, we should probably also add the device when that button is pressed.
