### ISSUE TITLE
Editing folder to be shared with a device - change is not saved

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [syncthing/syncthing-android#651]
What happens: on Android, I go to edit a folder to share it with a device that appears already on the Android system; I use the slider toggle to share the folder; I leave the edit screen either by pressing the arrow at the top left of by using my phone's 'back' button at the bottom left; the change to the sharing setting is not retained.

Syncthing 0.13.0
Syncthing-Android: 0.7.18

I wonder whether the versions of Syncthing I am using on my other devices is relevant. (One device is Windows and one is Linux. Try to share my Android folder with either of those devices encounters the same problem.)

**Comment by wweich** [comment]
dup of #647. Fixed in next version

**Comment by Nutomic** [comment]
Leaving this open for now so other people can easily find it.

**Comment by elconsultor** [comment]
I have two new devices and I can not use syncthing because of this error. When you think put the update on google play ?

Thank you very much

**Comment by AudriusButkevicius** [comment]
Use web ui in the meanwhile.

**Comment by elconsultor** [comment]
Sincerely, thank you very much

**Comment by Nutomic** [comment]
I just released the fixed version.
