### ISSUE TITLE
version number of syncthing-android has non-obvious relationship to syncthing version

### ISSUE THREAD

**Issue by gdt** [syncthing/syncthing-android#652]
I use syncthing on android (from f-droid) and on NetBSD and OS X (from pkgsrc).   Given that syncthing breaks protocol compatibility across major releases, this means that I have to upgrade everything at once.  With syncthing proper, it's clear that 0.12.19 to 0.13.2 is a protocol change.   In syncthing-android, going from 0.7.17 to 0.7.18 breaks protocol compatibility, if I read the commit logs correctly.   I realize that most of the android code may not have changed, but it would be really nice to somehow change the version number in a louder way.   One approach would be to just move to 0.8 for 0.13 (or 0.14 at this point).

**Comment by Nutomic** [comment]
Syncthing and syncthing-android are seperate projects. I don't think it's feasible to sync the releases, because it would be a lot of extra effort.

But I see your point about breaking changes. I think it would be okay to increase the minor version in that case (so 0.7 to 0.8).

**Comment by capi** [comment]
In my opinion it would make sense to mirror the `major.minor` version of the syncthing binary we use, e.g. now `0.13.x`, where as `x` is unrelated to the `syncthing` binary.

**Comment by AudriusButkevicius** [comment]
Or 0.8.1.01302

**Comment by gdt** [comment]
Understood about separate projects and that synchronized releases would be too hard.  I really only wanted to ask that when I saw a syncthing-android update that changes the syncthing branch (and hence is not protocol compatible) that it be readily apparent.

**Comment by Nutomic** [comment]
@capi Yeah that would make sense.

@AudriusButkevicius Looks way too complicated imo.

**Comment by gdt** [comment]
I think this can be closed now that the new release was labeled 0.8.0.   Thanks for listening and adjusting the versioning scheme
