### ISSUE TITLE
FR: Dark theme

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-android#653]
As it says in the title. A dark theme is veyr benecial to our eyes and to those with amoled screen.

**Comment by wbedard** [comment]
While the native client interface doesn't have this option, the web GUI does has an option for a dark theme which works very well.  Open the web GUI, go to Settings and then all the way at the bottom.

**Comment by letroll** [comment]
The change in the web UI not apply to the rest of the application

**Comment by MegaArthur** [comment]
Yes, it would be really nice if the whole app had a dark theme.

**Comment by AudriusButkevicius** [comment]
Please refrain from "yeah me too" comments, these add zero value to the issue, use the emoticons to express support.
