### ISSUE TITLE
Cannot add more devices to share with when editing a folder

### ISSUE THREAD

**Issue by elvetemedve** [syncthing/syncthing-android#654]
When I want to share a folder on my phone with multiple devices, the standard GUI does not save the associated devices. But when I do the same via Web GUI, it saves the association correctly.

**Steps to reproduce**:

1. Create a new folder on your mobile device.
2. Share it with a device.
3. Now edit the folder and add a second device to the list of shared devices

**Syncthing-android version**: 0.7.18
**Device name and Android version**: Sony Xperia Z1 Compact, Android 6.0.1
**Versions of involved Syncthing nodes**: 0.13.0, 0.13.4

**Comment by wweich** [comment]
Dup of #647 + #651. Already fixed and new version on the way.
