### ISSUE TITLE
Sync stop while enter suspend sometime. 

### ISSUE THREAD

**Issue by shengyilu** [syncthing/syncthing-android#657]
Hi, 
Syncthing is very cool! I am trying to integrate it into my personal project to sync files between my Android devices. I have found that once one of my Android entered suspend mode with charge plug-in, new files were not able to be synced to it.  I noticed that there is a fix (#498) trying to hold wakelock in SyncthingRunnable to keep cpu running. However, I still have this problem from time to time. How can I check the native libsyncthing process state? How can I ensure the native process not entering sleep during Android suspend? Thanks for any suggestion!!

**Comment by wweich** [comment]
If you have Android 6, you also have to disable the battery optimization for Syncthing in the Android settings.
