### ISSUE TITLE
Unable to change shared devices of a folder in app GUI

### ISSUE THREAD

**Issue by favonia** [syncthing/syncthing-android#658]
I am using Syncthing-Android 0.7.18 with Syncthing 0.13.0. Today I noticed that the setting is never saved after toggling shared devices of a folder and leaving the window (by tapping the left triangle next to the home button) in the app GUI. The web GUI is working as expected, and thus the Syncthing itself is fine. I suspect that #617 is related.

**Comment by Nutomic** [comment]
This is already fixed in 0.7.19. Unfortunately, there was a problem so this version didn't go into F-Droid. But that's fixed now, and it should be available tomorrow.

**Comment by favonia** [comment]
Thanks. Sorry I failed to find the relevant issue. Marked as closed.
