### ISSUE TITLE
On Android, every host is stuck to 4% (but in fact, directories are in sync)

### ISSUE THREAD

**Issue by neurolit** [syncthing/syncthing-android#659]
Hi!

I'm using Syncthing 0.7.19 on Android. On my computers (Linux and Windows), I'm using Syncthing 0.13.4 (Linux) and 0.13.5 (Windows).

Each instance is sharing the same directory (my Android pictures). Everything is looking good, every picture is in sync, however Android app is displaying that synchronization is stuck to 4%.

![screenshot_2016-06-05-16-31-27](https://cloud.githubusercontent.com/assets/1727830/15806093/089de43a-2b3c-11e6-9831-b9def775ad1d.png)

Of course, on my computers, Android sync is also showed at 4%.

I think it began when my computers were upgraded to Syncthing 0.13.

Do you know what's going on?

Android logs are here: https://drive.google.com/open?id=0BwrFUWrxgx-LeGRRYTByX3NIcDA
Android config file is here: https://drive.google.com/open?id=0BwrFUWrxgx-LekpQV2pqUjdMNTg

**Comment by licaon-kter** [comment]
WebUI->folder->(red)Overwrite changes->Re-scan->Success?

**Comment by neurolit** [comment]
Yes, it did the trick! Thank you very much @licaon-kter !

**Comment by licaon-kter** [comment]
Yeah, as long as files are synced that does it.
That's if the Android folder in `Master`, I would be careful around folders that accept changes from more devices as you might `overwrite` something that was updated elsewhere.
