### ISSUE TITLE
Adding new share does not work. 

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-android#661]
I think that adding a new share is broken in 0.7.19

I add a new folder, share with some devices. I then restart the new share is not there.

**Comment by Nutomic** [comment]
I just tried this and it works fine. Can you post a logcat?

**Comment by gerroon** [comment]
I just tried it on another device and it does not work. I can only do it in the web interface or editing the config manually. 

What kind of log do you want?

**Comment by Nutomic** [comment]
Is #690 the problem you're having?
