### ISSUE TITLE
Stuck "Loading", close app, starts up immediately

### ISSUE THREAD

**Issue by edrex** [syncthing/syncthing-android#663]
I have Syncthing android (0.7.19) set to sync only on wifi.

Often, the following sequence occurs:

 - I edit a file on my phone, in my sync folder.
 - I notice it doesn't sync to my laptop, and check the web ui on my laptop, noting that the phone hasn't connected in awhile.
 - I touch the "Syncthing is running" notification (low priority - doesn't this matter, functionally?).
 - Stuck "Loading..."
 - I bring up the task list, and swipe away Syncthing, then launch it again.
 - It comes up immediately and syncs.

This happens fairly consistently, whenever the app hasn't been launched for awhile. I'm not sure if it's because Android system has GC'd the go process, or it has hung on its own, possibly due to network link changes. 

Unfortunately, I can't access the in-app log viewer until I've restarted, which wipes the log. Next time this happens, I'll capture the log via logcat.

**Comment by edrex** [comment]
Apologies if this is a duplicate, didn't see one that seemed to match.

**Comment by wweich** [comment]
What Android version? If 6.x, did you disable the battery optimization for Syncthing in the System Settings?
Did you enable the experimental wake lock setting inside Syncthng App?

**Comment by edrex** [comment]
Oh yes, Android 6.0. 

 didn't do either of those things. It sounds like doing so would reduce battery life? 

Anyway it seems like a bug that syncthing android isn't detecting the failed core.

I have ADB logs now, but I'm not sure what's relevant so will try to sift though and isolate some interesting lines.

**Comment by scienmind** [comment]
I encounter this bug as well from time to time, on many devices (all android 6). 
My guess would be that this one and #634 have some common ground...

**Comment by DrSchnagels** [comment]
While my Nexus 6P works very flawlessly with syncthing i have a huge problem using it on my Google Pixel C. Like this thread discribes, syncthing does stop working at any time and has to be manually restarted. On the first start it is always stuck on the loading screen and has to be closed again.
After that it works again.
Both my devices are unrooted and have the stock firmware with all updates.

**Comment by go2null** [comment]
same as #687?

**Comment by Nutomic** [comment]
Right, good catch.
