### ISSUE TITLE
"Syncthing disabled" message does not go away when WLAN becomes available.

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#664]
**Steps to reproduce:**

1. Configure Syncthing to be available on Wi-Fi only;
2. Have Wi-Fi turned off in the system;
3. Enable Wi-Fi in the system;
4. Quickly open Synthing (before the system got connected to an AP);
5. Observe "Syncthing disabled ... [Exit] [Change Settings]" message;
6. System gets connected to an AP;
7. Observe "Loading..." message;

**Actual**:

"Syncthing disabled" message persists atop of now lively UI in background.

**Expected**:

"Syncthing disabled" message disappears.

**Actually expected by users of well-designed applications**:

UI is fully available even when Syncthing is disabled: #554.

**Workaround**:

Change device orientation to/from landscape and back.

**Comment by Nutomic** [comment]
I couldn't reproduce this. The "Syncthing disabled" dialog always goes away as soon as the phone connects to wifi.

**Comment by scienmind** [comment]
Sounds like this may have the same root cause: #634

**Comment by Nutomic** [comment]
Right, closing this as duplicate.
