### ISSUE TITLE
Devices showing as "Not Connected"

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#666]
My devices keep disconnecting sporadically from my Syncthing network, whether I have the firewall turned on or not. 
This is interfering with both speed and reliability of data transfers along with making my data transfers hard to forecast when they will be complete.

**Comment by Nutomic** [comment]
This sounds like a problem with firewalls or something like that, not a bug. You should post on the forum with more details.

**Comment by jebeld17** [comment]
Are there any ports I need to have opened for proper function? Which ones?

**Comment by wweich** [comment]
https://docs.syncthing.net/users/firewall.html

**Comment by holyoaked** [comment]
Did forwarding the required ports solve this solution @jebeld17 ?

**Comment by go2null** [comment]
I have this issue to and don't have a firewall.
However, ot does seem to be less frequent/more reliable since v0.8.0.

**Comment by Nutomic** [comment]
This issue seems to fit better on the forum. Please open a thread there if you still have this problem.

**Comment by jebeld17** [comment]
Looks like it actually was an issue and fixed in the recent update pushed out today.
