### ISSUE TITLE
Compression Type does not Save

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#667]
Changing the compression type and saving those changes for a different device from the app results in basically nothing... My changes never ever save. Please fix.

**Comment by Nutomic** [comment]
To save settings, you have to leave the device settings screen and restart Syncthing when the dialog comes up. I just tried and the compression setting works for me.

**Comment by jebeld17** [comment]
I did that, and it didn't fix the issue

**Comment by lkwg82** [comment]
I just tried and it runs.

**Comment by lkwg82** [comment]
Do you have the latest version?

**Comment by jebeld17** [comment]
Yes.
It still doesn't save. As soon as I restart the syncthing server, it reverts. 
I think it has to do with settings from other devices overwriting my recent changes.

**Comment by lkwg82** [comment]
which android version?

**Comment by jebeld17** [comment]
6.x

**Comment by lkwg82** [comment]
rooted?

**Comment by lkwg82** [comment]
maybe you can fetch the logs
