### ISSUE TITLE
Importing crashes on MM

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-android#668]
It looks like some kind of permission thing

https://paste.debian.net/hidden/b7566d57/

**Comment by AudriusButkevicius** [comment]
If you enable root, there is no way back, and you seem to want to run without root now.

**Comment by AudriusButkevicius** [comment]
Dup #453

**Comment by gerroon** [comment]
@AudriusButkevicius 

I used the root mode after failing to read those files, that was my second attempt with the root mode.

**Comment by AudriusButkevicius** [comment]
Regardless, this is a dup.
