### ISSUE TITLE
Too much battery consumption on mobile connection although only WiFi syncing is enabled

### ISSUE THREAD

**Issue by therealmarv** [syncthing/syncthing-android#671]
I'm currently in vacation in another country and during that time Syncthing is not useful for me. Actually I've set it up to sync only on WiFi (using nearly only mobile connections here) and later turned it also entirely off. Nevertheless Syncthing is the biggest battery consumption app. Hope this will be fixed in future. Sync on Wifi means for me that Syncthing is agressively doing nothing on mobile connections.

![image](https://cloud.githubusercontent.com/assets/1050582/15987097/aaa1a502-301c-11e6-9638-cacd60c61e4e.png)

**Comment by licaon-kter** [comment]
Pics with battery details for Syncthing and Display and maybe Android OS ?

**Comment by therealmarv** [comment]
I will try to make new ones tomorrow (the ones I have right now are flawed because I'm not moving and with Wifi) while traveling and without WiFi.

**Comment by therealmarv** [comment]
I realized Syncthing does not use any battery when completely turned off. Need to do some more testing, so the problem is only on battery usage although mobile connection is used and syncing on Wifi is only enabled.

**Comment by Nutomic** [comment]
If you enable sync only on wifi, Syncthing won't even be running when you're not connected to a wifi. So there shouldn't be any battery usage on mobile data. The battery stats are aggregated over the entire runtime, so it probably includes times when you were on wifi.
