### ISSUE TITLE
0.15 0.16 first impression

### ISSUE THREAD

**Issue by merlinuwe** [syncthing/syncthing-android#673]
First impression:
wrong release number
upnp checkbox doesn't stay activated
crash without reason
Language stays selected (+)

**Comment by licaon-kter** [comment]
Not sure what you mean.
What is `0.15 0.16` ?

**Comment by merlinuwe** [comment]
The release 0.13.5 is shown, but 0.13.6 is distributed.  (sorry, I watched soccer with one eye ;-)
Am 12.06.2016 23:11 schrieb licaon-kter <notifications@github.com>:Not sure what you mean.
What is 0.15 0.16 ?

**Comment by lkwg82** [comment]
The app is released with a fixed bundled version. 0.13.5 is the bundled one.
