### ISSUE TITLE
Feature request: "Wifi-only" sync for specific folders

### ISSUE THREAD

**Issue by twckr** [syncthing/syncthing-android#676]
Hi,
I would find a feature useful that allows to exclude specific folders from syncing while on mobile data connection. For example I have a folder with todo-list, documents etc. that I would like to be always up-to-date while others (pictures etc.) contain loads of data and don't need to be on the latest version at all the time.

What do you think about this idea?

Thomas

**Comment by wweich** [comment]
dup of #511
