### ISSUE TITLE
Support different Pull Orders

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-android#677]
Hi

it would be very nice if oldestfirst is the default puller because file dates get screwed up if it is random or any other. I personally rely on the date orders in my daily use so I would appreciate if the default value is that.

thanks

**Comment by AudriusButkevicius** [comment]
Android does not allow adjusting dates, so they will be screwed up anyway.

**Comment by AudriusButkevicius** [comment]
Sorry, that doesn't matter, if the order is right.

**Comment by gerroon** [comment]
Or it would be nice if this is offered in the adding a share interface so that the user can choose whatever she wants (like in the web gui)

**Comment by lkwg82** [comment]
I think this feature request turns obsolete at least very less relevant with the new delta updates in v0.14.1 of syncthing.

(Suggest closing this.)

Anyway thanks for your suggestion.

**Comment by capi** [comment]
@lkwg82 I don't see the connection between delta-indexes and puller-order?

**Comment by lkwg82** [comment]
Mhm ... my thoughts were: when it starts earlier, it completes earlier. So it becomes less relevant in which order.

Aah, I mixed delta updates (which already is) and delta-indexes. So from this point of view there is no connection.

**Comment by Magissia** [comment]
Android allows setting dates when root is available, don't forget people that has root.

**Comment by licaon-kter** [comment]
@Magissia Root is broken at the moment #453

**Comment by Catfriend1** [comment]
Does the pull order change dates? I thought it is the queue sorting which files comes when to sync. I think we should add it defaulting to random to the edit folder UI.

**Comment by AudriusButkevicius** [comment]
pull order is the download order, there is no reason not to provide all of them.
