### ISSUE TITLE
Error external storage sync (it says can't access .stversions) 

### ISSUE THREAD

**Issue by orangpelupa** [syncthing/syncthing-android#678]
Maybe can be fixed by making syncthing invoke the android "external storage selector" ap it can get proper permission? 

Like when you install es file Explorer. Then paste some stuff to external SD card. It will invoke the "external storage selector" to make it have the proper permission. 

I'm on CM13.

**Comment by Nutomic** [comment]
The problem is that Go doesn't (yet) support the APIs required to access external storage devices.
