### ISSUE TITLE
Photo Backup not supported

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#685]
I have noticed that using Syncthing as a photo backup - which is pre-included by default into the Android app - doesn't *really* work as a photo backup. 
It simply mimics my device DCIM or photos folder, committing changes both ways. 

A true photo backup system should:
A) Back up my photos from my Phone to my other device
B) Not commit changes to my phone made from the other device
C) Allow me to delete photos on my phone without worrying they will actually be deleted on my other device - The one I am backing up to.

**Comment by licaon-kter** [comment]
> B) Not commit changes to my phone made from the other device

Make the phone as MASTER for that folder

> C) Allow me to delete photos on my phone without worrying they will actually be deleted on my other device - The one I am backing up to. 

Not in scope, use a separate task on that other device to backup files somewhere else.

**Comment by Nutomic** [comment]
A) It does that.
B) The default camera folder is a master folder by default. That means it won't accept changes from other devices.
C) You can do this with the "File versioning" setting on the folder on another device.

**Comment by licaon-kter** [comment]
> C) You can do this with the "File versioning" setting on the folder on another device.

Yes and no, yes the files are still there but moved ( to the *.stversions* folder) and renamed.

**Comment by jebeld17** [comment]
Exactly, licaon. 
This is a problem. Why complicate the issue when the user should just have a sole backup location? Adding file versioning is just batting around the issue. 

Users that want to use ST as a means of backing up photos and media want something that will put all their information in one database, just like how Microsoft OneDrive backs up photos into one sole location, or even BitTorrent Sync.

**Comment by licaon-kter** [comment]
@jebeld17 Yes and no, syncthing just syncs things around, it's not a backup tool.
Anyway, this needs to be discussed on [Syncthing](https://github.com/syncthing/syncthing) proper and not here since this is just an Android wrapper.

**Comment by bigbear2nd** [comment]
Please use the feature "ignore deletes" on the Server. It covers your C) usecase, without the file versioning.
See https://github.com/syncthing/syncthing/issues/584

**Comment by jangrewe** [comment]
FYI: It's called "SYNCthing", not "BACKUPthing"...

**Comment by jebeld17** [comment]
And your point is?
If it were truly a SYNCthing, there would be no need for extra or excessive settings and permissions regardless.

**Comment by jangrewe** [comment]
My point is that you are complaining about stuff that isn't really a problem of Syncthing, but a mixture of ignorance and reporting and non-issue to the wrong project (as this is not the Android app).

Good luck with a different software then...

**Comment by bigbear2nd** [comment]
Can this please be closed? 
The functionality requested can be achieved with "Master Folder" on the phone + "Ignore Deletes" on the Server + Backup Software on the Server....

**Comment by capi** [comment]
I agree that it's supported, even though it's clearly non-obvious how to set it up correctly for new users. I'll close the issue, because any change to how Syncthing works in this regard are outside the scope of the Android application and I'd suggest opening an issue in the Syncthing project.

@jebeld17 Please re-open, if you feel otherwise.

**Comment by jebeld17** [comment]
I don't understand why this was closed. (Sorry, I'm just now getting back onto GitHub)

This is simply a feature request. It doesn't need to be closed or disregarded, I think users can benefit from this if they use it.

**Comment by AudriusButkevicius** [comment]
You have not explained whats not there. if you read the above posts its explained how to achieve what you are looking for.

**Comment by jebeld17** [comment]
But it's not readily available for the average user. It involves finishing around with the settings in order to hope it works just right.

**Comment by jebeld17** [comment]
@bigbear2nd I did not see your response until now, Thank you.
