### ISSUE TITLE
"Run Syncthing as Superuser" should be disabled in settings or at least the caution message should be different

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#688]
unless #453 more or less resolved.

Here I saw opinion about this option:  
> [DO NOT ENABLE ROOT](https://github.com/syncthing/syncthing-android/issues/687)

, but inside of the program itself one sees only a timid  
> This may cause various problems with Syncthing and with your device. Use at your own risk.

which is not strong enough for "it does not work at all and you can't easily disable it without reinstalling" case. Determined users should be able to build SyncthingAndroid with the option visible.

The setting should get available again as experimental when at least users may go back after discovering the root mode does not work and when handling the revocation of root privilege when using this setting is implemented.

As a minimum there should be additional message suggesting user to review #453 before experimenting with superuser mode.

**Comment by licaon-kter** [comment]
It's in "Experimental", that's enough, imho, if you choose to enable it and it works (for you) great.

**Comment by vi** [comment]
Message may be worded like this:

    This is very experimental and unstable feature.
    You may be unable to turn it off if it fails after turning on.
    See issue #453 for more details
