### ISSUE TITLE
Syncthing version in changelog for 0.7.21

### ISSUE THREAD

**Issue by blablatros** [syncthing/syncthing-android#691]
This is a minor issue. In the changelog for 0.7.21 it is written "updated Syncthing to 0.7.13" instead of 0.13.7

**Comment by wweich** [comment]
Just updated the GitHub release notes, but I can't / don't know how to change the release notes in the Play Store, so that has to be done by @Nutomic or @Zillode.

**Comment by Nutomic** [comment]
Whoops, fixed in Play Store.
