### ISSUE TITLE
0.14 support (preferably mixed version support)

### ISSUE THREAD

**Issue by paulhargreaves** [syncthing/syncthing-android#696]
It's been like 23 hours ;-)

Seriously though, while we wait for versions of SyncThing that don't break the protocol on upgrade, can you bundle both 0.13 and 0.14 and have us choose? That way upgrading Android to 0.14 won't force everyone to have to upgrade all their machines, and vice-versa.

**Comment by capi** [comment]
Bundling both and choosing would be way harder than going the way we did until now: just bundle the new version.

Maybe this release would also be the time to change the version scheme of the Android version and start with a 0.14.0 version instead of 0.7.22. So that at least it's clear from `major.minor` what the supported Syncthing version is.

**Comment by Nutomic** [comment]
I'm currently in the last days of my bachelor thesis, so I don't have time to work on Syncthing. But I'll try to get it done in the next days.

Seperate versions would mean quite some extra effort, which I don't feel is worth the effort. 

I'm not sure if going to 0.14.0 is a good idea. That also suggests we should go to 1.0 at the same time as Syncthing, and I don't feel we're ready to do that soon.

**Comment by capi** [comment]
I can understand the 0.14.0 vs 1.0.0 argument. It's a good one.

 So 0.7.22 or 0.8.0 then?

**Comment by gdt** [comment]
I don't think avoiding 1.0 is that important.   People attach all sorts of significance to version numbers, and that is essentially wrong.

The big thing is that users can know which incompatible version of syncthing the android client can interoperate with.

And, I think there is merit until waiting until 0.14 has had a few micro releases before updating.  This incompatibility, while not syncthing-android's fault, is a major negative for dealing with syncthing, and having a bit of time for packaging systems to think about upgrading would help.  Perhaps that's already true.

**Comment by Nutomic** [comment]
I will definitely go with a new minor version (so 0.8.0), to make it less confusing.

I think Syncthing is stable enough at this point that we can update right away, seeing as there were beta releases and all. It's just that I don't have the time right now. Syncthing v0.14 also allows for better backwards compatibility, so it shouldn't be such a big problem in the future.

**Comment by scienmind** [comment]
Regarding the version name convention, how about keeping something like: 
0.8.0-0.14.0

**Comment by AudriusButkevicius** [comment]
That does not follow semver.

**Comment by scienmind** [comment]
Would it be possible at some point, to allow core ST to update itself as it does on standard linux/windows? Without requiring a wrapper's update?

Or is there an inherent android limitation preventing this?

**Comment by wweich** [comment]
Updating Syncthing while the wrapper app doesn't support the new config format and API changes (both happened before) isn't a good idea.

**Comment by scienmind** [comment]
It makes sense for minor/major versions, but at least allowing patches through (Major.Minor.Patch) would  resolve more problems than it'd create IMHO.

**Comment by Nutomic** [comment]
Automatic updates of apps (or parts of apps) are forbidden by both Google Play and F-Droid. If you want that, you could compile it yourself.

**Comment by pit001** [comment]
... and good luck with your bachelor thesis !

**Comment by Nutomic** [comment]
Thanks, it's almost finished :)

**Comment by canton7** [comment]
> That does not follow semver.

Semver is only important for libraries, where library users need to know whether they can upgrade without things breaking. It makes little sense for user applications.

**Comment by Nutomic** [comment]
I've just published version 0.8.0, which includes syncthing v0.14.0

**Comment by RunasSudo** [comment]
@Nutomic FYI, the [F-droid build of 0.8.0 is failing](https://f-droid.org/wiki/page/com.nutomic.syncthingandroid/lastbuild_99)

**Comment by Nutomic** [comment]
@RunasSudo That's a problem on their side, because they don't have the latest support library. I pinged @mvdan on IRC.

**Comment by fti7** [comment]
Could you please (If you have time) Upgrade Syncthing to 0.14.2 - It now includes Delta Index Transfer - One of the Most wanted features on Mobile Devices :-)

**Comment by mvdan** [comment]
Apologies for the fire on our side. It should all be fixed soon.

**Comment by Schroedingers-Cat** [comment]
Still no update in fdroid: https://f-droid.org/wiki/page/com.nutomic.syncthingandroid/lastbuild_99

**Comment by jonasdemoor** [comment]
The people from F-Droid have pushed an update for Syncthing to their repos. All my devices are working perfectly now. Big thanks to both the F-Droid and Syncthing teams :)

**Comment by mvdan** [comment]
That took an embarassingly amount of time. Most of us were on vacation and it was a tricky issue to track.

**Comment by capi** [comment]
I'll close the issue now, since all our markets have 0.14 now, and 0.13 versions are still available from f-droid.
