### ISSUE TITLE
App crash adding device

### ISSUE THREAD

**Issue by erikhubers** [syncthing/syncthing-android#698]
Getting appcrash when trying to add a device by pressing on de + sign on the devices tab.

_Edit:_ Same happens accepting device add request via notification.

See log below for logcat message.
[appcrash_syncthing.txt](https://github.com/syncthing/syncthing-android/files/374756/appcrash_syncthing.txt)

Version used: 0.7.21

**Comment by Nutomic** [comment]
Duplicate if #690. I'll leave this issue open until the new version is released, so other people can see it.

**Comment by erikhubers** [comment]
I'm sorry for the duplicate issue.

**Comment by lkwg82** [comment]
This has been fixed with v0.8.0 see https://github.com/syncthing/syncthing-android/releases/tag/0.8.0
