### ISSUE TITLE
Please upgrade the protocol

### ISSUE THREAD

**Issue by Tyrkys** [syncthing/syncthing-android#699]
My localhost on PC when i want connect my android say:
Connecting to "localhost" (syncthing v0.13.7, ID.........): the remote device speaks an older version of the protocol (v0.13) not compatible with this version

My desktops: v0.14.0, Linux (64 bit)
Android via play v0.13.7

Thanks, sorry for my Eng. lang.

**Comment by wweich** [comment]
dup of #696
