### ISSUE TITLE
Changes are not propagated 

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-android#702]
I am using 0.7.21 from Fdroid.

Whenever I move or delete a file the change is not pushed to other devices.  I always have to restart it. I 

I tested this with 5.1.1 and 6.0. I checked to see if the syncthing binaries were crashed multiple time, no the webserver etc all work. So maybe the inotify is failing to detect the changes?

**Comment by licaon-kter** [comment]
Web UI -> folder -> Edit > Advanced -> rescan interval -> 1800 on both devices-> ok , does it help?

**Comment by Nutomic** [comment]
Are you sure the same version of Syncthing is running on all devices? Do you see anything in the logs? Especially on the Android side.

@licaon-kter Iirc we automatically reset the rescan interval to 3 days on every restart (but I might be wrong).

**Comment by gerroon** [comment]
@Nutomic 

All my devices are using the latest version from Fdroid. 

I will check the logs later.

**Comment by gerroon** [comment]
@Nutomic 

I see that the android client constantly doing this  Not sure if related. 

"I/SyncthingNativeCode( 1666): [27KPW] 01:55:34 INFO: Established secure connection to ZB4ME7E-RLNN5QK at 192.168.xxxxx:36552-192.168.xxxxxxxx:22000 (TCP (Client))
I/SyncthingNativeCode( 1666): [27KPW] 01:55:34 INFO: Device ZB4ME7E-RLNN5QK client is "syncthing v0.13.7" named "xxxxx"
I/SyncthingNativeCode( 1666): [27KPW] 01:55:34 INFO: Connection to ZB4ME7E-RLNN5QK closed: EOF
I/SyncthingNativeCode( 1666): [27KPW] 01:55:35 INFO: Established secure connection to 
T3VYBHN-QQBPMA2 at xxxxxxx:40655-xxxxxxxxx36640 (TCP (Client))
I/SyncthingNativeCode( 1666): [27KPW] 01:55:35 INFO: Device T3VYBHN-QQBPMA2 client is "syncthing v0.13.10" named "xxxx"
I/SyncthingNativeCode( 1666): [27KPW] 01:55:35 INFO: Connection to QQBPMA2 closed: EOF
"

and also such this
INFO: Failed to exchange Hello messages with T3VYBHN-QQBPMA2 (xxxxxx:36640): read tcp 192.168.xxxx:40672->xxxx:36640: i/o timeout



I trimmed some info there for privacy reasons.

**Comment by Nutomic** [comment]
It sounds like Android is killing Syncthing on your device. Have you tried [these things](https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions#why-is-syncthing-stopped-after-some-time)?
