### ISSUE TITLE
WiFi not detected

### ISSUE THREAD

**Issue by eightys3v3n** [syncthing/syncthing-android#703]
Syncthing does not detect wireless network connection if the wireless network does not have internet access. 

Android 6.0.1, Nexus 6P

**Comment by wweich** [comment]
This is expected. If the Wifi has no internet access, Android will not tell apps, that it exists.

To get it syncing, you need to temporarily disable mobile data.

**Comment by eightys3v3n** [comment]
With mobile data disabled before I join the WiFi or started syncthing it did not appear to count the WiFi as being connected.

**Comment by eightys3v3n** [comment]
I'll find my own solution I suppose, as this is now closed. Thanks anyways.

**Comment by wweich** [comment]
I tested this the other day. If I disable mobile data before getting in range of a internet-less wifi, and than connect to it, Syncthing will start automatically as soon as the wifi is connected.

Can you reliably reproduce this?

**Comment by eightys3v3n** [comment]
No. I must ha e been mistaken as now if I disable mobile data before I attempt anything, syncthing does pickup the wireless even without Internet access. Since that's a pain I will be looking for a way to use Tasker to start and stop syncthing. Thank you for your information and time.
