### ISSUE TITLE
WebGUI username and password are not saved

### ISSUE THREAD

**Issue by zechnkaas** [syncthing/syncthing-android#704]
Hi,
I have changed the listener to 0.0.0.0:8384 and also set username and password to access the website from other devices. 
But i noticed that there is no logon. i can directly access webpage without the need to logon. (Also the warning will be shown on the Website)
Tried to restart app/phone but it doesn't make any difference. (Android 6.0.1 App V0.8.0)

**Comment by Magissia** [comment]
This is a security issue

**Comment by Nutomic** [comment]
So apparently the environment variable `STGUIAUTH`, which we used to set the username/password, was removed from Syncthing. This means we have to set them in a different way, which will require some effort.
