### ISSUE TITLE
Syncthing binary: Build with GOOS=linux crashes > v0.14.1

### ISSUE THREAD

**Issue by capi** [syncthing/syncthing-android#706]
Since `v0.14.1`, the Syncthing binary requires a temporary directory, which for the `linux` flavor is `/tmp`. Unfortunately, this does not exist on Android, causing a panic.

This can be worked around, by setting an environment variable `TMPDIR` to `mContext.getCacheDir().getAbsolutePath()`, but I think it would be sensible to work using the `android` flavor of Go over the `linux`, since I can imagine, there are other subtle differences to various aspects.

Unfortunately I don't know much about Go and the native binary for Android, so I don't feel quite up to the task of changing that. Maybe this could be looked into together with #697?

**Comment by Nutomic** [comment]
@Zillode switched to `GOOS=linux` some time ago due to a problem. I don't remember what that was, though.

**Comment by AudriusButkevicius** [comment]
I think it was related to the cgo chain which we do not use anymore.

**Comment by Nutomic** [comment]
@capi I guess it would help if you post a crash log here.

**Comment by AudriusButkevicius** [comment]
It can't write to /tmp as it does not exist on android.

**Comment by capi** [comment]
It's already fixed in my PR. We just need to set `TMPDIR` (which I did) to something that exists. The Go temp-directory function takes that into account, and defaults for `/tmp` for Linux, and `/data/local/tmp` on Android. It's just one example where Linux uses other defaults than Android.

(Footnote: `/data/local/tmp` doesn't work reliably accross ROMs anyway, `context.getCacheDirectory()` works reliably, that's what I use.)

**Comment by capi** [comment]
@Nutomic I'd consider this more an "enhancement" than a "bug". The building as "linux" doesn't cause the crash, it would still happen with "android" on most ROMs, it was just a suggestion by @calmh that we should working towards compiling with GOOS=android to avoid subtle problems caused by differences between Linux and Android.

**Comment by Nutomic** [comment]
So this is an issue for something that you already fixed in your branch? I'm more or less on vacation now, so I don't have much time to look into this :p

**Comment by capi** [comment]
It's a ticket for something that we should change in the future, since it caused an issue and likely will cause more issues in the future.

Enjoy your well-earned vacation.

**Comment by capi** [comment]
@AudriusButkevicius Just noticed now, that you changed my request to build with GOOS=android to a bug-report that it crashes with Linux. Actually this ticket was meant to potentially change our build to GOOS=android if possible. Because if it's just about the crash, PR #707 will already fix this issue.

**Comment by AudriusButkevicius** [comment]
@lkwg82 changed the title and left a mistake, I just ckrrected the mistake.
