### ISSUE TITLE
Syncthing for Android TV - service dies after 30 minutes or so

### ISSUE THREAD

**Issue by holyoaked** [syncthing/syncthing-android#717]
I have Syncthing installed on my Nvidia Shield TV. I use it to sync media with a seedbox so that I can watch media in the living room without the need to stream or transcode anything.

At least, that's what i want to use it for. I've been trying for a week and can't seem to keep the Syncthing service running. It reliably stops after 30 minutes or so. This is with all relevant experimental options enabled to try to keep the Syncthing process from being killed. It is still killed.

This happens whether the Shield TV is 'awake' or not. In fact, the Shield doesn't go to sleep at all. I can be using the Shield for something else, or not using it at all, but Syncthing will always stop itself after 20-30 minutes or so.

After Syncthing dies, I can't restart the Syncthing service without plugging a mouse into my Shield TV - because I can't hit the 'Restart' button without a mouse (see issue #486). The app does not seem to 'repair' itself from this state, I *have* to hit the 'Restart' button. It's extremely inconvenient having to grab a mouse and plug it into the Shield TV every time this happens. **edit:** It seems that Force-Stopping the app and launching it again does restart the Syncthing service.

Expected outcome: Syncthing continues running in the background, or at least is able to restart itself in the event of a failure.

### Version Information

    App Version: 0.8.1
    Syncthing Version: v0.14.3
    Android Version: Android Marshmallow 6.0, Nvidia Shield TV

**Comment by Nutomic** [comment]
[Did you try this](https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions#why-is-syncthing-stopped-after-some-time)?

**Comment by holyoaked** [comment]
Hey,

There is no battery optimisation on Android TV. There isn't a battery, so no need for battery-saving features.

I've enabled both of those experimental features. The service is still killed. :(

**Comment by Nutomic** [comment]
Then I don't know. Can you check the logs for anything suspicious?

**Comment by holyoaked** [comment]
Hey,

The latest version of SyncThing has fixed this issue for me. It's got an uptime of 19 hours now, which is way more than it ever got before.

Just thought you should know, though, that the update completely wiped my Syncthing configuration. I'll be making backups from now on! :)

**Comment by Nutomic** [comment]
That's kind of surprising, because we didn't change anything that would have stopped the service. Unless it was a crash maybe. And I don't know why the update would wipe the configuration either.
