### ISSUE TITLE
Support Staggered Versioning

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing-android#718]
Seems like the native in-app UI doesn't support all versioning options..
1. Enable "Staggered Versioning" via WebUI 
2. Restart to apply config.
3. Review folder's details in-app

Result: "Keep Versions = off"
Expected result: something more reflective of the actual config in place
### Version Information

```
App Version: 0.8.1
Syncthing Version: v0.14.3
Android Version: Android 5
```

**Comment by jmintb** [comment]
As fare as I can tell there isn't a framework currently in place to get the versioning from the config file. Is this correct or am I missing something?
Not to say that it is not possible to get the versioning from the config, just that it hasn't been done yet.

**Comment by jmintb** [comment]
I have started adding functionality that would support all the types of file versioning, I just remembered that this issue only mentions staggered file versioning. 
Should I just stick to adding staggered file versioning or can I add an interface to choose between all the types of file versioning and configuration options?

**Comment by Nutomic** [comment]
I guess it might be easier if you do only staggered versioning at first. But thats your decision. It would be great to have all types of versioning supported :)

**Comment by scienmind** [comment]
I filed this issue when I discovered that staggered versioning (that I use most often) is missing from the UI.
There was no intention no imply that "only" staggered versioning should be implemented. 

Basically - if it is available in the web-ui, it should be available in the native UI as well :-)

**Comment by jmintb** [comment]
Question, if Syncthing is not given a parameter like amount of versions to keep for simple versioning, will it revert to a default value or just not work?

**Comment by jmintb** [comment]
Btw I forgot to mention that I chose to continue working on functionality that would support all versioning types. I have a version which works now, should I post an image of what the UI looks like before submitting a pull request?

**Comment by scienmind** [comment]
> should I post an image of what the UI looks like before submitting a pull request?

it's always useful for any kind of UI-altering PRs

**Comment by Nutomic** [comment]
You can just open a PR with the code you have now, and attach screenshots in the PR.
