### ISSUE TITLE
DNS patch not working with Go 1.7

### ISSUE THREAD

**Issue by hafoal** [syncthing/syncthing-android#723]
Building GO fails with:

HEAD сейчас на 5dc7525 syscall: mksyscall_windows.go: put path separator in suffix for matching GOROOT
Applying /home/user/syncthing-android/patches/golang/all/dns.patch
patching file net/dnsclient_unix.go
Hunk #1 FAILED at 279.
1 out of 1 hunk FAILED -- saving rejects to file net/dnsclient_unix.go.rej
patching file net/dnsconfig_unix.go
Hunk #1 FAILED at 8.
Hunk #2 FAILED at 33.
Hunk #3 succeeded at 126 with fuzz 2 (offset 16 lines).
2 out of 3 hunks FAILED -- saving rejects to file net/dnsconfig_unix.go.rej

As i understand there are no strings in these .go files which are had to be replaced or I am doing something wrong?

Version Information

App Version: 0.8.1
Syncthing Version: 0.14.4
Android Version:

**Comment by Nutomic** [comment]
Ping @AudriusButkevicius

**Comment by AudriusButkevicius** [comment]
I think you removed the reset --hard as part of the build. Also, maybe the patch does not apply on go 1.7

**Comment by hafoal** [comment]
Yes, when i cloned go 1.6 branch, it didn't break in this step.

**Comment by Nutomic** [comment]
Do we still need the patch with Go 1.7? I feel like they should have fixed the DNS by now.

**Comment by AudriusButkevicius** [comment]
There was some change to dns in 1.7, so someone needs to test it.

**Comment by AudriusButkevicius** [comment]
Sadly I nuked all tue android stuff from my vm as i ran out of space. I can make a new patch for go 1.7 if its still needed.

**Comment by hafoal** [comment]
When i skipped this patch with 1.7, app didn't find remote device.

**Comment by Nutomic** [comment]
Confirmed. I compiled with Go 1.7, and it doesn't connect to announce or relay servers with the default config.

@AudriusButkevicius Can you look into this?
