### ISSUE TITLE
0.8.2 Error message after Menu > Exit

### ISSUE THREAD

**Issue by NickPyz** [syncthing/syncthing-android#725]
After Play Store version update from 0.8.1 to 0.8.2, I am now getting the following pop-up message after I exit using the app's menu:

"Unfortunately, Syncthing has stopped."

Of course, I wanted it to stop, so I believe this is just a cosmetic bug. Never saw it in earlier versions tho ..
Thnx.

### Version Information

    App Version: 0.8.2
    Syncthing Version: v0.14.3
    Android Version: Android 4.4.4 (unrooted)

**Comment by Nutomic** [comment]
Right, the Android API is a bit weird there, so I called it wrong.
