### ISSUE TITLE
Reorganize App Settings

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing-android#732]
I thought about reorganizing the settings, so that they are easier to navigate. Here's what I came up with for top level categories:
- Run Conditions (any idea for a better title?)
  - only on wifi, only while charging, etc
  - etc
- Network
  - discovery, username, etc (basically all Syncthing settings)
- Behaviour
  - advanced folder picker, notification
- Experimental
  - same as now
- About
  - versions, log, issue/donate links

I'm not sure what should happen with import/export, debug options, and reset database. Any idea about these?

**Comment by NYPD** [comment]
"Run Conditions" sounds ok to me. "Restrictions" maybe? Probably sounds a bit too negative.

**Comment by wweich** [comment]
Would that be sections or sub menus?
Where would the import/export settings, debug options and reset db go?

**Comment by Nutomic** [comment]
@wweich I think sub menus will be better, otherwise it will take up too much space. As I wrote, I don't know where these should go, and I'm looking for suggestions ;)

**Comment by licaon-kter** [comment]
Import/Export in a Backup submenu
Debug in Experimental

**Comment by Nutomic** [comment]
Debug isn't really experimental though. I thought of having a "Debugging" category instead, together with logs and reset db. Also not sure if we should have a backup category with only two items.

**Comment by licaon-kter** [comment]
It's in line with those items in Experimental, don't touch them if you don't know what you are doing.
Same for logs and reset db.

**Comment by Nutomic** [comment]
Debug options can't really break anything. In the worst case, it will just spam your logs.

**Comment by Nutomic** [comment]
Implemented in 0.9.0-beta1.
