### ISSUE TITLE
Syncthing used lots of Mobile Data despite settings to the contrary

### ISSUE THREAD

**Issue by smithdtyler** [syncthing/syncthing-android#734]
I installed Syncthing on my Android 6.0 LG G3 this morning. I immediately went to settings and selected "Sync only when charging" and "Sync only on wifi".

A couple of hours later, I checked my data usage and saw that Syncthing had used 1.6GB!

I disabled mobile data for Syncthing via the Android mobile data settings.

I restarted Syncthing several times during the initial setup as I added new folders to sync, but otherwise didn't do anything fancy (that I'm aware of).

Version Information

Syncthing Version: v0.14.5 (Installed from Google Play)
OS Version: Windows 7, Raspbian Linux

**Comment by licaon-kter** [comment]
Pics of the data info?

**Comment by smithdtyler** [comment]
Attached, if github accepts attachments on email replies.

I set the "restrict background data" option after seeing this problem.

On Aug 28, 2016 14:59, "licaon-kter" <notifications@github.com> wrote:

>

> Pics of the data info?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
<https://github.com/syncthing/syncthing-android/issues/734#issuecomment-242995806>,
or mute the thread

**Comment by smithdtyler** [comment]
Is this what you're looking for?

![screenshot_2016-08-28-15-05-59 1](https://cloud.githubusercontent.com/assets/8142684/18036522/07ba8b26-6d32-11e6-83d3-d194d20e359e.png)
![screenshot_2016-08-28-15-05-59](https://cloud.githubusercontent.com/assets/8142684/18036523/0a487e84-6d32-11e6-85ef-f22a608b2fb2.png)

**Comment by AudriusButkevicius** [comment]
It's possible that it pushed through 1.6GB while you were setting it up. Also if it's sync on wifi only, you shouldn't even be able to adjust settings as syncthing would be killed.

**Comment by smithdtyler** [comment]
Yikes, that's not ideal :/

**Comment by capi** [comment]
According to your screenshot you _are_ on WiFi. Are you sure the data you are looking at does not include WiFi data?

**Comment by smithdtyler** [comment]
Yes. I've synced at least 4 gigs today and my data status still reports 1.6GB for Syncthing. I started the sync at home, then left. I'm guessing it continued after I left home wifi, finishing the final 1.6gigs on mobile data.

**Comment by smithdtyler** [comment]
I was syncing two directories from my phone to my home LAN - a photos directory and a music directory. One was marked 'master' and the other was not. They consisted of about 3,000 total files, averaging about 4MB each. 

I was setting up my nodes at the time, so I restarted the app multiple times.

**Comment by Nutomic** [comment]
Can you still reproduce this problem with the latest version? If so, can you post logs?

**Comment by smithdtyler** [comment]
I've since stopped using the mobile version, so I'll close this as unable to reproduce.
