### ISSUE TITLE
Scanning folders when folder's content update

### ISSUE THREAD

**Issue by hafoal** [syncthing/syncthing-android#735]
I noticed, that app scans folders more often than entered in "Rescan Interval" setting. As I understood, folders are scanned after any update inside them. Is there a way to disable it and scan folders only on specified interval? Because for frequently updated folders this makes high battery consumption.

### Version Information

    App Version: 0.8.1
    Syncthing Version: v0.14.4
    Android Version: Android 5.0.1

**Comment by wweich** [comment]
It should result in less battery consumption, as not the full folder is scanned, but only the changed files.

**Comment by hafoal** [comment]
@wweich , app scans only the changed files by default or it should be configured?

**Comment by wweich** [comment]
Syncthing Android uses inotify to watch for file system changes and notifies Syncthing only about those changes. Syncthing will then only scan that file or folder (for many changed files in one directory, syncthing will consolidate that to scanning the directory).
If there aren't any changes for a long while, the syncthing folder will do a full scan to check for missed changes.

There is nothing to configure.

**Comment by hafoal** [comment]
@wweich, Thanks for answer.
