### ISSUE TITLE
In sync percentage calculation will need an update

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing-android#736]
The calculation [here](https://github.com/syncthing/syncthing-android/blob/8d482f907d0b22487b50d26bc7cc9cc0d4721cea/src/main/java/com/nutomic/syncthingandroid/syncthing/RestApi.java#L666) is going to need a tweak. Since https://github.com/syncthing/syncthing/commit/5b37d0356cb3ff03edb45a79899dd7096403208a deleted files are no longer baked into the `needBytes` attribute, as that was buggy and incorrect. We fudge the percentage given to account for it anyway, but since this calculates the percentage on it's own it needs to take into account the new `needDeletes` attribute.

**Comment by capi** [comment]
v0.14.6 is now out, so when we upgrade to this version, we should also make the required changes for this issue here.

**Comment by Nutomic** [comment]
Feel free to code that. I'm moving to Korea next week, so I probably won't have much time.
