### ISSUE TITLE
Tasker plugin for enabling and disabling Syncing

### ISSUE THREAD

**Issue by mikemol** [syncthing/syncthing-android#746]
I can program all kinds of rules and conditions in Tasker. Such as performing actions if I'm on a particular wifi connection, charging, with battery at a given level, with my phone flat on its face. It would be helpful if tying syncing to Tasker rules were possible.

**Comment by wweich** [comment]
We already have Intent Receivers which you can use to start / stop syncthing:
https://github.com/syncthing/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents
