### ISSUE TITLE
Provide option to ignore symlinks completely

### ISSUE THREAD

**Issue by moyamo** [syncthing/syncthing-android#748]
I have a linux folder which I'm sharing with my android phone. The linux folder contains symlinks. Syncthing continuously fails to sync the symlinks to my android phone.

It would be nice to have an option to ignore symlinks entirely.

**Comment by wweich** [comment]
You can disable `symlinksEnabled` in the advanced settings under "options".

**Comment by moyamo** [comment]
Do I have to enable this on both sides? IIRC I already did this on my android phone.

**Comment by Nutomic** [comment]
If you haven't figured this out yet, I suggest you open a thread on the forum. The issue tracker isn't good for support.
