### ISSUE TITLE
statistics

### ISSUE THREAD

**Issue by axet** [syncthing/syncthing-android#751]
Hello!

According to https://data.syncthing.net/ here is only 20 android devices. But app download page shows 50k downloads.

Is it correct data? You have only 20 active installs?

**Comment by licaon-kter** [comment]
Only those 20 chose to submit `anonymous stats` I guess.

/mark as invalid

**Comment by wweich** [comment]
The Android version is build as Linux arm. IIRC this is because setting the GO builder to android has some issues.

**Comment by Nutomic** [comment]
Google Play shows around 30,000 active installs. Although the counting method is probably different than our stats, and does not include F-Droid.
