### ISSUE TITLE
changing listen address for syncthing daemon fails (but works in web interface)

### ISSUE THREAD

**Issue by wararjey** [syncthing/syncthing-android#753]
1. Change Listen address to something like "tcp://:_portnumber_"
2. A prompt appears to restart syncthing, let syncthing restart
3. look up listen address setting again, it still shows default

I can work around this issue by changing the listen address in the web interface, after having done that, the changed setting shows up correctly on the in-app settings dialogue.
### Version Information

```
App Version: 0.8.6
Syncthing Version: v0.14.8
Android Version: Android 5.1 / Cyanogenmod 12 nightly 
```

Regards,
wararjey

**Comment by Nutomic** [comment]
Should be fixed in 0.9.0-beta1. If not, please open a new issue.
