### ISSUE TITLE
Problems with the SD card write access in Android 6.0

### ISSUE THREAD

**Issue by BlackDragon381** [syncthing/syncthing-android#758]
Problems with the SD card write access in Android 6.0.
Syncthing does not request access to these rights, unlike other applications.
There is no way to synchronize files if a folder on the SD card.

    App Version: 0.8.6
    Syncthing Version: v0.14.8
    Android Version: Android 6.0

**Comment by Nutomic** [comment]
See #29

**Comment by liotcheg** [comment]
Nutomic, are you sure this is the same issue?
In android 6.0 there seems to be a new API and an app needs to request the permission from a user at runtime.
Please check this link https://developer.android.com/training/permissions/requesting.html

**Comment by Nutomic** [comment]
You should get a request for that permission when you first start the app. Or you can check in the system app settings.

**Comment by BlackDragon381** [comment]
There is no this permission in settings for this app. There is now request when first start.
Other apps requests permission only when you try to use external card, they do it via Documents app.

**Comment by Nutomic** [comment]
Not in the app settings, in the system settings (under apps).

**Comment by wweich** [comment]
> requests permission only when you try to use external card, they do it via Documents app asking root folder of your SD.

That has nothing to do with permissions, but with the File Access API which apps need to use to access external sd cards in current versions of Android. There is currently not a good way to use them in GO, in which Syncthing is written.

The request at the first start of the Syncthing Android App is the permission request to access files in general. This is needed for Syncthing to work at all, hence the request on first start.

**Comment by BlackDragon381** [comment]
> Not in the app settings, in the system settings (under apps).
I can't find this settings.

**Comment by licaon-kter** [comment]
That might be moved by your ROM provider, do search in Android Settings for "Permissions"

**Comment by BlackDragon381** [comment]
I know where placed permissions for apps, but Syncthing haven't this permission (MIUI 8).
