### ISSUE TITLE
ST does not stop itself after disconnecting from charger

### ISSUE THREAD

**Issue by conrad-heimbold** [syncthing/syncthing-android#761]
Sorry if this is a double-posting, but I could not find this bug reported already. Please tell me the correct bug number, if it exists already. 
I enabled the setting "Sync only with charger" in Syncthing's settings (and not "Sync only in WiFi"). 
Now if I connect my phone to a charger and Syncthing starts, it does not stop itself after I disconnect it from the charger again. 
This is also the reason why it takes so much of the battery, I guess. 

When disconnected from the charger, Syncthing for Android should stop itself (same thing for WLAN). 

### Version Information

    App Version: 0.8.6
    Syncthing Version: v0.14.8-dirty
    Android Version: Cyanogenmod 13.0

**Comment by capi** [comment]
I noticed myself a few time. I think, that the bugs (battery and WiFi) are somehow related.

**Comment by conrad-heimbold** [comment]
Strange, now I can't reproduce the error anymore (I tried to collect a logcat, but there was no error!). I don't know anymore, what kind oft settings I had; but now everything is working very good! 

At least for me, this issue can be closed.

**Comment by conrad-heimbold** [comment]
Was it possible in some version (e.g. 0.8.4) before, to activate "Sync only with charger", although " Keep in the background" was disabled? I can loosely remember something like that...? With version 0.8.6, it is not possible anymore. That could have been the reason.

**Comment by Nutomic** [comment]
No, that was never possible (unless there was a bug).
