### ISSUE TITLE
Directory selector in folder creation dialog inaccessible on TV devices

### ISSUE THREAD

**Issue by The0x539** [syncthing/syncthing-android#762]
Expected behavior: pressing the "down" button on remote when Folder ID is selected, or "up" with the top device-share switch selected, will highlight the directory entry, which can then be opened to select a directory.
Actual behavior: The directory entry is skipped, proceeding straight down to the top device or straight back up to Folder ID. As such, folders apparently cannot be created without touch or pointer input.

Steps to reproduce: On a device with d-pad input, navigate to the folder creation screen and try to choose a directory.

### Version Information

    App Version: 0.8.6
    Syncthing Version: v0.14.8
    Android Version: Android 7.0 (Nexus Player)

**Comment by Nutomic** [comment]
Thanks for the report, fixed!
