### ISSUE TITLE
Won't connect over WiFi with proxy

### ISSUE THREAD

**Issue by benshep** [syncthing/syncthing-android#763]
I'm trying to connect with my phone at work. The work WiFi network needs a proxy defined (WiFi settings -> long-press network name -> Modify network). But Syncthing doesn't recognise this. My phone appears disconnected when on the WiFi network (it's fine on the mobile network).

### Version Information

    App Version: 0.8.6
    Syncthing Version: v0.14.8
    Android Version: Android 6.0.1

**Comment by AudriusButkevicius** [comment]
A http proxy is not good enough for syncthing to connect, it needs a socks proxy.

**Comment by benshep** [comment]
Well, OK. But Syncthing works fine behind the proxy on my PC. So I don't quite understand why Android doesn't do the same.

**Comment by AudriusButkevicius** [comment]
Potentially because your PC specifies a socks proxy in the environment for syncthing to connect to, where as your mobile doesn't.

**Comment by benshep** [comment]
Hmm. It's not at all clear what it's doing on my PC with regards to the proxy. I had the all_proxy variable variously set to "server:port", defined in capitals and lowercase, and set to "socks5://server:port", and not defined at all. In all of these cases there's no "Using proxy settings" line in the log, and it seems to connect absolutely fine (joining relays, making connections to other nodes).

**Comment by AudriusButkevicius** [comment]
You probably didn't set it up correctly if the log line does not show up. Still, the network could behave differently when connected via pc and via guest wifi, and perhaps the wifi network only permits outgoing connections via http proxy, where as on pc it allows connections as usual.

**Comment by benshep** [comment]
No - as I understand it (and I think I do), the wired and wireless networks behave exactly the same with regards to proxies - all connections need to be routed through the proxy.

**Comment by benshep** [comment]
OK, I managed to get it so the proxy line appeared in the log (I had "http_proxy" defined too without the socks5 prefix, maybe that was confusing it?).

Is there a way to set environment variables in Android? This isn't a killer issue; I can sync at home where I don't need a proxy. But it would be nice to get to the bottom of it.

**Comment by AudriusButkevicius** [comment]
Sadly thats usually for the network people to decide. Perhaps your OS is clever enough to provide the necessery settings in the envoronment for syncthing to work, yet your phone is not. i guess you can enable debug options on the phone and look at the logs why its failing to connect, but this is more of a support issue than anything else until proven otherwise and belongs on the forums.

**Comment by AudriusButkevicius** [comment]
Http proxy should not need a socks:// prefix, if anything it would break it.

**Comment by benshep** [comment]
Sorry, I meant I had http_proxy=server:port. I deleted that variable and it said "Found proxy settings".

**Comment by Nutomic** [comment]
No, you can't set a proxy server in the app. But feel free to open a new issue for that.
