### ISSUE TITLE
Where should Syncthing's status show up? Configurable both as notification or inside the app

### ISSUE THREAD

**Issue by conrad-heimbold** [syncthing/syncthing-android#765]
The Android Material Docs say, you should not use the notification bar for "Operations that don't require user involvement, like syncing information". 
Source: https://material.google.com/patterns/notifications.html 

Please respect these Doc's and do only show notifications, if files have been added or deleted, a new device wants to connect, or anything similar which is really a notification (and only appears once or twice, not permanently). 

If you want to know, what an app is doing in the background, just open that app! Syncthing should show its status (starting, running, paused, stopped) and reason for that (no wifi, not connected to charger, etc.) inside of the app, not in the notification area. Or at least, the notification for Syncthing's status should be dismissable! 

In my opinion, too many apps are already spamming my notification area with stuff that is not a notification!

**Comment by wweich** [comment]
The permanent notification is there to make it less likely for Syncthing to be killed. Other Apps do this as well.

If you don't want that notification, you can disable it in the settings.

**Comment by capi** [comment]
You can disable the notification. When using the "Run in Foreground" setting, this is even required by Android's API. If you don't, disable the notification. Many people want the notification to know that a heavy-weight process is running and using resources, so it won't get removed, I'm sure.

**Comment by conrad-heimbold** [comment]
I know that, but then I can't find out its status (running, paused, stopped) and reason (wifi, charger) for that.

**Comment by wweich** [comment]
The notification is only shown when Syncthing is running.

**Comment by conrad-heimbold** [comment]
OK, I see, a lot of people like that "misuse", so please put the status both inside of the app and in the notification, or make it configurable where it shows up.

**Comment by capi** [comment]
It already _is_ configurable, if/when it shows up.

**Comment by capi** [comment]
And the status of Syncthing inside the application is already shown. It is running while application is active and connection and syncing is shown. That's the entire UI.

**Comment by Nutomic** [comment]
Besides what was said, we use a low priority notification, so it should be hidden most of the time.
