### ISSUE TITLE
Set proxy from within app

### ISSUE THREAD

**Issue by benshep** [syncthing/syncthing-android#766]
I would like the ability to set a proxy within the app. On Windows (and presumably Linux) it's straightforward to set proxies using environment variables. On Android, not so much. Can we have this as a setting in the Settings menu please?

**Comment by ProactiveServices** [comment]
At the risk of hijacking this issue, if we could set any of the relevant environment variables it'd be handy. I currently need to use the STHASHING envvar to diagnose a possible hashing problem but can't.

**Comment by Nutomic** [comment]
@ProactiveServices That makes sense. Can you open a seperate issue please?

**Comment by Catfriend1** [comment]
@benshep This can only be achieved with the correct proxy exception as this would else break the web UI display in the app. I am not sure, how Syncthing core would get the proxy information being set on android app's side.
Would a linux env help here to tell st core to use a proxy @AudriusButkevicius?

**Comment by Catfriend1** [comment]
https://docs.syncthing.net/users/proxying.html says the following env vars are respected by syncthing.
export all_proxy=socks5://10.20.30.40:5060
export http_proxy=...
export https_proxy=...
