### ISSUE TITLE
Syncthing Android should allow to see files in folders

### ISSUE THREAD

**Issue by thanosa75** [syncthing/syncthing-android#770]
Currently the app does not support "click" for the folder name. It should allow clicking and a new file explorer (the system file explorer?) should execute and show the file contents.

Syncthing should allow the user to browse through to the folders that have been synced, since this is the main reason why we would want this application in the first place.

**Comment by licaon-kter** [comment]
So if you have a file manager why not use it directly instead of triggering intents from another app?

**Comment by thanosa75** [comment]
It is a feature request. Looking from the user's perspective, the Android application is not as user friendly - it only shows information but does not allow you to act on it.

The typical use-case is as follows:

a. I am Andy and I have installed syncthing on my QNAP NAS for syncing files to my Macbook. Web UI is fine; I added a couple of folders and I am ready to go. I've done the `brew install syncthing-bar` and now I have the syncthing on my Mac also.
b. I have an Android phone and found that a Syncthing app exists; Installed it!
c. I have synced my folders and now am ready to use.
c.1 I open the app to make sure the latest is there; also to check status since I'm a geek.
c.2 I see the folder synced; and I click on it. The system uses the default file manager to open the folder (which can be in a very obscure path, by the way)
c.3 I navigate within the folder to my file and click to open it. The system uses whatever handler for my file (e.g. a pdf reader) and I see my file!

Obviously, sync application like dropbox and box do this already. It just enhances the user experience.

**Comment by licaon-kter** [comment]
> c. I have synced my folders and now am ready to use.

No, you stop there, you are done, there is no USE after that, not for you, you just put the app in the background, you hide (or not) the notification and you use the device NOT the app.

> c.1 I open the app to make sure the latest is there; also to check status since I'm a geek.

How do you make sure "the latest" is there when you have 4032 files?

> c.2 I see the folder synced; and I click on it. The system uses the default file manager to open the folder (which can be in a very obscure path, by the way)

The app is for "syncing", use the file manager to "manage the files" and "see file".

> c.3 I navigate within the folder to my file and click to open it. The system uses whatever handler for my file (e.g. a pdf reader) and I see my file!

What next? Image viewer integrated? Image cropper? Intents to "share file"? Oh c'mon.

**Comment by thanosa75** [comment]
Hi again - thanks for your comments.

Please note that _I am not an android developer_ and I did not mean to say that you have to implement a file navigator/viewer or a cropper; just that the default launcher for a file explorer is used. If that was not clear pls receive my apologies.

If only the sync state is to be shown, surely the Web UI is fine either as directly going to 127.0.0.1:8384 or launching a browser window (#578).

Please consider this for the future - I only reiterate functionality that is present in  box/dropbox/btsync.

**Comment by Nutomic** [comment]
I think such a feature makes sense. Implementing it takes almost no effort, so I do t see why not. 

The only question is where should we put this? We can't open the file browser when you click on a folder list item, because that opens the folder settings. How about a menu item in the folder settings? (Next to delete folder)

**Comment by thanosa75** [comment]
Hi again ;) 

One idea is to  have the default action to trigger the functionality and the settings to be a small "cog" icon - a typical stereotype used for settings pages.

**Comment by Nutomic** [comment]
That makes sense if the main thing users want when opening Syncthing is to open a folder, and changing the folder settings is less important. But I don't know if that assumption is true.

**Comment by thanosa75** [comment]
Understood. I may be biased due to having used the BtSync android app for too long - dropbox also (same UX). The main use (_for me anyway_) is to go to the app, click on the folder, see a file (e.g. a text file with my notes or a word document) and open it. Configuration of the folder is less important since it is something you will need to do once or maybe twice. I understand that this makes the syncthing app appear a glorified link manager for a file explorer but at the end of the day, I need my files synced to the mobile device so I can open them.

**Comment by Nutomic** [comment]
I can see that, and for me, either option seems okay. Would be good to hear more opinions on this.

**Comment by acolomb** [comment]
I second the suggestion to have an "open in file manager" action available. How about a small folder icon next to the folder name? That would keep the current focus on configuration intact.

Even less interaction is needed if the user just puts a shortcut to the folder on the home screen (e.g. using ES File Explorer). It's a rather optimal workaround, but not as easy to discover as something inside the Syncthing-android GUI.

**Comment by thanosa75** [comment]
Hi again. Have been using the "syncthing-bar" for OS X for a couple days now. Surprisingly, it stands in the top bar and gives the following options ([screenshot here](https://cdn.pbrd.co/images/jJxKeBO76.png)):

- Open UI
- Stop syncthing
- _Open 'Home' in Finder_ <--- most used option
- ... logs, settings, exit

IMHO _95% of users_ clicking on the bar icon (hence opening the app) _are going for the shortcut to the synced folder_.

**Comment by davidbaumann** [comment]
So Actually when I long press on any folder, it asks me to open the folder...
