### ISSUE TITLE
Crash on selecting folder

### ISSUE THREAD

**Issue by redmanmale** [syncthing/syncthing-android#772]
When I'm trying to add new folder (after filled up _Folder label_ and _Folder ID_) and tap to select Directory syncthing just crushing. Every time. I could not add even first folder on the new device.

Adding new folder only via Web GUI works just fine.

I could provide logs if you let me know where I could find them.

Syncthing v.0.14.9, android 4.1.2.

**Comment by licaon-kter** [comment]
Syncthing->settings->open log and Android log

Copy/paste their contents on https://gist.github.com and post those 2 links here

**Comment by redmanmale** [comment]
I cleaned up network requests with device IDs and all that personal stuff.

I've tried to select folder several times, and got a little different logs every time.
https://gist.github.com/redmanmale/84ecc06241f5d40f6fb38819f9b40434

**Comment by Nutomic** [comment]
Damn, apparently the documents folder isn't available on older Android versions. Will push an update later today.

**Comment by redmanmale** [comment]
Thanks for fixing!
