### ISSUE TITLE
Pause sync when battery is low (IDEA)

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#773]
Why not have an option in the app that lets the app turn off all background processes if the users battery is low?

**Comment by Nutomic** [comment]
The app is already disabled when the device enters battery saving mode.

**Comment by DasBiest** [comment]
Then this should be closed

**Comment by jebeld17** [comment]
That is when the device enters a Battery Savings Mode. But what if the user wants it to turn off before that Battery Savings Mode is needed?

**Comment by AudriusButkevicius** [comment]
You can control the app using tasker, use tasker to come up with whatever schedule you want.
