### ISSUE TITLE
(idea) Self-Repair 

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#774]
Recently, I've been getting issues with synchronization of my camera folder to my PC, with the ST longs stating the reason for the error is that the "folder marker is missing".

Maybe a Self-Repair mechanism can be put into play here for issues like mine, and it would work by looking into indexed information about the folder from other computers the user has tied into his or her ST relay somehow in order to re-assemble the lost information.

**Comment by Nutomic** [comment]
Did you delete `.stfolder` in the synced folder, or sync a folder on external storage? This file is needed so Syncthing knows when a folder has been unmounted, and doesn't think all files were deleted.

**Comment by jebeld17** [comment]
Nope, I've looked into File History and the .stfolder files weren't deleted.
I try to steer away from any temporary Syncthing file. I know better than that! ;)
