### ISSUE TITLE
Build with ./make-all.bash failed for clean git clone installation

### ISSUE THREAD

**Issue by begetan** [syncthing/syncthing-android#776]
For clean installation with 
`git clone https://github.com/syncthing/syncthing-android.git`

Git not resolve external dependecies and there are not sources in directories 
`ext/golang/go/src`

So build script failed with error:
`./make-go.bash: line 53: pushd: ext/golang/go/src: No such file or directory`

I expect it should try to initialize submodule dependecy the same way like for go1.4 
It should be mention in readme if it's a feature. 

**Workaround:**
I did initialization of go submodule in the same way like build script do for go1.4.
Just add to make-go.bash command:
`git submodule update --init ext/golang/go
pushd ext/golang/go/src`

The same thing is for the building syncthing:
./make-syncthing.bash: line 38: pushd: ext/syncthing/src/github.com/syncthing/syncthing:

`git submodule update --init  ext/syncthing/src/github.com/syncthing
pushd ext/syncthing/src/github.com/syncthing/syncthing`   

I have build apk file successfully with that changes.

### Version Information

    App Version: 0.8.8 - 0.9.0-beta1
    Syncthing Version: v0.14.9
    Build platform: Ubuntu 16.04 LTS
    Android Version:  no matter

**Comment by Nutomic** [comment]
You have to clone with `git clone https://github.com/syncthing/syncthing-android.git --recursive`. Feel free to make a PR and add it to the readme.
