### ISSUE TITLE
Continuing crashes since v0.8.6

### ISSUE THREAD

**Issue by phil99** [syncthing/syncthing-android#778]
See also issue #767
ST has been crashing and hanging regularly on my Android devices since 0.8.6. Before update to 0.8.6, ST had never crashed in a year's use. No system updates have been recently installed. The crashes are difficult to obtain logs from, as the device often reboots after the crash, and I do not have adb installed.

I have now obtained logs from an Xperia M4, Android 5.0, using ST 0.8.8
LOGS:
[S2 Syncthing Log 04_11_16.txt](https://github.com/syncthing/syncthing-android/files/571515/S2.Syncthing.Log.04_11_16.txt)
[S2 Android Log 04_11_16.txt](https://github.com/syncthing/syncthing-android/files/571519/S2.Android.Log.04_11_16.txt)

Whether the crashes are all caused by the same problem I am not sure, as the behaviour varies from event to event, and device to device.

### Version Information

    App Version: 0.8.8
    Syncthing Version: v0.x.y
    Android Version: 5.0

**Comment by Nutomic** [comment]
It crashes in the app settings for some reason. What exactly are you doing when it crashes?

**Comment by phil99** [comment]
I changed several parameters in Settings/ and Settings/Syncthing Options, but as far as I was aware ST did not crash at that point (though several Restarts were required). 
After finishing changes in Settings, the device appeared to hang up whilst syncing with another device, and never completed syncing. It was after this that I looked at and saved the logs, and assumed they were connected with the the later issue.

**Comment by phil99** [comment]
ST is still crashing on average around every 1 minute.

It crashes often when doing something (create folder, edit folder, or whilst syncing), but also when, as far as I am aware, doing nothing.

Sometimes it stops with the message "Unfortunately Syncthing has stopped", sometimes it hangs completely, often resulting in the device rebooting.

When I can get a log from Syncthing, it almost invariably includes something similar/the same as, the following log excerpt:

H1 Android log excerpt 101116 0919

I/SyncthingNativeCode( 2768): [RIA6F] 09:19:36 INFO: Single thread hash performance is 8.6 MB/s using minio/sha256-simd (8.6 MB/s using crypto/sha256).
D/dalvikvm( 2768): GC_CONCURRENT freed 513K, 14% free 4378K/5068K, paused 3ms+3ms, total 67ms
I/SyncthingNativeCode( 2768): [RIA6F] 09:19:36 FATAL: Cannot open database: resource temporarily unavailable - Is another copy of Syncthing already running?
E/SyncthingRunnable( 2768): Syncthing binary crashed with error code 1, output:
E/SyncthingRunnable( 2768): [RIA6F] 09:19:35 INFO: syncthing v0.14.9 "Dysprosium Dragonfly" (go1.6.2 linux-arm) unknown-user@P50 2016-10-17 07:21:58 UTC

As I am not trying to start a new instance of ST, this must be something ST is doing.

This behaviour started with 0.8.6, and disappeared when I reinstalled v0.8.4.

Currently ST 0.8.8 is unusable on my devices due to the regularity of crashes.

**Comment by capi** [comment]
```
I/SyncthingNativeCode( 2768): [RIA6F] 09:19:36 FATAL: Cannot open database: resource temporarily unavailable - Is another copy of Syncthing already running?
```

It seems that the database is still locked. Have you tried rebooting the device? Alternatively, try to export the settings and clean the data of the application after force-stopping it (or un-install / re-install), followed by re-importing the settings. Maybe this gets rid of the locked database.

You never executed it as `root`, did you?

**Comment by phil99** [comment]
@capi 

It was never executed as root.

Before 0.8.6 ST never crashed in almost a year's use.
I've tried most things I can think of:

-I've uninstalled ST completely, and reinstalled 0.8.4, which worked with zero crashes.
I updated again to 0.8.6, when the crashing restarted. I updated to 0.8.8, the crashing continued.
-I have tried Force Stops, but it doesn't change anything.
-This occurs on several different devices running different versions of Android, mainly 4.2.2 and 4.3, though I've also had a crash with an Xperia running 5.0 since installing 0.8.8 (see first post).
-I have tried all sorts of tests, but can find no pattern to the crashes except for the similar logs in most cases (if the device reboots I cannot retrieve logs). Crashes have occurred when adding, editing and deleting folders, adding a device, syncing, and (as far as I know) doing nothing.
-Sometimes the first I know is that the device is rebooting itself without any warning. This has never happened before on any device of mine, except when running ST, and only since 0.8.6.

I'm fairly ignorant about Android, but could these crashes and reboots be anything to do with running out of memory? If so, what is ST doing to cause this, and why is it trying to load new instances of itself?

**Comment by capi** [comment]
Hmm, 0.8.4 to 0.8.6 updated the Syncthing binary from 0.14.6 to 0.14.8. In [0.14.7](https://github.com/syncthing/syncthing/releases/tag/v0.14.7), Syncthing introduced new (fast) hashing algorithms for Intel and ARM64. _Maybe_ it has something to do with that.

@calmh Were there increased reports of issues on other ARM64 platforms than Android since then? But most likely, Android is the largest install-base for ARM64 at the moment.

**Comment by calmh** [comment]
Yeah there are a coupe of ARM64 cpus misdetected. The wrapper process handles them on non-Android, but I guess Android runs without the wrapper. Might want to detect the crash and set `STHASHING=standard` for those cases. Disabling it outright seems a shame as the wins are huge on ARM64 specifically.

**Comment by Nutomic** [comment]
We're only compiling for normal ARM, not ARM64, in case that matters.

**Comment by calmh** [comment]
I don't know, but if it's Syncthing that crashes we need the crash output to determine.

**Comment by phil99** [comment]
@capi 

> Hmm, 0.8.4 to 0.8.6 updated the Syncthing binary from 0.14.6 to 0.14.8. In 0.14.7, Syncthing introduced new (fast) hashing algorithms for Intel and ARM64.

I'm out of my depth here, so not sure if this is relevant, but the devices causing the most problems all have ARMv7 processors. Only the Xperia M4 has ARM64.

**Comment by edrex** [comment]
i'm also seeing frequent crashes in the past few releases with two different ARMv7 devices (Moto G 3 and Shield K1 Tablet)

**Comment by acolomb** [comment]
I'm under the impression that this issue might be hitting me as well. Sent a crash report through Play Store yesterday. Syncthing crashes repeatedly while initially scanning a folder. How can I set the STHASHING environment variable? 

I'm on an LG G4 (h815). Android 6.0.1, CyanogenMod 13.0

**Comment by Nutomic** [comment]
There are many reports in Google Play, so I dont know which one is yours. Please record a logcat yourself and post it here. Setting STHASHING isnt possible right now, unless you compile the app yourself (see #788).

**Comment by Nutomic** [comment]
Is this still a problem?
