### ISSUE TITLE
Using "restart now" after changing a setting unshares all folders

### ISSUE THREAD

**Issue by wweich** [syncthing/syncthing-android#782]
When trying to help in #781 I noticed share notifications for folders which were already fully shared. Turns out, that for some reason all folders were unshared, after I enabled the experimental foreground option.

Further testing showed, that this is reproducible by changing the experimental foreground option (didn't try others) and choosing "restart now" when asked. If I choose restart later, go back to the main App screen, exit with back button and then use the notification to restart, the folders keep being shared.

I don't have logs, as this is only after restart and the logs after restart don't show anything and I can't get `adb` to work with my new Pixel for now.

### Version Information

    App Version: 0.9.0-beta1
    Syncthing Version: v0.14.9
    Android Version: Android 7.1 (Google Pixel)

**Comment by capi** [comment]
It should then be in any "restart" case then, since there is nothing special about the "foreground" option (it's just a boolean flag for the service, and nothing which interacts with the native sync binary.

**Comment by Nutomic** [comment]
Yeah I also don't see how this could happen. Can you check if there's actually any difference in the config?

**Comment by wweich** [comment]
I just exported the settings, enabled NAT traversal, confirmed "restart now" and exported again.

The second export has no `<device>` entry inside the `<folder>`s, other than the Pixel itself.

I re-imported the first export and the folders were (of cause) shared again. I then enabled NAT, chose "later" and restarted with the notification. This time, the folders were still shared.

**Comment by Nutomic** [comment]
I suppose it might be a race condition or something like that. Will look into it later.

**Comment by acolomb** [comment]
I experience the same problem since today. All folders are unshared. If I enable the share slider again for some devices, next time I open Syncthing all sliders are unchecked again. What can I do to help with debugging?

Syncthing-android v0.9.0-beta1
Syncthing 0.14.9
Android 6.0.1 (Cyanogenmod 13)

**Comment by Nutomic** [comment]
No need for any help. I noticed this problem myself, should be easy to fix when I have the time.
