### ISSUE TITLE
Synced over Cellular even though WiFi-Only setting was enabled (no more cell data this month, ha)

### ISSUE THREAD

**Issue by bobbycircle** [syncthing/syncthing-android#784]
**What happened:** My phone synced over its Cellular connection even though I checked "Only sync over WiFi." Ended up overusing my data plan for the month (and now I owe some extra $$$ too.)

**What you expected to happen instead:** When the "Only sync over WiFi" setting is checked, I expect syncthing to not use my cellular data. I basically NEVER want it to use my cell connection.

**Any steps to reproduce the problem:** I had "Only sync over WiFi" turned on, and I also had "Only sync over certain WiFi networks" turned on as well. _My phone was in fact connected to my WiFi router, but the connection to the router was in some funky state such that from the phone's point of view, there was a WiFi connection but no internet._ (I believe I fixed it by disconnecting from WiFi and re-connecting.) So maybe syncthing got a false-positive that the WiFi was working, even though it kind of wasn't. (Interestingly, all my syncthing devices are within my internal network, so internet access isn't even required to sync, right?) Perhaps there is a way for syncthing to detect that even though WiFi is on, data is not flowing through it. Or just have a setting which says Never Over Cellular, No. Matter. What. ;)

### Version Information

    App Version: 0.8.8
    Syncthing Version: v0.14.9
    Android Version: Android 7.0

**Comment by bobbycircle** [comment]
FWIW, I just found the Android OS setting for disabling the use of cellular data **in the background** for particular apps. So now at least I can control how syncthing behaves in the background with respect to cell data (and it's usually in the background).

**Comment by wweich** [comment]
Google "improved" Android, by removing one of the possibilities to get notified of network changes. That's why on Android 7, Syncthing Android doesn't get notified of Wifi disconnect.

Disabling the mobile background data is the workaround I use.

dup of #783

**Comment by bobbycircle** [comment]
Gotcha. Thanks for the help.

**Comment by koo5** [comment]
syncthing just ate up all my mobile data as well. I think wifi was disabled, and im sure no known AP was nearby. Syncthing 0.10.6, Android 7.1.1
