### ISSUE TITLE
Forcing 60 sec rescan interval on Marshmallow and newer hogs cpu/battery with large directories

### ISSUE THREAD

**Issue by lszekeres** [syncthing/syncthing-android#786]
Please, allow setting it manually to any value:
https://github.com/syncthing/syncthing-android/commit/b38a152f6a43e4e1b17a64def28fd1169d96ae51#diff-d2bd4b4b066e6e893ebf3f06eba79b20R143

**Comment by Nutomic** [comment]
Right, I guess we should just set 60 seconds as default when creating a new folder.
