### ISSUE TITLE
Support setting of all relevant Syncthing environment variables

### ISSUE THREAD

**Issue by ProactiveServices** [syncthing/syncthing-android#788]
It would be useful if a user was able to set all of the relevant Syncthing environment variables. At the moment the "Debug options" feature exposes the STTRACE functionality, but being able to set the proxy (issue #766), hashing algo etc. envvars would also be helpful.

**Comment by Nutomic** [comment]
This is not possible right now. As a workaround, you can compile the app from source, and set the env var [here](https://github.com/syncthing/syncthing-android/blob/master/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java#L125).
