### ISSUE TITLE
Show device QR codes

### ISSUE THREAD

**Issue by JohnVeness** [syncthing/syncthing-android#790]
Although we can show device QR codes in the web GUI, it would be nice (more discoverable, fewer taps) in we could also do so in the native GUI.

**Comment by wweich** [comment]
You already need Barcode Scanner to add a device by scanning that QR code. You can share the device ID (button in the side menu) with Barcode Scanner to show your device ID as QR code.

**Comment by JohnVeness** [comment]
Ah yes, so you can. Maybe not quite as intuitive as a button labelled "Show QR", but good enough.

**Comment by licaon-kter** [comment]
Why is this closed? Can't a view be opened directly to the WebUI QR code? Say add a button near copy ID that opens that from the main interface.

**Comment by Nutomic** [comment]
Its possible, but I'm not sure if its worth the time and screen space, when you can already access the qr code via Barcode Scanner. That said, we can definitely keep the issue open.

**Comment by licaon-kter** [comment]
Screen space? What's the more probable action, share the ID by string or by QR?

Also, i'd vote for leaving only the Share ID entry (remove the current id and copy icon from top on slide menu), that opens up a view like the WebUI does, with string on top (add copy/share icons here) and a QR below.

**Comment by Nutomic** [comment]
Right, it makes sense to have a dialog with QR code + device iD (basically what Syncthing does in "show ID").

**Comment by JohnVeness** [comment]
Thanks for considering this. To be clear, for me this would be useful for showing the QR for both This Device and any Remote Devices. I was wishing to add a remote device that was already known by Android device 1, to Android device 2.

**Comment by jmintb** [comment]
It should be possible to get the QRCode image from the web UI with a Get request, that is how Syncthing-gtk does it. I will start working on it. :)

**Comment by Nutomic** [comment]
Its probably easier if you use ZXing to generate the barcode directly:

https://stackoverflow.com/questions/41606384/how-to-generate-qr-code-using-zxing-library

**Comment by jmintb** [comment]
I have got it working with the Get request, but I can switch to ZXing if you want? :)

**Comment by Nutomic** [comment]
If you already implemented it, and loading times aren't too long, that's fine. Can you make a PR?

**Comment by jmintb** [comment]
I will soon, I am just reviewing the code. The image is loaded instantly.
