### ISSUE TITLE
Folder pop-up remains after deleting folder.

### ISSUE THREAD

**Issue by kluppy** [syncthing/syncthing-android#796]
App Version: 0.9.0
Syncthing Version: v0.14.12
Android Version: Android 6.0.1

After new install I deleted the default camera folder from within the android GUI.
The folder dialogue remained open with the folders details.
Hitting the back button returned me to the now empty folder list. I would not expect to have to hit the back button after deleting a folder to leave it's configuration dialog.

**Comment by Nutomic** [comment]
Thanks for reporting this :)
