### ISSUE TITLE
Issues on 0.9.0

### ISSUE THREAD

**Issue by licaon-kter** [syncthing/syncthing-android#799]
Xperia 5.1.1

logcat: https://gist.github.com/licaon-kter/2e61134f6ab4ddfd6d185dc245e964fe

Not sure what issue is seen there (see #797), but I've seen an issue, I went on to setup it for the first time, import settings, restarted, setup, but on every restart in kept saying "Generating secure keys...", it stopped doing it after an Exit though.

**Comment by Nutomic** [comment]
What were you doing when that crash happened? Eg opened the app, or closed it, or something else?

**Comment by licaon-kter** [comment]
Using it, can't say more as I don't know.

**Comment by Catfriend1** [comment]
Frozen due to age.
