### ISSUE TITLE
0.9.1 - Device Status (Ready vs Disconnected) error

### ISSUE THREAD

**Issue by NickPyz** [syncthing/syncthing-android#800]
Immediately after version upgrade all devices show as "Up to Date", including known disconnected devices. Switching over to web-GUI displays the correct status - looks like a wrapper issue.

### Version Information

    App Version: 0.9.1
    Syncthing Version: v0.14.13
    Android Version: Android 4.4.4

**Comment by Tblue** [comment]
Same issue here.

- App v0.9.1
- Syncthing v0.14.13
- Android v6.0.1

**Comment by Simpleton350** [comment]
Same here, on two devices (Android 4.2.2 and 5.0.2).
