### ISSUE TITLE
ST hangs on not having the right web interface IP available

### ISSUE THREAD

**Issue by hboetes** [syncthing/syncthing-android#801]
Running ST on android cyanogenmod 13, I set the listening interface to the DHCP assigned address, which works great I have access to the web interface from my laptop browser.

But, if I’m not connected to that WLAN the IP does not exist of course. When I start ST I expected it to stop, or simply disable the web interface or something useful. Instead it hangs running the spinner.

If I then connect to the right WLAN the spinner keeps spinning, instead of it finding the right IP and continuing. I have to kill ST and then restart it.

**Comment by Catfriend1** [comment]
@hboetes: Does this issue still persist in the most recent version 0.10.8 from gplay?

**Comment by AudriusButkevicius** [comment]
It will, but it's most likely user error misconfiguring. If he wants the web ui to be available publically, he should bind to 0.0.0.0 and not a specific IP in a specific network, as that will never work on any other network. Closing this as this is more or less invalid.
