### ISSUE TITLE
Device Status as Disconnected Error

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#802]
Please note I could not find this exact same issue in the bug tracker.

The Syncthing GUI under the "Devices" list shows all devices as "DISCONNECTED" after a device screen auto rotation from portrait to landscape and vice versa.

The app will only say "DISCONNECTED" for up to fifteen seconds (rough estimate) maximum before placing the right status on my devices again, so I believe this is more of a cosmetic bug over functionality.

Device: HTC 10
Android Edition: 7.0
Security Patch: November 2016
STOCK HTC UNROOTED

**Comment by jebeld17** [comment]
Castro Information Report
 
Report generated: 06 December 2016 20:25:07
 
System
OS
Version: 7.0
Security patch: 01 November 2016
Build number: NRD90M
Tags: release-keys
Bootloader: 1.0.0.0000
SDK: 24
Font scale: Normal
Time zone: Eastern Standard Time
Uptime: 09:01:59
Uptime (w/o Deep Sleep): 09:01:58
Radio: 1.0.U010241a@61107_76.02_F

Miscellaneous
Disk encryption: Decrypted
Virtual machine: ART 2.1.0
Heap size: 512 MB
Root: Unavailable
BusyBox: Unavailable
Version ICU: 8.0
Library ICU: 56.1
ICU CLDR: 28.0
Version ZLib: null
Version OpenSSL: BoringSSL
Kernel: 3.18.31-perf-g3678dc9 and@AABM) ) #1 SMP PREEMPT Mon Nov 21 17:50:05 CST 2016
Fingerprint: htc/pmewl_00617/htc_pmewl:7.0/NRD90M/831921.8:user/release-keys
 
Device
Model: HTC 10
Codename: htc_pmewl
Manufacturer: HTC

Display
Resolution: 2560 x 1440 pixels
Frame rate: 60 Hz
Density: 640 dpi
Format: xxxhdpi

Identifiers
IMEI: 354259072192002
IMSI: 310410691580942
Serial number: HT64XBN00739
Device ID: 3c567ec0276bbcff
SIM serial: 89014103286915809426
 
Processor

CPU
Model: Error
Name: AArch64 Processor rev 2 (aarch64)
Architecture: Error (0x211)
DSP: Error
Process: Error
Cores: 4
Supported ABI: armeabi 
Governor: interactive
Frequency range: 307 MHz - 1593 MHz
Usage: 83 %

Technologies
NEON: Not supported
SWP: Not supported
Thumb: Not supported

GPU
Name: Error
Frequency: Error
Open GL: OpenGl ES 3.2
 
Battery
Capacity: 3000 mAh
 
Memory
RAM Total: 3766 MB
Internal memory Total: 23.91 GB
External memory Total: 59.60 GB
 
Cellular
Phone
Operator: AT&T
Operator code: 310410
Standard: GSM
Country code: us
Voice mail: Supported
World phone: Yes

Network
Type: 4G
Status: Disconnected
Roaming: Disconnected
ICC card: Present
Local (IPv4): 192.168.86.106
Local (IPv6): FE80::FC37:1FF:FEFA:6CFD
 
Wi-Fi
Properties
Name: "Google OnHub"
Hidden SSID: Disabled
Frequency: 2437 MHz
Speed: 21 Mbps
BSSID: 60:e3:27:9b:13:67
Signal: -73 dBm
Local IP: 192.168.86.106
5GHz band: Supported

DHCP 
DNS 1: 192.168.86.1
DNS 2: 0.0.0.0
Gateway: 192.168.86.1
Lease time: 24 hours
Subnet mask: 0.0.0.0
Server IP: 192.168.86.1
 
Back camera
Resolution: 12.0 MP (4000x3000)
JPEG quality: 90 %
Thumbnail size: 512x384
Thumbnail quality: 90 %
Focal: 4.58 mm
Auto exposure: Unlocked
Auto white balance: Unlocked
Vertical angle: 53.8285 %
Horizontal angle: 10
Horizontal angle: 10
Video stabilization: Error
Flash: Available
Zoom: Available

Color effect 
Current: Not selected
Supported: Not selected, Monochrome, Negative, Solarize, Sepia, Posterize, Whiteboard, Blackboard, Aqua

Focus mode 
Current: Automatic
Supported: Infinity, Automatic, Close-up, Continuous video, Continuous picture

Scene mode 
Current: Automatic
Supported: Automatic, Landscape, Snow, Beach, Sunset, Night, Portrait, Sport, Steady photo, Candlelight, Fireworks, Party, Night portrait, Theatre, Action

Antibanding mode 
Current: Automatic
Supported: Disabled, 60 Hz, 50 Hz, Automatic
 
Front camera
Resolution: 5.0 MP (2592x1944)
JPEG quality: 90 %
Thumbnail size: 512x384
Thumbnail quality: 90 %
Focal: 2.35 mm
Auto exposure: Unlocked
Auto white balance: Unlocked
Vertical angle: 57.9945 %
Horizontal angle: 10
Horizontal angle: 10
Video stabilization: Error
Flash: Unavailable
Zoom: Available

Color effect 
Current: Not selected
Supported: Not selected, Monochrome, Negative, Solarize, Sepia, Posterize, Whiteboard, Blackboard, Aqua

Focus mode 
Current: Automatic
Supported: Infinity, Automatic, Close-up, Continuous video, Continuous picture

Scene mode 
Current: Automatic
Supported: Automatic, Landscape, Snow, Beach, Sunset, Night, Portrait, Sport, Steady photo, Candlelight, Fireworks, Party, Night portrait, Theatre, Action

Antibanding mode 
Current: Automatic
Supported: Disabled, 60 Hz, 50 Hz, Automatic

**Comment by jebeld17** [comment]
Anyone else get the same issue?

**Comment by Nutomic** [comment]
Which app version are you using? And is the status shown correctly before you rotate the screen? I've removed your post with device status because it's not relevant.

**Comment by jebeld17** [comment]
Sorry, I didn't see any response until after the fix was pushed to users.

**Comment by jebeld17** [comment]
Thank you for fixing the issue, by the way! :-)
Android 0.9.2
ST 0.14.14
