### ISSUE TITLE
Dialog appear on device rotation

### ISSUE THREAD

**Issue by reverse-unina** [syncthing/syncthing-android#804]
When I perform this sequence of events, an unwanted dialog appear on the screen

1.  Click Later in Battery Optimization dialog
2. Orientation Change

**Comment by shobhitagarwal1612** [comment]
I'd like to tackle this issue

**Comment by Nutomic** [comment]
Cool! You should basically follow [this approach](https://stackoverflow.com/questions/151777/saving-android-activity-state/151940#151940). Let me know if you need more help ;)

**Comment by shobhitagarwal1612** [comment]
@Nutomic  I have built the project but it crashes just after pressing continue button at the starting screen. I have checked on Android 5.0 and Android 6.0 . Please help!


> 02-03 11:31:33.533 8472-8937/com.nutomic.syncthingandroid.debug W/SyncthingRunnable: Failed to trim log file
>                                                                                      java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.nutomic.syncthingandroid.debug/files/syncthing.log: open failed: ENOENT (No such file or directory)
>                                                                                          at libcore.io.IoBridge.open(IoBridge.java:452)
>                                                                                          at java.io.FileInputStream.<init>(FileInputStream.java:76)
>                                                                                          at com.google.common.io.Files$FileByteSource.openStream(Files.java:120)
>                                                                                          at com.google.common.io.Files$FileByteSource.openStream(Files.java:110)
>                                                                                          at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456)
>                                                                                          at com.google.common.io.CharSource.readLines(CharSource.java:311)
>                                                                                          at com.google.common.io.Files.readLines(Files.java:553)
>                                                                                          at com.google.common.io.Files.readLines(Files.java:520)
>                                                                                          at com.nutomic.syncthingandroid.service.SyncthingRunnable.trimLogFile(SyncthingRunnable.java:344)
>                                                                                          at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:94)
>                                                                                          at com.nutomic.syncthingandroid.util.ConfigXml.generateKeysConfig(ConfigXml.java:83)
>                                                                                          at com.nutomic.syncthingandroid.util.ConfigXml.<init>(ConfigXml.java:64)
>                                                                                          at com.nutomic.syncthingandroid.service.SyncthingService$StartupTask.doInBackground(SyncthingService.java:335)
>                                                                                          at com.nutomic.syncthingandroid.service.SyncthingService$StartupTask.doInBackground(SyncthingService.java:330)
>                                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:295)
>                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>                                                                                          at java.lang.Thread.run(Thread.java:818)
>                                                                                       Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
>                                                                                          at libcore.io.Posix.open(Native Method)
>                                                                                          at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
>                                                                                          at libcore.io.IoBridge.open(IoBridge.java:438)
>                                                                                          at java.io.FileInputStream.<init>(FileInputStream.java:76) 
>                                                                                          at com.google.common.io.Files$FileByteSource.openStream(Files.java:120) 
>                                                                                          at com.google.common.io.Files$FileByteSource.openStream(Files.java:110) 
>                                                                                          at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:456) 
>                                                                                          at com.google.common.io.CharSource.readLines(CharSource.java:311) 
>                                                                                          at com.google.common.io.Files.readLines(Files.java:553) 
>                                                                                          at com.google.common.io.Files.readLines(Files.java:520) 
>                                                                                          at com.nutomic.syncthingandroid.service.SyncthingRunnable.trimLogFile(SyncthingRunnable.java:344) 
>                                                                                          at com.nutomic.syncthingandroid.service.SyncthingRunnable.run(SyncthingRunnable.java:94) 
>                                                                                          at com.nutomic.syncthingandroid.util.ConfigXml.generateKeysConfig(ConfigXml.java:83) 
>                                                                                          at com.nutomic.syncthingandroid.util.ConfigXml.<init>(ConfigXml.java:64) 
>                                                                                          at com.nutomic.syncthingandroid.service.SyncthingService$StartupTask.doInBackground(SyncthingService.java:335) 
>                                                                                          at com.nutomic.syncthingandroid.service.SyncthingService$StartupTask.doInBackground(SyncthingService.java:330) 
>                                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:295) 
>                                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
>                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
>                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
>                                                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by Nutomic** [comment]
You probably didn't build the native Syncthing binary. Run `./gradlew buildNative` in command line and try again.

**Comment by shobhitagarwal1612** [comment]
Thanks :+1:

**Comment by shobhitagarwal1612** [comment]
@Nutomic I tried running `./gradlew buildNative` on command line. It gives the following error
`gometalinter is not installed`

**Comment by AudriusButkevicius** [comment]
Its just a warning.

**Comment by shobhitagarwal1612** [comment]
Tried it but no success. Please help

**Comment by Nutomic** [comment]
[Do you have these files](https://i.imgur.com/bcjdXPR.png)? They should be generated by the buildNative command. 

If you need more help, the forum is probably a better place to figure this out.

**Comment by shobhitagarwal1612** [comment]
@Nutomic I checked my device but no config.xml file was created. Do I need to root my mobile to give root access to the app?

**Comment by Nutomic** [comment]
No, root is not required. Maybe try a clean build? You can also disable instant run in Android Studio, and check that the `libsyncthing.so` files are in the apk (by opening it as zip).
