### ISSUE TITLE
Dialog disappear on orientation change

### ISSUE THREAD

**Issue by reverse-unina** [syncthing/syncthing-android#807]
When i perform these sequences of events, the dialog on screen disappears

Sequence 1: 
1. Click on Folder item
2. Click on Remove icon
3. Orientation Change

Sequence 2:
1. Open Side Drawer
2. Click on Restart
3. Orientation Change

Sequence 3:
1. Click on Add Folder icon
2. Click on Back
3. Orientation Change

Sequence 4:
1. Click on Devices
2. Click on Add Device icon
3. Click on back
4. Orientation Change

Sequence 5:
1. Click on Devices
2. Click on Add Device icon
3. Click on Compression
4. Orientation Change

**Comment by licaon-kter** [comment]
You must love to rotate your device. :)

**Comment by reverse-unina** [comment]
Yes, indeed 😃 
I am rotating everything I can and exploring mobile GUI failures for research purposes.

**Comment by licaon-kter** [comment]
And thank you for that. The whole issue is about Android recreating the view on rotation, iirc.
