### ISSUE TITLE
ST on chromeOS Android fails to launch

### ISSUE THREAD

**Issue by vbatts** [syncthing/syncthing-android#808]
When launching syncthing-android on upcoming Android for ChromeOS, 
* syncthing shows the first-run "welcome to Syncthing for Andriod" Screen
* click "continue"
* then android asks to allow access to storage and media
* After allowing it access, it fails with the toast at the bottom of the screen stating: "Failed to create Syncthing config. Please check logs"

Everytime attempting to launch the application, the same message is displayed.
The ./Android/data/com.nutomic.syncthingandroid/ only has a "files" directory, and nothing else.

### Version Information

ChromeOS Version 56.0.2920.0 dev
Platform 8992.1.0 (Official Build) dev-channel veyron_minnie
ARC Version 3477227
Android Version: 6.0.1
syncthing-android: 0.9.1

**Comment by Nutomic** [comment]
Please provide logs.

**Comment by vbatts** [comment]
Where do I find them?

**Comment by licaon-kter** [comment]
Settings->Debug->Log->this log & Android log
Do paste on https://gist.github.com and provide the link.

**Comment by vbatts** [comment]
it looks like i'll have to put this chromebook into developer mode to access these logs. Or install an apk that I've compiled myself (non-playstore).

**Comment by licaon-kter** [comment]
Those are in the Syncthing app!

**Comment by vbatts** [comment]
the syncthing app does not _launch_ ;-)

**Comment by vbatts** [comment]
i'm not seeing that the `-generate`'ed config.xml and key.pem even exist anywhere.

I just went down the route of seeing if `Context.getFilesDir()` may be the culprit, so I just tried switching that to `getExternalFilesDir(null)` instead --> http://pastebin.com/azPQmshY
But it has the same issue.

**Comment by vbatts** [comment]
FYI even `getDir("config", 0)` fails in the same way.

**Comment by vbatts** [comment]
https://github.com/vbatts/syncthing-android/tree/please_config_file has commits for the 3 approaches. None of them solve the issue.

**Comment by Nutomic** [comment]
Here are some instructions for debugging on Chromebook:
https://developer.android.com/topic/arc/index.html
http://opensourceforgeeks.blogspot.kr/2016/12/debug-android-apps-on-chromebook-using.html

**Comment by vbatts** [comment]
cool. https://paste.fedoraproject.org/505717/36898148/ is the tail of the log.

I built from master (92bf84915cf7da1a8dc54112c2fe71533ea298b0) using `./gradlew build`, and installed the syncthing-android-armeabi-debug.apk

**Comment by AudriusButkevicius** [comment]
It seems that you cannot use Go on the device you are using, The Go runtime is panic'ing quite early on.

**Comment by vbatts** [comment]
@AudriusButkevicius I see that panic, but calling that binary from the chrome host works fine: https://paste.fedoraproject.org/506002/16772841/

I'll have to try the similar from inside android tomorrow

**Comment by vbatts** [comment]
Welp, just determined where the binary is, and then ran it as the adb shell user
```bash
chronos@localhost / $ sudo adb shell
data/app/com.nutomic.syncthingandroid.debug-1/lib/arm/libsyncthing.so --help  <
panic: nil
fatal error: panic on system stack
runtime: panic before malloc heap initialized

runtime stack:
fatal error: gentraceback before goexitPC initialization
runtime: panic before malloc heap initialized
panic during panic

runtime stack:
fatal error: gentraceback before goexitPC initialization
runtime: panic before malloc heap initialized
stack trace unavailable
4|shell@minnie_cheets:/ $ whoami                                               
shell
shell@minnie_cheets:/ $ id
uid=2000(shell) gid=2000(shell) groups=2000(shell),605(arc-tracing),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats) context=u:r:shell:s0
```

**Comment by Nutomic** [comment]
Are you running the correct architecture? (arm vs x86). I also found a little info here: http://stackoverflow.com/a/29474411

**Comment by vbatts** [comment]
The chromebook is the asus c100pa. A quadcore rockchip arm.
`uname -a` in chromeOS: `Linux localhost 3.14.0 #1 SMP PREEMPT Fri Nov 18 00:51:13 PST 2016 armv7l ARMv7 Processor rev 1 (v7l) Rockchip (Device Tree) GNU/Linux`
`uname -a` in adb shell: `Linux localhost 3.14.0 #1 SMP PREEMPT Fri Nov 18 00:51:13 PST 2016 armv7l`

**Comment by vbatts** [comment]
@Nutomic i've submitted an issue https://bugs.chromium.org/p/chromium/issues/detail?id=673998 as it didn't look like there was an existing one that matched

**Comment by vbatts** [comment]
further info, https://play.google.com/store/apps/details?id=org.golang.ivy fails as well, so there is a golang issue in this contrived android environment for ChromeOS

**Comment by precurse** [comment]
I'm experiencing the same error "Unable to create config" on a Dell Chromebook 13.  It's an i3 skylake CPU (x86).

**Comment by Jack-sparrow-wannabe** [comment]
Same problem on my machine as well 
2017 x86_64 Intel(R) Celeron(R) CPU N3060 @ 1.60GHz GenuineIntel GNU/Linux

**Comment by precurse** [comment]
It seems the latest Chrome OS dev update fixed the issue. It's working great now.

**Comment by vbatts** [comment]
@precurse paste your version information with a statement like that. ;-)

**Comment by precurse** [comment]
Haha good call..

57.0.2987.6 official build dev 64bit

**Comment by vbatts** [comment]
thanks. They haven't pushed updates to all channels/builds yet.
This veryon build hasn't had an update since Dec 14, 2016
```
Version 57.0.2951.0 dev
Platform 9086.0.0 (Official Build) dev-channel veyron_minnie
ARC Version 3569695
Firmware Google_Veyron_Minnie.6588.237.0
```

**Comment by vbatts** [comment]
so great! The dev channel for the Veryron_Minnie build just updated.
```
Version 57.0.2987.11 dev
Platform 9202.7.0 (Official Build) dev-channel veyron_minnie
ARC Version 3678932
Firmware Google_Veyron_Minnie.6588.237.0
```
And now Android apps that have golang runtimes no longer panic. 
They must have updated the container's resource quotas and threading.

I'll close this out as others have reported it fixed for other architectures as well.
