### ISSUE TITLE
Run condition to restrict based on hours

### ISSUE THREAD

**Issue by timjefferies** [syncthing/syncthing-android#809]
I have set up syncthing on my laptops/servers and phone. Everything runs great, but the usage on the phone is a little cumbersome. My internet connection only has 40/kb upload, and yet I have a 64GB sd card in my phone - And my phone gets the most usage out of the day in terms of files changing.

When I look at other apps they tend to only run at night, but syncthing does not have this as an option.

Having syncthing run all the time with the existing conditions doesn't really work for my usage case. I often plug in my phone and use wifi at the same time, just in casual use... But syncthing kills my bandwidth and makes internet usage impossible. But then also, i'm not using the internet when I am sleeping... so setting global bandwidth restrictions does not make sense.

Can we then, have an option to add run time hours to the run conditions? 

I'd like my syncthing app to only perform syncing between the hours of 11pm and 6am ideally, without me having to micromanage the app settings.

**Comment by AudriusButkevicius** [comment]
Syncthing supports tasker integration. Use that.

**Comment by wweich** [comment]
https://github.com/syncthing/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents
