### ISSUE TITLE
Device state same for all devices

### ISSUE THREAD

**Issue by davidbaumann** [syncthing/syncthing-android#810]
I have 3 devices connected to my S7.
After connecting my laptop to the hotspot of my phone, all of the 3 devices are shown as "Syncing 94%", though only one is actually powered on.

If there is no device connected, it says "up to date".

### Version Information

    App Version: 0.9.1
    Syncthing Version: v0.14.13
    Android Version: Android 6.0.1 / Galaxy S7 stock

**Comment by AudriusButkevicius** [comment]
Dup #802 I suspect.

**Comment by davidbaumann** [comment]
Actually, the problem always occurs.
I quit syncthing, start again and still do have the issue, even if I don't trigger screen rotation.

**Comment by AudriusButkevicius** [comment]
802 is not realted to rotation

**Comment by davidbaumann** [comment]
Sure? I just double checked...

**Comment by AudriusButkevicius** [comment]
I meant #800

**Comment by jebeld17** [comment]
Issue was just patched this morning through a Play Store Update to Android at v0.9.2

**Comment by jebeld17** [comment]
Typo: at = *ST
