### ISSUE TITLE
Easier access to log data

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing-android#811]
It would be neat if the app allowed easy access to Syncthing's log data. Either as a text field somewhere that can be shown and copied from, or in worst case as a log file accessible somehow. The latter could even be done "for free" by just passing `-logfile` to Syncthing.

**Comment by AudriusButkevicius** [comment]
You already have access somewhere in the debug options.

**Comment by AudriusButkevicius** [comment]
Drop down > settings > debug > log

**Comment by Nutomic** [comment]
I dont want to use `-logfile`, as that seems to replace stdout logging. But printing to a file is easy enough. The only question I have is, how should we truncate the output file, so it doesnt get too big?

@AudriusButkevicius That doesnt work if the app wont start :/

**Comment by calmh** [comment]
Keep the last 1000 lines or something. If it's already there that's good, but it seems a repeating scenario that we ask for logs and people fumble with adb or logcat or whatever and never actually end up providing the real syncthing output. So I'm assuming it's somehow tricky to get at, in the app.
