### ISSUE TITLE
Root Start Problematic since 0.8.x - syncthing could not create config.XML popup

### ISSUE THREAD

**Issue by Catfriend1** [syncthing/syncthing-android#812]
Do not report security issues in this bug tracker. Instead, contact security@syncthing.net directly - see https://syncthing.net/security.html for more information.

If your issue is a support request ("How do I get my devices to connect?" or similar), please use the support forum at https://forum.syncthing.net/ where a large number of helpful people hang out. This issue tracker is for reporting bugs or feature requests directly to the developers.

If your issue is a bug report, replace this boilerplate with a description of the problem, being sure to include at least:

    what happened,
    what you expected to happen instead, and
    any steps to reproduce the problem.

Also fill out the version information below and add log output or screenshots as appropriate.

If your issue is a feature request, simply replace this template text in its entirety.

### Version Information

    App Version: 0.x.y
    Syncthing Version: v0.x.y
    Android Version: Android x.y / Cyanogenmod x / ...

**Comment by Catfriend1** [comment]
Version 0.8.x, currently 0.9.2
After upgrade 0.9.0->0.9.1 config.XML was valid only The first run after upgrade. Second run (rrpdroducible) was always unsuccessful with no useful logcat. Only popup config.XML is invalid on home screen. Figured it out because it was The same with 0.9.2.
The following root command helps to permanently solve this annoying Problem:chmod 0666 /data/data/com.nutomic.syncthingandroid/files/config.xml

Im on Lg h815 g4 with cm13 Android 6.0.1 rooted Rom.

**Comment by Catfriend1** [comment]
The App changes permission somehow on first run to rw------- instead of required rw-rw-rw-. Config.XML.v16 was successfully created.

**Comment by licaon-kter** [comment]
Did you enable root mode in app ?

**Comment by Catfriend1** [comment]
Yes Root checkbox was enabled

**Comment by licaon-kter** [comment]
Did you get a chance to read #453 ? Spoiler alert: it's not fixed.

**Comment by Catfriend1** [comment]
Its Quite similar as in The other thread. But why not change permission using Root on App Start before doing anything with The file? My syncthing works fine without Problem after doing this manually with Root Explorer. This should be done by The App itself I think.

**Comment by sirber** [comment]
Same thing with 0.9.6

**Comment by Catfriend1** [comment]
I found a solution:
1. chmod -R 0777 /data/data/com.nutomic.syncthingandroid/files
2. Then start Syncthing Android App with Root option enabled
3. ~ 12 seconds later, some files below the above mentioned folder turn back to rw-r-r. Syncthing does not get a clean database when running like this (I see device is correctly synced with master folder but master tells me on second sync-on-android-run "Out of sync" which is false) To solve this issue, use Tasker App to run (1) chmod .... again after ~ 12 seconds.

Now I can access all folders on SD card without reformatting, link hassle or long paths. Its perfect. But the final solution has to come from the app maintainers. Syncthing should use its already granted root rights to get the files below the "/files/" folder to the correct access right level (0777) before accessing them. This opens the door without the need to make GO compatible with Android Storage Framework.

**Comment by Nutomic** [comment]
I don't really understand this solution. Syncthing is already running as root, so it should be able to access these files no matter the permissions. Besides, 777 means that anyone can read and write these files, which also makes it a security problem.

**Comment by Catfriend1** [comment]
Hi Nutomic,
you can reproduce the issue with unix file system rights as follows:
1. Put Syncthing App into Root Mode (via app's own settings menu)
2. Close Syncthing App - to ensure the service also terminates, "force close" it from android's app manager.
3. Launch "Root Explorer" (or a similar file manager app)
4. Navigate to folder: /data/data/com.nutomic.syncthingandroid/files
5. Note down some unix rights of the files present. Modify this folder's (and sub-folders including all files) unix rights to 0777
- 0777 is just meant for testing purposes only. I thought a lower access level granting read/write access would also be sufficient later, but for now 0777.
6. Launch "Syncthing" app, create an example configuration with a "little sized" test folder and files, let it index
7. Close "Syncthing" app as described in step (2.)
8. Root Explorer: Navigate to folder: /data/data/com.nutomic.syncthingandroid/files
9. You will notice that the files unix rights have changed to a lower privileged level. (compared to step 5.)
10. Relaunch "Syncthing" app.
! On my phone with rooted LineAge Android 7.1.1 (LG-G4, type H815-eu, rom from 2017-07-04), I can now launch the app for ca. one time, but when I try to change e.g. folder configuration by adding a second folder to syncthing, restart the app, then I get "Invalid XML Configuration" popup message and the app will no longer start. - If I manually correct the unix rights as mentioned above my configuration does write down correctly and syncthing always starts fine when I try.

**Comment by Nutomic** [comment]
Feel free to make a PR, but this isn't something I'm going to implement myself.

**Comment by Catfriend1** [comment]
If I have time to go deeper in the Android/GO development I'll try. Until this time, I've temporarily disabled root access in the app and patched my android services.jar to allow sd card write from Go Syncthing :-). I'll bookmark this thread to come back later. Thanks your answer.

**Comment by flipreverse** [comment]
Btw, I came across that issue as well, and I've written a fix for that. I will file a pull request tomorrow. Keep your fingers crossed. ;)

**Comment by Catfriend1** [comment]
Google Play Update?

**Comment by Catfriend1** [comment]
Ok found it thanks
