### ISSUE TITLE
(idea) Bug Reporting on Main Menu

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#813]
Note this isn't anything critical and isn't something that requires a fix, but it is something that would be nice to fix.
---
Currently, the user has to sort through the Main Menu < Settings < About to find the Bug Reports section of the app, but what if that Bug Report section were in an easier location for the common user to see, such as right on the Main Menu, sort of like how Google has their "Help and Feedback" section on Gmail?
This would bring the number of bug reports up by silently persuading users to submit issues right there in the menu he or she always accesses.

**Comment by Nutomic** [comment]
I think the issue link is easy enough to find if you need it. And its not like we have a lack of issues here :p

**Comment by jebeld17** [comment]
I know that :-)
But it's something that would really grab the attention of the modern consumer

**Comment by Nutomic** [comment]
How about a link to the forum? I think that makes more sense, as the forum is also for general support questions.

**Comment by jebeld17** [comment]
I don't think so. I think a "bug report" section that leads to actually the process of reporting of bugs rather than forum discussions would make more sense for most folks. Most people won't care much about forum discussions and sifting through them because most are a) irrelevant to them, b) a lot of information to sift through with no real "status" indicator for fixes, c) forums aren't for bug reports.

**Comment by Nutomic** [comment]
Right, a link to the forum would also make sense. Still, I don't think the main menu is the right place. Eg on a 5 inch phone, there's not even space for the restart button (you need to scroll).

**Comment by jebeld17** [comment]
In response...
But Google is able to make it work. I'm not trying to sound piffy, but if Google can make it work with the same design algorithms, anyone else can using the same design algorithms.
