### ISSUE TITLE
(idea) Push Notifications

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#814]
Just an idea that may be nice to implement into future versions of ST and ST for Android, but has anyone ever thought about finding a way to  synchronize push notifications using Syncthing from one device to another or one device to all my devices? 
The infrastructure is already there, the program and main idea is already being used in Syncthing, so why not add an extra feature - push notification synchronization being the main one in mind - and seeing how the community and market responds?
Being able to synchronize those annoying notifications I get on all my devices all the time from all different types of programs can be a real hassle, and I believe Syncthing and Syncthing for Android and ARM have what is needed to give the users full control - universally across all platforms - of their notifications, in which there is a market for.
Now yes, ST is open source, but bringing more users into the pool can encourage growth and

**Comment by jebeld17** [comment]
Excuse me, typo via mobile device...
To finish, 
Now yes, ST is open source, and bringing more users into the pool will encourage growth on both the development end through anyone and everyone from the common everyday Joe that may want to report a bug all the way to Tim the software developer that has never heard of St until it began to pick up steam.

**Comment by Nutomic** [comment]
What exactly do you mean by push notifications? They notifications about new folders/devices? And how should they be changed?

**Comment by AudriusButkevicius** [comment]
What you are talking about is impossible. Syncthing syncs files and lets leave it at that.
