### ISSUE TITLE
App force-closes on HTC devices

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#815]
I have already looked into the details and seen of there's anything else posted about this, but there isn't...
Now we all know that ST now warns the user to remove the app from Android's Doze list, but this does not work for everyone even if their OS is on Marshmallow or up. 
Each device manufacturer has different ways of handing these long-running apps, whether in a form of an app meant to "kill" apps or more control over what can run in the background, whatever... This needs to be taken into consideration for the next update.

I strongly and firmly believe that the next small update needs to explain to users to also go into their Manufacturer app's settings and add ST to the whitelist, great example being HTC's "Boost+" app and battery saving tool. Even if I add ST to Android's Doze whitelist, ST will still close on my until I add it to the whitelist in Boost+ as well.

**Comment by jebeld17** [comment]
Similar issue, not the same: #737

**Comment by Nutomic** [comment]
Where should this information be shown? In the same dialog about battery saving, or in a seperate dialog? And can you suggest a text we can use?

**Comment by jebeld17** [comment]
@Nutomic , I would suggest the exact same dialogue. This way, it's all kept in the same place without having the popups getting out of hand :-)

Something like "In addition, some device manufacturers have their own task-killing apps preinstalled into the operating system, in which Syncthing will need to be added to the whitelist to, as well."

I can grab some of the names of tools pre-installed by OEMs to use in this dialogue, hopefully by tomorrow if I am not too busy.

**Comment by jebeld17** [comment]
Here's a rolling list I am starting...

* HTC: Boost+
* ASUS: Mobile Manager
* Lenovo: Lenovo Companion
* Clean Master: Pre-installed on most Verizon devices
* Samsung: Task Manager (Auto-End list)
* LG: Smart Clean

**Comment by licaon-kter** [comment]
* Sony: Stamina
* Samsung: Smart Manager

**Comment by jebeld17** [comment]
Note I didn't state just any app that can be downloaded in the Play Store. I only am stating ones pre-loaded into phones because they actually have full permissions to completely end tasks.

**Comment by licaon-kter** [comment]
Although this is nice, you can't just keep on listing them, keep them up to date and so on, this is really a user thing, they bought the device, they liked it, they should know how to use it.
I feel that a big warning on first setup: "blahblah battery optimisation exclude or else blahblah" is just enough.

**Comment by jebeld17** [comment]
I personally think it's fine to list the few from the major phone manufacturers.

**Comment by Nutomic** [comment]
I've extended the message to mention this. Adding the names of the task killers seems too complicated though.
