### ISSUE TITLE
remove tor

### ISSUE THREAD

**Issue by axet** [syncthing/syncthing-android#816]
Allowing file transferring over Tor is extremely bad form, as the [official Tor](https://www.torproject.org/download/download) site even asks you not to. It dramatically slows down the network for people who actually need to use it. Your "feature" can kill this network.

**Comment by AudriusButkevicius** [comment]
You can't a network used by worlds most evil activities to survive on good will of people. Someone will try to kill it sooner or later so I am fine to give them a training exercise  so they can mend their infrastructure. You are free not to use the feature.

**Comment by axet** [comment]
Not correct. You making bad actions popular, even people who not aware - going to work with bad people to destroy something good.

If bad person target Tor, Tor should be know how to protect it self and it will. But how Tor can protect it self from good people? What is the point? So, it is bad to use Tor against it's "EULA".

Like would it be ok to opensource spam applications and let whole communtiry to support and use it. Should we do this?

**Comment by axet** [comment]
Can you clarify please what exactly Tor does for syncthing people except destroying Tor? "Syncthing over Tor definitely makes sense for people who are concerned about their privacy"

Syncthing dont even allow to sync to machines doesn't have your key and manually configured.

**Comment by licaon-kter** [comment]
So Tor would be better if no one would use it? Interesting.

And for what Bittorrent clients did you raise this issue too then?

**Comment by axet** [comment]
@licaon-kter https://github.com/proninyaroslav/libretorrent/issues/4

**Comment by Nutomic** [comment]
As I said before, Syncthing is not a torrent client. My main Syncthing folder has about 2 GB of data, and of that, I think less than 10 MB change every day. I dont see how this would be a problem.

**Comment by licaon-kter** [comment]
@axet Nice. Do tackle my other questions too.

**Comment by axet** [comment]
@licaon-kter you right, use Tor to transfer files, flood it, and it will be not a problem for NSA.
