### ISSUE TITLE
IPv6 not supported by DNS

### ISSUE THREAD

**Issue by grinapo** [syncthing/syncthing-android#817]
Cannot discover devices. The log contains an unsettling comment: 
`dynamic.go:65 ... failed to lookup dynamic relays ... dial tcp: lookup relays.syncthing.net on 1111:2222:3333::33:53: dial udp: too many colons in address 1111:2222:3333::33:53:
`

(It's the DNS server's ipv6 address.)

### Version Information

    App Version: 0.9.2
    Syncthing Version: v0.14.14

**Comment by AudriusButkevicius** [comment]
this shouldn't matter much, if you're on v6, relays shouldn't really matter.
If you wish, reraise this issue on the main syncthing repo, but I vaguely recall there being a simillar issue already.

**Comment by AudriusButkevicius** [comment]
The issue here is the patch to fix Go DNS on Android not handling v6 DNS servers

**Comment by grinapo** [comment]
What's the progress here? Do we wait for _go_ upstream patch? If yes, where's the upstream issue [to track]? If not, what else?

This bug basically seem to make it completely impossible for syncthing to start on ipv6: no connections _ever_ established.

**Comment by AudriusButkevicius** [comment]
We patch stdlib, and that's broken, as it needs to quote v6 addresses in [ and ]. Feel free to file a PR to the patch.

**Comment by grinapo** [comment]
You mean the https://github.com/syncthing/syncthing-android/blob/master/patches/golang/all/dns.patch patch?

**Comment by AudriusButkevicius** [comment]
Yes

**Comment by uqs** [comment]
Hey, what is the status here? I cannot use syncthing on android currently, as it is not able to resolve hostnames to IPs on my IPv6 network here. C'mon guys ...

**Comment by AudriusButkevicius** [comment]
no status, nobody is working on this

**Comment by Nutomic** [comment]
Fixed in #853.
