### ISSUE TITLE
Viewing logs doesn't work

### ISSUE THREAD

**Issue by lukash** [syncthing/syncthing-android#818]
Going to Settings -> Debug -> Open Log, most of the time it just says "Retrieving logs..." and nothing happens. I've had a few lucky times when it actually worked.

    App Version: 0.9.2
    Syncthing Version: v0.14.14
    Android Version: Android 6.0.1

**Comment by licaon-kter** [comment]
The Android log works?

**Comment by lukash** [comment]
Nope, same stuff. Not sure how long it should take, I waited ~10 seconds.

**Comment by Nutomic** [comment]
It shows immediately for me, also on Android 6.0. Can you try if `adb logcat` shows any errors when you open the log? Btw you can also access the [Syncthing log on the sdcard](https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions#where-are-the-logs).

**Comment by lukash** [comment]
Well, I went through the process of making `adb` work only to find out it show immediately now too. As with #820 I am not able to reproduce it now. Inbetween the phone was rebooted a few times and some stuff installed. Probably some rare condition, but I was fiddling with it for quite some time, did numerous Syncthing restarts etc...

For the record, I had one more issue in the yesterday's state - when the battery saving was on for Syncthing and I got the popup dialog in Syncthing and tapped 'later', I was unable to change system settings (disabling the relaying to be precise), it would come back on after a restart. After I turned off battery saving, I was able to change the option. I wanted to reproduce it again before reporting, but now it works.

**Comment by Nutomic** [comment]
Yes, those settings are disabled if Syncthing is not running (like in battery saving mode). Thats because the settings are set in Syncthing, and that doesnt work if Syncthing isnt running.

**Comment by lukash** [comment]
Yes.. well Syncthing was running and I was able to change those, but the changes didn't stick. I'd say this, the log not being shown and the UI not updating was caused by some weird communication problem between the app and Syncthing. At the same time I was able to set up some folders - at least I think, I could have created them before the problem occurred...

**Comment by lukash** [comment]
I'm in the state when I can't get to the logs once again. If you want me to try something, say so now :)

**Comment by Nutomic** [comment]
Hmm i'm also getting this sometimes, but I cant see any crash or such that would cause this.

@Zillode Do you have any idea?

**Comment by AudriusButkevicius** [comment]
Why don't you just tap into the text log?

**Comment by Nutomic** [comment]
I just added the log file in the last release, this code is much older. Also, the log file doesn't give us logs for the app itself (but I'm not sure we actually need that).

**Comment by Zillode** [comment]
Maybe logcat only works if you have enabled developer mode?

**Comment by lukash** [comment]
@Catfriend1 honestly no idea, I've only did it a few times since the time I was getting the error and it was working, but syncthing also wasn't under any syncing load, which it was when I got the error originally, so it may be related. I also just tried it now and it's working.

I don't mind you closing the issue if you want.
