### ISSUE TITLE
Using relay on a local network

### ISSUE THREAD

**Issue by lukash** [syncthing/syncthing-android#819]
Syncthing always uses a relay, even though both devices are on local network without limitations. This happens even if I turn off relay and global discovery (if that changes anything) on both ends. I've had one time when they actually connected on local network. That was when relay was turned off on desktop only but I can't reproduce it again.

    App Version: 0.9.2
    Syncthing Version: v0.14.14
    Android Version: Android 6.0.1
    Remote Desktop Syncthing Version: v0.14.15

**Comment by licaon-kter** [comment]
The other device is listed with IP or dynamic? Try with IP:port

**Comment by AudriusButkevicius** [comment]
Being on the local network is not enough. The network has to support multicasts, etc to perform discovery.
Furthermore, on Windows, if your network marked as "public" (oppose to work or private), it will prevent any discovery packets from leaving and arriving at the machine.

**Comment by lukash** [comment]
Scratch this, sorry guys, it works. I got confused by IPv6 in the logs and the seemingly low speed at which it is running and still killing my wifi (I thought it's killing my internet connection).
