### ISSUE TITLE
Open folder crash app

### ISSUE THREAD

**Issue by lukaszjurczak** [syncthing/syncthing-android#822]
There is problem with this new feature.
When I click folder icon from the app then it's immediately crash.

App Version: 0.9.3
Syncthing Version: v0.4.16
Android Version: Android 6.0.1 (Nexus5, root)

**Comment by Nutomic** [comment]
I suppose you don't have a file manager installed? Or your file manager doesn't handle the intent.

Either way, I'll make sure it doesn't crash for the next version.

**Comment by lukaszjurczak** [comment]
I have installed Total Commander. It doesn't ask which app use to open - just crash.

**Comment by DrSchnagels** [comment]
Same issue here, also with Total Commander as single file manager installed.
Thanks for fixing this bug!

**Comment by Nutomic** [comment]
Fixed the crash. As for Total Commander, the app needs to support `resource/folder` intents. Best contact the developer and tell him that.

**Comment by PaulAnnekov** [comment]
Bad thing is `resource/folder` is supported by 1-2 apps from top 20 file managers :(. Most of the managers support only `ACTION_GET_CONTENT`, which is not what we need.
