### ISSUE TITLE
Can't sync from android. Error: Closed: reading length: EOF

### ISSUE THREAD

**Issue by dessalines** [syncthing/syncthing-android#824]
Trying to sync a newly set up folder(around 1GB) from android to a desktop syncthing.

On my android, I look at the devices tab, and it connects and starts uploading at a good speed for around 5 seconds, then disconnects for no reason.

On my PC, it still shows my device as being connected, but the logs give the error `Closed: reading length: EOF`, or sometimes: `Puller: Final: peers who had this file went away, or the file changed while syncing`.

The syncing broke since the most recent android version, so I tried to set up a brand new folder, and it has the same problem. 

I also can't view the logs in the android version, it times out.

Android, v 14.16
Desktop Linux, v14.17

**Comment by licaon-kter** [comment]
Device? Android version? Ever enabled root mode? Syncing from internal storage or SD card?

**Comment by dessalines** [comment]
Samsung galaxy s4, Android 5 lollipop, syncing from internal storage, never enabled root mode. I tried syncing to two different PCs, and they both have the same behavior, it disconnects after a few seconds.

**Comment by Nutomic** [comment]
Did you check the Syncthing logs on both sides? Generally, the forums are a better place for support questions.

**Comment by dessalines** [comment]
Unfortunately the logs on android are broken(or at least not working for me), but I could post the whole log from my PC. This was a situation where I had ignore deletes, and I think a newer version of syncthing may have changed how that works.... either way, I just deleted the folder, and now the devices seem to be connecting fine again.

I'll close this issue and reopen it if it props up again.

**Comment by Nutomic** [comment]
FYI regarding logs: 
https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions#where-are-the-logs
