### ISSUE TITLE
Big files - "pull: peers who had this file went away, or the file has changed while syncing. will retry later"

### ISSUE THREAD

**Issue by olegon-ru** [syncthing/syncthing-android#826]
### Version Information

Syncthing Version:
v0.14.17, Linux (64 bit) at desktop side (Fedora 25 64bit)
Version     : 0.14.17
Release     : 1.fc25
Repo        : decathorpe-syncthing

v0.14.16, Linux (64 bit) at Android side
Samsung Galaxy S7, Android 6.0.1
App: 0.9.3

Checked two devices (my S7 and my wife's S7) against one desktop. Some days ago, we can't charge our devices, as I researched, because of Synchting activity (it works when charging and connected wi-fi).

Tons of photo synced without any problem. But recorded video can't be uploaded to desktop. 1Gb file at the my wife's S7, and 2Gb and 4Gb at my phone.

When I checked log, it try to upload file again and again...

> янв 01 22:30:03 oops syncthing[15478]: [P3W2N] INFO: Device AXBCH-GYYUN52-XNA62GW-HQLGATJ-5LW73XS-YFP2JIU-ATGXELK-FYNQY client is "syncthing v0.14.16" named "TanyaS7"
> янв 01 22:37:33 oops syncthing[15478]: [P3W2N] INFO: Puller (folder "TanyaPhoto", file "Camera/20170101_003148.mp4"): pull: peers who had this file went away, or the file has changed while syncing. will retry later
> янв 01 22:37:33 oops syncthing[15478]: [P3W2N] INFO: Connection to AXBCH-GYYUN52-XNA62GW-HQLGATJ-5LW73XS-YFP2JIU-ATGXELK-FYNQY closed: read timeout
> янв 01 22:37:33 oops syncthing[15478]: [P3W2N] INFO: Puller: final: peers who had this file went away, or the file has changed while syncing. will retry later

this log strings repeated many times with my and wife's phone.

Tried to clean database, set up high priority, switch to application (not background) mode, setup to direct and relay mode connection. DIsabled IPv6, disabled compression. All synced very well, but big mp4. Filesystem is btrfs, so, no problem with big files at desktop.

**Comment by olegon-ru** [comment]
I copied mp4 file to another directory, but without any success. As before, at desktop appeared temporary file with the same size and progress frozen at 47%...

**Comment by AudriusButkevicius** [comment]
You'll have to touch the file to fix this. This usually happens when media file indexers modify files without adjusting the modification timestamps.

**Comment by olegon-ru** [comment]
Hm... You suppose video file modified after creation at both devices? This is video file, recorded by phone.
I turn off "disabledTempIndexes" parameter at this folder and file synced... Uff... Reinstallation of SyncThing not helped. May be this is some workaround, but only disableTempIndexes=true helped.

**Comment by AudriusButkevicius** [comment]
Hmm strange, temp index is only effective when there are multiple source devices involved, which doesn't seem to be the case in your case, so I am skeptical to believe that it's that that helped you. More likely the reinstall. Yeah android media indexer does weird things to files after they have been created.

**Comment by olegon-ru** [comment]
As I said before, this problem is occured on two devices. I tested variants on wife's phone (and reinstall app too), but on my phone I switched only indexes parameter and disable local announce (without any reinstallation e.t.c.). And it works! I don't know how it syncing now, but I rebooted device and changed many other parameters without success before...

**Comment by kai11** [comment]
I have exactly the same problem and I have no idea where I can find this setting. Hints, please?
