### ISSUE TITLE
When Syncthing service is busy, the app stops updating

### ISSUE THREAD

**Issue by lukash** [syncthing/syncthing-android#827]
Previously discussed in #820.

Whenever the Syncthing service is busy syncing or just looping endlessly over unsyncable files (https://github.com/syncthing/syncthing/issues/3851), the Android app will stop updating the folder and device lists (like the status of the folders, number of files synced etc.). Sometimes it would update from time to time (say once a minute), very often it would not update at all.

Changes made in the settings or in the properties of a folder or a device made in such a state will also not make it through to the Syncthing service. I can for example switch with what device a folder is shared, it will appear switched, but when I go to the webUI, it is not switched there. After a restart it will again show in the app as unswitched.

It appears there is some problem communicating with the service when it is busy and the app reports no such problem to the user. This makes it seem totally unreliable.

**Comment by Nutomic** [comment]
I guess this has something to do with the fact that all API requests are handled sequentially. We should switch to a proper networking library like Volley.
