### ISSUE TITLE
Crash on startup. NumberFormatException on minDiskFreePct

### ISSUE THREAD

**Issue by konradmb** [syncthing/syncthing-android#829]
Syncthing is crashing on startup for me. Looks like I've set minimum free space to 0.5% in 0.8.x version, and now I can't change it. It would help if minDiskFreePct was set to float.

Log:
D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.nutomic.syncthingandroid, PID: 30396
E AndroidRuntime: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 0.5 at line 1 column 781 path $.folders[0].minDiskFreePct

### Version Information

    App Version: 0.9.3
    Android Version: Android 6.0

**Comment by Nutomic** [comment]
Fixed for the next version. For now, you will have to reinstall the app, and not change that value to a float.
