### ISSUE TITLE
Use the same description for Master / Sent Only

### ISSUE THREAD

**Issue by PanderMusubi** [syncthing/syncthing-android#832]
Use the same description in the app for Master or no Master as in the webgui (on smartphone or computer) which is Sent Only or Sent & Receive. These different names confuse users.

### Version Information

    App Version: 0.9.3 (installed from F-Droid)
    Syncthing Version: v0.14.18
    Android Version: Android 6.0.1 / Cyanogenmod 13.1.2

**Comment by PanderMusubi** [comment]
See also https://github.com/syncthing/syncthing/issues/3889

**Comment by super9mega** [comment]
what would you change it to? i see the file that you would change is 
[https://github.com/syncthing/syncthing-android/blob/master/src/main/res/values/strings.xml](url)
but you have to change it to a single name, would it be called "receive?"

**Comment by super9mega** [comment]
resolved #832 by #878

**Comment by PanderMusubi** [comment]
Exactly the same 1-of-n selection as in the GUI (now two options but will probably be 3):
- Send only (Master)
- Receive only
- Send & Receive
