### ISSUE TITLE
Syncthing timeout upon service reboot

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#833]
Syncthing (ARM Android) tends to timeout and/or freeze completely on the "loading" screen after manually restarting the Syncthing service.
It often - as said - freezes completely giving me no other choice but to force quit the app in my system settings.

I was able to grab a bug report while Syncthing took an excessive amount of time after a Syncthing service reboot, but I wasn't able to capture one from when the app froze entirely.
Hopefully this will give some insight into why this is being caused.

**Comment by jebeld17** [comment]
Sorry, I'm making this report via the mobile site and it doesn't have an "upload" section.

Here's a copy of my bug report on Google Drive:
https://drive.google.com/file/d/0B6ihhZN41GENMFNEN3FYbjF3Mms/view?usp=drivesdk

**Comment by jebeld17** [comment]
Okay, I was able to catch it when the app got caught indefinitely on the "loading" screen:
https://drive.google.com/file/d/0B6ihhZN41GENdW55Mk9fMkpuZlU/view?usp=drivesdk

**Comment by Nutomic** [comment]
I couldnt see any errors in there. It might help if you can narrow down the log (only from the time where the problem occurs). 

When this happens, can you access the Syncthing web ui via localhost:8384 in the browser? (it will show a certificate warning which is normal)

**Comment by jebeld17** [comment]
No certificate warnings at all.

**Comment by Catfriend1** [comment]
Frozen due to age
