### ISSUE TITLE
Sync not working on ARMv8 devices

### ISSUE THREAD

**Issue by Groggy1** [syncthing/syncthing-android#835]
### Version Information
    App Version: 0.9.4
    Syncthing Version: v0.14.19
    Android Version: Android 7.0/LG G5 (H850)

Syncthing stopped working after updating my phone from 0.14.16 to 0.14.19. After some troubleshooting on IRC are there two logs, the first is from the phone. http://pastebin.com/4aXkPFky. The second is from the computer. http://pastebin.com/JD0Xmidn

The web UI on the computer first shows how the phone are connected and then isn't. The web UI on the phone still shows that it's connected to the computer even after it is disconnected.

I don't know what more one would say about this error, but I will gladly answer any questions.

**Comment by Jalbre2** [comment]
Same issue here.

**Comment by wweich** [comment]
What phones do you use? 32Bit or 64Bit CPU?
The current version is the first with a 64Bit compile (AArch64 instead of ARM).
Probably related: https://forum.syncthing.net/t/update-to-version-19-looses-connection-and-breaks-sync/9057

**Comment by Jalbre2** [comment]
Nexus 6P

**Comment by Groggy1** [comment]
I saw that forum post right after my post @wweich. My phone is a LG G5, which has a 64 bit processor. So I guess the change in how the app is compiled is the reason why I'm having problem.

**Comment by Jalbre2** [comment]
Is there an APK of the version before this available?

**Comment by Nutomic** [comment]
You can always get old versions from [F-Droid](https://f-droid.org/repository/browse/?fdid=com.nutomic.syncthingandroid). Note that you have to reinstall due to different signatures.

**Comment by Nutomic** [comment]
ping @calmh @AudriusButkevicius

**Comment by DrSchnagels** [comment]
The new version doesn't work at all for me. I reset the app, reset the database, tried old hash method. Nothing. It seems not to even scan files anymore :(.

Nexus 6P, 7.1.1., worked pretty much flawlessly with previous version.

**Comment by wweich** [comment]
As a workaround, you can enable `limitBandwidthInLan` in advanced settings and set a rate limit to 102400 (100MB/s) on the phone. No need to change anything on the other devices.

**Comment by DrSchnagels** [comment]
Did that. Phone started to connect to my pc. Phone started to hash my three folders in super fast speed (in total 22 GB, took about 4 mins!!).
Would you care to explain how you found this strange workaround? :D

**Comment by DrSchnagels** [comment]
... and the phone didn't even get warm from the hashing!!! It used to be really hot on the backside.
Amazing new hash method!
Thanks a lot and many greetings from super cold Germany @ Nutomic !

**Comment by wweich** [comment]
The hashing is the same (afaik) but the current version is now compiled for 64Bit so it can use the integrated functions of the CPU, which is faster and not so "demanding" on the CPU.

There is a discussion of the forums, where it was suggested, that the rate limiter could be the problem so I tested it :): https://forum.syncthing.net/t/android-arm64-version-0-14-19-looses-connection-and-breaks-sync/9057

**Comment by Groggy1** [comment]
Setting the speed limit made my Syncthing syncing. Thanks for the information about that!
