### ISSUE TITLE
No syncing

### ISSUE THREAD

**Issue by myonov** [syncthing/syncthing-android#836]
After last update I can no longer sync folders. I've added a file to a synced folder (on a remote machine) and expected to have it on my phone. I can see from the web interface that the remote folder has 6 files. However on my phone it shows that the folder is synced and there are 5 files.

    App Version: 0.9.4
    Syncthing Version: v0.14.19
    Android Version: Android 6.0 MRA58K

**Comment by wweich** [comment]
dup of #835 (if you have a 64Bit CPU).

You can either wait for 0.9.5 wich uses v0.14.18 instead of 0.14.19, or you can use the workaround posted in #835.
