### ISSUE TITLE
Not synchronizing to Windows 10 x64 devices

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#837]
Syncthing does not seem to be syncing *anything* from my Android device to any x86 and x64 bit PCs. Synchronizing between Android devices works nicely though, which leads me to think this is a compatibility issue across Android to Windows 10.

**Comment by AudriusButkevicius** [comment]
Update to latest version.

**Comment by wweich** [comment]
@AudriusButkevicius I think you refer to the limiter problem. But if it's true, that he can sync between Android devices, this is another issue.

@jebeld17 Which Syncthing version do you use on the different devices?

**Comment by AudriusButkevicius** [comment]
Regardless, this is not an actionable report, just a report that does not work, which should be handled on the forum first, until proven a bug.
