### ISSUE TITLE
Syncthing won't auto-restart after update

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#845]
Syncthing Android v0.9.6, running on Syncthing framework v0.14.22, won't auto-restart the service. The app does not auto-restart after the recent app update or at boot, even though the settings say different.

I have checked in my battery settings and Syncthing is set in the Battery Optimization whitelist.

System details...
OS Version: Nougat 7.0
Security patch: 01 January 2017
Build number: NRD90M
Tags: release-keys
Bootloader: 1.0.0.0000
SDK: 24
Font scale: Normal
Time zone: Eastern Standard Time
Uptime: 02:21:17
Uptime (w/o Deep Sleep): 01:47:17
Radio: 1.0.U010241a@61107_76.02_F
Root: Unavailable

**Comment by jebeld17** [comment]
[Castro Report.txt](https://github.com/syncthing/syncthing-android/files/769466/Castro.Report.txt)
System Report, via Castro app v2.2.1.

**Comment by Jalbre2** [comment]
I downgraded to 0.9.3 due to this and some other similar issues with instability. Hopefully some of it gets addressed

**Comment by Nutomic** [comment]
Do you have "always run in background" enabled? If not, it wont start on boot. What about sync on wifi/charging? Logcat might also be helpful.

**Comment by Jalbre2** [comment]
Yes, Always run in background is on. So is Wifi only.

What's the proper way to get the logcat?

**Comment by jebeld17** [comment]
I do have "always run in the background" on as well... All the same settings I've had before
