### ISSUE TITLE
Syncthing crashes on Android TV (SATV)

### ISSUE THREAD

**Issue by AdamPan** [syncthing/syncthing-android#847]
I'm attempting to get Syncthing running on my Shield Android TV, but can't seem to make it more than a day without Syncthing crashing and failing to restart.

I am syncing a large folder (811 items, 111 subfolders, ~882 GB data)

This is what I see in the log file after a crash:

```
SIGILL: illegal instruction
PC=0xa0e30 m=9

goroutine 0 [idle]:
```

The crashes seem to happen without any pattern, without any other log activity before or after a crash

    App Version: 0.9.6
    Syncthing Version: v0.14.22
    Android Version: Shield Experience 5.0.1 (Android Nougat) for SHIELD 2017

**Comment by Nutomic** [comment]
Can you post more of the log? I don't think these 2 lines are enough.

**Comment by AdamPan** [comment]
Full log below. 
[syncthing.log.zip](https://github.com/syncthing/syncthing-android/files/773175/syncthing.log.zip)

**Comment by Nutomic** [comment]
ping @calmh @AudriusButkevicius

**Comment by calmh** [comment]
Maybe don't run the arm64 version? No idea, seems to be some incompatibility anyway.

**Comment by Nutomic** [comment]
The arm binary is picked automatically by Android, so it's not easily possible to pick another one. And if the device picks arm64, it should work.

**Comment by AudriusButkevicius** [comment]
Well maybe its one of the arm64 cpus that do not support the sha opcodes. Perhaps enabling legacy hashing in android app would fix it.

**Comment by calmh** [comment]
Looks like the "sigill" may be a red herring given that it's on line 186 here:

```
 180 // systemstack_switch is a dummy routine that systemstack leaves at the bottom
 181 // of the G stack. We need to distinguish the routine that
 182 // lives at the bottom of the G stack from the one that lives
 183 // at the top of the system stack because the one at the top of
 184 // the system stack terminates the stack walk (see topofstack()).
 185 TEXT runtime·systemstack_switch(SB), NOSPLIT, $0-0
 186         UNDEF
 187         BL      (LR)    // make sure this function is not leaf
 188         RET
```

It's also crashing in the middle of setting up a defer so I suspect some stack shenagans. No idea about the details. But I think this will probably end up undebuggable given the circumstances. Perhaps the TV is broken.

**Comment by AdamPan** [comment]
So far legacy hashing seems to be working.

**Comment by AdamPan** [comment]
Nevermind, it crashed again. Log attached.

[syncthing.log.txt](https://github.com/syncthing/syncthing-android/files/775579/syncthing.log.txt)

**Comment by Nutomic** [comment]
Should be possible with Tasker, but I'm not familiar with that.

**Comment by Catfriend1** [comment]
Please use Tasker as a workaround to restart syncthing. If more people have the same issue we can reopen the ticket. Best case one developer with such a tv is able to chime in.
