### ISSUE TITLE
Can't re-run it after disabling

### ISSUE THREAD

**Issue by usakhelo** [syncthing/syncthing-android#848]
I disabled the app from running on the background some time ago
Today I wanted to start it again to sync some files
On app startup I get the screen "Syncthing is disabled. Do you want to change your preferences"
I choose Change Preferences and check Always Run in Background in Run Conditions.
Nothing is changing, app is not going past the sceen Syncthing is disabled.
Restarted the phone but it didn't help.

### Version Information

    App Version: 0.9.6
    Syncthing Version: v0.14.22
    Android Version: Android 7.1

**Comment by licaon-kter** [comment]
Do you have an Wi-Fi restriction? Uncheck "only on..."

**Comment by usakhelo** [comment]
It took some time, but it started to work correctly on its own. Thanks and sorry for keeping this open for so long. Closing it.
