### ISSUE TITLE
Interrupted system call

### ISSUE THREAD

**Issue by rkfg** [syncthing/syncthing-android#85]
It shows a red message for my DCIM/Camera repo (and only for it): Interrupted system call. The problem is it happens after a while, maybe day or two. So it's hard to provide a logcat. After the message appears, it seems it stops syncing this repo while sitting on "Scanning 100%". The only option is to restart Syncthing (btw, need to add the restart button to GUI). Any hints on this? Happens on Nexus 4 and (possibly) on Nexus 10, will check the latter.

**Comment by Zillode** [comment]
Fixed in next release
See https://github.com/golang/go/issues/8551 and https://github.com/syncthing/syncthing/commit/102a2db1f3fca8a8f0a1b595b044b1b6deda570f
