### ISSUE TITLE
Update to Go 1.8 for a large ARM performance boost

### ISSUE THREAD

**Issue by edrex** [syncthing/syncthing-android#850]
Two important changes related to Go on mobile have recently landed:

 - Go 1.8 has been released, with [SSA compiler backend on ARM](https://golang.org/doc/go1.8#compiler). This results in a significant reduction in binary size, as well as large performance improvements in most cases.
 - Gomobile has had a major release [adding "reverse binding" support](https://www.reddit.com/r/golang/comments/5fno6i/gomobile_now_comes_with_reverse_bindings_for_java/) (Go code calling into native code)

It seems that syncthing-android is currently building using Go 1.4.3. Time to update!

PS I'm tracking this because I'm using gomobile for `$DAYJOB`.

**Comment by wweich** [comment]
The Syncthing binary inside the Android App is compiled with Go 1.7.4.
Go 1.8 was officially released 10 days ago, so one doesn't have to wonder, why the current release didn't use it.
I'm pretty sure, the next release will be compiled with 1.8.

**Comment by edrex** [comment]
@wweich I just figured out that Go 1.4.3 is only used for bootstrapping, thanks. I'll close this, but for the next release y'all should mention the performance improvements in the release notes.

**Comment by AudriusButkevicius** [comment]
Why? Have you measured the actual improvements?
Most of the performance of syncthing comes when we need to hash files, if we are not hashing files we are usually not doing anything intensive hence I don't think you'd actually notice any improvements brought by SSA, as hashing is mostly written in assembly anyways.

**Comment by edrex** [comment]
@AudriusButkevicius I haven't done any benchmarking of Syncthing between Go versions on Arm, and your reasoning seems sound.

I was hoping to see a large improvement in binary size but that doesn't seem to hold either:

Go 1.7.4:
```
ls -sk src/main/jniLibs/armeabi/libsyncthing.so
12016 src/main/jniLibs/armeabi/libsyncthing.so
```

Go 1.8:

```
11672 src/main/jniLibs/armeabi/libsyncthing.so
```

Does syncthing have benchmark tests? I might try to run them on Arm HW to see if there's any change between Go version.

Generally though, improvements in power consumption will have to come from a combination of better integration with the Android platform and optimizing Syncthing itself. The reverse binding support in the latest Go mobile might help with that.

**Comment by Nutomic** [comment]
I looked into the Go mobile thing some time ago (with 1.7 I think), but didn't get anything to work. If you want to try and implement it, that would be great :)
