### ISSUE TITLE
github syncthing/syncthing-android  Building on Windows 

### ISSUE THREAD

**Issue by anneyking** [syncthing/syncthing-android#852]
when I do this:
From a cygwin shell in the project directory, build Go using ./make-go.bash amd64
The cygwin show :
ERROR: Do not use make.bash to build on Windows.
Use make.bat instead.

**Comment by Nutomic** [comment]
ping @AudriusButkevicius

**Comment by AudriusButkevicius** [comment]
I think I did Go bootstrapping myself hence I did nit have this problem. Read the build file and set the location env var of the bootstrapped go yourself.

**Comment by anneyking** [comment]
ping @AudriusButkevicius
Thank you very much for your answer.
