### ISSUE TITLE
Cannot write configuration file (root)

### ISSUE THREAD

**Issue by sirber** [syncthing/syncthing-android#855]
Do not report security issues in this bug tracker. Instead, contact security@syncthing.net directly - see https://syncthing.net/security.html for more information.

If your issue is a support request ("How do I get my devices to connect?" or similar), please use the support forum at https://forum.syncthing.net/ where a large number of helpful people hang out. This issue tracker is for reporting bugs or feature requests directly to the developers.

If your issue is a bug report, replace this boilerplate with a description of the problem, being sure to include at least:

Installed, activated root

Also fill out the version information below and add log output or screenshots as appropriate.

If your issue is a feature request, simply replace this template text in its entirety.

### Version Information

    App Version: 0.9.6
    Syncthing Version: v0.14.x
    Android Version: Android 6.0.1

**Comment by sirber** [comment]
Will clean and add details/screenshot later. Was on my cellphone

**Comment by AudriusButkevicius** [comment]
This is a duplicate, please search open issues.
