### ISSUE TITLE
Pausing individual folders or devices

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#856]
While the official version of Syncthing on PC, Mac OS, and Linux get the advanced feature to pause synchronization of individual folders or devices, the Android variant has been left in the dust and currently has no way to pause individual things unless the user knows how to get to the Web UI and familiar with it in the first place.
This isn't fair to the modern day Android user, and this needs to be addressed.

I would love to see the Syncthing Android app natively support pausing of individual computers and folders just like the rest of the variants for all other OSes.

**Comment by wweich** [comment]
You are right, that this should be implemented, especially as it is needed for #511, but:

> unless the user knows how to get to the Web UI

The Web UI has an entry inside the main menu, it can't get any easier.

> and familiar with it in the first place.

The Web UI is the UI used on any other platform, why shouldn't a user know how to use it?

**Comment by jebeld17** [comment]
If there is such an "easy" Web UI, why isn't the Android app UI based off a lightweight browser - such as Chrome - instead?

**Comment by Catfriend1** [comment]
I made a PR to improve the UI.
