### ISSUE TITLE
[Bug/FR] Do not use HTTPS for GUI by default, or at least make it configurable

### ISSUE THREAD

**Issue by mikp** [syncthing/syncthing-android#858]
Syncthing-android defaults to (as also syncthing does) having the Web GUI listening only to localhost. Still, HTTPS is enforced as a default for syncthing-android, which is useless and bad for usability in my opinion due to only accessible on the same device. 
When trying to disable HTTPS in the Web GUI settings, it is re-enabled after restarting syncthing automatically (this is not what I expect to happen). 

    App Version: 0.9.7
    Syncthing Version: v0.14.24, Linux (AArch64)
    Android Version: Android 6.0 (LG G4 H815)

Please let me know what you think about this or if you need further input, thanks!

**Comment by AudriusButkevicius** [comment]
Why is it useless and bad for usability?

**Comment by mikp** [comment]
Hi AudriusButkevicius, 
sorry for the late reply. In my opinion, HTTPS is not necessary (thus, useless) if only establishing connections within one device. I did not explain what I meant with bad usability: there is a self-signed certificate used, which cannot be verified by the browser and thus leads to a error message about broken encryption, which is misleading here in my opinion.

**Comment by Zillode** [comment]
No HTTPS is required because other applications could setup a mitm service and therefore retrieve the API key. I agree it's bad for usability when using a custom browser, hence this is why we implemented a webgui feature within the app.

**Comment by mikp** [comment]
OK, I see the reason, and also the Web GUI for the first time. 

But still, why is the configuration change not stored: When trying to disable HTTPS in the Web GUI settings, it is re-enabled after restarting syncthing automatically (this is not what I expect to happen).
