### ISSUE TITLE
In the local area network, the problem of long time pairing

### ISSUE THREAD

**Issue by anneyking** [syncthing/syncthing-android#859]
In the LAN, there are two devices. A device scans B device for matching. In a LAN, but why after more than a minute of time, B devices can receive the A device sent to the pairing request?
In the same network, A equipment is not through the transfer of the network to find B devices?

**Comment by licaon-kter** [comment]
Devices put as `dynamic` ? Both devices have an internet connection?

**Comment by AudriusButkevicius** [comment]
Device discovery is cached for 5mins I think, so if the device is not around when we first check it can take some time for them to find each other.

**Comment by anneyking** [comment]
ping @licaon-kter 
The first time I installed Syncthing on Android phone. I did not set any operation.
I think this is the default setting.

**Comment by anneyking** [comment]
ping @AudriusButkevicius 
Thank you very much for your answer.
