### ISSUE TITLE
[IDEA/SUGGESTION] Pause Periods

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#864]
As many cloud services have, I would find to great effect that having a "Pause Period" setting would really help me out, especially when I need to be conserving CPU and RAM usage while doing a task, working on a project I don't want the program adding and removing to the directory the same time I need to focus, or even if I am just borrowing a friend's WiFi hotspot but don't want to sift through all of the settings in Syncthing just to pause the service and than need to remember to turn it back on.

I would like it if the app did that for me: I choose to pause the service, and it gives me a dialogue box for "how long?"

**Comment by jmintb** [comment]
Sounds like a good idea, we could use the [Remote-Control-by-Broadcast-Intents](https://github.com/syncthing/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents) in conjunction with the [AlarmManager](https://developer.android.com/reference/android/app/AlarmManager.html). I will have a crack at it. :)

**Comment by jmintb** [comment]
@Nutomic When using `stopService(new Intent(context, SyncthingService.class))` or `sendBroadcast(new Intent(AppConfigReceiver.ACTION_STOP))` the SyncthingService is not stopping. Any idea why this is not working?

**Comment by Nutomic** [comment]
Not sure, do you see anything in the logs?

**Comment by jmintb** [comment]
If I add logging to the AppConfig class I can see that it is receiving the stop intent and calling `stopService`, but there is no log output from the syncthing service.

**Comment by Nutomic** [comment]
What exactly are you doing? Trying to add this as a feature in Syncthing itself? It would be helpful if you share your code.

**Comment by jmintb** [comment]
I am trying to add this feature into Syncthing itself. I have attempted to stop the Syncthing service two different ways:
`getActivity().stopService(new Intent(getActivity(), SyncthingService.class));`
and
`getActivity().sendBroadcast(new Intent(AppConfigReceiver.ACTION_STOP))`

I am not sure what more code I can share that would be relevant, the above code is run after the amount of time the user wants Syncthing to be paused for has been selected in a dialog.

**Comment by Nutomic** [comment]
Is any Syncthing activity running when you run that code? In that case, the activity is bound to the service, and the service wont be stopped.

Besides, I'm not sure if this is a feature that should be merged into Syncthing itself.

**Comment by jmintb** [comment]
Yeah a Syncthing activity is running. Should we close this it, if it isn't something that will be added to Syncthing?

**Comment by AudriusButkevicius** [comment]
You've missed the word "not" in his sentence.

**Comment by jmintb** [comment]
@AudriusButkevicius Maybe I didn't express my self properly :(.
I did understand that the service will not be stopped if a Syncthing activity is running. If that was what you were refering to?

I edited my comment, to make that fact more clear. :)

**Comment by Nutomic** [comment]
Yeah I guess we should.

**Comment by jebeld17** [comment]
You don't think this can be added?
