### ISSUE TITLE
Syncthing for Android Shows Over 100% is Synchronized.

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#866]
Build info: 2.41.617.3 8.0_g CL857212 release-keys
Syncthing for Android v0.9.7
Syncthing v0.14.24
![screenshot_20170321-085835](https://cloud.githubusercontent.com/assets/9492083/24148475/5d50e79a-0e15-11e7-8675-bfbffe642ab6.png)

Description: Syncthing folders appear in the Android UI to synchronize past a point of 100%, showing a higher numerator in MiB over denominator in GiB.

I have an Android Developer Options Debugging Log I can attach if necessary.

**Comment by Nutomic** [comment]
Right, we calculate the percentage with `local size / global size`, which seems to be the wrong calculation. Does anyone know how the web gui calculates this?

**Comment by jedie** [comment]
I saw this too: local size was bigger than global.

**Comment by jebeld17** [comment]
System dumps incoming.
I'm getting the files ready and uploading in just a few...

**Comment by jebeld17** [comment]
![screenshot-2017-03-21-08-58-43-1](https://cloud.githubusercontent.com/assets/9492083/24328788/607679a8-11c1-11e7-8766-b77eb8ac7067.png)
[bugreport-NRD90M-2017-03-21-08-58-43.zip](https://github.com/syncthing/syncthing-android/files/870569/bugreport-NRD90M-2017-03-21-08-58-43.zip)

**Comment by jebeld17** [comment]
NOTE: Resetting the Syncthing Databases does not resolve the issue.

**Comment by jebeld17** [comment]
(Another note: I didn't mean to close the issue. My bad. I reopened it!)

**Comment by belidzs** [comment]
I can confirm this issue

**Comment by belidzs** [comment]
@Nutomic this might help: https://forum.syncthing.net/t/a-syncthing-indicator/29/2

**Comment by jebeld17** [comment]
I'm having this issue again with the latest updates

**Comment by Nutomic** [comment]
Right now the percentage is already calculated with `inSyncBytes / globalBytes * 100`. We could just do `min(inSyncBytes / globalBytes * 100, 100)`, but I'm not sure if thats correct.
