### ISSUE TITLE
Syncthing (for Android) uses considerable CPU usage

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#867]
Syncthing is using a considerable amount of CPU usage both on average and instantaneouly, according to Qualcomm's Trepn Profiler app.

System details:
Google Nexus 9
Android 6.0.1 (rooted, AOSP kernel)
WiFi Model

**Comment by licaon-kter** [comment]
Is everything sync'ed 100%?

**Comment by jebeld17** [comment]
Yes but no... and another bug I posted lists that Syncthing is actually miscalculating my syncs at over 100% Synchronized.
So the app states they are synced and not at the same time.
It's confusing to explain.

**Comment by jebeld17** [comment]
See Bug #866

**Comment by Nutomic** [comment]
You will have to post more info (logs, steps to reproduce etc), otherwise theres nothing we can do.

**Comment by Catfriend1** [comment]
I assume this to be resolved with the build-fix preventing the java process to go wild and consume much cpu. See https://github.com/syncthing/syncthing-android/issues/1043
