### ISSUE TITLE
Build Syncthing with cgo and GOOS=android

### ISSUE THREAD

**Issue by calmh** [syncthing/syncthing-android#873]
This will hopefully get you better networking support, and we can qualify the remaining Android specializations on the architecture at build time instead of checking at runtime. I tested the procedure and it works fine - at least the build does, I can't test the binaries.

https://gist.github.com/calmh/20c24afc283656695b76f7822c8c8997

**Comment by Nutomic** [comment]
@AudriusButkevicius @Zillode Could you try to integrate this with the existing build scripts? I'm really bad with the Go build tools unfortunately.

**Comment by AudriusButkevicius** [comment]
I am still trying understand what this will give us.

**Comment by calmh** [comment]
I'm assuming that the goos=android platform exists for a reason.

**Comment by AudriusButkevicius** [comment]
It mostly exists for gomobile reasons being able to bind with Java.

From what I've looked at:

```
Audrius@Audrius src $ for A in `find -name '*.go' -or -name '*.s' | grep -v 'test' | grep -v '/cmd/' | grep -v '/build/'`; do grep -l android $A; done
./net/cgo_linux.go
./net/cgo_resnew.go
./net/cgo_resold.go
./net/cgo_socknew.go
./net/conf.go
./os/executable_procfs.go
./os/file_unix.go
./os/user/getgrouplist_unix.go
./os/user/listgroups_unix.go
./os/user/lookup_android.go
./os/user/lookup_stubs.go
./os/user/lookup_unix.go
./runtime/cgo/cgo.go
./runtime/internal/sys/gengoos.go
./runtime/internal/sys/zgoos_android.go
./runtime/internal/sys/zgoos_linux.go
./runtime/os_linux_arm.go
./runtime/rt0_android_386.s
./runtime/rt0_android_amd64.s
./runtime/rt0_android_arm.s
./runtime/rt0_android_arm64.s
./runtime/sys_linux_386.s
./runtime/sys_linux_amd64.s
./runtime/tls_arm.s
./runtime/write_err.go
./runtime/write_err_android.go
./time/zoneinfo_unix.go
```

logging to /dev/log/main
some asm tweaks for runtime and TLS
different location for tz defs
different location for tmpdir
disables fpu checks
disables user id/user group lookups
handling of /proc/self/exe (same as linux)
cgo resolver

**Comment by Nutomic** [comment]
Finally gave this a try, but running into errors, using this code:
```
cd ext/syncthing/src/github.com/syncthing/syncthing

CGO_ENABLED=1 CC=${ANDROID_NDK_HOME}/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc \
  go run build.go -goos android -goarch arm build
```
Output:
```
runtime/internal/sys
go install runtime/internal/sys: mkdir /usr/lib/go/pkg/android_arm: permission denied
exit status 1
exit status 1
```
So it looks like Go is trying to install stuff to system directories (which are handled by the package manager). I could make that work on my laptop, but definitely not on F-Droid. According to [this issue](https://github.com/golang/go/issues/18981), the only solution seems to be waiting for Go 1.10?

**Comment by calmh** [comment]
You can probably pass -pkgdir to handle that

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Nutomic** [comment]
It's working! But I didn't see any way to pass -pkgdir to `build.go build`, so I had to edit the file directly. 

Other than that, I just have to update the build script.

**Comment by calmh** [comment]
Yeah, I meant to `go build`. But feel free to patch `build.go` to take a `-pkgdir` that is just passed along. I'm fine with having that.
