### ISSUE TITLE
Listeners shows 0/0

### ISSUE THREAD

**Issue by DrSchnagels** [syncthing/syncthing-android#874]
While I have disabled NAT, Local Discovery, Global Discovery, Relaying on my Windows client, the Android app shows with the same config 0/0 and the Windows client 1/1.
I use static IP addresses for everything in my network and have static IPs in syncthing too.
Who's wrong here?

Thanks :)

**Comment by AudriusButkevicius** [comment]
You also need to remove listen addresses.

**Comment by DrSchnagels** [comment]
I have "default" in there everywhere. 
But I guess you wanted to April fool me :P.

**Comment by AudriusButkevicius** [comment]
Default will still produce a listener. Have you checked the web ui on android?

**Comment by DrSchnagels** [comment]
Update:
I found out that the webinterface shows 1/1 (like my other machines) BUT the app does display 0/0.
So it seems to be a problem of the app.
It should be reproducible if you try the same config as I do in my first post.

**Comment by wweich** [comment]
The app shows Indexservers. As you don't use Indexservers 0/0 is correct.

The web UI hides the Indexservers if you don't use any. The listeners is another info.

**Comment by DrSchnagels** [comment]
Ahhh, I understand now! It was just very distracting that the number is in red.
I thought I would have "over-configurated" my syncthing ;).

Thanks for clearing this up!
