### ISSUE TITLE
Request: Add time interval for syncing in run conditions

### ISSUE THREAD

**Issue by droidzone** [syncthing/syncthing-android#879]
Multiple carriers allow for free usage of data during time intervals. Kindly consider adding multiple run conditions where sync can be enabled or disabled. It ought to be possible to define multiple intervals of time (from and to) during which it can be run/not.

**Comment by licaon-kter** [comment]
Can't this be automated via Tasker or something?

**Comment by Nutomic** [comment]
Yep, I think this is too complex and specific for the app. You should use the [Remote Control](https://github.com/syncthing/syncthing-android/wiki/Remote-Control-by-Broadcast-Intents) functionality.

**Comment by jebeld17** [comment]
Maybe this can be tied with issue #864?

**Comment by Nutomic** [comment]
That issue is also closed, use Tasker or such if you need more than basic controls.
