### ISSUE TITLE
Only .syncthing.*.tmp files are synched

### ISSUE THREAD

**Issue by nmaggioni** [syncthing/syncthing-android#880]
When synching a folder to my smartphone, all I end up with in the destination folder is a bunch of `.syncthing.FILENAME.EXT.tmp` files. Their dimension looks right, but the contents are corrupt. If I delete them they get replaced.

Reinstalling the app does not solve the problem, and it is not complaining about permissions (which are fully granted).

The same folder syncs fine with the desktop client.

The logs are full of these lines (folder and file names edited):

```
[EKECW] 22:38:17 INFO: Puller (folder "MyFolder", file "myFile.myExt"): pull: peers who had this file went away, or the file has changed while syncing. will retry later
[EKECW] 22:38:17 INFO: Puller: final: peers who had this file went away, or the file has changed while syncing. will retry later.
```

How do I go about collecting more insights on this?

### Version Information

    App Version: 0.9.9
    Syncthing Version: v0.14.26
    Android Version: Android 7.1.2 / LineageOS-based ROM

**Comment by AudriusButkevicius** [comment]
Please use the [forum](https://forum.syncthing.net/) for support.
Please use the search on the forum and the closed issue tracker for similar issues before starting a new thread. 
If this issue is later proven to be a bug, we will reopen this issue or open a new one.

**Comment by nmaggioni** [comment]
This did not happen before the last updates to the app, and on desktop clients it works fine. Does that not qualify this as a potential bug?

**Comment by AudriusButkevicius** [comment]
Not really, issues with these symptoms have been around for ages.
Usually a rescan on the source side fixes it.

**Comment by nmaggioni** [comment]
Totally my bad then, my Google-fu is not strong enough. Sorry :smile:
