### ISSUE TITLE
Error, cannot write to USB-OTG drive

### ISSUE THREAD

**Issue by blakev** [syncthing/syncthing-android#882]
### Version Information

    App Version: 0.9.9
    Syncthing Version: v0.14.26
    Android Version: Android 7.1.1

I'm using a Samsung 128gb thumbdrive as external storage on my OnePlus 3T, but Syncthing in unable to write to a folder that's located on that drive. In the logs it said something about `permission denied`, but the specific line is no longer there -- just an "Error" above the folder icon.

It seems like Syncthing may need to track that the folder/drive is removable, and use the [Storage Access Framework](https://developer.android.com/guide/topics/providers/document-provider.html).

I don't know enough about Android app development to be much more helpful.

**Comment by AudriusButkevicius** [comment]
Please search before opening new issues.

Dup of #29

**Comment by blakev** [comment]
@AudriusButkevicius I searched for USB and OTG, neither of which are even mentioned in that ticket.

**Comment by licaon-kter** [comment]
No, not mentioned, but once that is tackeled this would be too.
