### ISSUE TITLE
Feature Request: Sync Filter not only when running in background

### ISSUE THREAD

**Issue by joker234** [syncthing/syncthing-android#889]
First: Thanks for the App!

I had the problem, that I don't want Syncthing to run in background because I don't need this and I think it permanently uses litte bit power. But I want Syncthing to only sync if I'm connected with Wifi. Is there a reason, why I can use this options only with the „running in background“ option?

**Comment by capi** [comment]
The idea behind is that you either:
1. Manually start it and are responsible for stopping it again
2. Let it run in background

In the 1st case, it is assumed you want to sync, if you start the application.
In the 2nd case, it makes sense, that you can define conditions when you want to run it.

**Comment by joker234** [comment]
Thanks for clarification.

I want to use case `1.` but with the confidence that no mobile data will be used if I lose Wifi connection or forget to stop the app. I forgot to stop the app onece (maybe because the app is not actively visible if I don't look into the notifications actively).

Other Apps have a possibility like that and I think this feature would make your app more awesome.

**Comment by tynsh** [comment]
I would also love to see this feature in the syncthing app. How about adding an additional global setting for exclusive usage of WIFI while keeping the other one related to running in background?

Unfortunately this would require adding some kind of notification on the start screen of the app when sync is disabled because the device is not connected via WIFI.

**Comment by wweich** [comment]
You can disable mobile data for Syncthing in the Android system settings. It says background data, but it never let Syncthing connect on mobile, even when it was in foreground.
