### ISSUE TITLE
Add option let us ignore DELETE action on files/directory

### ISSUE THREAD

**Issue by netroby** [syncthing/syncthing-android#893]
I am want to using syncthing-android to upload my DCIM (pictures) to my server.
Once i finished upload picture, i would like to delete them on my phone. 

But i would like keep all photos on my server.

So please add an option, let us ignore DELETE , do not sync delete action to server(Will delete file on server).

**Comment by netroby** [comment]
I can see an option here https://github.com/syncthing/syncthing-android/blob/23deb9a0ea00ceb80d8249ad64cdd7f29e75acae/src/main/java/com/nutomic/syncthingandroid/model/Folder.java#L28

**Comment by AudriusButkevicius** [comment]
Please read the advanced settings section of syncthing docs. If you need to enable that setting it can be accessed via web ui.
