### ISSUE TITLE
Syncthing process killed after a few minutes on Android 7.1.1

### ISSUE THREAD

**Issue by princejosuah** [syncthing/syncthing-android#894]
Hello,

I've finally updated to Android N a few days ago, and Syncthing process is killed after a few minutes (15? 30? 60? can't tell, as I just open the notification bar and note that Syncthing isn't running anymore).

In Android : I have "doze mode" enabled, but Syncthing is set as "not optimized".
In Syncthing : it is set to "always run in background", do not respect Android battery saving setting and "run service with foreground priority".

I'm using a OnePlus 3 and everything has been going smooth wirth Android 6.0.1.

#### Version Information
Syncthing Version: 0.14.25 (as the latest one is reported to be crashing, as per playstore reviews)
Android Version: Android 7.1.1

**Comment by licaon-kter** [comment]
Logcat?

**Comment by princejosuah** [comment]
Hi, 

When I try to share logs I got from within Syncthing, my folder names don't seem obfuscated. How can I avoid that?

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by AudriusButkevicius** [comment]
Search replace manually.

**Comment by Nutomic** [comment]
You should probably try the various experimental options. Feel free to reopen if you have any logs.
