### ISSUE TITLE
Save and Cancel buttons hidden when keyboard is open while sharing

### ISSUE THREAD

**Issue by nvllsvm** [syncthing/syncthing-android#897]
When sharing a file with Syncthing, the following opens immediately. The keyboard is open and the Save and Cancel buttons are hidden. This was initially conufsing. It is more convenient to have this visible so the extra step of closing the keyboard is not needed.

![tmp_704-screenshot_20170602-000009467062384](https://cloud.githubusercontent.com/assets/6550543/26710275/b8f71c1e-4726-11e7-8221-391908592e8c.png)

Upon closing the keyboard, the buttons unveiled at the bottom of the screen.
![tmp_704-screenshot_20170602-0000321882644145](https://cloud.githubusercontent.com/assets/6550543/26710296/e0e42884-4726-11e7-9274-05975037bac0.png)

App version: 0.9.10 from F-Droid
OS: LineageOS 14.1 by SultanXDA
Device: OnePlus 3T

**Comment by Nutomic** [comment]
Fixed, thanks for reporting!
