### ISSUE TITLE
No compatible file manager found

### ISSUE THREAD

**Issue by seb-1204** [syncthing/syncthing-android#900]
what happened,
I keep receiving the message '_No compatible file manager found_' when I try to browse/select a folder. See attached screenshot.
![screenshot_20170601-191000](https://cloud.githubusercontent.com/assets/307449/26755748/6c3a305c-48a5-11e7-84f4-3ccd6c86eb4b.png)

    what you expected to happen instead, and
I expected to have a file/folder selection dialogue to pop up in which I can select the folder to be synced.

    any steps to reproduce the problem.
click on the folder symbol of the standard _Camera_ folder

There is a discussion in the forum however no tangible solution.

### Version Information

    App Version: 0.9.10
    Syncthing Version: v0.14.29
    Android Version: Android 7.1.2 / LinageOS 14.1-20170518-NIGHTLY-m8

**Comment by wweich** [comment]
This is because you don't have a compatible file manager to browse the sync folder. This is just to browse the existing folder with a file.manager.

To select a folder to sync, just add a new folder and you will get a folder picker.
