### ISSUE TITLE
Sort order of folders in "Save to Syncthing" should match the main screen

### ISSUE THREAD

**Issue by nvllsvm** [syncthing/syncthing-android#902]
On the "Save to Syncthing" screen - the sort order of the folders appears random. It would make more sense if the order is the same as it is on the main screen.

![screenshot_20170605-104048](https://cloud.githubusercontent.com/assets/6550543/26813845/1b98acae-4a4f-11e7-9591-823eb509d9f5.png)

![screenshot_20170605-104103](https://cloud.githubusercontent.com/assets/6550543/26813844/19866eb0-4a4f-11e7-88c9-f48e045cc963.png)

App version: 0.9.10 from F-Droid
OS: LineageOS 14.1 by SultanXDA
Device: OnePlus 3T

**Comment by jmintb** [comment]
The folders are sorted in alphabetical order in the app, so all we have to do is sort the list of folders on the "Save to Syncthing Screen" in alphabetical order.
