### ISSUE TITLE
Problem with the Syncthing Webpage

### ISSUE THREAD

**Issue by Mannshoch** [syncthing/syncthing-android#903]
If I try t connect the Syncthing web-page many times I have a connection error, as if the website not exist.
Even if it connect I got sometimes the Dialog from the web-page that the connection is lost.

If I try to use REST to get Data from Syncthing, this never work (Token is checked and correct). I got:
`unexpected token a '<a href="https://localhost:8384/rest/system/config">Temporary Redirect<\a>. (JSON: :ParserError)`

Fairphone2 
Android 5.1
Syncthing 0.9.10 -> f-droid
Terminal: Termux (Ruby in Termux installed)

Script (works on desktop):
```
# developed by canton7 modified by Mannshoch
# https://github.com/syncthing/syncthing/issues/4039#issuecomment-286110386
API_KEY = 'TOKEN'
HOST = 'http://localhost:8384'

require 'uri'
require 'net/http'
require 'json'

uri = URI(HOST)
http = Net::HTTP.new(uri.host, uri.port)
headers = {
  'X-API-Key' => API_KEY
}
time = Time.new

config = JSON::parse(http.get('/rest/system/config', headers).body)
connections = JSON::parse(http.get('/rest/system/connections', headers).body)

config['devices'].each do |device|
  address = connections['connections'][device['deviceID']]['address']
  puts "+#{device['name']},+#{address},+" + time.strftime("%Y-%m-%d-%H")

end
```

**Comment by AudriusButkevicius** [comment]
You need to use https

**Comment by Mannshoch** [comment]
No effect. If I change 
HOST = 'http://localhost:8384'
to
HOST = 'https://localhost:8384'

I got the same error
The complete error:
```
/data/data/com.termux/files/usr/lib/ruby/2.4.0/json/common.rb:156:in `parse': 743: unexpected token at '<a href="https://localhost:8384/rest/system/config">Temporary Redirect</a>. (JSON::ParserError)

'
        from /data/data/com.termux/files/usr/lib/ruby/2.4.0/json/common.rb:156:in `parse'
        from /data/data/com.termux/files/home/.termux/tasker/data.rb:17:in `<main>'
```

**Comment by AudriusButkevicius** [comment]
So you should try and get your http library to follow redirects. Its not clear why it's redirecting though.
