### ISSUE TITLE
Rescan media after syncing. Implemented yet?

### ISSUE THREAD

**Issue by le-mon** [syncthing/syncthing-android#904]
Hey there, 

i sync my /storage/emulated/0/ with a folder on my linux machine. It works perfect. 
But sometimes it takes forever for the phone, to "scan" new synced songs or pictures. Sometimes they appear in Gallery/Audio Player immediatly, sometime after a couple of minutes, sometimes i have to restart MediaStorage and sometimes only a reboot does the shit. 

I looked trough the issues and found this: #251 
It was closed due to this commit: 849a8295ab7306f5a43c41a13179d7ffa407671c
Seems to me, syncthing-android should be enable to fire a rescan after syncing. 

Or is it just the API and somebody has to built something?

### Version Information

    App Version: 0.9.9
    Syncthing Version: v0.14.29 "Dysprosium Dragonfly" (go1.8.3 linux-amd64)
    Android Version: Android 7.1.2 / lineage-14.1-20170531-nightly-jfltexx

**Comment by Nutomic** [comment]
Yes its implemented, but I've also had some problems with it lately. I guess there could be some kind of bug.

**Comment by KopfKrieg** [comment]
Same here on Android 7.1.2 (LineageOS). Interestingly, the media rescan never worked for me as far as I remember. I always needed to restart the service myself or reboot the device to trigger a rescan.

**Comment by Cruplezone** [comment]
I too am wondering if this is being looked into after such a long while. I use st mainly for syncing music to my phone and right now after a sync completes none of my music apps can see the songs until I run a media rescan with another app I got from the Play store just for this purpose. It would be nice if st could just do it right after syncing completes

**Comment by Nutomic** [comment]
Should be fixed now. Please open a new issue with logs if you still get this issue with the next release.
