### ISSUE TITLE
Using Go on Mobile: discussion

### ISSUE THREAD

**Issue by LeonardoGentile** [syncthing/syncthing-android#909]
I am aware of the various problems, issues and discussion about the limitation of using an sdcard with Syncthing. The problem was moved upward to the Go team: https://github.com/golang/go/issues/10588.

That issue was around without any answer or progress for 2 years.  
After politely asking the team for an honest answer on what was going on a member of the team [replied](https://github.com/golang/go/issues/10588#issuecomment-308885977): 
> Unfortunately there's no one on the Go team actively supporting x/mobile at the moment.

I think this answer might have serious implication for this project and others relying on the goLang on mobile. The problem of the sdcard is already unsolvable, and there is no hope no one will fix it in incoming years.

But this might only be one of the problems: "no one on the Go team actively supporting x/mobile at the moment." means that as soon new features or restrictions comes from the mobile world no one will take care of them on the Go Team. 

Talking about problem anticipation I'd like to ask this to the team members:
Do you think is still safe to continuing support Go for the mobile environments?   

It is probably convenient because you write your code once and then with wrappers you can export it for mobiles or other platforms. But is it safe? No one is supporting the mobile platform..

Don't you think it is a good time to have a discussion and look for alternatives before a downfall of other problems might  arise?

**Comment by AudriusButkevicius** [comment]
Discussions should live on the forum if anything, but to be honest I feel this is a bit pointless as I don't see anyone volunteering to rewrite syncthing in a different language.

**Comment by AudriusButkevicius** [comment]
Also, we are not using go/mobile at all, the syncthing you run on your phone is the exact syncthing you run on your desktop, so there is nothing different about it.

**Comment by LeonardoGentile** [comment]
@AudriusButkevicius sorry for not using the forum, I tough this was more appropriate here because more technical probably, fell free to close this if you fell and I'll re-post to the forum.

Have you asked anyone to volunteering to rewrite it into another language already?

As for the second comment if that is exactly the same how comes https://github.com/golang/go/issues/10588 was opened in the first place? Am I missing something?

**Comment by AudriusButkevicius** [comment]
I am closing this, you can continue on the forum is you wish.
