### ISSUE TITLE
UTF-8 Autonormalization not always turned on

### ISSUE THREAD

**Issue by mariopaumann** [syncthing/syncthing-android#915]
just had a problem with „is not in the correct UTF8 normalization format“ message.

i found that some folder didn’t have „[autonormalize](https://docs.syncthing.net/advanced/folder-autonormalize.html)“ option set, although it’s documented that’s default is enabled. after setting it manually, the problem is solved.

i think it’s a problem with the Android App then.

Auto Normalize Setting can be found in the Syncthing Web Interface, upper right Config, Extended Settings, and there in every Foldersetting

![screenshot_20170703-092832](https://user-images.githubusercontent.com/10651646/27782515-25b40726-5fd3-11e7-9523-c4d6435827ea.png)

**Comment by Nutomic** [comment]
Thanks for finding this! We didnt set the right default value, so it was creating the folder with the wrong settings.
