### ISSUE TITLE
[Minor UI Suggestion] In-App On/Off Switch

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#917]
_**Having an** in-app toggle_ to flip Syncthing on or off could be very useful for the user to have, in case he or she needs to quickly allocate resources to other programs (and doesn't have Quick Settings Toggles [if that enhancement idea goes through] and/or experienced knowledge in the program).
This switch should be located on the left slide-out app panel within the ST GUI, ideally matching the same place as the "Restart Syncthing" icon, just above or below.

_This is simply a suggestion for a minor UI tweak, nothing fancy!_

_**Thank you for being such an awesome, honest development team! 👍 :-)**_
~ _Jeb_

**Comment by Nutomic** [comment]
Very similar to #886 and #914.

**Comment by jebeld17** [comment]
It's not exactly the same thing though, and not everyone has the luxury of Quick Settings toggles, which is why I submitted this separate. 😊

**Comment by Nutomic** [comment]
Yes I know, just added a comment so they can be found easily :)

**Comment by allejok96** [comment]
I would love this feature too. Right now I have it set to sync when charged. It would be nice to just have a "start now" or button on the dialog that says that syncthing is not running, instead of having to go into settings, and turn off Always on, and then set it back when I'm done syncing.

... or the quick setting toggle, whatever 😃

**Comment by lheckemann** [comment]
Also related to #254

**Comment by jebeld17** [comment]
Please add :)

**Comment by AudriusButkevicius** [comment]
Stop posting pointless comments just to bring attention, as that will encourage to lock the issue from new comments.

**Comment by Catfriend1** [comment]
Let's meet on one alternative #886 and #914 should be implemented in the future with a proper strategy as it's not easy "syncing by button clicking". Just running syncthing and stopping it some time later does not ensure a full sync (regarding you would be a normal user without extra skills manually looking at the webgui each time). To just exit syncthing and free system resources you can go into the left-side menu and hit "Exit app". If the option is unavailable, run condition "always run in background" has to be toggled off beforehand.
