### ISSUE TITLE
"Store in Syncthing" crashes when Syncthing not running/(not syncing?)

### ISSUE THREAD

**Issue by Dpunkt** [syncthing/syncthing-android#927]
I had Setup Syncthing to sync only while connected to Power and my Wifi. (In "Laufkonditionen"/Running Conditions.

On the go i tried to add some Pictures to Syncthing to have them synced later.
I used the Gallery, pressed Share and selected "Speichern in Syncthing"/Save to Syncthing.
In the following Window i was unable to select my Syncthing Folder. (No list popup, empty field)
When i pressed OK (Why can i press ok without selection anyway?) Syncthing Crashed and all the effort i spend in selecting my Pictures was wasted.

To Reproduced the Issue i tried again with Syncthing running: Everything works smoothly, the Folder-Field is prefilled with my only Syncthingfolder.
After Disconnecting Power (see sync/run conditions) The Problem appeared again.

Devices: Moto G (gen 2), Android 6.0
Telekom Puls Tablet (Alcatel OneTouch) Android 5.0.1

Syncthing Version 0.14.32
Syncthing Android Version 0.9.12 from PlayStore.

**Comment by Nutomic** [comment]
Fixed in 6dedc3182e9e6658243867dc2853d1011b8d7248
