### ISSUE TITLE
Unclear Wording for Run Conditions/Sync only

### ISSUE THREAD

**Issue by Dpunkt** [syncthing/syncthing-android#928]
Unclear Behavior of "Run Conditions" with set "Sync only when ..."-Conditions.

Does Syncthing now **run** or **sync** when this conditions are met?

From the Behavior (Error Messages, No Settings) i think it does not **run**.
I think the "sync_only_*" Messages should be described as "Run only if..." instead "Sync only if..." to avoid confusion.

**Comment by Nutomic** [comment]
It's actually both. For example if you check "sync only on wifi", Syncthing will be shut down if there is no wifi connection. When wifi is connected, Syncthing is started and will start synchronizing.

To be honest I'm not sure what the best wording is there. Any opinions from other people?

**Comment by lheckemann** [comment]
I think it would be good to have running actually be a separate concept from syncing. This would, as far as I understand, solve issues like #927 which prevent folder and device data from being accessible when syncing isn't active. I think this could be implemented by just [pausing all devices](https://docs.syncthing.net/rest/system-pause-post.html) but continuing to run syncthing when the power/network conditions aren't met?

**Comment by Nutomic** [comment]
That is possible, but Syncthing would still drain battery, so it might not be a good solution for everyone.

**Comment by lheckemann** [comment]
I'm not sure it would. If it's paused and the GUI isn't open, it should be doing nothing at all — just be waiting on the kernel to return control to it when it has something to do e.g. a new TCP connection or something, using `select()` or similar. This doesn't require waking the CPU up or anything, so I don't see why it would consume power.

**Comment by lheckemann** [comment]
Update: it appears that this is very much not the case and syncthing is fairly busy even when idle. Surely this isn't necessary though?

**Comment by Nutomic** [comment]
I don't know about that really. You should ask in the [syncthing repo](https://github.com/syncthing/syncthing), because it doesn't really belong here.

**Comment by Nutomic** [comment]
Closing this as it doesnt really seem to be a problem.

**Comment by lheckemann** [comment]
I do consider it to be a problem. It should be "run only…" because (at least in its current form) it's misleading. I also think running should not imply syncing — I want to be able to look at the state of my folders even if I'm not syncing because I'm on mobile data.

**Comment by Nutomic** [comment]
Hmm alright will change it.

Using pause instead of stopping isnt related to this issue though, I'm pretty sure there's an issue for that already.
