### ISSUE TITLE
syncthing not quoting filenames - errors on ":,?"

### ISSUE THREAD

**Issue by neurotensin** [syncthing/syncthing-android#932]
### Version Information

    App Version: 0.x.y
    Syncthing Version: v0.14.30
    Android Version: Android 0.9.11 (Nexus 6P)

While transferring some files, there were "Invalid argument" errors for files containing ":" and "?". 

This suggests the quoting is not correct...

Both devices are same syncthing versions. 

Source was Nexus 6P, destination was Samsung Tab S3.

**Comment by AudriusButkevicius** [comment]
Some filesystems won't support these characters. You'll have to rename the files.

**Comment by neurotensin** [comment]
I understand some FS would not, but  wouldn't quoting work on the local context to reproduce the source however it is interpreted? 
e.g Linux filenames to FAT 8.3 
In this case it is Android->Android.

**Comment by AudriusButkevicius** [comment]
It would but it would be considered data loss, as the name would change.

**Comment by neurotensin** [comment]
Agreed. But perhaps we should not permit the characters to trigger "invalid arguments", as this feels a bit like sql injection!!! 
Since the destination sees these errs, perhaps a quoted comparison at both ends would be safer? 

"These filenames  will differ between <source> <dest>".  The user would then have a clear list, that could be processed via sed  ;-)

The problem was obvious immediately (and files were renamed!), but the average user might be confused.

**Comment by wweich** [comment]
If the files / folders are renames on one of the devices automatically, they will be synced with those names to the other devices.

But as Syncthing doesn't support external sd cards, and internal storage and sd cards formatted for internal usage are ext4, I don't know where this erre can come from.

**Comment by neurotensin** [comment]
Yes, that is true. This is Nexus 6P internal(no sdcard!!) to Samsung Tab S3 external SD(I'll bet its EXFAT).
since the source machine was linuxfs, probably best I sanitise my files.

Would be nice to have a warning though as it threw unhandled errors. 

I'll generate a nicely corrupting file name for sync  and post the errors here, so that the experts can determine best course of action.

**Comment by neurotensin** [comment]
OK here's what I did:
1) mkdir "Th\!s_isf?_ul*o:ho@i#bulch'_\"s"
2) transferred to my Nexus 6P using KDEconnect.
3) place in folder to sync to samsung tab s3, Extcard
This is the log:

> [ZEL62] 17:51:43 INFO: Puller (folder "4ifvv-wvtok", dir "Th\\!s_isf?_ul*o:ho@i#bulch'_\"s"): mkdir /storage/206D-026D/Android/data/com.nutomic.syncthingandroid/files/External/Th\!s_isf?_ul*o:ho@i#bulch'_"s: invalid argument
[ZEL62] 17:51:43 INFO: Puller (folder "4ifvv-wvtok", dir "Th\\!s_isf?_ul*o:ho@i#bulch'_\"s"): mkdir /storage/206D-026D/Android/data/com.nutomic.syncthingandroid/files/External/Th\!s_isf?_ul*o:ho@i#bulch'_"s: invalid argument
[ZEL62] 17:51:43 INFO: Puller (folder "4ifvv-wvtok", dir "Th\\!s_isf?_ul*o:ho@i#bulch'_\"s"): mkdir /storage/206D-026D/Android/data/com.nutomic.syncthingandroid/files/External/Th\!s_isf?_ul*o:ho@i#bulch'_"s: invalid argument
[ZEL62] 17:51:43 INFO: Folder "4ifvv-wvtok" isn't making progress. Pausing puller for 1m0s.

>

**Comment by AudriusButkevicius** [comment]
Anyways, whats the purpose of this discussion?
Yes, you cannot sync files that are not supported by the underlying filesystem. Why is this a surprise and worth talking about?

There is a ticket on syncthing repo about potentially supporting some sort of escaping replacement, but it's much harder than you think. As in this case you might use some custom filesystem that doesn't allow filenames with letter A in it, and there isn't an awful lot we could do to work out what is allowed and what is not.

**Comment by neurotensin** [comment]
Well the fact that "invalid argument" appears, means the error is not handled. Bad things happen with unknown input.
I'm sure you are correct about the underlying filesystems, but this looks as if the "mkdir" is failing.

Any chance you could try/catch the exception and get more details? As I mentioned, I think renaming is fine. But as Android has this bizarre FS fragmentation, a slightly cleaner way would be to report this to the user, so they can fix it (by renaming).

This discussion ([https://superuser.com/questions/178025/linux-copy-to-fat32-filesystem-invalid-argument/407852](url) is linux->fat. Seems only *?: are toxic. So when syncing , each client should know the underlying invalid chars and flag as "Name not valid on host->". 
Renaming is definitely the user's job, but it would be nice to give them feedback to that end...

**Comment by AudriusButkevicius** [comment]
In the web UI, you get "Failed items" modal which lists the files we failed to sync, so we already report it to the user. 

That is not immediately visible in the Android app, as it doesn't expose that, but there already exists https://github.com/syncthing/syncthing-android/issues/747 regarding this.

**Comment by neurotensin** [comment]
Well the fact that "invalid argument" appears, means the error is not handled. Bad things happen with unknown input.
I'm sure you are correct about the underlying filesystems, but this looks as if the "mkdir" is failing.

Any chance you could try/catch the exception and get more details? As I mentioned, I think renaming is fine. But as Android has this bizarre FS fragmentation, a slightly cleaner way would be to report this to the user, so they can fix it (by renaming).

This discussion ([https://superuser.com/questions/178025/linux-copy-to-fat32-filesystem-invalid-argument/407852](url) is linux->fat. Seems only *?: are toxic. So when syncing , each client should know the underlying invalid chars and flag as "Name not valid on host->". 
Renaming is definitely the user's job, but it would be nice to give them feedback to that end...
Thanks, I'll leave it there.

**Comment by AudriusButkevicius** [comment]
The error is handled, as in - sync terminates, and we print an error which is then shown to the user in the web ui.
We are not crashing or something like that, so I am not sure why you are saying it's unhandled or unknown input.
Same way if we try to create a directory where we can't due to permissions we will print permission errors, same way "not handling the error".
The input is known, it just happens not to be valid for the platform in question, and the kernel does a fine job to tell us that.
