### ISSUE TITLE
Syncthing-Android suddenly not pairing with other devices

### ISSUE THREAD

**Issue by lavindir** [syncthing/syncthing-android#934]
Earlier I had Syncthing-Android paired and syncing with a Windows desktop and Windows laptop just fine; now, however, the devices (desktop and laptop) never change their state from "Disconnected", even after reinstalling Syncthing-Android and attempting to re-pair with my desktop. The desktop and laptop remain able to sync with each other, it's just android that is suddenly in the dark.

Here is a log that might help 
<pre>
[WA7UU] 23:45:22 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (2.999905 failures of 2.000000), restarting: false, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[WA7UU] 23:45:22 INFO: Device {device_id_windows_desktop} is "{device_name_windows_desktop}" at [dynamic]
[WA7UU] 23:45:22 INFO: Device {device_id_android} is "{device_name_android}" at [dynamic]
[WA7UU] 23:45:22 INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
[WA7UU] 23:45:22 INFO: GUI and API listening on 127.0.0.1:8384
[WA7UU] 23:45:22 INFO: Access the GUI via the following URL: https://127.0.0.1:8384/
[WA7UU] 23:46:00 INFO: UPnP parse: Get http://10.0.0.1:49152/IGDdevicedesc_brlan0.xml: dial tcp 10.0.0.1:49152: i/o timeout
[WA7UU] 23:46:00 INFO: Detected 0 NAT devices
[WA7UU] 23:50:55 INFO: Exiting
[WA7UU] 23:50:56 INFO: syncthing v0.14.30 "Dysprosium Dragonfly" (go1.8 linux-arm64) vagrant@jessie64 2017-05-31 18:14:04 UTC [noupgrade]
[WA7UU] 23:50:56 INFO: My ID: {device_id_android}
[WA7UU] 23:50:57 INFO: Single thread SHA256 performance is 878 MB/s using minio/sha256-simd (67 MB/s using crypto/sha256).
[WA7UU] 23:50:58 INFO: Hashing performance with weak hash is 439.18 MB/s
[WA7UU] 23:50:58 INFO: Hashing performance without weak hash is 734.17 MB/s
[WA7UU] 23:50:58 INFO: Weak hash disabled, as it has an unacceptable performance impact.
[WA7UU] 23:50:58 INFO: Ready to synchronize "{folder_name_android}" ({folder_id}) (readwrite)
[WA7UU] 23:50:58 INFO: Send rate is unlimited, receive rate is unlimited
[WA7UU] 23:50:58 INFO: Rate limits do not apply to LAN connections
[WA7UU] 23:50:58 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[WA7UU] 23:50:58 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[WA7UU] 23:50:58 INFO: Using discovery server https://discovery-v4-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[WA7UU] 23:50:58 INFO: TCP listener ([::]:22000) starting
[WA7UU] 23:50:58 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[WA7UU] 23:50:58 INFO: Completed initial scan (rw) of "{folder_name_android}" ({folder_id})
Using DNS servers: [[2001:558:feed::2]:53 [2001:558:feed::1]:53]
[WA7UU] 23:50:58 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.000000 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[WA7UU] 23:50:58 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.999968 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[WA7UU] 23:50:58 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[WA7UU] 23:50:58 INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[WA7UU] 23:50:58 INFO: Entering the backoff state.
[WA7UU] 23:50:58 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (2.999929 failures of 2.000000), restarting: false, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[WA7UU] 23:50:58 INFO: Device {device_id_windows_desktop} is "{device_name_windows_desktop}" at [dynamic]
[WA7UU] 23:50:58 INFO: Device {device_id_android} is "{device_name_android}" at [dynamic]
[WA7UU] 23:50:58 INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
[WA7UU] 23:50:58 INFO: GUI and API listening on 127.0.0.1:8384
[WA7UU] 23:50:58 INFO: Access the GUI via the following URL: https://127.0.0.1:8384/
[WA7UU] 23:51:09 INFO: Detected 0 NAT devices
</pre>

While android shows something like this
<pre>
[WA7UU] 23:50:58 INFO: Completed initial scan (rw) of "{folder_name_android}" ({folder_id})
Using DNS servers: [[2001:558:feed::2]:53 [2001:558:feed::1]:53]
[WA7UU] 23:50:58 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.000000 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[WA7UU] 23:50:58 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (1.999968 failures of 2.000000), restarting: true, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[WA7UU] 23:50:58 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[WA7UU] 23:50:58 INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[WA7UU] 23:50:58 INFO: Entering the backoff state.
[WA7UU] 23:50:58 INFO: c.S.listenerSupervisor: Failed service 'dynamic+https://relays.syncthing.net/endpoint' (2.999929 failures of 2.000000), restarting: false, error: "{dynamic+https://relays.syncthing.net/endpoint dynamic+https://relays.syncthing.net/endpoint} returned unexpectedly", stacktrace: [unknown stack trace]
[WA7UU] 23:50:58 INFO: Device {device_id_windows_desktop} is "{device_name_windows_desktop}" at [dynamic]
[WA7UU] 23:50:58 INFO: Device {device_id_android} is "{device_name_android}" at [dynamic]
[WA7UU] 23:50:58 INFO: No automatic upgrades; STNOUPGRADE environment variable defined.
[WA7UU] 23:50:58 INFO: GUI and API listening on 127.0.0.1:8384
[WA7UU] 23:50:58 INFO: Access the GUI via the following URL: https://127.0.0.1:8384/
[WA7UU] 23:51:09 INFO: Detected 0 NAT devices
</pre>
my desktop shows something like this 
<pre>
[AKHSL] 20:26:48 INFO: Completed initial scan (rw) of "{folder_name_windows_desktop}" ({folder_id})
[AKHSL] 20:26:48 INFO: Device WA7UUGC is "{device_name_android}" at [dynamic]
[AKHSL] 20:26:48 INFO: Device AKHSLHN is "{device_name_windows_desktop}" at [dynamic]
[AKHSL] 20:26:48 INFO: GUI and API listening on 127.0.0.1:8384
[AKHSL] 20:26:48 INFO: Access the GUI via the following URL: http://localhost:8384/
[AKHSL] 20:26:58 INFO: Joined relay relay://64.137.230.20:22067
[AKHSL] 20:26:59 INFO: Detected 0 NAT devices
</pre>

It seems as if Syncthing-Android is unable to connect to a relay server? I'm not really sure what's going on. What is the problem? How can I get Syncthing-Android to work again?

### Version Information

    App Version: 0.9.11
    Syncthing Version: v0.14.30
    Android Version: Android 7.1.1 / Omnirom 7.1.1

**Comment by Nutomic** [comment]
Sounds like a problem with Syncthing, not the Android app. You will probably get more help on the forum.

**Comment by lavindir** [comment]
alright I'll try there
