### ISSUE TITLE
Syncthing won't sync if "Sync only on wifi" option set

### ISSUE THREAD

**Issue by DrStrangepork** [syncthing/syncthing-android#936]
If the option "Sync only on wifi" option is checked, Syncthing stops running and I get the window "Syncthing is disabled" even when my phone is connected to my WiFi. But if I uncheck that option, Syncthing will run and sync over my WiFi. I have not tested to see if it also syncs over my cellular data connection.

### Version Information

    App Version: 0.9.12
    Syncthing Version: v0.14.32
    Android Version: Android 7.0, Moto Z Droid

**Comment by raffomania** [comment]
I get the same behavior. It also syncs over my cellular connection.
I had to disable "run in background" as a workaround :(
```
App Version: 0.9.12
Syncthing Version: v0.14.32
Android Version: Android 7.1.2, Nexus 5X
```

**Comment by capi** [comment]
Is your WiFi maybe set as "metered"? Because than it is treated like a mobile network.

**Comment by terba** [comment]
Same problem here, sometimes it works but sometimes not. I don't have any metered wifi networks. My settings are: Allways run in the background, Only when charging, Only on wifi, Only on selected wifi networks and Respect Android battery optimizations (I translated those back from my native language). If I uncheck Only on wifi it works well.

**Comment by Stebalien** [comment]
Same issue here (although my only run condition is "on wifi"). Note, my version of Android doesn't *have* metered wifi networks (as far as I can tell). Could that be the issue?

**Comment by Nutomic** [comment]
@Stebalien That shouldnt make any difference. Can you check if the latest beta Version fixes the Problem?

**Comment by Stebalien** [comment]
@Nutomic The beta version appears to work.
