### ISSUE TITLE
Add run condition: Avoid metered networks

### ISSUE THREAD

**Issue by HaleTom** [syncthing/syncthing-android#937]
To save money and avoid syncthing using a mobile phone tethered network, (what Android calls a "metered" network), can the following `Run Condition` be added:

* `Avoid metered networks`

**Comment by Nutomic** [comment]
This is already covered by the "run only on wifi" condition. If that condition is checked, Syncthing will be disabled on metered networks (on Android 4.1+). Maybe we should put that info in the description?

**Comment by HaleTom** [comment]
I'd suggest put the control in the hands of the user: If I am running Syncthing on my tablet, tethered to my phone, I am on wifi but _may or may not_ wish syncing to occur on this tethered network, separate from other un-tethered networks.

**Comment by carstenhag** [comment]
@Nutomic To enable "run only in wifi" I have to enable "always execute in background", which should not be a dependency in my opinion.

I should be able to only let syncthing sync via wifi without the background thing.

**Comment by ndnihil** [comment]
I agree that always run in background should be separate from run on wifi. I'd even go as far as to say that each sync'd folder should have it's own criteria where you can choose what content syncs based on what connections are available. My use case aims for a scenario like:

Syncthing Servers:
  * server-home (internal only, full sync/backup of devices)
  * server-work (internal only, sync of work folder on phone/tablet/laptop)
  * server-pub ('Share via Syncthing' dir for placing content on public web repo)

Devices:
* myphone:
    * /sdext - HomeSSID/HomeVPN - server-home
    * /sdext/work - WorkSSID/WorkVPN - server-work
    * /sdext/pub - AnySSID/LTE/4G/3G - server-pub via 'Share via Syncthing'

* mytablet:
    * /sdext - HomeSSID/HomeVPN - server-home
    * /sdext/work - WorkSSID/WorkVPN - server-work
    * /sdext/pub - AnySSID/LTE/4G/3G - server-pub via 'Share via Syncthing'

* mylaptop:
    * ~/files - HomeSSID/HomeVPN - server-home
    * ~/work - WorkSSID/WorkVPN - server-work

* herphone:
    * /sdext - HomeSSID/HomeVPN - server-home
    * /sdext/pub - AnySSID/LTE/4G/3G - server-pub via 'Share via Syncthing'

* hertablet:
    * /sdext - HomeSSID/HomeVPN - server-home
    * /sdext/pub - AnySSID/LTE/4G/3G - server-pub via 'Share via Syncthing'

* herlaptop:
    * ~/files - HomeSSID/HomeVPN - server-home

**Comment by Catfriend1** [comment]
@carstenhag  Thats a good point thus requiring to rethink the run conditions. We had another ticket those days where sync on wifi hotspot was discussed - result "too misleading as the user can fall into accidentially syncing over mobile network when thinking its wifi". But I agree it would be positive if the app cares about state changes and stops before attempting to sync in an unwise condition. The problem here is, we need a strategy first when syncthing can use which network and that has to be pushed (or told to the user to get it) into the syncthing core config.

**Comment by Catfriend1** [comment]
An interesting explanation I found about the isActiveNetworkMetered() function of ConnectivityManager:
https://stackoverflow.com/questions/23877476/android-why-connectivitymanager-isactivenetworkmetered-always-returning-true

**Comment by Catfriend1** [comment]
I'm preparing a solution in PR #1189.

**Comment by Catfriend1** [comment]
https://github.com/syncthing/syncthing-android/pull/1189/commits/947ff691f266af4ea6d4e0f953b3720a46e3695f
