### ISSUE TITLE
Adding new a new folder and selecting device interrupts existing sync with device.

### ISSUE THREAD

**Issue by danbo** [syncthing/syncthing-android#940]
I noticed that if there is a sync in progress between my phone and ubuntu instance, adding a new folder on the phone to the same devices stops any existing sync already happening to that device and ubuntu's GUI shows "Out of Sync" for few moments before continuing the sync again.

Phone version: 0.9.12 / st version: 0.14.32
Ubuntu version: 0.14.36

**Comment by AudriusButkevicius** [comment]
This is expected. Adding a new folder has to break connections to reestablish the cluster state.
