### ISSUE TITLE
Feature request: sync queue

### ISSUE THREAD

**Issue by danbo** [syncthing/syncthing-android#941]
I added 2 folders to sync on my phone, both with lots of data, to the same target and both started syncing at the same time.

It would be good to have one folder complete syncing before another starting.

Phone version: 0.9.12 / st version: 0.14.32
Ubuntu version: 0.14.36

**Comment by AudriusButkevicius** [comment]
Pause the folder you don't want to be synced.

**Comment by Nutomic** [comment]
This isn't supported in Syncthing itself, so it's not something we will add on Android.
