### ISSUE TITLE
Exiting only ever works the 2nd time

### ISSUE THREAD

**Issue by mlda065** [syncthing/syncthing-android#943]
# Steps to reproduce

* start syncthing
* look in notification drawer
* click on 'syncthing is running'
* press hamburger button to see syncthing menu
* press "Exit"

# Expected behaviour:

* Notification saying 'syncthing is running' dissappears
* User taken back to Android desktop, or to previous app

# Observed behaviour

* Notification saying 'syncthing is running' remains
* User taken back to Syncthing main landing page
* Loading animation appears, so user can't do anything for several frustrating seconds
* When the steps to exit are repeated it works

Here's a screen recording to show what I see. I couldn't figure out how to convert this mp4 file to a gif small enough to post here. So I'm posting a zip instead. (Github allows zips, but not mp4)

[syncthing_screenrecord_broken.mp4.zip](https://github.com/syncthing/syncthing-android/files/1289593/syncthing_screenrecord_broken.mp4.zip)

# Comment

* I think the exit button only fails to exit when the user clicks on the notification to open the app. If you open the app by clicking on the icon on the desktop, it works as expected.

# Details

### Version Information

    App Version: 0.9.13
    Syncthing Version: v0.14.7
    Android Version: Android 7.0

**Comment by Nutomic** [comment]
You're right, it looks like the main screen is opened twice in this case.
