### ISSUE TITLE
SyncThing refuses to sync to sdcard even with availible permissions.

### ISSUE THREAD

**Issue by ViperZer0** [syncthing/syncthing-android#946]
I am running Android 4.4.4 on CyanogenMod CM11. My  phone is rooted and has the infamous sdcard write permissions fixed. The  problem, I believe, comes from the app. I might be wrong, but both  Resilio Sync and SyncThing both seem to just sort of assume that write  permission to the SD card is restricted, even though it isn't. At no  point am I given an option to sync to the SD card, the app won't even  let me try it. I think this fault lies with the app, though again, I  could be wrong. I would very much appreciate seeing an option to at  least try to sync to SD card.

EDIT: Found a workaround.

I had previously used the web GUI to add /storage/sdcard1 as my sync destination, but it didn't seem to work. However, I have just restarted syncthing, and voila, there's my folder! With that in mind, these are the steps I took to achieving this, for anyone else who's struggling with this:

Step 1: Ensure that your phone has had write permissions to the SD card reactivated. I did this simply by running CyanogenMod, but there are apps for rooted phones that do the same thing.

Step 2: In syncthing, open up the web GUI. You can manually enter the sync destination as /storage/sdcard1. 

Step 3: Restart syncthing. In the regular UI the folder should appear. 

However, I still think that being able to enter folder destination manually and verifying SD card permissions should be an added feature

**Comment by Nutomic** [comment]
There is a setting in the app to show all folders in the file picker (under behaviour iirc).
