### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing-android#947]
Hi
Some strings were left behind on upgrade to 0.9.13 (*).
It would be nice if users & TX teams see the translation work effect ASAP. Jakob did something on the core so that this is automated on each release.
(*) : e.g. strings for French 98, 99, 

Nice job guys... go on !

**Comment by Nutomic** [comment]
You're right. Not sure what went wrong there. I will make sure translations are imported correctly for the next release. And yes, translation import is already automated.
