### ISSUE TITLE
Changing GUI language doesn't take effect

### ISSUE THREAD

**Issue by yukinakato** [syncthing/syncthing-android#952]
## What happened
Selecting any language in the list doesn't change the current (system default) language.

![z](https://user-images.githubusercontent.com/22708232/30632565-7e3102e4-9e23-11e7-8d2a-0b696a4df2ca.gif)

## What you expected to happen instead
GUI language changes to the selected one accordingly.

## Any steps to reproduce the problem
Go to Config -> Behaviour -> Language and select any language.

## Version information
* App version: 0.9.13
* Syncthing version: v0.14.37
* Android version: EMUI 5.0 based on Android 7.0 non-rooted
* Device and build no.: Huawei honor 8 (FRD-L02C635B383)

## Logs
`adb logcat *:W` emits the messages below when I repeat this operation.

```
W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@ae13394 attribute=null, token = android.os.BinderProxy@2365146
W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@9624f83 attribute=null, token = android.os.BinderProxy@2365146
W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@ee1937e attribute=null, token = android.os.BinderProxy@2365146
W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@957f7f5 attribute=null, token = android.os.BinderProxy@2365146
W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@eef6418 attribute=null, token = android.os.BinderProxy@2365146
W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@37f8cd7 attribute=null, token = android.os.BinderProxy@2365146
```

## Related issue
Feature: Allow to select GUI language explicitly #742

**Comment by Nutomic** [comment]
Did you try if restarting the phone applies the correct language?

**Comment by yukinakato** [comment]
Ah, forgot to mention that restarting the app or even rebooting the phone didn't help.

**Comment by yukinakato** [comment]
I overlooked some important logs. By `adb logcat Languages:* *:S`:

```
D Languages: Languages.setLanguage() ignored on >= android-24
D Languages: Languages.forceChangeLanguage() ignored on >= android-24
D Languages: Languages.setLanguage() ignored on >= android-24
D Languages: Languages.forceChangeLanguage() ignored on >= android-24
D Languages: Languages.setLanguage() ignored on >= android-24
D Languages: Languages.forceChangeLanguage() ignored on >= android-24
D Languages: Languages.setLanguage() ignored on >= android-24
D Languages: Languages.forceChangeLanguage() ignored on >= android-24
...
```

Maybe related:

https://github.com/syncthing/syncthing-android/blob/32be8ba207f905eaeab7d7524f4c153961d39571/src/main/java/com/nutomic/syncthingandroid/util/Languages.java#L71-L75

**Comment by Nutomic** [comment]
Ah I found it: https://gitlab.com/eighthave/fdroidclient/commit/add570ab4b02ccb753d87914e9ea5795a3f91f52

So the reason is that Android 7+ has a native functionality to set multiple languages, which is better than this hack. I will do it like F-Droid and hide the language setting in this case.

**Comment by yukinakato** [comment]
Thanks for that info. Actually I can no longer change the GUI language of F-Droid 0.104 on Nougat. That is a bit annoying because some words, such as _staggered_ in Syncthing, is difficult to translate into short words (because of the limitation of spaces on the phone screen) and it's easier to understand them in English. Is there any chance for Syncthing-Android to have the ability to change the GUI language? Meanwhile I'll continue to improve the translation on transifex :blush:

**Comment by Nutomic** [comment]
I think the F-Droid team has a good reason to disable this functionality on 7+, so I will follow them.

**Comment by yukinakato** [comment]
Ok, got it :blush:
