### ISSUE TITLE
Environment variables are ignored when running as root

### ISSUE THREAD

**Issue by flipreverse** [syncthing/syncthing-android#953]
Hi folks!

If Syncthing runs as root, the su binary does not pass the enviroment variables to the Syncthing binary.
Therefore, default settings, e.g., STNORESTART=1, and custom settings like STTRACE=all are skipped. This is the default behavior for su. I've observed a similar behavior of sudo on Ubuntu.  
To overcome that issue, su provides the option '--preserve-environment'. Adding this to the ProcessBuilder in SyncthingRunnable.java should fix this problem.
However, I cannot test that fix, because the su binary on my Fairphone 2 goes crazy. It deletes custom variables and resets some of them, e.g., HOME. Even with '--preserve-environment' the custom variables are deleted.
I'm currently working on a patch that suits my device. I do not know if it's suitable as a generic solution to that problem. I'll provide my patch as soon as it is completed -- more or less. :)

Cheers,
Alex

**Comment by Nutomic** [comment]
I can't reproduce this on my device (Nexus 5, Android 6). Maybe you just have a wonky su binary?

**Comment by flipreverse** [comment]
Can you set STTRACE=all and you get a very verbose Syncthing without using --preserve-environment?

**Comment by Nutomic** [comment]
Oh actually you're right, I didn't check properly. I tried by changing SyncthingRunnable:126 to `new ProcessBuilder("su", "-c", "printenv")`, which correctly prints some env vars, but not any of those we set. `--preserve-environment` also doesn't help for me.
