### ISSUE TITLE
Syncthing not starting with read-only Folders

### ISSUE THREAD

**Issue by craycrayuk** [syncthing/syncthing-android#956]
Using version 0.9.14 that was updated in the Google play store, Syncthing no longer successfully loads on a Samsung Galaxy S5. It displays the "Loading" screen, but then never finishes. 

I've tried clearing the cache, but it is still the same. I've also tried to open with out any networks without success. 

My phone is the latest Android version Samsung decided to update it to which is 6.0.1.

**Comment by Nutomic** [comment]
Are you using the option to start directly into web gui? Otherwise, post logs please.

**Comment by joseluis245** [comment]
I'm having the same problem here, with a Aquaris BQ E4.5 (Android 5.0). Worked like a charm until yesterday's update, now I can't go past the "loading" screen...

**Comment by craycrayuk** [comment]
I'm not loading directly into the web GUI. Looking at the log, there is this error:

20:26:00 FATAL: failed to upgrade folder marker: remove /storage/256D-971C/DCIM/Camera/.stfolder: permission denied

I renamed the .stfolder to .stfolder2 and reopened Syncthing. This time it loaded successfully but had an error about the folder marker missing. 

I closed it down again, renamed, stfolder2 and to stfolder and Syncthing successfully started. 

The folder it was having difficulty with is on an external SD card.

**Comment by Nutomic** [comment]
Ah Syncthing is probably trying to convert .stfolder from a file to a folder (and fails because the folder is not writable). But it shouldn't prevent Syncthing from starting.

Ping @calmh

**Comment by AudriusButkevicius** [comment]
Yeah, that would be my trophy of major fuckups.

**Comment by AudriusButkevicius** [comment]
We should make it best effort and handle conversions when we actually start using it.

**Comment by calmh** [comment]
Yeah that `Fatalln` should have been an `Infoln`.

**Comment by Nutomic** [comment]
The same problem would also appear on other platforms, if there is a folder where Syncthing can't write to.

**Comment by AudriusButkevicius** [comment]
Atleast the error is not as hidden as it is on android.

**Comment by calmh** [comment]
Also more unusual - the bug hasn’t been reported yet. Clearly we’ll fix it for the next release, I just meant if you wanted a quick fix for Android.

**Comment by Nutomic** [comment]
Tbh I don't think this is a very common setup on Android.

**Comment by Kugeleis** [comment]
Is there a workaround available?

**Comment by Nutomic** [comment]
You should be able to fix it by deleting the `.stfolder` file and creating a folder called `.stfolder`. After that, make Syncthing restart (eg by force killing the app or restarting your phone).

**Comment by AudriusButkevicius** [comment]
That won't work I think, you'd have to manually modify the config and bump the version to skip the migration.

**Comment by craycrayuk** [comment]
I renamed the .stfolder file to .stfolder2 and reopened Syncthing. This time it loaded successfully but had an error about the folder marker missing.

I closed it down again, renamed, stfolder2 back to stfolder and Syncthing successfully started.

**Comment by AudriusButkevicius** [comment]
yeah, that might work too I guess.

**Comment by distancesprinter** [comment]
Chiming in to say this affected me too, and also killed my battery for the past few days while it was broken.

**Comment by nyancow** [comment]
Also appear to be affected by this. Where can the Google Play Store version of the 0.9.13 APK be obtained?
