### ISSUE TITLE
Forever 'Loading...'

### ISSUE THREAD

**Issue by Ploppz** [syncthing/syncthing-android#957]
I just updated Syncthing for Android, 20th of September, and when I try to start it, it just says 'Loading...' indefinitely.

### Version Information

Syncthing Version: v0.14.38 (according to the description on the Google Play page)
OS Version: Android 5.0.2

**Comment by Nutomic** [comment]
Might be #956? Otherwise post logs please.

**Comment by nyancow** [comment]
Also appear to be affected by this. Where can the Google Play Store version of the 0.9.13 APK be obtained? I am on 0.9.14 and kind of in a "deadlock". Can't do anything, and I have no backup of the settings.
