### ISSUE TITLE
RC build released to the stable channel 

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing-android#961]
Syncthing-android v.0.9.15 that was released to the non-beta Play Store channel is based on ST v.0.14.39-RC (as per release notes as well).

RC branch contains stuff like mandatory statistics that will override users' preferences once upgraded. And of course it is not yet branded as stable. 
This should not be used in a stable channel for a global release.

(39-RC will advance to Stable in 2 days, so not clear what's the rush...)

### Version Information

    App Version: 0.9.15
    Syncthing Version: v0.14.39-RC1

**Comment by Nutomic** [comment]
I released the rc version on purpose, in order to get the fix for folder markers out (and there didn't seem to be a reason to wait any longer).

But good point about the statistics, I didn't think of that. I will release a new version with the stable Syncthing release once that is out.

**Comment by imsodin** [comment]
The F-Droid version is not yet out. I would try to prevent that publication as an easy measure to prevent the same problem for that share of users.

**Comment by AudriusButkevicius** [comment]
tbh, I'd pull the release as it is.

**Comment by Nutomic** [comment]
Okay I've deleted the tag so F-Droid won't pick it up. Pulling the release seems like overkill though.

**Comment by scienmind** [comment]
v.0.14.39 Stable is out: https://github.com/syncthing/syncthing/releases/latest 🎉

**Comment by Nutomic** [comment]
Release is out.
