### ISSUE TITLE
Folders contain an "Error" status, but Syncthing did not tell me.

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#965]
Folders on my device that are being synced contain an "Error" message in the status, but the program does not state why. Furthermore, I haven't been given any notifications from the program stating there's an error occurring.
[bugreport-N9F27M-2017-10-09-11-30-13.zip](https://github.com/syncthing/syncthing-android/files/1369038/bugreport-N9F27M-2017-10-09-11-30-13.zip)
![screenshot_20171009-112710](https://user-images.githubusercontent.com/9492083/31345885-2be1ca20-ace5-11e7-87e4-d9cd3a6df286.png)

**Comment by dromanov** [comment]
Same for me.

**Comment by jebeld17** [comment]
@dromanov , can you upload debugging information or your Syncthing log?

**Comment by dromanov** [comment]
Sure
```
--------- beginning of main
12-20 18:10:08.864 W/SyncthingNativeCode(14282): ionice: exec 14333: Permission denied
12-20 18:10:18.725 I/SyncthingNativeCode(14282): [VBLBO] INFO: kcp://0.0.0.0:22020 detected NAT type: Symmetric NAT
12-20 18:10:18.739 I/SyncthingNativeCode(14282): [VBLBO] INFO: New NAT port mapping: external TCP address 172.18.133.97:40032 to local address 0.0.0.0:22000.
12-20 18:10:18.744 I/SyncthingNativeCode(14282): [VBLBO] INFO: Detected 1 NAT device
12-20 18:10:31.216 I/SyncthingNativeCode(14282): [VBLBO] INFO: Established secure connection to AYFL4N2-****-HTYUHQQ at 192.168.0.102:55585-192.168.0.106:22000 (tcp-client) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
12-20 18:10:31.218 I/SyncthingNativeCode(14282): [VBLBO] INFO: Device AYFL4N2-****-HTYUHQQ client is "syncthing v0.14.41" named "jetpack"
12-20 18:10:31.494 I/SyncthingNativeCode(14282): [VBLBO] INFO: Joined relay relay://31.24.30.188:22067```

```
--------- beginning of main
12-20 18:10:10.159 I/FolderObserver(14282): Observer created for (folder v34z4-lzrch)
12-20 18:10:10.167 I/FolderObserver(14282): Observer created for (folder ejqr5-4exzq)
12-20 18:10:18.208 I/Timeline(14282): Timeline: Activity_launch_request time:108278617
12-20 18:10:18.265 I/DeviceStateHolder(14282): Stopped listening to network state changes
12-20 18:10:18.265 I/DeviceStateHolder(14282): Stopped listening to battery state changes
12-20 18:10:18.265 I/DeviceStateHolder(14282): Listening to power saving changes
12-20 18:10:18.266 I/DeviceStateHolder(14282): Stopped listening to network state changes
12-20 18:10:18.266 I/DeviceStateHolder(14282): Stopped listening to battery state changes
12-20 18:10:18.266 I/DeviceStateHolder(14282): Listening to power saving changes
12-20 18:10:18.267 I/DeviceStateHolder(14282): Stopped listening to network state changes
12-20 18:10:18.267 I/DeviceStateHolder(14282): Stopped listening to battery state changes
12-20 18:10:18.267 I/DeviceStateHolder(14282): Listening to power saving changes
12-20 18:10:18.268 I/DeviceStateHolder(14282): Stopped listening to network state changes
12-20 18:10:18.268 I/DeviceStateHolder(14282): Stopped listening to battery state changes
12-20 18:10:18.268 I/DeviceStateHolder(14282): Listening to power saving changes
12-20 18:10:18.293 I/DeviceStateHolder(14282): State updated, allowed network connection: false, charging: false, power saving: false
12-20 18:10:18.294 I/DeviceStateHolder(14282): State updated, allowed network connection: false, charging: false, power saving: false
12-20 18:10:18.295 I/DeviceStateHolder(14282): State updated, allowed network connection: false, charging: false, power saving: false
12-20 18:10:18.296 I/DeviceStateHolder(14282): State updated, allowed network connection: false, charging: false, power saving: false
12-20 18:10:18.725 I/SyncthingNativeCode(14282): [VBLBO] INFO: kcp://0.0.0.0:22020 detected NAT type: Symmetric NAT
12-20 18:10:18.739 I/SyncthingNativeCode(14282): [VBLBO] INFO: New NAT port mapping: external TCP address 172.18.133.97:40032 to local address 0.0.0.0:22000.
12-20 18:10:18.744 I/SyncthingNativeCode(14282): [VBLBO] INFO: Detected 1 NAT device
12-20 18:10:28.045 I/Timeline(14282): Timeline: Activity_launch_request time:108288453
12-20 18:10:31.216 I/SyncthingNativeCode(14282): [VBLBO] INFO: Established secure connection to AYFL4N2-****-HTYUHQQ at 192.168.0.102:55585-192.168.0.106:22000 (tcp-client) (TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305)
12-20 18:10:31.218 I/SyncthingNativeCode(14282): [VBLBO] INFO: Device AYFL4N2-****-HTYUHQQ client is "syncthing v0.14.41" named "****"
12-20 18:10:31.494 I/SyncthingNativeCode(14282): [VBLBO] INFO: Joined relay relay://31.24.30.188:22067
12-20 18:10:40.398 W/InputEventReceiver(14282): Attempted to finish an input event but the input event receiver has already been disposed.
12-20 18:10:50.132 W/InputEventReceiver(14282): Attempted to finish an input event but the input event receiver has already been disposed.
12-20 18:10:59.088 I/Timeline(14282): Timeline: Activity_launch_request time:108319496
12-20 18:11:45.617 W/OpenGLRenderer(14282): cuilf pushLayerUpdate 309 delete mLayer: 0x7f738cdd00, RenderLayer: 0x7f6fa3e800
12-20 18:11:48.274 W/IconCustomizer(14282): can't load transform_config.xml
12-20 18:11:48.376 I/ThemeRuntimeManager(14282): add pending job com.google.android.apps.docs.drive.clipboard.SendTextToClipboardActivity.png
12-20 18:11:48.377 I/ThemeRuntimeManager(14282): saving icon for com.google.android.apps.docs.drive.clipboard.SendTextToClipboardActivity.png
12-20 18:11:48.419 I/ThemeRuntimeManager(14282): add pending job com.xiaomi.midrop.png
12-20 18:11:48.419 I/ThemeRuntimeManager(14282): saving icon for com.xiaomi.midrop.png
12-20 18:11:48.771 W/OpenGLRenderer(14282): cuilf pushLayerUpdate 309 delete mLayer: 0x7f7384ba00, RenderLayer: 0x7f6cc77400
12-20 18:11:49.059 W/OpenGLRenderer(14282): cuilf destroyHardwareResources 545 RenderNode: 0x7f6fa3e800, layer: 0x7f738cdd00
12-20 18:11:52.706 W/OpenGLRenderer(14282): cuilf pushLayerUpdate 309 delete mLayer: 0x7f73d8c100, RenderLayer: 0x7f6ccc3800
12-20 18:11:53.007 W/OpenGLRenderer(14282): cuilf destroyHardwareResources 545 RenderNode: 0x7f6cc77400, layer: 0x7f73951000
12-20 18:11:55.775 I/Timeline(14282): Timeline: Activity_launch_request time:108376184
12-20 18:11:56.318 W/OpenGLRenderer(14282): cuilf destroyHardwareResources 545 RenderNode: 0x7f6ccc3800, layer: 0x7f6cca8300
12-20 18:12:07.748 W/IInputConnectionWrapper(14282): finishComposingText on inactive InputConnection
12-20 18:12:07.766 W/IInputConnectionWrapper(14282): finishComposingText on inactive InputConnection
12-20 18:12:11.009 W/IInputConnectionWrapper(14282): finishComposingText on inactive InputConnection
12-20 18:12:11.043 W/IInputConnectionWrapper(14282): finishComposingText on inactive InputConnection
12-20 18:12:21.697 I/Timeline(14282): Timeline: Activity_launch_request time:108402105
12-20 18:12:23.200 W/OpenGLRenderer(14282): cuilf pushLayerUpdate 309 delete mLayer: 0x7f6cce8b00, RenderLayer: 0x7f73ffc000```

Xiaomi Mi5s+, MIUI9 latest version on 2017/12

**Comment by Nutomic** [comment]
@dromanov Does the web gui show any errors?

**Comment by dromanov** [comment]
Yes, and it even explains it :-)
Screenshots are here: [https://www.evernote.com/shard/s171/sh/4c499545-678c-466f-bfe3-66b97d88d15a/b97fc1f67b24db22c01cb52a6a834ca0](https://www.evernote.com/shard/s171/sh/4c499545-678c-466f-bfe3-66b97d88d15a/b97fc1f67b24db22c01cb52a6a834ca0)

**Comment by jebeld17** [comment]
I'm continuing to get this same problem even on 0.10.3.

**Comment by Catfriend1** [comment]
I will need this later :
06-01 20:27:44.140 V/EventProcessor(30163): Ignored event StateChanged, data {duration=67.297718371, error=folder marker missing, folder=tuug3-pwvn6, from=idle, to=error}

**Comment by leandrofranca** [comment]
I was having the same problem and I resolved deleting the folders (app) and restarting syncthing-android. After the restart, all folders will be added automatically in the application. You will be prompted for each folder path.
