### ISSUE TITLE
Notifications don't work on latest beta

### ISSUE THREAD

**Issue by Phantop** [syncthing/syncthing-android#966]
As the title says, the activity notifications for Syncthing stopped working, not appearing at all. This happened at the same time the update came, so there is clearly some bug.

### Version Information

    App Version: v0.9.15
    Syncthing Version: v0.14.39-rc1
    Android Version: Android 8.0.0 Pixel

**Comment by Nutomic** [comment]
What settings are you using for notifications and run conditions? Steps to reproduce?

**Comment by Phantop** [comment]
Syncthing is set to run in background. None of the notification options work correctly, Normal nor Low Priority, and the active notification when in the app with backgrounding enabled isn't appearing either.

**Comment by Nutomic** [comment]
Hmm I still can't reproduce it, but maybe that will fix it.

**Comment by yacoob** [comment]
I see the same behaviour. No syncthing notification, there's however android's generic "Syncthing is running in the background" notification. This happens regardless of the selected notification option.

syncthing version: 0.14.39
app version: 0.9.16
android version: 8.0.0

I believe this has started to happen past 8.0 upgrade.

![screenshot_20171017-215755](https://user-images.githubusercontent.com/190463/31689311-ef52584c-b386-11e7-9c74-c7d93dbfb66d.png)

**Comment by Nutomic** [comment]
Apparently this is a new "feature" in Android 8:

https://www.androidauthority.com/annoyed-running-background-notification-oreo-798941/

**Comment by Phantop** [comment]
There's no reason for this to be reclassified. I've been on 8.0 for weeks before this showed up. Has the attempt at fixing this been rolled out?

**Comment by Nutomic** [comment]
We've changed the app to target Android 8 (it was still targeting Android 7 previously). So it's not running in compatibility mode any more. There is no way to change this back.

**Comment by fti7** [comment]
Same here. I switched to an Pixel 2 with Android 8.0. There are no Notifications anymore.
The "Syncthing is Running" and the "New Device/Folder" Dialogs will not appear :-(

**Comment by sqrt-1764** [comment]
From API 26 notifications have to be create with a notifiction-channel. Otherwise the notifications won't be shown any more:
https://developer.android.com/about/versions/oreo/android-8.0.html#notifications

In the Apps-Section of the Developer-Settings there is a setting for toasts when an app on Oreo doesn't use notification-channels. Enabling this I get from Syncthing:

Developer Warning:
Failed to post notification on channel "null"

So this is an issue here.

**Comment by fti7** [comment]
@Nutomic works like a charm.
But allthought you set the persistentChannel to NotificationManager.IMPORTANCE_MIN, on my phone its not shown in the Shade. Just look like a regular Notification (Including shown on the Lockscreen).
Im Running Android O 8.1. And i have an other App (LightFlow) which Notification is shown the the Shade. So it doesnt directly look like an Android Issue.

**Comment by yacoob** [comment]
Same here: the notification used to be low priority and only shown on the list, now it's permanently visible in the top bar.

**Comment by wweich** [comment]
No problem here with Stock Android 8.0 on Pixel.

**Comment by Phantop** [comment]
For those having trouble with the priority: use Android O's notification level feature by holding the notification and going to more settings for it. There, you can set it to minimum. It isn't the right way (probably) but it should work well enough for now.

**Comment by fti7** [comment]
Thx. That worked and its moved to the Shaded section. It was "Mid" not "Low". Looks like there is something wrong in the Code.

**Comment by Nutomic** [comment]
Nothing wrong, you just have to reconfigure because it's not porting any old settings.

**Comment by yacoob** [comment]
Well, not necessarily. Previously that notification was low priority by default. Looking at the change linked from this bug, it should be low priority here as well, but it isn't.

**Comment by yacoob** [comment]
I think this is not fixed - just ended up in situation where I got both Syncthing's and Android's notification. See the attached screenshot. I can provide more information, if you tell me what you'd like to see.
![screenshot_20171208-082614](https://user-images.githubusercontent.com/190463/33852448-914adaa6-deb2-11e7-8555-cc2f5f41827a.png)
