### ISSUE TITLE
Failed to create syncthing config¸check the logs

### ISSUE THREAD

**Issue by antonellosalis** [syncthing/syncthing-android#967]
On startup ST crashes: Failed to create syncthing config¸check the logs

on Lenovo A6020
ANDROID 5.1.1
version: 0.9.14
With both version Playstore and F-Droid

**Comment by AudriusButkevicius** [comment]
Did you what the error message suggests?

**Comment by antonellosalis** [comment]
no, cannot check the logs.

**Comment by Nutomic** [comment]
Why not?

**Comment by Catfriend1** [comment]
I also noticed some irregular crashes with the cannot create config error being on 0.9.x. Haven't had one for months with my config taken over and over from version to version. I assume this can be closed.
@antonellosalis : Android 5.x is pretty old. So if it is still a problem with 0.10.8 (recent version), please get the logs.
