### ISSUE TITLE
problem using webaccess without SSL

### ISSUE THREAD

**Issue by Mannshoch** [syncthing/syncthing-android#971]
If I deactivate TLS connection (need REST access, don't work with ssl) the access to web surface don't work anymore. If I export the config, edit the XML and remove `<tls>true</tls>` then the Webinterface work but I'm not anymore able to add devices with normal android surface.

**Comment by AudriusButkevicius** [comment]
Rest access works fine with TLS you just need to disable certificate checking in your client.

**Comment by Mannshoch** [comment]
Yes, I know. But I'm not able to get how to do it now and while I try to get how-to I stumbled-upon this error.

**Comment by AudriusButkevicius** [comment]
This is just a configuration error that you've caused. Same like if you pointed syncthing to an invalid directory for its database - it wouldn't work.

**Comment by Mannshoch** [comment]
But If that shouldn't be possible to use syncthing on Android without ssl then you should remove the possibility to deactivate ssl. Other way you should setup Syncthing-Android-surface that way that it also work without active ssl.

**Comment by AudriusButkevicius** [comment]
Well it uses the same code as the desktop version, so we are not going to remove options just to prevent you from shooting yourself in the foot. Most users don't fiddle with it, given you broke it, you own it.

**Comment by Mannshoch** [comment]
Why should that be a "shooting in the food" I know where is the problem, I know how to solve it. I thought to be nice and tell you about the error.

Shouldn't the Web site be a kind of Template?. I would say, remove the entry in the Menu or add an Information about the SSL on android.

**Comment by AudriusButkevicius** [comment]
It's not, it's literally the same application

**Comment by Mannshoch** [comment]
OK. Then you may should add an ssl Option to the Android surface into settings. This setting could steer the connection from the app to Syncthing and also the settings in Syncthing.

**Comment by Nutomic** [comment]
SSL is enabled as a security feature, otherwise every other app on your phone could intercept the traffic to read your api key/password, and access everything syncthing has access to. We used to have a setting for SSL in the app, but it was removed for this reason.

Besides, every browser should have an option to allow self-signed certificates.
