### ISSUE TITLE
Confusing behaviour when phone is in energy saving mode

### ISSUE THREAD

**Issue by nekr0z** [syncthing/syncthing-android#973]
Steps to reproduce:

1. Have the phone running in energy saving mode (available on stock android, activates when battery is low, can be activated manually).
2. Don't enable energy saving override for syncthing.
3. Don't have run conditions "run in background" set.
4. Run Syncthing.

What happens:
A notification is displayed that syncthing is not running. Options are to change settings or quit. If change settings option is chosen, settings menu with run conditions is displayed. In fact, Syncthing behaves as if run conditions were set and not currently met.

What should happen:
I'm not sure whether Syncthing shoud run regardless, maybe it's a good thing it refuses to run while phone user is supposedly trying to save battery. But in that case, a more informative notification would be welcome, as in "Syncthing is stopped to save your battery. Disable battery saving mode to continue."

### Version Information

    App Version: 0.9.17 - from Google Play
    Syncthing Version: v0.14.39
    Android Version: Android 8.0.0 - stock, non-rooted, Nexus 6P

**Comment by Nutomic** [comment]
So this is basically the same as #729 (or very similar). The question is, how should that information be displayed? And of course someone needs to implement it.

Also I don't think this should only be used when run in background is active, see #549.

**Comment by nekr0z** [comment]
Yes, pretty much. My main point here is that in this here case there's a particular reason Syncthing can't be run (e.g. system-wide battery saver active). The current behaviour implies that whatever reason there is for Synchting to not be running can be fixed by going to "run conditions" settings. Well, this particular reason can't be fixed there.

It's not that much the behaviour/functionality that is wrong here, it's that UX/UI is confusing.

**Comment by Nutomic** [comment]
But it can be fixed by disabling the battery saving option in Syncthing settings.

**Comment by nekr0z** [comment]
Yes, indeed, I've missed that. Sorry for raising. :)
