### ISSUE TITLE
Syncthing keeps crashing on Android 8

### ISSUE THREAD

**Issue by nekr0z** [syncthing/syncthing-android#974]
Not sure whether it's still #972 not properly fixed or another thing altogether.

I have Syncthing set up so that it loads directly in WebGUI. As soon as I press the "back arrow" button in upper left corner to exit WebGUI mode, app crashes.

[Logcat output](https://gist.github.com/nekr0z/3f38797d53ff9073456d3bfb71e4cc33)

### Version Information

    App Version: 0.9.17 - from Google Play
    Syncthing Version: v0.14.39
    Android Version: Android 8.0.0 - stock Nexus 6P

**Comment by Nutomic** [comment]
Yes this is the same error. Are you sure the log is from version 0.9.17? Because there are no reports for this on Google Play, and I can't reproduce it in the emulator. Maybe try restarting your device?

**Comment by nekr0z** [comment]
Yes, I'm sure it's 0.9.17. Even more: sometimes it works as intended, sometimes it crashes. #972 was very reproducable, this one not that much. I'll keep testing to catch this.

**Comment by nekr0z** [comment]
Tested through and through, can not reproduce any longer. Maybe the update didn't go all the way at the time I was logging this, since I'm totally sure it said 0.9.17 already. Closing anyway.
