### ISSUE TITLE
Remote Control by Broadcast Intents is broken

### ISSUE THREAD

**Issue by sqrt-1764** [syncthing/syncthing-android#976]
### Version Information
    App Version: 0.9.17
    Android Version: Android 8.0

When trying to start Syncthing by intent nothing happens (Syncthing is not started). In logcat the following is generated:
"Background execution not allowed: receiving Intent { act=com.nutomic.syncthingandroid.action.START flg=0x10 } to com.nutomic.syncthingandroid/.receiver.AppConfigReceiver"

This feature was working before in the exact same situation. Also checked that "Always run in Background" is still disabled.

The same holds if I try to stop a running Synthing instance by intent.

**Comment by Nutomic** [comment]
Ah, I forgot to fix that in the last release. It should be working now, but for some reason I can't test it in the emulator.
