### ISSUE TITLE
Run only when charging only works when battery is not full

### ISSUE THREAD

**Issue by samueltardieu** [syncthing/syncthing-android#979]
Contrary to what others seem to experience with Android 8.0, I have no problems with "run only when charging" + "run only on WiFi".

However, when the phone is plugged in but not charging because the battery is full already, Syncthing refuses to start, possibly because it is not technically "charging" (it is "charged") at this stage.

### Version Information

    App Version: 0.9.17
    Syncthing Version: v0.14.39
    Android Version: Android 8.0 / Nexus 5X

**Comment by Nutomic** [comment]
Are you sure it's not [this issue](https://forum.syncthing.net/t/charging-only-run-condition-is-no-longer-working-as-expected/10772)? Can you try if the latest beta release fixes the problem?

**Comment by DarkMio** [comment]
I've got the same issue but cannot find the beta apk. Travis seems to have no (public) binaries or I just missed it. I'd be happy to try, as I am currently in the transition of changing a few syncthing clients out.

**Comment by Nutomic** [comment]
I just released the final 0.10.0, so you should get that soon from Google Play.

**Comment by DarkMio** [comment]
I've updated to the most recent version and still run into issues. All the run conditions work, except "Run only on Wifi" and wifi restrictions. I am currently in a WPA2-PSK network with multiple Cisco beacons.

- App Version:: 0.10.0
- Android Version: Android 8.1
- Phone: Nexus 5X

**Comment by Nutomic** [comment]
@DarkMio Please post more information, like steps to reproduce and logs.

**Comment by DarkMio** [comment]
Alright, so I set the conditions:

- Always run in background
- Run only when chargin
- Run only on wifi
- Restrict to certain Wifi networks ([x] WorkWifi, [x] HomeWifi)

As described, it does not start syncthing, here's the log from the last charging plug:

```
11-13 11:49:01.303 I/zygote64( 4521): Explicit concurrent copying GC freed 14955(789KB) AllocSpace objects, 2(104KB) LOS objects, 50% free, 4MB/9MB, paused 79us total 44.629ms
11-13 11:49:01.351 I/zygote64( 4521): Explicit concurrent copying GC freed 12474(579KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 4MB/8MB, paused 77us total 30.334ms
11-13 11:49:01.375 E/StrictMode( 4521): class com.nutomic.syncthingandroid.activities.MainActivity; instances=5; limit=1
11-13 11:49:01.375 E/StrictMode( 4521): android.os.StrictMode$InstanceCountViolation: class com.nutomic.syncthingandroid.activities.MainActivity; instances=5; limit=1
11-13 11:49:01.375 E/StrictMode( 4521): 	at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
11-13 11:49:02.056 I/zygote64( 4521): Deoptimizing void android.support.v4.view.ViewCompat$ViewCompatApi16Impl.postInvalidateOnAnimation(android.view.View) due to JIT inline cache
11-13 11:49:02.151 I/zygote64( 4521): Do full code cache collection, code=249KB, data=165KB
11-13 11:49:02.151 I/zygote64( 4521): After code cache collection, code=230KB, data=132KB
11-13 11:49:04.263 I/zygote64( 4521): Explicit concurrent copying GC freed 6356(397KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 4MB/9MB, paused 57us total 60.365ms
11-13 11:49:04.305 I/zygote64( 4521): Explicit concurrent copying GC freed 2018(130KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 4MB/9MB, paused 34us total 38.698ms
11-13 11:49:04.312 E/StrictMode( 4521): class com.nutomic.syncthingandroid.activities.MainActivity; instances=6; limit=1
11-13 11:49:04.312 E/StrictMode( 4521): android.os.StrictMode$InstanceCountViolation: class com.nutomic.syncthingandroid.activities.MainActivity; instances=6; limit=1
11-13 11:49:04.312 E/StrictMode( 4521): 	at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
11-13 11:49:23.604 I/Choreographer( 4521): Skipped 40 frames!  The application may be doing too much work on its main thread.
11-13 11:49:25.191 I/zygote64( 4521): Deoptimizing void android.support.v7.widget.AppCompatImageHelper.applySupportImageTint() due to JIT inline cache
11-13 11:49:27.682 I/DeviceStateHolder( 4521): State updated, allowed network connection: true, charging: true, power saving: false
11-13 11:49:27.696 W/DeviceStateHolder( 4521): SSID [<unknown ssid>] unknown or not whitelisted, disallowing sync.
11-13 11:49:27.705 I/DeviceStateHolder( 4521): State updated, allowed network connection: true, charging: true, power saving: false
11-13 11:49:27.707 W/DeviceStateHolder( 4521): SSID [<unknown ssid>] unknown or not whitelisted, disallowing sync.
11-13 11:49:27.708 I/DeviceStateHolder( 4521): State updated, allowed network connection: true, charging: true, power saving: false
11-13 11:49:27.709 W/DeviceStateHolder( 4521): SSID [<unknown ssid>] unknown or not whitelisted, disallowing sync.
11-13 11:49:27.709 I/DeviceStateHolder( 4521): State updated, allowed network connection: true, charging: true, power saving: false
11-13 11:49:27.710 W/DeviceStateHolder( 4521): SSID [<unknown ssid>] unknown or not whitelisted, disallowing sync.
11-13 11:49:31.511 I/zygote64( 4521): Do partial code cache collection, code=237KB, data=142KB
11-13 11:49:31.512 I/zygote64( 4521): After code cache collection, code=235KB, data=142KB
11-13 11:49:31.512 I/zygote64( 4521): Increasing code cache capacity to 1024KB
11-13 11:49:33.324 I/zygote64( 4521): Explicit concurrent copying GC freed 10525(830KB) AllocSpace objects, 2(40KB) LOS objects, 49% free, 5MB/10MB, paused 59us total 63.349ms
11-13 11:49:33.376 I/zygote64( 4521): Explicit concurrent copying GC freed 4559(257KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5MB/10MB, paused 31us total 35.310ms
11-13 11:49:33.393 W/InputEventReceiver( 4521): Attempted to finish an input event but the input event receiver has already been disposed.
11-13 11:49:34.404 I/zygote64( 4521): Explicit concurrent copying GC freed 700(51KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5MB/10MB, paused 75us total 46.859ms
11-13 11:49:34.441 I/zygote64( 4521): Explicit concurrent copying GC freed 1176(96KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5MB/10MB, paused 36us total 34.744ms
11-13 11:49:34.449 E/StrictMode( 4521): class com.nutomic.syncthingandroid.activities.SettingsActivity; instances=2; limit=1
11-13 11:49:34.449 E/StrictMode( 4521): android.os.StrictMode$InstanceCountViolation: class com.nutomic.syncthingandroid.activities.SettingsActivity; instances=2; limit=1
11-13 11:49:34.449 E/StrictMode( 4521): 	at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
11-13 11:49:39.840 I/zygote64( 4521): Explicit concurrent copying GC freed 7613(508KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 5MB/10MB, paused 73us total 59.285ms
11-13 11:49:39.886 I/zygote64( 4521): Explicit concurrent copying GC freed 2397(142KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5MB/10MB, paused 33us total 39.306ms
11-13 11:49:39.894 E/StrictMode( 4521): class com.nutomic.syncthingandroid.activities.MainActivity; instances=7; limit=1
11-13 11:49:39.894 E/StrictMode( 4521): android.os.StrictMode$InstanceCountViolation: class com.nutomic.syncthingandroid.activities.MainActivity; instances=7; limit=1
11-13 11:49:39.894 E/StrictMode( 4521): 	at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
11-13 11:50:16.798 I/zygote64( 4521): Explicit concurrent copying GC freed 11768(949KB) AllocSpace objects, 10(296KB) LOS objects, 50% free, 5MB/11MB, paused 57us total 61.599ms
11-13 11:50:16.843 I/zygote64( 4521): Explicit concurrent copying GC freed 3357(181KB) AllocSpace objects, 1(28KB) LOS objects, 49% free, 5MB/10MB, paused 29us total 36.767ms
11-13 11:50:16.852 E/StrictMode( 4521): class com.nutomic.syncthingandroid.activities.SettingsActivity; instances=3; limit=1
11-13 11:50:16.852 E/StrictMode( 4521): android.os.StrictMode$InstanceCountViolation: class com.nutomic.syncthingandroid.activities.SettingsActivity; instances=3; limit=1
11-13 11:50:16.852 E/StrictMode( 4521): 	at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
11-13 11:50:20.383 I/DeviceStateHolder( 4521): Listening for network state changes
11-13 11:50:20.387 I/DeviceStateHolder( 4521): Listening to battery state changes
11-13 11:50:20.389 I/DeviceStateHolder( 4521): Listening to power saving changes
11-13 11:50:20.392 I/DeviceStateHolder( 4521): State updated, allowed network connection: true, charging: true, power saving: false
11-13 11:50:20.394 W/DeviceStateHolder( 4521): SSID [<unknown ssid>] unknown or not whitelisted, disallowing sync.
11-13 11:50:20.395 I/DeviceStateHolder( 4521): State updated, allowed network connection: true, charging: true, power saving: false
11-13 11:50:20.397 W/DeviceStateHolder( 4521): SSID [<unknown ssid>] unknown or not whitelisted, disallowing sync.
11-13 11:50:20.397 I/DeviceStateHolder( 4521): State updated, allowed network connection: true, charging: true, power saving: false
11-13 11:50:20.398 W/DeviceStateHolder( 4521): SSID [<unknown ssid>] unknown or not whitelisted, disallowing sync.
11-13 11:50:20.408 I/DeviceStateHolder( 4521): State updated, allowed network connection: true, charging: true, power saving: false
11-13 11:50:20.409 W/DeviceStateHolder( 4521): SSID [<unknown ssid>] unknown or not whitelisted, disallowing sync.
11-13 11:50:20.955 W/InputEventReceiver( 4521): Attempted to finish an input event but the input event receiver has already been disposed.
```

From the looks of it, it's not able to recognise the SSID. The wifi broadcasts SSID, is visible and runs WPA2-PSK. This is probably the same like I run my home-wifi, which I can't test until later this evening.

**Comment by Nutomic** [comment]
ping @capi Can you have a look at this? I haven't done any changes to the whitelist code. Probably the same as #700.

**Comment by capi** [comment]
Can have a look, but I am out-of-the rage of my PC for the upcoming 10 days, hopefully I can fit something in.

**Comment by Nutomic** [comment]
The issue is already quite old, so no hurry ;)

**Comment by Catfriend1** [comment]
@DarkMio @samueltardieu Is this issue still present in the current release? I cannot reproduce it on my device. If so, please post a reproducer and tell me how much percent your battery is charged when the syncthing active/inactive status transitions. Looking at the code, the app respects the STATE_CHARGING and BATTERY_FULL correctly. (Related issue https://github.com/syncthing/syncthing-android/issues/977)

**Comment by DarkMio** [comment]
@Catfriend1 The problem still persists - it isn't about the battery status, but as soon as I enable "Run only on Wifi" and restrict it to certain networks it stops running alltogether.

**Comment by Catfriend1** [comment]
@DarkMio could you please grab some logcat output? Before and after the change would be ideal including your system specs.

**Comment by DarkMio** [comment]
I just want to clarify: This has nothing to do with the charging. I can disable the charging checkbox and still get the same behaviour as soon as I restrict the networks.

Anyhow, here's a dump from logcat with everything that mentions syncthing. My usage was to remove the specific network filter, close the application, reopen it, reenabling the filter, closing it and opening it again.

``04-14 09:52:39.066   754  3635 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nutomic.syncthingandroid/.activities.FirstStartActivity bnds=[435,325][646,568] (has extras)} from uid 10043
04-14 09:52:39.139   754  3686 I ActivityManager: Start proc 4341:com.nutomic.syncthingandroid/u0a113 for activity com.nutomic.syncthingandroid/.activities.FirstStartActivity
04-14 09:52:41.407   754  3688 I ActivityManager: START u0 {cmp=com.nutomic.syncthingandroid/.activities.MainActivity (has extras)} from uid 10113
04-14 09:52:43.657   754  3688 I ActivityManager: START u0 {cmp=com.nutomic.syncthingandroid/.activities.SettingsActivity} from uid 10113
04-14 09:52:43.657   754  3688 W ActivityManager: startActivity called from finishing ActivityRecord{e1d6f8b u0 com.nutomic.syncthingandroid/.activities.MainActivity t3709 f}; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.nutomic.syncthingandroid/.activities.SettingsActivity }
04-14 09:52:53.407   754  3688 I ActivityManager: START u0 {act=.activities.LogActivity cmp=com.nutomic.syncthingandroid/.activities.LogActivity} from uid 10113
04-14 09:53:00.995   754  1523 I ActivityManager: START u0 {act=.activities.LogActivity cmp=com.nutomic.syncthingandroid/.activities.LogActivity} from uid 10113
04-14 09:53:06.151   754  1523 I ActivityManager: START u0 {act=.activities.LogActivity cmp=com.nutomic.syncthingandroid/.activities.LogActivity} from uid 10113
04-14 09:53:11.108   754   771 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nutomic.syncthingandroid/.activities.FirstStartActivity bnds=[435,325][646,568] (has extras)} from uid 10043
04-14 09:53:11.383   754   772 I ActivityManager: START u0 {cmp=com.nutomic.syncthingandroid/.activities.MainActivity (has extras)} from uid 10113
04-14 09:53:13.032   754   771 I ActivityManager: START u0 {cmp=com.nutomic.syncthingandroid/.activities.SettingsActivity} from uid 10113
04-14 09:53:13.033   754   771 W ActivityManager: startActivity called from finishing ActivityRecord{a64e31e u0 com.nutomic.syncthingandroid/.activities.MainActivity t3711 f}; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.nutomic.syncthingandroid/.activities.SettingsActivity }
04-14 09:53:14.050  4341  4341 E StrictMode: class com.nutomic.syncthingandroid.activities.MainActivity; instances=2; limit=1
04-14 09:53:14.050  4341  4341 E StrictMode: android.os.StrictMode$InstanceCountViolation: class com.nutomic.syncthingandroid.activities.MainActivity; instances=2; limit=1
04-14 09:53:16.375   754  1347 I ActivityManager: START u0 {act=.activities.LogActivity cmp=com.nutomic.syncthingandroid/.activities.LogActivity} from uid 10113
04-14 09:53:22.572   754   771 I ActivityManager: START u0 {cmp=com.nutomic.syncthingandroid/.activities.SettingsActivity} from uid 10113
04-14 09:53:22.760  4341  4341 E StrictMode: class com.nutomic.syncthingandroid.activities.SettingsActivity; instances=2; limit=1
04-14 09:53:22.760  4341  4341 E StrictMode: android.os.StrictMode$InstanceCountViolation: class com.nutomic.syncthingandroid.activities.SettingsActivity; instances=2; limit=1
04-14 09:54:56.061  4341  4341 E StrictMode: class com.nutomic.syncthingandroid.activities.SettingsActivity; instances=3; limit=1
04-14 09:54:56.061  4341  4341 E StrictMode: android.os.StrictMode$InstanceCountViolation: class com.nutomic.syncthingandroid.activities.SettingsActivity; instances=3; limit=1
04-14 09:56:21.420   754  3884 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nutomic.syncthingandroid/.activities.FirstStartActivity bnds=[435,325][646,568] (has extras)} from uid 10043
04-14 09:56:21.478   754  1347 I ActivityManager: START u0 {cmp=com.nutomic.syncthingandroid/.activities.MainActivity (has extras)} from uid 10113
04-14 09:56:21.665   428   428 D SurfaceFlinger: duplicate layer name: changing com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.MainActivity to com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.MainActivity#1
04-14 09:56:21.745   754   789 I ActivityManager: Displayed com.nutomic.syncthingandroid/.activities.MainActivity: +237ms (total +297ms)
04-14 09:56:23.145   754   771 I ActivityManager: START u0 {cmp=com.nutomic.syncthingandroid/.activities.SettingsActivity} from uid 10113
04-14 09:56:23.146   754   771 W ActivityManager: startActivity called from finishing ActivityRecord{db2fe38 u0 com.nutomic.syncthingandroid/.activities.MainActivity t3714 f}; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { cmp=com.nutomic.syncthingandroid/.activities.SettingsActivity }
04-14 09:56:23.361   754   789 I ActivityManager: Displayed com.nutomic.syncthingandroid/.activities.SettingsActivity: +140ms
04-14 09:56:24.140  4341  4341 E StrictMode: class com.nutomic.syncthingandroid.activities.MainActivity; instances=3; limit=1
04-14 09:56:24.140  4341  4341 E StrictMode: android.os.StrictMode$InstanceCountViolation: class com.nutomic.syncthingandroid.activities.MainActivity; instances=3; limit=1
04-14 09:56:28.357   428   428 D SurfaceFlinger: duplicate layer name: changing com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.SettingsActivity to com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.SettingsActivity#1
04-14 09:56:31.796  4341  4341 I SyncthingService: Starting syncthing according to current state and preferences
04-14 09:56:31.810  4341  9866 D ConfigXml: Trying to read '/data/user/0/com.nutomic.syncthingandroid/files/config.xml'
04-14 09:56:31.947  9879  9879 W chmod   : type=1400 audit(0.0:101): avc: denied { setattr } for name="libsyncthing.so" dev="dm-2" ino=351859 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:apk_data_file:s0 tclass=file permissive=0
04-14 09:56:32.181  4341  9883 I SyncthingNativeCode: [TIEFB] INFO: syncthing v0.14.45+1-gbf165d68 "Dysprosium Dragonfly" (go1.9.4 android-arm64) felix@p50 2018-03-13 18:08:09 UTC [noupgrade]
04-14 09:56:33.047  4341  9885 I SyncthingRunnableIoNice: ionice performed on libsyncthing.so
04-14 09:56:34.173  4341  9883 I SyncthingNativeCode: [TIEFB] INFO: Device 7LM26VD-WS3NUV5-YHVE466-AU5OMRA-IHQS7YB-YHV53S3-67XCLFN-TARZ3Q4 client is "syncthing v0.14.43" named "raspberrypi" at 192.168.0.101:41827-192.168.0.3:22000/tcp-client
04-14 09:56:34.176   428   428 D SurfaceFlinger: duplicate layer name: changing com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.SettingsActivity to com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.SettingsActivity#1
04-14 09:56:38.740   754   772 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nutomic.syncthingandroid/.activities.FirstStartActivity bnds=[435,325][646,568] (has extras)} from uid 10043
04-14 09:56:38.797   754  3626 I ActivityManager: START u0 {cmp=com.nutomic.syncthingandroid/.activities.MainActivity (has extras)} from uid 10113
04-14 09:56:39.007   754   789 I ActivityManager: Displayed com.nutomic.syncthingandroid/.activities.MainActivity: +164ms (total +217ms)
04-14 09:56:43.917  4341  4341 I chatty  : uid=10113(com.nutomic.syncthingandroid) identical 1 line
04-14 09:56:46.018   754  6383 I ActivityManager: START u0 {cmp=com.nutomic.syncthingandroid/.activities.SettingsActivity} from uid 10113
04-14 09:56:46.203   754   789 I ActivityManager: Displayed com.nutomic.syncthingandroid/.activities.SettingsActivity: +161ms
04-14 09:56:50.382   428   428 D SurfaceFlinger: duplicate layer name: changing com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.SettingsActivity to com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.SettingsActivity#1
04-14 09:57:00.135  4341  4341 I SyncthingService: Stopping syncthing according to current state and preferences
04-14 09:57:04.020  4341  4341 E StrictMode: class com.nutomic.syncthingandroid.activities.MainActivity; instances=4; limit=1
04-14 09:57:04.020  4341  4341 E StrictMode: android.os.StrictMode$InstanceCountViolation: class com.nutomic.syncthingandroid.activities.MainActivity; instances=4; limit=1
04-14 09:57:04.183   754  3635 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nutomic.syncthingandroid/.activities.FirstStartActivity bnds=[435,325][646,568] (has extras)} from uid 10043
04-14 09:57:04.216   754  6384 I ActivityManager: START u0 {cmp=com.nutomic.syncthingandroid/.activities.MainActivity (has extras)} from uid 10113
04-14 09:57:04.387   428   428 D SurfaceFlinger: duplicate layer name: changing com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.MainActivity to com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.MainActivity#1
04-14 09:57:04.456   754   789 I ActivityManager: Displayed com.nutomic.syncthingandroid/.activities.MainActivity: +204ms (total +252ms)
``

**Comment by Catfriend1** [comment]
@DarkMio Thanks for reporting back. So this issue can be closed.
