### ISSUE TITLE
Featurerequest: broadcast-api to inform other apps/plugins that syncthing has added/moved/deleted/modified a file

### ISSUE THREAD

**Issue by k3b** [syncthing/syncthing-android#983]
I want to use syncthing to sync jpg images between android device and pc. Images. On the android side are managed by the android-buildin-mediadatabase.

I want to build a simple app that triggers the media scanner to update infos in media database ( https://github.com/k3b/APhotoManager/issues/101 ) . So whenever jpg images are added/moved/deleted/modified via syncthing the media database update is triggered, too.

Is it possible to extend syncthing-android to send a broadcast after finishing add/move/delete/modify of files?

**Comment by Nutomic** [comment]
Are you referring to the Android media scanner? This should already be updated when new files are received ([source link](https://github.com/syncthing/syncthing-android/blob/master/src/main/java/com/nutomic/syncthingandroid/service/EventProcessor.java#L150)), but maybe it's not working correctly?

**Comment by k3b** [comment]
thanks for the info. up to now i was not aware that android already has a broadcast for https://developer.android.com/reference/android/content/Intent.html#ACTION_MEDIA_SCANNER_SCAN_FILE . 

When playing with syncthing on my android-4.4 i realized that the new file appeared in the media db but the old was not removed.

Is the code for `case "ItemFinished":` also called when syncthing deletes a file (because the file was deleted/moved/renamed on the other side)? if so i assume that my android-4.4 does not implement "delete from media db if not found". The api doc only states "add it(the scanned file) to the media database"

I already have implemented my own media scanner to parse jpg-iptc/xmp-data, too. creating my own broadcastlistener for `ACTION_MEDIA_SCANNER_SCAN_FILE` will allow me to trigger my own scanner.

**Comment by Nutomic** [comment]
There is no event for ItemDeleted, so i presume the same event is used for item deletes. But I think the deletion is implemented incorrectly, it should use this method: https://stackoverflow.com/questions/29875744/deleted-file-resurrects-after-action-media-scanner-scan-file-intent

Will try to fix that when I have time.

**Comment by k3b** [comment]
When you handle delete from media-db in syncthing there is no more need to do it on my side.

note on delete from media-db:

if you use 

* `Uri contentUri = MediaStore.Files.getContentUri("external")` 
* instead of `Uri contentUri = MediaStore.Images.Media.getContentUri("external");` 

the delete code will work for all media types (image, video, audio) in one call.
