### ISSUE TITLE
"Syncthing is running" when it is actually not.

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#984]
Recent update introduced a bug: "Syncthing is running" notification, which previously was only visible when Wi-Fi is connected (because of Syncthing is configured to run only on Wi-Fi) is now visible always. Clicking on it opens Syncthing with message like "Syncthing is not configured to run now. [Settings] [Exit]".

Also I see "Syncthing has crashed" (or "force stopped" or like that) messages here and there (with Wi-Fi off), but haven't investigated it further.

### Version Information

    App Version: 0.9.17
    Syncthing Version: v0.14.39
    Android Version: Android 4.4

**Comment by Nutomic** [comment]
See #981
