### ISSUE TITLE
Android Syncthing App only using Google's 8.8.8.8 DNS server. Cannot resolve names on local LAN

### ISSUE THREAD

**Issue by Joeviocoe** [syncthing/syncthing-android#986]
There must be something hardcoded in the Android app 0.9.17 (I am running Android 8.0.0).
When any peer is configured with a host name instead of an IP, the DNS Lookup goes to 8.8.8.8 udp/53 (checked with tcpdump on my router).
My Router hands out the OpenDNS servers via DHCP, and even when my Android is not on my local wifi, and on LTE, it gets my Carrier's DNS. There should not be anything in my phone telling apps to resolve using 8.8.8.8

**Comment by Nutomic** [comment]
Yes this was the case in versions before 0.10.0, because DNS was not working correctly. However, version 0.10.0 (latest release) should use the system DNS server.

**Comment by Joeviocoe** [comment]
The latest version available on the Google Play store is 0.9.17
When will 0.10.0 release to the Play Store?

Also, inside the Android app, it shows Syncthing Version as 0.14.39

**Comment by Nutomic** [comment]
Sorry you're right, 0.10.0 is not released yet. But you can use [this link](https://play.google.com/apps/testing/com.nutomic.syncthingandroid) to get the beta.
