### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by scienmind** [syncthing/syncthing-android#987]
The phone showed "ST crashed" notification at some point (while being idle).

At the same time "ST is running" low-priority notification was still there as well. I guess only ST binary itself crashed.

So, for what it worth:
Log: https://gist.github.com/anonymous/2b44680d37a8659f0f9985fa64f3c0d0

### Version Information

    App Version: 0.10.0
    Syncthing Version: v0.14.40
    Android Version: Android 7.1

**Comment by AudriusButkevicius** [comment]
I am closing this, as this log doesn't contain anything useful, so there is nothing to be understood from this.

**Comment by imsodin** [comment]
Isn't the real thing to investigate here, why the log is truncated? If the relevant part of the crash was here, it might be useful.

**Comment by AudriusButkevicius** [comment]
I think android doesn't have infinite logs, as android logs to a common system log.
When we dump 10k goroutines, stuff doesn't look good.
