### ISSUE TITLE
Syncthing crashes with missing symbol: sigfillset on Android 4.3

### ISSUE THREAD

**Issue by yurkobb** [syncthing/syncthing-android#991]
1) Install Syncthing from F-Droid
2) Launch
3) Click Continue
4) Asks for root access, grant
5) Syncthing crashes

In the notification area an error message appears with this log entry:

> --------- beginning of /dev/log/main
> CANNOT LINK EXECUTABLE: cannot locate symbol "sigfillset" referenced by "/data/app-lib/com.nutomic.syncthingandroid-1/libsyncthing.so"...
> usage: ionice <pid> [none|rt|be|idle] [prio]

### Version Information

    App Version: 0.10.0-BETA3
    Syncthing Version: v0.14.40
    Android Version: Android 4.3 / Cyanogenmod 10.2

**Comment by krvkir** [comment]
Looks like I'm experiencing the same bug, also on the latest version from F-Droid. I'm on Android 4.2.2.

Syncthing silently crashes, and in the log I've found this:

```
soinfo_relocate(linker.cpp:975): cannot locate symbol "sigfillset" 
referenced by "/data/app-lib/com.nutomic.syncthingandroid-1/libsyncthing.so"
...CANNOT LINK EXECUTABLE
```
(Sorry if there are typos -- I've had to type it in by hands.)

**Comment by Nutomic** [comment]
There was a configuration problem with 0.10.0-beta3. Can you wait and see if the final 0.10.0 release works correctly?

**Comment by yurkobb** [comment]
@Nutomic Thank you for quick reply. Sure, we can wait, however maybe it's a way to test the 0.10.0-beta4 (the latest beta, if I understand it correctly)? Is there a build somewhere?

**Comment by Nutomic** [comment]
You can get it from Google Play, but with a different signing key (so you'd have to reinstall the app). Not sure what happened on F-Droid, beta versions aren't supposed to be released there.

**Comment by yurkobb** [comment]
I'm fine with waiting, but if you think testing beta4 on older Android would make sense before making a release, I could test it if there was an apk somewhere.

**Comment by Nutomic** [comment]
0.10.0 is already released on Google Play, and doesn't seem to cause these crashes. So I don't think more testing is needed.

**Comment by wwwutz** [comment]
Concerning F-Froid downloads: As of today, 28 Nov '17 there seems to be a problem with f-droid builds. The build system is broken and they're still waiting to have it fixed. See https://forum.f-droid.org/t/is-the-f-droid-build-process-currently-broken/195/31

The build fails for all stuff which uses some gradle magic (whatever that means 8-).

**Comment by yurkobb** [comment]
The release has just updated on F-Droid as well. Runs fine now:)
