### ISSUE TITLE
Syncthing not synchronizing completely

### ISSUE THREAD

**Issue by M4R10zM0113R** [syncthing/syncthing-android#992]
[derp.txt](https://github.com/syncthing/syncthing-android/files/1484682/derp.txt)

![screenshot_20171118-084623](https://user-images.githubusercontent.com/3507989/32981631-b19841b8-cc3d-11e7-8085-883632212269.png)
![screenshot_20171118-084802](https://user-images.githubusercontent.com/3507989/32981633-b251c002-cc3d-11e7-89a9-f8fdf2840890.png)

- what happened,
Client doesn't finish synchronizing at all. The process gets stuck at a high percentage (~90-97%) of a big folder (~14.3GiB). Small folders seem to progress and finish (<3GiB).
Only one of 5 devices actually went through with it.
- what you expected to happen instead, and
I expected the program to finish syncing any folder regardless of the size of the Folder.
- any steps to reproduce the problem.
1. Install app to device (from F-droid).
2. Add device (from PC or from Android) mutually (No introducer), just sharing off the Folders and accepting when request appears on the other device(s). PC having the original folder(s).
3. Adding Folders to the new device, all of them with a Simple File Versioning and with different pull orders (Smallest, Random).
4. Wait to sync, getting stuck. Some new files added get synced, others get added to the unresponsive pool.

### Version Information

    App Version: 0.10.0-beta3
    Syncthing Version: v0.14.38 - 0.14.40-rc1
    Android Version: LineageOS 14.1

**Comment by AudriusButkevicius** [comment]
Press the rescan button. There was also a bug fix in the rc that could be related to this. This wouls also happen if you renamed folder or file cases, as that's not handled.

**Comment by Nutomic** [comment]
Just realized that you're running the beta. That version was actually not supposed to be released on F-Droid, no idea what happened there. You should really get the final version, but unfortunate the F-Droid build isn't working.

https://gitlab.com/fdroid/fdroiddata/issues/995

**Comment by M4R10zM0113R** [comment]
I just went on and deleted some files in question, solving the issue with the sync.
