### ISSUE TITLE
Android mobile data - not working at all

### ISSUE THREAD

**Issue by chicagobuss** [syncthing/syncthing-android#993]
I get 0/8 announce servers, log just says "detected 0 nat servers", run conditions is to always run in background with no other restrictions.

All other apps on the phone work fine on mobile data.  App works fine on wifi. What's going on?

### Version Information

    App Version: 0.14.40
    Syncthing Version: v0.14.40
    Android Version: Android 6.0.1 Cyanogenmod 13

**Comment by Nutomic** [comment]
If you click on the "Discovery" value in the web gui, it will show the errors.

**Comment by Catfriend1** [comment]
Closed due to lack of answer.
