### ISSUE TITLE
Syncthing on F-Droid: Abandon ship?

### ISSUE THREAD

**Issue by phuyuk** [syncthing/syncthing-android#996]
@Nutomic, in light of ongoing improvements (ahem) at F-Droid, do you recommend users move over to Google Play for updates? 

While this is not an STA 'bug', per se, F-Droid users have not seen a stable build (AKA bug fixes) for nearly two months - nor can they reasonably participate in the bug reporting/resolution process, while still using 0.9.17.

**Comment by licaon-kter** [comment]
It will be updated at the next F-Droid repo update, as it's already build, and awaits signing and publishing.

**Comment by Nutomic** [comment]
Great :)

**Comment by phuyuk** [comment]
Thank you very much for your work. Anyone following recent developments at F-Droid is aware of tbe inordinate pain getting tbis one built and published.
